### ISSUE TITLE
Steam Runner [BUG] 

### ISSUE THREAD

**Issue by kibasnowpaw** [bottlesdevs/Bottles#1007]
After installing Steam in the installing sections and going under program click refresh and then click run on Steam, i get this Error.

```
 (20:04:59) ERROR Executable file path does not exist or is not accessible by the Flatpak: /home/kibasnowpaw/.var/app/com.usebottles.bottles/data/bottles/bottles/test/drive_c/Program Files (x86)/Steam 
(20:04:59) ERROR Unsupported executable type: /home/kibasnowpaw/.var/app/com.usebottles.bottles/data/bottles/bottles/test/drive_c/Program Files (x86)/Steam 
```
And when i check the Folder, then there is a Folder Called Steam there, so i don't know what's happing, if there is an Error in the running scrips or what, but it doesn't work.

**Comment by mirkobrombin** [comment]
Fixed, the manifest was not updated to the new 2022.1.28 structure. To fix just re-install steam using our installer or just setting the executable path from `Program Files (x86)/Steam/` to `Program Files (x86)/Steam/Steam.exe`. 

Thanks for reporting.
