### ISSUE TITLE
[Bug] caffe-7.0 doesn't work on Debian testing

### ISSUE THREAD

**Issue by bestouff** [bottlesdevs/Bottles#1008]
When installing Bottles (from the .deb package) and first running, it should do a basic sanity check and tell if there's no functional `wine` installation.  
Bonus points if it could tell how to install it (e.g. under debian, add WineHQ's repo and install `wine-stable`).
  
I have been hit by this, when it installed a "runner" and other dependencies I thought it was installing Wine itself. The vocabulary used is too complex for the intended audience methinks.

**Comment by mirkobrombin** [comment]
When you run Bottles the first time it will install all the necessaries components and introduce you with the main concepts. How can this be improved?

**Comment by bestouff** [comment]
It does install the necessary component excepted Wine itself. Well, I had to manually install Wine on my Debian system afterwards to make it work, otherwise I had this error:
```
0174:err:module:open_builtin_so_file failed to load .so lib "/home/xav/.local/share/bottles/runners/caffe-7.0/lib32/wine/i386-unix/winex11.drv.so"
0174:err:user:load_desktop_driver failed to load L"winex11.drv"
0174:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0174:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

**Comment by bestouff** [comment]
Ok my bad, after looking into `$HOME/.local/share/bottles/runners/caffe-7.0/` I can see that there's a full Wine install in there. But for some reason I got the aforementioned error and had to manually install.

**Comment by mirkobrombin** [comment]
Maybe the runner doesn’t work in your distribution. Can you try installing the lutris runner from the Preferences and make a new bottle with it?

**Comment by bestouff** [comment]
I desinstalled `wine-stable` from my distro, installed `lutris-6.21-6` from Bottles, changed the existing bottle config to lutris and yes, it worked !
So apparently `caffe-7.0` doesn't work on Debian testing.

**Comment by bestouff** [comment]
Or maybe should I stay on the first topic and Bottles should check its default Wine install works properly, by doing some kind of "hello world" ?

**Comment by mirkobrombin** [comment]
There is an issue about Caffe on debian based distro. It seems not working due to wrong glib version.

**Comment by mirkobrombin** [comment]
Fixed by recent commit. On first start Bottles will check the glibc version to ensure it works with our Caffe runner. If not it will automatically download latest lutris or vaniglia runner.
