### ISSUE TITLE
[BUG] creating a bottle never finishes

### ISSUE THREAD

**Issue by D0nnieD4rk0** [bottlesdevs/Bottles#1009]
im on garuda linux and installed it off the chaotic-aur
i litteraly have done nothing with the software so far cuz i can't create a bottle

**Comment by mirkobrombin** [comment]
Follow the [bug report template](https://github.com/bottlesdevs/Bottles/issues/new?assignees=mirkobrombin&labels=bug&template=bug_report.md&title=%5BBUG%5D+) and give more info please.
