### ISSUE TITLE
[Request] How to run program inside a bottle?

### ISSUE THREAD

**Issue by bastianilso** [bottlesdevs/Bottles#101]
I have created a bottle using a clean environment, opened it and copied a folder onto the C: drive of the bottle. But when I open the "Programs" tab of the bottle, there are no programs listed. Is there some way I can add some manual entries to this list of programs?

**Comment by mirkobrombin** [comment]
The Programs view contains only the detected programs installed in the wineprefix. A search is made for .lnk files in the Start Menu.

Use the "Run .exe" button to exedute.
