### ISSUE TITLE
When pressing bottle virtual desktop shows.

### ISSUE THREAD

**Issue by Sultech** [bottlesdevs/Bottles#1011]
**Describe the bug**
When having virtual desktop enabled and you press a bottle the virtual desktop will show without opening a exe.

**Installation**
 - Method: Flatpak
 - Version 2022.1.28-trento-3

**To Reproduce**
1. Go to prefrences and enable virtual desktop (it also freezes sometimes when enabling)
2. Click on the back button so you can see all of your bottles.
3. Then press the bottle with virtual desktop

**Expected behavior**
When pressing a bottle with virtual desktop enabled it should not show the virtual desktop without opening a app or exe.

**Screenshots**

https://user-images.githubusercontent.com/30802163/152232819-908a8c39-64ce-4ac0-861c-583a23cd3253.mp4

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Bottles is using winedbg to track the processes status. Wine always trigger virtual desktop for cli tools too :S idk we can do something here. Can you disable the virtual desktop?

**Comment by Sultech** [comment]
I can't disable it because I need it for fifa so i can tab out. I normally use lutris but ea desktop works better with bottles.

**Comment by mirkobrombin** [comment]
Nvm I've found a solution

**Comment by mirkobrombin** [comment]
Ok my idea cannot be implemented and I need to find something else. In the meantime can you try this? https://wiki.winehq.org/FAQ#How_do_I_get_Wine_to_launch_an_application_in_a_virtual_desktop.3F

Disable the virtual desktop and from winecfg set the single app to use it.

```
6.6 Configuring
6.6.1 How do I get Wine to launch an application in a virtual desktop?
You can do this with [winecfg](https://wiki.winehq.org/Winecfg). Add the application in the Applications tab and then, in the Graphics tab, enable "Emulate a virtual desktop".

You can also use the following command:

wine explorer /desktop=name,1024x768 program.exe
```

**Comment by Sultech** [comment]
I have tried using winecfg but it does not work.

**Comment by mirkobrombin** [comment]
I've to close as there is no fix for this.
