### ISSUE TITLE
[BUG] Error while opening executable

### ISSUE THREAD

**Issue by SAXN-SYNX** [bottlesdevs/Bottles#1018]
**Describe the bug**
When opening the executable in CLI It shows error.

$ bottles apple.exe
/usr/share/bottles/bottles/dialogs/generic.py:18: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '4') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GtkSource, Gdk, Handy, Pango, WebKit2

**Installation**
 - Method AUR Arch linux
 -  Git package

**Screenshots**
https://i.imgur.com/pTeiY7b.png

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 2022.1.28
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting.
This should already be fixed by https://github.com/bottlesdevs/Bottles/commit/ced821b66952757b7adbed459c0bf3479b9b4d0c

Will be released with next release.
