### ISSUE TITLE
[BUG] Fox Weiqi not detected in Programs tab

### ISSUE THREAD

**Issue by petete1** [bottlesdevs/Bottles#1019]
Fox Weiqi (a client to play Go online) isn't detected in the programs tab.
It installs it's shortcut (Fox Go Server.lnk) only on the Desktop.
You can find the installer here: https://www.foxwq.com/Public/Soft/install.exe

Maybe it's possible to monitor the desktop folder for shortcuts, being careful not to show duplicate entries.

**Comment by mirkobrombin** [comment]
Bottles already look in user/you/Desktop path for .lnk entries but these are skipped if it is not possible to parse its content. We are looking for another way to handle these files.
