### ISSUE TITLE
[Request] Ability to reinstall grayed-out "core" dependencies

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#1020]
**Is your feature request related to a problem? Please describe.**
The bottle can break and require reinstallation of core dependencies. Current GUI doesn't allow the user to fix this.

Here's an example:

- I used the https://github.com/HereInPlainSight/gshade_installer script to install GShade (a version of ReShade) into the Bottle.
- This corrupted the system's d3dcompiler_47.dll for some reason. I was getting this error constantly: `0304:err:module:import_dll Loading library D3DCOMPILER_47.dll (which is needed by L"C:\\Program Files (x86)\\Zenimax Online\\The Elder Scrolls Online\\game\\client\\eso64.exe") failed (error c000007b).`
- I have no idea how it corrupted the system. I read their script, all it does is put d3dcompiler in the game folder and register the dlloverride.
- I tried deleting the d3dcompiler file their script puts in the game folder. Still, didn't fix the issue.

My final solution:

```sh
cd ~/.var/app/com.usebottles.bottles/data/bottles/bottles/Gaming/
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
WINEPREFIX="$(pwd)" ./winetricks
```

Then I used it to install `d3dcompiler_47` and now my prefix/bottle is repaired.

**Describe the solution you'd like**
How about this: If user clicks "..." menu of `Bottles > Dependencies > d3dcompiler_47` it has an option "Re-install" which runs the install scripts again?

**Describe alternatives you've considered**
I was able to use Winetricks manually to repair the bottle, but it would be nice to be able to fix this situation with Bottles GUI. What do you think about it?

**Comment by mirkobrombin** [comment]
Next time just remove the dependency from your bottle.yml. Avoid using winetricks in Bottles as it breaks the dependency tree.

**Comment by Bananaman** [comment]
> Next time just remove the dependency from your bottle.yml.

Oh that's smart, thanks for the tip!

> Avoid using winetricks in Bottles as it breaks the dependency tree.

Yeah, I guess you mean because Bottles doesn't know that it has installed this dependency. I just used it to repair this file. But I noticed something weird actually. Winetricks adds `*d3dcompiler_47` to the top of winecfg - Libraries, and Bottles adds `d3dcompiler_47`. Difference is the `*`. I have no idea why winetricks adds the library with `*` at the start of the name.

> Btw I’m going to implement this

Yayyy great. Your GUI is much better than winetricks so I respect that you made your own dependency system! :)

**Comment by mirkobrombin** [comment]
> But I noticed something weird actually. Winetricks adds *d3dcompiler_47 to the top of winecfg - Libraries, and Bottles adds d3dcompiler_47. Difference is the *. I have no idea why winetricks adds the library with * at the start of the name.

I think it's a pattern, maybe they install more data? Idk.

**Comment by Bananaman** [comment]
@mirkobrombin Yeah I found out what it means. It's a pattern.

Winetricks adds names with the pattern asterisk like `*d3d9.dll` just to let people know that Winetricks added it. It's nothing special.

https://forum.winehq.org/viewtopic.php?f=2&t=10925

And I see the Reinstall feature in the menus and tried it out. Works well. Thanks a lot Mirko! :) :heart:

**Comment by Bananaman** [comment]
@mirkobrombin For your info (can be useful), I found the exact code where Winetricks generates all of its DLL registrations. It uses the pattern `*${module}` to always put a `*` before the name. So yeah mystery is solved:

https://github.com/Winetricks/winetricks/blob/d431b15fa55667217571a791074dc3eb69155dfc/src/winetricks#L2115-L2122

**Comment by mirkobrombin** [comment]
Makes sense
