### ISSUE TITLE
[BUG] Scrivener License Activation fails with default 'Software' Bottle incl. workaround

### ISSUE THREAD

**Issue by akdean** [bottlesdevs/Bottles#1023]
**Describe the bug**
Scrivener, the software, works fine in Bottles/Wine, however the activation component presents issues. 

When Scrivener is installed using the 'Software' template, I was unable to get the activation manager to work correctly (uses a tool called Paddle that talks out to a license server,) however, with a custom bottle I was able to enter my license and get the appropriate response from the server.

Basically, the "bug" is that I had to use a custom bottle, install Scrivener, then install dotnet462 before I could activate the license. 

**Installation**
 - Method: Flatpak & Fedora RPM
 - Version: 2022.1.28-trento-4 (Flatpak)

**To Reproduce**
1. Install Scrivener in a Software bottle.
2. Attempt to activate license.
3. Watch it get stuck in a loop.
4. Play around with .net installs for a while. 
5. Eventually reinstall in a "Custom" bottle and install dotnet462.
6. Activate license successfully.

**Expected behavior**
The Software bottle should allow activation of the license, I'm not sure what combination of factors makes it fail in this case.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34
 - Display server: Wayland (fallback to Xwayland for legacy apps)

**Additional context**
N/A

**Comment by mirkobrombin** [comment]
Our Application environment does not install dotnet but mono https://github.com/bottlesdevs/Bottles/blob/26ccca93c7d664ce54e8dbc36b39e23b6f1143a1/src/backend/models/samples.py#L91

Maybe this is causing the bug? If true, just remove it from the dependencies section.

**Comment by akdean** [comment]
Ah, I hadn't considered that, let me check.

**Comment by akdean** [comment]
I suspect that was it @mirkobrombin, is there any possibility of excluding mono when a dotnet install is requested? Or perhaps some sort of message that reminds the user mono is already installed and asks if they want to proceed?

**Comment by mirkobrombin** [comment]
If you install any dotnet, mono is automatically removed from the bottle

**Comment by akdean** [comment]
Ah, maybe that's a better way to phrase the bug then. I've done two tests:

1. Create 'Software' bottle and remove `mono` as the first step.
2. Install Scrivener
3. Attempt to activate license (fails)
4. Kill all processes
5. Attempt to install dotnet462 (fails)

The installation fails with a message that '.NET Framework 4.6 or a later update is already...' etc.

**Comment by akdean** [comment]
I've just tested creating a Software bottle and immediately installing dotnet462.

The installation fails at the dotnet46 step with the above "already installed" error, you have to Cancel to continue.

Install finished, but `mono` is still listed as installed, even if I go out and back in to the bottle.

Scrivener activation fails.

**Comment by akdean** [comment]
@mirkobrombin let me know if you want me to test anything else with this, but right now I think the problem is that `mono` is still lingering and `.NET` versions might not be cleaned up correctly.
