### ISSUE TITLE
[BUG] Dependency typo in AUR PKGBUILD

### ISSUE THREAD

**Issue by Dhizaes** [bottlesdevs/Bottles#1024]
**Describe the bug**
AUR PKGBUILD, dependency list says "lib32-gnutxls" instead of "lib32-gnutls"

**Installation**
 - Method: AUR, with yay

**To Reproduce**
1. Open any terminal
2. Install Bottles from AUR, or update it
3. See dependency error

**Expected behavior**
Install Bottles with yay successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/16524806/152652238-5354a5d2-2d42-4ba1-a7e2-38fe9e3d5ac9.png)
![image](https://user-images.githubusercontent.com/16524806/152652268-da401d92-f267-4434-b2e8-821c15b356fa.png)

**Desktop:**
 - OS: Arch
 - Version: None
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Thanks for reporting. Fixed!
