### ISSUE TITLE
[Request] Install available dependencies offline

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1025]
2022.1.28-trento-4

I live in a poor country and when I am trying to use bottles with my bad internet connection and it cannot check for new dependencies nothing is listed.

From what I read about bottles, the dependencies previously downloaded and installed are stored locally. Those ones should still be accessible to install. If it's about a hash check that can be done locally.

please fix this for us poor people :( I just want to play games haha

![0B6CB2A8-C33B-4760-B553-937FFD51CBFD](https://user-images.githubusercontent.com/69682350/152657255-f9f0c4d9-09aa-400c-9bbb-f07d669bed7e.png)

this one already had a dependency installed so it is listed. But other bottles that never installed it cannot install the same one 
![F08676DB-25C1-4918-8E1D-DC09DD857348](https://user-images.githubusercontent.com/69682350/152657258-8c19e2af-d128-4af6-a830-1c5daa5595ba.png)

**Comment by mirkobrombin** [comment]
Please keep the titles as specific as possible. Also, your is a Feature request and not a bug, because Bottles just doesn't have this feature. I'm working on it and hope to make it available as soon as possible.

**Comment by ghtesting2020** [comment]
@mirkobrombin any update on this or planned for a future release? I still cannot install dependencies I already have downloaded if i am offline :(
