### ISSUE TITLE
[Request] Add power-profiles-daemon support

### ISSUE THREAD

**Issue by BigmenPixel0** [bottlesdevs/Bottles#1028]
It would be nice if Bottles had a "run with performance profile" feature.

https://gitlab.freedesktop.org/hadess/power-profiles-daemon

**Comment by mirkobrombin** [comment]
It seems interesting and useful, I inquire about it. Thanks for the reporting.

**Comment by TheEvilSkeleton** [comment]
Per the README, it depends on systemd:
> It requires libgudev, systemd and polkit-gobject.

Adding power-profiles-daemon would be quite harmful for users who use a distribution that doesn't use systemd. I'm completely against adding it, unless it's an optional dependency.

**Comment by mirkobrombin** [comment]
So maybe the best approach would be letting the user using them on their own, without an “official implement “

**Comment by TheEvilSkeleton** [comment]
Yes, or we could support it but make it automatically detect the init system. This is just a hypothesis.

**Comment by mirkobrombin** [comment]
Too much effort
