### ISSUE TITLE
[Request] Add Wine Explorer to Utilities section

### ISSUE THREAD

**Issue by frnmz** [bottlesdevs/Bottles#1029]
Hi! Thank you for making Wine so accessible now!
Playing game with Wine and sandboxed it never this easy before!

But I have a feature request:
In the Utilities section, it would be nice to have an option to open Wine Explorer.
This is useful (atleast for me) to know which folder Wine has access to (after granting the permission in flatseal).
All this time I have to open the cmd first, then open explorer from that.

What I mean Utilities section is this:
![image](https://user-images.githubusercontent.com/18339774/152683263-e4132ec1-46de-4dc7-bb80-45c41b1a6027.png)

What I mean Wine Explorer is this:
![image](https://user-images.githubusercontent.com/18339774/152683324-411dc534-fa03-40f4-88f4-896c6346306d.png)

Thank you!

**Comment by mirkobrombin** [comment]
Implemented!

**Comment by frnmz** [comment]
Woww not even an hour!
Thank you so muchhhh!

**Comment by mirkobrombin** [comment]
Did I win anything? Haha. You are welcome.
