### ISSUE TITLE
Discussion of the Russian translation

### ISSUE THREAD

**Issue by Knebergish** [bottlesdevs/Bottles#1035]
Hello all!

I would like to discuss some aspects of the Russian translation for Bottles.
In #1003 and #1014 , @Smoque significantly changed some existing parts of the translation. I completely agree with some of them, and I would like to discuss some of them.

1. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R471) for "runner": "«Пускач»"
In my opinion, this is a very slang term that sounds very unprofessional. I don't remember such a translation in other applications. In my opinion, this word could be kept without translation, because there is no adequate alternative in Russian. [In Lutris](https://github.com/lutris/lutris/blob/master/po/ru.po#L708), "раннер" is used as a translation. I suggest using the same variant for unification.
My suggestion: «Пускач» -> раннер

2. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R27) of the name of the Bottles application: "бутылки"
In the Russian translation, the "бутылка" form is already used for a separate bottle. Using a similar form for the app name will confuse users. And the name of the application, in my opinion, should begin with a capital letter. It seems to me that the name of the application can be left without translation, this is a fairly common practice.
My suggestion: "бутылки" -> Bottles

3. [Translation](https://github.com/bottlesdevs/Bottles/pull/1014/commits/3ec28581e781fc84cd86dc127ee979353e55e25b#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R387) for "Ultra Quality": "Сверхкачество"
Usually this phrase is not translated like that. This can be replaced simply with "Ультра" (used in many games).
My suggestion: Сверхкачество ->Ультра

4. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R417) for "Discrete GPU": "Дискретный ГПУ"
If we translate the abbreviation GPU, then as "ГП" (графический процессор). [In Lutris](https://github.com/lutris/lutris/blob/master/po/ru.po#L4377) it translates as "графическая карта", which is quite acceptable. But, in my opinion, here we can leave the original version (GPU), this is a popular abbreviation.
My suggestion: Дискретный ГПУ ->GPU

5. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R43) for "Mirko Brombin": "Мирко Бромбин"
As far as I can see, almost all other languages leave it unchanged, and I think the Russian translation should be the same. Direct transliteration can distort the original sound.
My suggestion: Мирко Бромбин ->Mirko Brombin

6. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R1069) for "environment": "среда"
There are two options, either "среда" or "окружение". Personally, I like the second option ("окружение"), it sounds more serious, but here I would like to hear someone else's opinion.
My suggestion: среда ->окружение

7. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R108) for "Various gaming-performance optimizations..."
All other languages use the original form with "()" instead of ":". I don't see any reason why it should be abandoned in the Russian translation.
My suggestion: keep old

8. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R293) for "Microsoft .NET Framework 4 .."
Again, the other languages use the "Microsoft" form, and I see no reason why the Russian translation should be different in this case.
My suggestion: keep old

9. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R217) for "Release Candidate": "релиз-кандидат"
I suggest using the [popular term](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%B4%D0%B8%D0%B8_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D1%8F#Release_candidate_-_%D0%BF%D1%80%D0%B5%D0%B4%D0%B2%D0%B0%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F) "предварительная версия" instead of a literal translation.
My suggestion: релиз-кандидат ->предварительная версия

10. [Translation](https://github.com/bottlesdevs/Bottles/pull/1003/commits/7ce0ad06092f54d0eb055998f398479a255fed3d#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R339) for "Improves performance of..."
Applications are not executed **IN** DirectX, so this "в" is unnecessary here.
My suggestion: keep old

11. [Translation](https://github.com/bottlesdevs/Bottles/pull/1014/commits/3ec28581e781fc84cd86dc127ee979353e55e25b#diff-92817e54c697fd6395db7e9eca8f2468538e83db228823136eaa96d834d74f76R423) for "Use a virtual desktop": "Виртуальный рабочий стол"
On the "Parameters" tab of a particular bottle, now part of the settings begins with the words "использовать/включить", and part does not, although in the original they all begin with "use/enable". I think we need to unify this, and either use these words in every setting, or nowhere.

12. Additionally, I would like to discuss a translation that does not relate specifically to @Smoque edits:
[Translation](https://hosted.weblate.org/translate/bottles/bottles/ru/?checksum=6b1282e178ec6147) for "GameMode": "игровой режим"
Yes, this is an obvious translation, but in this case, if the Russian users does not have the GameMode package installed, they will not be able to understand what they needs to do to activate this mode. Searching the Internet for just "игровой режим" may lead to nothing, but the keyword "GameMode" will help them find the information they need very quickly. Moreover, the word "Gamescope" remains untranslated nearby. In my opinion, we should leave this word without translation, because it is actually the name of a separate utility.
My suggestion: игровой режим ->GameMode

I would like to hear the opinion of all people interested in Russian translation, and in particular @Smoque and @mirkobrombin. It is possible that many people will not like my suggestions, so I would like to discuss this before making edits in Weblate.

I'm not sure if this is the right place for such discussions, so if I should use another platform for this, please guide me.

**Comment by mirkobrombin** [comment]
It all sounds reasonable (as far as I understand, not knowing Russian). I prefer to leave the floor to those who know anyway, feel free to use this issue as a discussion point.

**Comment by jannuary** [comment]
Looks good to me.

**Comment by lxdb** [comment]
For me as someone who speaks Russian the changes sound reasonable.

**Comment by Smoque** [comment]
Сильно сомневаюсь, что высказанные выше соображения по-настоящему интересны не-носителям русского, так что продолжу языком переводя, скопировав сюда свои ответы Артёму из Телеграма:

1. Технический термин "пускач" всё же существует. К примеру, бензиновый пускач дизель-генератора.
Раннер — ну, крайне корявое заимствование. Особенно при наличии неиноязычного аналога.

2. Надо обмозговать.

3. Ультра — годится.

4. Оставлять GPU — как оставлять CPU. Тем более, что есть аналогичная русская аббревиатура ЦПУ (центральное процессорное устройство). Так разве не бывает "графического процессорного устройства"?

5. Ну, тогда давайте писать все имена латиницей: Karl Marx, Vladimir Putin...

6. Окружение — боевой термин. В ИТ уместней переводить именно как среду. А "окружение" протащили не очень эрудированные спецы, привычные к переводам "в лоб".
Это как с "дезактивацией" — переводчики микрософта протащили английское написание без "з", тогда как по правилам Р.Я. в составных заимствованных словах префикс "де-" от последующей гласной следует отделять посредством "з": дезинформация, дезинтеграция, дезавуировать и т.п. В отличие от дегазации, демеркуризации и пр. корней, начинающихся с согласной.

7. Не помню строку полностью, позже гляну.

8. В русском две точки подряд используются лишь в диапазонах чисел: 7..15, к примеру. В качестве пропущенных слов/фраз — только многоточие.

9. Да, так лучше.

11. Надо осмыслить. Возможно, имеет смысл заменить словом "задействовать".

12. Насчёт GameMode от Feral Interactive я просто не сообразил, но как-то это надо обозначить.
А с Gamescope просто не знал, что делать.

**Comment by Smoque** [comment]
Дело в том, что я только взялся разбираться в Бутылках. И сразу режут глаз не переведённые моменты, а пуще того —переведённые криво. Вот и взялся привести в удобоваримый вид. Да вот слёг с болячкой — только на днях поправился.

**Comment by Smoque** [comment]
По пунктам, где в оригинале сказано включить/использовать/задействовать.
Если действие пункта представляет собой переключатель, переводить use/enable/switch вообще не надо: русскоязычным и без того понятно, что активированный пункт — включён/задействован/использован. И наоборот.

**Comment by Smoque** [comment]
"Повышает производительность DirectX 1... игр и 3D-приложений" — для русского глаза/уха чудовищно коряво.
DirectX-1... следует как минимум соединить дефисом, дабы термин не выглядел двумя отдельными сущностями, ну, и поставить в конец предложения — а то "будто Йода мастер написал как".
Но посыла, отчего там неуместен предлог "в", категорически не понимаю. Он вовсе ничему не мешает, не подменяет и не сбивает с панталыку.

**Comment by Smoque** [comment]
Вернёте сами те пункты, с которыми согласны?
Остальные продолжим обсуждать, искать лучшие варианты.

**Comment by Smoque** [comment]
И ещё. Для чего возвращены двойные кавычки, тогда как в русских печатных текстах куда уместней кавычки-ёлочки, каковые я старательно и расставил?

**Comment by Knebergish** [comment]
1. Хмм, и правда существует, не знал. Но такое ощущение, что он не используется где-либо, кроме автомобильной промышленности; не уверен, что стоит применять его здесь. Lutris - более зрелое, чем Bottles, приложение, и многие пользователи Bottles приходят сюда именно с него. Поэтому в таких сложных случаях, как этот, думаю, нормально ориентироваться на перевод из Lutris, что может помочь новым пользователям разобраться в Bottles, видя знакомые термины.
2. Сложный вопрос. У нас уже есть прямой перевод для "bottle" - "бутылка", поэтому аналогия для обычного пользователя будет ясна. Если таким же схожим образом будет переведено и название приложения, то в некоторых местах пользователю будет сложно определить, о чём идёт речь - о всём приложении в целом или о конкретной/множестве "бутылок". В то же время, у меня не установлено практически ни одного приложения, в котором был бы сделан перевод его названия, даже если он доступен на русском, так что не думаю, что это общепринятая практика. Firefox (Огнелис), Word (Слово), Steam (Пар), Element (Элемент), Postman (Почтальон)... Пользователи спокойно живут с такими названиями и не требуют их перевода, так что думаю, что и в данном случае можно обойтись без него.
4. Сложно, надо подумать.
5. Возможно, вы правы, просто тут решил ориентироваться на практику перевода Bottles на другие языки - в подавляющем большинстве там используется оригинальная, английская версия.
6. Тут не уверен. В моём опыте слово "окружение" очень часто используется как альтернатива "среде", и мне никогда не бросался в глаза его боевой смысл. Нам ещё, возможно, придётся как-то переводить "runtime" - скорее всего это будет "среда выполнения", и может начаться путаница со средами, которые бутылки.
8. Тут писал про сокращение Microsoft (MS). В остальных переводах используется полная версия, поэтому предложит и тут её оставить, а не сокращать. Про две точки согласен, это отдельная проблема, они используются во многих местах вместо троеточия, и это надо исправлять на уровне исходников, а не перевода.

С кавычками-ёлочками полностью согласен и не заменял их обратно на двойные. Возможно, у вас не обновлено приложение Bottles, и перевод с ними не дошёл до вас.

**Comment by Knebergish** [comment]
10 ) Технически, игры и приложения не выполняются **В** DirectX, а ну хотя бы "с помощью". Форма с написанием через дефис не используется где-либо, ни в других вариантах перевода, ни в Интернете в целом, так что не думаю, что нам стоит её использовать. Но как-то переформулировать это предложение можно, согласен.

**Comment by Smoque** [comment]
Можно использовать слово "посредством", но особой разницы с "в" не вижу: можно ведь трактовать как "в исполнении DirectX". :)
А поскольку речь не о _других_ переводах, а именно о русском, то дефис нужен: в русском он собирает термин воедино (как космический корабль "Восток-1", магнитофон "Комета-212" и т.п.), а оригинальному написанию ни в чём не противоречит.

**Comment by Smoque** [comment]
7. Можно оставить и в скобках. Но многоточие там в русском вариате ни к чему.

**Comment by psydvl** [comment]
2.	Нигде не используется перевод wine как вино, так что и бутылки лучше оставить как bottles
  
5)	Перевод или транслитерация имен сомнительное удовольствие, теряется произношение, и многие другие нюансы языка, на википедии этому посвящена отдельная тема https://ru.wikipedia.org/wiki/Википедия:Опросы/Иноязычные_имена
Лучше оставить как есть

10.	На сайте Microsoft нигде не используется дефис, так что предлагаю не плодить сущности. Тем более возможно придется в какой-то момент использовать что-то вроде DirectX 11.2

**Comment by Smoque** [comment]
> 1 ) Хмм, и правда существует, не знал. Но такое ощущение, что он не используется где-либо, кроме автомобильной промышленности; не уверен, что стоит применять его здесь.

И в ИТ вовсю используются дизель-генераторы для резервного электропитания. И тоже заводятся пускачами. :)
Насчёт зрелости лютриса не спорю. А вот к его переводу — тоже достаточно претензий.

**Comment by Smoque** [comment]
> 2\. Нигде не используется перевод wine как вино, так что и бутылки лучше оставить как bottles

1) Используется. В общении русскоговорящих игроков-линуксоидов.
2) Одна из строк оригинала буквально содержит упоминание про "разлить вино по бутылкам".

**Comment by Smoque** [comment]
> 1. Как я понимаю пускач - штука разово запускающая что-либо
>    Раннер же именно среда в которой все работает и это несколько другое

Тогда поищите, как по-английски называется "запускатор" дизеля. :)

**Comment by psydvl** [comment]
В общении используется именно вайн, а не вино 
Нетрудно проверить на различных форумах
- https://www.linux.org.ru/search.jsp?q=вайн
- https://www.linux.org.ru/search.jsp?q=вино

Runner вообще [имеет много смыслов](https://www.multitran.com/m.exe?s=runner&l1=1&l2=2), это как русская коса, так что ваш аргумент сомнительный
А конкретно тут имеется ввиду долгосрочная работа, и при переводе в "пускач" это теряется

**Comment by Smoque** [comment]
> Runner вообще [имеет много смыслов](https://www.multitran.com/m.exe?s=runner&l1=1&l2=2), это как русская коса,

Коса — не много смыслов, а много слов-омонимов. Runner — точно не омоним. В английском есть одинаково звучащие слова, но пишутся они по-разному и омонимами не являются.
Что же до "вина", в чатах телеги, матрицы и пр. звучит оно частенько. Да и как "вайн" его произносят только и исключительно дабы не путать эмулятор с напитком. :)

**Comment by Knebergish** [comment]
> Перевод "оптимизация окружения" дико смешит. Единственная оптимизация окружения — это его прорыв, выход и ликвидация. А уж мн.ч. этого слова действительно только от мелкософтовских переводчиков можно было услышать. :)

Судя по всему, у нас с вами совершенно разное отношение к этому слову ). Для меня оно всегда звучит в смысле того, "что находится вокруг". Вариант рассматривать здесь это слово в смысле вражеского окружения мне и в голову не приходил раньше. Думаю, что мы тут заложники субъективного опыта, и нужно ещё несколько мнений со стороны.

Насчёт использования "вина" вместо "вайн" - тут мне всё-таки чаще доводилось встречаться именно с "вайн".
Может быть стоит runner вообще не переводить, как и wine.

**Comment by Smoque** [comment]
> у нас с вами совершенно разное отношение к этому слову ). Для меня оно всегда звучит в смысле того, "что находится вокруг".

Полагаю, это именно результат вброса от корявых переводчиков винды. Полагаю, мы разных поколений: я рос на книгах/фильмах о войне, вы же, наверное, — как раз на пике распространения первых версий Windows (9х и т.д.).

**Comment by psydvl** [comment]
Слово имеющее разные смыслы это и есть омоним, и runner как видно по приведенной мною ссылке он и есть
Но я точно категорически против использования слова пускач, потому что его смысл точно не соответствует контексту

PS предлагаю не засорять issue, а обсудить это дело в телеграме?
https://t.me/+W2LpWnfIKGE4OTAy

**Comment by Smoque** [comment]
> PS предлагаю не засорять issue, а обсудить это дело в телеграме?
> https://t.me/+W2LpWnfIKGE4OTAy

Это же канал, а не чат. Как там обсуждать? :)

**Comment by psydvl** [comment]
Извиняюсь, перепутал кнопку
https://t.me/+3-5B_Pb6KaAxY2Ey
