### ISSUE TITLE
[BUG] Bottles just hangs when starting

### ISSUE THREAD

**Issue by lavadrop** [bottlesdevs/Bottles#1037]
Bottle does not respond after starting, both when started via desktop file shortcut or from CLI

**Installation**
Flatpak 
Version 0.83.22

Open Bottles

**Expected behavior**
A responsive program.

**Desktop:**
 - OS: openSUSE TW
 - TW
 - Display server:Xorg

CLI informs:

(15:54:18) INFO Performing Bottles checks... 
(15:54:18) INFO Dxvks found:
	 - dxvk-1.9.2
 
(15:54:18) INFO Vkd3ds found:
	 - vkd3d-v2.4
 
(15:54:18) INFO Nvapis found:
	 - dxvk-nvapi-v0.4
 
(15:54:18) INFO Runners found:
	 - vaniglia-6.18

**Comment by mirkobrombin** [comment]
duplicate of #974

**Comment by lavadrop** [comment]
Except this has been happening for months and it’s not ocasional, I haven’t seen the Bottles main window for months.

**Comment by mirkobrombin** [comment]
This is due to repository fetching on startup. To some it happens a few times, to others always. I'm investigating this.
