### ISSUE TITLE
Gamemode toggle not working 

### ISSUE THREAD

**Issue by Sultech** [bottlesdevs/Bottles#1040]
**Describe the bug**
Gamemode is not working

**Installation**
 - Flatpak
 - Version 2022.1.28-trento-4

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a bottle
2. Click on preferences 
3. Scroll down to gamemode and enable it
4. Open a game
5. gamemode will not work.

**Expected behavior**
 Gamemode toggle to work

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Can’t reproduce

**Comment by Sultech** [comment]
are you using the flatpak version

**Comment by Sultech** [comment]
Well I'm not sure why its not working in bottles. When I try gamemode with steam it works.

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/commit/e2c55b8328f609a2dd2cf13eb1d9b9add47f7b6e

(I was using a development version which has this fix).
