### ISSUE TITLE
[BUG] I always have to run executable twice before it opens up (CLI)

### ISSUE THREAD

**Issue by sophie-kuehn** [bottlesdevs/Bottles#1041]
**Describe the bug**
When i try to start an executable using the CLI, the first time always fails without an error. The second time the program is executed, but throws errors. Tested it with two apps:
- https://portableapps.com/de/apps/utilities/7-zip_portable
- https://www.heidisql.com/download.php (this one also doesn't like to run in multiple instances using Bottles, but that's another issue)

**Installation**
 - Method: flatpak
 - Version 2022.1.28-trento-4

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Version: 19.3 Cinnamon
 - Display server: Xorg

**Log**
```
###:$ flatpak run com.usebottles.bottles -b Work -e any.exe
(21:09:46) INFO Performing Bottles checks... 
(21:09:46) INFO Dxvks found:
	 - dxvk-1.9.4
 
(21:09:46) INFO Vkd3ds found:
	 - vkd3d-proton-2.5
 
(21:09:46) INFO Nvapis found:
	 - dxvk-nvapi-v0.5.2
 
(21:09:46) INFO Runners found:
	 - caffe-7.0
 
(21:09:46) INFO Temp path cleaned successfully! 
(21:09:46) INFO Bottles found:
	 - Work
 
(21:09:46) INFO Launching an executable… 
###:$ flatpak run com.usebottles.bottles -b Work -e any.exe
(21:09:49) INFO Performing Bottles checks... 
(21:09:49) INFO Dxvks found:
	 - dxvk-1.9.4
 
(21:09:49) INFO Vkd3ds found:
	 - vkd3d-proton-2.5
 
(21:09:49) INFO Nvapis found:
	 - dxvk-nvapi-v0.5.2
 
(21:09:49) INFO Runners found:
	 - caffe-7.0
 
(21:09:49) INFO Temp path cleaned successfully! 
(21:09:49) INFO Bottles found:
	 - Work
 
(21:09:50) INFO Launching an executable… 
wineserver: using server-side synchronization.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0068:err:module:open_builtin_so_file failed to load .so lib "###/com.usebottles.bottles/data/bottles/runners/caffe-7.0/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

###:$ 010c:err:shell:SHGetFileInfoW pidl is null!
^C
```

**Comment by mirkobrombin** [comment]
This happen only using CLI or also from GUI?

**Comment by sophie-kuehn** [comment]
Gui seams to start it always.

**Comment by mirkobrombin** [comment]
Is this option enabled?

![image](https://user-images.githubusercontent.com/9479903/153290933-5417b2db-f3fe-412d-97c0-d6bc6e628160.png)

**Comment by sophie-kuehn** [comment]
No.

**Comment by mirkobrombin** [comment]
CLI is under rewrite, I'll check this before next release. Thanks

**Comment by sophie-kuehn** [comment]
Maybe that's connected: When i start an app using CLI and afterwards fire up the Bottles app itself, the previously started app shuts down. The last log says:
```
010c:err:shell:SHGetFileInfoW pidl is null!
00cc:err:rpc:RpcAssoc_BindConnection rejected bind for reason 0
```

**Comment by mirkobrombin** [comment]
Mh I don't think it's related.

**Comment by mirkobrombin** [comment]
Fixed by new cli https://docs.usebottles.com/advanced/cli

**Comment by sophie-kuehn** [comment]
Confirmed.
