### ISSUE TITLE
[BUG] Naming bottles a certain way such as "yes".

### ISSUE THREAD

**Issue by RushingAlien** [bottlesdevs/Bottles#1043]
**Describe the bug**
Bottle names can be a bit finicky, maybe add quotes?
Bottle name from the .yml seen as boolean value thus can not be seen by Bottles app. then changed bottle name manually from .yml, it is recognized again.
Bottle path from the .yml seen as a boolean value thus creating a different prefix from the one wanted when run (the prefix first created is "yes", and then upon running executable, it created a prefix in a new folder "True".
putting quotes around "yes" in the bottle.yml file seems to fix it since it now seen as a string by python instead of a boolean

**Installation**
 - Method: AUR
 - Version: 2022.1.28

**To Reproduce**
1. Open Bottles
2. Create a Bottle with a name that may be taken as a boolean value by python
3. Succesfully create a bottle
4. Run something in said bottle

**Expected behavior**
For bottle/prefix to be recognized by Bottles app and for bottles to use the correct path.

**Desktop (please complete the following information):**
 - OS: Arch, GNOME
 - Version 40
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
🤔

**Comment by RushingAlien** [comment]
I'm sorry this seems to be a non-issue, the .yml has a `'` around the name and path if it has a name that can be taken as a boolean.

But I have noticed that renaming a bottle that isn't originally soemthing that can be taken as a boolean to a boolean-like name. Bottles seem to give a python error
