### ISSUE TITLE
[BUG] LTSpice doesn't appear in programs list

### ISSUE THREAD

**Issue by AdrianVovk** [bottlesdevs/Bottles#1044]
**Describe the bug**
I installed [LTSpice](https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html) into a bottle, but Bottles fails to detect it and put it into the "Programs" section. LTSpice's installer created a .lnk file on the Desktop (`C:\users\adrian\Desktop`)

Opening an issue as instructed [here](https://docs.usebottles.com/bottles/programs#the-program-does-not-appear)

**Installation**
 - Method: Flatpak
 - Version: 2022.1.28-trento-4

**To Reproduce**
1. Create a new box
2. Install LTSpice (installer link above)
3. Go to the programs list in bottles and press refresh
4. Observe that LTSpice isn't in the Programs list

**Expected behavior**
Bottles would detect that LTSpice is installed, and give me an option to launch it

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version: 35
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by antibunching** [comment]
TI-Spice has this issue too.
