### ISSUE TITLE
[BUG] Pekka Kana 2 no longer works after updates

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1045]
I don't know if this is the right place for that report but it worked nearly flawlessly before February.

**Describe the bug**
After update the Pekka Kana 2 game doesn't launch. It just displays error "Could not find the default language file". Tried caffe-7.0, caffe 6.23-x86_64 and Proton-6.21-GE-2 but they all throw the same error.

**Installation**
 - Method: Flatpak
 - Version: 2022.1.28-trento-4
 
**To Reproduce**
1. Go to [Piste Gamez PK2](https://www.pistegamez.net/game_pk2.html)
2. Download "PK2 v1.21 Installer (6.6MB)"
3. Launch the installer with Bottles "run the executable"
4. Install the game
5. try to launch it with play button in programs section
6. See error

**Expected behavior**
Pekka Kana 2 launching and being able to play it. It had a small bug with mouse click crashing the game but the mouse isn't needed there anyway.

**Screenshots**
![2022-02-12_10-29-57](https://user-images.githubusercontent.com/84787215/153705768-df1cdc8b-9a3a-4aac-bbb3-7c7c12e994db.png)

**Desktop:**
 - OS: Linux Mint
 - Version: 20.3
 - Display server: Xorg
 - Mesa AMD drivers
 
**Additional context**
Everything default - both Bottles and my OS. The update that broke it must have been released sometime before the February because I tried reinstalling the game so I have copied the save data (from PK2) and it shows: "modified: 28th January" "created 26th January"

**Comment by MrQuerter** [comment]
It's getting tricky.
I rolled back to version that was supposed to be just before my save and it didn't work.Then I remembered that at first I didn't update flatpaks so often so I decided to roll back to last version of 2021. A new option appeared called "PK2" and it launched like it used to.
![2022-02-12_13-29-46](https://user-images.githubusercontent.com/84787215/153711516-6aefea28-d4d5-426d-96e5-1c5fa98652a3.png)
1st rollback: 2022.1.14-trento-2 (2022-01-15)
2nd rollback: 2021.12.28 (2021-12-27)

Interestingly even mouse works this time without crashes. What I also noticed is that clicking the "browse directory" option on PK2 works, but the last two don't open any directory at all.
![2022-02-12_13-39-02](https://user-images.githubusercontent.com/84787215/153711699-9a39e25e-ab69-41ef-a2b1-d7203d6f843b.png)
Again, nothing changed, kept Bottles at defaults. Just checked caffe and proton.

**Comment by MrQuerter** [comment]
Just wanted to add some comments.

Updated flatpak to the newest today and it still didn't work. Then I went to the programs tab on the left and decided to add the custom path to exe (plus icon on top). It replaced "Pekka Kana 2" entry with "PK2" and it launched. Though once again clicking mouse crashes the game.

Next I installed another game from .exe just to be sure and after installation only "dxdiag" appeared pointing to system folder, but after setting the custom path it worked well. I don't know if that's the expected way of Bottles working but I guess it's kind of solved for now, though if you need I can check some things that you want (maybe making a reinstall so it's for sure set at defaults)

**Comment by mirkobrombin** [comment]
I don't know what other tests do or information ask you. Meanwhile, post your bottle.yml here please

**Comment by MrQuerter** [comment]
Had to save it as .txt for github to upload it, but it shouldn't be a problem.
[bottle.txt](https://github.com/bottlesdevs/Bottles/files/8061725/bottle.txt)

**Comment by MrQuerter** [comment]
Hi. I updated the flatpak today, nuked the whole bottle and decided to check it again. After installing, programs list shows "PK2", it launches normally, "browse path" option works and the mouse doesn't crash in the game. Have no idea what went wrong or what did you fix during that month, but I guess it was solved.

**Comment by mirkobrombin** [comment]
Nice, closing for now

**Comment by MrQuerter** [comment]
Hello. The bug is kind of back.

I was trying the "launch with terminal" button when I was testing the program menu for bugs and it can't launch the PK2.
![ksnip_20220616-115841](https://user-images.githubusercontent.com/84787215/174046045-640a4cd5-5298-4082-9f82-2bdd3ce58825.png)

Which is weird because if you run it with arrow icon it launches without problems.
![ksnip_20220616-120217](https://user-images.githubusercontent.com/84787215/174046513-8327bf22-82ee-4fc5-9629-a6cef590382b.png)
