### ISSUE TITLE
Add Philosophy and/or Use Case to "why bottle" FAQ

### ISSUE THREAD

**Issue by TheJoeSchr** [bottlesdevs/Bottles#1048]
Hi,

I think I'm drawn to this idea, but I still don't get how this differs from other solutions after reading faq and all docs.

I think there might be a part about the philosophy behind bottles needed. 

And example of how to use Bottles in the canonical way. 
Maybe another one if you are coming from steam proton and lutris.

For eg. questions I still ask myself:

- Am I supposed to just make to bottles, one for software and one for games and then install/import everything in there accordingly?
- what if they need different proton versions to work (or dependencies)

- Or do I still have different bottles for different games.
- How about something like vortex? One vortex to rule all games? 

Ps.: A small bug on the forums and the reason I'm writing here. You can't sign-up/login via GitHub on mobile over there

**Comment by mirkobrombin** [comment]
Hi, thanks for reaching us. This page explain some conceptshttps://docs.usebottles.com/faq/why-bottles

Should we make this more clean?

**Comment by TheJoeSchr** [comment]
> Hi, thanks for reaching us. These pages explain some concepts:
> - https://docs.usebottles.com/faq/why-bottles
> - https://docs.usebottles.com/faq/where-is-winetricks
> 
> Should we make this more clean?

Yes. Sorry, I wanted to include a part where I stated that I read all the docs and the faq, but seem to have forgotten it

**Comment by TheJoeSchr** [comment]
After reading bottles again, I'm still thinking about this.

I really don't get where to place bottles besides wine and proton and steam. What is bottles usecase?

Is it supposed to be similar to lutris/gamehubs/etc? One app to manage all your games with different launchers.

Or should I use steam and link it to each individual bottle? Put isn't it then like proton?

**Comment by mirkobrombin** [comment]
> Bottles is an application that allows you to easily manage Wine prefixes on your favorite Linux distribution.
> 
> Windows prefixes are environments where it is possible to run Windows software using runners. Runners are compatibility layers capable of running Windows applications on a Linux system.
In Bottles we call these environments as bottles.
