### ISSUE TITLE
[BUG] Some buttons in "About Bottles" window does not work

### ISSUE THREAD

**Issue by Knebergish** [bottlesdevs/Bottles#1049]
**Describe the bug**
In "About Bottles" window, buttons "License" and "Close" does not work.

**To Reproduce**
1. Go to top main Menu
2. Click on "About Bottles" item
3. Click on "License" or "Close" buttons

**Expected behavior**
The license information will open or the current window will close, depending on the button pressed.
**Actual behavior**
Nothing happened.

**Installation**
 - Method: Aur
 - Version 2022.1.28-trento-4

**Desktop:**
 - OS: Manjaro
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Related https://github.com/bottlesdevs/Bottles/issues/924

**Comment by Knebergish** [comment]
Yes, duplicate, sorry.
