### ISSUE TITLE
[BUG] Prevent application running from outside drive_c if sandboxed (to avoid system lockup)

### ISSUE THREAD

**Issue by MiguelGuthridge** [bottlesdevs/Bottles#1050]
**Describe the bug**
When Bottles is sandboxed, running an application that is present outside of the sandbox can cause your system to lock up, requiring a reboot. Giving a warning when the file is outside the sandbox 

**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

**To Reproduce**
- Create a sandbox and choose to run an application that is stored outside of the sandbox
- Run the application
- Observe the system lockup (mouse and keyboard and power button stop working and screen freezes, need to hold power for 10 seconds to force reboot)

**Expected behavior**
- There is some kind of warning to prevent you from crashing your OS (maybe reminding you to select the move to sandbox option)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version 21.10
 - Display server: Xorg
**Additional context**
- Hybrid Intel/NVidia graphics

**Comment by jannuary** [comment]
That's... not a solution to the problem

**Comment by MiguelGuthridge** [comment]
Ok yeah I presumed it was a Wine issue causing the crash (hence it's more difficult to fix here)? If a crash can be fully prevented that'd be obviously even better :)

**Comment by mirkobrombin** [comment]
I'm trying to reproduce this but with no results. Which program are you try to run and from which path?

**Comment by MiguelGuthridge** [comment]
It's happened for the Remarkable Companion App installer, as well as the FL Studio installer. They were both in my `~/Downloads` folder. When I try to run the program inside a bottle (gaming or standard application), the Bottles UI freezes and then roughly a minute later my system audio cuts out and keyboard and mouse inputs stop being accepted. If I run an application from within the sandbox I don't encounter that issue, although while Bottles moves installers into the sandbox, the UI for it freezes (although I can still use the rest of my OS).

Could also be useful to note that I'm on KDE 5.24.1 (rather than 5.22.5). Is there anything I can do to help diagnose the issue?

**Comment by mirkobrombin** [comment]
Flstudio is working fine here when launching from the Downloads folder 🤔

**Comment by MiguelGuthridge** [comment]
Very interesting.... I've run the installer, and the app has been frozen for the last 5 minutes. At least my system hasn't crashed though.... I'll keep investigating, but the app and my OS have seen a few updates since the last time I posted here... maybe the bug is gone now?

**Comment by mirkobrombin** [comment]
Maybe with latest release

**Comment by mirkobrombin** [comment]
Closing as I'm not able to replicate. Should be something system-related. Feel free to add more comments.
