### ISSUE TITLE
[BUG] Whole OS hang when run an executable

### ISSUE THREAD

**Issue by thanhminhmr** [bottlesdevs/Bottles#1051]
**Describe the bug**
Run an installer and not just Bottles, the whole OS hang (keyboard capslock light not responding kind of hang).

**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

**To Reproduce**
1. Create an Application bottles.
2. Go to Preferences
- Turn off DXVK and VKD3D
- Set Windows version to Windows 7
- Turn on Bottles runtime
- Turn on Reduce audio latency
3. Go to Dependencies
- Install allfonts
- Install gdiplus
4. Back to Details & Utilities
5. Run [this messaging app's installer](https://zalo.me/download/zalo-pc).

**Expected behavior**
The installer runs as expected. (Or at least it failed to run gracefully.)

**Screenshots**
<details>
<summary>Screenshot of Preferences page. Click to expand!</summary>

![image](https://user-images.githubusercontent.com/31412085/153812718-391c8a99-1029-4ce4-9d37-d6cafcb2113b.png)
</details>

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Display server: Xorg

**Additional context**
The task manager and the registry editor works fine, so not all executables produce the same bug.

**Comment by thanhminhmr** [comment]
I copy the installer to the bottle desktop folder and run it with the Add/Remove programs panel and now it works perfectly. Maybe something with the Run program button logic?

**Comment by mirkobrombin** [comment]
Flatpak is sandboxed. Some programs need to be inside the sandbox to works, we are looking for a way to improve this. Does it works with the installer places in downloads folder?

**Comment by thanhminhmr** [comment]
> Flatpak is sandboxed. Some programs need to be inside the sandbox to works, we are looking for a way to improve this. Does it works with the installer places in downloads folder?

You mean in the Downloads folder on the host machine? Yes, I saved the installer there.

**Comment by mirkobrombin** [comment]
As a trick you can give bottles permission to a specific folder using flatseal

**Comment by thanhminhmr** [comment]
I already found a workaround, I will put it here for anyone who needs it.
- Browse internal files of a bottle using Browse C:
- Copy the installer to somewhere, users/<your username>/Desktop will be easier to find.
- Run the installer using Add/Remove programs (open using Uninstaller) -> Install -> choose the installer
![image](https://user-images.githubusercontent.com/31412085/153819318-dadbd6d5-bb26-4a07-b1cf-f145ab3ae634.png)

**Comment by mirkobrombin** [comment]
If the file is just one you can also select “move to sandbox” in the run executable menu

**Comment by greatquux** [comment]
I just reproduced this by taking all the defaults. I just installed the Flatpak, clicked Next and created one bottle, tried to run an EXE out of my home directory, and boom, whole OS hangs.  Crazy.

**Comment by StephenRynas** [comment]
This is similar to Bug #1061. Merge the two?

**Comment by StephenRynas** [comment]
The workaround posted by [thanhminhmr](https://github.com/thanhminhmr) apparently works. Just made a quick install. So it is not fully tested. But it is progress!!!

One step in the install process was abbreviated, the file to be installed has to be placed in the "_fake_" Windows directory, not in a Linux directory, which is where I had placed it for installation. The instructions, overall, do not seem clear that a program to be installed needs to be fully moved out of the Linux environment and placed within the Bottles Window's environment. See image below for the path to place the Window's program.
![Screenshot from 2022-03-01 13-25-16](https://user-images.githubusercontent.com/99763298/156228251-234c4922-07a6-47c5-93f2-4683ab8b3c2e.png)

I did get one error message, but it did not seem to have an adverse effect.
![Screenshot from 2022-03-01 13-19-55](https://user-images.githubusercontent.com/99763298/156228626-f3703f3a-54c5-410e-8f75-6d9a1abc63fb.png)

**Comment by francescomasala** [comment]
@StephenRynas can I see the output of the error?

**Comment by StephenRynas** [comment]
The image of the error (Internal Error 25259. DirectX-9) is above. Is There another error message that you were thinking of? Thank-you for responding.

**Comment by mirkobrombin** [comment]
I was hitting this bug too some days ago and it disappear after recent WineExecutor update. Also, when using Flatpak, be sure to always move executables inside the bottle if those doesn't start (https://docs.usebottles.com/flatpak/black-screen-or-silent-crash)
