### ISSUE TITLE
install using .deb package launch the error dependence  gir1.2-handy-1 => 1.5.0

### ISSUE THREAD

**Issue by tridoxx** [bottlesdevs/Bottles#1053]
I am trying to install the .deb package on pop_os 21.10 but it gives me the error that gir1.2-handy-1 must be >= 1.5.0 but when checking the package manager it shows that the latest available or current version is 1.2 .3, maybe it's a bug or a dependency error.

the version i try to install is 2022.2.14-trento Release day: https://usebottles.com/blog/release-2022.2.14/ 

I stay tuned since I want to try this software, to create executables and show it on my channel dedicated to linux gaming.
![image](https://user-images.githubusercontent.com/22879539/153934691-3f93fc4a-6030-4023-8a51-304ceb9004bc.png)
![image](https://user-images.githubusercontent.com/22879539/153934700-45e863f5-9c48-4098-a392-d24c2cfffeb0.png)
![image](https://user-images.githubusercontent.com/22879539/153934762-42331cb2-858e-4e6a-9326-20e009e6c49c.png)

**Comment by mirkobrombin** [comment]
Hi, I suggest to use the flatpak instead, the deb file is actually broken in pop os :D

**Comment by tridoxx** [comment]
> Hi, I suggest to use the flatpak instead, the deb file is actually broken in pop os :D

okay, i will use for try, but you know no everybody use flatpak

**Comment by mirkobrombin** [comment]
Ya but I’ve not a Debian based distro and I’m very busy with the development and my job, so I prefer to invest my free time on the flatpak

**Comment by tridoxx** [comment]
> Ya but I’ve not a Debian based distro and I’m very busy with the development and my job, so I prefer to invest my free time on the flatpak

I really didn't mean to sound rude, I know it's a great project, and that a lot is invested, but it was more than anything a reference to my question and proposal, since there are .deb downloads, but I understand what you mean, I'll check in flatpak, thanks anyway for this project :)

**Comment by braiam** [comment]
@mirkobrombin would be wise to maintain the deb package out of tree?

**Comment by mirkobrombin** [comment]
> @mirkobrombin would be wise to maintain the deb package out of tree?

Yup. I'll remove it for now as GitHub is still building it but I'm only testing the Flatpak. I need to set up a VM and test on it.

**Comment by mirkobrombin** [comment]
Closing as the deb package is now deprecated.

**Comment by shirishag75** [comment]
Any possibility of getting the deb package being revived or it's gone for good :(

**Comment by mirkobrombin** [comment]
It's gone, use the Flatpak.
