### ISSUE TITLE
[Crash report] No such file or directory installing DLL Components

### ISSUE THREAD

**Issue by d33vliter** [bottlesdevs/Bottles#1055]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.2.14-trento

**Log**
```python3
[Errno 2] No existe el fichero o el directorio: '/home/USER/.local/share/bottles/bottles/juegos/drive_c/windows//syswow64/d3d9.dll'  File "/usr/share/bottles/bottles/utils.py", line 103, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1161, in create_bottle
    self.install_dll_component(config, "dxvk", version=dxvk_name)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1355, in install_dll_component
    manager.install(config, overrides_only, exclude)

  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 65, in install
    self.__install_dll(config, path, dll, False, overrides_only)

  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 98, in __install_dll
    shutil.copyfile(source, target)

  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:

```

**Comment by mirkobrombin** [comment]
Which package?

**Comment by kcthrn** [comment]
@mirkobrombin I'm getting similar error when selecting to create an _Application_ environment.

```
(08:23:51) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.managers.manager.Manager object at 0x7f65b85e92e0>>
	Exception: [Errno 2] No such file or directory: '/home/me/.var/app/com.usebottles.bottles/data/bottles/bottles/wkhtmlto/drive_c/windows//syswow64/d3d9.dll'
```
![image](https://user-images.githubusercontent.com/16540129/154062371-108beed6-20a4-4f37-a4ff-85f5a1305c6a.png)

Bottles version: 2022.2.14-trento

Output of Health check:
```
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.14.21-210.current
Distro:
    Name: GNOME
    Version: '"41 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
I'll try to reproduce (again)

**Comment by d33vliter** [comment]
> 


> Which package?

package for VoidLinux(xbps)

https://gitlab.com/d33vliter/void-custom-packages/-/blob/main/srcpkgs/bottles/template

**Comment by mirkobrombin** [comment]
Ok I've got it. Seems like that the prefix is not fully initialized when dxvk try to place its files. Can you check if the wineprefix contains all needed paths?
- drive_c
- drive_c/system32
- drive_c/syswow64
- drive_c/windows

**Comment by d33vliter** [comment]
> Ok I've got it. Seems like that the prefix is not fully initialized when dxvk try to place its files. Can you check if the wineprefix contains all needed paths?

there is nothing inside the folder, curiously when I try to create a new custom bottle, when I try to view the dxvk versions it crashes with the message: 
GLib-GIO-ERROR **: 15:48:44.857: Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-winebridge'

**Comment by d33vliter** [comment]
> > Ok I've got it. Seems like that the prefix is not fully initialized when dxvk try to place its files. Can you check if the wineprefix contains all needed paths?
> 
> there is nothing inside the folder, curiously when I try to create a new custom bottle, when I try to view the dxvk versions it crashes with the message: GLib-GIO-ERROR **: 15:48:44.857: Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-winebridge'

also when I try to enter settings

**Comment by mirkobrombin** [comment]
> > > Ok I've got it. Seems like that the prefix is not fully initialized when dxvk try to place its files. Can you check if the wineprefix contains all needed paths?
> > 
> > 
> > there is nothing inside the folder, curiously when I try to create a new custom bottle, when I try to view the dxvk versions it crashes with the message: GLib-GIO-ERROR **: 15:48:44.857: Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-winebridge'
> 
> also when I try to enter settings

Seems like a broken installation. Schemas should be rebuilded after updates but are not handled by Bottles.

Regarding the problem, I think we are hitting one of the following problems (which should already have dedicated issues):
- the `WINEPREFIX` env var is already set and Bottles is not able to replace it (so check if it is already set by echoing it)
- the `glibc` version is < 3.33 which is the min version required by the Caffe runner (so you should try another runner using a custom env)

**Comment by d33vliter** [comment]
> 

you are right, the version I have of glibc is glibc-2.32, I also compiled it from the sources and I could enter the settings. So most likely it is the version of glibc, thanks bro

**Comment by mirkobrombin** [comment]
> > 
> 
> you are right, the version I have of glibc is glibc-2.32, I also compiled it from the sources and I could enter the settings. So most likely it is the version of glibc, thanks bro

Flatpak should came with glibc 3.33 if I'm not wrong

**Comment by d33vliter** [comment]
> 

Update: 

Update glibc to the latest and the error still happens, except when I make it custom bottles.

**Comment by kcthrn** [comment]
@mirkobrombin I have WINEPREFIX set in my dotfiles.

BTW, Is there an option to skip installing/using dxvk? Not all GPUs have support for Vulkan.

**Comment by mirkobrombin** [comment]
> @mirkobrombin I have WINEPREFIX set in my dotfiles, would that still affect the Flatpak version of Bottles?

Yes.

> BTW, Is there an option to skip installing/using dxvk? Not all GPUs have support for Vulkan.

Just using the Custom environment. Btw Bottles installer will still install them.

**Comment by kcthrn** [comment]
@mirkobrombin This worked:
```
unset WINEPREFIX; flatpak run com.usebottles.bottles
```

What didn't work:
- Having WINEPREFIX set.

  My WINEPREFIX is set to `/home/me/.local/share/wineprefixes/default`. 

  When creating a bottle using the *Application* environment, before it failed, I would get lines like below.
  ```
  (08:03:08) INFO Using WINE Registry CLI 
  wine: chdir to /home/me/.local/share/wineprefixes/default : No such file or directory
  ```
- doing `WINEPREFIX='' flatpak run.com.usebottles.bottles`

  In logs I would get lines like
  ```
  (08:18:23) INFO Using WINE Registry CLI 
  wine: invalid directory  in WINEPREFIX: not an absolute path
  ```

**Comment by mirkobrombin** [comment]
So this is actually the same bug as #979
