### ISSUE TITLE
[Improvement] Make the navigation in the runners more readable and pleasant

### ISSUE THREAD

**Issue by EvoXCX** [bottlesdevs/Bottles#1057]
Hey,
I noticed that the runners are getting more and more numerous and it's getting complicated to read. The goal is not to clean up the number of runners (some soft asks for old runners) but rather to categorize them in dropdowns or something else that would make more visible for example only Caffe or GE runners.

Thanks for your hard work

**Comment by mirkobrombin** [comment]
Thanks for reporting. I will check if it will be possible to improve
