### ISSUE TITLE
[Request] Pacstall support  

### ISSUE THREAD

**Issue by niksingh710** [bottlesdevs/Bottles#1058]
Support for the application via Pacstall for debian based distro or a PPA to get latest updates instantly. AUR alternative for DEBIAN

**Comment by mirkobrombin** [comment]
Looks interesting, btw I’ve no time for this so I will keep this opened so maybe other users can join and help

**Comment by Henryws** [comment]
https://github.com/pacstall/pacstall-programs/pull/802

There's a PR already in the making!

**Comment by cat-master21** [comment]
This is only for bottles v1, Regular bottles needs compiling sadly.

**Comment by mirkobrombin** [comment]
V1 is still supported but very very old 😅

**Comment by trymeouteh** [comment]
Would like to see a maintained and compiled pacstall package of Bottles.

**Comment by mirkobrombin** [comment]
There is so much work already, we can’t put effort on this too. Feel free to include and maintain it as an unofficial package.
