### ISSUE TITLE
[BUG] New bottle has no network access

### ISSUE THREAD

**Issue by tsmithe** [bottlesdevs/Bottles#1063]
**Describe the bug**
New bottle has no network access. Possible sandboxing issue?

**Installation**
 - Method: Flatpak on Debian testing
 - Version 2022.2.14-trento

**To Reproduce**
1. Install Bottles using Flatpak on Debian testing
2. Create a new bottle
3. Open cmd.exe
4. ping 8.8.8.8  (or even 127.0.0.1)
5. "PING: transmit failed. General failure."
6. Other network access attempts also fail.

**Expected behavior**
Bottles should be able to access the network.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: testing
 - Display server: sway (wayland)

**Comment by tsmithe** [comment]
Hmm, actually I think this might be a bug in the app I'm using, accentuated (apparently) by WINE's ping not working... Closing for now; sorry for the noise.

**Comment by mirkobrombin** [comment]
No problem, reach us if you get other issues :D
