### ISSUE TITLE
[Request] Option for Discrete GPU per program

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#1065]
**Is your feature request related to a problem? Please describe.**
I've a bottle for a bunch of Indie Games I have. Some of them require a Discrete GPU to work, while most perform well with the iGPU.

**Describe the solution you'd like**
It would be nice if one could select Discrete GPU for per program added. Every program could have a "Use Discrete GPU" option with 3 options, namely "Yes", "No", "Follow Global Settings"

**Comment by mirkobrombin** [comment]
We're going to do this by default with the Layered environment, where the settings are no longer per bottle but per program instead. I think it is possible to take it to all the other envs too without too many complications.

**Comment by mirkobrombin** [comment]
Ref #510

**Comment by VarLad** [comment]
@mirkobrombin Sorry to use this issue to ask a question
GE-Proton comes with its own DXVK and VKD3D right?
When I use it in Bottles, are the DXVK and VKD3D being used are the one by GE-Proton or the one by Bottles?

**Comment by mirkobrombin** [comment]
Bottles don’t use the one coming with proton. Also please consider reading this https://github.com/bottlesdevs/Bottles/issues/1582

**Comment by VarLad** [comment]
@mirkobrombin I just noticed, Wine-GE also provides its own vkd3d-proton.
Can Bottles use that?

**Comment by mirkobrombin** [comment]
Just keep dxvk disabled in bottles

**Comment by VarLad** [comment]
@mirkobrombin Disabling vkd3d just crashes the game for me on Wine-GE-7-11
Also, doesn't Wine-GE often update vkd3d-proton to the latest git? 
"Ours" is comparatively older right?

**Comment by VarLad** [comment]
@mirkobrombin Sorry for the late reply. Not every version, but in some versions I spot this:
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-17

> dxvk updated to latest git
> vkd3d-proton updated to latest git
> gstreamer libraries updated

**Comment by mirkobrombin** [comment]
It’s weird but may be possible

**Comment by VarLad** [comment]
@mirkobrombin Is it feasible to actually use the versions provided by Wine-GE? 
It would be nice if I could do that
If yes, should I open a Feature Request issue for this?

**Comment by mirkobrombin** [comment]
This mean alter Bottles for just 1 runner, sounds something possible but maybe too much effort. As a workaround, make a new bottle without turning on dxvk, then close and set it to enabled in bottle.yml

**Comment by VarLad** [comment]
@mirkobrombin Trying that but the game refuses to run that way. 
I'd reckon its because of the deps.

Also, it'd be nice if Wine-GE could provide an option to use its own VKD3D since VKD3D keeps adding compatibility for new games and generally moves fast, but has a bi-yearly release, which is bad for playing some games.

**Comment by mirkobrombin** [comment]
With 2022.7.14 we will distribute our new runner based on Proton so you may want try it instead

**Comment by VarLad** [comment]
@mirkobrombin Would that runner provide git build of VKD3D?

**Comment by mirkobrombin** [comment]
No
