### ISSUE TITLE
[BUG] Crash when installed on an immutable os

### ISSUE THREAD

**Issue by WannaCyp0r** [bottlesdevs/Bottles#1066]
**Describe the bug**
Bottles crash with following output:
```
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```
The issue will be fixed if I create the directory manually. 

**Installation**
 - Method: Flatpak
 - Version `2022.2.14-trento`
 
**To Reproduce**
1. Install fedora silverblue
2. Install bottles from flathub
3. Launch bottles from desktop
4. 
5. Launch bottles from terminal
6. Bang

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 35

**Comment by mirkobrombin** [comment]
Bottles is entirely developed on Silverblue :D 

Btw I think it is missing something like compat lib. Try `flatpak install org.gnome.Platform.Compat.i386` and `flatpak update`

**Comment by WannaCyp0r** [comment]
> Bottles is entirely developed on Silverblue :D
> 
> Btw I think it is missing something like compat lib. Try `flatpak install org.gnome.Platform.Compat.i386` and `flatpak update`

Confirmed, `flatpak install org.gnome.Platform.Compat.i386` fixes the issue.
Looks like a missing dependency(or gnome-software didn't install it for some reason).
