### ISSUE TITLE
[BUG] Window of any installed application is very small

### ISSUE THREAD

**Issue by dar-kod** [bottlesdevs/Bottles#1067]
**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

I do not know, is this a bug, or I didn't set up something correct. I just created my bottle and wanted to install some application, but the screen of application is about 3 times smaller than it should be, so it is almost impossible to read what is written.

**Desktop:**
 - OS: Ubuntu
 - Version 20.04
 - Display server: probably GDM3 as I have never changed it

**Comment by mirkobrombin** [comment]
You can increase wine apps dpi from winecfg

**Comment by mirkobrombin** [comment]
Ya currently the flatpak cannot generate desktop entries due to lack of permissions.

**Comment by dar-kod** [comment]
I found this instruction in [documentation](https://docs.usebottles.com/bottles/run-.exe-.msi-.bat-.lnk-files#launch-from-cli-supports-.lnk), but still it is not clear for me what to do. Is there any full description how to do it?

**Comment by mirkobrombin** [comment]
You need to place a new desktop entry (example.desktop) in your ~/.local/share/applications path:

```
[Desktop Entry]
Name=APPNAME
Exec=bottles -e 'PATH/TO/EXECUTABLE' -b 'BOTTLE_NAME'
Type=Application
Terminal=false
Categories=Application;
Icon=com.usebottles.bottles
Comment=APP_DESCRIPTION

# Actions
Actions=Configure;
[Desktop Action Configure]
Name=Configure in Bottles
Exec=bottles -b 'BOTTLE_NAME'
```

**Comment by dar-kod** [comment]
@mirkobrombin thank you, but there is no "Allow Launching" option. The other thing is that my application doesn't run anymore with Bottles.
