### ISSUE TITLE
[BUG] Bottle path problems after re-naming existing bottle

### ISSUE THREAD

**Issue by Dhizaes** [bottlesdevs/Bottles#1073]
**Describe the bug**
Bottles doesn't respect paths after re-naming existing bottle. I removed my AUR version and installed Flatpak version, give permission to Bottles for folders where i'm keeping my bottles. I just renamed my bottle from LauncherSet to Launchers in Bottles UI. When i use "Browse" button in Details & Utilities, it sends me to "/run/user/1000/doc/5cec2296/Bottles/LauncherSet/" but i'm keeping my bottles in "/home/dhiz/Games/Bottles". 

I tried to find what is wrong with it and i used text editor for "bottle.yml" file in bottle directory. It shows "/home/dhiz/Games/LauncherSet" everywhere, every path where it needs, but as i said i changed its name to Launchers. When i look to my bottle directory, the path is "/home/dhiz/Games/Launchers" but bottle.yaml still uses LauncherSet. I changed every name in it by hand, now it sends me to correct directory. Before i changed it to correct name i can't open some *.exe files even path is correct(tried to test it in terminal, shows correct path but still can't find where it is).

_Now i have another problems, of course... I blame Flatpak for this but i need to test it. The problem is, Cloud save isn't work on Epic Games Launcher and i think it isn't work on Ubisoft Connect too(it isn't gave any error but i don't get my save files). Before Flatpak version i didn't have this problem. Maybe this problem is came from Bottles or Flatpak, maybe from my OS, maybe from Launchers... I really don't know it, i didn't use Flatpak before. But i'm still adding this problem to this Issue, maybe your eyes just catch something about it in somewhere if it is from your side._

**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

**To Reproduce**
1. Remove AUR(or maybe another package repository except Flatpak, i suppose) version of Bottles
2. Install Flatpak version of Bottles
3. Run Bottles from terminal for finding path problems
4. Get your previous bottle with adding custom bottle path from Bottles settings
5. Change your bottle name in Bottles UI
6a. Try to open your bottle path with Browse button in Details & Utilities page
6b. Try to open any Windows application with your bottle
7. See wrong paths and errors

**Expected behavior**
1. Give right bottle path
2. Open application without path error

**Desktop (please complete the following information):**
 - OS: Arch
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Thanks for reporting. Planning a fix

**Comment by Dhizaes** [comment]
> _Now i have another problems, of course... I blame Flatpak for this but i need to test it. The problem is, Cloud save isn't work on Epic Games Launcher and i think it isn't work on Ubisoft Connect too(it isn't gave any error but i don't get my save files). Before Flatpak version i didn't have this problem. Maybe this problem is came from Bottles or Flatpak, maybe from my OS, maybe from Launchers... I really don't know it, i didn't use Flatpak before. But i'm still adding this problem to this Issue, maybe your eyes just catch something about it in somewhere if it is from your side._

Well, this one is my fault. I forgot to add Documents folder for Flatpak permission. Game saves is placed in Documents.

**Comment by mirkobrombin** [comment]
> > _Now i have another problems, of course... I blame Flatpak for this but i need to test it. The problem is, Cloud save isn't work on Epic Games Launcher and i think it isn't work on Ubisoft Connect too(it isn't gave any error but i don't get my save files). Before Flatpak version i didn't have this problem. Maybe this problem is came from Bottles or Flatpak, maybe from my OS, maybe from Launchers... I really don't know it, i didn't use Flatpak before. But i'm still adding this problem to this Issue, maybe your eyes just catch something about it in somewhere if it is from your side._
> 
> Well, this one is my fault. I forgot to add Documents folder for Flatpak permission. Game saves is placed in Documents.

Nice :D

**Comment by mirkobrombin** [comment]
It seems this has already been fixed as I can't reproduce. I tried to select a different path for the bottles (where I put some) and after a rename it kept working, even the configuration file is correct. Regarding the `/run/..` path it is normal because the path is outside the sandbox and is granted on the spot (I could have explained myself badly about it).
