### ISSUE TITLE
[BUG] "Mouse Capture Fullscreen" setting resets itself

### ISSUE THREAD

**Issue by Dhizaes** [bottlesdevs/Bottles#1074]
**Describe the bug**
As i mentioned in header, "Mouse Capture Fullscreen" setting resets itself when i re-open Bottles, or even changing menus. I don't know if they are related to each other but full-screen mouse capturing in Wine config seems fine. Actually, I have this problem for a long time, including AUR version.

**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

**To Reproduce**
1. Open Preferences in current bottle
2. Change "Mouse Capture Fullscreen" to enabled
3. Change menus from left side and came back to Preferences, or re-open Bottles
4. "Mouse Capture Fullscreen" disabled again

**Expected behavior**
"Mouse Capture Fullscreen" needs to keep what i gave as setting

**Desktop (please complete the following information):**
 - OS: Arch
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
I understand what cause the problem, planning a fix
