### ISSUE TITLE
[BUG] "Desktop Entry" Shortcut Doesn't Run Program with Arguments as Launching from Within Bottles

### ISSUE THREAD

**Issue by erockce** [bottlesdevs/Bottles#1080]
**Describe the bug**
First reported in the forum, "["Desktop Entry" Shortcut Doesn't Run Program with Options](https://forums.usebottles.com/d/64-desktop-entry-shortcut-doesnt-run-program-with-options)"

**Installation**
 - Method: `yay bottles`
 - Version: `2022.2.14-trento`

**To Reproduce**
1. Ensure `gamemode` and `mangohud` are installed. Ensure executable are accessible from the `$PATH`
1. Create a bottle for a game
1. Add a Program, ("Add a custom executable path")
1. Use "Change launch options", and specify the following as arguments: `gamemoderun mangohud %command%` then save
1. Use "Add desktop entry" function to create a `.desktop` file in the user's `.local/share/applications` directory
1. Close Bottles
1. Run the new Bottle program from the desktop shortcut
1. Note that MangoHud is not running with the game as it does when launching when Bottles is running
1. Note that Gamemode is not running by checking the status from a terminal using `gamemode -s`

**Expected behavior**
When running the Bottle program from a desktop shortcut:
1. MangoHud *should be* running as an overlay with the game, the same behavior as if it were launched from the program configuration when Bottles is running
1. Gamemode *should be* running with the game, , the same behavior as if it were launched from the program configuration when Bottles is running.  The status of Gamemode may be verified from a terminal using the `gamemode -s` command

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: EndeavourOS (_Arch Linux_ variant)
 - Version: Atlantis
 - Display server: Xorg 21.1.3-6
 - Window Manager/Display Environment: XFCE 4.16

**Comment by tgschultz** [comment]
I believe I have encountered a related problem: The .desktop file created for Notepad++ doesn't launch the application. However, doubling every backslash in the windows path specified after `-e` on the `Exec` line allows it work. Seems like a weird escaping issue of some kind.

**Comment by mirkobrombin** [comment]
Can you share the desktop entry content?

**Comment by erockce** [comment]
@mirkobrombin for me here is an example of a minimum desktop entry for a game that does work with Bottles.  It is similar to what was described in my forum post:
```
[Desktop Entry]
Version=1.1
Type=Application
Name=Guild Wars
Comment=Launch Guild Wars using Bottles
Icon=guildwars-32x32
Exec=bottles -b 'Guild-Wars' -e /opt/games/windows/GW/Gw.exe
Actions=
Categories=Game;
```

I've obviously customized it a little, but the `Exec` line is what I believe you are most interested.

I generally don't install applications or games "inside" Wine prefixes. I've not had problems in the past with this convention using PlayOnLinux, Steam, or more manual setups using `winetricks`.

**Comment by mirkobrombin** [comment]
> @mirkobrombin for me here is an example of a minimum desktop entry for a game that does work with Bottles. It is similar to what was described in my forum post:
> 
> ```
> [Desktop Entry]
> Version=1.1
> Type=Application
> Name=Guild Wars
> Comment=Launch Guild Wars using Bottles
> Icon=guildwars-32x32
> Exec=bottles -b 'Guild-Wars' -e /opt/games/windows/GW/Gw.exe
> Actions=
> Categories=Game;
> ```
> 
> I've obviously customized it a little, but the `Exec` line is what I believe you are most interested viewing.
> 
> I generally don't install applications or games "inside" Wine prefixes. I've not had problems in the past with this convention using PlayOnLinux, Steam, or more manual setups using `winetricks`.

Using Flatpak? If true, you need to give it permissions to /opt/games path, otherwise Bottles will not reach it

**Comment by erockce** [comment]
Not using Flatpak.  Installed Bottles by `yay` or `pacman` on Archlinux.

**Comment by IAmV0id** [comment]
Same problem here, the shortcut launches bottles, but not the app.
Here's the contents of my .desktop file
`[Desktop Entry]
Name=VEXcode V5
Exec=bottles -e 'None' -b 'Vexcode V5'
Type=Application
Terminal=false
Categories=Application;
Icon=com.usebottles.bottles-program
Comment=Launch VEXcode V5 using Bottles.
Actions=Configure;
[Desktop Action Configure]
Name=Configure in Bottles
Exec=bottles -b 'Vexcode V5'`

**Comment by mirkobrombin** [comment]
A new update is coming that fixes a problem with desktop entries and the cli

**Comment by DrEVILish** [comment]
Currently using Flatpak and I think I've got the same bug, I've given it HOST access while I'm testing things, I know that's not secure so bite me.

Anyway, while using the Bottles GUI I can open one of the "Programs" stored in the tab by clicking the play button. However when trying to lauch it from the "Add desktop entry" 's entry in my "start" menu it bugs out.
HTOP filter "wine" shows the application start with a different command thing about it for 5 seconds then promptly close along with the wine server.

``` [Desktop Entry]
Name=plutonium
Exec=flatpak run com.usebottles.bottles -e '/mnt/games/wineGames/plutonium.exe' -b 'Plutonium'
Type=Application
Terminal=false
Categories=Application;
Icon=com.usebottles.bottles-program
Comment=Launch plutonium using Bottles.
Actions=Configure;
[Desktop Action Configure]
Name=Configure in Bottles
Exec=flatpak run com.usebottles.bottles -b 'Plutonium'
 ```

Tested with two different applications in two different bottles.

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by DrEVILish** [comment]
I'm happy to test anything you wanna throw at me.
Really great work on the App, it really ties together what wine should be into a tidy GUI!!

**Comment by erockce** [comment]
From relatively recent updates there is support now for both Gamemode and MangoHUD support (nice!) integrated with Bottles.

At the time I was calling them both using the command-line when I first reported this issue.

With that in mind I don't see a reason to keep this issue open now.

**Comment by mirkobrombin** [comment]
Fine, closing. Thanks again for reporting.

**Comment by RedSnt** [comment]
> I believe I have encountered a related problem: The .desktop file created for Notepad++ doesn't launch the application. However, doubling every backslash in the windows path specified after `-e` on the `Exec` line allows it work. Seems like a weird escaping issue of some kind.

Omg, this issue was driving me insane, because the same command would effortlessly launch from the terminal. Makes so much sense now.
