### ISSUE TITLE
[BUG] Bottles Does Not Respect the Display Environment's "Default Applications, Web Browser" Setting

### ISSUE THREAD

**Issue by erockce** [bottlesdevs/Bottles#1081]
**Describe the bug**
Bottles directing to documentation or the forum always opens the links with Firefox instead of using my set default Web Browser which is set to Google Chrome.

**Installation**
 - Method: `yay bottles`
 - Version: `2022.2.14-trento`

**To Reproduce**
1. Start Bottles
1. Select from the "Hamburger" menu...
    - Select the "Documentation" menu option 
    - or select the "Forums" menu option 
1. Either of the menu item actions open a website page using Mozilla Firefox web browser and not the default web browser

**Expected behavior**
1. When selecting the "Documentation" menu item, Bottles should open the website using the web browser set from my desktop environment configuration
1. When selecting the "Forums" menu item, Bottles should open the website using the web browser set from my desktop environment configuration

**Screenshots**
My Default Applications "Internet" setting [screenshot](https://user-images.githubusercontent.com/17682973/154871826-f43fc598-36a8-42dc-ae7f-db27d8353973.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS (_Arch Linux_ variant)
 - Version: Atlantis
 - Display server: Xorg 21.1.3-6
 - Window Manager/Display Environment: XFCE 4.16

**Comment by EvoXCX** [comment]
I just tested on my side is not reproducible, it seems that it comes from your configuration and not Bottles.

Try again to set your preferred browser as default!

**Comment by erockce** [comment]
This issue is 100% Reproducible, every time!!!

Attached is "[bottles-opening-documentation-w-firefox-20220227-150912-user-redacted.log](https://github.com/bottlesdevs/Bottles/files/8149568/bottles-opening-documentation-w-firefox-20220227-150912-user-redacted.log)" capturing use of Bottles. Line `24504` is the start of Bottles opening "Documentation".

Further down is the start of Bottles "looking for web browsers".

This is interesting...

```
access("/usr/bin/xdg-open", X_OK)       = 0$
```

The `xdg-open` command is found but not used apparently to open links with my chosen default web browser of Google Chrome when Firefox installed.

Instead Bottles settles on opening the "Documentation" link with Firefox because it is the first found known web browser executable, despite looking for other available browsers.
```
access("/usr/bin/firefox", X_OK)        = 0$
```

Seems like Bottles is _brute-forcing_ a search for available browsers and using the first available.

Below summarizes my systematic testing with web browsers installed and how Bottles opens the web links.

| Default Browser Preference Set | Browsers Installed | Bottles Behavior Opening Docs or Forums |
| - | - | - |
Google Chrome	| Google Chrome	| Opens with Google Chrome |
Google Chrome	| Google Chrome, Icecat | Opens with Google Chrome |
Google Chrome	| Google Chrome, Mozilla Firefox | Opens with *Mozilla Firefox* |
Google Chrome	| Google Chrome, Mozilla Firefox ESR | Opens with Google Chrome |
Google Chrome	| Google Chrome, Mozilla Firefox, Mozilla Firefox ESR | Opens with *Mozilla Firefox* |

Only when Google Chrome is the only browser installed, or with a browser that Bottles does not recognize, does Google Chrome get used to open browser links.

Reference of web browser Archlinux packages used testing:
* [Google Chrome](https://aur.archlinux.org/packages/google-chrome)
* [Icecat](https://aur.archlinux.org/packages/icecat)
* [Mozilla Firefox](https://archlinux.org/packages/extra/x86_64/firefox/)
* [Mozilla Firefox ESR "bin"](https://aur.archlinux.org/packages/firefox-esr-bin)

**Comment by mirkobrombin** [comment]
Sorry, I'm not able to reproduce this. I've Firefox and Chromium installed and if I switch the default one, Bottles pick up the correct one. Also, we use the built-in python [webbrowser](https://docs.python.org/3/library/webbrowser.html) module which handle this internally.
