### ISSUE TITLE
[BUG] Error: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by josue2363** [bottlesdevs/Bottles#1082]
**Describe the bug**
I installed the Bottles app from the "games:tools"  ([https://build.opensuse.org/package/show/games:tools/bottles](https://build.opensuse.org/package/show/games:tools/bottles)) repository on openSUSE Leap 15.3. When running Bottles in terminal, I get the following error:

josue@josue-pc:~> bottles
Traceback (most recent call last):
  File "/usr/bin/bottles", line 56, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 26, in <module>
    from bottles.widgets.message import MessageEntry
  File "/usr/share/bottles/bottles/widgets/message.py", line 22, in <module>
    from bottles.backend.managers.notifications import NotificationsManager # pyright: reportMissingImports=false
  File "/usr/share/bottles/bottles/backend/managers/notifications.py", line 27, in <module>
    class NotificationsManager:
  File "/usr/share/bottles/bottles/backend/managers/notifications.py", line 39, in NotificationsManager
    @lru_cache
  File "/usr/lib64/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

**Installation**
 - Method: RPM for openSUSE Leap 15.3
 - Version: 2022.2.14

**To Reproduce**
1. Install Bottles app RPM package for openSUSE Leap 15.3
2. Then try running Bottles.

**Expected behavior**
The Bottles application run correctly.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap
 - Version 15.3
 - Display server: Xorg Server
 
**Additional context**
I just downloaded the Bottles RPM package for openSUSE Leap 15.3 and tried to run the application. Unfortunately I don't have advanced knowledge of the Python programming language, so I need help with this, so that Bottles can be available in the Regata OS app store.

**Comment by mirkobrombin** [comment]
Bottles doesn’t work on python 3.6

**Comment by mirkobrombin** [comment]
You are welcome.
