### ISSUE TITLE
[BUG] Interface doesn't work as expected when opening from the steam library

### ISSUE THREAD

**Issue by KaiNickson** [bottlesdevs/Bottles#1084]
**Describe the bug**
When adding bottles as a non steam game in steam (I tried to make some publicity in my friendlist) the app correctly opens but when  I click on one of my bottles nothing happens except the "go back" arrow lights up indicating that something changed.
The bottle entries still get highlighted when I hover over them and other menu's and buttons work ("new bottle" opens the correct window, and things like "about bottles", "preferences", ... are perfectly working ).
Opening bottles from the KDE desktop or terminal work normally.

**Installation**
AUR under [Manjaro]
2022.2.14-trento

**To Reproduce**
1. In Steam click "Games" 
2. Click "Add a non-steam game to my library..."
3. Add a check to the "bottles" entry 
4. Click "Add selected programs"
5. Double-click on the bottles entry in the steam library
6. Click on the entry of the bottle I want to use
"
**Expected behavior**
I see the details of the bottle and can run an installed program

**Screenshots**
![Screenshot_20220223_223536](https://user-images.githubusercontent.com/4718050/155413018-346c484a-95e8-4abd-a8e8-3768e1538ae1.png)
![Screenshot_20220223_224208](https://user-images.githubusercontent.com/4718050/155413462-c0c26c8f-dfbb-4838-a5f2-52a94c8bd94e.png)

**Desktop:**
 - OS: Manjaro
 - Version 21.2.3 Qonos
 - Display server: Xorg
 - -DE: KDE Plasma

**Comment by mirkobrombin** [comment]
Can you post the output of Bottles?

**Comment by KaiNickson** [comment]
Sorry for the ignorance, but what is meant by "output"?

**Comment by mirkobrombin** [comment]
Like running steam from terminal and then run bottles and check the output on terminal

**Comment by mirkobrombin** [comment]
Closing due to missing response
