### ISSUE TITLE
[BUG]  AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by 32nmud** [bottlesdevs/Bottles#1090]
**Describe the bug**
This bug is pretty simple. When trying to launch specifically the flatpak version, it will throw a GTK error and then spit out a python stacktrace and fail to launch. No GUI is ever loaded.

**Installation**
 - Method: Flatpak
 - Version: 2022.2.14-trento

**To Reproduce**
Just launch the app. Both from terminal and from GUI will result in a failed launch.
From terminal will provide the mentioned errors.

**Expected behavior**
The application should successfully open.

**Screenshots**
Not a screenshot, but here are the errors:
```
Gtk-Message: 00:48:31.707: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/app/bin/bottles", line 56, in <module>
    from bottles import main
  File "/app/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/app/share/bottles/bottles/window.py", line 26, in <module>
    from bottles.widgets.message import MessageEntry
  File "/app/share/bottles/bottles/widgets/message.py", line 22, in <module>
    from bottles.backend.managers.notifications import NotificationsManager # pyright: reportMissingImports=false
  File "/app/share/bottles/bottles/backend/managers/notifications.py", line 24, in <module>
    from bottles.backend.globals import API
  File "/app/share/bottles/bottles/backend/globals.py", line 34, in <module>
    class Paths:
  File "/app/share/bottles/bottles/backend/globals.py", line 57, in Paths
    if data.get("custom_bottles_path"):
  File "/app/share/bottles/bottles/backend/managers/data.py", line 97, in get
    return self.__data.get(key)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Desktop**
 - OS: Arch
 - Version Tested on kernel 5.15.25-lts and 5.16.10
 - Display server: Xorg

**Additional context**
Just for clarity, the AUR version works fine for me. However, the flatpak version is preferable due to containerization.

**Comment by mirkobrombin** [comment]
The gtk one is a non blocking thing, the blocking one is the python error. Planning a fix.

Can you try to remove the data.yml file as a workaround?

**Comment by mirkobrombin** [comment]
I'm not able to reproduce this. Can you attach your data.yml file?

**Comment by 32nmud** [comment]
As an update, things seemed a little off where the data.yml file was stored (lots of other files were empty as well), so I copied everything in that directory out and relaunched the application and it seems to be working now. I'll try and install a program and see how that goes.

**Comment by mirkobrombin** [comment]
Did you migrate from AUR to Flatpak copying the bottles folder? Because the runtime should be out of the bottles folder when in Flatpak and this causes a lot of errors.

**Comment by mirkobrombin** [comment]
I will keep the issue open pending other reports
