### ISSUE TITLE
[Request] add mangohud

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1092]
Hi, i saw lots of steamdeck reviews and mangohud look very cool for performance viewing. The DXVK HUD is very limited. Please look into possible to integrate MangoHUD into Bottles. Would be very cool

https://github.com/flightlessmango/MangoHud

"A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more."

**Comment by mirkobrombin** [comment]
Hi, tracking here #530 🙂
