### ISSUE TITLE
[BUG] Command Line closing immediately with Konsole and xterm

### ISSUE THREAD

**Issue by 1nikolas** [bottlesdevs/Bottles#1095]
**Describe the bug**
In a bottle, when I open something involving the terminal (either that's launching an exe with "Launch with terminal" option or opening the bottle's command line) the terminal opens for a split second and then closes. This happens with both konsole and xterm (so it is probably a bottles issue??). As a side note, when launching an exe with "Launch with terminal" option, the exe never runs. This happens with all bottles.

**Installation**
 - Method: aur (yay)
 - Version: upstream (bottles-git)

**To Reproduce**
1. Create a bottle
2. Open Command Line
3. Immediately closes

**Expected behavior**
Terminal stays open

**Screenshots**
![Screencast 2022-02-27 15^ 23^ 16-00 00 00 000-00 00 08 066](https://user-images.githubusercontent.com/30593419/155884368-6f3bf307-2529-4ee4-b820-ffcf9d1307bd.gif)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version: latest
 - Display server: Xorg

**Additional context**
This log occurs when launching the command line
```
(15:47:42) INFO Using WINE Command Line -- launch_terminal 
(15:47:42) WARNING No GPU vendor found, keep going without setting VK_ICD_FILENAMES.. 
```

**Comment by mirkobrombin** [comment]
I think there is a problem with Konsole integration. We will investigate this, thanks for reporting.

**Comment by 1nikolas** [comment]
![image](https://user-images.githubusercontent.com/30593419/155889653-e9edb5bc-1f34-441c-b13e-bd1836a299c6.png)
Problem still persists but now it throws this error (had to do a screen record to get the screenshot)

**Comment by 1nikolas** [comment]
Also I don;t think it's a Konsole issue. Same thing happens with xterm

https://user-images.githubusercontent.com/30593419/155889738-42beea69-a395-4144-a9d2-e75737fd1164.mp4

**Comment by mirkobrombin** [comment]
I'm able to make it works with both gnome-terminal and easyterm. Maybe something is broken in the bottle? Are you able to launch winecfg or any executable?

**Comment by 1nikolas** [comment]
> I'm able to make it works with both gnome-terminal and easyterm. Maybe something is broken in the bottle? Are you able to launch winecfg or any executable?

Yes the bottle works fine. This happens on every bottle. Let me try gnome-terminal

**Comment by 1nikolas** [comment]
Okay I didn't get to run gnome-terminal on kde but xfce4-terminal works.. Weird

**Comment by mirkobrombin** [comment]
This is actually weird :smile: I'll try with konsole or xterm asap

**Comment by jarrard** [comment]
Can confirm this happening for me also.

**Comment by 1nikolas** [comment]
I think this is fixed now, thanks
