### ISSUE TITLE
[BUG] proton-7.3-ge-1 wrong path

### ISSUE THREAD

**Issue by fishxz** [bottlesdevs/Bottles#1099]
**Describe the bug**
```/bin/sh: line 1: /var/home/***/.var/app/com.usebottles.bottles/data/bottles/runners/Proton-7.3-GE-1/files/bin/wine64: No such file or directory```
with the latest proton-ge update the naming of the folder "files" changed to "dist"
```/var/home/***/.var/app/com.usebottles.bottles/data/bottles/runners/Proton-7.3-GE-1/dist/bin```

**Installation**
 - Method: flatpak
 - Version: 2022.2.28-trento

**To Reproduce**
install proton-7.3-ge-1

**Desktop (please complete the following information):**
 - OS: fedora
 - Version 35
 - Display server: wayland

**Comment by mirkobrombin** [comment]
So they moved to the dist path again...

**Comment by mirkobrombin** [comment]
So they moved again to the dist path... This was already fixed, seems like a regression. Working on a hotfix, thanks for reporting!
