### ISSUE TITLE
[BUG] Gnome shortcut invalid

### ISSUE THREAD

**Issue by totalgaara** [bottlesdevs/Bottles#110]
**Describe the bug**

Hi, After installing an app, for my case i tried to install Offce 2010. Everything runs fine but i cannot start the app from the gnome application menu. My only way to run word for example is to go to Bottles > CMD typing "explorer.exe" and then look for word.exe 

Here is the content of the gnomeshortcut bottles automatically created : 
```[Desktop Entry]
Name=Microsoft Word 2010
Exec=env WINEPREFIX="/home/dylan/.local/share/bottles/bottles/Word-2010" /home/ubuntu/buildbot/runners/wine/lutris-6.0-x86_64/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/dylan/.local/share/bottles/bottles/Word-2010/dosdevices/c:/users/dylan/Start\\ Menu/Programs/Microsoft\\ Office/Microsoft\\ Word\\ 2010.lnk
Type=Application
StartupNotify=true
Comment=Créez et modifiez des documents d’aspect professionnel tels que des lettres, des articles, des rapports et des brochures à l’aide de Microsoft Word.
Icon=0575_wordicon.0
StartupWMClass=winword.exe
```
I've find weird the path of " `/home/ubuntu/buildbot/runners/wine/` and tried to correct it and no luck

**Installation**
 - Method: AUR 
 - Version : 2.1.0.4 (in about bottle)

**To Reproduce**
1. Install an app, example notepad++
2. Try to run the app by running the shortcut that has been created

**Expected behavior**
Open the app

**Desktop (please complete the following information):**
 - OS: Manjaro - Gnome Edition [arch]

**Comment by mirkobrombin** [comment]
Can you try starting the program from the Programs page in Bottles?

**Comment by totalgaara** [comment]
Office is  not present unfortunatly : 
![Capture d’écran du 2021-01-27 13-22-06](https://user-images.githubusercontent.com/1378194/105990427-bbffbd00-60a2-11eb-8292-ca3bf7afce5c.png)

Notepad++ otherwise is launching fin when i press the play button

**Comment by mirkobrombin** [comment]
> Office is not present unfortunatly :
> ![Capture d’écran du 2021-01-27 13-22-06](https://user-images.githubusercontent.com/1378194/105990427-bbffbd00-60a2-11eb-8292-ca3bf7afce5c.png)
> 
> Notepad++ otherwise is launching fin when i press the play button

I think it's a problem I solved in Bottles v3, see if I can bring it to v2.

**Comment by totalgaara** [comment]
Do you think it could be possible to add a button to add apps manually in the list ? next to the refresh button

**Comment by mirkobrombin** [comment]
> Do you think it could be possible to add a button to add apps manually in the list ? next to the refresh button

In the new design we provide a context menu for each installed program, we can place it there.

**Comment by mirkobrombin** [comment]
#115 related
