### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by A6GibKm** [bottlesdevs/Bottles#1106]
Recently a new dark mode was introduced, this is a xdg-desktop-portal backed setting that will be picked by all mayor desktop environments in their next (or current in some cases) version.

Libhandy>=1.5 provides an easy way to opt-in to this, but there are some open problems:

- How to deal with the actual setting in the preferences windows. GNOME apps (and most Circle apps) have opted for removing the in-app setting in favor of following the system theme
- libhandy 1.6 is going to be released soon, so there is no stable versions supporting this for gtk3 yet, is it ok to depend on the current developer version?
- There are css styles that do work very well on dark mode like

![image](https://user-images.githubusercontent.com/11528996/156324410-f095c1b6-8761-4884-842e-04fabee165b3.png)

![image](https://user-images.githubusercontent.com/11528996/156324474-debf3cc5-87e3-49f5-aaa3-c70301d3552b.png)

![image](https://user-images.githubusercontent.com/11528996/156324534-012203ea-93bf-464c-a029-a7ec5ebb71e6.png)

I can submit a PR to support dark mode, but I would need to know how to deal with the in-app preference and if depending on libhandy 1.5 sounds good to you.

**Comment by mirkobrombin** [comment]
Nice!

About this:
> I would need to know how to deal with the in-app preference 

The switcher is updated according to the dedicated gsetting:
https://github.com/bottlesdevs/Bottles/blob/73df01e403712756285eee60acdc80fac5c682aa/src/views/preferences.py#L70

So to handle both system theme and user choice, we should use a dropdown or a three-button like for the sync type in the bottle preferences. 

Btw I think we can just remove this options an just use the system one, but there should be an environment variable to force the dark mode for the entire session, just for testing and development purposes.

**Comment by A6GibKm** [comment]
I think the best approach is to remove the button, and leave the setting in the gschema making it to force dark mode.

**Comment by mirkobrombin** [comment]
Can also be good

**Comment by SgtMooshroom** [comment]
> I agree

I strongly _disagree._ Unless you can tell us _exactly where the dconf file for the Flatpak is in Debian-based distros,_ then at least have the button enabled specifically on Debian-based distros.
