### ISSUE TITLE
[BUG] [Flatpak] font antialiasing missing

### ISSUE THREAD

**Issue by portaloffreedom** [bottlesdevs/Bottles#1108]
**Describe the bug**
The font rendering is broken in my particolar configuration, only if running on wayland, forcing the xorg protocol (using flatseal) font rendering works.

**Installation**
 - Method: Official Flatpak
 - Version: 2022.2.28-trento-2

**To Reproduce**
1. Open any window with some text in it

**Expected behavior**
Text should be smooth with font anti-aliasing enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/1150666/156386432-bd3ee61e-7e8e-4bd3-8f3c-9b576055fed0.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: latest
 - Display server: kwin_wayland
 - System Fonts: Fira Sans, anti-aliasing enabled, sub-pixel rendering RGB, hinting slight
 - System dark theme: ON

**Additional context**
Forcing the Xorg protocol it works fine.
It's possible that some fonts are not found and is fallbacking to an ugly font? not sure
AUR version works fine

**Comment by portaloffreedom** [comment]
update: flatpak version on opensuse tumbleweed works fine, but it does use the Breeze GTK theme and not Adawita.

**Comment by portaloffreedom** [comment]
The bug seems to be correlated to this: https://github.com/flatpak/flatpak/issues/2861
but none of the proposed solution in the thread worked for me

**Comment by mirkobrombin** [comment]
We are trying to reproduce the bug

**Comment by portaloffreedom** [comment]
The issue seems to be the dbus call ```gdbus call --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop --method org.freedesktop.portal.Settings.ReadAll \[\"org.gnome.settings-daemon.plugins.xsettings\"\]```
for me returns `(@a{sa{sv}} {},)` instead of something more complicated.

Anyway, seems to be unrelated to Bottles and more an issue of kde+gtk+flatpak, so I'm closing this

**Comment by mirkobrombin** [comment]
Nice found.

**Comment by vchernin** [comment]
As mentioned in that bug, is `xdg-desktop-portal-gtk` installed?
