### ISSUE TITLE
[BUG] Installation fails silently if checksum does not match

### ISSUE THREAD

**Issue by maufl** [bottlesdevs/Bottles#1115]
**Describe the bug**
Installation of Origin and Ubisoft launchers fail because of checksum errors, but the programs are still listed as installed.

**Installation**
 - Method: Flatpak on Arch Linux
 - Version: 2022.2.28-trento-2
 
**To Reproduce**
1. Create a new bottle for gaming
2. Try installing a launcher that has an incorrect checksum in the manifest
3. Installation does finish, no error is reported, the launcher is shown in the list of programms
4. Launching the program does not succeed, because it's not installed

**Expected behavior**
I would expect an error to be shown to the user, the installation to abort and the program to not appear in the list of installed programms.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling release
 - Display server: Gnome Wayland

**Additional context**
I only really figured out what happened once I started bottles from the command line.

In general, thanks for the great UI!

**Comment by mirkobrombin** [comment]
Thanks for reporting
