### ISSUE TITLE
[Request] Option to Import DXVK/WINE/NVAPI version package file into runners list.

### ISSUE THREAD

**Issue by jarrard** [bottlesdevs/Bottles#1120]
ATM to add custom or updated DXVK/WINE etc versions you need to go into local/share/bottles/<folder> and drop said extracted version into the folder. This does not show up in the preferences runner/dxvk lists but will show up in the components drop down list once inside a bottle.

A solution would be to add a option somewhere in the Preferences section of Runners and DXVK/VKD3D to Import custom versions to that list. Additionally give people the option (icon) to delete versions of runners/dxvk.

Why would anyone do this? because Bottles does not maintain a up to date runner or DXVK list. 
Already DXVK1.10 is out but bottle hasn't updated list. Additionally some people run different wine builds.

I just think this would be a nice feature to have. Just give a button to allow people to import direct from gz files. Pretty simple.

**Comment by mirkobrombin** [comment]
> ATM to add custom or updated DXVK/WINE etc versions you need to go into local/share/bottles/ and drop said extracted version into the folder. This does not show up in the preferences runner/dxvk lists but will show up in the components drop down list once inside a bottle.
> 
> A solution would be to add a option somewhere in the Preferences section of Runners and DXVK/VKD3D to Import custom versions to that list. Additionally give people the option (icon) to delete versions of runners/dxvk.
> 
> Why would anyone do this? because Bottles does not maintain a up to date runner or DXVK list. Already DXVK1.10 is out but bottle hasn't updated list. Additionally some people run different wine builds.
> 
> I just think this would be a nice feature to have. Just give a button to allow people to import direct from gz files. Pretty simple.

Bottles maintains DXVK and runners updates but latest release was slowed down due to a needed fix which was just released and should be available soon.

Btw your idea is great and should be implemented.

**Comment by mirkobrombin** [comment]
Tracking here #1321
