### ISSUE TITLE
[BUG] System shutdown/reboot hangs because of software launched through bottles

### ISSUE THREAD

**Issue by tf2professor** [bottlesdevs/Bottles#1124]
I've set a menu entry with alacarte to launch an application through Bottles. The menu entry executes the following commands:

bottles -b Bottle-Name -e "full_path_to_software.exe"

The application launches and works well, but when I go to shutdown or reboot my system, it hangs before forcing shutdown. When I don't launch the application, the issue doesn't happen. When I launch the application through the bottles GUI, instead of using the alacarte shortcut (which runs the commands above listed), the issue also doesn't happen.

Installed from the AUR, version 2022.2.28-trento-2

**To Reproduce**
Using Alacarte, create a menu entry which runs the terminal commands to launch an application through bottles, like this: 
bottles -b Bottle-Name -e "full_path_to_software.exe"
Launching the application through the created menu entry works, but the system hangs when shutdown/reboot, even if you manually close the application before issuing the shutdown/reboot command.

**Expected behavior**
I expected the system to shutdown/reboot normally, without hanging.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Display server: Xorg

**Additional context**

```
Journalctl had these messages about not being able to kill the windows application run through Botlles:
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Stopping timed out. Killing.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1520 (winedevice.exe) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1526 (winedevice.exe) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1530 (n/a) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1535 (winedevice.exe) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1547 (n/a) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1560 (n/a) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Killing process 1561 (n/a) with signal SIGKILL.
mar 07 09:38:48 benja-arch systemd[723]: app-gnome-alacarte\x2dmade\x2d9-1078.scope: Failed with result 'timeout'.
```

**Comment by mirkobrombin** [comment]
Closing as this is a wine related problem. Nothing we can fix in our end.
