### ISSUE TITLE
Please implement a features to run valorant in bottles.

### ISSUE THREAD

**Issue by rishuriya** [bottlesdevs/Bottles#1126]
The valorant game by riot games are not running on bottles. please try to make bottles in such a way that it run valorant. valorant are installed in bottles but keep asking to restart system. and when i restart the bottles with reboot ,Nothing happen and when i restart whole system still valorant ask to do restart. so please make bottles suitable for  valorant.

**Comment by mirkobrombin** [comment]
Valorant can't works with WINE because of its anticheat. Sorry.

**Comment by SlyPex** [comment]
@mirkobrombin  Hey there, isn't anticheat only a service which runs in the background ?
isn't there a way to just enable or start services under a bottle ?
Thanks in advance.

**Comment by Kapy2003** [comment]
I think just link vgtray.exe from the folder and then first launch the vgtray.exe then the valorant itself it might work.
