### ISSUE TITLE
[BUG] Display Settings won't let me emulate a 1440p virtual desktop

### ISSUE THREAD

**Issue by kozross** [bottlesdevs/Bottles#1132]
**Describe the bug**

The list of resolutions for virtual desktops in Display Settings (in Preferences) does not include 1440p (2560 x 1440).

**Installation**
 - Method: AUR package
 - Version 2022.2.28-trento-3

**To Reproduce**
1. Create a bottle.
2. Go to Preferences.
3. In Display Settings, click on the arrow in the menu for 'Use a virtual desktop'.
4. Observe the lack of 1440p resolution option.

**Expected behavior**

Any resolution up to the maximum supported by the monitor being used should be present as a choice.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Version not applicable (Arch is rolling-release)
 - Display server: Wayland
**Additional context**

**Comment by mirkobrombin** [comment]
Hi, is such resolution available on winecfg?

**Comment by kozross** [comment]
@mirkobrombin Yes - if you set it manually in `winecfg` it works as intended. You can in fact set any resolution you want, whether it's supported or not, since it's a free-entry pair of text boxes.

**Comment by mirkobrombin** [comment]
Nice
