### ISSUE TITLE
[BUG] Auto-detecting path to wine bin folder

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#1137]
This hotfix was recently released, which treats any runner with "Proton" in the name as a Proton runner:

- https://github.com/bottlesdevs/Bottles/commit/add43b4f8b23d58e05d20290d174fdd45c58d0b7

This issue is related. The official Proton runners use a "files" or "dist" folder:

- https://github.com/bottlesdevs/Bottles/issues/1099

But, the GloriousEggroll improved versions of Proton/Wine don't use any folder at all. `bin` is directly under the runner-folder.

- I personally use the Wine-GE-Proton. GloriousEggroll took Proton, removed the Steam-code that makes Proton break outside of Steam, and then rebased Wine-staging and other game patches on top of the De-Steamed Proton. As a result it's the best of all worlds, truly the best game compatibility of all runners I've used: https://github.com/GloriousEggroll/wine-ge-custom/releases/
- As mentioned, that release now contains "Proton" in the name, but doesn't use dist/files subfolders.
- Therefore, I get `~/.var/app/com.usebottles.bottles/data/bottles/runners/lutris-GE-Proton7-6-x86_64/files/bin/wine64: No such file or directory` from Bottles.
- Recently, a new commit was also merged which brings in that exact Wine-GE-Proton, which will trigger this bug since that version lacks dist/files subfolders: https://github.com/bottlesdevs/components/pull/116
- My temporary fix: I manually created a `files` folder (that's what the public version of Bottles looks for).

## Proposed solution:

Perhaps use Python's `pathlib.Path.glob()` and look for this pattern:

- Create a `Path(path to the wine runner's main folder)` object.
- Search its subfolders via `thatpathobject.glob(r"**/bin/wine64")`. This would return a list of all paths that were found anywhere in the runner's directory tree.
- Next, loop through all matches and pick the shortest path (in case of multiple matches).

Something like that may solve this forever.

**Comment by mirkobrombin** [comment]
fixing with the next hotfix, I'll improve the whole check with another release as I'm rewriting some stuff in the backend
