### ISSUE TITLE
[BUG] 2022.2.28-trento-4 Offiline mode doesn't works

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1141]
2022.2.28-trento-4 FLATPAK
No errors seen in logs.

I update to latest version "2022.2.28-trento-4" and when I started Bottles (with no internet) application screen is now empty and white except for the top "menu" bar that says I am offline and click to connect and see settings.

I was using dark mode before so not sure why it would change to light mode even if offline. I cannot see any bottles or anything.

I was able to downgrade to previous version "2022.2.28-trento-3" and lucky nothing was lost. very scary moment hahahahahaha thought i lost all of my games and saves.

I tried upgrading and had the same issue. The "Fixed a regression with offline mode" must have introduced new regression.

**Comment by mirkobrombin** [comment]
The funny thing is that you are hitting a regression which was not fixed in -4, as we just fix a wrong exception name
