### ISSUE TITLE
[BUG] LatencyFleX can be enabled despite the system is missing the Vulkan layer

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1146]
**Describe the bug**
LatencyFleX support need a vulkan layer to works. Currently there is no check for these and it will just silently fails.

**Fix**
- Check for common paths, if missing just disable the switcher
- Inject them directly in the environment, so the user don't need to install theme manually (need testing)

**Expected behavior**
Should not be enabled if the layer is missing.

**Additional context**
Doesn't hit the Flatpak as LatencyFleX vulkan layer came with the installation.

**Comment by vandpurnama** [comment]
i got error when opening bottles my installed apps is not showing on bottles if i disconnected the internet it's snow normally and terminal say's it's KeyError: 'latencyflex'... is it same error as above ?

![2022-03-12_10-44](https://user-images.githubusercontent.com/33601181/158002584-2f67b305-70e0-49fe-839d-f59bd429211e.png)

![2022-03-12_10-45](https://user-images.githubusercontent.com/33601181/158002570-6fa6e765-5cd6-439c-9549-ed9121d52a12.png)

Apps show when internet disconnected (image 1) and not visiblle when i connected to the internet (image 2)


**Terminal LOG :**

/usr/share/bottles/bottles/dialogs/generic.py:18: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GtkSource, Gdk, Handy, Pango, WebKit2
(10:35:13) INFO Performing Bottles checks... 
(10:35:13) INFO DXVKs found:
         - dxvk-1.9.4
 
(10:35:13) INFO VKD3Ds found:
         - vkd3d-proton-2.5
 
(10:35:13) INFO NVAPIs found:
         - dxvk-nvapi-v0.4
         - dxvk-nvapi-v0.5.2
         - dxvk-nvapi-v0.5.1
 
(10:35:13) INFO Runners found:
         - sys-wine-7.1

         - vaniglia-6.23
         - caffe-7.0
         - lutris-ge-7.1-1
 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 167, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/main.py", line 232, in do_activate
    win = MainWindow(
  File "/usr/share/bottles/bottles/window.py", line 89, in __init__
    self.manager = Manager(self)
  File "/usr/share/bottles/bottles/backend/manager.py", line 99, in __init__
    self.checks(install_latest=False, first_run=True)
  File "/usr/share/bottles/bottles/backend/manager.py", line 109, in checks
    self.organize_components()
  File "/usr/share/bottles/bottles/backend/manager.py", line 183, in organize_components
    catalog = self.component_manager.fetch_catalog()
  File "/usr/share/bottles/bottles/backend/component.py", line 166, in fetch_catalog
    catalog[category][component[0]] = component[1]
KeyError: 'latencyflex'

**Comment by mirkobrombin** [comment]
You should open a new issue, btw I think you are on a old release which doesn’t support the new repositories structure. Can you upgrade to 2022.2.28-4 or 2022.2.14 at least.
