### ISSUE TITLE
[BUG] Bottles doesn't start on pop os

### ISSUE THREAD

**Issue by mblithium** [bottlesdevs/Bottles#1147]
**Describe the bug**
It turns out that after a certain program update, which I don't remember exactly, Bottles stopped working. It no longer opens, even deleting its folder in "~/.var/app/" the problem still persists. Uninstalling and reinstalling doesn't work either. I've already tried to see logs in the terminal but the only things that appear when trying to start the program are:

`Gtk-Message: 20:38:09.518: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:38:09.518: Failed to load module "appmenu-gtk-module"
Gtk-Message: 20:38:09.725: Failed to load module "canberra-gtk-module"`

**Installation**
 - Method: Flatpak
 - Version: 2022.2.28-trento-4

**To Reproduce**
1. Open Bottles installed via flatpak on Pop!_OS? I don't think there's an accurate description of it.

**Expected behavior**
The program should open.

**Screenshots**
[Bottles doesn't open and stays like this.](https://snipboard.io/CQB1Ga.jpg)

**Desktop:**
 - OS: Pop!_OS 21.10
 - Version: 21.10
 - Display server: Xorg
 
**Additional context**
Kernel: 5.16.11; X11; X.Org 1.20.13; Flatpak: 1.11.2;

**Comment by mirkobrombin** [comment]
There is very poor info to be able to hypothesize something but I understand that you have no other ones given the situation.

Are you offline the moment you start it?

Have you changed any flatpak permissions?

**Comment by mirkobrombin** [comment]
Just removing the `~/.var/app/com.usebottles.bottles/data` directory. Can you try issuing a `flatpak update`?

**Comment by mblithium** [comment]
Yes and the problem still persisted. Fortunately it started working again when I restored Pop!_OS with the Recovery tool. Fortunately it started working again when I restored Pop!_OS with the Recovery Tool. I still don't know what may have caused the problem but for those who have the same problem it would be interesting to consider using System Recovery. ("Fresh Install", which does not lose user files).

**Comment by mirkobrombin** [comment]
Interesting

**Comment by GokulDas027** [comment]
I'm having the same issue on Pop OS 21.10
```
Gtk-Message: 12:20:15.082: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:20:15.309: Failed to load module "canberra-gtk-module"
```
And I've reinstalled both, and `xdg-desktop-portal-gtk is already the newest version (1.8.0-1build1)`

Fresh Install isn't an option, since it'll remove all the installed application.
@mblithium  please reopen the issue.

**Comment by mirkobrombin** [comment]
I have found that this problem affects other applications as well and tends to disappear like magic or after a reinstall. I don't think this is something we can fix in the project, as from what I see it is not dependent on the language but on a stalled instance of some interfering program.

Also the gnome control center had this problem https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/30

I can't see a solutions for this, closing for now. Feel free to add more details and comments if needed.

**Comment by GokulDas027** [comment]
Received updates for these packages today, and now it runs. I've installed the runner, haven't run any program.
```
libnss-systemd, libudev-dev, libudev1, libsystemd0, systemd, udev, systemd-timesyncd, systemd-sysv, libnss-mymachines, systemd-container, libpam-systemd, gnome-shell-extension-system76-power, pop-cosmic, touchegg
```
