### ISSUE TITLE
Run in Terminal Flag Only Followed on Default Wine

### ISSUE THREAD

**Issue by Ryu945** [bottlesdevs/Bottles#1150]
**Describe the bug**
Setting the run in terminal flag only works on default wine.   Other wines like system wines do not follow this flag.

**Installation**
 - Method: Mint XFCE repository
 - Version 2022.2.28-trento-3

**To Reproduce**
1. Change Wine version from default (ex.  Like system wine)
2. Change it so that the installer runs in terminal.
3. Install a program.

**Expected behavior**
To see the program executing in terminal like it does when you use the default wine.

**Actual behavior**
Only the default wine follows the run in terminal command.   Every other wine like system wine does not follow this.

**Desktop (please complete the following information):**
 - OS: Mint 20.2
 - Display server: 2:1.20.13-1ubuntu1~20.04.2

**Comment by mirkobrombin** [comment]
Does the Mint XFCE repository provide a flatpak?

**Comment by Ryu945** [comment]
I don't know if it comes by default or if me turning flat packs on when I installed Ungoogled Chromium previously caused this to show up.

Here is the version information I see:

Package:  com.usebottles.bottles
Version:  2021.7.28-treviso-2
Size 474.8 MB of disk space
Remote:  Flathub
Architecture x86_64
Branch:  Stable

**Comment by mirkobrombin** [comment]
Ya it's a flatpak

**Comment by Ryu945** [comment]
You mentioned that version 4  will fix a container creation error.  I only see version 3 in github right now  (treviso-3 vs treviso-4).   The repositories also only show up to version 3.

**Comment by Ryu945** [comment]
> Sorry I've forgot about this issue.
> 
> > Version: 2021.7.28-treviso-2
> 
> Seems like you are using the `2021.7.28-treviso-2` release which is a very old and deprecated release. Latest one is `2022.3.14-3` (like 10+ releases).
> 
> From Flathub site: [Flatpak support is built into Linux Mint 18.3 and newer—no setup required!](https://flatpak.org/setup/Linux%20Mint)
> 
> Can you post the output for `flatpak remotes | grep flathub`?

I am on the latest one and it i snot working.   Any idea how to fix this?

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/commit/8050f829c3fcda8975505f9d84827a00dd5e101f
