### ISSUE TITLE
[Request]  Implement DXVK state cache download

### ISSUE THREAD

**Issue by shuriken1812** [bottlesdevs/Bottles#1151]
**Is your feature request related to a problem? Please describe.**
DXVK state cache avoids major stutters and lags.

**Describe the solution you'd like**
Steam distributes shader cache files, not dxvk state cache files. The state cache files describe how to compile the shaders before draw time. The problem is from Direct3D to Vulkan translation trying to compile compile shaders at draw time rather than compiling pieces ahead of time and linking at draw time like Direct3D does. Even if the shaders are cached on disk, disk accesses are too slow to avoid stutter from the sheer quantity of shaders involved.

**Additional context**

As an example Lutris provides the same for Overwatch and few other games where this really matters.
https://lutris.nyc3.cdn.digitaloceanspaces.com/games/overwatch/Overwatch.tar.xz

Apex legends - someone on reddit maintains the [DXVK state cache for apex legends](https://cdn.discordapp.com/attachments/483946408676818974/951257660131520632/r5apex.dxvk-cache) on reddit he also has a good info on his thread.

Cache files go in this path - `/.local/share/Steam/steamapps/shadercache/1172470/DXVK_state_cache/gamename.dxvk-cache`
examples would be 
example  -    `/.local/share/Steam/steamapps/shadercache/1172470/DXVK_state_cache/Phasmophobia.dxvk-cache`

To merge caches you can use - https://github.com/DarkTigrus/dxvk-cache-tool also lutris has a build [here](https://lutris.nyc3.cdn.digitaloceanspaces.com/games/overwatch/merge-tool.tar.xz)

**Comment by PixsaOJ** [comment]
Before it's implemented, it would be helpful if someone writes manual steps ass well^

**Comment by cyberphantom52** [comment]
@mirkobrombin shouldn't we close this issue now that GPL is a thing?

**Comment by orowith2os** [comment]
This isn't too solvable on our end; we'd have to know what to download the cache files for, and someone would have to actually implement it. I'm going to close as not planned unless someone's willing to come work on it and writes out what steps Bottles would need to take for it.

> shouldn't we close this issue now that GPL is a thing?

Even if GPL is a thing, it won't *entirely* solve the fundamental problem of compiling shaders. But it's a major help, especially with gpl-async.
