### ISSUE TITLE
[BUG] EA Launcher doesn't install/run

### ISSUE THREAD

**Issue by DashCruft** [bottlesdevs/Bottles#1155]
**Describe the bug**
After creating a bottle, and then installing EA Launcher through the installers tab, it wont run, and when clicking to open location of the installed launcher, it says there isnt any location existing. (uploaded picture shows better)

**Installation**
 - Method: [e.g. Appimage, Meson build, other]
 - Version [e.g. 2021.7.2 (find this in the about dialog)]

**To Reproduce**
1. Create a bottle
2. Go to installers tab
3. Install EA Launcher
4. After installed, try running it or opening the location of it.

**Expected behavior**
Launcher should install, and run normally.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel Version: 5.16.13-zen1-1-zen 
 - Display server: Xorg

![image](https://user-images.githubusercontent.com/59381835/157778013-c367e0c3-937a-4c00-8333-56060dab7357.png)

**Comment by mirkobrombin** [comment]
Please provide package and version

**Comment by rmrfasterisk** [comment]
Can confirm the bug. Unable to install EALauncher on archlinux with Bottles version: 2022.2.28-trento-4 (flatpak)
