### ISSUE TITLE
[BUG] Not knowing the path /media [Solved]

### ISSUE THREAD

**Issue by qasem-talaee** [bottlesdevs/Bottles#1157]
Hello. Thanks for making this software.
The software does not know all the root routes. 
For example, it does not know the path of the /media.

![Screenshot from 2022-03-11 17-43-49](https://user-images.githubusercontent.com/62870048/157884574-7fc23b48-75f3-4308-927c-eabb2fb904ce.png)

Therefore, I have to use the following command to install the game from an external hard drive.
```bash
WINEPREFIX="/<route>" wine install-file.exe
```
Thank you for your help.

**Comment by mirkobrombin** [comment]
Bottles sandbox prefixes by default https://docs.usebottles.com/flatpak/expose-directories

**Comment by qasem-talaee** [comment]
Thank you very much.My problem solved with [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)
