### ISSUE TITLE
using bottles for existing prefixes, in particular for steam

### ISSUE THREAD

**Issue by ExpandingMan** [bottlesdevs/Bottles#1159]
**Is your feature request related to a problem? Please describe.**
I'm not really sure if this is a request for an actual feature or just better documentation.

I'm currently very dissatisfied with how frustrating it is to fix broken steam games, in my experience this has always involved using some combination of steam itself and `winetricks` (possibly through `protontricks`) in a very messy and ad hoc way.  Bottles seems to have a lot more features than `winetricks` alone, so I'd really like to use it instead, but so far, I can't seem to figure out how to do that.  It seems to me like presently bottles only really allows you to create new bottles completely from scratch.  I would love to be able to use it on steam's prefixes.

Maybe it's already possible to create a bottle and install a steam game into it, but I'm not too sure how this would work (steam itself being the major limiting factor because it's very opinionated about how it installs games).

**Describe the solution you'd like**
I think it would be really cool if there were a button that said something like "create bottle from existing prefix".

Again, I feel very uncertain about what capabilities already exist, certainly if it is already reasonably easy to achieve what I'm getting at here, simply expanding the documentation would be great!

**Describe alternatives you've considered**
Again, this is either a huge new feature or some simple documentation, depending on what can already be done with an existing prefix.

**Comment by mirkobrombin** [comment]
Hi, the feature you are asking for, is currently under development and will be provided as an experimental feature with the next release. There will be no need to manually add steam prefixes or create a bottle from that, as Bottles will find them automatically and can be configured as regular bottles, except for some features that will be disabled to prevent them from breaking or becoming incompatible with steam.

 https://twitter.com/usebottles/status/1500463084057595905?s=21

**Comment by ExpandingMan** [comment]
Nice!  Looking forward to checking it out.
