### ISSUE TITLE
[BUG] Run Executable is not opening a file picker

### ISSUE THREAD

**Issue by quasigod-io** [bottlesdevs/Bottles#1160]
**Describe the bug**
Clicking "Run Executable" does not open any file explorer. Clicking "Browse C:" does work. 

**Installation**
 - Method: AUR
 - Version: 2022.2.28-trento-3

**To Reproduce**
1. Go to any bottle
2. Click on “Run Executable”
3. It doesn't run

**Expected behavior**
My default file manager should open.

**Screenshots**
![peek](https://user-images.githubusercontent.com/62124625/157990371-52e19e21-e678-46e7-a647-e5508dc9c0f9.gif)
![image](https://user-images.githubusercontent.com/62124625/157990690-ba24adee-eab6-4dbc-bbde-b5b6361088a2.png)

No relevant info in terminal. The "Opening file manager in path" line appeared when I clicked "Browse C:"

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.16.13
 - Display server: Xorg

**Additional context**
I am running on i3 with lxsession. My default file manager is defined in lxsession and with xdg-open.

**Comment by mirkobrombin** [comment]
We are aware of this problem and it seems that your setup is not configured to allow the use of GtkFileChooserNative, while KDE, GNOME, XFCE etc yes. Unfortunately, I don't know how to help here, I hope I gave you enough info.

**Comment by quasigod-io** [comment]
Turns out, installing xdg-desktop-kde allows it to use the kde file picker. It's a little weird since I already had xdg-desktop-gnome, but it works. Thanks!

**Comment by mirkobrombin** [comment]
Nice!
