### ISSUE TITLE
[BUG]  gamescope invalid option -- 'd'

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#1162]
**Describe the bug**
Gamescope doesn't work

**Installation**
Installed Bottles and Gamescope through Flathub
 - Version [2022.2.28-trento-4]

**To Reproduce**
1. Activate Gamescope
2. Run with this config
![image](https://user-images.githubusercontent.com/51269425/158016808-10225bff-b705-46d3-a737-0a364f643e0c.png)

3. Run executable. 

**Expected behavior**
Gamescope works.

**Desktop (please complete the following information):**
 - OS: Fedora 
 - Version 35
 - Display server: Wayland
 
**Additional context**
When run with terminal, it gives the following error. 
```
/app/utils/bin/gamescope invalid option -- 'd'
See --help for a list of options
```

**Comment by mirkobrombin** [comment]
I'm not able to reproduce this on a clean installation. Can you drop here your bottle.yml?

**Comment by VarLad** [comment]
Just read the Bottles.yml file and noticed that there was a custom command for launch that I set and forgot. Removed that and it works. Thanks!

**Comment by VarLad** [comment]
Looking forward to the release with MangoHUD and LatencyFleX :P
I wonder how the parameters in MangoHUD will be managed by Bottles

**Comment by mirkobrombin** [comment]
Initially using env vars like usual.
