### ISSUE TITLE
[Crash report]  Cab file /home/nicolas/.var/app/com.

### ISSUE THREAD

**Issue by SuperBaguette** [bottlesdevs/Bottles#1164]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.2.28-trento-4

**Log**
```python3
Cab file /home/nicolas/.var/app/com.usebottles.bottles/data/bottles/temp/directx_Jun2010_redist/Apr2005_d3dx9_25_x86.cab not found
```

**Comment by mirkobrombin** [comment]
Hi thanks for reporting. Seems like the download was failed and Bottles cannot find the file. This should be already handled just returning this exception.
