### ISSUE TITLE
[Request] Drag and drop to reorder bottles

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1169]
It would be good to have ability to drag and drop to reorder the bottles.
Ex:
bottle1
bottle2
bottle3

Nice if i can drag and drop
bottle2
bottle1
bottle3

**Comment by mirkobrombin** [comment]
I would a feedback from @jannuary and @alvarlagerlof as this is part of the UX

**Comment by alvarlagerlof** [comment]
If it's something that is supported by GTK and can be done cleanly I don't have anything against it.

**Comment by jannuary** [comment]
It's not something that's easily done, especially in 3 as far as am aware. 

Either way, I don't see what the usecase of this is.

**Comment by mirkobrombin** [comment]
So probably locked by the gtk 4 porting or the missing uses cases. @ghtesting2020 What should this function solve for you?
