### ISSUE TITLE
LatencyFleX should be available only if nvapi enabled

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1176]

**Comment by TheEvilSkeleton** [comment]
I thought LatencyFleX supports non-NVIDIA GPUs?
> **Vendor agnostic** latency reduction middleware. An alternative to NVIDIA Reflex. 

https://github.com/ishitatsuyuki/LatencyFleX#:~:text=About-,vendor%20agnostic,-latency%20reduction%20middleware

**Comment by mirkobrombin** [comment]
> I thought LatencyFleX supports non-NVIDIA GPUs?
> 
> > **Vendor agnostic** latency reduction middleware. An alternative to NVIDIA Reflex.
> 
> https://github.com/ishitatsuyuki/LatencyFleX#:~:text=About-,vendor%20agnostic,-latency%20reduction%20middleware

Thanks for reaching out. That’s actually what the project repository  says and why I haven’t completed the task yet and my first thought was that it was “just” like a reimplementation of the nvidia technology, but I’ve done just a few tests and I don’t know if I get it right. I think this task can actually be closed.

**Comment by TheEvilSkeleton** [comment]
At the moment, it looks like there are only two methods:

> Direct hooking (UE4 hook) can trip the game's integrity check and directly get you banned.
> Proton NVAPI integration is relatively safe, but I am not responsible for any bans issued due to LatencyFleX.

I do agree that LatencyFleX should only be available on NVAPI, but I don't think it's necessary for NVIDIA GPUs only.

**Comment by mirkobrombin** [comment]
And maybe I have to add a warning for bans
