### ISSUE TITLE
[BUG] Component DXVK version 1.10 listed under 1.9.3 due to x.x.x higher priority than x.x

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1188]
flatpak 2022.3.14-trento-3

When inside a bottle Preferences > Components version > DXVK version the available versions are out of order due to the way numbers are handled. Looks like x.x.x is higher priority than x.x but the x.x is newer than x.x.x so it should be above.

currently
dxvk-1.9.4
dxvk-1.9.3
dxvk-1.10  <-----------------------

should actually be
dxvk-1.10  <-----------------------
dxvk-1.9.4
dxvk-1.9.3

**Comment by mirkobrombin** [comment]
Thanks for reporting
