### ISSUE TITLE
[Bug]: Bottles window freezes when creating a new bottle.

### ISSUE THREAD

**Issue by tati1454** [bottlesdevs/Bottles#1191]
### Describe the bug

When I create a new bottle the progress window appears, but if for some reason I minimize bottles and maximize it again the progress window hides behind the bottles window and it just freezes, so I can't know if the program is actually doing something or it got stuck.

### To Reproduce

1. Create a new bottle
2. Wait until the progress window appears
3. Minimize bottles
4. Maximize it again

### Package

Flatpak from Flathub

### Distribution

Kubuntu 21.10

### Display Server

Xorg

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by tati1454** [comment]
Oh I just realized that this also happens when you move the main window while the bottle its creating. The bottle creation progress window gets stuck behind the main window, and because the focused windows its the progress window you can't do anything.

**Comment by mirkobrombin** [comment]
I'm not able to reproduce this with GNOME. I think the problem is how GTK apps are managed in KDE, because GNOME doesn't let me minimize the window when the bottle creation's dialog is on top.

**Comment by tati1454** [comment]
And have you tried moving or resizing the main window?

**Comment by mirkobrombin** [comment]
Can’t resize because the dialog is attached to the main window

**Comment by tati1454** [comment]
mmm now I'm on fedora 35 with KDE and wayland and now it doesn't happen. I'm not sure why it happened, probably a bug with KDE that now got fixed or it only happens with Xorg?

**Comment by mirkobrombin** [comment]
It could be
