### ISSUE TITLE
Flaptak regression: Cannot use Wine staging anymore. Cannot install software due to bugs which are fixed in staging

### ISSUE THREAD

**Issue by imDema** [bottlesdevs/Bottles#1195]
With the deb installer it was possible to use the Wine staging version. With Flathub, the wine libraries are locked to the stable version and now I am unable to install a program, which I was able to install using the deb install, due to a bug in wine which is fixed in the staging version.

Given the rapid evolution that wine is experiencing, being locked to the stable version is limiting. I would have no problem with it if it were like this since the beginning, but now I find myself having degraded functionality with respect to an older version of the software and I am unable to install software that I could install with the deb version.

Would it be possible to have either a flatpak release with staging wine or another way to run with the wine staging libs?

(The software in question is VirtualDJ and the installation fails due to a bug in winemenubuilder which is fixed in staging)

**Comment by mirkobrombin** [comment]
Bottles uses it's own runners, should use the sys-wine runner only if the user ask for it. Can you try changing the runner in the bottle preferences? The default one is Caffe 7.2

**Comment by mirkobrombin** [comment]
> Correct me if I'm wrong, but from what I understand, runners still use wine shared libraries installed system wide (or in the sandbox in case of Flatpak), no?
> 
> I am using the Caffe 7.2 runner and getting the error which is
> 
> ```
> 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
> wineserver: file_set_error() can't map error: Function not implemented
> ```
> 
> Previously I installed the same program with the deb version, but with system wine-staging 7.3 and had no such error. I'm not sure if the staging wine version is the exact problem, but it's the only difference in the configuration I could think of

Not all builds, the Caffe runner has almost all its libraries built-in, the missing ones are provided by the flatpak or the Bottles runtime but it should just works. The only thing changed in the flatpak is how these libraries are provided, before was defined in the flatpak itself, now are provided by the WineHQ base but actually are the same and all should just works right before.

**Comment by imDema** [comment]
Ok, so I managed to find the problem, the msi installer was failing silently and worked by checking the move inside the sandbox flag when running the installer.

It may be useful to add some kind of indication or suggestion in the UI to prevent this happening to someone else. Since the execution was silently failing, only signaling the error I copied earlier (and only if I turned on the terminal), I had no UI clues that could really lead me there and only got it by trial and error trying basically every toggle I could one at a time.

Thank you for the quick responses

**Comment by mirkobrombin** [comment]
Closing as this is already documented. FYK I'm looking for a way to automated the whole process but I've no expectations as what I've in mind can works with just only 1 file, so DLLs and other needed stuff cannot be moved inside the bottle path. I think there is no way to automated this at all.
