### ISSUE TITLE
[Request]: Ability to use obs-vkcapture

### ISSUE THREAD

**Issue by kozross** [bottlesdevs/Bottles#1197]
### Tell us the problem or your need

`obs-vkcapture` is a really good way of screen-recording a game. The [current instructions](https://github.com/nowrep/obs-vkcapture#usage) are a bit tricky to do in a bottle, or at least, it's not clear to me how this would be possible.

### Describe the solution you'd like

Either document a way that `obs-vkcapture` can be used to capture something running in a bottle, or, better, provide built-in support for doing this. `obs-vkcapture` [exists in Flatpak](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture), so it shouldn't be difficult to provide such an option for those who might want it.

### Other solutions?

Currently, it might be possible to do this already, but it's not at all clear to me how this would be done.

**Comment by SuNNjek** [comment]
If you have the linked Flatpak installed, you can simply set the environment variable `OBS_VKCAPUTRE` in the bottle settings to `1` and it should work. Maybe there could be a toggle in the settings for this like with mangohud in the future.
