### ISSUE TITLE
[Request]: Full DXVK HUD as an option

### ISSUE THREAD

**Issue by kozross** [bottlesdevs/Bottles#1199]
### Tell us the problem or your need

Currently, the DXVK HUD option doesn't enable everything that the DXVK HUD can show. In particular, it doesn't indicate GPU load as a percentage, which you _can_ see if you manually pass `DXVK_HUD=full` to something being executed in-bottle.

### Describe the solution you'd like

Either add a 'use full HUD' option, or better, allows us to pick [which things we want to see](https://github.com/doitsujin/dxvk#hud).

### Other solutions?

It's possible to do this manually at the moment, but it's needlessly tedious. It's also not clear how (if at all) such a 'manual' setting interacts with setting the DXVK HUD to 'on' in the GUI.

**Comment by mirkobrombin** [comment]
This is intentional, you can use the compact DXVK_HUD from our GUI, or just set your own using the Environment Variables option in your bottle preferences.

**Comment by kozross** [comment]
Is there a reason why we can't default to the full HUD when set graphically? You probably want it for debugging purposes, and more information is always better in such a case.

**Comment by mirkobrombin** [comment]
> Is there a reason why we can't default to the full HUD when set graphically? You probably want it for debugging purposes, and more information is always better in such a case.

There is no reason, I just thought it was enough. I've no other requests for this, so it should be okay to use the full one instead
