### ISSUE TITLE
[Question] Can bottles install Windows applications on external disk while it is installed on internal disk?

### ISSUE THREAD

**Issue by Nokia808** [bottlesdevs/Bottles#120]
Hi.

Dear I need your help but kindly be patient with my story !

My laptop is Lenovo ThinkPad e550 with default HDD of 1 TB. It has no mSATA port to add additional disk.
My system is Linux Fedora installed on default HDD.

I has 2 user accounts: the default (which has su & sudo & polkit powers), & a 2nd special user account "wineuser" without any root power (no su, no sudo, no polkit). Home directory of "wineuser" is within default HDD.

If I will install bottles from FlatHub, I will install it from within "wineuser" with "--user" flag to be isolated from system.

All these for protection from viruses, & I'm waiting for your further feature work about https://github.com/flathub/com.usebottles.bottles/issues/4

The problem is that I need additional space because recent Windows games are of huge size (45 GB or 87 GB). 1 TB is not enough. And because my laptop has no mSATA I'm unable to add internal disk. Instead, I have Dock - see attached pictures - can use it to connect SSD disk of 2 or 

3 TB via USB version 3 port of my laptop.

My questions are:

1) does bottles has ability to utilize such externally connected disks to install Windows games & applications on them instead of default HDD ?

2) if the answer for point (1) above is yes, then do I have need to attach Dock USB cable, every time, to same USB port of laptop or can I change it ? My laptop has 3 USB ports .......

3) what could happened if electrical power shut down for Dock while I'm playing a game installed on external disk connected through Dock to laptop ? Please notice that in this case Dock will stop from working because it need independent power supplying from power supply of laptop (laptop will continue working from it's battery while external Dock will shut down). Does this will break flatpak package integrity & lead to serious damage or only interfere with game play ?

Accept my sorry if I bother you by such question !

![1](https://user-images.githubusercontent.com/25375330/106949830-6c199980-6725-11eb-9300-4764ad9f9f21.jpeg)

![2](https://user-images.githubusercontent.com/25375330/106949918-89e6fe80-6725-11eb-8709-9f50354325a9.jpeg)

![3](https://user-images.githubusercontent.com/25375330/106949935-92d7d000-6725-11eb-8a46-61b77860b84c.jpeg)

![4](https://user-images.githubusercontent.com/25375330/106950099-cdda0380-6725-11eb-8c6a-39377ce1f693.jpeg)

**Comment by Nokia808** [comment]
In fact my original plan was to replace build-in DVD drive of my laptop by new additional SSD disk & creating new account (without any root power) but it's home directory on new additional SSD disk but the problem is that I need this piece:
https://hddcaddy.com/en/lenovo-ibm-hdd-caddy/1143-lenovo-thinkpad-edge-e550-hdd-caddy.html
which seem to be not available in my country ......

**Comment by mirkobrombin** [comment]
Hi, you should be able to add other disks from `winecfg`.

**Comment by Nokia808** [comment]
@mirkobrombin 
Thank you for your rapid response ! What about point (2) & (3) ?

**Comment by mirkobrombin** [comment]
2- I think you can put the cable into any usb port
3- no, the most that can happen is that the application jutst crash, the risks are the same as a crash of the same application on Windows

**Comment by Nokia808** [comment]
@mirkobrombin 
Good news from you ! Very relieving answers !
I will continue in next 10 days my search for adopter piece to be able to replace built-in DVD room. If I failed then I will shift to Docking solution. It is very good after your answers. The only disadvantage of it is that user need to put laptop & Dock flat on a firm table & can not use laptop in for flexible states ..... Not big issue

Issue is solved & questions are answered. 

Thank you again.

**Comment by Nokia808** [comment]
Hi again. Just yesterday, I bought the new SSD. It is of 2 TB SATA 3 Samsung - see:
https://www.samsung.com/us/computing/memory-storage/solid-state-drives/870-evo-sata-2-5-ssd-2tb-mz-77e2t0b-am/

As you see, It is internal & I can use it both internally or externally via external Docking. I will select, for now using it externally via external Docking station ......

My question is that: what is the most suitable file format most suitable to work with WineHQ via Bottles? Is it:
- Ext4 (only working with Linux, so I can not scan the new SSD by antivirus from a Windows laptop, because Windows does not recognize Ext4 format).
- NTFS (can be recognized by both Linux & Windows, so I can scan new SSD with antivirus from a Windows laptop).
- exFAT (same for NTFS)

Kindly, help me in this decision. Please taking in 1st place the performance rather than the ability to scan new SSD by antivirus from Windows laptop. Performance in making games working correctly & perfectly is the chief target & aim.

**Comment by Nokia808** [comment]
@mirkobrombin 
Only one concern: you said "you should be able to add other disks from winecfg".

Okay, my last question is that: if you in the feature add the following feature request:
https://github.com/flathub/com.usebottles.bottles/issues/4
& then at that future time I used "winecfg" to select external SSD disk to be the ONLY place where ALL Windows installed will be installed, then does this will prevent Windows applications from touching the default internal HDD by dirty action ?
