### ISSUE TITLE
[Request]: Improving issue forms

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1202]
### Tell us the problem or your need

I noticed some elements are missing, For example, the Bug Report template doesn't mention if Bottles is running on the X11 or Wayland backend, but it only asks what display protocol the session is using.

I think asking both questions is really important, especially when some people might force to X11 and forget about it. Or, use AppImage which forces to X11. So, having a section that asks what display backend Bottles is using should be important too.

https://github.com/bottlesdevs/Bottles/blob/b45925b243c2770a6119046b1e7cb1f9725e1da5/AppImageBuilder.yml#L130

### Describe the solution you'd like

Adding a section to ask specifically what display backend Bottles is running on, and fixing some inconsistencies here and there.

### Additional context and references

I've pushed some changes in my fork: https://github.com/TheEvilSkeleton/Bottles/issues/new/choose. If accepted, I can submit an MR.

**Comment by mirkobrombin** [comment]
Its a very useful detail. I’m fine with a PR
