### ISSUE TITLE
[Request] Shortcuts to instantly launch Windows apps 

### ISSUE THREAD

**Issue by superdreamkilla** [bottlesdevs/Bottles#121]
From what I understand, it doesn't look like Bottles can make shortcuts of Windows apps to immediately launch them. I would like to know if it would be possible to add a feature to launch Windows apps using a CML, or make menu/desktop shortcuts to  launch apps maintained by bottles? Thank you.

**Comment by mirkobrombin** [comment]
We are working on our installer system. You can still install a program and run it from the Programs Tab until it is complete.

Please next time follow the Feature Request template.

**Comment by mirkobrombin** [comment]
Ref #115
