### ISSUE TITLE
[Request]: Turn off compositor when Bottles launches and on again when Bottles closes

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1213]
### Tell us the problem or your need

Flatpak 2022.3.14-trento-3

I still new to bottle and linux so i am not sure if this already happens but i read users should turn off compositor when gaming to improve performance.

### Describe the solution you'd like

 Not sure if Flatpak can even do this but if possible according to this page https://askubuntu.com/questions/36654/how-do-i-turn-on-and-off-compositing-from-the-command-line you can turn off compositor with
```metacity --replace &```
and then on again when bottles exists with
```compiz --replace &```

**Comment by axtloss** [comment]
Disabling the compositor doesn't work on every desktop environment and also only on x11. Desktops like gnome and generally mutter based desktops don't support turning off any compositor. Same goes for any wayland window manager or desktop since the compositor is also the window manager.

**Comment by mirkobrombin** [comment]
So this would make no sense to integrate it

**Comment by axtloss** [comment]
Yeah, people who do need to kill the compositor could just kill it manually or make gamemode hooks that kills and starts the compositor

**Comment by jannuary** [comment]
Yeah, no, that's impossible.

However, this should already work on mutter: [Wayland surface fullscreen unredirect](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/798)
