### ISSUE TITLE
The "Enable ACO shader compiler" toggle appears to be disabled by default. Is there a reason for this?

### ISSUE THREAD

**Issue by Sonickyle27** [bottlesdevs/Bottles#1221]
The ACO shader compiler is automatically enabled for Mesa since 20.2. For version `2022.3.14-trento-3` of Bottles running through Flatpak, when I check the Preferences of a Bottle, it shows that the "Enable ACO shader compiler" toggle is disabled by default. When using Mesa 20.2 or higher, shouldn't this toggle be enabled by default?

**Comment by mirkobrombin** [comment]
I thought there was already a issue for this 🤔
Btw we are aware of this, I’ll keep this issue open as a reminder, than for reporting

**Comment by Sonickyle27** [comment]
I did try searching for a similar issue yeah, but at least searching for `aco` didn't really come back with anything relevant :/
