### ISSUE TITLE
How to allow running a native application from a bottle in flatpak?

### ISSUE THREAD

**Issue by brunoais** [bottlesdevs/Bottles#1224]
After I setup as specified in Wine's wiki:
https://wiki.winehq.org/FAQ#How_do_I_launch_native_applications_from_a_Windows_application.3F

Then executing (what I believe to be ) the necessary steps in flatseal to open up the access to the executables:
![image](https://user-images.githubusercontent.com/639467/159187569-0880bce2-bba1-4067-b819-710a37ad80d1.png)

What am I missing so I can access the native files and execute them?
I'm trying to run:

```
Z:\usr\bin\git
```
However, 
![image](https://user-images.githubusercontent.com/639467/159187644-32dba411-11ee-4d85-b16a-f9ed22f6ab6e.png)
But if I use wine with the prefix in the wine prefix created by bottles, I can run it fine.

What am I missing here?

**Comment by mirkobrombin** [comment]
The command line in Bottles is actually a CMD, not bash or sh. You can only run Windows executables.

**Comment by mirkobrombin** [comment]
Nvm, I got your point. 

Try with ‘cmd /c /usr/bin/git‘

**Comment by brunoais** [comment]
Tsk! I can't with flatpak... I only found this now:
https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

Unfortunately:
1. AppImage is broken (I think I saw sometime in January you writing it's discontinued (that's sad... It's something I could try to fix))
2. Deb doesn't install on my system (ubuntu 20.04 LTS).
3. I don't have the requirements to compile and install on my machine (ubuntu 20.04 LTS; too old of libhandy).

Fortunately:
I know my way around podman (which is very similar to docker). Maybe I can figure out a way around this... If I can fix AppImage, do you want it back?

**Comment by mirkobrombin** [comment]
> If I can fix AppImage, do you want it back?

Sure! I love AppImage, just I don’t have the time to maintain it

**Comment by brunoais** [comment]
> Tsk! I can't with flatpak... I only found this now:
> https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

Workaround:
If I create an `/usrs` and `mount --bind usr usrs` (requires root :(), it seems to work (as long as it's a self-contained executable)

> It would be great if I could make it work again.

I also don't have much time in my life but this can be a win-win for us.  
I'll close this issue in the meantime because it won't go far with flatpak for now.
