### ISSUE TITLE
[Progress] Making Bottles run as AppImage

### ISSUE THREAD

**Issue by brunoais** [bottlesdevs/Bottles#1232]
Status update:

On Bottles side, the problem was easy to fix. My issues now lie on wine side. I can't understand how do I tell wine's libs where to load from. They are currently trying to load libc from my own system outside the AppImage instead of being redirected to the (fuse) mount point.
The wine runtimes are being compiled with version 3.2 of libc but my system has libc version 3.1

@mirkobrombin Do you know any way to tell wine where to find the libc libraries? I'm trying to set the `LD_LIBRARY_PATH` with the path to the directory where it is but doesn't seem to work

I'm also considering the use of AppImages for the wine runtimes. Such as https://github.com/Hackerl/Wine_Appimage

**Comment by mirkobrombin** [comment]
I think the `LD_LIBRARY_PATH` is the only way. I have encountered many library problems with the AppImage, it seems that regardless of whether these are provided by the bundle or not, it is still unable to reach them. At the moment Bottles also offers a runtime and I can add anything we need there but this is also injected via `LD_LIBRARY_PATH` by Bottles, so I don't think it's a solution as it is affected by the same problem.

**Comment by brunoais** [comment]
After extensive back and forth... and after going deep into reading C code, complaints and how people have been giving up, I think placing wine on AppImage successfully is not achievable for my knowledge level.
I will do a try with your build of wine 7.2-caffe but I can't think of a success path in advance. I can't piece things together to try to make it work... I'll just jump in and hope AppImage runtime can do the work for me with me without proper recourse. From what I see, it appears like `libhookexecv.so` stopped working with version 7.0... I can see why from the source code. It is rather fragile.

If I can't find a solution here... I guess I will have to use the workaround I mention [here](https://github.com/bottlesdevs/Bottles/issues/1224#issuecomment-1073578975), which also means that solution is only available to root users.... Unless there's a fuse option...

**Comment by mirkobrombin** [comment]
Maybe there is some similar project that has succeeded and we can understand/ask how

**Comment by brunoais** [comment]
I didn't know about GameHub. I'll take a look at it. Thanks

**Comment by mirkobrombin** [comment]
Eeew

**Comment by brunoais** [comment]
With wine, what I got only works on a very limited variety of executables.
Here's what I got so far for using wine:
[AppImage.tar.gz](https://github.com/bottlesdevs/Bottles/files/8344562/AppImage.tar.gz)
Almost everything fails to load correctly or crashes.
The major program I was able to run successfully was `git.exe`

**Comment by brunoais** [comment]
I really can't make wine work right...
[AppImage.tar.gz](https://github.com/bottlesdevs/Bottles/files/8357795/AppImage.tar.gz)
With wine compiled against glibc, I'm stuck. Right now I ran out of ideas...  I can run the simpler programs but when it's a windows executable that forks, the overrides are lost.

However, I learned a lot about AppImage packaging (it should work around 95% of the times. It's an incredible job) and I learned about many interesting facilities of flatpak I didn't know.

For now, I will continue if I encounter a breakthrough. Otherwise, I'll put these means to rest.

As for running a native linux program (or another flatpak) from wine in Bottles. That one isn't dead and it's still well-alive. It's just that I won't actively try AppImage actively.

**Comment by mirkobrombin** [comment]
Unfortunately I gave up because I never managed to package Bottles as Appimage with acceptable results. Let's understand, I really love Appimage. I think it is one of the greatest projects but with wine there is not much to do. I also tried to package a newer version of glibc but it can't find the libraries even though those are close to it

**Comment by brunoais** [comment]
I have no issues packaging a newer glibc.
Maybe with the new runtime they are preparing the situation will change but it will stay broken with the current runtime.
Given the compilation you are doing, whoever updates to ubuntu 22.04 will be able to use an AppImage with the fixes I did.

May I suggest changing the README to remove the AppImage reference and, instead, link to this issue (with a short description that wine appears to be unpackageable as an AppImage unless rebuilt with unusual settings)?

**Comment by mirkobrombin** [comment]
But even if WINE isn't packaged, Bottles will still use what it downloads on first run (or while creating the bottle if it doesn't find any). Right?

**Comment by brunoais** [comment]
My idea was to package Wine as an AppImage and Bottles as a different AppImage, having, in effect, separated things. One thing is the wine, the other is Bottles and then having Bottles downloading the intended AppImage wine as required.

With the fixed Bottles AppImage (which was a straightforward fix, btw) yes, Bottles runs correctly and downloads the runtime normally. However, wine will expect glibc version >=3.22<4.*, while the latest ubuntu LTS has glibc 3.21. So, as soon as you try to do something with wine, it fails.

The main reason wine `7.2-caffe` works on the flatpak version is because flatpak mounts a `/usr` in `/usr` with the version associated with the runtime chosen. In your case, you chose a runtime that has glibc `3.22`. So, when wine looks for `ld-linux.so.2` in `/lib`  (or the corresponding x64 version of it), its found and just runs.
With an AppImage, there's no similar sandboxing. The content in `/usr` is the handling OS's libraries and not the "packaged" libraries. Here, the fact there's no "overlord" with sudo privileges doing the sandboxing with namespaces causes the downfall. So, the compilation of wine will have to be compatible with the machine where it runs, against the philosophy of the AppImage.

**Comment by brunoais** [comment]
I got a breakthrough. I wasn't using one of AppImage runtime features properly. I'm able to run most windows programs I have just fine now. Some still have some issues but I'll try to deal with them as I can

**Comment by MaxPeal** [comment]
@brunoais do you have the build scripts / build env for the AppImage on github?
i like to give it a try.

**Comment by brunoais** [comment]
I don't have a repo because, at this stage, I have my stuff in a very caotic way.
Here's the files @MaxPeal :
[AppImage.tar.gz](https://github.com/bottlesdevs/Bottles/files/8402160/AppImage.tar.gz)

Extract that inside `bottles/runners/caffe-7.2`. You have to allow Bottles to download the caffe version of wine first

**Comment by brunoais** [comment]
@MaxPeal It's hard. If you give up, let me know and I'll try to continue. I don't want to do double-work :slightly_smiling_face:

**Comment by brunoais** [comment]
@MaxPeal Any news?

**Comment by brunoais** [comment]
@MaxPeal Any news?

**Comment by brunoais** [comment]
I see @azubieta is the actual one fixing AppImage. Thank you @azubieta. I'll close this issue, then
