### ISSUE TITLE
Improved desktop file creator with renaming and icon support. 

### ISSUE THREAD

**Issue by Zenith222** [bottlesdevs/Bottles#1234]
### Tell us the problem or your need

The current desktop file tool is oversimplified and doesn’t allow setting a shortened or custom name, or selecting an icon. The .desktop file will have to be manually edited to change these aspects. 

### Describe the solution you'd like

Add a menu for .desktop file creation that allows setting multiple options such as a custom name and icon.

**Comment by mwleeds** [comment]
If Bottles moves to using the new dynamic launcher [portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.DynamicLauncher) for creating .desktop files, it allows the user to edit the name but not the icon. The ability to edit the icon could be a feature for it in the future (there's already an option in the interface, it's just not supported by the backends).

**Comment by mirkobrombin** [comment]
Good to know

**Comment by mirkobrombin** [comment]
Bottles now automatically extract icons from the executable. We have no plans to provide a "builder" for desktop entries.

Tracking Dynamic Launchers here #1366
