### ISSUE TITLE
How to change install directory for bottles?

### ISSUE THREAD

**Issue by m-GDEV** [bottlesdevs/Bottles#1236]
Hi, I'm trying to find a way to install a bottle in a different directory than the default directory. 

Is this possible? Thanks.

**Comment by mirkobrombin** [comment]
You can change the default bottles' location from Bottles' preferences
![image](https://user-images.githubusercontent.com/9479903/160070646-17009ba9-486a-4e91-8577-add6cb01945a.png)


It is not possible to store a single bottle in a different path.

**Comment by m-GDEV** [comment]
> Hi, you can change the default bottles' location from Bottles' preferences ![image](https://user-images.githubusercontent.com/9479903/160070646-17009ba9-486a-4e91-8577-add6cb01945a.png)
> 
> It is not possible to store a single bottle in a different path.

Thanks for the help, didn't see that setting.

**Comment by mirkobrombin** [comment]
You are welcome
