### ISSUE TITLE
[Question] Which is most suitable file system format for external disk to be run by WineHQ/Bottles ?

### ISSUE THREAD

**Issue by Nokia808** [bottlesdevs/Bottles#124]
Hi again. I bought the new SSD. It is of 2 TB SATA 3 Samsung - see:
https://www.samsung.com/us/computing/memory-storage/solid-state-drives/870-evo-sata-2-5-ssd-2tb-mz-77e2t0b-am/

As you see, It is internal & I can use it both internally or externally via external Docking. I will select, for now using it externally via external Docking station ......

My question is that: what is the most suitable file format most suitable to work with WineHQ via Bottles? Is it:

    Ext4 (only working with Linux, so I can not scan the new SSD by antivirus from a Windows laptop, because Windows does not recognize Ext4 format).
    NTFS (can be recognized by both Linux & Windows, so I can scan new SSD with antivirus from a Windows laptop).
    exFAT (same for NTFS)

Kindly, help me in this decision. Please taking in 1st place the performance rather than the ability to scan new SSD by antivirus from Windows laptop. Performance in making games working correctly & perfectly is the chief target & aim.

Thank you.

**Comment by mirkobrombin** [comment]
I think it doesn't make too much difference, the disk is read by the system so I recommend an FS like ext4, btrfs, xfs etc.

**Comment by Nokia808** [comment]
@mirkobrombin 
So you recommend file system that not read by Windows & thus can not use benefit from scanning by antivirus installed on a Windows PC.

Since you recommend to use Linux specific file system can not read by Windows OS, I will select Ext4 because my system is Ext4 since I 1st fresh installation was Fedora 24 & I'm using system upgrading not fresh installation to upgrade to newer Fedora release. Moreover, btrfs still not mature enough & has bugs & slower than Ext4 .........

At Freiday I will start the work on formatting new SSD. Hope you will finalized anti-virus safety of flatpak version in near future .........
