### ISSUE TITLE
flatpak version of bottles is not updated

### ISSUE THREAD

**Issue by Lvaskz** [bottlesdevs/Bottles#125]
**Describe the bug**
Flatpak version of bottles is not updated
flatpak version describes as 2.0.9, when the recently version is 2.1.0.7

**Installation**
 - Method: [flatpak]
 - Version [2.1.0.7]

**To Reproduce**
1. Go to terminal and installing typing:  flatpak install flathub com.usebottles.bottles
2. wait untill all elements are installed 
2. type in terminal type : flatpak list
3. Scroll down to find bottles and see version of it
4. See error, the flatpak version is 2.0.9 instead of 2.1.0.7

**Expected behavior**

after install flatpak version of bottles, must be the recently version 2.1.0.7

**Screenshots**
<img width="862" alt="bottles 11" src="https://user-images.githubusercontent.com/29207169/108422652-73987280-71fc-11eb-9b8a-fd98088a5ffc.png">

**Desktop (please complete the following information):**
 - OS: [kde neon]
 - Version [5.20.5]

**Additional context**

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. Check bottles version from the about dialog. Idk why flathub is showing the wrong version even if it is actually installing the latest.

**Comment by Nokia808** [comment]
@mirkobrombin 
I'm already notify you about this - see:
https://github.com/flathub/com.usebottles.bottles/issues/6

**Comment by mirkobrombin** [comment]
Keep the conversation on the flathub repository https://github.com/flathub/com.usebottles.bottles/issues/6
