### ISSUE TITLE
[Request]: Create Empty/Basic Wine/Proton Bottles

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#1250]
### Tell us the problem or your need

For those who want a GUI to create and manage Wine and Proton bottles but want to create a empty/basic Wine/Proton bottle without any additional stuff in it.

### Describe the solution you'd like

Would like to create a Wine/Proton bottle without a Runner, DXVK,

### Additional context and references

If one wants to add a runner or DXVK to a basic Wine/Proton bottle later, they can by going into the bottle settings.

**Comment by mirkobrombin** [comment]
When you made a bottle with the custom environment, you are actually making a clean bottle. You can still select the dxvk version but it will not be installed. Actually it is a pure clean wine prefix without any dependencies or tweak.
