### ISSUE TITLE
[Request]: Download Wine/Proton Versions

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#1251]
### Tell us the problem or your need

A menu to download Wine or Proton version which one can backup and restore.

### Describe the solution you'd like

A menu were you can choose what version of Wine or Proton to download and it can download that version of Wine/Proton to a directory on your computer of your choosing. Similar to what PlayOnLinux offers for downloading Wine versions.

**Comment by mirkobrombin** [comment]
You can download any wine or proton version from the software preferences.

**Comment by trymeouteh** [comment]
In the software preferences I do not see older version of runners and I do not see regular Proton runners (Only Proton GE) and I do not see any Wine runners to download.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/161338611-90add75e-ad97-4f75-94d5-603a22c9cec3.png)

![image](https://user-images.githubusercontent.com/9479903/161338640-e7f9efa2-8d58-47c9-a032-f09a826b8461.png)

![image](https://user-images.githubusercontent.com/9479903/161338669-4aa031c9-5651-429c-9c14-83963587d978.png)

![image](https://user-images.githubusercontent.com/9479903/161338691-0bbed45a-5178-4177-9822-e9a7e8ccc21b.png)

![image](https://user-images.githubusercontent.com/9479903/161338725-6a44c3dc-e472-4c2c-94d5-5d683208d4ad.png)

**Comment by trymeouteh** [comment]
I guess then I would like to see the ability to download all older versions of Wine and not modified versions of Wine.

**Comment by mirkobrombin** [comment]
Vaniglia are vanilla wine releases

**Comment by trymeouteh** [comment]
Vaniglia is not the original wine as stated on the [bottles docs](https://docs.usebottles.com/components/runners)

_Vaniglia (Vanilla) is a clean runner as its name suggests. Apply only wine-staging patches and a modern theme created by Joshua Ashton._

It has wine staging patches added and a modified theme. The theme is not the issue but the wine staging can cause compatibility issues. If I use Vaniglia 7.0 and got my Windows application working in it, I will assume Wine 7.0 makes this application works when it could be in reality Wine 7.0-staging and the application does not work in Wine 7.0.

**Comment by mirkobrombin** [comment]
Ik, I've written this doc. Again, to provide new runners, just open a new PR with its manifest.
