### ISSUE TITLE
[Request]: personalized bottle path

### ISSUE THREAD

**Issue by Martinligabue** [bottlesdevs/Bottles#1255]
### Tell us the problem or your need

All the bottles are created in the same folder

### Describe the solution you'd like

It would be nice to have an option to specify a custom path for every new bottle or moving existing ones

**Comment by mirkobrombin** [comment]
We also have an option to change the default bottles path:

![image](https://user-images.githubusercontent.com/9479903/161341821-861c8839-bba3-4776-bfa4-b996b36c55b4.png)

Currently it is not possible to specify a different path for each bottle and it may be hard to do so at the moment. I prefer to wait until I finish writing the new bottle manager

**Comment by Martinligabue** [comment]
thxlol
