### ISSUE TITLE
[Request]: Add Wine & Proton Runners

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#1256]
### Tell us the problem or your need

An option to select Wine or Proton as a runner instead of only having modified versions of Wine and Proton such as Caffe, Vaniglia. Proton-GE and Lutris.

### Describe the solution you'd like

Runners such as Caffe, Vaniglia. Proton-GE and Lutris are [modified versions](https://docs.usebottles.com/components/runners) of the original Wine and Proton runners. I would like to see the ability to have access to stable and staging versions of original Wine runners and the original versions of Proton runners from Steam.

### Additional context and references

Vaniglia is not the original wine as stated on the [bottles docs](https://docs.usebottles.com/components/runners)

_Vaniglia (Vanilla) is a clean runner as its name suggests. Apply only wine-staging patches and a modern theme created by Joshua Ashton._

And there is no original wine runner option, only Proton GE runners which are modified versions of Proton.

**Comment by trymeouteh** [comment]
If there are no repo for grabbing Proton runners from, then Wine is all that can be added. PlayOnLinux does grab Wine runners from a repo.

**Comment by mirkobrombin** [comment]
Can you please stop open 10000 issues for the same thing? 😐 Playonlinux has its own repository how we have our own repository. Bottles travels on a centralized repository system that requires repositories with ITS index file structure. To have other versions and runners, you need to open a Pull request in the components repository for each individual version. We cannot change this structure.

https://github.com/bottlesdevs/components
