### ISSUE TITLE
RPM version doesn't load executables

### ISSUE THREAD

**Issue by mvevitsis** [bottlesdevs/Bottles#1258]
### Describe the bug

I am trying to use the RPM version but get the following errors when trying to launch an executable

<pre>(07:46:06) <b>INFO</b> <font color="#2AA1B3">Launching an executable…</font> 
(07:46:06) <b>INFO</b> <font color="#2AA1B3">Setting Key: [Latest_Executables] to [[{&apos;name&apos;: &apos;TradosStudio2021SR2_16.2.9.9198.exe&apos;, &apos;file&apos;: &apos;/media/sf_Trados/TradosStudio2021SR2_16.2.9.9198.exe&apos;, &apos;args&apos;: &apos;&apos;}, {&apos;name&apos;: &apos;TradosStudio2021SR2_16.2.9.9198.exe&apos;, &apos;file&apos;: &apos;/media/sf_Trados/TradosStudio2021SR2_16.2.9.9198.exe&apos;, &apos;args&apos;: &apos;&apos;}]] for bottle: [Trados]…</font> 
(07:46:07) <b>WARNING</b> <font color="#A2734C">No GPU vendor found, keep going without setting VK_ICD_FILENAMES..</font> 
wineserver: using server-side synchronization.
002c:err:wineboot:process_run_key Error running cmd L&quot;C:\\windows\\system32\\winemenubuilder.exe -r&quot; (2).
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
00f8:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
00f8:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
00f8:err:module:open_builtin_so_file failed to load .so lib &quot;/home/Matvei/.local/share/bottles/runners/caffe-7.2/lib32/wine/i386-unix/winex11.drv.so&quot;
00f8:err:user:load_desktop_driver failed to load L&quot;winex11.drv&quot;
00f8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00f8:err:winediag:nodrv_CreateWindow The explorer process failed to start.
</pre>

### To Reproduce

Launch executable

### Package

Other, unofficial package

### Distribution

Fedora 35

### Health Check

Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors: {}
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.16.18-200.fc35.x86_64
Distro:
    Name: Fedora Linux
    Version: '35'
Tools:
    cabextract: true
    p7zip: false
    patool: false
    glibc_min: '2.34'
Bottles_envs: null

### Display Protocol

Wayland

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting.

This one 
```
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
```

should be fixed by the maintainer. 


Regarding this:
```
00f8:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
00f8:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
00f8:err:module:open_builtin_so_file failed to load .so lib "/home/Matvei/.local/share/bottles/runners/caffe-7.2/lib32/wine/i386-unix/winex11.drv.so"
00f8:err:user:load_desktop_driver failed to load L"winex11.drv"
00f8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00f8:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

seems like there are missing windows dependencies. Can you take a look at the WineDB? Also:
```
(07:46:07) WARNING No GPU vendor found, keep going without setting VK_ICD_FILENAMES.. 
```
seems like that Bottles doesn't not detect any GPU

**Comment by mirkobrombin** [comment]
We are receiving reports from users saying that the Fedora package lacks p7zip, which is essential for Bottles. Please file a report to the maintainer for this.
