### ISSUE TITLE
[Bug]: Cant launch Bottles (TypeError: 'type' object is not subscriptable)

### ISSUE THREAD

**Issue by Flrian** [bottlesdevs/Bottles#1259]
### Describe the bug

When trying to launch bottles the following happens:
```
❯ bottles
Traceback (most recent call last):
  File "/usr/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 30, in <module>
    from bottles.backend.managers.manager import Manager
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 68, in <module>
    class Manager:
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 438, in Manager
    ) -> Union[Union[bool, list[Any]], Any]:
TypeError: 'type' object is not subscriptable
```
Sorry if this is me fucking up while packaging it somehow, but pretty much the same rpm spec file works fine with 2022.3.14-trento-3. This was on commit 7e1fd6478a274f094cc522de89eca6f3b30b0b23, but I'm pretty sure its been happening for a week or more already.

Any idea whats going on there?

### To Reproduce

Launch bottles

### Package

Other, unofficial package

### Distribution

openSUSE Tumbleweed

### Health Check

-

**Comment by mirkobrombin** [comment]
Fixed, btw which package is it?

**Comment by Flrian** [comment]
Nice, that was fast, thank you. 
I threw a development snapshot version for personal use on the obs [here](https://build.opensuse.org/package/show/home:Flrian:Testing/bottles-snapshot) because I like trying the latest stuff.

Btw I just saw that someone else is properly packaging it in a openSUSE community repo https://build.opensuse.org/package/show/games:tools/bottles and had the same issue.

**Comment by mirkobrombin** [comment]
Ok, latest commit should do the trick
