### ISSUE TITLE
[Request] Option to change renderer

### ISSUE THREAD

**Issue by Amb0s** [bottlesdevs/Bottles#1261]
### Tell us the problem or your need
Some games require to change renderer from OpenGL to GDI to work in fullscreen. It can be done by [running](https://github.com/Winetricks/winetricks/blob/master/files/verbs/settings.txt) `winetricks renderer=gdi` or [modifying the registry key](https://wiki.winehq.org/Useful_Registry_Keys) `HKEY_CURRENT_USER\Software\Wine\Direct3D\renderer` in a prefix.

### Describe the solution you'd like
Add a user-friendly option to change the bottle renderer.

**Comment by mirkobrombin** [comment]
Thanks for reporting
