### ISSUE TITLE
[Bug]: Using custom bottles path (secondary drive) breaks the program

### ISSUE THREAD

**Issue by tgharib** [bottlesdevs/Bottles#1266]
### Describe the bug

Once I set a custom bottles path, any bottles created in that path no longer work. I can create a bottle but even after installing EGS, the EGS executables do not show in the wine prefix.

### To Reproduce

1. Install bottles in flatpak
2. Enable access to "All system files" in Flatseal for Bottles
3. Launch bottles
4. In Preferences, set a custom bottles path. I use `/mnt/games/bottles`.
5. Restart bottles
6. Create a gaming bottle
7. Install Epic Games Store in the bottle
8. Checking the wine prefix, Epic Games Store is not actually installed. Launching EGS fails.

### Package

Flatpak from Flathub

### Distribution

NixOS 21.11

### Health Check

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.10.108
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by tgharib** [comment]
So as I was filing this bug report, I tried reproducing after wiping `~/.var/app/com.usebottles.bottles` and that seems to have fixed it. I decided to create the github issue anyway in case anyone in the future has a similar problem.

**Comment by mirkobrombin** [comment]
Thanks for reporting
