### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'connect'

### ISSUE THREAD

**Issue by simonvanderveldt** [bottlesdevs/Bottles#1270]
### Describe the bug

When trying to run bottles I get the following traceback:
```
$ bottles
(19:11:17) INFO Performing Bottles checks... 
(19:11:17) INFO Runners found:
	 - sys-wine-7.4
 
(bottles:18576): Gtk-CRITICAL **: 19:11:17.471: Error building template class 'DetailsPrograms' for an instance of type 'DetailsPrograms': .:25:1 Invalid object type 'HdyStatusPage'
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 166, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/main.py", line 231, in do_activate
    win = MainWindow(
  File "/usr/share/bottles/bottles/window.py", line 115, in __init__
    page_details = DetailsView(self)
  File "/usr/share/bottles/bottles/views/details.py", line 58, in __init__
    self.view_programs = ProgramsView(self, config)
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 50, in __init__
    self.btn_add.connect("clicked", self.add)
AttributeError: 'NoneType' object has no attribute 'connect'
```
The main window occurs but none of the buttons are functional.
This happens with 2022.03.14 but I've tried version back till November last year and they show the same issue.

This same bug was mentioned in [#768](https://github.com/bottlesdevs/Bottles/issues/768#issuecomment-986313209) but it wasn't the original bug reported in that issue and that issue is now closed.

I'm on gentoo, so it might very well be something specific about my setup. I was unable to find a list of dependencies in the repo. The code is python but there's no `setup.py`, `setup.cfg` or `pyproject.toml` I could look at to check the required (Python) packages. Did I miss a file somewhere listing the dependencies?
I did check the package in the AUR and all dependencies are installed, but that doesn't tell me anything about minimum or maximum required versions, so could still be a version issue.

The ebuild (gentoo "package") I used to install bottles can be found here https://github.com/gentoo-mirror/src_prepare-overlay/blob/master/app-emulation/bottles/bottles-20220314_p3.ebuild.

**Comment by mirkobrombin** [comment]
Hi, this is the dependencies list https://github.com/bottlesdevs/Bottles/wiki/Packaging#dependencies

**Comment by simonvanderveldt** [comment]
@mirkobrombin Thanks for the pointers, libhandy was also what I was expecting. I'm on a too low version it seems, will try out a newer one and bump the dependency in the package if it works.
I guess we can close this? Or do you want to wait for me to confirm it works?

**Comment by mirkobrombin** [comment]
Waiting for response

**Comment by simonvanderveldt** [comment]
I've updated libhandy to 1.4.0 and it's working now :)
