### ISSUE TITLE
[Bug]: Steam prefixes doesn't get imported

### ISSUE THREAD

**Issue by lodriguez** [bottlesdevs/Bottles#1274]
### Describe the bug

After activating the experimental feature and restarting bottles I get "Steam path doesn't exist, creating now. " on every startup, but nothing gets imported. 

If I ctrl+r 

> INFO [Refresh] request received. 
> Traceback (most recent call last):
>   File "/usr/share/bottles/bottles/main.py", line 281, in __refresh
>     self.win.manager.update_bottles()
>   File "/usr/share/bottles/bottles/backend/managers/manager.py", line 159, in update_bottles
>     self.check_bottles(silent)
>   File "/usr/share/bottles/bottles/backend/managers/manager.py", line 828, in check_bottles
>     SteamManager.update_bottles()
>   File "/usr/share/bottles/bottles/backend/managers/steam.py", line 203, in update_bottles
>     shutil.rmtree(Paths.steam)  # generate new configs at start
>   File "/usr/lib/python3.10/shutil.py", line 712, in rmtree
>     onerror(os.lstat, path, sys.exc_info())
>   File "/usr/lib/python3.10/shutil.py", line 710, in rmtree
>     orig_st = os.lstat(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/lod/.local/share/bottles/steam

`

### To Reproduce

Just activate "Steam Proton prefixes" in Experiments

### Package

AUR ("bottles" package)

### Distribution

Arch

### Health Check

Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.1-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
Seems like that Bottles is not able to make the home/lod/.local/share/bottles/steam path. Try manually creating that folder.

**Comment by lodriguez** [comment]
If I `mkdir -p /home/lod/.local/share/bottles/steam` "INFO Steam path doesn't exist, creating now. " is gone. Nothing gets imported and the folder (~/local/share/bottles/steam) gets removed. And the same error with ctrl+r, because the folder is already gone.

**Comment by mirkobrombin** [comment]
Definitely the kind of problem I expect from an experimental feature but not quite what I was hoping for haha I will investigate it
