### ISSUE TITLE
[Request]: Allow selecting bottle/wineprefix location when creating a bottle and allow changing it in a bottle's settings.

### ISSUE THREAD

**Issue by Oreeeee** [bottlesdevs/Bottles#1275]
### Tell us the problem or your need

Bottles location is always this one that is set in global settings, so if I want to create one Bottle on SSD and second on HDD I have to change the global new bottle location.

### Describe the solution you'd like

Add a option when creating a bottle to set bottle's location and allow to change it in bottle's settings.

**Comment by mirkobrombin** [comment]
Thanks for reporting. This is something I will do in the future but at the moment it is blocked by the rewriting of the “bottles” manager
