### ISSUE TITLE
[Bug]: Launch from Terminal cannot handle spaces in path

### ISSUE THREAD

**Issue by SvdB-nonp** [bottlesdevs/Bottles#1276]
### Describe the bug

When using the 'Launch from terminal' option, programs at a location with spaces anywhere in the path will lead to FileNotFoundError.

`Failed to execute child process “bash -c /usr/bin/mangohud /usr/bin/gamemoderun  /home/<user>/.local/share/bottles/runners/GE-Proton7-10/files/bin/wine64 C:GOG”: Failed to execve: No such file or directory`

Since the play button succesfully launches the (GOG) game, I expected the game to succesfully launch with Launch from Terminal as well.

### To Reproduce

I tried 4 GOG games, all working normally, but experiencing the same bug when launched with terminal.

- Create a Gaming bottle
- Install any windows GOG game (all games will use 'C:/GOG Games' in their path)
- Launch from 'Play button' to see the game starting succesfully
- Close the game
- Click the menu next to the play button, then select Launch with Terminal
- Pop-up will show the FileNotFoundError (The error shows it tries to find C:/GOG, which indeed does not exist.)

### Package

Other, unofficial package

### Distribution

Fedora 35

### Health Check

Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.16.18-200.fc35.x86_64
Distro:
    Name: Fedora Linux
    Version: '35'
Tools:
    cabextract: true
    p7zip: false
    patool: false
    glibc_min: '2.34'
Bottles_envs: null

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

Installed with `sudo dnf install bottles`
Version: 2022.3.14-trento
I have the regular workstation version of Fedora, so that would probably mean it tries to launch through Gnome Terminal (Version 3.42.2 for GNOME 41).

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by Alzarath** [comment]
Similar issue happens with xterm.
