### ISSUE TITLE
[Bug]: Dark Mode missing

### ISSUE THREAD

**Issue by RickAndTired** [bottlesdevs/Bottles#1279]
### Describe the bug

The `Dark Mode` option is missing for me
According to the Bottles Docs there should be a `Dark Mode` option under `Preferences` - `Appearance` 

### To Reproduce

1. Click on the menu button
2. Click Preferences
3. `Dark Mode` option is missing

### Package

Flatpak from Flathub

### Distribution

Ubuntu 20.10

### Health Check

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-39-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by derkork** [comment]
Same issue here, when using the AUR package. System is in dark mode but Bottles is showing in light mode.

**Comment by mirkobrombin** [comment]
Is the system in dark mode or is it using a dark theme? Btw to force it, edit the dark option from dconf

**Comment by RickAndTired** [comment]
> Is the system in dark mode or is it using a dark theme? Btw to force it, edit the dark option from dconf

System is in dark mode

In dconf `/com/usebottles/bottles/` There is only one option `update-date`
I can't find any dark option for Bottles in dconf

**Comment by 0x6e656b6f** [comment]
> > We have removed it since the last release and is now being updated according to system preferences.
> 
> In that case My system preference is dark mode and Bottles is running in light mode
> 
> Is there anyway to force dark mode in the Flatpak?

You can force a GTK theme in flatpak by using `flatpak override --env=GTK_THEME=your-theme` or using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) under Environment Variables. Keep in mind that you need to install the respective theme first.

**Comment by RickAndTired** [comment]
> > > We have removed it since the last release and is now being updated according to system preferences.
> > 
> > 
> > In that case My system preference is dark mode and Bottles is running in light mode
> > Is there anyway to force dark mode in the Flatpak?
> 
> You can force a GTK theme in flatpak by using `flatpak override --env=GTK_THEME=your-theme` or using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) under Environment Variables. Keep in mind that you need to install the respective theme first.

Thank you, this worked

**Comment by SgtMooshroom** [comment]
Well then, _where's the dconf file in Ubuntu?!_
