### ISSUE TITLE
%5BCrash%20report%5D  join%28%29%20argument%20must%20be%20str%

### ISSUE THREAD

**Issue by VotesNHose** [bottlesdevs/Bottles#1280]
This crash report was generated by Bottles.%0A%0A**Details**%0A* **package**: Other%0A* **version**: 2022.3.28-trento-1%0A%0A%0A**Log**%0A```python3%0Ajoin%28%29%20argument%20must%20be%20str%2C%20bytes%2C%20or%20os.PathLike%20object%2C%20not%20%27NoneType%27%20%20File%20%22/usr/share/bottles/bottles/utils.py%22%2C%20line%20108%2C%20in%20__target%0A%20%20%20%20result%20%3D%20self.task_func%28%2Aargs%2C%20%2A%2Akwargs%29%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/wine/executor.py%22%2C%20line%20120%2C%20in%20run%0A%20%20%20%20return%20self.__launch_with_bridge%28%29%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/wine/executor.py%22%2C%20line%20138%2C%20in%20__launch_with_bridge%0A%20%20%20%20return%20self.__launch_exe%28%29%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/wine/executor.py%22%2C%20line%20153%2C%20in%20__launch_exe%0A%20%20%20%20winecmd%20%3D%20WineCommand%28%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/wine/winecommand.py%22%2C%20line%2093%2C%20in%20__init__%0A%20%20%20%20self.cwd%20%3D%20self.__get_cwd%28cwd%29%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/wine/winecommand.py%22%2C%20line%20109%2C%20in%20__get_cwd%0A%20%20%20%20bottle%20%3D%20ManagerUtils.get_bottle_path%28config%29%0A%0A%20%20File%20%22/usr/share/bottles/bottles/backend/utils/manager.py%22%2C%20line%2086%2C%20in%20get_bottle_path%0A%20%20%20%20return%20os.path.join%28Paths.bottles%2C%20config.get%28%22Path%22%29%29%0A%0A%20%20File%20%22/usr/lib/python3.10/posixpath.py%22%2C%20line%2090%2C%20in%20join%0A%20%20%20%20genericpath._check_arg_types%28%27join%27%2C%20a%2C%20%2Ap%29%0A%0A%20%20File%20%22/usr/lib/python3.10/genericpath.py%22%2C%20line%20152%2C%20in%20_check_arg_types%0A%20%20%20%20raise%20TypeError%28f%27%7Bfuncname%7D%28%29%20argument%20must%20be%20str%2C%20bytes%2C%20or%20%27%0A%0A```

**Comment by mirkobrombin** [comment]
Something goes wrong :| Sorry I'm going to close as the crash log is not readable
