### ISSUE TITLE
[Feature request]: Programs with Windows-like paths are run from prefix directory

### ISSUE THREAD

**Issue by Alzarath** [bottlesdevs/Bottles#1283]
### Describe the bug

When an `External_Programs`' `path` in bottle.yml is set to a Windows-like path (e.g. `C:\Program Files (x86)\Warcraft III\Frozen Throne.exe`), it will run, but as if it was run from the prefix's root directory (where the bottle.yml/etc files are located) rather than at the location of the executable. Setting the `folder` (with a Windows-like nor Unix-like path) also does not set the working directory as I might expect it to.

### To Reproduce

1. Open a Bottle's bottle.yml
2. Set an External_Programs entry's `path` to its equivalent Windows-like path (e.g. `C:\Program Files\etc`)
3. Run the program from Bottles
4. If the program would generate files in the current working directory or look for files in the current working directory, it would be checking the Bottle's prefix's directory.

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.16.13-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

My intended use-case with Bottles is to back up prefixes. I would like to strip references to full paths that might not exist in another system. A Windows-like path seems like the obvious way to accomplish this.

**Comment by Alzarath** [comment]
In case I was unclear, I described the current behavior, whereas the expected/desired behavior would be to run the executable from the directory it's contained in, not in the prefix directory.

Running an executable with an absolute path (e.g. `/home/alzarath/.local/share/bottles/bottles/Warcraft III/Frozen Throne.exe`) _would_ run the executable with the Warcraft III directory as the working directory, as desired. So it seems like a bug to me.

**Comment by mirkobrombin** [comment]
Hi, `folder` is actually the right way. It doesn't works because of how WINE handle the Windows path. I may be wrong but launching a Windows path, WINE loses the current directory that Bottles pass.

**Comment by Alzarath** [comment]
After finding [this documentation](https://wiki.winehq.org/Start) on setting the directory, I was able to get it working as desired by changing [line 368 in winecommand.py](https://github.com/bottlesdevs/Bottles/blob/dd2a77ef378e82be50d9dde1a4181f1ea88b98de/src/backend/wine/winecommand.py#L368) to:

```py
if not return_steam_cmd:
            command = f"{runner} start /d ''C:\\Program Files (x86)\\Warcraft III' {command}"
```

Obviously this is not portable and I don't know off-hand how to get a path that works for it (the absolute path from `self.cwd` does not), but hopefully it's helpful information.
