### ISSUE TITLE
[Bug]: Hanging when trying to make a gaming bottle

### ISSUE THREAD

**Issue by Exw27** [bottlesdevs/Bottles#1284]
### Describe the bug

002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
wine: Unhandled page fault on execute access to 00007F261C897BA0 at address 00007F261C897BA0 (thread 00b8), starting debugger...

This is the error that appears.

### To Reproduce

Make a gaming bottle.

### Package

AUR ("bottles" package)

### Distribution

Arch

### Health Check

Display:
            Xorg
Graphics
             NVIDIA GeForce GTX 1050 Mobile
             IIntel UHD Graphics 620 

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
This is unfortunately hard to debug. I'm sure it works on Arch because I tried a few hours ago, so I think it's something in your env. Can you post the full health check? Menu -> health check

**Comment by Exw27** [comment]
Here is my health check 

Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.16.2-2-rt19-MANJARO
Distro:
    Name: Manjaro Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null

**Comment by mirkobrombin** [comment]
Can you try with flatpak? Just for testing

**Comment by Exw27** [comment]
Same thing

002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
wine: Unhandled page fault on execute access to 00007FD8E8DD5BA0 at address 00007FD8E8DD5BA0 (thread 00bc), starting debugger...

**Comment by mirkobrombin** [comment]
Try installing caffe 7.2 and removing 7.5, then make a new bottle. Latest runner is built with fedora, maybe related

**Comment by joelostblom** [comment]
@mirkobrombin How would I go about downgrading to caffe 7.2? I have installed bottles via flatpak and it worked fine for several months but after a recent update I have started to see the same issue reported here when trying to launch an app I use for teaching (iClicker). I can't find a program called caffe in either the flatpak or Ubuntu repos.

**Comment by joelostblom** [comment]
And @Exw27 Can you confirm if this fixed the issue for you? Or did you find another workaround?

**Comment by Exw27** [comment]
> And @Exw27 Can you confirm if this fixed the issue for you? Or did you find another workaround?

I have not used bottles in a bit so no idea.

**Comment by joelostblom** [comment]
Thank you @Exw27.

It turns out that this message was a red herring. I downgraded to bottles 5.9 and I still see the message but the program now works. I opened another issue for 5.10 here https://github.com/bottlesdevs/Bottles/issues/3267
