### ISSUE TITLE
Run on OpenGL

### ISSUE THREAD

**Issue by qasem-talaee** [bottlesdevs/Bottles#1288]
Hello.I installed wine from ppa and install vulkan on it and games run with vulkan.
But with your software, considering that I have activated the vulkan in software option, but the games run on OpenGL.
What do you think is the problem?
Specifications:
OS : Ubuntu
Driver : nvidia-driver-470
Thank you.

**Comment by mirkobrombin** [comment]
Please share the health check (from menu)

**Comment by qasem-talaee** [comment]
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.13.0-39-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

**Comment by mirkobrombin** [comment]
Which games can I test? And how did you notice wine is using OpenGL instead of Vulkan?

**Comment by qasem-talaee** [comment]
I installed Mirror's Edge.
I found out using HUD. Instead of VK it prints GL.

**Comment by mirkobrombin** [comment]
Ok thanks

**Comment by mirkobrombin** [comment]
I'm not able to replicate with any games. Please ensure that "Use discrete GPU" is turned on.

**Comment by qasem-talaee** [comment]
thank you."Use discrete GPU"  is turned on.

**Comment by mirkobrombin** [comment]
Does it works using the integrate?
