### ISSUE TITLE
[Request]: add VKBasalt support

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1289]
### Tell us the problem or your need

In Windows i used to use Reshade to get better performance. Looking online on Linux users use VKBasalt instead. Lutris and Steam has support for this.
I’m from poor country so it is beneficial to get as much as i can from tweaks and caches hahahahaha

https://github.com/DadSchoorse/vkBasalt

https://github.com/flathub/com.valvesoftware.Steam/issues/625

### Describe the solution you'd like

Add support for VKBasalt

### Other solutions?

n/a

### Additional context and references

n/a

**Comment by mirkobrombin** [comment]
Thanks for reporting
