### ISSUE TITLE
[Bug]: versioning tool does not preserve symlinks

### ISSUE THREAD

**Issue by omichalek** [bottlesdevs/Bottles#1290]
### Describe the bug

I use symlinks inside bottles to share data between prefixes as well as expose it in appropriate places. eg.
`C:/users/steamuser/Documents/` pointing to `~/Wine`
or
`C:/Program Files (x86)/GOG Galaxy/Games` inside GOG Galaxy prefix pointing to `~/Games/GOG`
so that a game could be launched inside a separate prefix.

When I tried to create new state using the versioning tool Bottles starting copying data the symlinks point to. In order to create a backup Bottles should honor symlinks.

### To Reproduce

1. have a symlink inside the bottle
2. in the "versioning" click on "create new state"
3. Bottles does not replicate symlinks but copies their destination

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue

### Health Check

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.1-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

### Display Protocol

Wayland

**Comment by mirkobrombin** [comment]
Thanks for reporting
