### ISSUE TITLE
[Bug]: Bottles does not work with a custom bottles path

### ISSUE THREAD

**Issue by ItzTobias** [bottlesdevs/Bottles#1297]
### Describe the bug

Bottles works fine when the custom bottles path is at the default location but it acts strangely when the path is on a different SSD.

### To Reproduce

1. Open Bottles
2. Click on the three dots
3. Select Preferences
4. Change the custom bottles path setting to a path that is not on your root drive
5. Create a new Bottle
6. Install Battle.net or EA Launcher
7. The Programs don't work (But they work when they are installed on the default location)

### Package

Flatpak from Flathub

### Distribution

Manjaro

### Health Check

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.16.14-1-MANJARO
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

The path I used was /mnt/ssd-1/Bottles.
The bottles folder is owned by my user.
Creating the bottle works but Installing software causes trouble.
I already mentioned EA Launcher and Battle.net not working.
The bug also affects other software. (Some Windows software from school does not work when installed using a custom path and Origin only worked by installing it on my root drive and then moving it to my second SSD)

It would be very nice if that bug was fixed because a lot of people install their games on a different drive.

**Comment by mirkobrombin** [comment]
Did you give permission to reach that path?

**Comment by ItzTobias** [comment]
Yes. The folder /mnt/ssd-1/Bottles has the exact same permissions as the default bottles folder. Do you mean any special permissions? Bottles is able to create folders inside that folder but the apps behave strangely.

**Comment by mirkobrombin** [comment]
I use flatseal but it should be ok. So Bottles make the bottle but any installer works. I have received confirmation from some Steam deck users that they use an external disc as a bottle store and it works. Can you maybe make sure with Flatseal that the permissions are correct? Never used the CLI for this purpose but I expect an override

**Comment by ItzTobias** [comment]
I enabled every permission in flatseal that has anything to do with file permissions and I am still experiencing this issue.
I also created an arch linux virtual machine with kde, wayland, and a second virtual hard drive and I'm experiencing the problems there too. I don't think it has anything to do with the installers. They sometimes work and sometimes don't.

I had an issue similar to this a few days ago where I wanted to play a game that uses EasyAntiCheat using Steam but it didn't work. The solution was to move some compatibility package and proton from my main drive to the drive that had the game installed. Maybe the problem here is similar. Maybe the apps need wine or some other stuff installed on the same drive in order to work.

**Comment by mirkobrombin** [comment]
You just need one permission which is the full path to the folder, like I'm doing here:

![image](https://user-images.githubusercontent.com/9479903/162795022-864ab552-f80d-4685-86a6-1bbef14a4a30.png)


> I had an issue similar to this a few days ago where I wanted to play a game that uses EasyAntiCheat using Steam but it didn't work. The solution was to move some compatibility package and proton from my main drive to the drive that had the game installed. Maybe the problem here is similar. Maybe the apps need wine or some other stuff installed on the same drive in order to work.

Nope, the flatpak came with all needed dependencies. The problem should related to permission in somehow. I'll test on my own using an usb

**Comment by ItzTobias** [comment]
Maybe you should also try to reproduce the bug with the AUR version to see if it has anything to do with the Flatpak version. I tried to install the AUR version but it doesn't work in Manjaro because it requires `libhandy-1' ['>= 1.5']` and the newest version in the Manjaro repos is 1.4.0. I also tried to install it in my arch virtual machine but I can't install `meson` (a dependency of the AUR version) at the moment for some reason. I'll try it as soon as possible. Maybe you have more luck.

**Comment by mirkobrombin** [comment]
In manjaro you have to install libhandy-git.

**Comment by ItzTobias** [comment]
I managed to install the AUR version in my virtual machine and I still have the problem. I guess it doesn't have anything to do with flatpak permissions.

**Comment by mirkobrombin** [comment]
I'm not able to reproduce the problem, waiting for other reports

**Comment by ItzTobias** [comment]
Have you tried to reproduce it in a virtual machine? What software did you test and what permissions (linux and flatpak) did you give Bottles / the Target folder? Maybe I just configured something wrong.

**Comment by mirkobrombin** [comment]
I've just plugged in a new disk, set the bottles path to it and give Bottles the permission to full disk path, then after restart it make the new bottle in my external disk. Tested with Notepad++.

My disk is ext4.

**Comment by mirkobrombin** [comment]
Which format is your disk?

**Comment by ItzTobias** [comment]
My disks are ext4

**Comment by ItzTobias** [comment]
I'm completely confused. I just tried to record everything and it works now. I tried to install Battle.net and the EA launcher like ten times over the past three days and created a virtual machine just to make sure that it is not something that only happens on my system. I'm so sorry for wasting your time.

**Comment by mirkobrombin** [comment]
Not a problem. Reach me again if it appear again ;) This is still something that should be monitored.

**Comment by ItzTobias** [comment]
Should I close this issue?

**Comment by mirkobrombin** [comment]
Keep it open for a while, maybe other users are experiencing the same problem
