### ISSUE TITLE
[Request] Use XDG base directories

### ISSUE THREAD

**Issue by wsdfhjxc** [bottlesdevs/Bottles#130]
**Is your feature request related to a problem? Please describe.**
One thing I've noticed is that the Flatpak version is non-functional when filesystem access to `~/.local/share/bottles` is denied (runners can't be even downloaded, the config/data directories structure is missing, and nothing can be done at that point).

**Describe the solution you'd like**
I guess it's because of the `~/.local/share/bottles` path being hardcoded, instead of using XDG base directories, which would be then evaluated to Flatpak-provided locations (at least I hope so this is sufficient to get it working, see [here](https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories) for details).

**Additional context**
For the Flatpak version, all config/data/cache writing operations should fall back to `~/.var/app/com.usebottles.bottles/*`, but it seems not to be the case here. Denying access to the host filesystem is perfectly reasonable, and all other Flatpak apps I've tried work correctly within their own location at `~/.var/app/some.app.name` (they manage to write config/data/cache here).

**Comment by mirkobrombin** [comment]
I never went too deep into Flatpak, I'll fix it once v3 is released, thank you very much.

Altrought  if you know how to fix this, without compromising the native package and AppImage, you can create a PR.

**Comment by ManIVIctorious** [comment]
As an intermediate workaround you can disable the access to your home directory and set the persist flags for the mentioned directories

`flatpak --user override --nofilesystem=home --persist=.local/share/bottles com.usebottles.bottles`

(disclaimer, typed from my phone, expect some typos)

**Comment by mirkobrombin** [comment]
I am going to close this issue as we are leaving Flatpak (https://mirko.pm/blog/bottles-will-leave-flatpak/).

**Comment by TomaszGasior** [comment]
Proper support for XDG directories it not related to the Flatpak itself. When your app is not compatible with XDG directories, it's harder to package it properly to Flatpak but even without Flatpak release. compatibility with XDG directories is must-have for each properly written Linux app.

From my experience the problem exists because Bottles hardcodes `~/.local/share/bottles` which is incorrect. Instead, XDG environment variables should be used to retrieve `~/.local/share` part or fallback with `~/.local/share` value should be used if environment variable does not exist.

**Comment by mirkobrombin** [comment]
This actually makes sense

**Comment by sonnyp** [comment]
@mirkobrombin can you assign me?

**Comment by mirkobrombin** [comment]
Here we go

**Comment by nanonyme** [comment]
I guess this is related to https://github.com/bottlesdevs/Bottles/issues/997. Sorry, I didn't notice this one.

**Comment by mirkobrombin** [comment]
Oh yes, I think we can close now.
