### ISSUE TITLE
How can i change the windows language

### ISSUE THREAD

**Issue by hegel1337** [bottlesdevs/Bottles#1304]
The software that i'm trying to run needs to have Brazilian regional settings. in Wine commandline. On terminal, i use LANG=pt_PT.UTF-8 wine software.exe
how can i add the wine prefix??
thx

**Comment by Alzarath** [comment]
Hello. If all you need to do is set the LANG variable, I can think of two options:

You could set a [Program's launch options](https://i.imgur.com/AtPNfHA.png) to:

```
LANG=pt_PT.UTF-8 %command%
```

You could try adding an Environment Variable for a Bottle [under Preferences](https://i.imgur.com/YdSmRVB.png) to make it apply universally.

**Comment by mirkobrombin** [comment]
> Hello. If all you need to do is set the LANG variable, I can think of two options:
> 
> You could set a [Program's launch options](https://i.imgur.com/AtPNfHA.png) to:
> 
> ```
> LANG=pt_PT.UTF-8 %command%
> ```
> 
> You could try adding an Environment Variable for a Bottle [under Preferences](https://i.imgur.com/YdSmRVB.png) to make it apply universally.

Those are both good solutions.

**Comment by hegel1337** [comment]
![image](https://user-images.githubusercontent.com/13904986/164113328-5ffd60c5-475d-4e03-b4b0-56e25bd5a757.png)
Hi, tanks for replying. I tried to do it, but i couldn't make work. Despite inserting the on launch options, when i open the program it prompts that my regional settings is worg :(
The environment variable couldn't be set too.

**Comment by mirkobrombin** [comment]
> ![image](https://user-images.githubusercontent.com/13904986/164113328-5ffd60c5-475d-4e03-b4b0-56e25bd5a757.png) Hi, tanks for replying. I tried to do it, but i couldn't make work. Despite inserting the on launch options, when i open the program it prompts that my regional settings is worg :( The environment variable couldn't be set too.

Try with `LC_ALL=pt_PT.UTF-8` according to your locale
