### ISSUE TITLE
[Request] Being able to install all wine versions

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#131]
**Is your feature request related to a problem? Please describe.**
Many games don't work with the wine versions that exist for bottles.

**Describe the solution you'd like**
That you can download all wine and proton versions

**Comment by mirkobrombin** [comment]
Bottles **is not** Lutris or POL.Btw providing and maintaining multiple versions of wine and Proton takes a lot of work.You can do this yourself by creating a PR in the [components](https://github.com/bottlesdevs/components) repository.

Each wine should be:
- Tested
- Provide a direct and immutable download link
