### ISSUE TITLE
[Request]: Add support for zoom or full app scaling

### ISSUE THREAD

**Issue by travier** [bottlesdevs/Bottles#1312]
### Tell us the problem or your need

First of all, thanks a lot for this great app!

Right now, we can set DPI scaling in wine but this does not work well with some apps, especially old games, that do their own rendering. Some games also have issues with full screen scaling.

Thus it would be interesting if we could set a configurable zoom or window scaling value to essentially have the app use small resolutions and then have the output be zoomed on the screen.

### Describe the solution you'd like

This could be an interface to setup a solution like this one: https://bbs.archlinux.org/viewtopic.php?id=192733

### Other solutions?

Excusing scaling support in wine that does work on this case: https://askubuntu.com/questions/1337156/how-do-i-set-scaling-in-wine

Alternative in proton: WINE_FULLSCREEN_INTEGER_SCALING https://github.com/ValveSoftware/Proton

### Additional context and references

Known games with this issue:
- Imperialism II

Thanks!

**Comment by mirkobrombin** [comment]
Hi thanks for reporting. Did you try gamescope with scaling?

**Comment by ghtesting2020** [comment]
> Hi thanks for reporting. Did you try gamescope with custom resolution?

Currently those of us with Nvidea cards cannot use gamescope but Nvidea will release support in future drivers. Also gamescope has fixes required
https://github.com/Plagman/gamescope/pull/454

I suppose you could just wait for those instead of implementing this ticket since gamescope is supposed to be good from what I heard.

**Comment by travier** [comment]
> Hi thanks for reporting. Did you try gamescope with custom resolution?

Did not know about that. Will take a look!

**Comment by mirkobrombin** [comment]
> > Hi thanks for reporting. Did you try gamescope with custom resolution?
> 
> Did not know about that. Will take a look!

Let me know if that's what you need

**Comment by travier** [comment]
Hum, it tells me that "This feature is not available on your system". I'm using the Flatpak version (Bottles                                       com.usebottles.bottles 2022.4.14-trento) on Fedora 35 KDE Wayland session.

**Comment by mirkobrombin** [comment]
You have to install `com.valvesoftware.Steam.Utility.gamescope`

**Comment by travier** [comment]
Looks like this works and is definitely what I needed. I'll make a PR to add docs.

**Comment by mirkobrombin** [comment]
Thanks! I'll keep this open in case the nvidia support take too long to get implemented
