### ISSUE TITLE
[Request]: Animate the loading screen

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1313]
### Tell us the problem or your need

It is good design to have a loading screen animated. In the issue https://github.com/bottlesdevs/Bottles/issues/1311 I waited a couple minutes before realizing Bottles was frozen and would never load before I had to kill it.

### Describe the solution you'd like

Animate the loading screen. Maybe the "..." could be animated to go . .. ... . .. ... . .. ... as it loads to show feedback to the user.

**Comment by MiguelGuthridge** [comment]
+1 on this, little animations for long-running tasks are an absolute joy when they're done well.

**Comment by mirkobrombin** [comment]
How many seconds are meant too long? Bottles startup take ~2s. If something goes wrong, animation or not it will just never start

**Comment by ghtesting2020** [comment]
For me personally my computer isn't the best and most of the time I am offline (does being offline add to the startup time due to some checks not working?). I would say my startup time is more like 5 to 10 seconds sometimes.

**Comment by mirkobrombin** [comment]
Offline mode disable a lot of checks, it is almost instant on mine. Also the winebridge download (which was causing stuck in some distro) is now disabled

**Comment by ghtesting2020** [comment]
It would still be nice for additional polish. We don't all have beefy powerful gaming computers :( mine is from 2013 haha

**Comment by mirkobrombin** [comment]
Ping #610
