### ISSUE TITLE
[Feature request] update desktop entries 

### ISSUE THREAD

**Issue by emiltang** [bottlesdevs/Bottles#1315]
### Bottles version: 
2022.3.28-trento-1

### Desktop Environment:
Gnome 42.0

## Steps to reproduce:
 1. Create a new bottles.
 2. Install a program.
 3. Select a Bottle an got to "Details & Utilities" > Programs.
 4. Click the menu to the right and click "Add desktop entry" .
 5. Repeat step 4 two or more times.
 6. Open your DE's menu and observe multiple desktop entries of the same program.

## Expected Result:
Only one .desktop file is created and multiple invokes updates or recreates the file.

## Observed Result:
Multiple identical appearing desktop entities clutter the applications menu.

**Comment by emiltang** [comment]
Took a look at the code and seem pretty straight forward, could just return None if a file matching the pattern already exists.

**Comment by mirkobrombin** [comment]
Thanks again for your contribution
