### ISSUE TITLE
[Request]: Optional minimize Bottles when play button is pressed

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1316]
### Tell us the problem or your need

Along with the option to close bottles when the play button is pressed it would be nice to have another setting to only minimize instead of fully close Bottles.

These settings could either be per bottle or for the entire Bottles application that includes all bottles.

### Describe the solution you'd like

Setting that minimizes Bottles when the play button is pressed on a bottle and launches a game/app. Another setting to close Bottles instead of minimize upon launching a game/app.

**Comment by mirkobrombin** [comment]
I have highly evaluated this feature request, concluding that it is not the best solution. However, there are few occasions when it is necessary to minimize the window automatically and it can still be done afterwards.

Adding a setting for each individual behavior causes confusion.
