### ISSUE TITLE
[Bug]: flatpak: Can't launch multible applications from terminal

### ISSUE THREAD

**Issue by ServerMonkey** [bottlesdevs/Bottles#1324]
### Describe the bug

Launching a single application from bottles cli individually works fine.
But when I open a second terminal and try to launch another application, after around 20 seconds I get the error:
_"Failed to register: Timeout was reached"_

For example:
**Terminal A:**
`/usr/bin/flatpak run -v com.usebottles.bottles -b Win-Apps -e "<FULLPATH>/drive_c/SpeedCrunch/speedcrunch.exe"`
**Terminal B:**
`/usr/bin/flatpak run -v com.usebottles.bottles -b Win-Apps -e "<FULLPATH>/drive_c/Firefox Portable ESR/FirefoxPortable.exe"`

Shell output:
The error occures after:
`F: Running 'bwrap --args 41 bottles -b Win-Apps -e '/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/Win-Apps/drive_c/Firefox Portable ESR/FirefoxPortable.exe''`
And aborts before the first INFO stage, which would usually be like:
`(xx:xx:xx) INFO Performing Bottles checks...`

### To Reproduce

Open two terminals, on the first start any Wine application like this:
`/usr/bin/flatpak run -v com.usebottles.bottles -b Win-Apps -e "/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/Win-Apps/drive_c/SpeedCrunch/speedcrunch.exe"`
This works fine.

Now open a second terminal and try to launch another application:
`/usr/bin/flatpak run -v com.usebottles.bottles -b Win-Apps -e "/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/Win-Apps/drive_c/Firefox Portable ESR/FirefoxPortable.exe"`
This will hang / and abort after around 20 seconds.

### Package

Flatpak from Flathub

### Distribution

Debian 11 x64 stable, latest upgrades as of this date.

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.10.0-13-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Bottles version: 2022.4.14-trento stable
Tested with Bottles default "Applications" environment.
Debian running with XFCE and picom

**Comment by mirkobrombin** [comment]
Hi, old cli doesn't support multiple instances. Use the new one: https://docs.usebottles.com/advanced/cli
Currently Bottles doesn't use this for desktop entries but will do soon.
