### ISSUE TITLE
[Bug]: Desktop file does not execute exe if the bottle has a space in its name

### ISSUE THREAD

**Issue by emiltang** [bottlesdevs/Bottles#1325]
## Observed Behavior
When i click a desktop icon with a bottle with a space in its name it only opens the main page bottles

## Expected Behavior
Clicking the icon should run the exe in a bottle

### To Reproduce

1. Create a new bottle with a space in the name
2. Install a program
3. Create a desktop icon
4. Click icon

### Package

From source

### Distribution

Arch

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Pull request incoming in sec

**Comment by mirkobrombin** [comment]
This could actually be a problem. Thanks for reporting
