### ISSUE TITLE
[Bug]: GLib-GIO-ERROR Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-library'

### ISSUE THREAD

**Issue by VortexAcherontic** [bottlesdevs/Bottles#1326]
### Describe the bug

Hey there this might not be related to Bottles but rather to something wrong on my system but at this point I don't know where to ask as I am trying to get this error straight since 2h now x.x

What happened:

I'm trying to update the latest version of bottles for the openSUSE repos and after installing the locally build RPM I got the following error:  
`GLib-GIO-ERROR **: 22:49:02.558: Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-library'`

I checked `/usr/share/glib-2.0/schemas/com.usebottles.bottles.gschema.xml` and the above key is there.  
Also the file gschemas.compiled was rebuild successfully after installing bottles.  
Furthermore other applications having some gschema file in there seem to still run fine.  

Also I tried manually rebuilding the schemas using:
`sudo glib-compile-schemas --strict /usr/share/glib-2.0/schemas` to see if it aborts due to some errors. Yet to no avail.  

Next I also noticed that the previous version also now suddenly suffers from this issue which worked fine not two days ago.  

So yeah the signs are pretty good that I messed up something on my end but I am too inexperienced to find out what this might be.  

As I am now reaching for any straw I can get I now asking here. ^^"

### To Reproduce

1. Build Bottles
2. Install package
3. Run application

### Package

Other, unofficial package

### Distribution

openSUSE Tumbleweed

### Health Check

```shell
This one is from the flatpak version as the native package does not launch.

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.2-1-default
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
I had this problem, fixed by reinstalling Bottles. You can safely uninstall the flatpak and install again. Make a backup of `~/.var/app/com.usebottles.bottles/data/bottles` if you feel unconfortable.

**Comment by VortexAcherontic** [comment]
I guess my comment lead to confusion.

The flatpak version is actually fine I am struggle to get the compiled and installed RPM version to function properly.  
Also tried re installing it several time didn't helped.

But also I can confirm that this has nothing to do with bottles itself.  
I just installed the locally build RPM in a fresh openSUSE Tumbleweed VM and the package works just fine.

Anyways, thank you for your time and efforts to make this awesome application :)
