### ISSUE TITLE
[Bug]: GameMode not activated from starting game via CLI

### ISSUE THREAD

**Issue by MementoVile** [bottlesdevs/Bottles#1334]
### Describe the bug

When launching an application via the Bottles CLI, GameMode is not activated despite being turned on for that bottle.

### To Reproduce

1. Run e.g. `flatpak run com.usebottles.bottles -b "Guild-Wars-2" -e "C:\\GW2\\Gw2-64.exe" -a "-autologin -log -maploadinfo"`
2. See from `gamemoded -s` or the journal that gamemode is not active.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

GameMode is activated when launching from the Bottles GUI.

**Comment by mirkobrombin** [comment]
Terminal command are launched with minimal WineCommnbd which disable some tools as this is intended for maintenance and developing purposes. You can still force it by editing program launch options.

**Comment by MementoVile** [comment]
Changed it to use the actual bottles-cli and it works correctly, thank you.

**Comment by mirkobrombin** [comment]
You are welcome!
