### ISSUE TITLE
Collection of issues with launch options

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#1336]
### Describe the bug

This is https://github.com/bottlesdevs/Bottles/issues/948#issuecomment-1100666070 in its own proper issue.

There are several things I've noticed while playing around with launch options and post-run scripts:

- [x] White spaces in the script path aren't handled
- [x] Launch options and the post-run-script setting will get ignored until Bottles is restarted
  - [x] Re-viewing the launch options won't show the current values until Bottles is restarted (probably related to the above)
- [x] There's currently no way to see if there's a post-run script set, which it is set to and a script can't be removed.
  There are several places with similar problems:
  - [x] The `WorkingDir` of a bottle
  - [x] The `custom_bottles_path` in the settings
- [x] The description for the launch options are translated which results telling me to put in `%befehl%` instead of `%command%` - I've tried, it's not working this way.

### To Reproduce

<details>
<summary>Launch options ignored until restart</summary>

1. Create a bottle
2. Add a program
3. Add some launch options
4. Save launch options
5. Review launch options - Launch options text box is empty
7. Launch program - Observe launch options aren't given to the program
9. Restart Bottles
10. Review launch options - Launch options are displayed correctly
12. Program launch now gets the launch options

</details>

---

<details>
<summary>White space in script path</summary>

1. Add a post-run script which has a white space in the path to a program
2. Script is not running after the program exits and an error is thrown that the script can't be found

</details>

---

<details>
<summary>Translated %command%</summary>

![grafik](https://user-images.githubusercontent.com/1408843/163731089-fdff758f-7557-4e15-9bf8-465946615de5.png)

</details>

---

<details>
<summary>Unable to tell if a script is given</summary>

1. Set a post-run script to a program
2. Try to see if a script is set - There's no indicator of the current state

Without script:
![image](https://user-images.githubusercontent.com/1408843/163810528-f98c5b38-ced2-41d3-966f-2b4a213229ba.png)

With script:
![image](https://user-images.githubusercontent.com/1408843/163810385-6e7325e0-46ac-455e-8651-e7cef4492eac.png)

</details>

### Package

AUR ("bottles" package)

### Distribution

Arch linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
The title is a bit confusing, the issue mixes problems from several points, not only in the launch options.
