### ISSUE TITLE
[Bug]: DXVK usage persists even when disabled

### ISSUE THREAD

**Issue by Dansito** [bottlesdevs/Bottles#1341]
### Describe the bug

There are some games where you get better performance with opengl or directly only work with opengl, so I have one of those games and proceeded to disable the use of DXVK from the preferences of my bottle, but even after doing so the use of DXVK persisted therefore it was not possible to run the game normally, the only way I could open the game was with the tool to uninstall/add programs (it is a portable game, you only need to open an .exe) which would be equivalent to a pure wine

### To Reproduce

1) Open bottles
2)Create new bottle
3) Add a game that does not need installation (portable), it opens only by opening the .exe in its folder
4) Wait for the crash because the game only works with opengl

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.34-1-lts
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

I love bottles and I hope the solution to this problem, Thanks to the developers for creating this amazing tool.

**Comment by mirkobrombin** [comment]
Cant replicate. Tested with some games from itch.io, disabling dxvk it is no more loaded. The problem should be elsewhere as dxvk install/uninstall is just add/remove register/unregister some dll and Bottles is doing this in the right way.

Can you try making a bottle using the Custom environment to ensure that DXVK is never installed. I'll expect the same behavior. It may also be a dependencies related problem, as gaming and software envs install some of those automatically.

**Comment by Dansito** [comment]
I'm investigating and it seems that this particular pc is not compatible with vulkan, for that reason DXVK fails, on my other pc it ran perfectly since it does have vulkan. Could you give me a brief explanation of how to completely disable the use of dxvk?

**Comment by mirkobrombin** [comment]
Just switching it if from the bottle preferences. You can also make a new bottle using the custom environment to ensure that it will never be installed and so test with it
