### ISSUE TITLE
[Bug]: First time download gets stuck at Caffe with different checksum

### ISSUE THREAD

**Issue by Oreeeee** [bottlesdevs/Bottles#1344]
### Describe the bug

When starting Bottles for the first time, it starts downloading corrupted Caffe archive.

### To Reproduce

Start Bottles for the first time, click next a few times and install initial files.

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
I can't start health check because the popup is blocking it.
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Here are logs: https://pastebin.com/raw/wNrLTng7

**Comment by Oreeeee** [comment]
Closing, this isn't issue with Bottles itself, but with checksum not matching in https://github.com/bottlesdevs/components/blob/main/runners/wine/caffe-7.6.yml

**Comment by DevilzAvacado** [comment]
I'm getting this same exact issue. I'm on manjaro and using the flatpak. I'm fairly new to linux so i'm at a loss with this.

**Comment by tychii93** [comment]
I'm having the exact same issue as well.  Both from AUR and Flatpak.

**Comment by Tennyleaz** [comment]
#https://github.com/bottlesdevs/components/issues/127
