### ISSUE TITLE
[Request]: Add an option to let the app access hardware 

### ISSUE THREAD

**Issue by bahtioraliev** [bottlesdevs/Bottles#1351]
### Tell us the problem or your need

In case there is a need to upgrade a thunderbolt docking station with a new firmware, which run on Windows only, you can't install it  since the hardware is unrecognized. 
For example - https://support.lenovo.com/il/en/solutions/pd500265
The Lenovo utility wouldn't recognize the  thunderbolt docking station due to app isolation. 

### Describe the solution you'd like

Let the bottle access the hardware.

**Comment by mirkobrombin** [comment]
WINE has already access to your hardware. The flatpak too has right permissions to access hw. The problem may be related by software incompatibility with WINE
