### ISSUE TITLE
[Bug]: Bottles hangs on KDE Plasma with compositor disabled

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1355]
### Describe the bug

When i disable the compositor in KDE Plasma it takes Bottles over a minute to launch and does not display properly. There is no error logged when launching via terminal. It just takes a very long time to launch for some reason.

### To Reproduce

1. Disable compositor in KDE settings>Display and Monitor>uncheck Compositing "Enable on startup 
2. restart your computer
3. Launch Bottles and it takes over a minute and does not display properly

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
No issues in health. Works fine if i enable Compositing
```

### Display Protocol

X11

**Comment by mirkobrombin** [comment]
I think this is not a Bottles problem. We do nothing with the compositor and start up just ping some urls
