### ISSUE TITLE
[Bug]: The .bat scripts doesn't like spaces in path

### ISSUE THREAD

**Issue by elgabo86** [bottlesdevs/Bottles#1357]
### Describe the bug

If a run a .bat script to open a .exe and if there is any space on the path, the script doesn't find the .exe on the same folder

Example :  ~/.var/app/com.usebottles.bottles/data/bottles/bottles/gaming1/drive_c/Games/adi 2/launch.bat

If i remove any space on the path, it finds the .exe 

Example :  ~/.var/app/com.usebottles.bottles/data/bottles/bottles/gaming1/drive_c/Games/adi2/launch.bat

Some old games like mugen have the same problem if there is any space on the executable name. (it doesn't find the data on the same folder), but rename the .exe without space works.

Maybe a problem with the working path resolver?

### To Reproduce

- Run any .bat script to launch an executable with a space in the path
- Run old games like Mugen with a space in it name.

### Package

Flatpak from Flathub

### Distribution

Archlinux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by mirkobrombin** [comment]
I think there is another problem. Just tested:
```
>>> path = "~/.var/app/com.usebottles.bottles/data/bottles/bottles/gaming1/drive_c/Games/adi 2/launch.bat"
>>> print(os.path.dirname(path))
~/.var/app/com.usebottles.bottles/data/bottles/bottles/gaming1/drive_c/Games/adi 2
>>> 
```


It pick the right place. The problem should be elsewhere

**Comment by elgabo86** [comment]
With space (super heroes.exe) : 

![Screenshot_20220421_122908](https://user-images.githubusercontent.com/25168862/164439995-d4784738-3665-410a-a2ca-9cf4f5e09682.png)

Without space (superheroes.exe): 

![Screenshot_20220421_123138](https://user-images.githubusercontent.com/25168862/164440010-fc98d85f-f3a2-4349-b33f-03086319927b.png)

**Comment by mirkobrombin** [comment]
Is this game for free? So I can test

**Comment by elgabo86** [comment]
The website is in the screenshot :) , you can download directly from there.

**Comment by mirkobrombin** [comment]
I didn't noticed it

**Comment by mirkobrombin** [comment]
That website is a pain. Idk where should I download the game, and I hope this is not crack
