### ISSUE TITLE
[Bug]: Apostrophe naming inconsistency

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1362]
### Describe the bug

Bottles forbids me from creating a bottle with an apostrophe. However, when duplicating a bottle, Bottles will allow me.

### To Reproduce

1. click `+` to add a new game
2. press apostrophe (`'`), you will see that Bottles shows an exclamation point as a means to forbid me from creating a bottle.

Duplication:
1. open a bottle
2. press the arrow down button
3. press "Duplicate bottle"
4. use a comma; Bottles will allow me

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Here's a video:

https://user-images.githubusercontent.com/50847364/164817723-b05cb598-ea6f-4e74-b015-856c0af6fa97.mp4

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by TheEvilSkeleton** [comment]
I just noticed something else. With the duplicate bottle, it creates a directory that includes the apostrophe and spaces:

```
$ ls
Assassins-Creed
"Assassin's Creed Backup"
```

The first directory is the original bottle, the second directory is the backup bottle.

**Comment by mirkobrombin** [comment]
I'll check asap
