### ISSUE TITLE
[Bug]: Problems running games without installers

### ISSUE THREAD

**Issue by Dansito** [bottlesdevs/Bottles#1367]
### Describe the bug

Bottles or wine in particular (I don't know which of the two), they have a problem in flatpak for the execution of portable games (without installer) I tried this in 3 different games to verify if it was not the fault of a particular game, then the I tried all 3 in wine on the system and all 3 worked. After doing different tests, I came to the conclusion that in the isolated environment created by the bottle (flatpak) no game that does not have an installer works, this means games that come uncompressed and only have to open the .exe, the The only solution to open these games was, Create a folder in /home, with flatseal give permissions to bottles to read the home, and through the "programs" tab add the game manually from there, and then I could run it normally, if I tried executing the .exe on the default button always produced an error. This only happens with games that don't have an installer, for some reason games with an installer work fine (some don't), but the steps I explained above solve all the problems.

![imagen](https://user-images.githubusercontent.com/84112405/164975381-5c5671ee-458f-499f-8251-094283e3b8a2.png)
Default button that does not work in portable .exe's

---
![imagen](https://user-images.githubusercontent.com/84112405/164975416-2fa1cea4-79e3-476d-b8d4-4cc65ffd613c.png)
This is where I was able to add it manually and get it working

### To Reproduce

1)Create the bottle
2)Download any game without installer(uncompressed/portable)
3) run and look for errors

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.35-1-lts
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

Tested Games: Touhou 6, Touhou 7, Geometry Dash

The only solution to the errors was what I put above, give read permissions to home, create a folder in home and save the games there, add it to the programs tab and play :)

**Comment by mirkobrombin** [comment]
Hi thanks for reporting. This issue is already covered by our documentation https://docs.usebottles.com/flatpak/black-screen-or-silent-crash

will be improved soon with neighbors portal
