### ISSUE TITLE
[Bug]: Disabling Library mode fails to launch Bottles upon relaunch

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1371]
### Describe the bug

Disabling Library mode fails to launch Bottles upon relaunch. It gets stuck at the "Loading..." screen.

### To Reproduce

1. Open the menu
2. Click Preferences
3. Go to the Experiments tab
4. Enable "Library mode"
5. Relaunch Bottles
6. Add some executables in the library
7. Disable Library mode from the Experiments tab

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-302.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

#### Workaround

As a workaround, deleting `~/.var/app/com.usebottles.bottles/data/bottles/library.yml` and relaunching fixes the issue.

#### Image
Here's the picture:

![1](https://cdn.discordapp.com/attachments/956654626671845446/968130044050440243/unknown.png)

**Comment by mirkobrombin** [comment]
I'm not able to replicate this. I'm using the main branch which includes some fixes, so the bug may be gone.

**Comment by mirkobrombin** [comment]
> I'm not able to replicate this. I'm using the main branch which includes some fixes, so the bug may be gone.

Closing as I'm not able to replicate. I think this was fixed some commits ago.



> I got this bug on Flatpak with X11 It doesn't have to do with disabling Library mode as I never disabled it
> 
> It looks like adding a program/game to your library twice causes the bug for me

Sounds like a different problem. Can you try latest release and then open a new issue if the problem persist?
