### ISSUE TITLE
[Bug]: I cannot install some games because error "not enough memory"

### ISSUE THREAD

**Issue by warcayac** [bottlesdevs/Bottles#1372]
### Describe the bug

I cannot install some big-sized games (approx. 4GB, like Age of Empires 3 Definitive Edition, or Civilization VI Digital Deluxe), during the installation the process is aborted with the following message:

```
An error occurred while unpacking: Not enough memory!
Unarc.dll returned an error code: -5
ERROR: archive data corrupted (decompression fails)
```

### To Reproduce

1. Go my bottle "Gaming Zone"
2. Press the button "Run"
3. Select the file "setup.exe"
4. Installation is running 
5. Installation is aborted with the above message

### Package

AUR ("bottles" package)

### Distribution

Manjaro Linux x86_64, Kernel: 5.17.1-3-MANJARO, RAM: Memory: 15985MiB

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.1-3-MANJARO
Distro:
    Name: Manjaro Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by elgabo86** [comment]
Some fitgirl installer simply don't work on wine (unarc.dll error). You can find alternative installers but this is not the subject.

**Comment by pietrodicaprio** [comment]
I'm sorry but we do not support execution of cracked software. Moreover looking on Google this issue exists since years due to a problem with WINE itself. There is nothing we can do even if you have a legal copy of the software that provides this problem.
