### ISSUE TITLE
[Bug]: Change launch options does not consistently save settings

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1376]
### Describe the bug

When I try to add launch options by going to Details & Utilities>Click the 3 dots beside the play button>Change launch options while inside a bottle, the parameters I add are saved at what seems to be random time.
For example, I want to add "vblank_mode=0" and click save then go look again it is empty. Then add it and click save and go look and it is there now!!!! Then I want to add a new one like MaxFramesAllowed=1 and replaced the old one and click save and it is empty!!!! Ahhhhh going crazy

### To Reproduce

1. Details & Utilities
2. Click the 3 dots beside the play button
3. Click Change launch options while inside a bottle
4. Add a launch parameter of your choice
5. click save and look at launch option

it might be empty or it might save, depends how Bottles feels hahaha. Keep trying and it is not consistent.

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
No issues here.
```

**Comment by mirkobrombin** [comment]
Fixed some commits ago
