### ISSUE TITLE
[Request]: Progress bar for downloads happening

### ISSUE THREAD

**Issue by IagoFloriano** [bottlesdevs/Bottles#1378]
### Tell us the problem or your need

When i was creating my first gaming bottle, it hung up for a some time (something like 10 minutes), and the only message shown was what was already downloaded and "Installing dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable …", there was no way for me to know if the download was taking longer than i expected or if the app was frozen.

### Describe the solution you'd like

Adding some percentage of how much of the current dependency has already been downloaded would be something that would help the user know if they are having problems with their internet or with the app. Something similar to what pacman (the package manager) shows in the command line would be great.

**Comment by glyh** [comment]
Is this implemented? I can't find progress on bottles.

**Comment by axtloss** [comment]
https://github.com/bottlesdevs/Bottles/commit/45dde897a2bb87254227b0364143a1cb12e918c8 This commit closed this issue

**Comment by glyh** [comment]
But I don't see a progress bar..,

**Comment by TheEvilSkeleton** [comment]
Is Bottles up to date on your end?

**Comment by mirkobrombin** [comment]
Progress bars are CLI only. We show a percentage in the GUI.

**Comment by glyh** [comment]
@TheEvilSkeleton 2022.5.28-trento-3, the commit is made before the time stamp, so I suppose it should work. 
@mirkobrombin I got it, thank you.
