### ISSUE TITLE
Fix blog links?

### ISSUE THREAD

**Issue by bayazidbh** [bottlesdevs/Bottles#1379]
For the past few release days now, I've noticed that the blog link was borked.

The latest one, for example, links to https://usebottles.com/blog/release-2022.4.28/ while the correct link should be https://usebottles.com/blog/release.2022.4.28/ with the hyphen should be a dot.

It's usually a one character mistake, is it some sort of link auto-generation issue? I've been noticing this for the past few months, and looks like past links haven't been corrected?

**Comment by mirkobrombin** [comment]
We just switched to the new format. Where do you see the broken one?

**Comment by bayazidbh** [comment]
I saw it in the Releases page here on github, I think it stretches from the latest one to the ones around release 2022.3.14 and up. Sometimes it uses dot correctly, but most of them still use a hyphen in the link.

**Comment by mirkobrombin** [comment]
Just me writing it from scratch :D Thanks for reporting

**Comment by mirkobrombin** [comment]
Fixed. I'll fix the link with next release returning to release-yyyy.mm.dd
