### ISSUE TITLE
[Request]: Have static positions for top right icons

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1381]
### Tell us the problem or your need

In the top right there are 2 icons when outside of a bottle (connected/not connected and the hamburger menu) and there are 2 icons when inside of a bottle (3 dot menu and connected/not connected). Currently the 3 dot menu and hamburger menu either seem to appear on the right and left of the connected/not connected icon or they are swapping spaces.

### Describe the solution you'd like

Ideally the connected/not connected icon would always be on the left side of the hamburger and 3 dot menu when inside and outside of a bottle.

### Other solutions?

n/a

### Additional context and references

n/a

**Comment by mirkobrombin** [comment]
I didn't understand the point 🤔

**Comment by ghtesting2020** [comment]
> I didn't understand the point thinking

Sorry my english is not so good. Here is screenshot. You can see the "not connected" icon moves from the left to the right. For consistency it would be nice if they stayed in the same spot. The 3 dots menu could replace the spot of the hamburger menu when inside of a bottle.
![1](https://user-images.githubusercontent.com/69682350/165821024-9d60a960-5b40-4568-a8be-f94722843a56.png)
![2](https://user-images.githubusercontent.com/69682350/165821033-1c21d69f-eb2c-4de7-95e3-d0c1a6579784.png)

**Comment by mirkobrombin** [comment]
Oh that's because the 3 dots icon refers to a context menu which is additional, so it should not "hit" the other ones
