### ISSUE TITLE
[Bug]: Desktop Entries created for Programs ignore launch options

### ISSUE THREAD

**Issue by jaylittle** [bottlesdevs/Bottles#1383]
### Describe the bug

I discovered today while configuring an older game with Bottles that if I setup a programs entry for the game, apply launch options to it (e.g. gamescope scaling options) and then create a desktop entry... that using the desktop entry to launch the game appears to ignore the launch options. The launch options are only used when I open bottles, go into the bottle, go into the list of programs and launch the program from that list.

### To Reproduce

1. Create a bottle
2. Install some software in it
3. Create a Program Entry within the bottle
4. Set some launch options for the Program entry
5. Create a Desktop Entry for the Program Entry
6. Launch the Program via the Desktop Entry

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-302.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
This was already fixed 1 release ago, was just missing the post-script argument. Try re-creating your desktop entry using 2022.5.2 please.
