### ISSUE TITLE
Saved data doesn't persist after reboot

### ISSUE THREAD

**Issue by nu111** [bottlesdevs/Bottles#1388]
Hi, I have successfully imported wineprefix to bottle: #1209.

It seems that the game I am running (CNC generals Zero Hour) has no persistence.

If I save a game or I change options, they will survive when restarting the game from bottles, but they don't survive to a reboot.

How can I fix this?

**Comment by mirkobrombin** [comment]
Sounds like a permission problem. When using Flatpak you must give it permission to reach external paths, otherwise that will be lost with restart.

**Comment by nu111** [comment]
You are right, my bottle's user dir is somehow full of symlinks pointing to my linux home.
I fixed by removing the symlinks and creating real dirs instead.

**Comment by mirkobrombin** [comment]
Nice! I'll close the issue as there is nothing we can do.
