### ISSUE TITLE
[Bug]: When you use 'browse' from the KDE utilities it doesn't open dolphin

### ISSUE THREAD

**Issue by Dansito** [bottlesdevs/Bottles#1398]
### Describe the bug

When using the 'browse' utility tool in kde, pressing doesn't open dolphin(file manager) but it opens another program in my case(vscode), I guess this has to do with why vscode asks me for gnome-keyring( for github authentication) and somehow associates it as if it were the file manager

### To Reproduce

1)Open bottles
2)Open any existing bottle (in kde)
3)Open the utilities tab and click browse

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-27-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Thanks for reporting! This depends on your system preferences. Bottles uses xdg to start the file manager and we can't fix it.

**Comment by Dansito** [comment]
![image](https://user-images.githubusercontent.com/84112405/166149690-147bacf0-2ef0-4d3f-852b-381de0e27a04.png)


![image](https://user-images.githubusercontent.com/84112405/166149733-16c15c70-70bc-436d-8042-4f3e39c42615.png)

And the applications that I have on my system normally work with dolphin... so what could be happening here?

**Comment by Dansito** [comment]
![image](https://user-images.githubusercontent.com/84112405/166149976-63a8a647-f24b-46e3-8422-65ecd114daee.png)

It's not a problem with portals in kubuntu either, it looks like something with bottles

**Comment by mirkobrombin** [comment]
I mean, it's fully managed by your system:
https://github.com/bottlesdevs/Bottles/blob/bd4c30999b2dffdc630293248a36e94840335fdb/src/backend/utils/manager.py#L72

**Comment by Dansito** [comment]
So why do other flatpak's like telegram correctly detect dolphin and bottles not? it's weird

**Comment by mirkobrombin** [comment]
> So why do other flatpak's like telegram correctly detect dolphin and bottles not? it's weird

I think they uses other methods, we should check at the source

**Comment by Dansito** [comment]
![image](https://user-images.githubusercontent.com/84112405/166150904-19860a40-4ef7-4436-b851-86a68afe7d71.png)
Fixed, but it would be nice if another way to detect it will be implemented, I leave the image in case there is another kubuntu user who installs vscode and gets the same problem, this is the way to solve it
