### ISSUE TITLE
[Request] Support uppercase extensions [.EXE/.MSI/.BAT]

### ISSUE THREAD

**Issue by LeandroStanger** [bottlesdevs/Bottles#140]
**Is your feature request related to a problem? Please describe.**
Bottles doesn't see executables with uppercase extensions.

**Describe the solution you'd like**
Supporto both lowercase/uppercase.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mirkobrombin** [comment]
Ref https://github.com/bottlesdevs/libwine/issues/2

**Comment by mirkobrombin** [comment]
Ping https://github.com/bottlesdevs/LibraryWine/issues/1
