### ISSUE TITLE
[Bug]: DLL overrides from dialog don't work

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#1402]
### Describe the bug

There's the possibility to set dll overrides for a bottle but they won't get assigned when starting a program.

### To Reproduce

1. Find a configuration of bottle and executable which makes it easy to spot if a dll-override is assigned.
  For my testing I've used an existing Valve Proton prefix which already includes dxvk with a game that's clearly running better with dxvk turned on - the dxvk hud can help here too.
  It'll get a 50 FPS boost when using dxvk for which it needs the following overrides: `d3d11=n;d3d10core=n;d3d9=n;dxgi=n`.
1. Spot overrides not working:
    1. Set up dll-overrides in the bottles options menu. See figure 1.
    2. Start the program and notice that the overrides didn't get applied:
        * The performance is bad,
        * The dxvk hud doesn't show up.
4. Test the other way around to pinpoint that the override system is indeed the problem:
    1. Set up a new environment variable named `WINEDLLOVERRIDES` and assign the same dll overrides. See figure 2.
    2. Start the program and notice that the overrides get applied:
        * The performance is way better.
        * The dxvk hud shows up. 
1. Conclude that dll overrides work as an environment variable and don't work as a dedicated dll override which should be a bug.

<details>
<summary>Figure 1</summary>

![grafik](https://user-images.githubusercontent.com/1408843/166158336-939fedd8-abcf-4683-abcf-c93902090a25.png)

</details>

<details>
<summary>Figure 2</summary>

![grafik](https://user-images.githubusercontent.com/1408843/166158575-1e9430b7-4e2e-43b6-ad52-33d62402d59d.png)

</details>

### Package

AUR ("bottles" package)

### Distribution

Arch linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

The tested overrides aren't listed in the library tab of the internal wine configuration which could interfere with the testing.

Trying to enable dxvk in this pre-existing bottle aborts with an error because the relevant files are set to read only by proton. When disabling dxvk it deletes some registry entries which don't exist because the initial installation failed so those registry entries couldn't interfere with my testing.
~~~
ERROR Error while running async job: <bound method Manager.install_dll_component of <bottles.backend.managers.manager.Manager object at 0x7f5687a99e40>>
	Exception: [Errno 13] Keine Berechtigung: '/mnt/games/prefixes/test/drive_c/windows//syswow64/d3d10.dll'
 
  File "/usr/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1486, in install_dll_component
    manager.install(config, overrides_only, exclude)
  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 69, in install
    self.__install_dll(config, path, dll, False, overrides_only)
  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 116, in __install_dll
    shutil.copyfile(source, target)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
~~~

**Comment by mirkobrombin** [comment]
Steam proton prefixes is an experimental feature and not all preferences are yet implemented

**Comment by Lucki** [comment]
Well, then sry.

**Comment by mirkobrombin** [comment]
No problem, you are welcome :D I'll implement all the missing prefs soon
