### ISSUE TITLE
[Bug]: 32 bit visual basic app (possibly all?) broken in Flatpak on Fedora 35

### ISSUE THREAD

**Issue by MarSik** [bottlesdevs/Bottles#1405]
### Describe the bug

There seems to be no way to run old 32 bit only apps at the moment, at least in the Flatpak version of Bottles.

Take for example the zip version of 4nec2 (antenna simulator): https://www.qsl.net/4nec2/ (requires vb6run)

In 64 bit prefix with caffe-7.2, it prints this into the console:

```
/lib/ld-linux.so.2: could not open
ShellExecuteEx failed: Internal Error
```

Trying to create a 32 bit prefix creates one, but the prefix directory is actually empty except the bottles.yaml and sometimes (depends on runner) the windows dir. No program files, nothing.. obviously it does not work at all.

### To Reproduce

1. Create 64 bit prefix using the Application profile
2. Copy in the directory from 4nec2 zip
3. Run executable with terminal
4. See the failure

or

1. Create 32 bit prefix using Custom profile
2. Check the generated bottle folder
3. Nothing works (not even regedit)

### Package

Flatpak from Flathub

### Distribution

Fedora 35

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.16.20-200.fc35.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
I'm able to make it works in a 64bit bottle with vb6run

![image](https://user-images.githubusercontent.com/9479903/167261976-dd5cd87b-dcbd-457e-90af-abbc549afe54.png)

This sounds like a broken template. Please remove `~/.var/app/com.usebottles.bottles/data/bottles/templates` then start Bottles again and test in a new bottle. If using the Custom environment, be sure to use Caffe 7.7 (wine 7.5, 7.6 have some problems with some dependencies). If the problem persist, please try in X.org too.

Closing as I'm not able to replicate, feel free to add more comments.

**Comment by rebukaaa** [comment]
Re-installing bottles completely fixed the issue for me.

**Comment by CrazyDiamond-75** [comment]
Re-installing bottles from scratch fixed the issue for me.
