### ISSUE TITLE
[Bug]: wine64 cmd : Failed to execve: No such file or directory

### ISSUE THREAD

**Issue by jawadalkassim** [bottlesdevs/Bottles#1406]
### Describe the bug

I'm getting this error when trying to open command line from inside bottles:
```
Failed to execute child process “bash -c /home/jawad/.local/share/bottles/runners/caffe-7.7/bin/wine64 cmd”: Failed to execve: No such file or directory 
```
![image](https://user-images.githubusercontent.com/48631694/166234254-d966773b-0e47-404a-a560-32a7e84f1b4e.png)

also apps inside the bottles have no internet access maybe because the first issue

Tried removing `bash -c` and execute the command it's working
![image](https://user-images.githubusercontent.com/48631694/166234654-fba075f4-ebbe-4be7-abdd-3eff9325e687.png)
here when it's working I've tried opening wine internet explorer and the internet is working. (Only from here not in Bottles)

i switched from fish shell to bash and the issue is still happening

### To Reproduce

1: Open Bottles
2: open any created bottle
3 press Command Line

### Package

Other, unofficial package

### Distribution

Fedora 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-302.fc36.x86_64
Distro:
    Name: Fedora Linux
    Version: '36'
Tools:
    cabextract: true
    p7zip: true
    patool: false
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Because I'm Having Issues with Flatpak version I'm using Fedora package.
Bottles Version:  2022.3.28-trento

is this error related to the unofficial package should i use App Image version?

**Comment by alissonlauffer** [comment]
Apparently this has been introduced in 33351405b9a60cad7ef09f1de89d9f42add4b8e4, since gnome-terminal uses `gnome-terminal -- sh -c "command args"` instead of `gnome-terminal -- 'sh -c "command args"'`.

**Comment by mirkobrombin** [comment]
> Apparently this has been introduced in [3335140](https://github.com/bottlesdevs/Bottles/commit/33351405b9a60cad7ef09f1de89d9f42add4b8e4), since gnome-terminal uses `gnome-terminal -- sh -c "command args"` instead of `gnome-terminal -- 'sh -c "command args"'`.

Thanks for the tip, just tested and you are right

**Comment by mohamadali-halwani** [comment]
Greetings,
Sorry for reopening this thread
I'm having the same issue using archlinux and gnome on xorg. How did you solve it?
I've also found these errors when I opened bottles from my terminal
```

00d0:err:ole:start_rpcss Failed to open service manager
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0024:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0024:err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-9
0024:err:unwind:RtlUnwindEx invalid frame 0000000000120008 (0000000000022000-0000000000120000)
```
