### ISSUE TITLE
[BUG] Installed Programs won't appear on the bottle page

### ISSUE THREAD

**Issue by czrcbl** [bottlesdevs/Bottles#141]
Installed applications in a bottle won't show up on the interface. The only way to start the installed applications (Office 2007) is to go on run exe and navigate to the program executable inside the wine prefix.

**Installation**
flatpak

**To Reproduce**
1. Install Office 2007
2. No icons to start the programs

**Expected behavior**
The installed programs would show up on the interface.

**Desktop (please complete the following information):**
 - OS: POP-OS
 - Version 20.10

**Comment by mirkobrombin** [comment]
Are you sure the installation was successful?
Bottles looks for the .lnk files in the common Windows directories, if it does not appear it means that the icon was not created by the installer or that it is located in a directory not recognized by Bottles.

**Comment by czrcbl** [comment]
The installer reported that the installation as successful. This could be caused by a nonenglish program installer? Where are the .lnk files supposed to be located? So I can check and try to fix it manually?

**Comment by mirkobrombin** [comment]
```
drive_c/users/*/Start Menu/Programs/**/*.lnk
drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/**/*.lnk
```

**Comment by czrcbl** [comment]
This is strange, the files are missing on both locations.

**Comment by czrcbl** [comment]
Also, I have reinstalled twice and repaired the installation once. Have already reinstalled and purged bottles data folders.
Do you know a way of creating the shortcuts manually on linux?

**Comment by mirkobrombin** [comment]
> Also, I have reinstalled twice and repaired the installation once. Have already reinstalled and purged bottles data folders.
> Do you know a way of creating the shortcuts manually on linux?

This function is not yet present: https://github.com/bottlesdevs/Bottles/issues/115

**Comment by czrcbl** [comment]
Thank you for the help.I really looked all around the disk C folder and searched on the file browser but I couldn't find the shortcuts.

**Comment by mirkobrombin** [comment]
This appears to be an installer problem. In bottles v4 you can create custom links to executables.

**Comment by czrcbl** [comment]
How can I test bottles v4?

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/Bottles/issues/133
You can't, it is in early development.

**Comment by alemoh1234** [comment]
I just installed a program, the program on installation put it's .lnk in the desktop and bottles can't seem to detect it.
It's also a very frustrating experience because I can't add it manually.
Is there anyway to solve this?

**Comment by alemoh1234** [comment]
I realized the installer actually put the .lnk file in one of the locations mentioned above, but bottles can't detect it.
`/home/*/.var/app/com.usebottles.bottles/data/bottles/bottles/superstar-chefs/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Superstar Chefs/Superstar Chefs.lnk`
