### ISSUE TITLE
[Bug]: vkBasalt option available when not installed

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1410]
### Describe the bug

The vkBasalt option in Bottles can be toggled on or off whether it is not installed.

### To Reproduce

1. Open a bottle
2. Press Preferences
3. Enable or disable vkBasalt

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.3-302.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

`flatpak list --all` doesn't show vkBasalt:
```
TheEvilSkeleton@TheMainDesktop ~> flatpak list --all | grep -i vkbasalt
TheEvilSkeleton@TheMainDesktop ~>
```
The option can still be toggled on or off:
![image](https://user-images.githubusercontent.com/50847364/166344454-4d00eca6-abd4-4b8e-8ea1-0943ddac6fd9.png)

**Comment by mirkobrombin** [comment]
I couldn't find a way to verify that vkbasalt is installed (apart from using all package managers because it's a bad approach)
