### ISSUE TITLE
[Bug]: Settings schema 'com.usebottles.bottles' does not contain a key named 'dark-theme' 

### ISSUE THREAD

**Issue by quasigod-io** [bottlesdevs/Bottles#1411]
### Describe the bug

When launching Bottles it crashes instantly. Running through the terminal gives this output as it crashes.

### To Reproduce

Simply launch Bottles from the terminal on my system.

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
I cannot do this as I can't launch Bottles.
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

This happens with the bottles and bottles-git packages in the AUR. I checked using dconf editor and that key indeed does not exist, I'm just not sure how to fix that. 
The bottles Flatpak will launch, but I would greatly prefer to use bottles-git

**Comment by mirkobrombin** [comment]
FYI: bottles-git is unofficial. 

This is not a Bottles related problem but a broken schema in your system. Uninstall bottles and manually remove schemas if keep existing, then reinstall bottles. 

Maybe duplicate: https://github.com/bottlesdevs/Bottles/issues/964

**Comment by quasigod-io** [comment]
Thanks for the FYI, I didn't realize. Do you happen to have any idea how I could remove that schema? I've now followed every method I can find online and scoured my system to remove any related files, and it's still there. Reinstalling doesn't overwrite it, either.

**Comment by mirkobrombin** [comment]
Honestly idk, I don't recommend to remove those files.

**Comment by quasigod-io** [comment]
Okay, after learning more than I wanted to about glib schemas, I checked all my XDG_DATA_DIRS and found that at some point an incorrect Bottle's schema had been compiled to /usr/local/share/glib-2.0/schemas, and that was overwriting the correct Bottle's schema in /usr/share/glib-2.0/schemas. It was the only schema in the binary, and otherwise the directory was empty. I'm guessing the bottles-git package did this, since it's unofficial.

After deleting the incorrect schema and running 'glib-compile-schemas /usr/share/glib-2.0/schemas', Bottles is working as expected.
