### ISSUE TITLE
[Bug]: No text on WINE apps under Gnome 42

### ISSUE THREAD

**Issue by Microwave-WYB** [bottlesdevs/Bottles#1412]
### Describe the bug

Application has no text under Gnome 42 and Fedora 36. 

### To Reproduce

1. Run any windows application, the window can be rendered but texts are missing

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-300.fc36.x86_64
Distro:
    Name: Fedora Linux
    Version: '36'
Tools:
    cabextract: true
    p7zip: false
    patool: false
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

![image](https://user-images.githubusercontent.com/68882116/166406185-1dd70f3e-a279-4838-a858-1681b8d4169c.png)

**Comment by mirkobrombin** [comment]
Can’t replicate. Sound more like a wine bug related then bottles. Which lang is using your system?

**Comment by Microwave-WYB** [comment]
> Can’t replicate. Sound more like a wine bug related then bottles. Which lang is using your system?

English. The system is Fedora 36 Beta and was fresh installed 2 days ago.

**Comment by Microwave-WYB** [comment]
I though this could be a font issue, so I copied some fonts into the windows font dir, it didn't help

**Comment by mirkobrombin** [comment]
Fonts are not going to be properly installed in your bottles due to some missing tools. Note:
```
    p7zip: false
    patool: false
```

Please ask to the fedora package maintainer to provide them or install on your own.

**Comment by Microwave-WYB** [comment]
I installed `p7zip` and `patool`, but the text is still missing

**Comment by mirkobrombin** [comment]
p7zip and patool are just missing dependencies but has nothing to do with this problem. My thought is that as those are missing, maybe other are too

**Comment by fastrizwaan** [comment]
install `allfonts` in `Dependencies`

**Comment by natrist** [comment]
@Microwave-WYB Make sure you have riched20 and msftedit dependencies installed, as they are used for rendering text in windowed applications under Windows.

**Comment by mirkobrombin** [comment]
Closing as not replicable. Also it may be fixed by Soda runner.
