### ISSUE TITLE
[Bug]: Child name 'page_about' not found in GtkStack

### ISSUE THREAD

**Issue by Jeglerjeg** [bottlesdevs/Bottles#1416]
### Describe the bug

On a first-time install of bottles, the "Next" button on the welcome panel does nothing, and throws the error Gtk-WARNING **: 16:20:12.035: Child name 'page_about' not found in GtkStack.

### To Reproduce

1. Install bottles
2. Click on "Next" on the welcome panel

### Package

AUR ("bottles" package)

### Distribution

EndeavourOS

### Health Check

```shell
Not possible to do as the welcome panel blocks interaction with the rest of Bottles.
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Pushing an hotfix, thanks for reporting
