### ISSUE TITLE
[Bug]: Incorrect command line argument handling with gamescope enabled

### ISSUE THREAD

**Issue by jarrard** [bottlesdevs/Bottles#1418]
### Describe the bug

Example when adding launch arguments with gamescope.
%command% ARG
Result
/usr/bin/gamescope: unrecognized option '--use-gl=osmesa'

### To Reproduce

1. enabled gamescope
2. launch options

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-xanmod1-1
Distro:
    Name: EndeavourOS
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by jarrard** [comment]
Result:
No way to use command line arguments for programs while gamescope is enabled as it interrupts them for gamescope and not the program.

**Comment by jarrard** [comment]
Command Line option in details and utilities also just uses the system wine version and not the bottles configured one... .
Starting to loose faith in using Bottles :(

**Comment by jarrard** [comment]
This command works however 
gamescope -f -- %command% -use-gl=osmesa

It seems Bottles is doing the below which is wrong and disobey syntax rules!
gamescope -f -- -use-gl=osmesa %command%

**Comment by mirkobrombin** [comment]
Gamescope is disabled by default when launching something via terminal, as terminal commands uses the minimal WineEnv instead of the full one.

> This command works however gamescope -f -- %command% -use-gl=osmesa
> 
> It seems Bottles is doing the below which is wrong and disobey syntax rules! gamescope -f -- -use-gl=osmesa %command%

Do you have some refs about this?

**Comment by jarrard** [comment]
> This sounds weird. Just tested and it works as expected. Check if you have sys-wine set as runner.

It should run off whatever is set inside the bottle/container not whats available elsewhere. 

> Do you have some refs about this?

What do you mean refs? its gamescope github syntax info stuff. It's just clear that Bottles is passing the Launch Arguments to gamescope and not the %command% itself.
