### ISSUE TITLE
Can't find the "Remove from programs option"

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/Bottles#1422]
I would to remove completely a manually added program from the list but the option "Remove from programs" stated in documentation here: <https://docs.usebottles.com/bottles/programs> 

.. is not present in my up-to-date AUR version:

![Screenshot from 2022-05-05 13-40-48](https://user-images.githubusercontent.com/910115/166916179-4722613e-db6c-42f6-ac26-dcaf533ac516.png)

I can just "hide" the program. Is it a deprecated feature ?,

**Comment by mirkobrombin** [comment]
You can hide programs. If you want to remove it, just edit your bottle.yml and remove the whole entry.
