### ISSUE TITLE
[Bug]: Post-run script is launched only one run after set it

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/Bottles#1423]
### Describe the bug

Seems the "Post-run script" value is not persisted inside the bottle runtime:

If you run a program just after setting a post-run script in launch options menu, the script is launched correctly on exit. But if you run the command again, this time the script is not executed on exit. 

It is not executed even if bottles is restarted and command launched again.

The "script" attribute is correctly persisted in the bottles.yml though.

Related:
The script path is not displayed below the "Post-run script" after you click on save and you re-open the "launch options" menu
("choose a script which should be executed after run" is displayed instead, like if there is no script set). 

### To Reproduce

1. Go to Programs
2. Click on "change launch options" of a program
3. Go to advanced options
4. Set a post-run script
5. Launch the program
6. Exit the program
7. You'll see here that the script is run correctly
8. Launch the program again
9. Exit the program
10. This time you'll see the script is not executed. 
11. You can start again and again now.. it will never be executed (even if you restart bottles)
12. Go to "change launch options" > "advanced options"
13. You'll see that the script is not displayed under "Post-run script" but boilerplate message "Choose a script..."
14. Open bottles.yml -> you'll see that the script attribute is correctly set though...

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
There is a bug in GUI and the script path is not showed when you came to change it. Btw just tested and the post-run script is working fine. I've made a sh script:

```sh
#!/bin/sh
notify-send "Hey dude!"
```

which simply send a on-screen notification, then set it as executable `chmod +x myscript.sh`, picked from Bottles and launched the program. It always show the notification when the program exit. I've also tried after a restart and it's still working.

**Comment by TiBeN** [comment]
OK, so i think the issue is with the use of "&&" to concatenate post_script with command in this line:

https://github.com/bottlesdevs/Bottles/blob/6ab68f2ce35494538f1bc7551a08f3891ebde8bd/src/backend/wine/winecommand.py#L410

In bash, if previous command does not exit with 0 code, the command after is not executed. Make use of ";" instead of "&&" could solve the issue (depending on the desired behavior, Lutris does executes the exit script even if wine crash).

**Comment by mirkobrombin** [comment]
It was my intention to prevent the script from running if the wine command failed, as I don't know what the purpose of the script is.

**Comment by TiBeN** [comment]
To my point of view, not executing the command at all is more restrictive than letting the user determine what to do in is script. 
If needed, there are common shell tricks to determine if wine crashed, like using "$?" to get the exit status of the last command. 
Maybe the exit status can be passed through env var as well or define a UI switch to ask the user to execute or not if wine program crashes....

In my specific use case, i use pre and post script to mount and unmount an iso image required by the program. Whatever if the Wine program crashes or exits properly i want the iso image to be unmounted to free the kernel device when the program stops.

That's just my opinion, as said i found a workaround so for my use case it is not critical :)

**Comment by mirkobrombin** [comment]
I'll evaluate this. Thanks for reporting
