### ISSUE TITLE
[Bug]: Cannot play any game with DXVK enabled

### ISSUE THREAD

**Issue by U-ENERGY** [bottlesdevs/Bottles#1425]
### Describe the bug

Since this version of flathub package, i cannot play any game with DXVK enabled.

    Commit: f444f38123594adb9c204f6f5e5157edab8b166628c1c55aa3c5f2353073fd32
    Subject: update to org.gnome.Platform 42 (acddeae2)
    Date: 2022-03-27 21:04:42 +0000

Logs from terminal:
```
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
info:  Game: NFS13.exe
info:  DXVK: v1.10.1-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
err:   DxvkInstance: Failed to create instance
info:  Game: NFS13.exe
info:  DXVK: v1.10.1-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
err:   DxvkInstance: Failed to create instance
wine: Unhandled page fault on read access to 00000000 at address 0041409C (thread 00e8), starting debugger...
Can't attach process 00e4: error 5
gamemodeauto: 
```

At the moment I have bottles to be downgraded to this version, if I want my games to start.

    Commit: d458ecaed6044a065602c299522b84a80f041453709f9bd8d7d3c3ee9adaec5d
    Subject: 2022.3.14-trento-3 (25f879af)
    Date: 2022-03-14 17:11:22 +0000

There are no any differences if I'll switch runner or something else.

### To Reproduce

1. Download the latest Bottles version from flathub
2. Create a bottle with DXVK enabled
3. Install any DirectX11 game
4. Try to start it. It fails for me.

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
The only change we did is using the Start WineProgram instead the Executor for Windows path executables. Can you try manually adding the executable to the programs list and launch from it?

**Comment by U-ENERGY** [comment]
> Can you try manually adding the executable to the programs list and launch from it?

The same result.

According to logs, I think it unable to load vulkan driver properly. But if I go to version from 2022-03-14 there are no problems.

**Comment by mirkobrombin** [comment]
Reading your health check:
```
icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
```
Bottles found and loads vulkan.

I've tested all releases since 2022.3.14 and all works as expected (despite other bugs of course). Can you try the latest? Also do a `flatpak update`. Maybe try 2022.4.14 and 2022.4.28.

**Comment by U-ENERGY** [comment]
> Can you try the latest? Also do a flatpak update. Maybe try 2022.4.14 and 2022.4.28. 

I do flatpak update once a day. These two versions and the latest one don't work for me, I still need to disable dxvk in order to start my games.
I really need dxvk. So my workaround is either downgrade bottles or use wine package itself instead.

**Comment by U-ENERGY** [comment]
> What games have you tried?

Need For Speed: Most Wanted 2012
Life Is Strange
Life Is Strange: Before the storm

[bottle.yml.txt](https://github.com/bottlesdevs/Bottles/files/8639899/bottle.yml.txt)

**Comment by mirkobrombin** [comment]
I see nothing strange (apart from dxvk-async with which I have never been able to get anything to work)

**Comment by mirkobrombin** [comment]
Closing as no response.
