### ISSUE TITLE
[Request]: Checkboxes to select all dependencies for install

### ISSUE THREAD

**Issue by maxpowerstl** [bottlesdevs/Bottles#1428]
### Tell us the problem or your need

Having to click download, wait for the download, wait for the install for each and every dependency is a nightmare.  If I have several dependencies I need to install I can take hours.

### Describe the solution you'd like

Having the ability to select multiple dependencies for installation and then clicking a single button would allow the user to select these and then come back later without having to interact for each dependency.

### Other solutions?

winetricks

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/167151962-da6f3dba-e421-455b-b9cf-e7f762d73b59.png)

click the checkmark:
![image](https://user-images.githubusercontent.com/9479903/167152043-9e761ac4-fa0e-4718-923d-0edca0399678.png)

select the needed dependencies:
![image](https://user-images.githubusercontent.com/9479903/167152112-380db80b-e6b9-4b75-9eb7-26835242efc9.png)

click on "Install selected":
![image](https://user-images.githubusercontent.com/9479903/167152172-035f1132-a825-4fcb-8d13-e5e0062c5396.png)
