### ISSUE TITLE
UI Refresh Follow-up

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#143]
We have shipped the UI Refresh (#77) in v3, but there are quite a few cut corners and things that could be polished more. This is a meta-issue compiling them.

### Need improvements

- [x] Weird language in initial state
- [x] Initial state has no suggested actions ([mockup](https://www.figma.com/file/2o1rKcFToABvzJFcxyy2v3/Bottles-Refresh?node-id=199%3A608))
- [x] Initial state should use HdyStatusPage for sake of consistency
- [x] Weird language in onboarding
- [x] Download icon should be hidden when there are no downloads
- [x] "Run Executable" button in bottle view is oval ([screenshot](https://user-images.githubusercontent.com/27908024/125466143-bcec9b7f-c9d0-4e91-819c-414c55beba67.png))
- [x] "Create Bottle" dialog doesn't have animations
- [x] "Create Bottle" should have descr
- [x] Adaptive view switcher appears in the bottle view, even when it fits in the header bar ([screenshot](https://user-images.githubusercontent.com/27908024/109408379-ad673700-79bb-11eb-8144-9dd904697ffb.png))
- [ ] "Programs" should be the second tab in the bottle view
- [x] "Programs" title appears in the bottle view, even if there are no programs
- [x] Program view has no blank state (ideally would use HdyStatusPage too) 

Since a lot of them seem like low-hanging fruit and are not critical, I'd encourage new contributors to try to solve these issues and submit pull requests.

-------------------
> The following lines are added by @mirkobrombin 

### Need UI
- [x] onboard #211 
- [x] task manager (should be part of the bottle page)
  Thanks to [libwine](https://github.com/bottlesdevs/libwine) we can now manage wine processes. For now we can show its name (process.exe), the parent (if present) and kill the process (or processes if it is parent).
- [x] https://github.com/bottlesdevs/Bottles/issues/274
- [x] Dependencies/Installers view need a search bar

**Comment by mirkobrombin** [comment]
There are some big limits with the current project. Any changes outside the Glade files will be lost with v4.Some of the tasks in this list can be done in v3 but others will have to wait for v4 with the new code base and GTK4.

**Comment by AdrianVovk** [comment]
In the "Create Bottle" dialog, I would also show the description of each of the modes (gaming/software/custom) at all times so the user won't need to click around to figure out what each option means

**Comment by mirkobrombin** [comment]
-Weird language in initial state 
  How can be improved?
- Initial state has no suggested actions 
  Importing bottles is allowed but not recommended, I will only add the "Create a new bottle" button
- HdyStatusPage
  This widget doesn't seem to be available in Glade with libhandy1, which version of the library do you use?

**Comment by jannuary** [comment]
> - Weird language in initial state 
> How can be improved?
> 
> - Initial state has no suggested actions 
> Importing bottles is allowed but not recommended, I will only add the "Create a new bottle" button
> 
> - HdyStatusPage
> This widget doesn't seem to be available in Glade with libhandy1, which version of the library do you use?

For initial state I'd use "Start by creating a bottle".

As for HdyStatusPage, it was added in 1.1.90, though it's probably not packaged yet

**Comment by mirkobrombin** [comment]
Now that libhandy is offered in Ubuntu 21.04 and Fedora 34 you might want to consider migrating the missing widgets. For example by implementing the HdyStatusPage instead of using ours.

This decision could lead to the loss of backward compatibility with older distributions like Ubuntu 20.04, Fedora 33, elementary 5 (and the future 6 as it is based on Ubuntu 20.04, although it supports flatpak so it remains accessible) and others.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/119447756-a5a3fe00-bd30-11eb-9d10-bcb2a7c39a75.png)
Starting with Bottles v4 we will support our installers. Being a community driven project, I expect significant growth, this means that it will no longer be possible to list all the installers in a simple view. I think there will be a need for a search field. As this is an on-bottle installation system, the search should be done via the bottle details tab.

At the moment it is not possible to place a search in the headerbar as it is already filled by the switcher for the bottle stack.

**Comment by alvarlagerlof** [comment]
I think it could simply be below the toolbar, always visible

**Comment by mirkobrombin** [comment]
> I think it could simply be below the toolbar, always visible

![image](https://user-images.githubusercontent.com/9479903/119497205-96d73e80-bd64-11eb-9ed5-163fdcdcd27b.png)

**Comment by jannuary** [comment]
> The standard pattern for search in GNOME utilizes a search bar which **slides down from beneath the header bar**. In primary windows, the search bar is typically hidden until it is activated by the user. There are three common ways to activate search in this context:
> 
>     Typing, even when the search field is not focused (this is called “type to search”).
> 
>     Ctrl+F: the keyboard shortcut for search.
> 
>     **The search button in the header bar, which should toggle.**
- [Search - GNOME User Interface Guidelines](https://teams.pages.gitlab.gnome.org/Design/hig-www/nav/search.html)

**Comment by jannuary** [comment]
In addition to placing a loupe button, we should probably redesign the bottle view in a fashion that does away with the view switcher and uses an alternative navigation method, although I am bit too busy right now to realize that.

**Comment by alvarlagerlof** [comment]
> > I think it could simply be below the toolbar, always visible
> 
> ![image](https://user-images.githubusercontent.com/9479903/119497205-96d73e80-bd64-11eb-9ed5-163fdcdcd27b.png)
> 

This is what I imagined due too the lack of space.

**Comment by alvarlagerlof** [comment]
> In addition to placing a loupe button, we should probably redesign the bottle view in a fashion that does away with the view switcher and uses an alternative navigation method, although I am bit too busy right now to realize that.

What other options are there? A sidebar?
