### ISSUE TITLE
[Bug]: hover popups in header bar menu show in the wrong place

### ISSUE THREAD

**Issue by Flrian** [bottlesdevs/Bottles#1430]
### Describe the bug

When hovering over a menu entry with the mouse cursor the popup shows on the left side of the program instead of next to the menu entry itself.

![Screenshot from 2022-05-06 18-41-52](https://user-images.githubusercontent.com/4444593/167177140-0497fbb2-06c2-4312-b971-0c15f910aa0c.png)

![Screenshot from 2022-05-06 18-42-10](https://user-images.githubusercontent.com/4444593/167177049-e9cd3d0f-3962-4233-94d7-52b0283836ee.png)

I would expect the popup to be next to the menu entry I'm hovering over itself, right?

Btw I also just noticed, if you look at the 2nd screenshot the popup when over "Show/hide hidden programs" features the wrong text, it uses the text for the documentation about dependencies.

### To Reproduce

1. Go to a bottle 
2. Click on either Dependencies, Programs, Versioning or Installers
3. Open the 3 dot/kebab menu
4. Hover over a menu entry

### Package

Other, unofficial package

### Distribution

openSUSE Tumbleweed

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.4-1-default
Distro:
    Name: n/a
    Version: opensuse
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

The same happens for me with the flatpak and in a Fedora VM too.

**Comment by mirkobrombin** [comment]
I'm not able to replicate
![image](https://user-images.githubusercontent.com/9479903/167211950-363f673b-c8a9-4a10-8003-a3ea1739989c.png)

**Comment by Flrian** [comment]
I just tested a bit further and it seems to only happen when Bottles runs via Wayland. If I disable X11 on Flatseal it is bugged every time and if I disable Wayland it works as it should.

**Comment by mirkobrombin** [comment]
> I just tested a bit further and it seems to only happen when Bottles runs via Wayland. If I disable X11 on Flatseal it is bugged every time and if I disable Wayland it works as it should.

Wayland is magic sometimes
