### ISSUE TITLE
[Bug]: Launch options are ignored when using a windows path

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#1434]
### Describe the bug

If the `path` of an external program is a windows path launch options are ignored.

### To Reproduce

1. Create a new clean bottle.
2. Close bottles and insert the following test values in the `bottle.yml`:
    ~~~ yml
    External_Programs:
        test_unix:
            arguments: notify-send "test" && %command%
            executable: test.exe
            name: Test Unix
            path: /test/path/test.exe
        test_win:
            arguments: notify-send "test" && %command%
            executable: test.exe
            name: Test Win
            path: C:\test\path\test.exe
    ~~~
1. Start bottles, switch to the bottle and try to start the examples.
2. The Unix example spawns a new test notification while the windows example doesn't.

### Package

AUR ("bottles" package)

### Distribution

Arch linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs:
    LOCAL_INSTALLERS: /home/lucki/git_clones/programs
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Stumbled across this while testing installers. The path there [gets automatically resolved](https://maintainers.usebottles.com/installers/structure/#title1) to a windows path.

Maybe here's the reason why the behavior is different:
https://github.com/bottlesdevs/Bottles/blob/8050f829c3fcda8975505f9d84827a00dd5e101f/src/backend/wine/executor.py#L150-L153

**Comment by mirkobrombin** [comment]
Thanks for reporting. This was fixed by https://github.com/bottlesdevs/Bottles/commit/8050f829c3fcda8975505f9d84827a00dd5e101f

Will be distributed with 2022.5.14.
