### ISSUE TITLE
[Request]: Automatic refresh of Programs list after installing new program

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1436]
### Tell us the problem or your need

When you install programs using "run as executable" from Bottles they are not visible in programs list. I always used to just make a custom path and then it detected the whole folder, but one time I accidentally closed Bottles and to my surprise it automatically detected newly installed program and showed it on the list without me doing anything.

### Describe the solution you'd like

Is it possible to make Bottles refresh the programs list after installing software or games? Maybe when Bottles detects the installer stopped running it could check the installed programs for any changes.

**Comment by pietrodicaprio** [comment]
Request accepted, going to be available in next release.
