### ISSUE TITLE
[Question] Does Bottles v3 support creating win32 (x86) bottles?

### ISSUE THREAD

**Issue by AfoninZ** [bottlesdevs/Bottles#144]
Hello,
I have seen a x86 bottle being created (some old screenshot on the website). Does Bottles v3 still support that functionality? Many of Windows apps still only run on 32-bit prefixes, so that's pretty important I think.

**Comment by mirkobrombin** [comment]
Bottles create 64bit wineprefixes wich support both 32 and 64bit binaries.
