### ISSUE TITLE
[Bug]: Text missing in certain areas for unknown reason

### ISSUE THREAD

**Issue by YaBoiMax** [bottlesdevs/Bottles#1442]
### Describe the bug

The text seems to be missing for certain areas and I haven't found a way to fix it yet

![Screenshot 1 of the problem](https://i.postimg.cc/mkF68xds/Unsaved-Image-1.jpg)

![Screenshot 2 of the problem](https://i.postimg.cc/hGfwf79v/Unsaved-Image-2.jpg)

### To Reproduce

1. Open preferences
2. Navigate to the Runners tab
3. Everything past the Pre-Release toggle will be blank

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-zen1-1-zen
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 479569186816
    Free: 344593043456
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I tried looking up if people ever had this kind of problem with gtk apps but I found nothing that was similiar

**Comment by mirkobrombin** [comment]
Try forcing the Adwaita theme using the env var: `GTK_THEME=Adwaita`

**Comment by YaBoiMax** [comment]
Same result but now in white mode.

![Screenshot of the same problem but in white mode](https://i.postimg.cc/yxLYXbNs/Unsaved-Image-3.jpg)

**Comment by mirkobrombin** [comment]
Unfortunately, this kind of problem is system specific and not easy to reproduce. It is not a Bottles bug and I also rule out a GTK bug. I don't think I can do much, I will wait a few days to see if others have this problem before closing

**Comment by TheEvilSkeleton** [comment]
Can you run Bottles from the terminal and send the logs? Also, could you try to install it as a Flatpak? It might be a missing font issue.

**Comment by YaBoiMax** [comment]
Running it from the terminal gives me these logs when I navigate to the affected menus
```log
(bottles:89869): Handy-WARNING **: 21:52:37.629: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
(21:52:37) INFO Bottles Started! 
(21:52:38) INFO Performing Bottles checks... 
(21:52:38) INFO Dxvks found:
         - dxvk-1.10.1                                                                                            
         - dxvk-1.10                                                                                              
         - dxvk-1.9.4                                                                                             
                                                                                                                  
(21:52:38) INFO Vkd3ds found:
         - vkd3d-proton-2.6                                                                                       
                                                                                                                  
(21:52:38) INFO Nvapis found:
         - dxvk-nvapi-v0.5.3                                                                                      
         - dxvk-nvapi-v0.5.2                                                                                      
                                                                                                                  
(21:52:38) INFO Latencyflexs found:
         - latencyflex-v0.1.0                                                                                     
                                                                                                                  
ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
(21:52:38) INFO Runners found:
         - sys-wine-7.7                                                                                           
         - caffe-7.5
```

Also running the flatpak version fixes the issue.

**Comment by TheEvilSkeleton** [comment]
> `ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

Could you try to open Bottles without `gtk3-nocsd`? Perhaps reinstall every dependency that comes with the `bottles`?

**Comment by YaBoiMax** [comment]
It was gtk3-nocsd. It's an AUR package that disables gtk3 client side decoration. I needed it to fix an issue I had with firefox's borders being kinda borked after applying a kwin patch for rounded corners on my KDE install. After removing gtk3-nocsd, firefox looks the same so I'll just keep it uninstalled. Thanks alot guys!
