### ISSUE TITLE
[Bug]: New bottle creation fails on X.org

### ISSUE THREAD

**Issue by savanton** [bottlesdevs/Bottles#1444]
### Describe the bug

Freshly installed Bottles (2022.5.2-trento-2) on Ubuntu 22.04 LTS failes to create new bottle.

### To Reproduce

Creating a new bottle eventually fails and stuck on the following line:
"Setting Windows version…"

Logs contain the following errors:
wine: Unhandled page fault on execute access to 00007FDE858A9550 at address 00007FDE858A9550 (thread 00b4), starting debugger...
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04 LTS 

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-27-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Thanks for reporting.

This line:
```
002c:err:wineboot:process_run_key Error running cmd L"C:\windows\system32\winemenubuilder.exe -r" (2).
```
can be safely ignored as winemenubuilder is blacklisted in Bottles.

This is more interesting:
```
wine: Unhandled page fault on execute access to 00007FDE858A9550 at address 00007FDE858A9550 (thread 00b4), starting debugger...
```

I'm not able to replicate. This is my output:
```
wineserver: using server-side synchronization.
wine: configuration in L"/var/home/mirko/.var/app/com.usebottles.bottles/data/bottles/bottles/fdfdfdf" has been updated.
```

Which environment did you select?

**Comment by savanton** [comment]
Hi Mirko,
I've tried all and all failed with the same error.

Eventually I switched to Wayland and Bottles seems working now, so it is
probably related to the issue.

пн, 9 мая 2022 г. в 22:46, Mirko Brombin ***@***.***>:

**Comment by mirkobrombin** [comment]
Sounds like a system related problem. Which DE?

**Comment by savanton** [comment]
It is a freshly installed, almost empty, latest Ubuntu distro with Gnome.

пн, 9 мая 2022 г., 23:06 Mirko Brombin ***@***.***>:

**Comment by mirkobrombin** [comment]
Thanks, I'll set up a VM

**Comment by pietrodicaprio** [comment]
Looks like: https://forum.winehq.org/viewtopic.php?t=36177 /
Did you update your Nvidia driver recently?

**Comment by savanton** [comment]
I just installed a fresh Ubuntu yesterday.
Looks like switching to Wayland resolved the issue, so it might be related
to the graphics adapter/drivers.

пн, 9 мая 2022 г., 23:17 Pietro di Caprio ***@***.***>:

**Comment by mirkobrombin** [comment]
Please post output for `glxinfo | grep vendor`

**Comment by savanton** [comment]
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Mesa/X.org

пн, 9 мая 2022 г. в 23:53, Mirko Brombin ***@***.***>:

**Comment by mirkobrombin** [comment]
Seems that you don’t have nvidia drivers installed

**Comment by savanton** [comment]
That is correct.

вт, 10 мая 2022 г. в 00:32, Mirko Brombin ***@***.***>:

**Comment by mirkobrombin** [comment]
Bottles have problems with nouveau as it try to detect the gpu and load the right vulkan layers

**Comment by mirkobrombin** [comment]
Tracking in https://github.com/bottlesdevs/Bottles/issues/1447
