### ISSUE TITLE
[Bug]: Installing to "C:\GoG Games\...." breaks bottles.

### ISSUE THREAD

**Issue by SeanRamey** [bottlesdevs/Bottles#1445]
### Describe the bug

Basically, exactly what the title says. The bottle won't automatically recognize programs installed to "C:\GoG Games\...." and after closing the bottle, it becomes impossible to reopen. See issue #976 where I started replying.

### To Reproduce

1. Create bottle.
2. Get a game installer from GOG, and install it with defaults (which is C:\GoG Games\..)
3. Observe that no programs are detected
4. Quit bottles and restart
5. Try to open previous bottle and observe that it does nothing.

### Package

AUR ("bottles" package)

### Distribution

EndeavorOS

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: EndeavourOS
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Try starting Bottles from terminal and then open the bottle to catch some output

**Comment by lemonzest79** [comment]
I have this with any game like gog games that have spaces in their path, to get them working I remove the spaces

**Comment by pietrodicaprio** [comment]
> I have this with any game like gog games that have spaces in their path, to get them working I remove the spaces

we solved this bug a lot of releases ago... going to understand why it is back, thank you for reporting

**Comment by mirkobrombin** [comment]
Bottles checks for `.lnk` files, I suppose that you don't have those files in your `C:\GoG Games`.

**Comment by lemonzest79** [comment]
My GOG games were from a previous install in Wine, I took the C:\GOG Games\ directory and put in into fresh bottle via browse C:\ Drive, and added the program manually and if the path had spaces it would not run, remove the space and re-add it worked

**Comment by mirkobrombin** [comment]
Fix for spaces will be distributed soon, thanks again for reporting

**Comment by SeanRamey** [comment]
> I have this with any game like gog games that have spaces in their path, to get them working I remove the spaces

But that doesn't fix the issue. The new install directory includes spaces. "Program Files\Close Combat 2". Yet, it works.

**Comment by SeanRamey** [comment]
> Bottles checks for `.lnk` files, I suppose that you don't have those files in your `C:\GoG Games`.

Yes, it does. All GoG games will add .lnk files to the start menu.

**Comment by SeanRamey** [comment]
> Try starting Bottles from terminal and then open the bottle to catch some output

What exactly should I do here? Should I try installing and everything from the terminal?

**Comment by pietrodicaprio** [comment]
The fact that removing and adding again the space "fixes" is due some luck. We have been able to replicate the issue and with the latest build here on GitHub there is a workaround to avoid it to happen and is going to be released in next patch (2022.5.14). Since you are using AUR you could use `bottles-git` package to receive the latest commit and test it. Users using flatpak version are not reporting the issue anyway. You could also give it a try.

About automatically adding GoG games to programs list we'll give a look but it's a different discussion to be handled, if you want, in a different issue.

**Comment by lemonzest79** [comment]
I'm on Flatpak, Fedora 36 and as I said this issue is affecting me

**Comment by mirkobrombin** [comment]
That's weird, Health check says you are not using Flatpak

**Comment by lemonzest79** [comment]
Because that's not my health check :P this is mine

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-xm1.0.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

**Comment by mirkobrombin** [comment]
Hotfix sent, will reach Flathub in ~3h
