### ISSUE TITLE
Launching multiple instances of the same bottle stopped working

### ISSUE THREAD

**Issue by zebhlindqvist** [bottlesdevs/Bottles#1449]
Hi,

I was running Bottles version _2022.3.28-trento-1_ and was frequently launching multiple instances of the same bottle. When I updated Bottles to version _2022.5.2-trento-3_ I noticed that I could no longer launch multiple instances of the same bottle.

I launch my bottles using the command below:
`flatpak run com.usebottles.bottles -e 'C:\Program Files (x86)\xxx\xxx.exe' -b 'XXX'`

When I try to launch the second instance using version _2022.5.2-trento-3_ I get the following message:
`Failed to register: Timeout was reached`

Is there a way to get it working in the latest version or am I just using Bottles in a way that's not intended?

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting.
Please use the [new CLI](https://docs.usebottles.com/advanced/cli#run) as the legacy will be deprecated soon.

Closing to keep the issues list clear, please feel free to add more comments.
