### ISSUE TITLE
Nvidia gamescope ready?

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1453]
Today Nvidia released beta drivers that will allow gamescope to be properly supported. Does Bottles already use these prefixes for AMD and is the same for Nvidia?

"Added support for the ```VK_EXT_external_memory_dma_buf``` and ```VK_EXT_image_drm_format_modifier``` Vulkan extensions. To use this functionality, the nvidia-drm kernel module must be loaded with DRM KMS mode setting enabled. See the DRM KMS section of the README for guidance on enabling mode setting."

https://www.nvidia.com/download/driverResults.aspx/187834/en

**Comment by ghtesting2020** [comment]
@mirkobrombin Hi Mirko i update Nvidia drivers local and flatpak to 515 and i can play games normally without issue. When I try to turn on GameScope this is show:
```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'NVIDIA GeForce GTX 1650'
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateFence failed (VkResult: -1)
Failed to initialize Vulkan
```
i already have gamescope package installed via flatpak
gamescope                         com.valvesoftware.Steam.Utility.gamescope     3.11.28  stable       system
nvidia-515-43-04                  org.freedesktop.Platform.GL.nvidia-515-43-04           1.4          system
nvidia-515-43-04                  ?g.freedesktop.Platform.GL32.nvidia-515-43-04          1.4          system
is this a bug in Bottles? Nvidia supposed to be able to work with gamescope in 515.

**Comment by mirkobrombin** [comment]
I'll test it when 515 hits stable

**Comment by GageBerz** [comment]
@ghtesting2020 [!454](https://github.com/Plagman/gamescope/pull/454) Gamescope needed additional changes for it to work with Nvidia 515 drivers I believe. Gamescope 3.11.31, when that reaches stable, will include those changes.

**Comment by mkaito** [comment]
We all compiled it from git master for those reports.

**Comment by Bananaman** [comment]
Gamescope 3.11.32 (stable) has the NVIDIA support.

Here's a screenshot of gamescope rendering on NVIDIA: https://twitter.com/Plagman2/status/1524480478408953856

You also need NVIDIA driver 515.48.07, released on May 31st, 2022: https://www.nvidia.com/Download/driverResults.aspx/189809/en-us

For Fedora users, that driver is in RPM Fusion's testing since June 1st, so it'll be out soon.

Reference for why that driver is needed (it was some driver bug): https://github.com/Plagman/gamescope/issues/492#issuecomment-1142371068

When it's out, gamescope 3.11.32 will "just work" for NVIDIA users immediately.

**Comment by Bananaman** [comment]
By the way, can someone tell me how Bottles Flatpak uses gamescope?

I looked in `/var/lib/flatpak/app/com.usebottles.bottles/current/active/files` and did a search for "gamescope", but the only file it found is `share/bottles/bottles/dialogs/gamescope.py`. There's no gamescope binary inside Bottles Flatpak.

Does that mean that Bottles somehow uses the host's gamescope binary?
