### ISSUE TITLE
[Request] option to enable gamemode

### ISSUE THREAD

**Issue by soredake** [bottlesdevs/Bottles#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add option to enable [gamemode](https://github.com/FeralInteractive/gamemode).

**Describe alternatives you've considered**

**Additional context**

**Comment by mirkobrombin** [comment]
What are the effective benefits that come with gamemode?

**Comment by soredake** [comment]
> What are the effective benefits that come with gamemode?

![IMG_20210306_092019](https://user-images.githubusercontent.com/5204968/110198740-54851c00-7e5d-11eb-865e-e1cc8c249104.jpg)

**Comment by soredake** [comment]
Mostly i use it for setting 'performance' (i have some games that stutter with ondemand or schedutil) governor for games, and screensaver inhibiting because of bug https://bugs.kde.org/show_bug.cgi?id=328987

**Comment by mirkobrombin** [comment]
Implemented in 2021.7.1-treviso

**Comment by LifeWatcher123** [comment]
How does one enable the `gamemode` feature in the Flatpak version?
