### ISSUE TITLE
Batch file executes fine via GUI but not via CLI

### ISSUE THREAD

**Issue by rkr87** [bottlesdevs/Bottles#1463]
I have a need to launch an .exe with launch arguements via cli. I thought the best way to achieve this would be to create a batch file to execute the .exe with the required arguments and then have bottles open that batch file via cli. However, I can't get it to work via cli no matter what I try, it does however work fine if I execute the batch file via the GUI.

BATCH FILE CONTENTS
"/Path/to/exefile.exe" -arg
::"Z:\path\to\exefile.exe" -arg

NOTE: I've tried using both windows and Linux locations, both work fine via the GUI, neither works via CLI.

KONSOLE COMMAND
Flatpak run com.usebottles.bottles -b GE-Proton -e "/path/to/batfile.bat"

If I run the above pointing directly to the exefile it launches fine (but without my required arg).

Can someone please point me in the right direction? I'm tearing my hair out trying figure out why it won't work.

Thanks.

**Comment by pietrodicaprio** [comment]
Issue executing `.bat` file via CLI solved.
Note that with your batch file you don't run the second file until the first exited. If it is not intended modify the batch file as:
```batch
start "" "/Path/to/exefile.exe" -arg
start "" "/Path/to/anotherexefile.exe" -arg
```

Evaluating if an hotfix will be released. No workaround available at the moment.
@mirkobrombin FYI
