### ISSUE TITLE
[Bug]: Switching runners doesn't unlink home folders

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#1464]
### Describe the bug

When switching from a proton runner (uses `steamuser` as user) to the system runner (uses `$USER` as user) the new userdirs in the prefix link to my home folders (`documents`, …) despite having checked the "Unlink home folder" option on bottle creation.[](url)

### To Reproduce

1. Create a new custom bottle which uses a proton runner and is setting up the prefix with a different user than `$USER`.
2. Make sure the "Unlink home folder" option is activated. (This isn't important for this particular runner as unlinking is the default here)
3. Investigate the prefix and see the only userdir isn't linked to the home folder
4. Go to the bottle settings and change the runner to `sys-wine`.
5. Investigate the prefix again and notice a new user.
6. Looking in the newly created user shows symlinks into `$HOME`

### Package

AUR ("bottles" package)

### Distribution

Arch linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.6-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 116976529408
    Free: 4986773504
RAM:
    MemTotal: 11.6GiB
    MemAvailable: 6.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs:
    LOCAL_INSTALLERS: /home/lucki/git_clones/programs
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

It's still baffling to me that there's no global way to disable this terrible default wine behavior.
Seriously, who want's some savegames between important personal documents?
/rant

Luckily proton and bottles have sane defaults :)

**Comment by mirkobrombin** [comment]
I think there is a problem switch proton <-> wine, just tried from caffe 7.7 to caffe 7.8 and my unlinked folders was preserved

**Comment by mirkobrombin** [comment]
We added a notice when using Proton as runner, alerting this. Re-linking again the userdir is a huge process and can break symlinks added by the user.

Tried our official runners and the problem is not showing up:
Caffe <-> Caffe
Soda <-> Soda
Vaniglia <-> Vaniglia
Caffe <-> Soda
Vaniglia <-> Soda
Vaniglia <-> Caffe
