### ISSUE TITLE
[Bug]: Creating default gaming bottle crashes app

### ISSUE THREAD

**Issue by runouttt** [bottlesdevs/Bottles#1467]
### Describe the bug

I can't create any "Gaming" bottles on Fedora 35/36.  When I try to do so the entire application hangs on:

"Generating bottle configuration…
The Wine config is being updated…"

Meanwhile my desktop will start stuttering, suggesting it is an issue with Nvidia drivers, but I am not sure. Happens on both Silverblue and freshly installed Fedora Workstation. Xorg or Wayland does not seem to make any difference. The app eventually crashes without any errors. Manually creating a custom bottle with Proton-GE runner seems to work, but not for caffe-7.8.

### To Reproduce

1. Install bottles from flathub.org
2. Go through default setup
3. Click + and create default "gaming" bottle
4. App hangs on "Creating bottle..." dialogue and eventually crashes

### Package

Flatpak from Flathub

### Distribution

Fedora 35

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.6-200.fc35.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8384450560
    Free: 8384294912
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Additional context

NVIDIA-SMI 510.60.02

**Comment by runouttt** [comment]
Just tested with caffe-7.7 and that works flawlessly. Deleted caffe-7.8 from runners list, installed 7.7 and then created default gaming bottle.

**Comment by mirkobrombin** [comment]
Thanks for reporting, I'm going to retire 7.8

**Comment by mirkobrombin** [comment]
There is a new Caffe 7.8-1 release under testing (you can install it enabling "Pre-Release" in Bottles preferences)

**Comment by runouttt** [comment]
Unfortunately the result is the same for me with 7.8-1

**Comment by mirkobrombin** [comment]
So I think there is a bug in wine itself
