### ISSUE TITLE
[Bug]: "Add desktop entry" does not work at all

### ISSUE THREAD

**Issue by kemra102** [bottlesdevs/Bottles#1468]
### Describe the bug

The `Add desktopentry` button ALWAYS shows the popup telling you to watch the video about adding additional filesystem permissions. Even after enabling the required permissions the popup still shows. I have ran Bottles via the CLI and there is no error, or even any output at all when clicking this button.

### To Reproduce

1. Use Flatseal to allow Bottles to access relevant path (tried; `xdg-data`, `~/.local/share/applications` & `/home/kemra102/.local/share/applications`). The video shows a path under `/var` but as I understand it that is only relevant to Silverblue.
2. Load Bottle and open the details of a bottle with an application installed into it.
3. Select the triple dot button next to the application you want to have a desktop entry for.
4. Select `Add desktop entry` from the drop down.
5. Get the pop telling you to view the Youtube video.

### Package

Flatpak from Flathub

### Distribution

Fedora 36 (KDE, x86_64) - NOT Silverblue/Kinoite

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.6-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16831901696
    Free: 16831758336
RAM:
    MemTotal: 31.4GiB
    MemAvailable: 26.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by Dansito** [comment]
If is fedora normal try with: /home/youruser/.local/share/applications

If is fedora silverblue try with: /var/home/youruser/.local/share/applications

**Comment by kemra102** [comment]
It's regular Fedora, I tried the path you mentioned (without the typo in my GitHub issue of course).

**Comment by Dansito** [comment]
Just to test, give it permissions to read your home, to see if it works that way, if it doesn't, run bottles from the console and leave the logs here so the developers know what's causing the error.

**Comment by kemra102** [comment]
Giving access to the whole of the home dir via Flatseal still results in the same issue. The entire console output from Bottles starting to clicking "Add desktop entry" is:

```
❯ flatpak run com.usebottles.bottles
(12:56:18) INFO Performing Bottles checks... 
(12:56:18) INFO Dxvks found:
         - dxvk-1.10.1
 
(12:56:18) INFO Vkd3ds found:
         - vkd3d-proton-2.6
 
(12:56:18) INFO Nvapis found:
         - dxvk-nvapi-v0.5.4
 
(12:56:18) INFO Latencyflexs found:
         - latencyflex-v0.1.0
 
(12:56:18) INFO Runners found:
         - sys-wine-7.0
         - caffe-7.8
         - caffe-7.7
 
(12:56:18) INFO Bottles found:
         - WoW
 
(12:56:20) INFO Setting Key: [discrete_gpu] to [True] for bottle: [WoW]… 
(12:56:21) INFO Setting Key: [pulseaudio_latency] to [True] for bottle: [WoW]… 
(12:56:21) INFO No states found for bottle: [WoW] 

(bottles:2): Handy-CRITICAL **: 12:56:21.284: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
```

**Comment by mirkobrombin** [comment]
Just tested and it's working fine, can't replicate.

![image](https://user-images.githubusercontent.com/9479903/168496523-1e5df462-947d-4a87-9fe4-66a65a81e551.png)
![image](https://user-images.githubusercontent.com/9479903/168496528-cb089496-481b-4ad5-86d9-70ae69d28a0c.png)
![image](https://user-images.githubusercontent.com/9479903/168496541-7119747b-385b-4e76-b9c0-885dd3441519.png)

**Comment by kemra102** [comment]
Even after a reboot I still have the same issue (not that I expected it to):

![Screenshot_20220516_160216](https://user-images.githubusercontent.com/1282143/168623720-97fbcaf1-6c81-4621-8b14-0f034e238e37.png)
![Screenshot_20220516_160031](https://user-images.githubusercontent.com/1282143/168623770-80f6634e-3ae2-4583-88ac-4218d8a10e12.png)

This is being done against a test "Gaming" bottle I created just to see if the issue was that Bottle but as you can see it has the same issue.

I also tried removing the Bottle Flatpak then re-installing it, but still got the same problem.

Any advice for debugging this further? I've tried `flatpak run` with both of the `-vv` & `--ostree-verbose` as well as running with `strace` & at the moment I press the `Add desktop entry` button shows no output in the terminal at all.

Further info to clarify:
OS: Fedora 36 (KDE Spin)
Display Server: Wayland
Bottles Version: `2022.5.14-trento`

Out of curiosity I replicated the same software setup on my laptop and got exactly the same error as above (which so far has been my main desktop).

**Comment by mirkobrombin** [comment]
Does that path exists?

**Comment by kemra102** [comment]
Can't believe I didn't think of that, but no it wasn't there by default. Once I created it I can get desktop entries as normal.

**Comment by mirkobrombin** [comment]
Bottles cannot automatically create that path as the control is based on the existence of the path

**Comment by kemra102** [comment]
Shame really, I think there's a few places where the experience can be improved. I'll try to make a few contributions.

**Comment by mirkobrombin** [comment]
This will improve it https://github.com/bottlesdevs/Bottles/issues/1234#issuecomment-1079431485

**Comment by zzzzqwdqdqwfdqwfqc** [comment]
**i fix the error Bottle's can't create a desktop entry**

 when you click on add desktop entry.Bottle create a Desktop entry in this location.   `/home/kali/.var/app/com.usebottles.bottles/data/applications/`

**Comment by zzzzqwdqdqwfdqwfqc** [comment]
> Just tested and it's working fine, can't replicate.
> 
> ![image](https://user-images.githubusercontent.com/9479903/168496523-1e5df462-947d-4a87-9fe4-66a65a81e551.png) ![image](https://user-images.githubusercontent.com/9479903/168496528-cb089496-481b-4ad5-86d9-70ae69d28a0c.png) ![image](https://user-images.githubusercontent.com/9479903/168496541-7119747b-385b-4e76-b9c0-885dd3441519.png)

i fix the error Bottle's can't create a desktop entry

when you click on add desktop entry.Bottle create a Desktop entry in this location.

/home/kali/.var/app/com.usebottles.bottles/data/applications/

Now copy the desktop entry of your app you create on bottle and paste in this location.

/home/kali/.local/share/applications/

Now click on the Home menu of your linux Distro and search for your app

**Comment by joezhouchenye** [comment]
If the copy-and-paste process is needed, why is this issue labeled closed??

**Comment by yllekz** [comment]
Issue should be reopened as the button does not work as intended.

**Comment by VortexAcherontic** [comment]
Can confirm, fresh install of a new system running Plasma 6.1.4 and flatpak Bottles.

When adding new desktop entries they get created at: `$HOME/.var/app/com.usebottles.bottles/data/applications/` which seems not to be a path where KDE looks for desktop files.

What I did to workaround the issue is the following:
- Grand Bottles read/write access to: `$HOME/.local/share/aplications/`
- Created a symlink from  `$HOME/.local/share/aplications/` to '$HOME/.var/app/com.usebottles.bottles/data/applications/`

This way bottles will create the desktop entries at a location KDE actually looks up and the bottle shortcuts do show up in the app launcher of Plasma right away.

**Comment by FlooferLand** [comment]
On my system it won't even make them at that path, so making a symlink is useless
I'm using ARch with KDE

**Comment by radzradz** [comment]
The entries were working for me but after recent update they are not anymore.
The entry is created at "/home/USER/.local/share/applications" as an Untrusted Application Launcher, setting to be trusted did not work. 
In terminal it says "Forcing offline mode" for a brief period.

When launching from Bottles the application launch normally.

The "Launch with bottle" option on a executable that is inside a bottle, which usually worked for me, is also not working.

I tried "flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications" which was the command that previously fixed the desktop entries problem for me.

**Comment by VortexAcherontic** [comment]
Maybe this is a vital information, I noticed on Gnome the override worked and Bottles could create app menu shortcuts but on KDE it didn't.

Tried this the last time with Plasma 6.something. Do not recall the exact version.

**Comment by jeancf** [comment]
I tested and failed on Plasma 6.3.4.

**Comment by usamaizm** [comment]
Does not work on SteamOS 3.8.

**Comment by fossthehoss** [comment]
> > Just tested and it's working fine, can't replicate.
> > ![image](https://user-images.githubusercontent.com/9479903/168496523-1e5df462-947d-4a87-9fe4-66a65a81e551.png) ![image](https://user-images.githubusercontent.com/9479903/168496528-cb089496-481b-4ad5-86d9-70ae69d28a0c.png) ![image](https://user-images.githubusercontent.com/9479903/168496541-7119747b-385b-4e76-b9c0-885dd3441519.png)
> 
> i fix the error Bottle's can't create a desktop entry
> 
> when you click on add desktop entry.Bottle create a Desktop entry in this location.
> 
> **`/home/kali/.var/app/com.usebottles.bottles/data/applications/`**
> 
> Now copy the desktop entry of your app you create on bottle and paste in this location.
> 
> **`/home/kali/.local/share/applications/`**
> 
> Now click on the Home menu of your linux Distro and search for your app

This is a workaround that works. I do agree that while overall it does add the desktop entry, it does so into the incorrect location that a normal user would not know to look. 

I believe this function should add it into the "/home/USER/.local/share/applications" directory by default since the application in question does not appear in the Home menu after the fact.

**Comment by redoxahmii** [comment]
Anyway to override the path it is making these entries because making inside `.var` makes no sense nor can you use that to display applications in a standard way rather than having to copy paste each entry every time.

**Comment by CraterDylan** [comment]
This is still an issue, and it required quite some digging to find a fix. #4012 seems to suggest it is related to KDE specifically, and having a non-English system language might make it worse, with how paths are handled. Check https://github.com/bottlesdevs/Bottles/issues/4012#issuecomment-3180365684 for a fix that worked (same idea of making a symlink, but with a practical example).

**Comment by VortexAcherontic** [comment]
> This is still an issue, and it required quite some digging to find a fix. [#4012](https://github.com/bottlesdevs/Bottles/issues/4012) seems to suggest it is related to KDE specifically, and having a non-English system language might make it worse, with how paths are handled. Check [#4012 (comment)](https://github.com/bottlesdevs/Bottles/issues/4012#issuecomment-3180365684) for a fix that worked (same idea of making a symlink, but with a practical example).

Update KDE. With at least 6.5.2 this issue is no more. Earlier 6.x releases are working as well but I can not pin point an exact version.

**Comment by CraterDylan** [comment]
> > This is still an issue, and it required quite some digging to find a fix. [#4012](https://github.com/bottlesdevs/Bottles/issues/4012) seems to suggest it is related to KDE specifically, and having a non-English system language might make it worse, with how paths are handled. Check [#4012 (comment)](https://github.com/bottlesdevs/Bottles/issues/4012#issuecomment-3180365684) for a fix that worked (same idea of making a symlink, but with a practical example).
> 
> Update KDE. With at least 6.5.2 this issue is no more. Earlier 6.x releases are working as well but I can not pin point an exact version.

I'm on 6.5.2-1, latest version on Nobara (based on Fedora 42).

**Comment by VortexAcherontic** [comment]
> > > This is still an issue, and it required quite some digging to find a fix. [#4012](https://github.com/bottlesdevs/Bottles/issues/4012) seems to suggest it is related to KDE specifically, and having a non-English system language might make it worse, with how paths are handled. Check [#4012 (comment)](https://github.com/bottlesdevs/Bottles/issues/4012#issuecomment-3180365684) for a fix that worked (same idea of making a symlink, but with a practical example).
> > 
> > 
> > Update KDE. With at least 6.5.2 this issue is no more. Earlier 6.x releases are working as well but I can not pin point an exact version.
> 
> I'm on 6.5.2-1, latest version on Nobara (based on Fedora 42).

Okay, that is weird. For me on Kalpa Desktop it works. Thought it was an KDE Bug but maybe not. My bad 🫤

**Comment by jarrard** [comment]
STILL a issue 

WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

kde 6.5.2

EDIT: 

It did create the shortcut in /home/gerarderloper/.local/share/applications/ after all but this has no connection to my desktop at all. Guess I'll just need to move it out.

**Comment by isaacluizalves** [comment]
I created a link from one folder to another to work in my
`ln -s ~/.local/share/applications ~/.var/app/com.usebottles.bottles/data/applications`

**Comment by jeancf** [comment]
I am on Arch with KDE Plasma 6.5.4 and my `~/.var/app/com.usebottles.bottles/data/applications` is empty. When I click on "Add Desktop Entry" I get redirected to the infamous `https://docs.usebottles.com/bottles/programs#flatpak` page. Executing the command does not change anything. It has been like this for years. Why is this bug closed?

**Comment by VortexAcherontic** [comment]
> I am on Arch with KDE Plasma 6.5.4 and my `~/.var/app/com.usebottles.bottles/data/applications` is empty. When I click on "Add Desktop Entry" I get redirected to the infamous `https://docs.usebottles.com/bottles/programs#flatpak` page. Executing the command does not change anything. It has been like this for years. Why is this bug closed?

Because it can not be reliably reproduced. For some it just works. For others it doesn't. Me for example I once was affected by this, but also I messed up some global flatpak permissions I assume not sure thought it started working one day but I can not recall what I may have changed. On others newly installed system the issue never happened in the first place.

Plasma 6.5.4 as well but on Kalpa Desktop (Tumbleweed based distro)

**Comment by jeancf** [comment]
I found what the problem was. The "program" in the bottles interface is named "C:\Program Files\Epic Games\SnowRunner". "Add Desktop Entry" tries to create a .desktop file with the same name but fails because the name is invalid.

```
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/applications//Epic Games--C:/Program Files/Epic Games/SnowRunner--1768233671.120976.desktop'
```

If I rename the entry under "Programs" in my bottle to "SnowRunner" then the desktop file gets created correctly.

**Comment by alexreinking** [comment]
I am also experiencing a related issue.

I'm on Fedora 43 Kinoite, KDE Plasma Version 6.5.5.

Creating a desktop entry from the menu places it in `~/.var/app/com.usebottles.bottles/data/applications` rather than `~/.local/share/applications`. Creating a symlink from the former to the latter is an effective workaround.

Permissions are set correctly, too:

```console
alex@alex-desktop:/var/home/alex$ flatpak info --show-permissions com.usebottles.bottles
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=all;
features=devel;multiarch;per-app-dev-shm;
filesystems=~/.local/share/applications;~/Dropbox/Documents/Guitar Music;

[System Bus Policy]
org.freedesktop.UDisks2=talk

[Environment]
LD_LIBRARY_PATH=/app/lib:/app/lib/i386-linux-gnu
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/usr/lib/i386-linux-gnu/gstreamer-1.0
PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/:/usr/lib/extensions/vulkan/gamescope/bin/
```

**Comment by forever-and-a-day** [comment]
> I am also experiencing a related issue.
> 
> I'm on Fedora 43 Kinoite, KDE Plasma Version 6.5.5.
> 
> Creating a desktop entry from the menu places it in `~/.var/app/com.usebottles.bottles/data/applications` rather than `~/.local/share/applications`. Creating a symlink from the former to the latter is an effective workaround.
> 
> Permissions are set correctly, too:
> 
> alex@alex-desktop:/var/home/alex$ flatpak info --show-permissions com.usebottles.bottles
> [Context]
> shared=network;ipc;
> sockets=x11;wayland;pulseaudio;
> devices=all;
> features=devel;multiarch;per-app-dev-shm;
> filesystems=~/.local/share/applications;~/Dropbox/Documents/Guitar Music;
> 
> [System Bus Policy]
> org.freedesktop.UDisks2=talk
> 
> [Environment]
> LD_LIBRARY_PATH=/app/lib:/app/lib/i386-linux-gnu
> GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/usr/lib/i386-linux-gnu/gstreamer-1.0
> PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/:/usr/lib/extensions/vulkan/gamescope/bin/

This worked for me, thanks! probably needs a new bug report of its own.
