### ISSUE TITLE
How do I install a program with a setup and multiple folders

### ISSUE THREAD

**Issue by refugedesigns** [bottlesdevs/Bottles#1469]
I am trying to install adobe photoshop, whenever I choose the executable, the program selects the executable alone and leaves the dependency folders which always makes the installer fail, Please how can I go about this. In all the research I've done, I can see people using only single executable with no dependency files.

**Comment by mirkobrombin** [comment]
Hi, check this (the title can distract) https://docs.usebottles.com/flatpak/black-screen-or-silent-crash
