### ISSUE TITLE
[Bug] - Command line/debug doesn't work on Flatpak

### ISSUE THREAD

**Issue by catsout** [bottlesdevs/Bottles#147]
**Describe the bug**
`Command Line` not work.

**Installation**
 - Method: flatpak
 - Version 3.0.2

**To Reproduce**
1.Create a software wineprefix
2.It use lutris-6.0
3.Go bottle page
4.Click `Command Line`, nothing happened

**Expected behavior**
A cmd window appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian
 - Version sid

**Additional context**

**Comment by mirkobrombin** [comment]
Can you run Bottles from your terminal and grab the error?

`flatpak run com.usebottles.Bottles`

**Comment by catsout** [comment]
Nothing helpful show
```text
2021-03-01 18:26:07 INFO: Runners found: [lutris-6.0-x86_64]
2021-03-01 18:26:07 INFO: Dxvk found: [dxvk-1.7.3, dxvk-1.8]
2021-03-01 18:26:07 INFO: Connection status: online …
2021-03-01 18:26:07 INFO: Connection status: online …
2021-03-01 18:26:08 INFO: Connection status: online …
2021-03-01 18:26:08 INFO: Bottles found: wine
2021-03-01 18:26:09 INFO: Bottles Started!
2021-03-01 18:26:10 INFO: Setting Key: [sync] to [wine] for bottle: [wine] …
2021-03-01 18:26:12 INFO: Running a CMD on the wineprefix …
2021-03-01 18:26:16 INFO: Running a CMD on the wineprefix …
```

But I can run cmd though taskmanager's `New Task..`

**Comment by mirkobrombin** [comment]
What terminal has your system?

**Comment by catsout** [comment]
Konsole

**Comment by mirkobrombin** [comment]
Should be supported
https://github.com/bottlesdevs/Bottles/blob/536532364c01981d7c383a0653c8ad9d126983e4/src/utils.py#L69

**Comment by catsout** [comment]
https://github.com/bottlesdevs/Bottles/blob/536532364c01981d7c383a0653c8ad9d126983e4/src/utils.py#L64

So the `Command Line` not launch a wine cmd window, but it's run in a system terminal?
But bottles is in flatpak, it's able to open konsole on host system?

**Comment by mirkobrombin** [comment]
> https://github.com/bottlesdevs/Bottles/blob/536532364c01981d7c383a0653c8ad9d126983e4/src/utils.py#L64
> 
> So the `Command Line` not launch a wine cmd window, but it's run in a system terminal?
> But bottles is in flatpak, is it able to open konsole on host system?

This may actually be a limitation

**Comment by wsdfhjxc** [comment]
In order to run host programs (e.g. from `/usr/bin`) within a Flatpak application, the application needs a session bus talk permission to `org.freedesktop.Flatpak`. Then it can execute `flatpak-spawn --host program args` to run the actual `program`.

**Comment by Nokia808** [comment]
@mirkobrombin 
Hello ! I would like to ask, is implementation of this can increase risk of viruses penetration or not ? It would be very good to implement it without increase such risk.
