### ISSUE TITLE
[Bug]: Remove from list does not do anything anymore

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1470]
### Describe the bug

When a new program has been install into a bottle and sometimes extra stuff is added that is not wanted like test.exe by developers i like to hide those. In the latest release "Remove from list" when clicking the ... dots beside a program does not do anything. Also what would the difference be between Hide from list and Remove from list? If i pick hide from list can i still show later?

### To Reproduce

1. install a program
2. Click ... dots beside program either on "Details & Utilities" or "Programs" page
3. Click "Remove from list
nothing happen

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
2022.5.14-trento

No issues here everything else work normal
```

**Comment by mirkobrombin** [comment]
You have to use "hide from list" to "hide" auto-discovered software and "remove from list" to remove your added entries.
The remove option just delete the reference, not the .lnk file discovered by Bottles.

**Comment by ghtesting2020** [comment]
> You have to use "hide from list" to "hide" auto-discovered software and "remove from list" to remove your added entries. The remove option just delete the reference, not the .lnk file discovered by Bottles.

Wouldn't it be better for user experience if "remove from list" only shows when the program was manually added?

**Comment by mirkobrombin** [comment]
Already planned
