### ISSUE TITLE
[Bug]: download every nvidia runtime with each update

### ISSUE THREAD

**Issue by samuraied** [bottlesdevs/Bottles#1471]
### Describe the bug

whenever i update my flatpaks by running flatpak update, i noticed it redownloads every nvidia drivers there is, back from 470 all the way to the newest editions, this does not happen when i update flatpaks individually, only when updating bottles.

### To Reproduce

run flatpak update com.usebottles.bottles.

here is a screenshot
![Screenshot from 2022-05-15 19-21-01](https://user-images.githubusercontent.com/23434177/168483223-78a98b77-c63e-458d-894d-a560c00ac93e.png)

### Package

Flatpak from Flathub

### Distribution

fedora 35 and 36

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.6-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16826634240
    Free: 16826478592
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 25.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

this has been happening since i installed bottles, but i recently got bored and decided to debug this problem, after several hours, i narrowed it down to bottles, this issue no longer happens when i don't update bottles.

i am only using 2 apps, 7zip and SAK,
i forgot to mention, i already updated the 64bit versions of nvidia drivers, that's why only the 32bit drivers appear in the screenshot.
PS: i love how neat and innovative bottles is, i hope this gets fixed.

**Comment by samuraied** [comment]
Nevermind, the problem came back even after i deleted bottles.

**Comment by mirkobrombin** [comment]
Hi thanks for reporting.
This is how Flatpak works, Bottles declares the need for Nvidia GLs, and Flatpak installs and keeps them up to date.

Closing as non-bug, feel free to add more comments.
