### ISSUE TITLE
What's needed to bring this to Mac?

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [bottlesdevs/Bottles#1472]
In a nutshell. What incompatibilities or snags to run into?

**Comment by jannuary** [comment]
Someone willing to take the burden of porting and maintaining a macOS version indefinitely, first of all

**Comment by mirkobrombin** [comment]
I have no experience with MacOS app development, I think it can work by changing the internal paths (now obtained via xdg) and it should work without too many obstacles

**Comment by alsyundawy** [comment]
vote

**Comment by ohault** [comment]
+1 for porting and supporting Bootles on MacOS.

**Comment by mirkobrombin** [comment]
I will investigate

**Comment by mirkobrombin** [comment]
As we are splitting backend and frontend, it might make more sense if someone creates a client with a MacOS supported toolkit. Of course, this cannot be done immediately as the backend has to become a package in itself but, it is an idea.

**Comment by xorik** [comment]
@tiziodcaio wine perfectly works on latest mac (even on M1 CPU). I used this command to install working version:

```
brew install --cask wine-crossover
```

**Comment by xrishox** [comment]
Yeah I've used wine on macos for a few things and it seems to be quite compatible even including 32 bit software. The guy who seems to be the biggest maintainer or packager for wine on macos says that you need to use specific versions of wine to have reasonable 32 bit compatibility and performance though.

Would be really cool to have bottles on macos.

**Comment by alsyundawy** [comment]
bump ...

**Comment by mirkobrombin** [comment]
No need to bump, read here: https://usebottles.com/blog/bottles-next-a-new-chapter/
