### ISSUE TITLE
[Bug]: Cant install any new runners / DLL Componets 

### ISSUE THREAD

**Issue by 32bitx64bit** [bottlesdevs/Bottles#1480]
### Describe the bug

No idea why this is happening worked just fine till the latest release 

Just says when attempting to install 'The installation failed. This may be due to a repository issue, partial download or checksum mismatch

Tried to reinstall bottles still doesnt work

### To Reproduce

Go to preferences 
Runner or DLL Component tab
Attempt to install a Runner / Component 

### Package

Flatpak from Flathub

### Distribution

Ubuntu Linux mint

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-110-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16792309760
    Free: 16792154112
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 27.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Can't replicate, it works fine on my side:

![image](https://user-images.githubusercontent.com/9479903/168970172-8d7bab49-8148-4b38-a8f1-174115dc2375.png)
![image](https://user-images.githubusercontent.com/9479903/168970181-14a6869f-ddf7-44f0-98bc-1eadd83f429d.png)

All downloads are on GitHub, it can happen that the platform has slowdowns.

I'll close, feel free to add comments if it persists.

**Comment by 32bitx64bit** [comment]
Seems to be fixed in the latest verison of bottles
