### ISSUE TITLE
use external drive as custom bottles path?

### ISSUE THREAD

**Issue by gamerjag** [bottlesdevs/Bottles#1505]
i have a games drive and a main drive for linux/windows and i can’t really move 900gb of games onto a 105gb partition is there a way to use the external drive as a path? i only see the linux partition in the window that opens when i search for a custom location

**Comment by mirkobrombin** [comment]
Please use our forum for stuff like this (forums.usebottles.com).

---

Assuming you are on Flatpak, you must [give permission](https://docs.usebottles.com/flatpak/expose-directories) to reach the path, then restart Bottles, and go to `your bottle -> preferences -> Manage drives`, then pick a letter (e.g. G:) and choose the path. Now it is available from the wine file manager.
