### ISSUE TITLE
Is libpcap included?

### ISSUE THREAD

**Issue by zoenglinghou** [bottlesdevs/Bottles#1513]
I have a program that needs `npcap` to run. From what I gather from [this forum post](https://forum.winehq.org/viewtopic.php?t=29830), I need `libpcap` to enable wine's replacement for `npcap`. Is this library included in the flatpak version? Or am I mistaken?

Thank you!

**Comment by mirkobrombin** [comment]
Yes it is https://github.com/flathub/com.usebottles.bottles/blob/6ce8ce2f356250c4af85711148aaab60c0cde7fc/com.usebottles.bottles.yml#L261
