### ISSUE TITLE
I want to use the wine installed in the system.

### ISSUE THREAD

**Issue by YTOAA** [bottlesdevs/Bottles#1514]
Thank you for making a good program. The program I want is run only on "winehq-staging 7.9" due to a bug. So I want to use that version as a runner, is there any way? I tried it with other runners, but it didn't work.

**Comment by YTOAA** [comment]
> 

I don't know why, but it keeps showing only sys-wine version 7.0.

**Comment by YTOAA** [comment]
Obviously, it only runs on version 7.0 even though it is installed on the system at version 7.9
![화면 캡처 2022-05-24 221952](https://user-images.githubusercontent.com/24527825/170044856-cba8401c-9c19-495e-a7ca-8e9429bbf259.png)
.

**Comment by YTOAA** [comment]
Unfortunately, the update of Vaniglia runner is a little slow. If I don't install it using flatpak, can I solve this phenomenon?

**Comment by mirkobrombin** [comment]
You have to wait for the build. I don’t think you strictly need the 7.9 which was releases a few days ago 😅
