### ISSUE TITLE
[Tip] Screenshots should use system font

### ISSUE THREAD

**Issue by bertob** [bottlesdevs/Bottles#152]
The current appstream screenshots don't seem to be using the default system font (Cantarell), which makes them look a bit alien.

**Comment by mirkobrombin** [comment]
I don't seem to have changed the font to the system but I'll check. Thanks for the report

**Comment by bertob** [comment]
FWIW I think some distributions (including Ubuntu at some point, not sure if it's still the case) ship a broken version of Cantarell.

**Comment by mirkobrombin** [comment]
These screenshots were taken on Fedora Silverblue 33 as far as I can remember.
