### ISSUE TITLE
[Bug]: Arguments are ignored when using the --program option

### ISSUE THREAD

**Issue by pbaja** [bottlesdevs/Bottles#1522]
### Describe the bug

I am using the `bottles-cli` tool to run games directly from .desktop shortcut (which I am then adding to a Steam).
I want to run a launcher (Ubisoft Connect in this case) and pass an argument to it that will directly open my game.

This does not work:
```
flatpak run --command=bottles-cli com.usebottles.bottles run -b Ubi -p "Ubisoft Connect" -a "uplay://launch/5595/0"
```
It just opens the ubisoft connect. Does not pass the arguments provided with `-a` option.

This does work:
```
flatpak run --command=bottles-cli com.usebottles.bottles run -b Ubi -e "/home/deck/.var/app/com.usebottles.bottles/data/bottles/bottles/Ubi/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/upc.exe" -a "uplay://launch/5595/0"
```
And opens the Ubisoft Connect launcher, which is then immediately launching my game.

### To Reproduce

1. Install any program in the bottle with "Installers" option
2. Try to run that program from bottles-cli, with the `-p PROGRAM -a ARGUMENTS` options
3. ARGUMENTS are being ignored

### Package

Flatpak from Flathub

### Distribution

Steam Deck

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 9.9GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by Lucki** [comment]
I've also stumbled upon this before and can confirm this behavior.

Sadly it seems intentional because the help text says exactly this but a bit unclear:
>  -a ARGS, --args ARGS  Arguments to pass to the **executable**

**Comment by mirkobrombin** [comment]
Only executables support inline arguments. To add arguments to programs you have to use the Launch Options from the GUI and they will also be used by the CLI while launching the program.

It is unclear and we should update the documentation.
