### ISSUE TITLE
[Bug]: Unhanded page fault setting windows version (wine)

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#1523]
### Describe the bug

![Screenshot_2022-05-25_12-24-03](https://user-images.githubusercontent.com/98482469/170300978-a5e670b1-dcb7-4227-a269-c3669e2fa61d.png)

![Screenshot_2022-05-25_12-24-23](https://user-images.githubusercontent.com/98482469/170301200-196beb85-10e2-461b-adc5-dd4ad2abca33.png)

### To Reproduce

.

### Package

Flatpak from Flathub

### Distribution

Zorin OS Lite

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-44-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 2051911680
    Free: 2051764224
RAM:
    MemTotal: 3.8GiB
    MemAvailable: 2.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by Heus-Sueh** [comment]
> I may be a compatibility problem with the runner. Please try removing `~/.var/app/com.usebottles.bottles/data/bottles/templates` and make the bottle again (restart Bottles after removing)

I deleted the folder but it didn't work
and this is only happening in the flatpak version when i was on arch linux the aur version worked normally
![image](https://user-images.githubusercontent.com/98482469/170329417-3bbfde47-9e3a-454e-a2a9-b212aad7bf02.png)

**Comment by mirkobrombin** [comment]
Oh Arch ok, the flatpak has some problems with the flatpak, idk why. It cause freezes, crash, weird behavior

**Comment by Heus-Sueh** [comment]
> Oh Arch ok, the flatpak has some problems with the flatpak, idk why. It cause freezes, crash, weird behavior

I'm not using Arch Linux, but Zorin OS 
But this problem occurs in both systems in the Flatpak version

**Comment by mirkobrombin** [comment]
Interesting

**Comment by ConicalBurrSet** [comment]
Hi Mirko!

I'm coming from #1556. I also tried the above steps and ran into the exact same issue. I left Bottles alone for a couple of hours and it was still hung at the same point. I can test in other distros if you would like also. I have a multiboot system with Fedora (KDE), Kubuntu, Manjaro (KDE), MX Linux (KDE), and Pop!_OS (yeah I like KDE LoL). I have space for another distro also so please make any recommendation and I'll install and test.

Have a great day!

**Comment by Heus-Sueh** [comment]
i installed Arch Linux again and installed Bottles AUR and it worked normally.

![Screenshot_2022-06-14_21-33-36](https://user-images.githubusercontent.com/98482469/173711821-9f941f52-3e7a-4021-a799-070962735299.png)
![Screenshot_2022-06-14_21-33-51](https://user-images.githubusercontent.com/98482469/173711828-ad221dd0-8f96-4e95-aed9-5e46cfbfe85b.png)
