### ISSUE TITLE
[Request]: gamescope defaults

### ISSUE THREAD

**Issue by Martinligabue** [bottlesdevs/Bottles#1524]
### Tell us the problem or your need

I think Gamescope can be improved by adding the default screen settings both for screen and window size, so it's easier and faster to configure

### Describe the solution you'd like

get screen res, autocomplete screen res

### Other solutions?

maybe it would be cool to have some default resolutions to choose from

**Comment by ghtesting2020** [comment]
+1. Great idea

**Comment by Martinligabue** [comment]
default res could be inspired by yt defaults: https://support.google.com/youtube/answer/6375112
it would help understand how it will look

also, a button for keeping ratio so the view will not stretch or create black bars would help manage gamescope

**Comment by TheEvilSkeleton** [comment]
I like the idea, but I'm not sure how we would detect the aspect ratio of the display. The user might have two or more monitors, so making it detect the right monitor might be extremely difficult. And then there will be more complications with Wayland and X11.

**Comment by TheEvilSkeleton** [comment]
Looks like `gdk_screen_height` and `gdk_screen_width` are deprecated. https://docs.gtk.org/gdk3/class.Screen.html

We'll have to find a workaround or something.

**Comment by mirkobrombin** [comment]
So we should probably remove them

**Comment by TheEvilSkeleton** [comment]
There's no easy way for us to gather information about the display. Furthermore, if we do implement it, we'll have to support X11 users and Wayland users. It will require workarounds and likely won't be easily maintainable.

Unfortunately, for the time being, we can't implement it.
