### ISSUE TITLE
[Crash report]  'NoneType' object has no att (Steam Prefix)

### ISSUE THREAD

**Issue by MistrPokr** [bottlesdevs/Bottles#1528]
Hi! I'm experiencing this issue after checking Steam Proton Prefixes in Experiments settings. While I fully understand this feature is experimental and this crash report is quite generic (might have something to do with my Steam setup as well), the fact that Bottles refuses to launch due to this fault in Bottles' early launch stages was quite troubling. 

Initially I thought Bottles would have a standalone, user-global configuration file under ~/.local/bottles and spent quite a while trying to find a global configuration file for Bottles and failed, then I read `window.py` and realized Bottles uses the GtkSettings API. As a mainly KDE/Qt user I wasn't very aware of its existence and had very little experience with `gsettings`. For anyone with the same issue, the trouble was solved with: 

```
$ gsettings set com.usebottles.bottles experiments-steam false
```

And I believe this has reverted my configuration setup. While all these very much are my own problems, it would be quite nice to document this behavior just in case someone else has a wrong setup and cannot revert it from Bottles GUI, since the error prevents the GUI from launching at all. 

---

This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.5.14-trento-3

**Log**
```python3
'NoneType' object has no attribute 'items'  File "/usr/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/window.py", line 279, in get_manager
    mng = Manager(window)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 118, in __init__
    self.checks(install_latest=False, first_run=True)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 135, in checks
    self.check_bottles()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 843, in check_bottles
    SteamManager.update_bottles()

  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 242, in update_bottles
    prefixes = SteamManager.list_prefixes()

  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 188, in list_prefixes
    for appid, appdata in apps.items():

```

**Comment by mirkobrombin** [comment]
Thanks for reporting
