### ISSUE TITLE
[BUG]  Installation of Chardonnay 6.2-unstable runner fails

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/Bottles#153]
**Describe the Bug**
When enabling Pre-Release wine runners and trying to download chardonnay version 6.2-unstable, the installation fails. A notification appears that says that the dowloaded file is corrupted and I should try again. This leads to the same result

**Installation**
 - Method: Flatpak
 - Version 3.0.5

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Hamburger Menu Button.
2. Click on the Preferences entry.
3. Scroll down to Wine Runners.
4. Click on Pre-release to enable the chardonnay 6.2-unstable option.
5. Click on the download button besides the chardonnay-6.2-unstable entry.
6. The downloads starts, but the install of the runner fails. It says that the downloaded file looks corrupted.

**Expected behaviour**
The chardonnay 6.2-unstable runner should be installed successfuly.

**Screenshots**
![Bildschirmfoto von 2021-03-03 11-00-04](https://user-images.githubusercontent.com/41188546/109788485-a89ac100-7c0f-11eb-9976-da95f01f5a6b.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
Actually the Chardonnay 6.2 unstable build is broken. You should open an issue in the bottlesdevs/wine repository.

**Comment by Sebastian-Hirsch** [comment]
Thanks for the clarification! I don't see an option to create an issue like here in the repo. The issues button is missing. Also shouldn't there be an option to add the unstable-6.3 version in bottles? Or is that broken too?

![Bildschirmfoto von 2021-03-03 11-15-44](https://user-images.githubusercontent.com/41188546/109790720-fc0e0e80-7c11-11eb-93a6-dafb2a6e21b3.png)

**Comment by mirkobrombin** [comment]
Builds are automatic. Since 6.2 it broke due to lack of 32bit dependencies and I have to investigate. I have enabled the issues.

**Comment by Sebastian-Hirsch** [comment]
Thanks for your help @mirkobrombin. I have created an issue in the mentioned repository: https://github.com/bottlesdevs/wine/issues/13
