### ISSUE TITLE
Message of changes when updating bottles

### ISSUE THREAD

**Issue by Dansito** [bottlesdevs/Bottles#1536]
I consider that getting along with the community is important for any program and also keeping them informed, so I suggest an idea to notify the changes/fixes of each bottle update when starting the first time after updating (this by version). Many bugs are fixed and new features are added and many people don't have the time to look at the blog or github to see this, I think this should be implemented to keep the community even more informed and this reduce the burden on developers with old bugs or people not knowing that new features have been added.

An example of this implementation is the application in flathub (Extension Manager) which notifies the changes of each update.

I also think you should add a "Do not show more" option for users who don't want to know about this.

Example:
![image](https://user-images.githubusercontent.com/84112405/170822797-6e534366-d744-41a8-9a82-a528c947da96.png)

**Comment by jannuary** [comment]
No, we will not be doing this. When one opens an app, their primary goal is to, well, use the app, not to be interrupted by random & unexpected dialogs. If I'm not mistaken Extension Manager scrapped it for this reason. 

Users are already notified about updates by GNOME Software (or similar), where they can see the changelog.

**Comment by Dansito** [comment]
Sure, there are people who will annoy you, which is why I said there should be a "don't show anymore" option for those who don't care about this information.

But there will be people who like this information (which will only come out after updating) it won't always come out if that's what you think.

I was also thinking it would be interesting to sync those release notes with the bottles blog, that would be great.

**Comment by TheEvilSkeleton** [comment]
I don't see a point of duplicating work. As @jannuary said, it's interruptive to the user. People can check the changes directly from GNOME Software. Before they update, they click on the software in question and then the change log appears.

**Comment by MrQuerter** [comment]
What about people that don't use GNOME Software? Bottles is flatpak so it's not only used by GNOME users. When updating through CLI you don't get any changelogs at all.

Maybe it will be ok to just add a "update changelog" link in the menu that would point to the newest blog post?

**Comment by mirkobrombin** [comment]
We spend a lot of time writing release posts in our blog with care for details and readability. Please read notes there.

**Comment by Dansito** [comment]
I had not thought about that, I think that discover does not show this information either, and as I said. It could perfectly synchronize this new function with the blog and show only a general summary, if you want to see more you would have to go to the blog.

**Comment by TheEvilSkeleton** [comment]
Again, the concern is the interruption. Whether the summary is 10 words or an essay, it will always interrupt initially.

There are already plenty of ways to get to the changelogs: GNOME Software, website, GitHub, chat platforms, etc.
