### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tjapro** [bottlesdevs/Bottles#1541]
### Describe the bug

I removed the bootles and cleaned the respective folder inside `.var`

P.S.: When I click on the "Report" button, chrome sends a 400 message from github.

### To Reproduce

1. Uninstall bottles
2. Remove bootles folders inside the `.var`folder.
3. Install bottle.
4. The program hangs.
5. Close it and reopen it (and the error report appears).

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
I do not have acess to that button.
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/releases/tag/2022.5.28-trento-1, should hit flathub soon
