### ISSUE TITLE
[Bug]: Stuck on loading screen after update

### ISSUE THREAD

**Issue by RadioactiveRadio** [bottlesdevs/Bottles#1545]
### Describe the bug

Updated bottles through flatpak, now it's stuck on loading

![Screenshot_20220529_024012](https://user-images.githubusercontent.com/106451902/170843068-28355037-95c7-4b21-981f-dc2fb5328024.png)

crash report:

[Errno 20] Not a directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/.directory/bottle.yml'  File "/app/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/window.py", line 279, in get_manager
    mng = Manager(window)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 118, in __init__
    self.checks(install_latest=False, first_run=True)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 768, in check_bottles
    with open(_config, "r") as f:

### To Reproduce

When installed using flatpak:

update and launch bottles

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Health Check

```shell
Not able to health check because of bottles not loading.
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Idk why and how but you have a bottle named .directory. I’m not able to replicate, also we served an hotfix some hours ago, be sure to update. 

Delete the broken bottle or just rename, it should works. If the bottle.yml file is missing, the bottle is unrecoverable (Bottles don’t delete without user input). 

Closing as not replicable, feel free to provide more info.

**Comment by RadioactiveRadio** [comment]
i see, thanks!
