### ISSUE TITLE
[Bug]: Bottles crashes if the bottles' folder has an empty folder inside

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [bottlesdevs/Bottles#1550]
### Describe the bug

I like having my bottles folder in my home directory, and to easily identify the folder, I gave it Bottle's program icon.

However, apparently Bottles sees the .directory file that is created for this purpose inside the folder, and tries to open it as a bottle directory and search for the bottle.yml file that would be inside, which prompts the following error:

`Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x7f00528c1e50>
        Exception: [Errno 20] Not a directory: '/home/aura/Bottles/.directory/bottle.yml'`

Apparently, this crash occurs if there is anything in the bottles directory besides a bottle.

I would expect Bottles to ignore hidden files, or at least the .directory file specifically.

### To Reproduce

1. Create any file in the bottles directory (in this case, a .directory file created by Dolphin)
2. Run Bottles
3. Bottles crashes.

### Package

Flatpak from Flathub

### Distribution

KDE Neon

### Health Check

```shell
isplay:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.11.0-43-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8053833728
    Free: 8053690368
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 9.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
I'll fix this with next release, in the meantime can you just put a bottle.yml file inside or remove that directory?

**Comment by AuraHerreroRuiz** [comment]
I apologize if I didn't explain myself correctly, but the .directory file is, well, a file. My guess would be that Bottles is crashing because it tries to open a file inside a directory with the name of the file (".directory" in this case), and gets the "not a directory" exception.

That aside, yes, in the mean time I'll delete the file and have the folder without a custom icon, it's no issue.
