### ISSUE TITLE
[BUG] Namespace Handy not available (AppImage)

### ISSUE THREAD

**Issue by Lvaskz** [bottlesdevs/Bottles#156]
**Describe the bug**
Appimage does not start after make it executable

**Installation**
 - Method: [ Appimage]
 - Version [3.0.5]

**To Reproduce**
1. Go to https://usebottles.com/download/
2. Click on download appimage
3. wait untill appimage is downloaded
4. find bottles.appimage 
5. make it executable
6. doble click on bottles.appimage
5. See error, nothing happens, not start.

**Expected behavior**
Appimage must run and it must to show all menus and work

**Screenshots**

**Desktop:**
 - OS: [kde Neon,Ubuntu]
 - Version [5.21.1,20.04]

**Additional context**

**Comment by mirkobrombin** [comment]
I think some addiction is missing. Try starting it from the terminal. I expect a python error.

**Comment by mclvren** [comment]
```
(bottles:25796): Gtk-WARNING **: 19:22:50.236: Theme parsing error: gtk-dark.css:6361:24: 'none' is not a valid color name
Traceback (most recent call last):
  File "/tmp/.mount_BottlehSf6eZ/usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_BottlehSf6eZ//usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_BottlehSf6eZ//usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
```

after installing libhandy the same

**Comment by mirkobrombin** [comment]
Install the libhandy-dev package (should be something like libhandy-1.0-dev). It is not packaged in the AppImage and this is a problem.

**Comment by Lvaskz** [comment]
libhandy-1.0-dev should be package in the appimage, not?  Some day for that?, not?

**Comment by mirkobrombin** [comment]
> libhandy-1.0-dev should be package in the appimage, not? Some day for that?, not?

I am not too familiar with AppImage, I have to read up on how to do it correctly.

**Comment by mirkobrombin** [comment]
> > libhandy-1.0-dev should be package in the appimage, not? Some day for that?, not?
> 
> I am not too familiar with AppImage, I have to read up on how to do it correctly.

**Comment by mirkobrombin** [comment]
Missclicked. Is it working with that dependency?

**Comment by Lvaskz** [comment]
Well, I must try. I need some time, I have not my personal computer.

**Comment by Lvaskz** [comment]
> after installing libhandy the same

Well, I think he tried by me.

**Comment by Lvaskz** [comment]
ok, I tried, with libhandy installed, same problem.

**Comment by Lvaskz** [comment]
Traceback (most recent call last):
  File "/tmp/.mount_BottlepUsTlo/usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_BottlepUsTlo//usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_BottlepUsTlo//usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1

**Comment by mirkobrombin** [comment]
> ok, I tried, with libhandy installed, same problem.

The package is libhandy1.0-dev or something like this. You need the dev dependency

**Comment by mirkobrombin** [comment]
I did some tests to include the dependencies in the AppImage but there is a problem in using the system GTK theme, it may take some time to figure it out

**Comment by Lvaskz** [comment]
I tried the last appimage 3.0.6 in ubuntu 20.04 and kde neon 5.21.1. The issue remains

**Comment by hthre7** [comment]
python bug don't show after bundling gtk but still appimage will not open, it's libhandy(`ValueError: Namespace Handy not available`)(not available in repos of this Distro)(linux mint 19.3-bottles 3.0.6)

**Comment by mirkobrombin** [comment]
The needed package is libhandy1 or libhandy1.0, Idk how is packaged. I will bundle it with the AppImage

**Comment by hthre7** [comment]
installed libhandy1 but still will not open ,not it show(previous python-gi error )[`gi.repository.Gtk' object has no attribute 'Template`]

**Comment by hthre7** [comment]
is it possible to use AppImage recipe(.yml) to build Bottle with it's dependencies(I think(?) this method will bundle dependencies properly)

**Comment by mirkobrombin** [comment]
> is it possible to use AppImage recipe(.yml) to build Bottle with it's dependencies(I think(?) this method will bundle dependencies properly) OR using [linuxdeploy-plugin-python](https://github.com/niess/linuxdeploy-plugin-python) could help .

We are already using linuxdeploy-plugin-gtk but I want to migrate to the recipe format in the near future. At the time there is a lot of work on other fronts and I cannot do this. You are free to open a PR if you know how, it would be greatly appreciated.

**Comment by soredake** [comment]
Same problem with 3.0.7 on Kubuntu 20.10.

**Comment by mclvren** [comment]
> Same problem with 3.0.7 on Kubuntu 20.10.

Haven't tried the latest appimage but check the version of installed libhandy library in your system, in my case the problem was solved by installing 1.0.* version, the default was 0.0.*.

**Comment by soredake** [comment]
Installing `libhandy-1-dev` works, i hope it will be properly included in appimage later.

**Comment by soredake** [comment]
```
(bottles:56080): GLib-GIO-ERROR **: 18:44:24.968: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
/tmp/.mount_BottleUIPUft/AppRun.wrapped: line 52: 56080 Trace/breakpoint trap   (core dumped) python3 $APPDIR/usr/bin/bottles $1
```
File picker in appimage makes bottles crash.

**Comment by mirkobrombin** [comment]
> ```
> (bottles:56080): GLib-GIO-ERROR **: 18:44:24.968: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
> /tmp/.mount_BottleUIPUft/AppRun.wrapped: line 52: 56080 Trace/breakpoint trap   (core dumped) python3 $APPDIR/usr/bin/bottles $1
> ```
> 
> File picker in appimage makes bottles crash.

This can be caused by the GTK bundle in the AppImage. Strange because I tested it before the release.

**Comment by hthre7** [comment]
> > is it possible to use AppImage recipe(.yml) to build Bottle with it's dependencies(I think(?) this method will bundle dependencies properly) OR using [linuxdeploy-plugin-python](https://github.com/niess/linuxdeploy-plugin-python) could help .
> 
> We are already using linuxdeploy-plugin-gtk but I want to migrate to the recipe format in the near future. At the time there is a lot of work on other fronts and I cannot do this. You are free to open a PR if you know how, it would be greatly appreciated.

so I tried bundling dependencies manually(following some AppImage docs) but I faced new bug `*** stack smashing detected ***: terminated
/home/rfanze/Applications/squashfs-root/squashfs-root/AppRun.wrapped: line 58:  5040 Aborted                 (core dumped) python3 $APPDIR/usr/bin/bottles $1` also I'm trying Appimage-builder (but there is error also related to appimage-builder itself not bottles).

**Comment by hthre7** [comment]
not build script just extracted the appimage(`--appimage-extract`) and adding the missing dependencies and export the library in (apprun.wrapped)

**Comment by mirkobrombin** [comment]
> **update**
> after using Appimage-builder what I manage to get is this
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/user/Applications/squashfs-root/AppDir//usr/bin/bottles", line 49, in <module>
>     from bottles import main
>   File "/home/user/Applications/squashfs-root/AppDir///usr/local/share/bottles/bottles/main.py", line 47, in <module>
>     logging = UtilsLogger()
>   File "/home/user/Applications/squashfs-root/AppDir///usr/local/share/bottles/bottles/utils.py", line 110, in __init__
>     formatter = format_log
> NameError: name 'format_log' is not defined
> ```

Check that you are using the latest AppImage please

**Comment by hthre7** [comment]
> Check that you are using the latest AppImage please

I'm using appimage-builder to generate appdir from source then run (AppRun) 
cause still bottles appimage showing missing related python-gi version

**Comment by mirkobrombin** [comment]
I fixed the format_log error a few commits ago

**Comment by hthre7** [comment]
that's weird I updated to last source, if you want I could provide the recipe of appimage-builder for bottle if you could test it

**Comment by mirkobrombin** [comment]
Check for this line in your source code
https://github.com/bottlesdevs/Bottles/blob/0eeafd94682956907561130becc3df85772e29e0/src/utils.py#L99

**Comment by hthre7** [comment]
> format_log = {

`    format_log = {
        'fmt': '%(asctime)s \033[1m%(levelname)s\033[0m: %(message)s',
        'datefmt': '%Y-%m-%d %H:%M:%S',
    }`
it's there

**Comment by mirkobrombin** [comment]
> > format_log = {
> 
> ` format_log = { 'fmt': '%(asctime)s \033[1m%(levelname)s\033[0m: %(message)s', 'datefmt': '%Y-%m-%d %H:%M:%S', }`
> it's there

Ok it's definitely weird.

**Comment by hthre7** [comment]
finally managed to get it to work but themeing is off I think it missing some gtk stuff (theme) here is recipe for [bottles-recipe-AppImage-builder](https://paste.ubuntu.com/p/FyVHVYdZZG/) 
![mainwindow-bottles](https://user-images.githubusercontent.com/64407362/110779733-8f77bd00-826c-11eb-9e88-03dc1a0a4722.png)
![preferences-bottles](https://user-images.githubusercontent.com/64407362/110779736-90105380-826c-11eb-9ba5-70a41d713242.png)

**Comment by mirkobrombin** [comment]
Great. Regarding the theme, maybe it no longer reads the system preferences or can't access the directory of the system one?

**Comment by hthre7** [comment]
I think it need editing enviroment variable to make it work
cause the .env with gtk has the following env variable added

```bash
GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
APPDIR_LIBRARY_PATH=$APPDIR/lib/x86_64-linux-gnu:$APPDIR/lib/x86_64-linux-gnu/security:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders:$APPDIR/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules:$APPDIR/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/printbackends:$APPDIR/usr/lib/x86_64-linux-gnu/gio/modules
GTK_EXE_PREFIX=$APPDIR/usr/lib
GTK_DATA_PREFIX=$APPDIR/usr/lib

```

**Comment by Lvaskz** [comment]
> final bottles AppImage size **'Bottles-3.0.8-x86_64.AppImage 54.6 MB'** quite large(but hoping to make it more portable).

Well, I know I have not power of decision about this, but I think it is recommended. I hope it can be released

**Comment by mirkobrombin** [comment]
~60MB is an absolutely acceptable size. I don't have much time to devote to the AppImage packaging process but I am available to merge changes (stable and tested). This is a community driven project, any contributions are welcome.

**Comment by hthre7** [comment]
> ~60MB is an absolutely acceptable size. I don't have much time to devote to the AppImage packaging process but I am available to merge changes (stable and tested). This is a community driven project, any contributions are welcome.

absolutely that's great, but as I mentioned above theme still some work to figure it out . for now I think we should see will the appimage work in different distribution and we managed to include acceptable coverage of dependencies.

**Comment by hthre7** [comment]
> Well, I know I have not power of decision about this, but I think it is recommended. I hope it can be released

for now you could find it (if its allowed by developer) https://github.com/hthre7/bottles-appimage-builder-test-unofficial/releases/tag/test

**Comment by Lvaskz** [comment]
> for now you could find it (if its allowed by developer) at [bottles-appimage-builder-test-unofficial/releases](https://github.com/hthre7/bottles-appimage-builder-test-unofficial/releases/tag/test)

Great!!! thanks

**Comment by hthre7** [comment]
@mirkobrombin could you tell me which gtk version bottles is using? thanks in advance.
also gtk issue is actually known one, check this https://github.com/AppImage/AppImageKit/issues/906#issue-398543025 .

**Comment by mirkobrombin** [comment]
> @mirkobrombin could you tell me which gtk version bottles is using? thanks in advance.
> also gtk issue is actually known one, check this https://github.com/AppImage/AppImageKit/issues/906#issue-398543025 .

Should be latest 3.x, maybe 3.38?

**Comment by Lvaskz** [comment]
Traceback (most recent call last):
  File "/tmp/.mount_BottleYSNiG9//usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/tmp/.mount_BottleYSNiG9/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
 i have the same issue with this https://github.com/hthre7/bottles-appimage-builder-test-unofficial/releases/download/test/Bottles-3.0.8-x86_64.AppImage

**Comment by hthre7** [comment]
> Traceback (most recent call last):
> File "/tmp/.mount_BottleYSNiG9//usr/bin/bottles", line 49, in
> from bottles import main
> File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/main.py", line 49, in
> from .window import BottlesWindow
> File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/window.py", line 21, in
> gi.require_version('Handy', '1')
> File "/tmp/.mount_BottleYSNiG9/usr/lib/python3/dist-packages/gi/**init**.py", line 129, in require_version
> raise ValueError('Namespace %s not available for version %s' %
> ValueError: Namespace Handy not available for version 1
> i have the same issue with this https://github.com/hthre7/bottles-appimage-builder-test-unofficial/releases/download/test/Bottles-3.0.8-x86_64.AppImage

updated just redownload.

**Comment by mirkobrombin** [comment]
Let me know when you have something stable that I can add to the GitHub workflow

**Comment by Lvaskz** [comment]
> > Traceback (most recent call last):
> > File "/tmp/.mount_BottleYSNiG9//usr/bin/bottles", line 49, in
> > from bottles import main
> > File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/main.py", line 49, in
> > from .window import BottlesWindow
> > File "/tmp/.mount_BottleYSNiG9///usr/local/share/bottles/bottles/window.py", line 21, in
> > gi.require_version('Handy', '1')
> > File "/tmp/.mount_BottleYSNiG9/usr/lib/python3/dist-packages/gi/**init**.py", line 129, in require_version
> > raise ValueError('Namespace %s not available for version %s' %
> > ValueError: Namespace Handy not available for version 1
> > i have the same issue with this https://github.com/hthre7/bottles-appimage-builder-test-unofficial/releases/download/test/Bottles-3.0.8-x86_64.AppImage
> 
> **updated just redownload.**

Traceback (most recent call last):
  File "/tmp/.mount_Bottlekm6M2d//usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_Bottlekm6M2d///usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_Bottlekm6M2d///usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/tmp/.mount_Bottlekm6M2d/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1


same issue

**Comment by mirkobrombin** [comment]
Please, put codes and outputs inside the ``` accents.

**Comment by hthre7** [comment]
> same issue

@Lvaskz could try now I updated (it should work but if there is an issue please report back)
@mirkobrombin  could you tell me what's the default bottles icons set( adwaita or other icons set)

**Comment by mirkobrombin** [comment]
> > same issue
> 
> @Lvaskz could try now I updated it (it should work but if there is an issue please report back)
> @mirkobrombin could you tell me what's the default bottles icons set( adwaita or other icons set)

Adwaita

**Comment by Lvaskz** [comment]
> @Lvaskz could try now I updated it (it should work but if there is an issue please report back)

Hi, I tried it. Appimage is working, but some icons are broken in kde plasma, see:
![b1](https://user-images.githubusercontent.com/29207169/111697212-e7796b00-87fa-11eb-831c-d60083081dcb.png)
![b2](https://user-images.githubusercontent.com/29207169/111697216-e8120180-87fa-11eb-9920-fcd41d7253cf.png)
![b3](https://user-images.githubusercontent.com/29207169/111697218-e8aa9800-87fa-11eb-8e69-549c2babe430.png)

**Comment by Lvaskz** [comment]
@hthre7 by the way, thanks for making the appimage work

**Comment by Lvaskz** [comment]
> Adwaita

packaging these icons set in appimage will fix this issue ?

**Comment by mirkobrombin** [comment]
> > Adwaita
> 
> packaging these icons set in appimage will fix this issue ?

Should

**Comment by hthre7** [comment]
> packaging these icons set in appimage will fix this issue ?

@Lvaskz  could you test,I updated it ( theme should work but if there is an issue please report back).
lastly I should add translations.(but now theme if its work adding translations will be next)

**Comment by mirkobrombin** [comment]
> > packaging these icons set in appimage will fix this issue ?
> 
> @Lvaskz could you test,I updated it ( theme should work but if there is an issue please report back).
> lastly I should add translations.(but now theme if its work adding translations will be next)

Great. What's the problem with translations?

**Comment by Lvaskz** [comment]
> @Lvaskz could you test,I updated it ( theme should work but if there is an issue please report back).
> lastly I should add translations.(but now theme if its work adding translations will be next)

Hi there, I can confirm theming and running is ok, I tested on live OS kde neon. I NOT tested  all function, I will be later. Thanks by the way!!!!

**Comment by Lvaskz** [comment]
> What's the problem with translations?

With the version not official 3.0.9 translation are not applied in the location language in the app, in my case spanish.  There is a open issue related I think https://github.com/bottlesdevs/Bottles/issues/174

**Comment by Lvaskz** [comment]
> There is a open issue related I think #174

but in this case is in flatpak bundle

**Comment by hthre7** [comment]
> What's the problem with translations?

nothing but they were not included but now there are in AppImage.

@Lvaskz could you test,I updated it [also now it's updated to the latest master commit] ( **translations** are included, should work but if there is an issue please report back).

**Comment by Lvaskz** [comment]
Hi, I can confirm appimages has translations to spanish and it running well, but some translations are to 90 to 95 percent. I can live with that. 
Thanks

**Comment by Lvaskz** [comment]
I wonder why is not completed translated. I guess I did it completely.

**Comment by mirkobrombin** [comment]
There is now a Telegram group if you guys need a more immediate communication tool t.me/usebottles

**Comment by Lvaskz** [comment]
> There is now a Telegram group if you guys need a more immediate communication tool https://t.me/usebottles

Cool!!!

**Comment by Lvaskz** [comment]
When we can use this appimage with all improvements ?

**Comment by mirkobrombin** [comment]
> When we can use this appimage with all improvements ?

It needs to be integrated into the GitHub CI build process via the build script in the project root.

**Comment by hthre7** [comment]
> It needs to be integrated into the GitHub CI build process via the build script in the project root.

@mirkobrombin I tried to do pull request but couldn't figure out how to do it so Ill send the recipe to you. and it could be integrated  in github CI

**Comment by Lvaskz** [comment]
New appimages 3.1.1 run well. I gona close
Thank you all you guys. Great app 👍

**Comment by Lvaskz** [comment]
Bottles 3.1.1 has libhandy and theming looked good in KDE neon. Thank all you guys.👍
