### ISSUE TITLE
[Request]: Option to choose Wine username

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/Bottles#1564]
### Tell us the problem or your need

When you create bottle it uses your system username for "drive_c/users/X"

### Describe the solution you'd like

To fix this there could be an option that allows you to pick the username that you want Bottles to use.

It could either be per bottle or for all of them in the preferences.

**Comment by mirkobrombin** [comment]
Hi thanks for reporting. What's the purpose of this?
