### ISSUE TITLE
[Tip] Use portal for "Run .exe" file picker

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#157]
Currently, the file picker doesn't integrate with xdg-desktop-portal. 
This means that:

1. Flatpak users cannot choose a file anywhere in the filesystem 
2. The file picker will stick out like a sore thumb on non-GNOME platforms.

[Portal Documentation](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser)

**Comment by mirkobrombin** [comment]
Unfortunately for me the whole Flatpak world is unknown and I need help on this front.

**Comment by mirkobrombin** [comment]
I am going to close this issue as we are leaving Flatpak (https://mirko.pm/blog/bottles-will-leave-flatpak/).

**Comment by jannuary** [comment]
This is still unsolved and portals do not only affect Flatpak - [GtkFileChooserNative](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) just summons the platform native file picker, which makes for better system integration, even disregarding Flatpak.

**Comment by mirkobrombin** [comment]
I got confused because of the flatpak documentation in your post. I have NEVER read about this and assumed it refers to Flatpak (as your text implies)
