### ISSUE TITLE
[Request]: add program's shortcuts to desktop after installing it

### ISSUE THREAD

**Issue by soredake** [bottlesdevs/Bottles#1571]
### Tell us the problem or your need

I want this option to achieve this: i install program (skype for example) in bottles -> after installing skype's shortcut (that bottles sees already) is placed to ~/Desktop so i can easy launch it later

### Describe the solution you'd like

Have an option to add program's shortcuts to desktop after installing it

**Comment by soredake** [comment]
For flatpak there is https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.DynamicLauncher

 And what i want can and should be added as optional option, yes.

**Comment by mirkobrombin** [comment]
We don't support DynamicLauncher yet but we will in the future.

We have 2 places to start programs (program list, library) and you can still generate desktop entries with 1 click. Adding another option in Bottles can be done but needs to be evaluated.

**Comment by mirkobrombin** [comment]
Merging #1366

**Comment by soredake** [comment]
So, no option for auto-adding shortcuts to desktop will be added? Or it will be added after Dynamic Launcher portal will be supported?

**Comment by mirkobrombin** [comment]
We be added as optional after dynamic implementation
