### ISSUE TITLE
[Request]: Add support for easily setting custom icons (such as for Pride month, etc.)

### ISSUE THREAD

**Issue by orowith2os** [bottlesdevs/Bottles#1590]
### Tell us the problem or your need

Having the ability to make custom Bottles icons and integrate them with the rest of the app would be a nice feature to have for some occasions, such as for Pride month. 

### Describe the solution you'd like

A simple editor included inside the app to set some images to use ones modified by the user without needing to compile from source, dig around in the files, and the like.

### Other solutions?

A tab included inside the settings panel that gives detailed instructions on how to customize the icons.

### Additional context and references

example of what this feature would add the ability for: https://media.discordapp.net/attachments/864654997357854745/984511277189722232/unknown.png

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting.

Help me understand, are we talking about an editor in Bottles to add overlays on the program icons that Bottles generates or on the Bottles icon itself?

**Comment by orowith2os** [comment]
An editor in (or one that allows easy modification to) Bottles to change the icon, and maybe even some UI elements, so that you don't have to go digging into the files to find the right file to change (the flatpak of Bottles needs you to change a file that's deep in the .local directory)

**Comment by orowith2os** [comment]
Maybe something to add onto the custom icons, the ability to set an icon per app, so you could have a Bottle with the EGS installed have the EGS logo next to the name, for example.

**Comment by jannuary** [comment]
No, we're not gonna do that - no other app has this and you can just as easily use programs like MenuLibre to change the Bottles desktop icon.

**Comment by mirkobrombin** [comment]
Ok I understand what you mean. This feature is too out of scope and only weighs down the user interface, as well as something not easy to maintain.

Closing, feel free to add more comments.
