### ISSUE TITLE
[Bug]: Mobile mode doesn't open content

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1592]
### Describe the bug

Mobile mode doesn't open content. It's just stuck doing nothing. I'm using Bottles from Flathub-beta with libadwaita + GTk4.

### To Reproduce

1. Open a bottle
2. Resize to make it resize to a mobile
3. Try to open any tab

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.12-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 3862990848
    Free: 3862847488
RAM:
    MemTotal: 7.2GiB
    MemAvailable: 3.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

I can't go past this screen on mobile mode:

![image](https://user-images.githubusercontent.com/50847364/172943709-a9938c84-e070-4c2f-ba5f-3ccc6697e6fc.png)

**Comment by mirkobrombin** [comment]
I think the problem here is the permission to resize the window so much. Although Bottles could run on smartphones, at the moment there are no ARM builds working for Wine
