### ISSUE TITLE
[Bug]: Invisible checkbox in dropdown menu

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1593]
### Describe the bug

It's nearly impossible to tell that the "Launch in terminal" button is a check. The only way to find out is if we click on it. I'm using Bottles from Flathub-beta with libadwaita + GTk4.

### To Reproduce

1. Open a bottle
2. Click on the arrow button next to "Run Executable"

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.12-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 3862990848
    Free: 3862847488
RAM:
    MemTotal: 7.2GiB
    MemAvailable: 2.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

![image](https://user-images.githubusercontent.com/50847364/172945646-64f38f71-4055-4b46-aeea-a425f49459cf.png)

**Comment by mirkobrombin** [comment]
Assuming checkbox just doesn't works in menus, we should change widget. @jannuary what's your proposal to fix this?
