### ISSUE TITLE
Broken Font with Flatpak version.

### ISSUE THREAD

**Issue by TomJuri** [bottlesdevs/Bottles#1599]
The font look distorted and broken while using the flatpak version.
AUR Version is fine. Screenshots: 
![image](https://user-images.githubusercontent.com/99533320/173117380-2bce76be-20e8-473b-98e1-8f2bb43cf85c.png)
![image](https://user-images.githubusercontent.com/99533320/173117420-59dbf0d4-ad6d-45de-b4b5-6c55723bfe46.png)
![image](https://user-images.githubusercontent.com/99533320/173117462-0169d995-dce6-4dfe-ba1b-7184b2283fae.png)
I'm using Arch, with Linux Zen kernel and KDE Plasma.

**Comment by edisionnano** [comment]
Wayland right?

**Comment by TomJuri** [comment]
Yes.

**Comment by TheEvilSkeleton** [comment]
Do you have `xdg-desktop-portal-gtk` installed?

**Comment by TomJuri** [comment]
Yes, I do.

**Comment by TomJuri** [comment]
I fixed it by disabling Wayland windowing system in Flatseal.
![image](https://user-images.githubusercontent.com/99533320/173123083-f9a97e0e-143d-4a51-9627-12dbf5b2cdd0.png)
