### ISSUE TITLE
[Bug]: Cant open any bottle

### ISSUE THREAD

**Issue by julikaiba** [bottlesdevs/Bottles#1600]
### Describe the bug

When clicking on a bottle it normally opens details for said bottle. When I click on it, only the plus in the top right changes to an arrow and the three dots next to the minimize button disappear, but nothing else happens. 

### To Reproduce

1. start bottles
2. (create a bottle)
3. click on a bottle
4. see that nothing happens

### Package

AUR ("bottles" package)

### Distribution

Manjaro

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.195-1-MANJARO
Distro:
    Name: Manjaro Linux
    Version: Unknown
Disk:
    Total: 422146228224
    Free: 272349958144
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 21.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I already rebuild or removed and installed the package multiple times and also deleted the files in ~/.local/share/bottles

**Comment by mirkobrombin** [comment]
Run in a terminal and post the output here please

**Comment by edisionnano** [comment]
> Run in a terminal and post the output here please

Happens on my two machines, both are from AUR
here's the python error
`Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/usr/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 336, in set_config
    self.switch_runtime.handler_block_by_func(self.__toggle_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_runtime of <bottle_preferences.PreferencesView object at 0x7ff61cfa7e00 (DetailsPreferences at 0x55e4161c31f0)>>
`

**Comment by Vilsol** [comment]
Seems like wrapping these 2 lines in try-catch fixes it.

https://github.com/bottlesdevs/Bottles/blob/master/src/views/bottle_preferences.py#L308

https://github.com/bottlesdevs/Bottles/blob/master/src/views/bottle_preferences.py#L406

**Comment by mirkobrombin** [comment]
Oh it's the same problem as the steam runtime where the widget is disconnected when it already is. Nice found
