### ISSUE TITLE
[Request]: vkBasalt configuration per bottle

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1607]
### Tell us the problem or your need

Currently Bottles only uses one vkBasalt config for every bottle, which is located at `~/.var/app/com.usebottles.Bottles/config/vkBasalt/vkBasalt.conf` if using Flatpak. There's no convenient method to use a specific config per bottle.

### Describe the solution you'd like

I propose to create a GUI editor for vkBasalt. vkBasalt has the option to take configs from the `VKBASALT_CONFIG_FILE` environment variable, which gives us the ability to apply specific configs for each bottle.

### Additional context and references

I am writing a CLI for vkBasalt, since vkBasalt doesn't have one. We could use this program as a backend to generate configs: https://gitlab.com/TheEvilSkeleton/vkbasalt-cli.

**Comment by Arcitec** [comment]
I have been digging a lot to figure out how this works.

This is how:

- If the Post-Processing Effects checkbox is enabled in Bottles (vkBasalt):
- It looks for `vkBasalt.conf` in the bottle directory and enables that config path via environment variable if found. To edit this config, go into the bottle in Bottles, and press the "Browse" button. You will be taken to a directory that contains `drive_c`, `bottle.yml` etc. Place `vkBasalt.conf` next to all of that.
- If no per-bottle config is found, vkBasalt itself loads the Bottles Flatpak's generic vkBasalt config location (equivalent to `~/.config/vkBasalt/vkBasalt.conf`).

```py
        if params.vkbasalt and not self.minimal:
            vkbasalt_conf_path = os.path.join(
                ManagerUtils.get_bottle_path(config), "vkBasalt.conf"
            )
            if os.path.isfile(vkbasalt_conf_path):
                env.add("VKBASALT_CONFIG_FILE", vkbasalt_conf_path)
            env.add("ENABLE_VKBASALT", "1")
```

**Important Note:** If you edit the Post-Processing Effects GUI shader checkboxes and stuff in Bottles, it will overwrite the aforementioned per-bottle `vkBasalt.conf` file and loses your hand-edited config. It's a good idea to make a duplicate copy of `vkBasalt.conf` to easily restore if Bottles breaks it.

===

To debug whether the environment was applied, I did this:

```bash
# replace game.exe executable name with yours:
ps aux | grep 'game\.exe'

# replace 50783 with game PID result from above:
strings /proc/50783/environ | grep BASALT
```

I got the expected results:

```
ENABLE_VKBASALT=1
VKBASALT_CONFIG_FILE=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Gaming/vkBasalt.conf
```

===

There's an easy way to debug effects by running `vkcube` inside the Flatpak to see if your config is applied correctly:

```sh
$ flatpak run --command=sh com.usebottles.bottles
$ ENABLE_VKBASALT=1 VKBASALT_CONFIG_FILE=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Gaming/vkBasalt.conf vkcube
```
