### ISSUE TITLE
[Bug]: Can't open "Preferences" from the menu

### ISSUE THREAD

**Issue by bikebaranek** [bottlesdevs/Bottles#1611]
### Describe the bug

When I click _Preferences_ from the Bottle's menu nothing happens.

When running through terminal I get:

`Traceback (most recent call last):
  File "/app/share/bottles/bottles/window.py", line 371, in show_prefs_view
    preferences_window = PreferencesWindow(self)
  File "/app/share/bottles/bottles/views/preferences.py", line 101, in __init__
    self.populate_runners_list()
  File "/app/share/bottles/bottles/views/preferences.py", line 223, in populate_runners_list
    and runner[1]["Channel"] in ["rc", "unstable"]):
KeyError: 'Channel'`

### To Reproduce

1. Open Bottles
2. Click _Preferences_ from the menu
3. Nothing happens

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04 LTS

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.0-14.1-liquorix-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8230834176
    Free: 8230686720
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 12.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Bottles version: 2022.5.28-trento-3 (Flatpak from Flathub)

**Comment by MaCroX95** [comment]
Can confirm, also happens on Wayland with flatpak version
