### ISSUE TITLE
[Request]: Porting to Windows leveraging WSL2

### ISSUE THREAD

**Issue by ohault** [bottlesdevs/Bottles#1614]
### Tell us the problem or your need

Managing Windows App on Windows is still very problematic.
Windows GUI apps cannot still run in Windows Containers and it is not a joke.
There is almost no Bottles features on Windows.

### Describe the solution you'd like

Easily run Windows software on Windows with Bottles!

This could leverage WSL2(with WSLg)+WINE - see https://www.youtube.com/watch?v=UEre6Bd75dw 

Even when Microsoft will support running Windows GUI apps in Windows Containers, Bottles features will continue to provide an add value.

**Comment by VarLad** [comment]
Can we close this issue? :)

**Comment by jannuary** [comment]
You could feasibly run Bottles in WSL, if that's what you need for whatever reason, but I don't think we're interested in supporting that incredibly niche use case in an app for running *Windows* apps on *Linux*.
