### ISSUE TITLE
[Bug]: Namespace Gtk not available for version 4.0

### ISSUE THREAD

**Issue by xioren** [bottlesdevs/Bottles#1619]
### Describe the bug

Latest version does not open. Installed via .deb file. When running from terminal this error is received:

```
Traceback (most recent call last):
  File "/usr/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 27, in <module>
    gi.require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0

```

### To Reproduce

open bottles

### Package

From source

### Distribution

debian testing

### Health Check

```shell
n/a
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Not Bottles fault, you are missing GTK4

**Comment by mirkobrombin** [comment]
Yup! We deprecated our dev manifest so don’t use it to build Bottles

**Comment by xioren** [comment]
Well I just run dpkg-buildpackage, so idk the correct way to build a deb but that clearly is not it.

**Comment by TheEvilSkeleton** [comment]
You might want to use the Bottles Flatpak instead. It's actively supported.

**Comment by xioren** [comment]
> You might want to use the Bottles Flatpak instead. It's actively supported.

Thanks I tried that but the flatpak installs literally gigabytes of bloat just to install bottles so that's just not something I'm willing to accept.

**Comment by jannuary** [comment]
>  flatpak installs literally gigabytes of bloat 

Source?

**Comment by Anachron** [comment]
$ sudo flatpak install ~/usr/dls/com.usebottles.bottles.flatpakref

```
 1. [✓] com.usebottles.bottles.Locale             stable       i  flathub 628,9 kB / 591,5 kB
 2. [✓] org.freedesktop.Platform.GL.default       21.08        i  flathub 131,0 MB / 131,3 MB
 3. [✓] org.freedesktop.Platform.GL32.default     21.08        i  flathub 109,1 MB / 138,6 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel      21.08        i  flathub  11,7 MB / 11,8 MB
 5. [✓] org.freedesktop.Platform.ffmpeg-full      21.08        i  flathub   4,7 MB / 4,2 MB
 6. [✓] org.freedesktop.Platform.ffmpeg_full.i386 21.08        i  flathub   4,8 MB / 4,3 MB
 7. [✓] org.freedesktop.Platform.openh264         2.0          i  flathub   1,5 MB / 1,5 MB
 8. [✓] org.gnome.Platform.Compat.i386            42           i  flathub 145,5 MB / 154,1 MB
 9. [✓] org.gnome.Platform.Locale                 42           i  flathub 171,6 MB / 336,0 MB
10. [✓] org.gnome.Platform                        42           i  flathub 233,3 MB / 276,2 MB
11. [✓] org.winehq.Wine.DLLs.dxvk                 stable-21.08 i  flathub  21,9 MB / 21,2 MB
12. [✓] org.winehq.Wine.gecko                     stable-21.08 i  flathub 114,0 MB / 114,0 MB
13. [✓] org.winehq.Wine.mono                      stable-21.08 i  flathub  68,2 MB / 85,1 MB
14. [✓] com.usebottles.bottles                    stable       i  flathub 113,7 MB / 146,7 MB
```

**Comment by Anachron** [comment]
I'm not OP but I am not using flatpak (or AppImage) and being forced to download all of these things to install a `4MB` app is quite ridiculous.

**Comment by TheEvilSkeleton** [comment]
`.var/app/com.usebottles.bottles` is user data. So even if you got it from the AUR, you'd use it as much/

**Comment by TheEvilSkeleton** [comment]
Also, the """bloat""" is one of the reasons why we went for Flatpak. Everyone uses the same dependencies. It makes troubleshooting and user experience much better because we can update at our pace while using up-to-date dependencies.

**Comment by xioren** [comment]
So for what it's worth, despite digging my heals in I have finally converted. Flatpaks are the way to go.
