### ISSUE TITLE
[Request]: Increase size of side tabs

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1620]
### Tell us the problem or your need

Right now, Bottles's side tabs are narrow and don't seem to be consistent with the GNOME desktop. GNOME apps typically have wider side tabs, which also look better on 1080p monitors and above.

### Describe the solution you'd like

Increase the size of side tabs.

### Additional context and references

GNOME Settings:
![image](https://user-images.githubusercontent.com/50847364/173700215-994e2587-6f06-4490-9249-9fed70318be2.png)

Bottles:
![image](https://user-images.githubusercontent.com/50847364/173700234-1e1d2f9e-7ea4-48b0-b27f-6a57f2fb4dcc.png)

**Comment by ghtesting2020** [comment]
How would this impact when not in full screen? There is already a ridiculously large margins/whitespace beside each title. The longest title is "Details & utilities" and beside that there is already 30% or more empty space. The others are much shorter and it is more like 50% extra margins/whitespace.

**Comment by TheEvilSkeleton** [comment]
This is how Settings and Bottles look like respectively:
![image](https://user-images.githubusercontent.com/50847364/173708868-03733ef2-3fae-430e-bf77-e96a5a94304a.png)

![image](https://user-images.githubusercontent.com/50847364/173708882-3d14a2f5-6159-4622-bb90-3ccece3204a6.png)

On a 1080p monitor:

![image](https://user-images.githubusercontent.com/50847364/173709420-dc85fe39-9ac0-4f45-ae69-9158d0cecc2e.png)

I'm not too sure exactly what the size of those windows are, as I don't know how to resize them exactly to a size. They should be roughly 868x703.

**Comment by jannuary** [comment]
Is this defined anywhere? I cannot recall the HIG or otherwise stating sidebars should have this many pixels, and not one more

**Comment by TheEvilSkeleton** [comment]
I don't know, I didn't read the HIG. I just believe it'd look better and be easier to click the side tabs. I have difficulty moving all the way to the left because the width is too narrow.

**Comment by mirkobrombin** [comment]
Assuming that I have not found any HIGs to mention it, I have tested different sizes for the sidebar and this seems to me the most correct as the titles are very short and would result in a huge waste of space.

If you want to test in yours, you can start Bottles with the Gtk inspector `GTK_DEBUG = interactive flatpak run com.usebottles.bottles` and test different sizes in yours.

**Comment by mirkobrombin** [comment]
Closing as the sidebar will be removed with the final DetailsView design.
