### ISSUE TITLE
[Bug]: Un-navigable paths in file picker

### ISSUE THREAD

**Issue by xioren** [bottlesdevs/Bottles#1623]
### Describe the bug

Basic system paths are outright missing when trying to choose a custom bottles path. In particular media/mnt where all my hard drives reside.

![Screenshot from 2022-06-14 15-55-08](https://user-images.githubusercontent.com/40043405/173703194-212f746d-9427-4386-813e-23239f955390.png)

I checked and there are no permission issues with these folders.

### To Reproduce

attempt to change default bottles path

### Package

Flatpak from Flathub

### Distribution

debian testing

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.0-1-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8367566848
    Free: 8367411200
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.9GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
You must give Bottles permission to reach other paths. In this context we have explicitly avoided using the portal to reach external paths by scaling the permissions because Bottles must have permanent access to the new path.

Here an example on how to achieve this: https://docs.usebottles.com/flatpak/expose-directories
