### ISSUE TITLE
[Bug]: Cannot add desktop entry

### ISSUE THREAD

**Issue by dklementowski** [bottlesdevs/Bottles#1624]
### Describe the bug

When clicking on "Add desktop entry" nothing happens in the UI. When running program from terminal, it dumps the Python stack trace after unhandled exception

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/widgets/program.py", line 284, in update
    dialog = Gtk.MessageDialog(
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 522, in __init__
    _window_init(self, *args, **kwargs)
TypeError: gobject `GtkMessageDialog' doesn't support property `flags'
```

### To Reproduce

1. Go to any bottle
2. Click the 3 dots menu in any program entry
3. Click 'Add Desktop Entry' option

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.3-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8339619840
    Free: 8339464192
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 12.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I updated Bottles to `2022.6.14-brescia` and all the programs was installed using older versions. I haven't tried installing anything new just yet. I also never tried to use the option before as I just noticed it's there and I die to have that feature, seriously!

**Comment by jannuary** [comment]
Whoops, yeah, that's broken indeed :\
It's supposed to bring a dialog explaining how to get permissions, but it hasn't been updated for GTK4 - though of course, would be the best to stop shipping that hack in general.

**Comment by mirkobrombin** [comment]
I'll make a fix but I want to provide dynamic launcher portal support in 2022.6.28 so the workaround will be removed.
