### ISSUE TITLE
[Bug]: Manually added Programs no longer show on Details & Utilities

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1625]
### Describe the bug

2022.6.14-brescia

A lot of my games are portable .exe that i manually added in "Programs" since updating to latest version they disappear from the "Details & Utilities" page. Only ones that were automatically added when installing show there now

### To Reproduce

manually add game exe in Programs
go to Details & Programs
no show

### Package

Flatpak from Flathub

### Distribution

arch

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.17.14-hardened1-1-hardened
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8306270208
    Free: 8306102272
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 12.4GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by ghtesting2020** [comment]
actually it looks like the issue is that now only 5 Programs are displayed in "Details & utiltiies". Some of my bottles have over 30 programs in them.

**Comment by mirkobrombin** [comment]
This is how it should works. The main page shows only 5 rows and you must use the programs page to view the full list. In the future the 5-entries list will be sorted by usage.
