### ISSUE TITLE
[Bug]: Libadwaita-git ArchLinux do not compile

### ISSUE THREAD

**Issue by EvoXCX** [bottlesdevs/Bottles#1629]
### Describe the bug

Latest version come with libadwaita-git but can't compile it.
Why do not use libadwaita ?

### To Reproduce

Update Bottles to version 2022.6.14-brescia

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.14-xanmod1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 105089261568
    Free: 57153896448
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

When installing latest version of bottles without libadwaita-git and with libadwaita packages do not work !

Crash log :

Traceback (most recent call last):
  File "/usr/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 35, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 36, in <module>
    from bottles.views.details import DetailsView
  File "/usr/share/bottles/bottles/views/details.py", line 34, in <module>
    from bottles.views.bottle_preferences import PreferencesView
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 32, in <module>
    from bottles.dialogs.envvars import EnvVarsDialog
  File "/usr/share/bottles/bottles/dialogs/envvars.py", line 25, in <module>
    class EnvVarEntry(Adw.EntryRow):
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'EntryRow'

**Comment by laichiaheng** [comment]
@jannuary Why libadwaita-git?

**Comment by TechXero** [comment]
Now the dependency pefile ([python-pefile-git](https://aur.archlinux.org/packages/python-pefile-git)) will not compile either and hasn't been updated since 2015.. 

Not to mention libadwaita-git which got an update this morning that still fails to compile for us on KDE..

**Comment by laichiaheng** [comment]
Flatpak is the only way to go now.

**Comment by TechXero** [comment]
I don't use flatpaks.. I maintain my own distro with my own repos and I have Bottles on my repo need to build latest to push..

**Comment by laichiaheng** [comment]
Flatpak version can't access my home folder....

**Comment by TechXero** [comment]
> Flatpak version can't access my home folder....

I would highly recommend you downgrade to 2022.05.28-5 that's what I have done and all is back to normal.. Keeping that version on my repo for now...

**Comment by mirkobrombin** [comment]
> That’s why we need libadwaita-git. I’m not the package maintainer but I’m considering to rollback until libadwaita gets the release we need

@francescomasala

**Comment by mirkobrombin** [comment]
We are going to rollback the aur package until libadwaita get updated
