### ISSUE TITLE
[Bug]: New file/directory selection screen no longer follows symbolic links

### ISSUE THREAD

**Issue by ak-42** [bottlesdevs/Bottles#1631]
### Describe the bug

Before 2022.6.14-brescia-1, the file/folder selection dialogue used for running an exe or setting a working directory would allow the user to follow symbolic links. This is useful, as symbolic linking allows users to move storage intensive files like games to a different drive with more storage, and simply leave a link behind. Such solutions have worked reliably for me for months, and I have never encountered any issues attributable to symbolic link usage.

After 2022.6.14-brescia-1, the new file/folder selection dialogue no longer follows the symbolic links, but simply treats them like a file. This means that if a link is selected while trying to run the exe, the symbolic link file will simply be selected as if it was a file, rather than being followed to the new location.

Could you please consider reverting this regressed behaviour to the previous solution?

### To Reproduce

1. Create a new bottle, with any successfully executing Windows program in it.
2. Move the exe (or the folder containing it) to a new location, either on the same storage device, or another one.
3. Create a symbolic link pointing to exe in the new location, and leave it in the old location.
4. Select 'run an exe' and try to navigate to the exe via the symbolic link. You will find that you cannot follow the symbolic link.
5. Alternatively, try setting the working directory of the bottle to where the exe is, by following the symbolic link. It can no longer be done.
6. (Optional) Run the program via the standard program shortcut. It will still work via the symbolic link, as expected.

### Package

Flatpak from Flathub

### Distribution

Steam Deck (immutable Arch)

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 9.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I think this might be related to move to GTK4? The only workaround I have so far is to make all these changes (such as setting the working directory or manually selecting program entry) and only moving the files and creating link last.

**Comment by mirkobrombin** [comment]
We haven’t changed anything in that context. Does flatpak have access to the destination path?

**Comment by ak-42** [comment]
> We haven’t changed anything in that context. Does flatpak have access to the destination path?

I have given Flatpak access to the whole home folder via Flatseal. And while I haven't explicitly given Bottles access to the sdcard that the symlinks points to, this worked fine prior to brescia (and actually still works, bottles using symlinks which were setup on the previous version still work fine, I just cannot make the changes on new ones). I actually successfully setup a new bottle using symlinks like an hour before the brescia update popped up for me. Then I updated, came back and tried to do another one, and it did not work.

Before brescia, the file/folder selection dialogue for me was native KDE-looking one, but in brescia it has changed to what seems to be GNOME provided one (presumably due to move to GTK4?).

**Comment by mirkobrombin** [comment]
Testing master in a Fedora KDE VM and it uses Dolphin.

![image](https://user-images.githubusercontent.com/9479903/174469719-fe9eb8c0-a9df-4063-9ae1-12e40b532d5b.png)

I'm able to reproduce the symlink problem but it's not something we can fix in our as we "just use it". Closing to keep the issues tracking clean, feel free to add more comments.
