### ISSUE TITLE
[Bug]: Problems with program options menu

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1640]
### Describe the bug

When you click the "3 dots" button on any program in your programs list there are few problems:

1. It stays on when you click "browse path" or "launch with terminal" button
2. It doesn't allow you to press print screen button to make a screenshot
3. "Remove from list" button doesn't work at all - except when you user it on a hidden program then it puts the program back into the list.
4. It takes focus from all the windows and bars that you have - I can't click on any icons on my taskbar and I can't click on any windows that were opened when you use "open with terminal" button

### To Reproduce

1. Open Bottles
2. Go to your installed programs in any bottle
3. Check the "browse path", "launch with terminal" button
4. Try to make a screenshot
5. Try to click on icons on your taskbar
6. Try the "remove from list" button

### Package

Flatpak from Flathub

### Distribution

Linux Mint 20.3 Cinnamon

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-117-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8361029632
    Free: 8360882176
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

I also tried the "add to my library" button and it closed the menu, but now my library doesn't show any programs that I had (it used to show my 2 games without icons even after the update)

**Comment by mirkobrombin** [comment]
1. need to investigate and sounds like a bug in our
2. I see this in other gtk4 apps, I think it's gtk related
3. that's "normal" as you can't remove auto-discovered programs, only hide, the remove button should not be visible for auto-discovered programs
4. same as point 2

**Comment by MrQuerter** [comment]
Hi. The first point from this issue:
"1. It stays on when you click "browse path" or "launch with terminal" button"
is still half true. The menu stays on when you click "launch with terminal" button. The "browse path" button works as intended so there was a fix for it. Also the terminal button still can't launch Pekka Kana 2 just like I wrote in my old issue. I don't know if you've seen it.
