### ISSUE TITLE
[Bug]: Moving two fingers on touchpad slightly makes UI disappear

### ISSUE THREAD

**Issue by o-kotb** [bottlesdevs/Bottles#1641]
### Describe the bug

It's kinda hard to explain, so here is a video demonstration. I'm scrolling on the left side there with my trackpad.

https://user-images.githubusercontent.com/72304125/174077645-cb486226-3b67-4fa0-a75c-9ff5a5c696e3.mp4

### To Reproduce

1. Open a bottle.
2. Scroll the left area where the tabs are there.
3. Window disappears.

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    
X.org
: true
    
X.org
 (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json😕usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.14-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 1898684416
    Free: 1898536960
RAM:
    MemTotal: 3.5GiB
    MemAvailable: 2.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

**Comment by jannuary** [comment]
Here's the gist: swiping right is supposed to navigate back - that's intentional.
However, also, while navigating back, (that is, while the transition is running) the bottle's contents get destroyed. This is fine with buttons and keyboard shortcuts, but less fine with swipes - a tiny tap can trigger the back transition, which deletes the bottle UI.

**Comment by o-kotb** [comment]
Looks like it. I never noticed the UI change because I mostly used bottles on desktop and just pressed to back button. But on a laptop, it becomes very obvious especially since I often fail to complete the swipe and it goes back to the window with the deleted UI. And then there is activating the transition accidentally like in the video.

**Comment by mirkobrombin** [comment]
I'm not able to replicate. Is this wayland only?

**Comment by axtloss** [comment]
I have faced the same issue and managed to "fix" it by setting `can-navigate-back` in https://github.com/bottlesdevs/Bottles/blob/master/src/ui/window.ui#L76 to `false`, which disables the gesture to swipe back with a touchpad.
In my opinion this would be a worthy tradeoff, or at least a workaround.
