### ISSUE TITLE
[Bug]: Wrong close button placement.

### ISSUE THREAD

**Issue by Khayasen** [bottlesdevs/Bottles#1647]
### Describe the bug

The close button is placed in the 1/4 corner of the window bar, it should be placed on the most left alongside back button.

### To Reproduce

1. Open GNOME Tweaks
2. Change window button to just close and move it to the left
3. Open Bottles
4. Open a bottle
5. See the error.

![Screenshot from 2022-06-17 16-03-31](https://user-images.githubusercontent.com/103806906/174265882-149be824-f6f8-4f6c-ae77-dfd0aa8d05d6.png)

### Package

Flatpak from Flathub

### Distribution

Fedora 36 - Workstation

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.5-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 2986004480
    Free: 2985861120
RAM:
    MemTotal: 5.6GiB
    MemAvailable: 2.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by jannuary** [comment]
This is fixed in master.
