### ISSUE TITLE
[Bug] Bottles can't change runners or takes too long.

### ISSUE THREAD

**Issue by juampiursic** [bottlesdevs/Bottles#1649]
### **Describe the bug**

When choosing another runner from the menu, Bottles takes too long to change it, doesn't change it and sometimes it just freezes the app.

### **To Reproduce**

Open a Bottle, get to Settings, Runners, choose other than the one you're using.

### **Package**

Flatpak from Flathub

### **Distribution**

Fedora 36

**### Health Check**

> Version: 2022.6.14-brescia
> Display:
>     X.org: true
>     X.org (port): :99.0
>     Wayland: false
> Graphics:
>     vendors:
>         nvidia:
>             vendor: nvidia
>             envs:
>                 __NV_PRIME_RENDER_OFFLOAD: '1'
>                 __GLX_VENDOR_LIBRARY_NAME: nvidia
>                 __VK_LAYER_NV_optimus: NVIDIA_only
>             icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
>     prime:
>         integrated: null
>         discrete: null
> Kernel:
>     Type: Linux
>     Version: 5.17.13-300.fc36.x86_64
> Distro:
>     Name: GNOME
>     Version: '"42 (Flatpak runtime)"'
> Disk:
>     Total: 16765243392
>     Free: 16765087744
> RAM:
>     MemTotal: 31.2GiB
>     MemAvailable: 24.8GiB
> Tools:
>     cabextract: true
>     p7zip: true
>     patool: true
>     glibc_min: '2.33'
> Bottles_envs: null

### **Display Protocol**

X11

### **Display Backend used by Bottles**

X11

**### Additional context**

https://user-images.githubusercontent.com/6501647/174406763-4d3cfa9a-d843-4d59-9aaf-abd6dbfe874d.mp4

**Comment by mirkobrombin** [comment]
Not able to replicate (Silverblue 36)

**Comment by juampiursic** [comment]
It's always been like this. It supposed to be instant? 

```
Arch: win64
Creation_Date: '2022-06-17 20:20:31.448668'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.10.1
Environment: Gaming
Environment_Variables: {}
External_Programs:
    EpicGamesLauncher.exe:
        arguments: -opengl -SkipBuildPatchPrereq
        executable: EpicGamesLauncher.exe
        name: Epic Games Store
        path: C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- riched20
- andale32
- arialb32
- comic32
- georgi32
- impact32
- tahoma32
- trebuc32
- verdan32
- webdin32
- allfonts
- vcredist2015
LatencyFleX: latencyflex-v0.1.0
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.4
Name: Epic Games Store
Parameters:
    custom_dpi: 96
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: true
    fixme_logs: false
    fsr: true
    fsr_level: 2
    fullscreen_capture: false
    gamemode: true
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: true
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: true
    renderer: gdi
    sync: esync
    take_focus: false
    use_runtime: false
    use_steam_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
Path: Epic-Games-Store
Runner: lutris-GE-Proton7-16-x86_64
State: 0
Uninstallers:
    allfonts: true
    andale32: false
    arial32: false
    arialb32: false
    comic32: false
    courie32: false
    d3dcompiler_43: false
    d3dcompiler_47: false
    d3dx9: false
    georgi32: false
    impact32: false
    msls31: false
    riched20: false
    tahoma32: false
    times32: false
    trebuc32: false
    vcredist2015: true
    verdan32: false
    webdin32: false
Update_Date: '2022-06-18 04:01:30.492294'
VKD3D: vkd3d-proton-2.6
Versioning: false
Windows: win10
WorkingDir: ''
```

**Comment by ghtesting2020** [comment]
> It's always been like this. It supposed to be instant?
> 
> ```
> Arch: win64
> Creation_Date: '2022-06-17 20:20:31.448668'
> Custom_Path: false
> DLL_Overrides: {}
> DXVK: dxvk-1.10.1
> Environment: Gaming
> Environment_Variables: {}
> External_Programs:
>     EpicGamesLauncher.exe:
>         arguments: -opengl -SkipBuildPatchPrereq
>         executable: EpicGamesLauncher.exe
>         name: Epic Games Store
>         path: C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe
> Installed_Dependencies:
> - d3dx9
> - msls31
> - arial32
> - times32
> - courie32
> - d3dcompiler_43
> - d3dcompiler_47
> - riched20
> - andale32
> - arialb32
> - comic32
> - georgi32
> - impact32
> - tahoma32
> - trebuc32
> - verdan32
> - webdin32
> - allfonts
> - vcredist2015
> LatencyFleX: latencyflex-v0.1.0
> Latest_Executables: []
> NVAPI: dxvk-nvapi-v0.5.4
> Name: Epic Games Store
> Parameters:
>     custom_dpi: 96
>     discrete_gpu: true
>     dxvk: true
>     dxvk_hud: false
>     dxvk_nvapi: true
>     fixme_logs: false
>     fsr: true
>     fsr_level: 2
>     fullscreen_capture: false
>     gamemode: true
>     gamescope: false
>     gamescope_borderless: false
>     gamescope_fps: 0
>     gamescope_fps_no_focus: 0
>     gamescope_fullscreen: true
>     gamescope_game_height: 0
>     gamescope_game_width: 0
>     gamescope_scaling: false
>     gamescope_window_height: 0
>     gamescope_window_width: 0
>     latencyflex: false
>     mangohud: true
>     mouse_warp: true
>     obsvkc: false
>     pulseaudio_latency: true
>     renderer: gdi
>     sync: esync
>     take_focus: false
>     use_runtime: false
>     use_steam_runtime: false
>     virtual_desktop: false
>     virtual_desktop_res: 1280x720
>     vkbasalt: false
>     vkd3d: true
> Path: Epic-Games-Store
> Runner: lutris-GE-Proton7-16-x86_64
> State: 0
> Uninstallers:
>     allfonts: true
>     andale32: false
>     arial32: false
>     arialb32: false
>     comic32: false
>     courie32: false
>     d3dcompiler_43: false
>     d3dcompiler_47: false
>     d3dx9: false
>     georgi32: false
>     impact32: false
>     msls31: false
>     riched20: false
>     tahoma32: false
>     times32: false
>     trebuc32: false
>     vcredist2015: true
>     verdan32: false
>     webdin32: false
> Update_Date: '2022-06-18 04:01:30.492294'
> VKD3D: vkd3d-proton-2.6
> Versioning: false
> Windows: win10
> WorkingDir: ''
> ```

it has never been instant for me using Bottles for 9 months now. If you run Bottles with Terminal open you can see dozens or hundreds of modifications happening when you click a different runner so it makes sense it will take time. I do not know how much time normal but for me it takes a little over a minute when switching runners.

**Comment by mirkobrombin** [comment]
It should take like 20s

**Comment by Hyphaed** [comment]
Could you add an icon to open/show a terminal line with has is going on, not only the icon spinning ?

I guess that will help many

I agree it takes too long and it makes the sensation that something is not working properly 

thanks for the great work you are doing
