### ISSUE TITLE
Problems scrolling in settings

### ISSUE THREAD

**Issue by Somaxa8** [bottlesdevs/Bottles#1651]
I was configuring a bottle but I have the problem that when I am in the configuration and I accidentally scroll many selects end up changing value, the select should not react to the mouse scroll because otherwise it is very annoying.

**Comment by ghtesting2020** [comment]
is what you are experience the same as  this issue? https://github.com/bottlesdevs/Bottles/issues/843
if yes it is a regression as it was fixed 6 months ago.

**Comment by jannuary** [comment]
It is a regression introduced with the GTK4 port, specifically [9a6e5d4](https://github.com/bottlesdevs/Bottles/commit/9a6e5d45f53d2cebdaedb2167468ecce576330ca).

**Comment by mirkobrombin** [comment]
I was not able to make our workaround works after the switch

**Comment by jannuary** [comment]
Yeah, because we need to fix #454 instead :)

**Comment by mirkobrombin** [comment]
So tracking there https://github.com/bottlesdevs/Bottles/issues/454
