### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'get_path'

### ISSUE THREAD

**Issue by g3434343** [bottlesdevs/Bottles#1653]
### Describe the bug

Then I try to open an .exe file or any other program, I get the following error:
(bottles:2): Gtk-WARNING **: 08:53:36.095: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/bottle_details.py", line 207, in __execute
    exec_path=_file.get_path(),
AttributeError: 'NoneType' object has no attribute 'get_path'

It was working. It simply happened.

### To Reproduce

1. Try to run an app using a terminal

### Package

Flatpak from Flathub

### Distribution

Pop-Os 22.04

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-76051705-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8362508288
    Free: 8362364928
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 9.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
`unsupported windowing system` seems like your system window manager is missing something. I can't fix, I'll just avoid the exception.

Which DE/WM is?

**Comment by g3434343** [comment]
I'm using Xfce.

Em dom, 19 de jun de 2022 às 07:07:25 -0700, Mirko Brombin 
***@***.***> escreveu:

**Comment by mirkobrombin** [comment]
I'll setup a VM asap

**Comment by g3434343** [comment]
This is odd. I'm using Bottles for two years now. If there's anything I 
can do, let me know.

Em dom, 19 de jun de 2022 às 07:11:31 -0700, Mirko Brombin 
***@***.***> escreveu:

**Comment by mirkobrombin** [comment]
We moved from GTK3 to GTK4, maybe xfce is not updated. Does the file dialog show?

**Comment by g3434343** [comment]
Somebody told me it's related to wayland. I'm using X11. Xfce has no support for wayland afaik. I don't trust gnome at all (no recommended for privacy). I'll try to switch to pop-os desktop (gnome based) and see what I can come up with or maybe use cinnamon which sucks less.

**Comment by mirkobrombin** [comment]
In which way GNOME would be “not recommended for privacy”?

**Comment by g3434343** [comment]
> In which way GNOME would be “not recommended for privacy”?

https://www.gnome.org/privacy-policy/
https://fosspost.org/privacy-security-concern-regarding-gnome-software/

But you're free, of course, to use any DE you like. I recommend you start reading and watching Techlore's stuff because I've learned a lot about privacy. Also, snaps are not safe to use, as it was audited too. I'd rather not use a distro if I'm forced to use Gnome, for instance (I don't know if this is possible lol). I usually use Xfce, sometimes Openbox, i3-gaps.

**Comment by jannuary** [comment]
>https://www.gnome.org/privacy-policy/
https://fosspost.org/privacy-security-concern-regarding-gnome-software/

Have you read either?
