### ISSUE TITLE
[Request]: Additional installer Options

### ISSUE THREAD

**Issue by UniqueName992** [bottlesdevs/Bottles#1658]
### Tell us the problem or your need

Currently the available installer yaml steps offers a few functions for automating installations, but more are needed to automate complicated installs.
I want to create an installer where command line interaction is required (msiexec) and a zip utility is needed.

### Describe the solution you'd like

Add additional supported steps in the installer yaml to allow installers to: 
- unzip downloaded resources 
- run commands in windows cmd.exe

### Other solutions?

Not automating this installation process for more complicated installs.

### Additional context and references

Revu BluBeam (https://www.bluebeam.com/solutions/revu/) can be installed with bottles, but the steps require calling msiexec from command line as using the included bottles MSI installer fails with this file, and the deployment MSI packages provided from the company are ZIP'd.

I'd like to publish an installer for this software, but need the requested functionality adding to the yaml parser.

**Comment by mirkobrombin** [comment]
For advanced tasks: 
- [run_script](https://maintainers.usebottles.com/installers/structure/Actions#title7)
- [run_winecommand](https://maintainers.usebottles.com/installers/structure/Actions#title10)
