### ISSUE TITLE
[Request] Ability to drag'n'drop exe to bottle to start it

### ISSUE THREAD

**Issue by soredake** [bottlesdevs/Bottles#166]
**Is your feature request related to a problem? Please describe.**
Would be nice to have ability to drag and drop exe to bottle to start it.

**Describe the solution you'd like**
Having ability to drag and drop exe to interface.

**Describe alternatives you've considered**

**Additional context**

**Comment by mirkobrombin** [comment]
This is a feature I absolutely want in Bottles but will be talked about in v4. #133

**Comment by sonnyp** [comment]
Should behave like #437 IMHO 

---

Flatpak only:

Beware that it won't work with GTK 3 file managers, including GNOME Files

Long story short, support for this under Flatpak has landed in GTK4 but has not been back-ported to GTK 3.

See https://github.com/flatpak/xdg-desktop-portal/issues/99#issuecomment-565264246

**Comment by mirkobrombin** [comment]
> Should behave like #437 IMHO
> 
> Flatpak only:
> 
> Beware that it won't work with GTK 3 file managers, including GNOME Files
> 
> Long story short, support for this under Flatpak has landed in GTK4 but has not been back-ported to GTK 3.
> 
> See [flatpak/xdg-desktop-portal#99 (comment)](https://github.com/flatpak/xdg-desktop-portal/issues/99#issuecomment-565264246)

Bottes Trento GTK client will use GTK4. Currently Flatpak is the most used Bottles package, so I think is reasonable to wait for Trento

**Comment by sonnyp** [comment]
What I meant is that the application you are dragging the file from also needs to be GTK4.

**Comment by mirkobrombin** [comment]
> What I meant is that the application you are dragging the file from also needs to be GTK4.

Oh I got it, this is a huge limitation

**Comment by TheEvilSkeleton** [comment]
This could come in handy: https://github.com/refi64/flatpod

**Comment by TheEvilSkeleton** [comment]
This could come in handy: https://developer.gnome.org/documentation/tutorials/drag-and-drop.html.
