### ISSUE TITLE
[Bug]: Bottles isn't in Dark Mode anymore

### ISSUE THREAD

**Issue by KiritoStorm** [bottlesdevs/Bottles#1661]
### Describe the bug

I use bottles for maybe a month now, since the latest update the system dark mode isn't detected anymore.
Is there a way to fix it for myself?

### To Reproduce

Launch the bottles flatpak on 

### Package

Flatpak from Flathub

### Distribution

Zorin OS 16.1

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-51-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8348147712
    Free: 8347983872
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 6.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by jannuary** [comment]
Intentional behavior - new release uses the new dark preference API, that Zorin isn't compatible with.

If you really need it, you might want to try [this](https://gitlab.gnome.org/exalm/color-scheme-simulator).
