### ISSUE TITLE
[Bug]: Night Light mode get's disabled when starting EA Launcher 

### ISSUE THREAD

**Issue by KiritoStorm** [bottlesdevs/Bottles#1662]
### Describe the bug

I just installed the EA Launcher and I realised that the night light mode get's disabled when launching the application.
In Zorin it is still shown as enabled but needs to be toggled to be active again.

### To Reproduce

1. Active Night Mode in System Settings (Displays -> Night Light)
2. Install EA Launcher (from the Installers)
3. Start the EA Launcher

### Package

Flatpak from Flathub

### Distribution

Zorin OS 16.1

### Health Check

```shell
Version: 2022.6.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-51-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8348147712
    Free: 8347983872
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 6.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting.

Unfortunately there is nothing we can do, Bottles does not handle the dark mode of the system in any way and this seems an anomalous behavior of the system itself.
