### ISSUE TITLE
Speed up launch time or make bottles do Catalog checks on pc boot in background once?

### ISSUE THREAD

**Issue by XDM-Inc** [bottlesdevs/Bottles#1674]
i like bottles but one of my issues is that every time you launch the bottles app or a app pertaining to bottles theirs a 4-5 second loading screen every time you start it. i have some windows apps that i need to open and close VERY frequently throughout my workday as some of the apps im using need one to be closed for the other to work. but the wait time becomes unbearable after a while.
when launching through the terminal i see that it check a online database or catalog before launching

the terminal output...
`07:04:53 (INFO) Bottles Started! 
07:04:56 (INFO) Catalog components loaded 
07:04:56 (INFO) Catalog installers loaded 
07:04:56 (INFO) Catalog dependencies loaded `

and this is the slowdown, when disabling internet access via flatseal bottles loads LIGHTING fast as it should but obviously without the ability to download anything internal or update runners.
perhaps a option to disable Catalog loading or to have this happen on pc boot or in the background?

**Comment by mirkobrombin** [comment]
Tracking solution here https://github.com/bottlesdevs/Bottles/issues/439
