### ISSUE TITLE
Developer documentation for building and testing needed

### ISSUE THREAD

**Issue by jntesteves** [bottlesdevs/Bottles#1676]
I've just made changes to code and would like to try them, but I couldn't find any developer docs, not even on the CONTRIBUTING file. I would prefer to test in Flatpak, since that's usually easier to build in my experience (fewer dependencies necessary on the root OS). That's probably just a few commands you can copy from your bash history and paste in a doc somewhere.

**Comment by mirkobrombin** [comment]
Che Manual build under Flatpak: https://docs.usebottles.com/getting-started/installation
