### ISSUE TITLE
[BUG] chardonnay-6.3-unstable runner can be downloaded even though its already installed

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/Bottles#168]
**Describe the bug**
The chardonnay-6.3-unstable runner can be downloaded even though its already installed. It installed successfully and can be selected in an bottle.

**Installation**
 - Method: Flatpak
 - Version 3.0.7

**To Reproduce**
Steps to reproduce the behaviour:
1. Start bottles and click the hamburger menu Icon.
2. Click on 'Preferences'.
3. Scroll down to 'Wine Runners'.
4. Download the 'chardonnay-6.3-unstable' runner.
5. Close bottles and restart it.
6. Click on 'Preferences'.
7. Scroll down to 'Wine Runners'.
8. The 'chardonnay-6.3-unstable' runner can be downloaded again even though it is already there.

**Expected behaviour**
The 'chardonnay-6.3-unstable' runner can not be downloaded again as it is already there.

**Desktop:**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
This should disappear if you restart bottles after the installation. This is a know bug

**Comment by mirkobrombin** [comment]
Should be fixed
