### ISSUE TITLE
How to run with parameters?

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1685]
I am very excite to try the new parameters to improve speed and benechmark.

"FORCE_OFFLINE=1 can be used to force-launching Bottles in offline mode
BOOT_TIME=1 can be used to benchmark Bottles' boot"

how do I do? When I try running via terminal I get

```
flatpak run com.usebottles.bottles FORCE_OFFLINE=1

(process:3): Gtk-WARNING **: 17:53:34.364: Locale not supported by C library.
        Using the fallback 'C' locale.
Invalid URI (syntax: bottles:run/<bottle>/<program>)

flatpak run com.usebottles.bottles --FORCE_OFFLINE=1

(process:3): Gtk-WARNING **: 17:54:37.539: Locale not supported by C library.
        Using the fallback 'C' locale.
Unknown option --FORCE_OFFLINE=1
```

Can you expose these as settings inside Bottles for us not tech savvy? Like it would say "start offline" requires restart

**Comment by mirkobrombin** [comment]
`FORCE_OFFLINE=1 flatpak run com.usebottles.bottles`
