### ISSUE TITLE
[Bug]: Сommands for flatpak from the documentation only work with sudo

### ISSUE THREAD

**Issue by boris-gu** [bottlesdevs/Bottles#1686]
### Describe the bug

This
https://docs.usebottles.com/bottles/programs#flatpak
and this
https://docs.usebottles.com/bottles/programs#flatpak
only works with sudo. Is this normal behavior?

### To Reproduce

1. Try running the command from the documentation. Output: Permission denied
2. Try running the command with sudo. It works

### Package

Flatpak from Flathub

### Distribution

Manjaro

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.49-1-MANJARO
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 6205644800
    Free: 6205497344
RAM:
    MemTotal: 11.6GiB
    MemAvailable: 7.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
It’s related to your system. Did you install it as root? Try removing and install using the —user flag. 

Closing as non-bug, feel free to add more comments.
