### ISSUE TITLE
[BUG] chardonnay-6.3-unstable runner can only be selected in bottles if bottles gets restarted

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/Bottles#169]
**Describe the bug**
The chardonnay-6.3-unstable runner can only be selected in bottles if bottles gets restarted. After installing chardonnay-6.3-unstable via the preferences menu and creating a bottle afterwards, the runner cannot be selected in the bottle till bottles gets restarted. It also missed the 64bit version and only showed the 32bit version.

**Installation**
 - Method: Flatpak
 - Version 3.0.7

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the hamburger menu icon.
2. Click on 'Preferences'.
3. Scroll down to 'Wine Runners'.
4. Install the chardonnay-6.3-unstable runner.
5. Close the menu and go to the main screen.
6. Create a bottle. I used the gaming environment.
7. Click on the newly created bottle.
8. Click on 'Preferences' in the header bar.
9. Scroll to 'System'.
10. Click on 'Runner' (not the cog wheel).
11. The chardonnay-6.3-unstable runner should be available in the 32bit and 64bit version, but it isn't.

**Expected behaviour**
The chardonnay-6.3-unstable runner should be available in the 32bit and 64bit version in the menu.

**Desktop:**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
Same bug #168
