### ISSUE TITLE
[Request]: Dedicated "Hide GPU" or "Report AMD GPU" switch

### ISSUE THREAD

**Issue by timocapa** [bottlesdevs/Bottles#1694]
### Tell us the problem or your need

Some games / applications can have issues when a NVIDIA GPU is reported (Not sure if this exists on AMD GPUs too where they need a NVIDIA GPU, maybe add possibility to report either / or)

Example: Battlefield 5 cripples FPS on NVIDIA with "Post Processing Quality" set above Medium

### Describe the solution you'd like

Switch to report an AMD GPU (maybe opposite for AMD users too, if needed)

### Other solutions?

Mirko proposed a DXVK configurator in the Telegram chat.

### Additional context and references

The Battlefield 5 Lutris installer reports an AMD GPU, see: https://lutris.net/games/install/10065/view

Some NVIDIA user reports over at protondb: https://www.protondb.com/app/1238810

**Comment by mirkobrombin** [comment]
An integrated DXVK configuration should be the way to go.
