### ISSUE TITLE
[Crash report]  'NoneType' object is not sub Can I get help? steam deck

### ISSUE THREAD

**Issue by swoozi** [bottlesdevs/Bottles#1696]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.6.28-brescia

**Log**
```python3
'NoneType' object is not subscriptable  File "/app/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1137, in create_bottle
    template = TemplateManager.get_env_template(environment)

  File "/app/share/bottles/bottles/backend/managers/template.py", line 154, in get_env_template
    if template["env"] == env.lower():

```

**Comment by mirkobrombin** [comment]
Seems like your template is damaged an Bottles is not handling the behavior. Can you try removing the templates folder? In ~/.var/app/com.usebottles.bottles/data/bottles/

**Comment by mirkobrombin** [comment]
Just pushed a fix but removing the templates folder should do the trick. Let me know. If the problem persist I'll send an hotfix
