### ISSUE TITLE
[Bug]: Mismatch in override-dlls as configured in Bottles and wine-cfg

### ISSUE THREAD

**Issue by Eonfge** [bottlesdevs/Bottles#1697]
### Describe the bug

Here a short overview of a Gaming prefix that I've created for an older game: C&C Generals. Since the game uses dxd8 and some mods use that to inject extensions, I wanted to add the dxd8.dll to the overrides list.

To my surprise, the Bottles config-panel does in no way reflect (or affact) the actual wine-cfg config

![Screenshot from 2022-06-29 21-42-42](https://user-images.githubusercontent.com/33983090/176526220-79fba7e5-7f99-4fd8-8163-d5b839ffd5f5.png)

### To Reproduce

1. Create a gaming prefix
2. Add a custom dll to the override list (netive, build-in)
3. See the mismatch when opening wine-cfg

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.6-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16730660864
    Free: 16730517504
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 27.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

**Comment by mirkobrombin** [comment]
DLL Overrides in bottles preferences are stored in your bottle configuration and used on-fly trough environment variables. Winecfg is there only because some features are not already available in our UI but should not be used for what it's already in the UI.
