### ISSUE TITLE
[Bug]: Cannot save files in shared directory

### ISSUE THREAD

**Issue by cbmeeks** [bottlesdevs/Bottles#1699]
### Describe the bug

I've installed Bottles on Fedora 36 via Flatpak. 

I've setup an application to use a mapped drive that points to a folder outside of my /home directory.
For example, my "G" drive maps to "/data/Dropbox/projects".

I can read files just fine within the app but when writing to the G drive, I get access denied.

Any ideas what I can do to fix this?
Thanks.

### To Reproduce

1. Create mapped drive outside ~/ directory
2. Attempt to save files with an app

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.6-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16393375744
    Free: 16393232384
RAM:
    MemTotal: 30.5GiB
    MemAvailable: 23.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Did you give Bottles permanent permissions to access that path?

**Comment by cbmeeks** [comment]
Not sure how to do that.

**Comment by mirkobrombin** [comment]
flatpak override --user --filesystem="/full/path" com.usebottles.bottles

**Comment by cbmeeks** [comment]
Ah thanks.  I actually already have flatseal and I went through all configs looking for some kind of "permanent" setting or something that sets permissions but couldn't find it.  I will give that command a try.

**Comment by cbmeeks** [comment]
In fact, here is my setting in Flatpak:

![image](https://user-images.githubusercontent.com/49341/176892079-476c55c2-40c2-4cac-813a-eade77fd8500.png)

I have that path mounted to the G drive but none of my Win apps can modify that path.

**Comment by axtloss** [comment]
Are you able to create files in that directory manually? It could be that you just don't have privileges to write in that mountpoint.

**Comment by mirkobrombin** [comment]
Closing due to no reponse/
