### ISSUE TITLE
Which is more secure ?

### ISSUE THREAD

**Issue by Nokia808** [bottlesdevs/Bottles#170]
Hello.

Which is more secure: create independent bottle (WINEPREFIX) for every Windows application/game or it is not a matter ?

Usual use is create bottle for each specific Windows environment like bottle for Windows XP compatible software that not work with other Windows version, bottle for Windows 7 compatible software, ....... & so on.

But regarding risk of possibility to run viruses, does run each application/game in independent bottle (set independent bottle per each application/game) will decrease possible damage or not ?

Thank you.

**Comment by mirkobrombin** [comment]
Please use the "[Discussions](https://github.com/bottlesdevs/Bottles/discussions)" sections for questions like this.
The risk is about the same, the disc is always the same. However these are questions you should ask the Wine development team.
