### ISSUE TITLE
[Bug]: mscoree.dll disabled after installing Mono

### ISSUE THREAD

**Issue by Eonfge** [bottlesdevs/Bottles#1701]
### Describe the bug

In a follow-up of https://github.com/bottlesdevs/Bottles/issues/1697, I think I found a related bug that I couldn't pin-point first.

When a user installs the Mono-dependency, there is still an error when trying to run an application:

```
010c:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"WarZone.exe" cannot be loaded
010c:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\TW Warzone Fin\\WarZone.exe" failed, status c0000135
```

### To Reproduce

1. Install a C&C game like[ War Zone that uses a .NET wrapper](https://www.moddb.com/mods/tiberian-sun-warzone/downloads/tiberian-war-warzone)
2. Enable the Mono-dependency
3. start the application

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.7-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16730660864
    Free: 16730517504
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 27.9GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

**Comment by VarLad** [comment]
Same issue for TMNT Shredder's Revenge

**Comment by davidmartos96** [comment]
+1 When installing Magic the Gathering Arena on Fedora 36

**Comment by M-Mabrouk1** [comment]
Same issue with logitech GHUB.

**Comment by mirkobrombin** [comment]
There could be a mistake in the dependency manifest
