### ISSUE TITLE
Merge conflict on Weblate

### ISSUE THREAD

**Issue by flipflop97** [bottlesdevs/Bottles#1703]
There's a merge conflict on Hosted Weblate. Translations are not updating because of this.

https://hosted.weblate.org/projects/bottles/bottles/#alerts

**Comment by flipflop97** [comment]
Thanks for fixing!

**Comment by flipflop97** [comment]
There's a merge conflict on Weblate again because it can't push to master. Was this branch recently renamed to main?

**Comment by mirkobrombin** [comment]
Ops

**Comment by mirkobrombin** [comment]
Fixed
