### ISSUE TITLE
[Bug]: Cannot capture a game using the OBS Vulkan Capture option

### ISSUE THREAD

**Issue by kozross** [bottlesdevs/Bottles#1704]
### Describe the bug

When I try to run a game inside a bottle with the 'OBS Vulkan Capture' option enabled, OBS does not capture the game.

### To Reproduce

1. Install any game that can use DXVK (that is, runs on DirectX 10 or 11) into a bottle.
2. Go to 'Preferences' and toggle the 'OBS Vulkan Capture' option to on.
3. Start the game.
4. Try to use 'Game Capture' in OBS to capture the footage.
5. Observe that it fails.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.7-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16776712192
    Free: 16776564736
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 26.3GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

This may be an issue with the capture plugin itself; the reason I am reporting this is because this used to work before, on a very similar game, in a prior Bottles version, but seems to not work any more.

**Comment by kozross** [comment]
Further note: this is _definitely_ a regression _somewhere_. I just tried running the old game where capture used to work, and it no longer works, in a similar way to the above.

**Comment by mirkobrombin** [comment]
We changed nothing on this

**Comment by kozross** [comment]
@mirkobrombin - how does that option currently work? I have a suspicion, based on [documentation for the plugin](https://github.com/nowrep/obs-vkcapture#usage) that the old envvar option no longer works.

**Comment by mirkobrombin** [comment]
I thought it was using that syntax, I’ll fix with the next release. Can you test through launch options?

**Comment by kozross** [comment]
@mirkobrombin I just checked: if you use `obs-vkcapture command`, it works flawlessly, but using the old envvar, it doesn't.

**Comment by mirkobrombin** [comment]
Do you have mangohud, gamescope or Gamemode enabled?

**Comment by kozross** [comment]
I definitely don't.

**Comment by kozross** [comment]
Sorry for the delay. I've just set up a brand new, clean bottle, installed ToCS3 into it, then tried to capture it into OBS. I basically get the exact same problem (can't capture anything) if I use the built-in support, while if I use `obs-vkcapture %command%`, I get double Wine desktop again.

I genuinely am quite confused at this point, since nobody seems to be able to replicate this issue but me.

**Comment by axtloss** [comment]
My tests all were on wayland, maybe it's a problem with the game you're testing?

**Comment by kozross** [comment]
@axtloss I tried recording a game I previously had no issue with: same deal.

**Comment by axtloss** [comment]
This is really weird, could it maybe be an issue with obs-vkcapture itself and not with bottles?

**Comment by kozross** [comment]
@axtloss That's probably not it either. Steam games capture just fine.

**Comment by Jookia** [comment]
I did a lot of debugging today and found a way to reproduce this: Enable Wine's virtual desktop feature.

**Comment by kozross** [comment]
To extend what @Jookia said above: this happens _regardless_ of how you virtualize. I tried doing this using _both_ virtual desktop settings via `winecfg`, as well as the builtin option in Bottles itself: same effect.

**Comment by axtloss** [comment]
Then this is not a bottles issue, the wine virtual desktop doesn't use Vulkan and also isolates any window in it, which is why obs can't capture it.

**Comment by Jookia** [comment]
But if you switch back and forth it can capture just fine.

**Comment by axtloss** [comment]
You mean the capture works when disabling the virtual desktop and re-enabling it?

**Comment by Jookia** [comment]
Yes.

**Comment by mirkobrombin** [comment]
Double-check the program launch options to make sure the virtual desktop is not overwritten

**Comment by Jookia** [comment]
How do you check this? I'm fairly sure it's not overwritten. Though I'm
not sure what that means.

**Comment by mirkobrombin** [comment]
Your programs > the chosen program > launch options > overrides

**Comment by Jookia** [comment]
I'm fairly sure unless it gets overriden by the virtual desktop option. Just switching the virtual desktop off then on makes it able to capture again.

**Comment by kozross** [comment]
@axtloss Also, before I hit this issue, I could capture games in a virtual desktop just fine.
