### ISSUE TITLE
[Bug]: unable to launch an executable from a prefix with a colon in the name

### ISSUE THREAD

**Issue by dariox86** [bottlesdevs/Bottles#1709]
### Describe the bug

Bottles is unable to launch an executable from a bottle with a colon in the name. Perhaps this is not allowed because in some Windows version and/or filesystems «:» is an illegal character and the directory of the bottle is created with a colon in the name.

### To Reproduce

1. Download [Smile Guide: The Apple Escape](https://krainagrzybowtv.itch.io/smileguide).
2. Create a bottle with the name «Smile Guide: The Apple Escape». Note the «:» character in the name.
3. Place the executable of the game SmileGuide.exe in a directory inside the bottle. The game needs no installation.
4. Try to launch the executable. You will see that bottles is unable to launch the file.

If I do the same without «:» in the name of the bottle, the game starts successfully.

### Package

Flatpak from Flathub

### Distribution

Parabola GNU/Linux-libre

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.8-xanmod1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8343527424
    Free: 8343384064
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by axtloss** [comment]
I've tried to recreate this issue, but bottles won't let me create a bottle with a colon in the name:

![image](https://user-images.githubusercontent.com/60044824/177011238-1d6bd278-b023-423f-a8ff-9a1e43e41126.png)

how did you create the bottle?

**Comment by dariox86** [comment]
Steps to reproduce:
1. Launch Bottles.
2. Click + button.
3. In the Name field type: _Smile Guide: The Apple Escape_. It will not let you go through.
4. Click Cancel button.
5. Click + button once more.
6. In the Name field type: _Smile Guide: The Apple Escape_. This time no error is raised.

**Comment by axtloss** [comment]
Yep, works when doing it the way you described it:
![image](https://user-images.githubusercontent.com/60044824/177012827-5c039407-31ee-4a0f-aabf-35ed485b17c4.png)
