### ISSUE TITLE
[Request]: Library mode cover

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1715]
### Tell us the problem or your need

I saw tweet today here https://nitter.net/usebottles/status/1543537821729816577#m can I put in request that we can add our own covers? Maybe you can restrict to certain pixel size maximum and file type png/jpg?

### Describe the solution you'd like

 it would work like click "select cover" button and then opens file picker dialogue

### Other solutions?

n/a

### Additional context and references

n/a

**Comment by mirkobrombin** [comment]
Already planned!

Merging with https://github.com/bottlesdevs/Bottles/issues/1277
