### ISSUE TITLE
[Bug]: Program -> Add Desktop Entry partly works on KDE Plasma

### ISSUE THREAD

**Issue by CuteTadpole** [bottlesdevs/Bottles#1722]
### Describe the bug

When adding desktop entry of some app, Bottles only add entry to Plasma Kickoff (Plasma Menu) -> Others, but not the shortcut to the desktop.

### To Reproduce

1. Go to any bottle with some installed application
2. Click 3 dots
3. Click "Add Desktop Entry"
4. See shortcut in menu and not on desktop

### Package

Flatpak from Flathub

### Distribution

Fedora 36 KDE Plasma spin

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.9-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 4052008960
    Free: 4051849216
RAM:
    MemTotal: 7.5GiB
    MemAvailable: 2.9GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by CuteTadpole** [comment]
Wouldn't it be better to clarify this by renaming "Add Desktop Entry" to "Add to applications menu" for example? I think that people migrating from Windows are expecting adding .desktop file not only to the app menu but to the actual desktop too.

**Comment by jannuary** [comment]
"Add to App Grid".

"Desktop Entry" was always kinda a jargonism based off how the ".desktop" extension is used, now that I think about it
