### ISSUE TITLE
[Bug]: Gamescope not detected

### ISSUE THREAD

**Issue by Sporknife** [bottlesdevs/Bottles#1723]
### Describe the bug

Gamescope toggle button is not enabled, which I assume indicates that gamescope is not installed.

### To Reproduce

1. Install bottles, gamescope and create a wine prefix
2. Go to current prefix settings -> Preferences
3. Try to enable gamescope

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.9-zen1-1-zen
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8318775296
    Free: 8318627840
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 6.3GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
You need to install gamescope from flatpak

**Comment by Sporknife** [comment]
> You need to install gamescope from flatpak

I feel stupid for not realizing that.

**Comment by mirkobrombin** [comment]
Don’t worry, it often happens 😂
