### ISSUE TITLE
[Request]: It should be possible to have Steam-like open source functionality by using Bottles as a Wine manager and flatpak as delivery method

### ISSUE THREAD

**Issue by MateusRodCosta** [bottlesdevs/Bottles#1731]
### Tell us the problem or your need

If you take a look at the recent developments like improved Wine due to Valve's work on Proton, Bottles simplifying managing wine installs and flatpak and Flathub working on paid applications support, it might make sense that basically pieces are getting in place to what should effectively allow Linux to have Steam Proton-like functionality for running Windows apps with optional paid and DRM support.

### Describe the solution you'd like

Well, the thoughts are that most of the pieces are in place.

- Bottles allow you to create bottles for each app you want, it also seems that there is already support for pre-made configs
- flatpak allows you to distribute apps either on flathub or your own repo, also there's the functionality of extensions for apps and runtimes
- flatpak has initial support on paid apps and apparently DRM, flathub will try to get them working in the future

It should be possible to package a Wwindows application/game as a flatpak application, running on a runtime provided by Bottles and Bottles would be the frontend to that.

Ideally the app/game itself would only be split into two pieces: Configuration (obrigatory, has dependency info and user can override settings) and Data (optional, ideally to only be used if the app can be redistributed, if not available user should manually run the installer). Optionally modification and other types of extension (for example, game mods) could be redistributed this way.

### Additional context and references

This would be just a tad bit more convenient for users that already use Bottles.

But, assuming the Steam Deck becomes increasingly popular, this should actually make for a increasingly better experience as it would allow lots of pre-packaged non-Steam apps/game to be more easily run.

Since the Steam Deck is also a pretty locked down platform (due to locked root and all that) and being focused on a console-like experience, that would also add lots of functionalities for those users.

---

**EDIT**: I have been informed that I am basically describing [winepak](https://github.com/winepak), except with the difference that now Bottles is used as a management tool for it.

**Comment by jannuary** [comment]
Not actionable.

**Comment by MateusRodCosta** [comment]
> I am not against the idea but it is not in the scope of the project.

@mirkobrombin Sure, I think I could try to implement this myself as some kind of separate project, would Bottles accept code allowing me to integrate that project if I end up doing it? (I am not really sure if Bottles has some kind of plugin system I could use)

**Comment by mirkobrombin** [comment]
I was thinking about a plugin system but not in the near future. You should be able to achieve it using bottles-cli
