### ISSUE TITLE
[Bug]: Arch linux aur bottles package out of date. 

### ISSUE THREAD

**Issue by prorounak2005** [bottlesdevs/Bottles#1747]
### Describe the bug

I use arch linux and in arch linux yay is constantly saying that bottles has been flagged as out of date - 
https://aur.archlinux.org/packages/bottles

```
[rounak@archissexy ~]$ yay
[sudo] password for rounak: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> nuclear-player-bin: local (1652230304092:2022511_c36a0119558e3a9f44a6465750f71030-2) is newer than AUR (2022627_267b920591069c3daa0652269aa20cb9-2)
 -> Flagged Out Of Date AUR Packages:  bottles
 there is nothing to do
[rounak@archissexy ~]$ 

```

### To Reproduce

NA 

### Package

AUR ("bottles" package)

### Distribution

Arch Linux x86_64 5.18.9-zen1-1-zen

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.9-zen1-1-zen
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 486350536704
    Free: 312995622912
RAM:
    MemTotal: 11.5GiB
    MemAvailable: 9.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Please fix it :'(

**Comment by axtloss** [comment]
This is a known issue that can't really be fixed since bottles relies on libadwaita 1,2 which isn't released yet and not in the arch repos. To get the newest bottles version you need to install it with flatpak, which has the right libadwaita version bundled in it.

**Comment by prorounak2005** [comment]
oh ok nvm

**Comment by ghost573** [comment]
[v1.2 alpha](https://gitlab.gnome.org/GNOME/libadwaita) is out apparently but I don't know if that's suitable for the aur package to be updated.

**Comment by axtloss** [comment]
nope, arch doesn't release libadwaita alpha versions, if you really want to use bottles from the aur, you can use bottles-git, which replaces the system libadwaita with libadwaita-git, which is at 1.2 alpha, but keep in mind that this can break stuff
