### ISSUE TITLE
[Request]: icoutils support or something similar?

### ISSUE THREAD

**Issue by Noobao** [bottlesdevs/Bottles#1753]
### Tell us the problem or your need

The default icons are a bit bland,i think it would look nicer if it went with the default themes of the exe,just like windows.

### Describe the solution you'd like

Use icoutils or something similar?Bottles should be able to do something like that easily,as seen by when we add exes to steam through it.

**Comment by jannuary** [comment]
Default icons of what? Default themes of what?

**Comment by mirkobrombin** [comment]
Bottles use icoextract to extract icons from executables since [2022.6.14](https://usebottles.com/blog/release-2022.6.14/) so actually this is already a thing. 

When you click on "create desktop entry" Bottles extract the executable icon/

**Comment by Noobao** [comment]
Sorry for not being clear enough,i'm talking about the option of being able to use the default ms windows icons,like when you decide to create a desktop entry, it extracts the executable icon and set's it as the icon in the desktop entry right?i was thinking of a option to add the icon when adding a game to programs,instead of leaving it blank like it is on the brescia version,or using the default theme for icons that comes with the current gtk theme of your choosing in the previous versions.

I thought that since there's already a icoextract implementation in bottles,this shouldn't be something hard to implement.

This is not an issue btw,just thought it would be a nice thing to add.

**Comment by Noobao** [comment]
Uh,maybe i didn't express myself correctly yet again.

I'm saying that it would be good to add the image iconextract extracts when adding a game to programs in bottles

For example,below here,we have the icon iconextract extracted from the game library of ruina
![LibraryOfRuina](https://user-images.githubusercontent.com/84132367/178379020-c27d8ac0-d131-469c-8d79-338be5ef4a0e.png)


But when i add the exe to bottles,the game either uses what is the default of my gtk theme 
 ![2022-07-11_21-04](https://user-images.githubusercontent.com/84132367/178378933-dcc23535-9991-425d-a5f3-bbb55973923c.png)

or just uses the name of the exe.
![image](https://user-images.githubusercontent.com/84132367/178380362-c5b33649-9db6-4662-913f-ad72896f515a.png)

What i'm asking for is a option to have the option to add a png to the icon in bottles when you add a game to programs,or something similar.

Preferably,when i add the game to programs,it would be nice if i could set it up with the icon extracted from iconextract.

**Comment by mirkobrombin** [comment]
Oh you are talking about the Bottles program’s view. Now I got it. 

Btw no, we already removed icons at all in such list (you are probably using and old version). For icons you should enable the Library mode which is currently experimental.
