### ISSUE TITLE
[Request]: Dark/Light mode select in settings on unsupported systems

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1758]
### Tell us the problem or your need

The Brescia update made Bottles not detecting my OS dark mode preference (Mint 20.3). Before it was even themed like other programs here. Maybe it would be a good idea to add a switch in settings that would force the Bottles to appear in a different theme? Then users would have easy access to changing it without effort.

### Describe the solution you'd like

To do this we would need a setting to choose your preferred theme. Something maybe like in YouTube app on android where you have 3 settings: a) Device theme (reads the theme used by your phone), b) light mode, c) dark mode. This way users can choose the theme on their own or leave it on first option for Bottles to detect the theme automatically.

### Additional context and references

https://support.google.com/youtube/answer/7385323?hl=en&co=GENIE.Platform%3DAndroid

**Comment by axtloss** [comment]
Bottles does still follow the system dark/light theme by using the [freedesktop appearance.color-scheme spec](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45), which linux mint doesn't seem to follow (might be something to report to the linux mint devs).
As for the custom light/dark mode chooser, there are applications like [extension manager](https://github.com/mjakeman/extension-manager) and [the gnome text editor](https://apps.gnome.org/app/org.gnome.TextEditor/) that have it implemented in different ways, so it definetly would be possible to implement that feature.

**Comment by mirkobrombin** [comment]
> Bottles does still follow the system dark/light theme by using the [freedesktop appearance.color-scheme spec](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45), which linux mint doesn't seem to follow (might be something to report to the linux mint devs).

^

---


I personally find that replicating this setting for each app is a waste of space and time. We follow the standard and the distribution / DE should do the same. Anyway you can still force dark mode via dconf: https://github.com/bottlesdevs/Bottles/blob/8af6ea3808ae2af6d27aac0ad79520e3598b60d7/data/com.usebottles.bottles.gschema.xml#L9

**Comment by mpaterakis** [comment]
Simple fix:

Open the terminal, write
> flatpak run --command=bash com.usebottles.bottles
Press enter, then write
> gsettings set com.usebottles.bottles dark-theme true
and finally
> exit
And press enter one last time.

Restart Bottles, enjoy dark mode. I guess this can be reverted by using "false" instead of "true" but don't quote me on that.
