### ISSUE TITLE
No way to change runner in lattest version of bottles

### ISSUE THREAD

**Issue by dr-nemesis-96** [bottlesdevs/Bottles#1759]
There seems to be no way to change runner in lattest release of bottles(2022.5.28-trento-3), there used to be one, if there is a way to change runner, please write how to do so in the documentation, it seems really confusing now

**Comment by mirkobrombin** [comment]
We changed the position like 6 releases ago, it is now in bottle preferences > components versions > runners

**Comment by dr-nemesis-96** [comment]
> We changed the position like 6 releases ago, it is now in bottle preferences > components versions > runners

nah not that, i know that i can install runner from there, but it seems in normal gaming bottle, i cannot change runner(yes i am using bottle after a long time)

**Comment by dr-nemesis-96** [comment]
@mirkobrombin

**Comment by mirkobrombin** [comment]
Change runner in an existing bottle
![image](https://user-images.githubusercontent.com/9479903/178658333-7e6f1448-7c88-4540-85a9-2617d426cd66.png)


Change runner for a new bottle
![image](https://user-images.githubusercontent.com/9479903/178658369-138c7fdf-982c-4803-a99f-f63c806855f3.png)

**Comment by dr-nemesis-96** [comment]
@mirkobrombin sorry i feel like i just wasted your time, thank you <3

**Comment by dr-nemesis-96** [comment]
@mirkobrombin alright i figured it is not proton only issue, i cannot seem to run epic games launcher no matter what, it says i have unsupported gpu, why tho?

**Comment by dr-nemesis-96** [comment]
i have a rx 570 , it should be capable of running epic games launcher

**Comment by axtloss** [comment]
You may have DXVK and/or VKD3D disabled, which makes epic games think that your gpu doesn't support some specific directx versions, causing it to error with that message. Maybe enabling both fixes it.

**Comment by dr-nemesis-96** [comment]
@axtloss [https://i.ibb.co/529115h/2022-07-13-06-02-40-screenshot.png](url)

**Comment by dr-nemesis-96** [comment]
i have that enabled

**Comment by dr-nemesis-96** [comment]
![2022-07-13-06:08:15-screenshot](https://user-images.githubusercontent.com/103036804/178708928-18cbbac1-ccb5-4dac-ad7f-24bee20376cf.png)
that didnt help

**Comment by dr-nemesis-96** [comment]
@axtloss welp :"(

**Comment by axtloss** [comment]
No I doubt that i3 is the issue, it either actually is an issue with your gpu or some wine issue
