### ISSUE TITLE
[BUG]para na segunda tela e não segue a diante. 

### ISSUE THREAD

**Issue by FabioSilvaIluminador** [bottlesdevs/Bottles#176]
**Describe the bug**

**Installation**
 - Method: [e.g. Appimage, Meson build, other]
 - Version [e.g. 877386d (find this in name file for Appimage)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 33]

**Additional context**

**Comment by mirkobrombin** [comment]
This is a blank issue
