### ISSUE TITLE
[Request]: Criação de garrafas em outros discos

### ISSUE THREAD

**Issue by PedroHenriqueMQ** [bottlesdevs/Bottles#1764]
### Tell us the problem or your need

Eu estou frustrado pelo motivo de que o Bottles não possui ferramenta para instalação de garrafas em outros discos. Meu disco principal não possui memória suficiente para instalar os programas ( e jogos ) que eu gostaria.

I'm frustrated that Bottles doesn't have a tool to install bottles on other disks. My main disk doesn't have enough memory to install the programs (and games) I'd like.

### Describe the solution you'd like

Eu gostaria que o Bottles pudesse instalar garrafas em outros discos e partições.

I wish Bottle could install bottles on other disks and partitions.

**Comment by mirkobrombin** [comment]
Per bottle

1. [Give bottle permission to reach new paths](https://docs.usebottles.com/flatpak/expose-directories)
2. Chose Custom environment while making a new bottle, then choose the custom path 
3. Switch to gaming or software or keep custom



 All bottles
1. Give bottles permission to reach the new path
2. Bottles > preferences > change the bottles path
3. Restart bottles
