### ISSUE TITLE
[Bug]: Opening Environment Variables menu of a second bottle breaks variable addition.

### ISSUE THREAD

**Issue by SvdB-nonp** [bottlesdevs/Bottles#1769]
### Describe the bug

I want to open existing bottle 1, create a variable. Then I want to open bottle 2 and create a variable there. However, adding a variable in bottle 2 then fails.

Doing the reverse, it works for bottle 2 and fails in 1. Hence it always is successful in the first bottle opened, but fails in the second.

### To Reproduce

- Open an existing bottle
- Go to the Environment Variables menu
- Go back and open another bottle
- Go to the Environment Variables menu

Here the first critical error is already popping up in terminal:
```
11:45:15 (INFO) No states found for bottle: [Biomutant] 
(bottles:2): Gtk-CRITICAL **: 11:45:19.921: gtk_widget_add_controller: assertion 'gtk_event_controller_get_widget (controller) == NULL' failed
```

- Type the name of the new variable
- Click the blue icon or hit enter key
- No variable is added

Final terminal output is:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/dialogs/envvars.py", line 109, in __save_var
    if not self.__valid_name:
AttributeError: 'EnvVarsDialog' object has no attribute '_EnvVarsDialog__valid_name'
```

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.10-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16730980352
    Free: 16730836992
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 27.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

xeyes fails to install, so couldn't check.

**Comment by axtloss** [comment]
I'm not able to replicate the issue, it may have been fixed in the new bottles release, which doesn't seem to be on flathub yet.
