### ISSUE TITLE
[BUG] a .exe that won't run (Foxit Reader)

### ISSUE THREAD

**Issue by rodneydup** [bottlesdevs/Bottles#177]
**Describe the bug**
Cannot open the setup .exe file for [Foxit Reader](https://www.foxitsoftware.com/downloads/pdf-reader-thanks.html?product=Foxit-Reader&platform=Windows&version=&package_type=&language=English&formId=download-reader)

**Installation**
 - Method: Flatpak
 - Version: 3.0.8

**To Reproduce**
1. Open bottles and go into a default software bottle
2. run .exe and select FoxitReader1011_Setup_Prom_IS.exe
3. nothing happens. But if running bottles from the terminal, the output is below.

**Expected behavior**
I'm not sure if this is a problem with wine or I need to configure the prefix better. Maybe this is too specific an issue to warrant attention, but maybe it reveals something bigger regarding Bottles, so I'm posting the issue anyway.

**Desktop (please complete the following information):**
 - OS: Debian 11

**Additional context**
For the record, I'm trying to install Foxit reader through wine because their Linux version crashes constantly. And there's no other (free) native linux pdf editor like Foxit. anyway...

Oh I also tried the Appimage version of Bottles but I encountered some strange crashes that blcoked me from even trying to replicate this.

**Comment by mirkobrombin** [comment]
Without a crash report or anything else it's hard to help you, I'll try it shortly on my PC.

However, I believe it is a problem of some dependency not related to bottles. What interests me particularly is the AppImage crash, do you have any logs of this?

**Comment by mirkobrombin** [comment]
This is the output thet pop up executing Foxit executable:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
  at System.Security.Principal.WindowsIdentity.get_Owner () [0x00000] in <7713cb95b33244ed9608bf0b23fbdce9>:0 
  at DotSetup.SingleInstance.NamedPipeServerCreateServer () [0x00042] in <d602683e72c04a5c812b3df4e5b2318d>:0 
  at DotSetup.SingleInstance..ctor (System.String appID) [0x0007f] in <d602683e72c04a5c812b3df4e5b2318d>:0 
  at DotSetup.DotSetupManager.ValidateSingleInstance () [0x00015] in <d602683e72c04a5c812b3df4e5b2318d>:0 
  at DotSetup.DotSetupManager.InitInstaller (System.String[] args, System.Reflection.Assembly assembly) [0x00012] in <d602683e72c04a5c812b3df4e5b2318d>:0 
```

After removing `mono` via Uninstaller and installing `dotnet40` from the dependencies tab:
```
0100:err:ole:CoGetContextToken apartment not initialised
0024:err:eventlog:ReportEventW L"Application: FoxitReader1011_Setup_Prom_IS.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.NotSupportedException\nStack:\n   at System.Net.ServicePointManager.set_SecurityProtocol(System.Net.SecurityProtoco"...

Unhandled Exception: System.NotSupportedException: The requested security protocol is not suppor
ted.
   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at DotSetup.Infrastructure.CommunicationUtils.EnableHighestTlsVersion()
   at DotWrapper.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 24 at address 000000007B036D36 (thread 0024), starting debugger...
```

There are some applications that don't work on Wine or that require an extreme tweak, I think it's one of them. I keep the issue open for information on the AppImage crash on Debian.

**Comment by mirkobrombin** [comment]
> I'm sorry, I was certain that I copied the output/crash report into my issue. I guess I need to proofread better. Indeed the output that you got was the same that I had.
> 
> Regarding the Appimage crash, the first thing that happened was the same as issue #156. apt installing "libhandy-1-dev" fixed that.
> 
> The crash I haven't seen reported here happened when I tried to click "Run .exe" in a bottle. It immediately crashed. Here is the full output:
> 
> ```
> 2021-03-10 10:47:32 INFO: Runners found: [chardonnay-6.3]
> 2021-03-10 10:47:32 INFO: Dxvk found: [dxvk-1.8.1]
> 2021-03-10 10:47:32 INFO: Connection status: online …
> 2021-03-10 10:47:32 INFO: Connection status: online …
> 2021-03-10 10:47:33 INFO: Connection status: online …
> 2021-03-10 10:47:33 INFO: Bottles found: bottle1
> 2021-03-10 10:47:34 INFO: Bottles Started!
> 2021-03-10 10:47:40 INFO: Setting Key: [sync] to [wine] for bottle: [bottle1] …
> 
> (bottles:28713): GLib-GIO-ERROR **: 10:47:42.605: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
> /tmp/.mount_BottlefcxF42/AppRun.wrapped: line 52: 28713 Trace/breakpoint trap   python3 $APPDIR/usr/bin/bottles $1
> ```

Ok this is the first time I see this error, I have to investigate.

**Comment by mirkobrombin** [comment]
Check if it has been fixed by the latest AppImage.

**Comment by rodneydup** [comment]
I'm not getting this crash anymore. Thanks!
