### ISSUE TITLE
[Crash report] Startup screen never proceeds after updating to 2022.7.14-brescia

### ISSUE THREAD

**Issue by Gert-dev** [bottlesdevs/Bottles#1774]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.7.14-brescia

**Log**
```python3
one of the hex, bytes, bytes_le, fields, or int arguments must be given  File "/app/share/bottles/bottles/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/window.py", line 234, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 133, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 190, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 813, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 745, in process_bottle
    uuid.UUID(k)

  File "/usr/lib/python3.9/uuid.py", line 171, in __init__
    raise TypeError('one of the hex, bytes, bytes_le, fields, '

```

**Comment by Gert-dev** [comment]
Not entirely sure what is wrong here, but the hang started happening right after updating to 2022.7.14, and did not occur before.

I have only about two or three bottles active.

**Comment by mirkobrombin** [comment]
I'm not able to replicate. Seems like there is a problem with 1 of your bottles.
Can you try closing bottles, renaming ~/.var/app/com.usebottles.bottles/data/bottles/bottles in something else and make a new bottle?

If it works in this way we can investigate your bottles confs

**Comment by mirkobrombin** [comment]
Ok I see the problem, one of your bottles are using the old programs format and the check for this is not working as expected. I'll plan a fix.

In the meantime post your bottle.yml(s) so I can giving you the updated versions

**Comment by Gert-dev** [comment]
Yes, I can confirm that fixes the issue, it appears to be one of the bottles. I have two bottles, and have pinned the problem to one of those - if I temporarily remove it, Bottles starts again; the other one does not have this problem.

The culprit bottle is not a really special one, it doesn't really even contain any custom installations, as I just created it to run a Windows game I already had installed somewhere else by mounting that path into the Flatpak using Flatseal, and then run it from there. I could probably just regenerate the bottle fairly easily to try and fix the problem, but that would probably not help you in pinning down the actual issue - are there any configs I can provide to help you debug it?

**Comment by Gert-dev** [comment]
It's fine, I got it fixed by looking at the commit message - the `null` name had to be rewritten to a UUIDv4, I think; it works now, thanks! :smile:

**Comment by mirkobrombin** [comment]
Yup! Happy you fixed it
