### ISSUE TITLE
What does the AppImage installation?

### ISSUE THREAD

**Issue by Moltkex** [bottlesdevs/Bottles#178]
Hi, 
I just downloaded Bottles-devel-x86_64.AppImage. In the main page:

"chmod +x Bottles-devel-x86_64.AppImage
./Bottles-devel-x86_64.AppImage

And you're done!"

Not quite. Unless I'm missing something, the whole point of appimages is to run software without having to install anything, however, after launching bottles it asks if I want to install the appimage, I use quite a few appimages, around 20+, and none of them has ever asked being installed; they just run. So, if you don't mind me asking, what is it exactly bottles.appimage want to do?

**Comment by mirkobrombin** [comment]
Just don't.....install?
The real question (without too much irony) should be: Can I hide the warning if I say no the first time?

**Comment by Moltkex** [comment]
> Just don't.....install?
> 
> The Bottles installation just "install" its desktop file to show in your system applications menu and context menu.

This "install" .desktop file isn't really necessary, is it? Most users can add the app to their DE's menu by themselves, it's not a difficult procedure and it's very easy in most DEs since they provide the tools to do so. 

> The real question should be: Can I hide the warning if I say no the first time?

If I say no - which is not an option by the way, you can hit "**just run**", there isn't a "**no**" option -  what's the expected behavior? It runs? No, it doesn't:

```
./Bottles-devel-x86_64.AppImage 

Traceback (most recent call last):
  File "/tmp/.mount_BottleQvuQ2u/usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_BottleQvuQ2u//usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_BottleQvuQ2u//usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
```

Is this error showing up because I didn't hit "**install**" but "**just run**" or is it something wrong with the appimage? Either way, the app should run when launched without asking to install anything as it defeats the main purpose of appimages 
https://appimage.org/

> Download an application, make it executable, and run! No need to install. No system libraries or system preferences are altered.

**Comment by mirkobrombin** [comment]
I think that "The user is drunk", I can't assume that anyone knows how to add an application to the menu.

For the Handy namespace problem, there is an active discussion with a proposal fix here: https://github.com/bottlesdevs/Bottles/issues/156
