### ISSUE TITLE
Packaging issues for Tumbleweed

### ISSUE THREAD

**Issue by VortexAcherontic** [bottlesdevs/Bottles#1786]
Hello there, since this is not a bug but rather me unable to figure out whats missing I try to reach out to you by this "feedback".

Currently I am desperately trying to finally update bottles for openSUSE Tumbleweed to the latest version since libadwaita 1.1.3 released but I am still getting the same and the same error.

````
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 36, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 36, in <module>
    from bottles.views.details import DetailsView
  File "/usr/share/bottles/bottles/views/details.py", line 36, in <module>
    from bottles.views.bottle_preferences import PreferencesView
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 34, in <module>
    from bottles.dialogs.envvars import EnvVarsDialog
  File "/usr/share/bottles/bottles/dialogs/envvars.py", line 24, in <module>
    class EnvVarEntry(Adw.EntryRow):
  File "/usr/lib64/python3.10/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'EntryRow'
````

I closely watched the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bottles) file and therefore noticed the dependency libadwaita-git was now removed and is back to just libadwaita.  
Initially I thought that the above issue was caused by some un-released / un-tagged features in libadfwaita as the comment on AUR said.  
But since libadwaita was updated from 1.1.2 to 1.1.3 for both Arch Linux and Tumbleweed I was like: Well the issue will be solved then. But still I am experiencing the above issue when trying to launch the locally build bottles rpm.  

Since I never developed anything with GTK4 I have no clue what I need to look for.  
I already double checked the PKGBUILD with [my spec file](https://build.opensuse.org/package/view_file/home:VortexAcherontic:branches:games:tools/bottles/bottles.spec?expand=0) but I seem to be unable to figure out what is missing and hopped you guys might be able to help me?  
Maybe I need to reach out to the libadwaita maintainers of openSUSE. But at this point I don't know where to start.

Kind regards,
V.

**Comment by axtloss** [comment]
Bottles uses libadwaita 1.2, which isn't released yet, the bottles aur package is also outdated because of that. You'll have to use the snap or flatpak or figure out a way to install libadwaita 1.2 on your system.

**Comment by VortexAcherontic** [comment]
Ay many thanks. Didn't noticed that.
