### ISSUE TITLE
[Bug]: Inception folders created into Bottle environment

### ISSUE THREAD

**Issue by olivierb2** [bottlesdevs/Bottles#1787]
### Describe the bug

When creating an new Bottle, it looks take forever, but inception folder are created (about millions if you keep running long time).

### To Reproduce

1. Remove or rename data folder (~/.var/app/com.usebottles.bottles).
2. Open Bottles app, go over welcome screen and create new Bottle (e.g. with name "Test").
3. Select Game environment and click Create.
4. Wait until all dependancies are downloaded and Bootle finished to be created.
5. Open the Bootle, access to three dot menu and Delete the Bottle.
6. Create one time again a new Game Bootle then put any name you want (e.g. "Test)
7. Click on create, the wiard indicated "Model founded" and stuck on this step.
8. Don't wait too much time otherwise it will take fovever to remove the folder (about 1 million folder ~= 5 minutes with very fast SSD). Use xkill to kill Bottle.
9. Look into folder ~/.var/app/com.usebottles.bottles/data/bottles/bottles/Test and just do find, you will see the problem, many folders Videos created inside Videos. `./drive_c/users/olivierb/Documents/Music/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos/Videos`

### Package

Flatpak from Flathub

### Distribution

Debian Unstable

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.0-2-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16799342592
    Free: 16799186944
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.5GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
It should not appear with bottles created starting from 2022.7.14

**Comment by olivierb2** [comment]
Thanks for your reply !

I removed the app folder completely (`~/.var/app/com.usebottles.bottles/`), so templates was downloaded as well. I assume old template not was used.
