### ISSUE TITLE
[Bug]: Adobe Digital Editions installation not recognized in Programs tab

### ISSUE THREAD

**Issue by BenvdStouwe** [bottlesdevs/Bottles#1792]
### Describe the bug

I successfully installed Adobe Digital Editions 4.5 inside a bottle and even though it's running fine when I manually select it with "Run Executable...", the installation is not detected in the Programs tab. Manually adding it to that tab still doesn't make it show up. According to [the docs](https://docs.usebottles.com/bottles/programs#the-program-does-not-appear) this could be due to Bottles not monitoring the path (<bottle>/drive_c/Program Files (x86)/Adobe/Adobe Digital Editions 4.5/DigitalEditions.exe).

Thank you for this great product, I really like it! 

### To Reproduce

1. Create a new "Application" bottle
2. Set "Windows Version" to "Windows XP"
3. Install "dotnet40" dependency
4. Install Adobe Digital Editions (ADE) from https://adedownload.adobe.com/pub/adobe/digitaleditions/ADE_4.5_Installer.exe
5. Leave all options at the default value
6. Make sure to skip the annoying Norton installer...
7. Notice that ADE will autorun when installation is complete and it will work fine
8. Close ADE
9. Navigate to "Programs" tab
10. Notice that there are no programs here
11. Manually add program: <your bottle>/drive_c/Program Files (x86)/Adobe/Adobe Digital Editions 4.5/DigitalEditions.exe
12. Notice that the "Programs" tab is still empty
13. Use the same path in "Run Executable..." and notice that it will run fine

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.17.12-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8308137984
    Free: 8307990528
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.4GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

I'm sure you can see it from the Bottles version in the Health Check, but I installed Bottles from "Flathub beta".

**Comment by mirkobrombin** [comment]
Bottles look for .lnk files and get the executable from there (if readable). We are already monitoring all paths which are supposed to store those files so probably it’s just unreadable. 

Can you check if there is one .lnk in the bottle for such program so we can extend the check?

**Comment by BenvdStouwe** [comment]
Thank you for the information. I found some .lnk files for this application inside the bottle:
![image](https://user-images.githubusercontent.com/16904162/179387275-bfb6fa0c-42d7-4974-8760-309dcb6e1627.png)

Does this help?

**Comment by mirkobrombin** [comment]
Thanks for looking at it. Bottles is already monitoring those paths so probably the lnk file is just unreadable. We have plans for a new approach which should improve the whole thing.
