### ISSUE TITLE
How can I install other dependency?

### ISSUE THREAD

**Issue by nguyenhai97** [bottlesdevs/Bottles#180]
Since you remove the support for winetricks (for good reason) I'm just wonder how can I install other dependency that not currently supported (d3dcompiler-47 to be specific)
Also could you add option which allow me to add exe to Programs tab? some game put the launcher in different path and so not being listed there yet

**Comment by mirkobrombin** [comment]
Hi. You can add other dependencies with a PR in our dependencies repository.

**Comment by nguyenhai97** [comment]
This is how winetricks do it, seem like they download firefox, unpack it and copy ddl to specific location, can bottles support extract and copy like that ?

**Comment by mirkobrombin** [comment]
We can but I don't want to. It doesn't seem like a good approach to download an installer and copiwt In Windows when you need something you download and install it, Wine is mature enough to install a dependency as is.

**Comment by nguyenhai97** [comment]
Oh so what about msu file, can wine deal with that now [this comment](https://github.com/Winetricks/winetricks/issues/1012#issuecomment-394143004) say that microsoft only give .msu version of that dll

**Comment by mirkobrombin** [comment]
I don't know .. this is an issue from 2 years ago is it still like this?

**Comment by nguyenhai97** [comment]
I'm not play that game, but my game required that same dll if not it only give black screen after compiling shader, dialog can show up just fine. About state of wine, I'm not really know

**Comment by mirkobrombin** [comment]
I would like to keep Bottles as close as possible (albeit simplified and guided) to what a wineprefix is. With Bottles v4 and the installers, the software installation process will be simplified even further and I hope to find a way to include those dependencies that are now missing but for all that is "tweaking" I'll let the user get into it.

Regarding your "problem" I think you can simply get that dll from the web and put inside your wineprefix.

**Comment by nguyenhai97** [comment]
Quite weird to reopen this issue, since it not bottles problem, but for though who try to play Kara no Shojo 2 (Manga gamer version) and got black screen, just cd to game directory first then run wine there, if you run wine from other place then it not gonna work, even if you use absolute path. It strang but it work
