### ISSUE TITLE
[Bug]: User is able to skip onboarding dialog

### ISSUE THREAD

**Issue by axtloss** [bottlesdevs/Bottles#1803]
### Describe the bug

Due to the onboarding dialog using an AdwCarousel, the user is able to skip the dialog by using the gestures that AdwCarousel has to navigate it.

### To Reproduce

1. remove the data directory of bottles so that the onboarding dialog appears
2. swipe to the last page of the dialog
3. press "start using bottles"
4. onboarding dialog closes without going through the actual process

### Package

Flatpak from Flathub

### Distribution

Arch linux

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.12-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8300376064
    Free: 8300228608
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.1GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Here's a video showing the issue:

https://user-images.githubusercontent.com/60044824/179759924-de653cc7-76e9-4dba-b9ee-1469f530ffcb.mp4

**Comment by mirkobrombin** [comment]
Can I lol on this? 😂

btw should be easy to fix, planning for next release
