### ISSUE TITLE
[Bug]: No cursor on wayland session in legacy tools

### ISSUE THREAD

**Issue by AnteKronos** [bottlesdevs/Bottles#1804]
### Describe the bug

I have been looking for a solution for a long time but nothing worked. 
I use sway, then a wayland session, bottles installed with flatpak starts, but when opening one of the legacy tools the cursor does not appear, I guess it depends on wayland. 

I tried activating and disabling sockets on flatseal but nothing changed. Checking with extramaus, I see that the Xwayland cursor appears but the mouse click from the application is not captured anyway.
If there is a duplicate on this problem I could not find it.

### To Reproduce

1. Open bottles
2. Select one bottle
3. Open one of the legacy tools

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.12-zen1-1-zen
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8331407360
    Free: 8331247616
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 9.8GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```
### Display Protocol

Wayland

### Display Backend used by Bottles

X11

![ezgif-1-56103ce1fe](https://user-images.githubusercontent.com/101885287/179787306-f099213d-5bc5-41e6-86fc-0fdf5003abad.gif)

EDIT: The problem is no bottles related, the problem appear only on sway.

**Comment by mirkobrombin** [comment]
I found another problem with Sway and the slider in Wine https://github.com/swaywm/sway/issues/4857

it may be related (even if who reported said that the cursor appear)

**Comment by mirkobrombin** [comment]
No problem. I’ll close the issue, feel free to add more comments
