### ISSUE TITLE
[Bug]: Bottles crash before it finishes loading

### ISSUE THREAD

**Issue by mez0ru** [bottlesdevs/Bottles#1810]
### Describe the bug

When I launch bottles the window appear, "still loading, please wait" and then after around 3 seconds it crashes.

### To Reproduce

From how I was able to reproduce it, I wanted to install the source version, so I cloned the github repo, then installed normally via the development instructions on the site, but since I'm using fedora which uses outdated libadawaita it did not launch, And since I'm unable to progress from that point any further I decided to downgrade and remove the installed "source" version by doing:
```
sudo ninja uninstall
```
After that I installed the package manager version like:
```
sudo dnf install bottles
```
The problem appeared after this point, even after deleting all the settings/reinstalling, it still persists.

### Package

Other, unofficial package

### Distribution

Fedora 36

### Health Check

```shell
Bottles could not launch, so I'm unable to run the health check.
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

```
(bottles:522019): Handy-WARNING **: 23:47:09.283: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
23:47:14 (INFO) Catalog components loaded 
23:47:14 (INFO) Catalog installers loaded 
23:47:15 (INFO) Catalog dependencies loaded 
23:47:15 (INFO) Performing Bottles checks... 

(bottles:522019): GLib-GIO-ERROR **: 23:47:15.346: Settings schema 'com.usebottles.bottles' does not contain a key named 'experiments-steam'
Trace/breakpoint trap (core dumped)
```

**Comment by mirkobrombin** [comment]
Try issuing a bottles-cli -v or bottles -v and post here the version

**Comment by mez0ru** [comment]
> Try issuing a bottles-cli -v or bottles -v and post here the version

```
~ $ bottles-cli -v
Bottles 2022.5.28-trento-3
```

**Comment by axtloss** [comment]
This is a very outdated bottles version, try using the flatpak version of bottles and see if that fixes anything.

**Comment by mez0ru** [comment]
The flatpak works great, but I would file many bug reports since I have many issues concerning the flatpak version which are not present in the package manager version. Either way since I don't a choice I will do that. Thanks.

**Comment by mirkobrombin** [comment]
Issues are welcomen
