### ISSUE TITLE
[Request]: I propose adding support for self-restriction security measures to Bottles

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [bottlesdevs/Bottles#1818]
### Tell us the problem or your need

Hello everyone!

Recently, I was studying the self-restriction measures in OpenBSD and GNU/Linux (specifically, pledge and unveil for OpenBSD and seccomp and Landlock for GNU/Linux). These mechanisms allow a process to impose self-restrictions (for syscall and file access) that cannot be removed and are inherited by child processes created after enabling restrictions. This can enhance the security of managed Wine prefixes.

### Describe the solution you'd like

I'd like to propose adding support for unprivileged sandboxing using seccomp and Landlock for GNU/Linux systems (I'm currently looking for a way to implement it and it's possible that I'll add a pull request soon). I'm thinking of creating a syscall whitelist and file access whitelist that can be managed through Bottles GUI.

### Other solutions?

Another security option is using mandatory access control systems (such as SELinux and AppArmor). However, since reconfiguring them requires root privileges, the only option is to switch to pre-loaded dedicated profile for Wine apps. This can be used in addition to seccomp and Landlock.

### Additional context and references

seccomp is a Linux kernel feature that allows a process to restrict its access to a defined set of syscalls. Once a filter has been installed, it can never be removed and it's inherited by all child processes created after installation of a filter. A process that is restricted by seccomp (in filter mode) can install additional filter -- in this case, the only syscalls that will be available are syscalls that are allowed by all installed filters.

Landlock is a Linux security module that allows a process to restrict its file access to a defined set of paths. Like seccomp, these restrictions are also un-removable, can be stacked and are inherited by child processes.

**Comment by jannuary** [comment]
I mean, that's already a thing with Flatpak, and Mirko was working on per-bottle permissions afaik

**Comment by axtloss** [comment]
As jannuary already said, these sandboxing features are already implemented by flatpaks sandboxing and the per-bottle permissions system.
Both flatpak and the per-bottle permissions system use [bubblewrap](https://github.com/containers/bubblewrap) to manage the sandboxing, which uses seccomp rules, as well as namespaces and bind mounts to allow for unprivileged sandboxing.
So basically, this feature is already implemented in some way by the underlying programs bottles uses.

**Comment by ChrysoliteAzalea** [comment]
> As jannuary already said, these sandboxing features are already implemented by flatpaks sandboxing and the per-bottle permissions system. Both flatpak and the per-bottle permissions system use [bubblewrap](https://github.com/containers/bubblewrap) to manage the sandboxing, which uses seccomp rules, as well as namespaces and bind mounts to allow for unprivileged sandboxing. So basically, this feature is already implemented in some way by the underlying programs bottles uses.

I'd like to add, that I've made [an experimental patch for Bubblewrap](https://github.com/containers/bubblewrap/pull/519) that implements Landlock-related functionality. We can make use of this.

**Comment by axtloss** [comment]
The only official way that bottles is distributed is via flatpak (and snap too iirc), so bottles can't dictate in any way on what bubblewrap version is used, as it's a dependency from flatpak, not bottles.
Additionally, there isn't really any need for that, since bottles already has a separate bottle sandboxing, which allows for unprivileged sandboxing of processes.

**Comment by ChrysoliteAzalea** [comment]
> The only official way that bottles is distributed is via flatpak

I also [proposed using Landlock in Flatpak](https://github.com/flatpak/flatpak/issues/4984). It can be done on Flatpak's side, and Bottles can additionally tighten Landlock and seccomp restrictions.

**Comment by axtloss** [comment]
Bottles shouldn't modify the sandboxes itself, if this feature were to be implemented it would have to be added in flatpak or bubblewrap which, as already stated, is what bottles uses.
Additionally it may not even be possible for bottles to modify the Landlock restrictions itself due to it already running in an unprivileged sandbox.
