### ISSUE TITLE
[BUG] Cog wheel buttons shown when creating a custom bottle don't work

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/Bottles#182]
**Description**
When creating a new bottle and selecting the custom environment, you get some options you can configure. If I click on the cog wheel besides the 'Runner' and 'DXVK Version' entries, nothing happens. 

**Installation**
 - Method:  Flatpak
 - Version 3.0.9

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the plus-button in the headerbar on the left.
2. Click on 'custom' under 'Choose an environment' in the popup that opens.
3. Click on the cog wheel of one of the entries in the 'Advanced options' menu.
4. Nothing happens when clicking the cog wheel.

**Expected behaviour**
Either an option menu should open, or the cog wheel button should be hidden.

**Screenshots**
![Bildschirmfoto von 2021-03-14 13-51-30](https://user-images.githubusercontent.com/41188546/111069425-4e321800-84cd-11eb-9103-d9af10a4a491.png)

**Desktop:**
 - OS: Fedora
 - Version: 33

**Comment by mirkobrombin** [comment]
Partially fixed with latest unstable release.
Please read the commit description.
