### ISSUE TITLE
[Bug]: No such file or directory: 'gtk-update-icon-cache'

### ISSUE THREAD

**Issue by martinmurgovski-rldatix** [bottlesdevs/Bottles#1820]
### Describe the bug

Trying to build the application from source, and am having trouble with the ninja install part.

Running custom install script '/usr/bin/python3 /Bottles/build-aux/meson/postinstall.py'
--- stdout ---
Updating icon cache...

--- stderr ---
Traceback (most recent call last):
  File "/Bottles/build-aux/meson/postinstall.py", line 13, in <module>
    call(['gtk-update-icon-cache', '-qtf', path.join(datadir, 'icons', 'hicolor')])
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gtk-update-icon-cache'

FAILED: install script '/usr/bin/python3 /Bottles/build-aux/meson/postinstall.py' exit code 1, stopped
ninja: job failed: /usr/bin/meson install --no-rebuild
ninja: subcommand failed

### To Reproduce

build bottles from source

### Package

From source

### Distribution

Alpine 3.16

### Health Check

```shell
-
```

**Comment by axtloss** [comment]
This looks like you're missing a build dependency, do you have [gtk-update-icon-cache](https://pkgs.alpinelinux.org/package/edge/main/x86/gtk-update-icon-cache) installed?

**Comment by martinmurgovski-rldatix** [comment]
After installing it, got another error. Needed to also add desktop-file-utils. Then it worked fine. Thanks for the help.
