### ISSUE TITLE
[Bug]: Clicking on a bottle dosent take me to settings page

### ISSUE THREAD

**Issue by KenwoodFox** [bottlesdevs/Bottles#1822]
### Describe the bug

I launch bottles and click on a preconfigured bottle, i'd expect to slide to the settings page, but, nothing happens, it remains static.

![image](https://user-images.githubusercontent.com/31870999/180468390-9a951c16-e9dc-48fe-a28f-7ccb90fab11c.png)
![image](https://user-images.githubusercontent.com/31870999/180468424-55f74419-9ee7-446d-84a7-06bfa380982d.png)

I see this traceback:
```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/usr/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 336, in set_config
    self.switch_runtime.handler_block_by_func(self.__toggle_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_runtime of <bottle_preferences.PreferencesView object at 0x7f791d47e300 (DetailsPreferences at 0x55c2b78690b0)>>
```

### To Reproduce

Launch bottles (from cli if you want to capture traceback)
Click bottle

### Package

AUR ("bottles" package)

### Distribution

Manjaro Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.10.131-1-MANJARO
Distro:
    Name: Manjaro Linux
    Version: Unknown
Disk:
    Total: 946762092544
    Free: 70826864640
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 23.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

That should be everything, thanks for reading!

**Comment by axtloss** [comment]
You are using the outdated aur version of bottles, try installing the flatpak and check if the issue still appears

**Comment by mirkobrombin** [comment]
Already fixed

**Comment by KenwoodFox** [comment]
Sorry, not familer with flatpaks, this is taking a long time to download everything, will the aur package be updated?

**Comment by mirkobrombin** [comment]
We are [dropping](https://twitter.com/usebottles/status/1549498729492881410) the AUR package because users are reporting it as orphan (despite the very very first message in the AUR repository our tweet explaining why the version will receive the update later). So you probably want to switch to the flatpak or bottles-git which is not official but maybe updated

**Comment by KenwoodFox** [comment]
It feels weird having 1 flatpak app on my machine, Id prefer to switch back to the aur package if it gets patched up, ill keep an eye on your twitter

this is taking forever XD install 12/16 flatpaks.

**Comment by KenwoodFox** [comment]
Ah, it seems to.. have erased or at least is not using my previous config?

**Comment by mirkobrombin** [comment]
It use its own path. Copy .local/share/bottles in .var/app/com.usebottles.bottles/data/bottles

**Comment by KenwoodFox** [comment]
> It use its own path. Move .local/share/bottles to .var/app/com.usebottles.bottles/data/bottles

Gave that a go, everything coppied fine but, dosent seem to have changed anything, sorry this is such a headache, is everybody who uses the aur package migrating this way?

**Comment by mirkobrombin** [comment]
Ya probably. The only problem you may face is path permissions (due to sandbox). But this is easy to fix: https://docs.usebottles.com/flatpak/expose-directories
