### ISSUE TITLE
[Bug]: Environment variables from Command Arguments not handled when using Sandboxing

### ISSUE THREAD

**Issue by whytiwari** [bottlesdevs/Bottles#1823]
### Describe the bug

Trying to set LANG environment variable while having the Dedicated Sandbox feature enabled causes error

"bwrap: execvp LANG=ja_JP.UTF-8: No such file or directory"

Caused due to sandbox.py not handling the environment variables set in Command Argument field of Change Launch Options.

### To Reproduce

1. Enable "Sandbox per bottle" in Experiments
2. Create new bottle or use existing bottle
3. Add new a new Program in Programs section of the bottle
4. Open the Change Launch Options for the program
5. Change the command arguments field to contain a environment variable as well as the "%command%"
6. Launch the program

### Package

Flatpak from Flathub

### Distribution

openSUSE Tumbleweed

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.11-1-default
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8070455296
    Free: 8070316032
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 9.8GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
Ping #1690

**Comment by mirkobrombin** [comment]
Please use the Language option in the bottle preferences instead. I'll merge this issue with the above.

**Comment by goddaneel** [comment]
@mirkobrombin 
I'm having the same problem, only this time it's DISPLAY (x11) and I'm experiencing a replication of the same thing on steam.
After analyzing this it could be related to flatpak-portal.service, which I have already filed in flatpak: https://github.com/flatpak/flatpak/issues/6209
