### ISSUE TITLE
bottles blank screen after starting

### ISSUE THREAD

**Issue by XnasYTPL** [bottlesdevs/Bottles#1825]
Hi i just installed nitrux os on my laptop with an amd processor and integraded graphics. its the latest version of nitrux. i just installed it and just realized that the screen is just black i cannot choose a option for a program to install 

![image](https://user-images.githubusercontent.com/78598920/180581257-d11e8635-4e5c-4066-bf0a-caa3801d6ab3.png)

**Comment by mirkobrombin** [comment]
Please fill the bug report template and provide more details like an output.
