### ISSUE TITLE
[Request]: Updated wine?

### ISSUE THREAD

**Issue by yajo** [bottlesdevs/Bottles#1827]
### Tell us the problem or your need

I'm experimenting [this bug](https://bugs.winehq.org/show_bug.cgi?id=48718), which got fixed in Wine 7.10.

However, in Bottles I only have available 7.2.

### Describe the solution you'd like

Would it be possible to update wine executors?

### Other solutions?

Install without bottles.

### Additional context and references

I use it from flathub. These are the executors currently available:
![imagen](https://user-images.githubusercontent.com/973709/180596711-58566650-3675-4ab8-b0f9-b3fc2c64d64f.png)

**Comment by mirkobrombin** [comment]
Don’t use Wine standard, use a different runner instead, like Soda or Caffe or anything else. 

Documented here https://docs.usebottles.com/components/runners#runner-updates
