### ISSUE TITLE
[BUG] Enabling the DXVK Option of a bottle makes games crash on startup

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [bottlesdevs/Bottles#183]
**Description**
Enabling the DXVK Option of a bottle makes any game or direct x accelerated application crash on start. Disabling DXVK fixes the crash. This crash does not happen if I use the wine package from fedora and their dxvk package. The crash happens with all available DXVK versions.

**Installation**
 - Method: Flatpak
 - Version 3.0.9

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a bottle. I used the custom configuration with its defaults.
2. Click on 'Preferences' in the headerbar.
3. Enable the option 'Use DXVK'
4. Now launch an exe that uses DXVk like a game (in my case Hellgate London).
5. The game does not launch and crashes.

**Expected behaviour**
The game launches without crashing on startup with DXVK enabled.

**Screenshots**
![Bildschirmfoto von 2021-03-14 14-17-41](https://user-images.githubusercontent.com/41188546/111070020-0fea2800-84d0-11eb-93be-0e3714e09a1d.png)
![Bildschirmfoto von 2021-03-14 13-46-04](https://user-images.githubusercontent.com/41188546/111069956-c568ab80-84cf-11eb-85ad-954f277196ab.png)

**Desktop:**
 - OS: Fedora
 - Version: 33

**Comment by Sebastian-Hirsch** [comment]
The crash can also be triggered by installing .Net 4.0 for the a bottle.

**Comment by mirkobrombin** [comment]
Bottles is just a prefix manager. This looks more like an error caused by dxvk or wine itself. As for chardonay, at the moment I find the bug only with unstable.
