### ISSUE TITLE
[Bug]:  black/blank window launching an executable

### ISSUE THREAD

**Issue by dandidwi** [bottlesdevs/Bottles#1830]
### Describe the bug

When running the Windows application only displays black/blank windows

### To Reproduce

When starting the Windows application only brings up a black window

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Spin Kde Plasma

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.13-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 3022999552
    Free: 3022856192
RAM:
    MemTotal: 5.6GiB
    MemAvailable: 2.3GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

X11

### Additional context

It also appeared on the X11 protocol screen and only the Flatpak version was found as an error like this.If running the RPM version of the Bottles and immediately using WINEHQ there is no error like this

**Comment by mirkobrombin** [comment]
Please read this https://docs.usebottles.com/flatpak/black-screen-or-silent-crash
