### ISSUE TITLE
[Bug]: Missing directories

### ISSUE THREAD

**Issue by Tesla-Tank** [bottlesdevs/Bottles#1832]
### Describe the bug

I installed Bottles using the flatpak (both using the software store and terminal) but every time the application launches it always fetches 3 packages at a slow speed. I even uninstall both bottles and flatpak entirely but this did not worked.
The app still works, but when I tried to change the directory to another hard drive it doesn't show up in the file explorer (Other Locations does not work either). 
Whats worse is every time I close the app, I have to go through the setup process all over again.
Thank you.
What bottles shows:
![image](https://user-images.githubusercontent.com/56700328/180627926-940ee1c9-aec2-4bd9-801d-f6532dda930a.png)
Whats missing (media directory):
![image](https://user-images.githubusercontent.com/56700328/180628066-7c2a9168-7bda-4c49-9fd4-4894b1da37e9.png)

### To Reproduce

1. Download Bottles using Software Store or Terminal.
2. Open Bottles.
3. Wait for Bottles to fetch the packages.
4. Accept the additional packages needed and wait for the setup.

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-43-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 33666932736
    Free: 33666777088
RAM:
    MemTotal: 62.7GiB
    MemAvailable: 54.9GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

My only guess on whats causing this error is with the download status (Although I'm not too sure if this is the case but it shows that com.usebottles.bottles.Locale has 7.9kb/616.8kb downloaded)
![image](https://user-images.githubusercontent.com/56700328/180628109-ff7ba3d6-ebeb-4ecc-a603-7842fda44d09.png)

**Comment by mirkobrombin** [comment]
Fetching repositories only download few kb from our repo. There should be a problem with your internet connection or reaching our server. We are already monitoring our infra and not noticing problems at all.

Post the output for `ping repo.usebottles.com -c 5`

**Comment by Tesla-Tank** [comment]
![image](https://user-images.githubusercontent.com/56700328/180656185-91289817-2034-4f24-925e-059600bae5de.png)
Yeah that makes sense, I'll reboot my router to see if that fixes anything. Thanks again.

**Comment by mirkobrombin** [comment]
Let me know

**Comment by Tesla-Tank** [comment]
Rebooting the router did not work and I switch to a wireless connection with no success. I did test the same command on my laptop with no issue, so it has to be the computer itself.

**Comment by Tesla-Tank** [comment]
Rebooting the router did not work and I switch to a wireless connection with no success. I did test the same command on my laptop with no issue, so it has to be the computer itself. I'm running out of ideas on how to fix this.

**Comment by KajacC** [comment]
> Rebooting the router did not work and I switch to a wireless connection with no success. I did test the same command on my laptop with no issue, so it has to be the computer itself. I'm running out of ideas on how to fix this.


I have the same problem. I'll see if changing the DNS solves the problem

**Comment by Tesla-Tank** [comment]
> I have the same problem. I'll see if changing the DNS solves the problem
I had a custom DNS (1.1.1.1) but my laptop had the same DNS configuration, so I doubt that's the issue.

**Comment by KajacC** [comment]
> > I have the same problem. I'll see if changing the DNS solves the problem
> 
> I had a custom DNS (1.1.1.1) but my laptop had the same DNS configuration, so I doubt that's the issue.

I tried to change the dns and nothing changed. bottles start very slowly.

Strange that in the previous version everything was good!

**Comment by Tesla-Tank** [comment]
I also tried booting into a live usb session of Kubuntu 22.04 and I'm still getting the same packet loss. I don't know what to do at this point.

**Comment by KajacC** [comment]
I tested with another internet connection, even slower than I have and had the same result!

It could be something related to the connection route. Since even that influences when you are on another continent!

**Comment by TwoPizza9621536** [comment]
I have the same problem, at the time of writing of this, as it is described here as the "fetch # of 3 packages" takes a while to show up for bottles and downloading the packages also take a while for ~20-30kb packages. Pinging the repository server results in a 100% packet loss but accessing the server on a browser shows the entire repository. Bottles did not take a long time to start before. But it did eventually load.

**Comment by KajacC** [comment]
So guys, doing tests here. I could see that in my case it is a problem with my internet provider. I went to test ping to servers in other countries and many gave packet loss!

I tried things like resetting the modem, changing DNS, disabling firewall's and nothing worked!

I partially solved the packet loss issue with a VPN. Now the bottles are flying. It's annoying to have to activate it all the time but it works!

I hope they implement something for bottles to work offline.

**Comment by TheEvilSkeleton** [comment]
You can use the `FORCE_OFFLINE=1` environment variable to force it to work offline. Although I do admit that it would be better if it was automatic.

**Comment by mirkobrombin** [comment]
FYI Bottles already enters offline mode when the connection takes long. It should probably be debugged and improved

**Comment by Tesla-Tank** [comment]
Sorry about the late comment but I recently updated to 2022.8.14-brescia and I'm no longer having the long startup time issue (although it still fetches the package during startup). I'm still having the issue with the missing directories though.

**Comment by mirkobrombin** [comment]
About missing paths https://docs.usebottles.com/flatpak/expose-directories
