### ISSUE TITLE
Tooltip for "Steam Proton Prefixes" has a non-clickable link in it

### ISSUE THREAD

**Issue by CorruptComputer** [bottlesdevs/Bottles#1833]
The tooltip when you hover "Steam Proton Prefixes" has a link in it that you can't click.

This link is long, and manually typing that out into your browser is a terrible UX. 
Could you please add a way for a user to click on this link?

Screenshot:
![image](https://user-images.githubusercontent.com/5573038/180630924-700ed932-ccbb-46db-b5b3-d6c3703ccbb7.png)

**Comment by jannuary** [comment]
Tooltips can't be made clickable, I don't think. That said, such information shouldn't be in a tooltip anyway.

**Comment by mirkobrombin** [comment]
Just reach our docs: https://docs.usebottles.com/flatpak/cant-enable-steam-proton-manager

**Comment by CorruptComputer** [comment]
You linking the page in this GitHub issue doesn't fix the problem. You are just ignorong the issue by closing this.

The issue is that anyone who sees this and needs to go to that page is going to have a bad experience with the application.

**Comment by mirkobrombin** [comment]
This wasn't a feature request, at least I saw a "feedback" prefix so nothing to implement (despite my commit)
