### ISSUE TITLE
[Request]: add ability to run native linux binaries 

### ISSUE THREAD

**Issue by allaeddineomc** [bottlesdevs/Bottles#1835]
### Tell us the problem or your need

bottles offer some great features such as FSR , gamescope, gamemode and mangohud , this features are very useful and it will be great to be able to use them with native linux binaries through bottles , and it will be very convenient to be able to access all the games in bottles library .

### Describe the solution you'd like

a good solution can be adding the ability to create bottles that aren't wine prefixes but only include steam runtime or bottles runtime.

**Comment by mirkobrombin** [comment]
Isn't this more in the Lutris purpose?

**Comment by allaeddineomc** [comment]
> Isn't this more in the Lutris purpose?

i have no idea about Lutris , it have never worked for me and it's not nearly as polished as bottles

**Comment by orowith2os** [comment]
Lutris seems to be able to do this, but it would be neat to have the feature implemented in Bottles. However, that would take away from the original point of the software, so maybe it could be split into something else and take advantage of flatpak being able to spawn new containers, so the user can have a prebuilt docker image and use that for running their software.

**Comment by mirkobrombin** [comment]
We are working on a similar app https://github.com/mirkobrombin/Atoms

This feature is too out of context as Bottles is a WINE prefix manager.
