### ISSUE TITLE
[Request]: Use generic names as titles instead of project names in preferences

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1837]
### Tell us the problem or your need

At the moment, we're using project names as titles in preferences. These names can be quite confusing, as some projects don't convey its use case:

![image](https://user-images.githubusercontent.com/50847364/180660613-5cdf0876-fdcf-4f66-af40-9589e4afb978.png)
![image](https://user-images.githubusercontent.com/50847364/180660663-a9bc5133-c464-4bb1-a1f6-abfcfc9fa757.png)

### Describe the solution you'd like

I propose to use generic names instead, and add project names in the description:

![image](https://user-images.githubusercontent.com/50847364/180660793-1c99957b-eb31-4f65-a988-0327030b361a.png)
![image](https://user-images.githubusercontent.com/50847364/180661245-298f8152-9223-4695-b5d7-e08ee06ad686.png)

I only used vkBasalt and MangoHud as examples, but we could change many other options.

**Comment by mirkobrombin** [comment]
From discord conversation: provide credits in the about dialog for projects used by Bottles

**Comment by TheEvilSkeleton** [comment]
Also from Discord: remove DXVK Hud.
