### ISSUE TITLE
[Bug]: add option for `gamescope` FSR upscaling

### ISSUE THREAD

**Issue by pmartiner** [bottlesdevs/Bottles#1838]
### Tell us the problem or your need

FSR upscaling has been available on `gamescope` [for a couple of releases](https://github.com/Plagman/gamescope/pull/360). It'd be great if, within the Gamescope config window, there was an option for enabling FSR scaling.

### Describe the solution you'd like

Besides the integer scaling option, I would like an option for FSR scaling within gamescope

### Additional context and references

I've tried turning on the "regular"(?) FSR option, but it doesn't upscale a gamescope window

**Comment by TheEvilSkeleton** [comment]
It'd be better if there weren't any toggle within Gamescope, to avoid duplicating toggles and functionality. What we could do instead is reuse the FSR toggle from the Preferences and make it act accordingly.
