### ISSUE TITLE
[Bug]: Bottles unable to load Steam Proton prefixes.

### ISSUE THREAD

**Issue by Megalex42** [bottlesdevs/Bottles#1839]
### Describe the bug

 Hello everyone, I'm using Bottles 2022.7.14-brescia-3 from flatpak, and used flatseal to give it permission to all my files. then when I go to Preferences and enable Steam Proton prefix integration, Bottles no longer opens. it stays stuck at "fetched 3 of 3 packages" and never launches. I started it from command line and can see this error:

Output of terminal: https://pastebin.com/ZseZ0T1a

thank you

### To Reproduce

Enable proton integration

### Package

Flatpak from Flathub

### Distribution

SteamOS

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.1GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
There is a problem with the launch options of one of your games. Bottles is not able to parse them. I've fixed it but it will be distributed with 2022.7.28, so in the meantime disable the steam proton pfx support or clean your launch options on steam

**Comment by Megalex42** [comment]
Hello Mirko,

Thanks for the reply. I went thru all games "Launch Options" and found the one that was causing the issue.

https://steamlists.com/sid-meiers-civilization-vi-codes-and-commands-for-linux-proton-bypass-2k-launcher/

it's the one for civ6 to bypass the 2k launcher, Launch Options are changed to:

eval $( echo "%command%" | sed "s/2KLauncher\/LauncherPatcher.exe'.*/Base\/Binaries\/Win64Steam\/CivilizationVI'/" )

After deleting that one, it loaded up fine

**Comment by mirkobrombin** [comment]
Nice! My fix should avoid the problem
