### ISSUE TITLE
[Bug]: Add to Steam won't work

### ISSUE THREAD

**Issue by gtd3692** [bottlesdevs/Bottles#1844]
### Describe the bug

I have given Bottles the permissions neccessary, but it won't add to steam. If I try to just add the .desktop it will point to just /flatpak instead of whatever the link actually points to.

### To Reproduce

Install AC Origins via Ubisoft Connect
Give Bottles permissions
Relaunch 
Click Add to steam in the menu for origins that shows under programs.
Nothing happens

### Package

Flatpak from Flathub

### Distribution

SteamOS

### Health Check

```shell
same as other decks
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
`same as other decks` no. This provides information on Bottles setup which can change from installation to installation.
