### ISSUE TITLE
[Bug]: Can't get MangoHUD to work with a ge-proton bottle

### ISSUE THREAD

**Issue by xchoice** [bottlesdevs/Bottles#1846]
### Describe the bug

terminal says this about it:
pressure-vessel-LOG-0x100: Failed to execute child process "/usr/bin/mangohud" (No such file or directory)

I've both mangohud and lib32-mangohud installed.

```
[erios@zen2choice ~]$ which mangohud
/usr/bin/mangohud
[erios@zen2choice ~]$ file /usr/bin/mangohud
/usr/bin/mangohud: POSIX shell script, ASCII text executable
[erios@zen2choice ~]$ cat /usr/bin/mangohud
#!/bin/sh

if [ "$#" -eq 0 ]; then
        programname=`basename "$0"`
        echo "ERROR: No program supplied"
        echo
        echo "Usage: $programname <program>"
        exit 1
fi

if [ "$1" = "--dlsym" ]; then
        MANGOHUD_DLSYM=1
        shift
fi

MANGOHUD_LIB_NAME="libMangoHud.so"

if [ "$MANGOHUD_DLSYM" = "1" ]; then
        MANGOHUD_LIB_NAME="libMangoHud_dlsym.so:${MANGOHUD_LIB_NAME}"
fi

# Preload using the plain filenames of the libs, the dynamic linker will
# figure out whether the 32 or 64 bit version should be used, and will search
# for it in the correct directory
LD_PRELOAD="${LD_PRELOAD}:${MANGOHUD_LIB_NAME}"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/\$LIB/"

exec env MANGOHUD=1 LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" LD_PRELOAD="${LD_PRELOAD}" "$@"
```

### To Reproduce

1.- Enable mangohud in the bottle
2.- Run anything
3.- stare at the screen while nothing happens
4.- check the terminal for errors >.<

### Package

AUR ("bottles" package)

### Distribution

Archlinux

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.14-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 511033282560
    Free: 199811473408
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 9.8GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Note on the package installed, right now I've installed bottles-git from AUR.

GE-Proton 7-26

**Comment by mirkobrombin** [comment]
Please don’t use Proton-GE, we don’t provide support for it. Viene mostrato un dialog quando si sceglie Proton-GE come runner dove sporgiamo che viene abilitato il Steam runtime per ridurre i problemi di incompatibilità ma questo sta anche causando il problema. 

Utilizza Soda o Wine-GE e disattiva lo Steam runtime. Questi runner sono basati su Proton e pensati per essere usati  fuori da steam. 

Proton-GE è presente in Bottles per altri scopi: testing, sperimentazione per la maggiore.

**Comment by mirkobrombin** [comment]
Please don’t use Proton-GE, we don’t provide support for it. A dialog is shown when choosing Proton-GE as a runner where we protrude that Steam runtime is enabled to reduce incompatibility issues but this is also causing the problem.

Use Soda or Wine-GE and turn off the Steam runtime. These runners are Proton based and meant to be used out of steam.

Proton-GE is present in Bottles for other purposes, e.g. testing.

I’ll close as not really a bug. Feel free to add more comments.
