### ISSUE TITLE
[Bug]: Cannot find the package in Flatpak

### ISSUE THREAD

**Issue by SilvSchlcht** [bottlesdevs/Bottles#1852]
### Describe the bug

I am trying to install the program via flatpak on my Ubuntu 22.04 LTS 64bit operating system and it tells me that the installation package does not exist in flatpak. I tried it on Rasberry OS 32 bit and I get the same thing.

### To Reproduce

flatpak install flathuub com.usebottles.bottles
looking for coincidences...
error: nothing matches com.usebottles.bottles in the remote flathub branch

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04 LTS 64 bit

### Health Check

```shell
flatpak install flathuub com.usebottles.bottles
looking for coincidences...
error: nothing matches com.usebottles.bottles in the remote flathub branch
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by TheEvilSkeleton** [comment]
Based on what you posted, you typed `flathuub`. Can you try `flatpak install flathub com.usebottles.bottles` instead?

**Comment by TheEvilSkeleton** [comment]
Closing the issue. If you need help, don't hesitate to comment.

**Comment by axtloss** [comment]
How did you add the flathub remote?

**Comment by mirkobrombin** [comment]
This should be reported in the dedicated Flathub channels.

Post the output of `flatpak remotes`

**Comment by SilvSchlcht** [comment]
Install these packages?

**Comment by TheEvilSkeleton** [comment]
What they're saying is you should post your issue on [Flathub forums](https://discourse.flathub.org/) or [Flatpak chat](https://matrix.to/#/#flatpak:matrix.org).
