### ISSUE TITLE
[Bug]: Adding a program to the library lets Bottles loading forever

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#1859]
### Describe the bug

Adding a program to the Library makes Bottles unusable until `library.yml` is manually deleted.

### To Reproduce

1. Create a bottle, name it `delete me`
2. Manually add a program exe
3. Rename that program exe to the bottle name `delete me`
4. Add that program exe to the Library

<details>
<summary>wrong/old</summary>

1. Have a perfectly working program.
2. Add it to the Library
3. Get notified it was successfully added to your library. But with the terminal open I can see the following error:
    ~~~
    13:47:45 (INFO) Library saved 
    13:47:45 (INFO) Adding new entry to library: 7319cd5a-11e5-4958-8433-caaa44651484 
    13:47:45 (INFO) Library saved 
    13:47:45 (INFO) Library saved 
    Traceback (most recent call last):
      File "/usr/share/bottles/bottles/views/library.py", line 55, in update
        entry = LibraryEntry(self, u, e)
      File "/usr/share/bottles/bottles/widgets/library.py", line 78, in __init__
        path = ThumbnailManager.get_path(self.config, entry['thumbnail'])
      File "/usr/share/bottles/bottles/backend/managers/thumbnail.py", line 32, in get_path
        return ThumbnailManager.__load_grid(config, uri)
      File "/usr/share/bottles/bottles/backend/managers/thumbnail.py", line 42, in __load_grid
        bottle_path = ManagerUtils.get_bottle_path(config)
      File "/usr/share/bottles/bottles/backend/utils/manager.py", line 86, in get_bottle_path
        if config.get("Environment") == "Steam":
    AttributeError: 'NoneType' object has no attribute 'get'
    ~~~
1. Changing to the library tab shows an empty page, Bottles is still usable otherwise.
2. Close Bottles and start Bottles again.
3. Bottles now loads forever, the terminal shows the same error as before.
4. Force quit Bottles and delete the `library.yml`
5. Bottles starts fine again.

</details>

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Version: 2022.7.28-brescia
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.9-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 116976529408
    Free: 9441288192
RAM:
    MemTotal: 11.6GiB
    MemAvailable: 4.8GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

This happens over many versions now but since you're advertising it in the new release notes I guess it should work at least a little bit.

Issue causing `library.yml`:
~~~ yml
7319cd5a-11e5-4958-8433-caaa44651484:
  bottle:
    name: Grand Theft Auto San Andreas
    path: Grand-Theft-Auto-San-Andreas
  icon: '/mnt/games/prefixes/Grand-Theft-Auto-San-Andreas/icons/Grand Theft Auto:
    San Andreas.png'
  id: gta_sa.exe
  name: 'Grand Theft Auto: San Andreas'
  thumbnail: grid:35e2243b-367b-4d05-8348-3d18e59dbd36.png
~~~

<details>
<summary>Forever hanging Bottles</summary>

![grafik](https://user-images.githubusercontent.com/1408843/181753854-0da2b0c0-688b-427a-87e7-485c4c8cb884.png)

</details>

**Comment by mirkobrombin** [comment]
Not able to replicate

**Comment by axtloss** [comment]
I'm not able to recreate this issue with the latest bottles version from flathub, could you try installing bottles from flathub and see if the issue still appears?

**Comment by mirkobrombin** [comment]
Are you trying to add a Steam game from a Steam proton prefix? If yes, this is not currently possible.

> This happens over many versions now but since you're advertising it in the new release notes I guess it should work at least a little bit.

That's why this is an **Experimental feature**.

**Comment by Lucki** [comment]
> Are you trying to add a Steam game from a Steam proton prefix? If yes, this is not currently possible.

It's GTA:SA, standalone. The prefix was created using Bottles.

[tmp-2022-07-29_15.03.53.webm](https://user-images.githubusercontent.com/1408843/181766612-ffb72d99-a02a-4e1c-83bb-16b57480c49d.webm)

**Comment by Lucki** [comment]
I think the problem is when the program which should get added to the Library has the same name as the Bottle.

**Comment by axtloss** [comment]
The issue probably is when having a `name: name` value, since that can be taken as a yml config entry

**Comment by Lucki** [comment]
The colon is unrelated, that was just coincidence.

It's `bottle name == program name`.

**Comment by mirkobrombin** [comment]
> The issue probably is when having a `name: name` value, since that can be taken as a yml config entry

I expect it to be handled by the yaml parser

**Comment by Lucki** [comment]
I'm not sure anymore what's causing this. Renaming doesn't have to be involved, and even the naming is different.
Here's a video of me creating a bottle `delete me` and adding a 0B file names `test.exe` and trying to add it to the library.

[tmp-2022-07-29_17.05.50.webm](https://user-images.githubusercontent.com/1408843/181789956-590f120f-a703-475f-8cad-d6daeb7558ec.webm)

**Comment by jannuary** [comment]
Can replicate even without the name conflict here.

**Comment by mirkobrombin** [comment]
After many hours I was able to figure out what was causing the problem and to replicate. The entry tried to retrieve its config based on the bottle name, but as the manager listed the bottles using the folder name as the index key, it was not detected if different.

**Comment by Lucki** [comment]
Fix works :)
