### ISSUE TITLE
[Bug]: Bottles uses only 64 bit gstreamer

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [bottlesdevs/Bottles#1863]
### Describe the bug

This bug might look similar to issue 1802 so it might be best to reopen it, but after updating to 2022.7.28 i still have issue with gstreamer under 32 bit prefix, so i've look at directory it appears to take required libs from org.gnome.Platform while it should use one from org.gnome.Platform.Compat.i386. I am not a developer so i am not sure if it's fault on maintainer of gnome runtime since gnome.Platform have broken symlink called "i386-linux-gnu".
List of my flatpak apps:
![obraz](https://user-images.githubusercontent.com/55759769/181793087-67948605-d772-4407-acdd-e31f34c2ac34.png)
Broken symlinks from gnome.Platform:
![obraz](https://user-images.githubusercontent.com/55759769/181793162-d5b7c45d-0084-4fb9-b009-3cf219243440.png)
![obraz](https://user-images.githubusercontent.com/55759769/181793182-9fc25224-7afe-4786-92a6-7efba415a1e1.png)

### To Reproduce

1. Open Bottles
2. Create 32 bit prefix
3. launch 32 bit app that requires gstreamer

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.7.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.13-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8227020800
    Free: 8226856960
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 12.2GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by taoky** [comment]
Set environment variable `GST_PLUGIN_SYSTEM_PATH` to `/usr/lib/i386-linux-gnu/gstreamer-1.0` in bottle environment may workaround this bug.

**Comment by TheEpicNoobZilla** [comment]
It works! thank you!
