### ISSUE TITLE
[Request]: Special bottles with parental controls

### ISSUE THREAD

**Issue by axtloss** [bottlesdevs/Bottles#1864]
### Tell us the problem or your need

(this idea originated in the bottles discord)
It would be interesting to have some sorts of parental controls bottle, which allows parents/guardians to set restrictions on bottles like limited/no network access or not being able to run executables/installers manually unless a password or a different form of authentication is provided.

### Describe the solution you'd like

This could be implemented in a seperate bottle style (maybe called "baby bottle") which can be chosen when creating a new bottle in the form of a toggle or checkbox:
![Screenshot from 2022-07-29 19-31-16](https://user-images.githubusercontent.com/60044824/181813352-0cfd0b35-2ab6-4845-83b3-72619be5a4b5.png)

![Screenshot from 2022-07-29 19-31-30](https://user-images.githubusercontent.com/60044824/181813443-be4d5644-b55f-409c-b66a-9587d4319776.png)

**Comment by mirkobrombin** [comment]
I think this option should not be on the bottle creation dialog as the "baby" user can still create a new bottle with full permissions

**Comment by axtloss** [comment]
So maybe an option in the global bottles prefrences that lets you set bottles to be controlled by parental controls or sets bottles generally in a restricted mode?

**Comment by mirkobrombin** [comment]
> So maybe an option in the global bottles prefrences that lets you set bottles to be controlled by parental controls or sets bottles generally in a restricted mode?

Workflow concept:
0. no Parental Control options are displayed
1. enable Parental Control in Bottles' Preferences (this will ask for a PIN)
2. create a new bottle (which will pop up the PIN dialog) and enable Parental Control for the new bottle

so to run an executable, launching an Installer/Dependency and every Legacy Tool  will pop up the PIN dialog. In the program's launch options (which will pop up the PIN dialog too) add an option to enable Parental Control for that program

**Comment by TheEvilSkeleton** [comment]
Typically, parental controls are used to restrict users no? If a parent wants to create a user for their child, then they'll create a new user and enable Parental Controls within.

![image](https://user-images.githubusercontent.com/50847364/181821960-0af946eb-e35e-4714-8469-40585659e485.png)

**Comment by mirkobrombin** [comment]
> Typically, parental controls are used to restrict users no? If a parent wants to create a user for their child, then they'll create a new user and enable Parental Controls within.
> 
> ![image](https://user-images.githubusercontent.com/50847364/181821960-0af946eb-e35e-4714-8469-40585659e485.png)

If we have access to this info, an option can be added to add a minimal Bottles view with only programs allowed by the parent/guardian. So the "baby" user has no access to a full Bottles instance.

**Comment by TheEvilSkeleton** [comment]
Keeping it here so we don't lose the link: https://lazka.github.io/pgi-docs/Malcontent-0

**Comment by TheEvilSkeleton** [comment]
Revisiting this, I doubt any of us are interested in having this feature at this point. I'm closing this issue.

(If there's an objection, we can reopen.)
