### ISSUE TITLE
[Bug]: "Add to Steam" does not add to steam

### ISSUE THREAD

**Issue by mbentham** [bottlesdevs/Bottles#1870]
### Describe the bug

"Add to steam" option is not working for any installed programs, no link is added to steam.
have followed steps on https://docs.usebottles.com/bottles/programs to give required permissions
Restarting steam/bottles and rebooting do not make any difference

### To Reproduce

open any bottle
Click on 3 dots menu for any program
Click add to steam

### Package

Flatpak from Flathub

### Distribution

Pop OS! 22.04

### Troubleshooting Logs

```shell
Version: 2022.7.28-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.10-76051810-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8320536576
    Free: 8320376832
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.0GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

steam is installed via the apt repository to ~/.steam

**Comment by mirkobrombin** [comment]
Does this path exists? ~/.local/share/Steam
Try giving Bottles access to ~/.steam

**Comment by Mavarice** [comment]
Having the same issue as this user, on the same version of PopOS.
Running the flatpak directly from terminal returns this when attempting to add the program to Steam
```
18:03:35 (INFO) Library saved
18:03:40 (INFO) Adding shortcut for Battle.net
18:03:40 (WARNING) Userdata path is not set
```

To respond to your previous question:
* No, ~/.local/share/Steam does not exist.
* When you say give Bottles access how do you mean? I don't see a "bottles" user in my `/etc/passwd` file

**Comment by mirkobrombin** [comment]
Bottles is a flatpak and has limited permissions. By default bottles can’t reach your steam path. You must give bottles flatpak permission to reach the steam path (wherever it is). 
https://docs.usebottles.com/bottles/programs

**Comment by Mavarice** [comment]
I think that might be the root-cause of the issue. It looks like the steam client installed for ubuntu (which pop_os is a derivation of) uses `.steam`. Supposedly it's supposed to create a symlink to `.local/share/Steam` but it doesn't seem to be doing so.

Some random discussions on the subject. https://steamcommunity.com/app/221410/discussions/0/4149455258721898356/

I tried manually creating the symlink for `ln -l ~/.steam ~/.local/share/Steam` and then rerunning the 
`flatpak override com.usebottles.bottles --filesystem=~/.local/share/Steam` command and then readding, but the same result

**Comment by Mavarice** [comment]
I also tried installing the flatpak version of steam but I think it created a web of symlink references between the two.
I completely purged both the .deb and flatpak from my system and will attempt a clean install of the package from Steam's website tonight.

**Comment by Lucki** [comment]
On Debian based systems `$XDG_DATA_HOME/Steam` is mapped to `$HOME/.steam/debian-installation`.
Old installation may still be just be using `$HOME/.steam` without the subfolder.

**Comment by Mavarice** [comment]
So I was able to finally get it to work.
The command `sudo flatpak override` didn't seem to be working as expected...
It adds it to `/var/lib/flatpak/overrides/com.usebottles.bottles` but Bottles doesn't actually seem to pick it up. 
![adding permission](https://user-images.githubusercontent.com/28742681/182220650-81bf20b1-7ed0-4239-b923-714a26e47608.png)

Thus the Warning: `(WARNING) Userdata path is not set`

However if I use flatseal to add that path directly to the Filesystem section, it works fine.
I also notice that Flatseal and the above overrides path don't share content...so somehow my flatpak installation is off? Might be a PopOS thing
![flatseal](https://user-images.githubusercontent.com/28742681/182220707-9ec261e9-c5ae-4721-a5fa-414c36658592.png)

**Comment by mirkobrombin** [comment]
Try setting the override with the `--user` flag

**Comment by mirkobrombin** [comment]
Latest commit should avoid the symlink

**Comment by oviniciusfeitosa** [comment]
If your steam was installed by non flatpak and the folder `~/.steam/debian-installation` exists, try this command:

`sudo flatpak override com.usebottles.bottles --filesystem=/home/your_user/.steam/debian-installation`

Relaunch your Bottles, then try to click `add to steam` again
