### ISSUE TITLE
Strings missing translations

### ISSUE THREAD

**Issue by A6GibKm** [bottlesdevs/Bottles#1871]
Doing a grep for `"label">` reveals the following strings, and some of them should be translatable.

![image](https://user-images.githubusercontent.com/11528996/181935571-2a8456b7-4d51-4b41-8a71-e2c9ad2a8959.png)

There are also a lot of results by querying `label`, `title`, `subtitle`,  and `description`.

**Comment by A6GibKm** [comment]
Also running `intltool-update -m`, one can see that the following files are missing from POTFILES

```
src/dialogs/exclusionpatterns.py
src/ui/dialog-bottle-picker.ui
src/ui/dialog-exclusion-patterns.ui
src/ui/dialog-proton-alert.ui
src/ui/dialog-sandbox.ui
src/ui/dialog-upgrade-versioning.ui
src/ui/exclusion-pattern-entry.ui
src/ui/local-resource-entry.ui
src/views/bottle_versioning.py
src/views/loading.py
```

**Comment by mirkobrombin** [comment]
We haven't actually updated translation strings in a while :D

**Comment by A6GibKm** [comment]
Note that there are tons of strings that are not marked for translations still.

**Comment by mirkobrombin** [comment]
Those has no translations, there are placeholder which are overwritten in python:
- dependency-entry.ui
- list-entry.ui
- loading.ui
- task-entry.ui
- dialog-deps-check.ui
- library-entry.ui
- dialog-installer.ui
- importer-entry.ui
- installer-entry.ui
- dialog-crash-report.ui

**Comment by A6GibKm** [comment]
I made  PR, imho there are two possibilities, either the placeholder is translated in case something goes wrong, or there is no placeholder.

**Comment by mirkobrombin** [comment]
A fallback makes sense
