### ISSUE TITLE
Question: why is xdg-download permission introduced?

### ISSUE THREAD

**Issue by DuckDuckWhale** [bottlesdevs/Bottles#1874]
In 6419f85bba1b482b81f25ff7bdf566caf50028f6, `xdg-download` is added as a default permission. Why is this introduced? What would I be missing out on if I remove this permission? Would this cause sandboxed programs to have access to my Downloads folder without asking?

**Comment by mirkobrombin** [comment]
It is a compromise for those who want to run non-standalone installers without having to change the permissions of the flatpak. The Downloads directory is where users are expected to download the installer they want to run. Bottles breaks the symlinks between userdir (wine home) and homedir (host system home), however this will be available in the Z: drive. You can remove this permission safely without breaking anything.
