### ISSUE TITLE
[Poll] Linux bottles

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1877]
> **Notes**: We are evaluating this because it has been asked by our users.

In the past few days we have been experimenting with the implementation of Linux bottles in Bottles using chroot and proot. This has yielded very promising results. We were able to install Nginx in a Linux bottle and host a site accessible from the outside.

Linux bottles support any Linux distribution (we have tested Alpine Linux and Ubuntu).

To implement this feature it is essential to change the purpose of the project from **Wine prefix manager** to **Environment manager**. In the designed workflow, when the users creates the bottle, they are asked for the type of environment desired (Linux or Windows). Each type of bottle will have more or less functionality but the use will be almost the same.

This public survey invites interested users to express their consent or dissent, we will use these results to understand whether or not to implement the feature.

To vote just drop an emoji or comment.

**Comment by TheEvilSkeleton** [comment]
We should fix existing issues before implementing new features and risking even more issues.

**Comment by arcDaniel84** [comment]
> We should fix existing issues before implementing new features and risking even more issues.

+1

**Comment by Knebergish** [comment]
Bottles was originally stated as an application for managing Wine prefixes. Many, if not most, users use Bottles to run familiar programs from Windows. It seems to me that "...install Nginx in a Linux bottle and host a site accessible from the outside" is far from the most common case of using Bottles, and its support can only confuse and scare away ordinary users.

**Comment by Martinligabue** [comment]
I'm not against this, if its added as an advanced option. It could be an option in the settings, or a fourth way to create a bottle, but it shouldn't interfere with a basic user workflow. I can see why it would be part of bottles, personally I'd like to sandbox some Linux apps or systems, or even native games if possible, but I don't see it as a basic feature.

**Comment by lovelyyfiaaa** [comment]
Emm, a lot of Linux enthusiasts promote the separation of apps to just their core features, right?? Sooo we could have it as a separate app called "Bottles Containers". ^^

I think it would be great to have an app that lets you easily create OCI images and use them in Podman or Toolbox!! Writing Dockerfile or Nixfiles from scratch for reproducible dev environments are pretty painful, and we can't use Flatpak everytimeee..

**Comment by fagnerln** [comment]
I like the idea of becoming an environment manager, it's something like creating a flatpak to closed source software. It can be used to play old natives games from GOG for example.

But isn't the initial concept of Bottle being a Bottle of WINE? There's nothing that worth to improve first? What if make a fork of Bottles to work with sandboxed Linux?

**Comment by SViN24** [comment]
While it looks cool I think you should prioritize wine bottles and all the issues with it now. Also don't get too Feature creep heavy. 
The way I look at it bottles satisfies the issue of managing wine instances in a fast and easy way. 
When it comes to containerized Linux environments we already have pretty good solutions to that, I can already think of distrobox which works just fine.

**Comment by mirkobrombin** [comment]
I would have liked to keep my vote neutral but I think a few things are worth specifying.

This feature was requested by some users who would like Bottles to handle even more stuff. Personally I am not against this idea but it is important to consider and state what Bottles' purpose is. I created this program in 2017 as a hobby with the sole purpose of managing Wine prefixes, today it is still a Wine prefix manager despite all the remakes. My aim with Bottles is to graphically integrate and automate 100% of Wine's features, improving and simplifying the user experience as much as possible, eliminating strange and inconsistent windows, complex and hidden configurations and allowing the user to recover a previous state. of its bottle without losing data.

Today Bottles is 90% of this. Almost all Wine tools are graphically integrated into Bottles, the automated configuration processes, the installers streamline the entire installation process, the versioning system allows you to recover a previous state. In short, some bugs exist and always will exist but I can say that Bottles now has an image.

Back to the survey, Bottles is a Wine prefix manager and anything not related to Wine or Windows software is out of the context. For this reason this feature as well as other similar ones will not be integrated.

As mentioned, the idea is still interesting and personally I am having a lot of fun experimenting with chroots/proot and automating them too and for this reason I will start a new project just for this purpose, letting Bottles go its own way focusing on its core purpose.

Thanks to everyone who took part in the survey. We are writing an article that will summarize the situation and also explain other concepts while affirming the purpose of Bottles.

**Comment by wusaby-rush** [comment]
I loved the idea, but it can be a new program, maybe gui for distrobox or any thing, but use bottles to manage Linux bottles I think it is confusing 

and thank you @mirkobrombin for “bottles”

**Comment by Chadano** [comment]
> We should fix existing issues before implementing new features and risking even more issues.
> 
> Frankly, we should also prioritize to get it to GNOME Circle.

I completely agree that this should be the push forward. Furthermore I would argue that having a Linux bottle, on a Linux environment would not necessarily be useful unless it were to be integrated into Windows as well. I'm sure there would be certain use-cases for it, but it would be a lot smaller and varied and could be integrated into its own program itself rather than an extension of Bottles.

If it were to be implemented into bottles I would recommend that it be a toggleable feature, as the main feature of Bottles first and foremost should remain "Windows in a bottle".

**Comment by HadetTheUndying** [comment]
This sounds to me like it should be a separate projects. This has nothing to do with managing Wine Prefixes and serves mostly an entirely different purpose.

**Comment by KaspianDev** [comment]
I love the idea
