### ISSUE TITLE
[Bug]: Manually added programs can't be removed without restarting Bottles

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1884]
### Describe the bug

I was testing bunch of new programs and decided to add them all one by one to programs list to have the ability to force close them easily in the GUI in case of them not responding. I noticed I couldn't remove them with "remove from list" button. I did some tests and it appears after restarting Bottles you can use that button without problems. Freshly added programs don't work with it.

### To Reproduce

1. Go to any bottle
2. Add a new program to the program list
3. Click "remove from list"
4. Close and open Bottles
5. Try removing the added program once again.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.7.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-43-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8357883904
    Free: 8357736448
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.9GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
fixed by 48a400aedcf8d75734c4f080a0cb7b57c1396e59
