### ISSUE TITLE
[Bug]: "Add to Steam" using wrong bottle name in command when the bottle name has a space in it

### ISSUE THREAD

**Issue by RibShark** [bottlesdevs/Bottles#1885]
### Describe the bug

When the name of a bottle has a space in it, for example `Example Game`, the xdg-open command generated when adding a program to Steam will have the bottle in the command formatted as `Example-Game`, which does not correctly launch the program. The command should instead be formatted with the bottle name as `'Example Game'`, which then runs the program correctly.

### To Reproduce

Make a bottle with a space in it, add a program to the bottle, then add that program to the steam library through the "Add to Steam" feature.

### Package

Flatpak from Flathub

### Distribution

SteamOS

### Troubleshooting Logs

```shell
Version: 2022.7.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778521088
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 12.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by pixartist** [comment]
The same thing happens with add to library and it's very annoying

**Comment by mirkobrombin** [comment]
Fixed some commits ago.

**Comment by claudiodekker** [comment]
Seems like this bug has returned (on Steam Deck at least) as of 51.5
