### ISSUE TITLE
[BUG] Clicking the Run.exe button makes Bottles to crash silently

### ISSUE THREAD

**Issue by midvok** [bottlesdevs/Bottles#189]
**Describe the bug**
I'm unable to run any exe from the Bottles GUI. Every time I click the Run.exe button, the GUI crashes silently without reporting any issue.

**Workaround**
I was able to to install PhotoLine and ColorMania by using the context menu from File manager (which is great).
But many of the other exe installers just do nothing and even no issue/error/exception is reported. Also the context menu doesn't work when Bottles GUI is open, I always have top close it first.

**Installation**
 - Method: AppImage
 - Version: 3.0.9, 3.1.0

**To Reproduce**
1. Run Bottles and create a new Bottle (software mode)
2. Click on Run.exe button or the icon button next to the Bottle name.
3. The Bottles GUI crashes/closes without reporting anything

**Expected behavior**
When something goes wrong, Bottles should report some issue or error. Otherwise, I have no idea what's going on when the GUI just silently closes.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Kernel: 5.10.19-1-MANJARO 
 - GNOME 3.38.3 

**Additional context**
I love the GUI, it looks awesome and provides all the relevant information, but problem is that it silently crashes without reporting any issue.

**Questions**
1. Is there some log file created to see what happens with the GUI?
2. Is there some way to see what happens when I run exe file (using context menu) and it does nothing?
3. What is a recommended method to upgrade Bottles using AppImage, I downloaded version 3.1.0 AppImage, run it and it created another instance in my applications dir (so had to delete manually the previous version).

**Comment by mirkobrombin** [comment]
Hi! I didn't understand if it is Bottles crashing or the application you are trying to start/install.
In the first case, try to run Bottles from the command line to catch the output.

For the AppImage update, just replace the old .AppImage with the new one.

**Comment by midvok** [comment]
@mirkobrombin
Hi and thanks for the quick respond!
I tried to run the AppImage from terminal and this is the error after clicking the Run.exe button:
```
    ~/app  ./Bottles-devel-x86_64.AppImage                                                                      ✔ 
2021-03-19 15:54:13 INFO: Runners found: [chardonnay-6.0]
2021-03-19 15:54:13 INFO: Dxvk found: [dxvk-1.8.1]
2021-03-19 15:54:13 INFO: Connection status: online …
2021-03-19 15:54:13 INFO: Connection status: online …
2021-03-19 15:54:13 INFO: Connection status: online …
2021-03-19 15:54:13 INFO: Bottles found: Photoline
2021-03-19 15:54:14 INFO: Bottles Started!

(bottles:2573): GLib-GIO-ERROR **: 15:54:22.949: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
/tmp/.mount_BottleXgCPDu/AppRun.wrapped: line 52:  2573 Trace/breakpoint trap   (core dumped) python3 $APPDIR/usr/bin/bottles $1
```
My default file manager is Nautilus (I believe), but I also installed Nemo, Dolphin and Krusader.

**Comment by mirkobrombin** [comment]
This may be related to #157

**Comment by midvok** [comment]
I've been trying older versions of Bottles and it works perfectly fine for me with the version 3.0.5!!!

Since the version 3.0.6 Bottles crashes for me with the above error. The newer version is probably bounded with some GTK dependency which is incompatible with the most recent Manjaro GNOME 3.38. I also noticed that since version 3.0.6, it looks like the Bottles actually do not respect my Gnome system theme and try to push its own. Just Bottles 3.0.5 are perfectly styled with my system theme.

**Comment by mirkobrombin** [comment]
I refer you to an active conversation on improving and solving problems with AppImage dependencies
#156
