### ISSUE TITLE
[Crash report]  [Errno 17] File already exists

### ISSUE THREAD

**Issue by nevaforget** [bottlesdevs/Bottles#1891]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.7.28-brescia-2

**Log**
```python3
[Errno 17] Die Datei existiert bereits: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles'  File "/app/share/bottles/bottles/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/window.py", line 191, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 134, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 155, in checks
    self.check_app_dirs()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 234, in check_app_dirs
    os.makedirs(Paths.bottles, exist_ok=True)

  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

```

**Comment by nevaforget** [comment]
moved files and tried to symlink ~/.var/app/com.usebottles.bottles/data/bottles/bottles -> /media/second_drive/Data/bottles

**Comment by mirkobrombin** [comment]
Looking at the code, we perform a `os.makedirs(Paths.bottles, exist_ok=True)` with `exist_ok=True` which should not raise an exception if the directory already exists. So nothing we can fix in our own.

I think there is a permission problem which is not identified by the python wrapper. Did you give permissions for both paths (symlink source and destination)?

**Comment by mirkobrombin** [comment]
Closing for no response
