### ISSUE TITLE
[Bug]: Can't add custom programs or run executables.

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#1896]
### Describe the bug

Custom programs don't get added and I can't get executable to run either.

### To Reproduce

1. Go to "Programs" in any bottle
2. Click on the + button
3. Add a program

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.7.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.13-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 3813380096
    Free: 3813212160
RAM:
    MemTotal: 7.1GiB
    MemAvailable: 3.4GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

I tried emptying the bottles folder in `.var` but that didn't solve anything

**Comment by mirkobrombin** [comment]
Some useful logs?

**Comment by VarLad** [comment]
@mirkobrombin I tried running it from the terminal and this is what it shows when I try adding a program 
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/bottle_programs.py", line 69, in set_path
    _file_name = _file.get_path().split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'get_path'
```

**Comment by VarLad** [comment]
@mirkobrombin Is that enough information?

**Comment by VarLad** [comment]
@mirkobrombin Can you replicate this issue?

**Comment by VarLad** [comment]
Resolved by deleting the `/home/username/.local/share/flatpak` folder for some reason

**Comment by mirkobrombin** [comment]
Sounds like a Flatpak issue: `F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.`

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/bottle_programs.py", line 69, in set_path
    _file_name = _file.get_path().split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'get_path'
```

The file chooser is returning None, so not a Bottles problem.



> Resolved by deleting the `/home/username/.local/share/flatpak` folder for some reason

This is weird but if works... :D

**Comment by Orthestral** [comment]
I'm having the same problem. Adding custom programs and running an executable inside the bottle does nothing (Running through console works; file chooser doesn't)
There isn't a "None" or any other dropdown menu on the file chooser. Deleting .local/share/flatpak didn't fix it.
I'm running Void Linux. It seems to have to do with xdg-desktop-portal, cause it works fine when it isn't running.

There are two relevant error messages: one on Bottles' side, and the other on xdg-desktop-portal's side.

Bottles:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_programs.py", line 69, in set_path
    _file_name = _file.get_path().split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'get_path'
```
xdg-desktop-portal:
```
XDP: Handling OpenFile

** (/usr/libexec/xdg-desktop-portal:13693): WARNING **: 13:15:25.281: Failed to register file:///home/moonbow/.var/app/com.usebottles.bottles/data/bottles/bottles/Hames/drive_c/windows/explorer.exe: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by Orthestral** [comment]
Fixed when I switched frome awesomewm to GNOME
