### ISSUE TITLE
[Bug]: Unable to download on steam deck

### ISSUE THREAD

**Issue by Inquirejdm** [bottlesdevs/Bottles#1902]
### Describe the bug

When downloading through discover and flatpak I am able to download, I have given permissions to bottles. Stuck on “Almost Done” we need a few more minutes to set everything up for roughly 10 minutes

### To Reproduce

Redownloaded and same result - new steam deck

### Package

Flatpak from Flathub

### Distribution

Steam OS

### Troubleshooting Logs

```shell
Unable to select hamburger menu
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Hi thanks for reporting.
It's related to to your connection or github servers. Our infrastructure has no problems.


Post the output here please.

**Comment by Inquirejdm** [comment]
Did you have an idea why my connection/ISP/router would be causing this? I believe I can finish downloading bottles from my phone via hotspot .

**Comment by mirkobrombin** [comment]
Idk honestly 😅

**Comment by Inquirejdm** [comment]
Lines and lines of code later. DNS issue

**Comment by mirkobrombin** [comment]
Did you solve the problem?

**Comment by Inquirejdm** [comment]
Yes, I did.
