### ISSUE TITLE
[Request]: Provide sensible configuration defaults for win32 applications looks

### ISSUE THREAD

**Issue by DoodlesEpic** [bottlesdevs/Bottles#1905]
### Tell us the problem or your need

Wine is an amazing software and using it through Bottles is also very nice, but something that Wine completely fails at is making applications look like the Windows version they are supposed to be running, instead they all look like Windows 95 applications.

### Describe the solution you'd like

It is possible to improve text rendering in Wine by enabling font smoothing, it's also possible to provide a .msstyles or .theme file so that it doesn't look like straight out of Win95. Bottles being a convenience application that probably newer users use a lot I think the "Application" environment should provide more sensible defaults for those.

### Other solutions?

Another solution I think would be appropriate is adding a simple wizard to setup such configuration in the preferences of the wine bottle.
Using the bundled light theme and increasing the DPI would also go a long way compared to the default settings and would be much easier to set up I imagine.

### Additional context and references

There are a few solutions listed here which I find might be interesting:
[Ask Ubuntu: Improve GUI appearance of Wine applications](https://askubuntu.com/questions/219791/improve-gui-appearance-of-wine-applications)

I expect all of these solutions should also work perfectly on Soda.

**Comment by keenanweaver** [comment]
I find using the 'Light' theme and the setting the Active Title Text, Menu Text, and Message Box Text desktop integration items to Tahoma, size 10 makes it look a lot more modern without needing to increase the DPI. A complementary 'dark' version would be cool, too, but that's probably coming from upstream Wine.

![2022-08-08_07-01](https://user-images.githubusercontent.com/37268985/183413735-fd65eaf4-73d6-409a-b6e7-cbb405d86572.png)

![2022-08-08_07-02](https://user-images.githubusercontent.com/37268985/183413751-80a8359c-568c-49d1-b5da-28b484eb08a2.png)

**Comment by DoodlesEpic** [comment]
The light theme has recently become the default in new wine prefix, I believe this is a non-issue at this point. Should we close this issue? I still think maybe increasing the default DPI and possibly enabling RGB font-smoothing would be better, but it's really not that big of a deal as the default ms-styles.
https://www.winehq.org/announce/8.0

**Comment by eiliatmr** [comment]
can anyone help me how to enable the light theme on flatpak version of bottles. i really dont know how to do it. sry.

**Comment by orowith2os** [comment]
This should be managed by your Wine runner, not Bottles.
