### ISSUE TITLE
gst-plugins-ugly support in flatpak Bottles

### ISSUE THREAD

**Issue by taoky** [bottlesdevs/Bottles#1913]
Recently I tried to play a game with Bottles (installed from FlatHub), and the winegstreamer complains about missing decoder:

```
winegstreamer error: decodebin0: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin0: ../gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstBin:bin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)

winegstreamer error: decodebin1: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin1: ../gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstBin:bin1/GstDecodeBin:decodebin1:
no suitable plugins found:
Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)
```

Although I could still play the game without video playback, it could be a problem for some games. As far as I know, the decoder of `video/x-ms-asf` (`libgstasf.so`) is contained in gst-plugins-ugly (which may bring some legal trouble in some regions?). However, it would be very difficult for end-user to install that in GNOME flatpak runtime. The current runtime contains gst-libav, gst-plugins-bad, gst-plugins-good and gst-plugins-base (https://gitlab.gnome.org/GNOME/gnome-build-meta/-/tree/master/elements/sdk), but sadly I cannot find a place where I can get gst-plugins-ugly into the runtime.

I'm wondering if it is possible for Bottles to pack gst-plugins-ugly as optional "Dependencies" (or by ["Extensions"](https://github.com/flatpak/flatpak/wiki/Extensions))? And if not, I think that it would be convenient to provide some guidance in docs about alternative solutions about video playback in Bottles (use quartz and disable winegstreamer, etc.)

Thanks.

**Comment by taoky** [comment]
I discovered that Proton-GE has gst-plugins-ugly libraries bundled within their tarball. Only need to set env `GST_PLUGIN_SYSTEM_PATH` to `/var/data/bottles/runners/<replace me with proton-ge runner name>/dist/lib/gstreamer-1.0/` to use them.

(Maybe Bottles can help set that env automatically? 

For reference Proton-GE running from Steam will set related env: `GST_PLUGIN_SYSTEM_PATH_1_0=/home/username/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/files/lib64/gstreamer-1.0:/home/username/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/files/lib/gstreamer-1.0` and `WINE_GST_REGISTRY_DIR=/home/username/.local/share/Steam/steamapps/compatdata/<game_id>/gstreamer-1.0/` when I'm using procfs to get its environ.)

**Comment by mirkobrombin** [comment]
We use gstreamer inherited from [org.winehq.Wine](https://github.com/flathub/org.winehq.Wine/blob/branch/stable-21.08/org.winehq.Wine.yml)

**Comment by esjeon** [comment]
Hi, I'm currently facing the same issue. One of the game I requires ASF to play videos, but wine emits the same error message as  the original report.

```
winegstreamer error: decodebin3: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin3: ../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstBin:bin3/GstDecodeBin:decodebin3:
no suitable plugins found:
Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)

00cc:err:wmvcore:init_stream Failed to connect parser, hr 0x80004005.
```

One thing I noticed here is that Bottles actually does *NOT* inherit Wine as-is. [Wine is based on Freedesktop runtime](https://github.com/flathub/org.winehq.Wine/blob/afcbcfa46e7578bd817da4245b529ac251663ecc/org.winehq.Wine.yml#L34C3-L34C6), but [Bottles pulls in GNOME runtime instead](https://github.com/bottlesdevs/Bottles/blob/af3a7ccf44cd17d40160b1db66a5c8177b6f4cf5/com.usebottles.bottles.yml#L35C8-L35C8). `libgstasf` is included in the Freedesktop runtime, but not in GNOME one. 

```
$ dpkg -L gstreamer1.0-plugins-ugly | grep asf
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstasf.so

$ find /var/lib/flatpak/runtime/ |grep libgstasf | grep i386
/var/lib/flatpak/runtime/org.gnome.Platform.Compat.i386/x86_64/44/14adbe64f716e55d55542de7f14ce61be1cedd8eebe94199bbebbf1c4ce91f08/files/gstreamer-1.0/libgstasfmux.so
/var/lib/flatpak/runtime/org.freedesktop.Platform.Compat.i386/x86_64/22.08/d3a368f5d767fd6ff336a82be7259b115d42b418fd3b0fef63b455abcf1929e2/files/gstreamer-1.0/libgstasf.so
/var/lib/flatpak/runtime/org.freedesktop.Platform.Compat.i386/x86_64/22.08/d3a368f5d767fd6ff336a82be7259b115d42b418fd3b0fef63b455abcf1929e2/files/gstreamer-1.0/libgstasfmux.so
```

However, even the Freedesktop runtime doesn't offer all of gst-plugins-ugly (though the selection looks reasonable):
```
$ dpkg -L gstreamer1.0-plugins-ugly | grep libgst | while read path; do basename "$path"; done
libgsta52dec.so
libgstamrnb.so
libgstamrwbdec.so
libgstasf.so
libgstcdio.so
libgstdvdlpcmdec.so
libgstdvdread.so
libgstdvdsub.so
libgstmpeg2dec.so
libgstrealmedia.so
libgstsid.so
libgstx264.so

$ dpkg -L gstreamer1.0-plugins-ugly | grep libgst | while read path; do filename=$(basename "$path"); [[ -e /var/lib/flatpak/runtime/org.freedesktop.Platform.Compat.i386/x86_64/22.08/d3a368f5d767fd6ff336a82be7259b115d42b418fd3b0fef63b455abcf1929e2/files/gstreamer-1.0/"$filename" ]] || echo "missing: $filename"; done
missing: libgsta52dec.so
missing: libgstamrnb.so
missing: libgstamrwbdec.so
missing: libgstcdio.so
missing: libgstdvdread.so
missing: libgstmpeg2dec.so
missing: libgstsid.so
missing: libgstx264.so
```

Still, I'm not sure if migrating to Freedesktop can solve this issue. Perhaps building an extension might be a better fit.

**Comment by orowith2os** [comment]
The GNOME runtime is based and built from the Freedesktop runtime. Anything built in the Freedesktop runtime will run in the GNOME runtime just fine. And the GNOME runtime can make use of Freedesktop compat platforms.

**Comment by esjeon** [comment]
Mostly yes, but GNOME somehow chose not to ship `libgstasf.so`.

```
$ flatpak run org.gnome.Platform//44
[📦 org.gnome.Platform ~]$ find / -name 'libgstasf.so'
find: ‘/proc/tty/driver’: Permission denied
[📦 org.gnome.Platform ~]$ 
exit
```

A good news tho - the version 45 comes with the library. Both x86_64 and i386 (in Compat).

```
$ flatpak run org.gnome.Platform//45
[📦 org.gnome.Platform ~]$ find / -name 'libgstasf.so'
find: ‘/proc/tty/driver’: Permission denied
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstasf.so
[📦 org.gnome.Platform ~]$ 
exit
```
Upgrading to 45 should resolve this issue naturally.
