### ISSUE TITLE
[BUG] LTspice runs perfectly but don't appear in programs

### ISSUE THREAD

**Issue by richieloro** [bottlesdevs/Bottles#192]
**Describe the bug**
After installing LTspiceXVII, in a software bottle. The program finish the installation without issues, then automatically open a window and works perfectly. I can work in LTspice no bug everything work. But the program shortcut don't appear in Bottles, I can't launch the program again after closing it.
Note : I can find the LTspice program in wine uninstaller, and a shortcut is created in my desktop.

**Installation**
 - Method: Flatpak version 3.1.0 on Ubuntu 20.10 (pop os)
 - LTspice downloaded from the official source : https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html

**To Reproduce**
1. Create a software bottle
2. Lauch the installer "LTspiceXVII.exe"
3. After the install the program launch and works fine
4. Bottles V3 did not add the shortcut to the program list

**Screenshots**
![Screenshot from 2021-03-20 18-38-08](https://user-images.githubusercontent.com/81038208/111880505-4df1bb00-89ac-11eb-97b7-710093444ffa.png)
![Screenshot from 2021-03-20 18-41-47](https://user-images.githubusercontent.com/81038208/111880508-50ecab80-89ac-11eb-80a7-fa178ad3ced3.png)

**Comment by mirkobrombin** [comment]
Thanks for reporting, please read this: #141

**Comment by richieloro** [comment]
Ok thank you, I understand. Bottles/wine looks for *.ink in the Start Menu.

I found LTspiceXVII.ink in the folder you mentioned but it was located here : 
_drive_c/users/*/Start Menu/users/Start Menu/LTspiceXVII.ink_
It should have been located here :
_drive_c/users/*/Start Menu/users/Start Menu/Programs/LTspice/LTspiceXVII.ink_

So I took this .ink and copied it in :
drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/LTspice/LTspiceXVII.lnk
**AND now it works !** 

Thank you Mirko and keep up the good work your program is a breath of fresh air in the Wine community.
I like Bottles a lot.
