### ISSUE TITLE
[Request]: Unify and anonymize the username used inside Wine bottles

### ISSUE THREAD

**Issue by omichalek** [bottlesdevs/Bottles#1924]
### Tell us the problem or your need

I would welcome if the directory inside `drive_c/users/` would always have the same name

1. Some runners use different usernames - Proton creates `users/steamuser`, others create `users/$USER`.
   - This leads to duplicate data inside the directory
   - It causes the data to appear to be lost when switching the runners.
2. A bottle that is "sandboxed" should not need to use the host linux username anyway

### Describe the solution you'd like

A simple `drive_c/users/user` used by all Wine runners would sound great to me.

### Additional context and references

I have another related user-data suggestion here: https://github.com/bottlesdevs/Bottles/issues/1923

**Comment by mirkobrombin** [comment]
What are the benefits of this?

**Comment by omichalek** [comment]
switching between Proton and other Wine versions does not make you loose your data

**Comment by mirkobrombin** [comment]
Proton will still force its username

**Comment by omichalek** [comment]
would it then be possible to change every other Wine runner to use "steamuser" instead?

**Comment by mirkobrombin** [comment]
No as this will result in weird configurations. You should not use Proton for non Steam purposes, use Soda or Wine-GE instead which are proton based.

Closing as there is no fix for this.
