### ISSUE TITLE
Cannot use input method like fcitx

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#1929]
**it is impossible to use fcitx to apps through bottles**
recently i use notepad++ and line(by naver) ,and find out that all the app in bottles cannot use fcitx to input words, meanwhile I try to use winetricks to make a clear wine environment and install then both works.

**Comment by mirkobrombin** [comment]
Please follow the bug report template.

**Comment by csc-chicken** [comment]
sorry first time reporter here

**Comment by mirkobrombin** [comment]
Don’t worry
