### ISSUE TITLE
[Crash report]  bottles tries to use a template that does not exist

### ISSUE THREAD

**Issue by infirit** [bottlesdevs/Bottles#1936]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.8.14-brescia

**Log**
```python3
[Errno 2] Bestand of map bestaat niet: '/home/USER/.local/share/bottles/templates/e23732eb-2673-4f4a-a958-0cce0e7384e7'  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1182, in create_bottle
    TemplateManager.unpack_template(template, config)

  File "/usr/share/bottles/bottles/backend/managers/template.py", line 169, in unpack_template
    shutil.copytree(_path, bottle, symlinks=True, dirs_exist_ok=True, ignore=shutil.ignore_patterns('.*'))

  File "/usr/lib/python3.10/shutil.py", line 556, in copytree
    with os.scandir(src) as itr:

```

**Comment by mirkobrombin** [comment]
Which package is this?

**Comment by mirkobrombin** [comment]
This is weird as the uuid is taken exactly from that path. Share your data.yml file and health check please.

**Comment by infirit** [comment]
I saved the old templates directory and can easily reproduce it.

```yml
custom_bottles_path: /meuk/Bottles
notifications: []
```

What healthcheck are you talking about? I can't find anything in bottles.

**Comment by infirit** [comment]
I think I see what is going on. The UUID `e23732eb-2673-4f4a-a958-0cce0e7384e7` (I think it's a UUID) in the `template.yml` does not match the directory name `fb7f7e0a-f82c-4c0a-8baf-1a87d4f3bfc2`. Here is the file.

[template.zip](https://github.com/bottlesdevs/Bottles/files/9339816/template.zip)

**Comment by mirkobrombin** [comment]
> I saved the old templates directory and can easily reproduce it.
> 
> ```yaml
> custom_bottles_path: /meuk/Bottles
> notifications: []
> ```
> 
> What healthcheck are you talking about? I can't find anything in bottles.

press the hamburger menu (☰) at the top right. Then press "About Bottles", select "Troubleshooting", then "Debugging Information". Lastly, copy text and paste here.
