### ISSUE TITLE
[Request]: Adobe Reader DC installer requires mspatcha.dll

### ISSUE THREAD

**Issue by silviucc** [bottlesdevs/Bottles#1938]
### Tell us the problem or your need

Trying to install Adobe Reader DC with bottles will fail.

See this bug:
https://bugs.winehq.org/show_bug.cgi?id=12501

### Describe the solution you'd like

Winetricks provides a way to inject mspatcha.dll into the selected wine prefix. Ideally, Bottles would provide a way to do that too.

**Comment by mirkobrombin** [comment]
Please send a request here: https://github.com/bottlesdevs/dependencies

**Comment by silviucc** [comment]
Done. Thanks.
