### ISSUE TITLE
[Request] That you can import already existing prefixes

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#194]
**Is your feature request related to a problem? Please describe.**
I already have some prefixes and I want to add them instead of creating new prefixes and import all the files.

**Describe the solution you'd like**
That you can just import a prefix to Bottles.

**Comment by mirkobrombin** [comment]
Please follow the Request template for the issue.

**Comment by Toadfield** [comment]
changed it

**Comment by mirkobrombin** [comment]
To import prefixes created with systems other than Bottles v1, Lutris and POL, you have to proceed manually.

First of all create a custom bottle without versioning and with a stable version of Wine (for example Chardonnay or Lutris). Close Bottles and place the wineprefix you want to import in path `~/. local/share/bottles`. Copy the bottle configuration file you created earlier, inside the prefix you moved (or copied). Open and edit the configuration file, changing the name and path parameters.

Start Bottles again.
Please note that bottles not created with Bottles may not work. I don't support this operation.
