### ISSUE TITLE
"Launch in terminal" strange behavior (GUI vs CLI)

### ISSUE THREAD

**Issue by Loki-101** [bottlesdevs/Bottles#1943]
I have a program that will run in bottles and connect to a server, yet crashes halfway through the loading screen.

The only solution appears to be going into bottles, clicking the three dots next to the game, and choosing the "Launch with terminal" option. The game can then load into the server.

The weird part, besides having to run in the terminal, is that it MUST be done in exactly that way. I have tried adding Launch with terminal to the .desktop file, which does launch the program in the terminal, and it crashes halfway through loading into the server again. So I disabled it in the .desktop file and change bottles-cli run to bottles-cli shell thinking it would act the exact same as using the GUI; it still crashed. There appears to be some kind of difference between the two "Launch in terminal" methods I tried and the graphical interface clicking on the three dots and clicking "Launch with terminal" (The shelll icon)

![image](https://user-images.githubusercontent.com/59907407/184604166-6358656a-52b6-4740-8283-6cfa174a0fdb.png)

My question to anyone willing to help is this: Is there a way to replicate that Launch in terminal option EXACTLY in the command line interface?

Any/all advice is welcome. Thank you to anyone who takes time out of their day to hypothesize or give feedback. I really appreciate it.

**Comment by mirkobrombin** [comment]
Launch with terminal uses a minimal environment which disable some preferences, the software might be incompatible with your bottle settings

**Comment by Loki-101** [comment]
Thanks, I'll try disabling preferences one by one and see if I can get this work :D

**Comment by mirkobrombin** [comment]
Closing, feel free to add more comments
