### ISSUE TITLE
[Bug]: Can not manually add programs

### ISSUE THREAD

**Issue by b1zzu** [bottlesdevs/Bottles#1944]
### Describe the bug

I tried with different apps and I can't manually add programs to a bottle

### To Reproduce

1. Create a new Bottle called `Test`
2. Under programs click on the + 
3. Select `iexplore.exe` in `~/.var/app/com.usebottles.bottles/data/bottles/bottles/Test/drive_c/Program Files`

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.16-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 4103426048
    Free: 4103262208
RAM:
    MemTotal: 7.6GiB
    MemAvailable: 3.4GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I can add a program by editing the .yaml file and restart Bottles, but I would prefer to use the UI

**Comment by mirkobrombin** [comment]
I'm not able to replicate.
![image](https://user-images.githubusercontent.com/9479903/184820224-e86fd140-b4c6-4f14-b49a-02879e01e860.png)

try launching bottle from cli and check if drops some logs

**Comment by rsantellan** [comment]
@mirkobrombin same happens to me. I choose the program and is not added, starting from flatpack don't show any error.

**Comment by mirkobrombin** [comment]
Might be, I'll test

**Comment by mirkobrombin** [comment]
Not able to replicate, path with spaces works on my side. Might be another problem

**Comment by mirkobrombin** [comment]
Not able to replicate in any way. I'll close, feel free to provide more details.
