### ISSUE TITLE
Descriptions update for Legacy Tools

### ISSUE THREAD

**Issue by Knebergish** [bottlesdevs/Bottles#1945]
Hello all.
I have a suggestion for updating section "Details & Utilities" -> "Tools" -> "Legacy Tools".
Old view:
![LegacyTools](https://user-images.githubusercontent.com/10116459/184615964-16c082ab-0cb9-41b5-99fb-3fb73f4beea5.png)

My suggestion is:
1) Change "Legacy Tools" to "Legacy Wine Tools"
2) Completely remove the description of the items in this section, because it is completely clear from their names what they are doing.
2.1) Or, if it is necessary to keep these descriptions, simplify them in something like this:
```
Legacy Wine Tools \/

Explorer
    Browse internal files.
Task Manager
    Manage processes.
Debugger
    Debug Wine processes.
Configuration
    Adjust internal settings.
Uninstaller
    Uninstall programms.
Control panel
    Access the internal Control Panel.
```
It seems to me that this section will look cleaner this way.
What do you think about this? If you agree, I can create a PR.

**Comment by Knebergish** [comment]
Hello, @jannuary!
When you have time, could you take a look, please?

**Comment by jannuary** [comment]
I don't object to this. FWIW lot of strings aren't very clear or even gramatically correct in general, so this is a welcome change.

**Comment by Knebergish** [comment]
Thank you!
Do you think it's better to delete the item descriptions completely, or should we keep short descriptions?

**Comment by mirkobrombin** [comment]
I think we can simply remove them
