### ISSUE TITLE
[Bug]: DLL overrides not applying

### ISSUE THREAD

**Issue by keenanweaver** [bottlesdevs/Bottles#1946]
### Describe the bug

DLL overrides do not apply when using the DLL Overrides menu option.

### To Reproduce

1. Create a bottle
2. Click preferences --> DLL Overrides
3. Enter in a DLL (ddraw, for example)
4. Attempt to launch application/game
5. Application/game does not respect the override

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.1-arch2-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16786415616
    Free: 16786247680
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.5GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Problem can be worked around by editing launch options of a program in the programs list and adding 'WINEDLLOVERRIDES="dllName=n,b" %command%' or manually adding them with winecfg.

**Comment by mirkobrombin** [comment]
I'm not able to replicate
https://user-images.githubusercontent.com/9479903/184817844-431b6d1b-651e-43e5-b0aa-9fb614e6d755.mp4

**Comment by keenanweaver** [comment]
> I'm not able to replicate https://user-images.githubusercontent.com/9479903/184817844-431b6d1b-651e-43e5-b0aa-9fb614e6d755.mp4

Looks like I get the same behavior using the terminal to launch the executable as you do, so that's good. However, launching iexplore.exe as a program in the Programs tab instead of through the terminal makes iexplore.exe launch still. Do you experience the same?

**Comment by mirkobrombin** [comment]
This is normal as the programs view use the full path to the executable

**Comment by keenanweaver** [comment]
Oh, OK. Looks like I misunderstand what the feature is for. Editing individual programs with custom command arguments is intuitive enough, but is it feasible to add the same or similar DLL override UI to the preferences override section of a program? It seems to me that it's easier to have users click on something instead of adding command arguments.

**Comment by mirkobrombin** [comment]
I must have explained myself badly.

To record an override for all bottle programs you need to use DLL Overrides in your preferences. Launch options are not thinking for this purpose although it is possible to do so.

**Comment by keenanweaver** [comment]
OK, that is what I thought. To take it from the top, I initially thought DLL Overrides in preferences would override for all Bottles programs. I found that that was not the behavior for me, so I opened this issue. Since your video showed testing with the built-in terminal, I tried it again that way and found the DLL override _did_ work, the program just had to be launched through the terminal and not as a program in Bottles. So is the intended behavior for DLL Overrides to apply to applications in the Programs tab? Because if so, that is not what I am seeing. It seems like launching the same program through the Programs tab and through the built-in terminal results in a different outcome for each. Please forgive me, but I am not understanding why the programs view using the full path wouldn't make the DLL override work.

My use case is this: create a bottle for a game, set a DLL override to the whole bottle using the DLL Overrides preference, and add the game executable as a program (and eventually Library entry). The DLL overrides does not work in this case for me.

**Comment by mirkobrombin** [comment]
Might be something else as I'm still not able to replicate. Can you share your bottle.yml file?

**Comment by keenanweaver** [comment]
Here's a pretty replicatable setup, at least for me. If you want to recreate, here are the steps (or I can attached a full backup as well if you want.)

1. Download [Tomb Raider 2 demo](https://archive.org/details/TOMBRAI2)
2. Download [dgVoodoo2](https://github.com/dege-diosg/dgVoodoo2/releases)
3. Create a bottle (I use the gaming preset)
4. Run executable --> tr2demo2.exe. Install it wherever.
5. Extract the files from the dgVoodoo2 archive to the same directory you installed the demo: MS/x86/D3DImm.dll, MS/x86/DDraw.dll, dgVoodoo.conf, dgVoodooCpl.exe
6. Add TOMB2.EXE as a program in bottles
7. Set ddraw & d3dimm as DLL Overrides in the Bottles interface
8. Launch TOMB2.EXE through programs tab. Hit OK on the window. You should see this in game:

![2022-08-25_11-22](https://user-images.githubusercontent.com/37268985/186718825-6c0a933d-a1ff-453c-b7a3-b01d6cc47d4c.png)

However, what should be happening is dgVoodoo2 showing a watermark at the lower right corner. To make this work, edit the TOMB2.EXE program launch options to `WINEDLLOVERRIDES="ddraw=n,b;d3dimm=n,b" %command%`

Launch the game again and see this, override working correctly:

![2022-08-25_11-23](https://user-images.githubusercontent.com/37268985/186718844-da07fcac-c129-4656-a841-ce8cbfa9a478.png)

Here is the bottle.yml

```Arch: win64
Creation_Date: '2022-08-25 11:20:53.956140'
Custom_Path: false
DLL_Overrides:
    d3dimm: n,b
    ddraw: n,b
DXVK: dxvk-1.10.3
Environment: Gaming
Environment_Variables: {}
External_Programs:
    2d0ded70-3edf-4884-9e2a-c22a64c5e9e1:
        arguments: ''
        dxvk: true
        dxvk_nvapi: false
        executable: TOMB2.EXE
        folder: /home/keenan/.var/app/com.usebottles.bottles/data/bottles/bottles/tomb2demo/drive_c/tomb2
        fsr: false
        icon: com.usebottles.bottles-program
        id: 2d0ded70-3edf-4884-9e2a-c22a64c5e9e1
        name: TOMB2
        path: /home/keenan/.var/app/com.usebottles.bottles/data/bottles/bottles/tomb2demo/drive_c/tomb2/TOMB2.EXE
        pulseaudio_latency: true
        removed: null
        script: null
        virtual_desktop: false
        vkd3d: false
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
Language: sys
LatencyFleX: latencyflex-v0.1.0
Latest_Executables:
-   args: ''
    file: /run/user/1000/doc/dfb1cdaf/tr2demo2.exe
    name: tr2demo2.exe
NVAPI: dxvk-nvapi-v0.5.4
Name: tomb2demo
Parameters:
    custom_dpi: 96
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: true
    renderer: gl
    sandbox: false
    sync: esync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: false
    vmtouch: false
    vmtouch_cache_cwd: false
Path: tomb2demo
Runner: soda-7.0-3
Sandbox:
    share_net: true
    share_sound: true
State: 0
Uninstallers: {}
Update_Date: '2022-08-25 11:23:49.557057'
VKD3D: vkd3d-proton-2.6-1-5b73139
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
```

**Comment by mirkobrombin** [comment]
Ok I found the cause of the bug, I haven't been able to replicate with other executables but the bug exists.

**Comment by keenanweaver** [comment]
Thank you very much!
