### ISSUE TITLE
[Bug]: Can't run exe files from the file manager

### ISSUE THREAD

**Issue by Hairo** [bottlesdevs/Bottles#1948]
### Describe the bug

Running exe files from the file manager doesn't work again.

When running bottles in a terminal with:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bottles --file-forwarding com.usebottles.bottles file.exe
```

i get:
```
Invalid URI (syntax: bottles:run/<bottle>/<program>)
```

### To Reproduce

- Double click exe in file manager
- Nothing happens

### Package

Flatpak from Flathub

### Distribution

EndeavourOS

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.1-zen1-1-zen
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16788701184
    Free: 16788553728
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 27.8GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
I'm not able to replicate
https://user-images.githubusercontent.com/9479903/184816715-448b2b62-a133-45b1-8d32-2363031fb2a8.mp4

Same from terminal
![image](https://user-images.githubusercontent.com/9479903/184817006-d22f3764-85ef-4457-ba25-8ca6c7df909b.png)

**Comment by Hairo** [comment]
Seems to be a permissions issue, using flatseal to enable `filesystem=host` makes the dialog show but now apps won't launch, i only get this in the terminal:
```
14:12:35 (INFO) Forcing offline mode 
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
```
Using `Run executable...` from the bottle details window works.

**Comment by mirkobrombin** [comment]
I tested with a bunch of executables and always works. Can you try from another place?

**Comment by Hairo** [comment]
Apps not launching seems to be a flatpak issue(?) since i'm having some other issues too.

Have you tried with `filesystem=host` disabled? if it still works then might be my setup (though i didn't change anything in flatpak itself, this is my only app installed)

**Comment by mirkobrombin** [comment]
I use default bottles permissions, no host

**Comment by Hairo** [comment]
Sorry, using `filesystem=host` was for executables with multiple files (ie: .dll and such) in the same folder without moving the whole thing to the prefix (which is kinda inconvenient when testing the same exe with multiple bottles, but it's a flatpak thing).

I'm having issues with dxvk not working so it's probably something on my end, which is weird because the outdated version on AUR (2022.5.28) works fine, i'll just keep using that version until i figure out what's wrong, can close this.

**Comment by mirkobrombin** [comment]
Closing, feel free to add more comments and details.
