### ISSUE TITLE
[Request] Being able to set that steam prefixes automatically get added

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#195]
I want that every steam prefix automatically gets added with the same proton version as the game uses.
With that I could easily manage the files.

**Comment by mirkobrombin** [comment]
Same of #194 
When you create an issue there are two templates (Bug and Request), these contain instructions to correctly report a bug or request a feature. They serve to maintain order in the issues and help "the" developers to understand immediately what you are asking for.

**Comment by mirkobrombin** [comment]
Stems prefixes are a bit different from standard wineprefixes. There are already plans (I replied to a few issues about it) to increase the importer's support.I immediately exclude working on a function that automatically prefixes from other managers. This is not the Bottles concept, that aims to create and manage its own bottles. Also note that Bottles requires a configuration file for each bottle and use this to understand how it is created.Reproducing this process automatically can be risky, already at the moment a prefix imported from Lutris is modified by Bottles and the functionality of the software installed is not guaranteed.
