### ISSUE TITLE
Integrating with the Steam Flatpak: How?

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#1958]
Hi! :)

I have been scouring the tickets and https://docs.usebottles.com/components/runners and Google for an hour. I even checked the source code at https://github.com/bottlesdevs/Bottles/blob/72667c7b2911ec234ed1d2bbf96852d436d9a7cc/bottles/backend/managers/steam.py

I'm trying to run GE's Proton, which needs the Steam Runtime (Soldier).

Both Bottles and Steam are installed via Flatpak.

I can't enable the Steam Runtime checkbox, so it obviously can't find Steam.

1. Is the fix as easy as using Flatseal to add `~/.var/app/com.valvesoftware.Steam:ro` to Bottles permissions? Or should I add some more folders too?
2. Is read-only permissions fine, or should it be read-write? :)

Sorry for asking but I tried really hard to find the answer with no results. 🐱

Thank you so much for Bottles. It's incredibly good. I consider you a genius!

**Comment by mirkobrombin** [comment]
Yes, you must give Bottles the permission to access the steam path
`flatpak override --user com.usebottles.bottles --filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam`
