### ISSUE TITLE
[Request] Being able to set a standard wine version that every program uses

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#196]
What I mean is that you can select a default wine version that every program uses by default and if you change it,then every program that uses the default will also use that.
So it's more like how steam does it,so that you can still set a specific wine version.
I find that better,cause then all the programs could use the newest version and I don't have to change it manually.

**Comment by mirkobrombin** [comment]
Same of #194

**Comment by mirkobrombin** [comment]
This is already what happens in Bottles. Only it is bound to a single bottle. Also hot upgrading a version of Wine can cause dependency problems. I don't feel like taking responsibility for a function that could just lead to too many other issues to manage.


Please note that Bottle is NOT Lutris, his approach is use one bottle for multiple software and not one bottle for one software.
