### ISSUE TITLE
[Request]: Add devices toggle to dedicated sandbox

### ISSUE THREAD

**Issue by Froggy232** [bottlesdevs/Bottles#1963]
### Tell us the problem or your need

Hi,
The dedicated sandbox let set network and sound permission per bottle, but not devices permission.
It should allow that in order to let sandboxed games use the controller.
Thanks you
https://user-images.githubusercontent.com/72796064/184930201-d1de2fbc-a90a-4fb1-805d-e169f176b229.png

### Describe the solution you'd like

There should be a toggle for sharing devices

**Comment by mirkobrombin** [comment]
Tracking here  #1691
