### ISSUE TITLE
[Bug]: EasyTerm doesn't show anything.

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1966]
### Describe the bug

I was testing why an program stopped working so I needed to launch it with terminal window, but after selecting this option EasyTerm just showed empty window and the program didn't show either. I then checked it on things in my program list and none of them worked. Today I decided to rollback to previous update (2022.7.28-brescia-2) and EasyTerm worked but showed some weird stuff and didn't launch any programs after that:

> esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).

After updating to the newest version EasyTerm is still empty.

### To Reproduce

1. Go to your programs list
2. Click "open with terminal" button

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21 Cinnamon

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-46-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Not a bug, easyterm is showing what wine and the launched program wants to show, precisaly:
```
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\windows\system32\winemenubuilder.exe -r" (2).
```

which means:
- esync is enabled and running
- you are using a wine build with the RLIMIT_NICE bug (not a blocking thing)
- winemenubuilder not found (because is blacklisted in Bottles, so not a blocking thing)

You should check on WineDB why that programs won't run or open an issue in our programs repository.

**Comment by MrQuerter** [comment]
Even the "Command Line" tool in "Details & Utilities" tab launches empty window and I used to run that program many times with different runners in the past. But if you say so then I'm making another issue in programs repository.

**Comment by MrQuerter** [comment]
Update: it's Vmtouch fault. Turning it off returns every EasyTerm window back to normal.
