### ISSUE TITLE
[Bug]: Cannot edit existing drives in "manage drives", they reset after restarting Bottles

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#1967]
### Describe the bug

Unable to change custom drive letter paths after saving them the first time.

### To Reproduce

1. Add a custom drive in Bottles, let's say `~/custom`.
2. Quit and restart Bottles.
3. Go into "Manage Drives", click the "Browse" icon and select a different folder.
4. QUit and restart Bottles.
5. Look at the "Manage Drives" now. It is still the original path you selected at 1.

I was trying to change to the following custom path: `~/.var/app/com.usebottles.bottles/data/bottles/bottles/Games/drive_d` so I know that it isn't a sandboxing issue.

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.11-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 33621905408
    Free: 33621733376
RAM:
    MemTotal: 62.6GiB
    MemAvailable: 33.7GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Default drives are generated/managed by wine. Does it works via winecfg?

**Comment by Bananaman** [comment]
@mirkobrombin I'm sorry for being so terrible at following up.

I can confirm that the bug still happens in Bottles 50.1 (latest as of this writing).

# Start Bottles and add a drive (such as K). Set it to your "drive_c" path of your current bottle.

![01](https://user-images.githubusercontent.com/38923130/212954498-ba650b75-d9ee-40c0-b0d9-46e178fd0a3b.jpg)

![02](https://user-images.githubusercontent.com/38923130/212954546-b3328a46-c701-42ea-b0ed-379425487682.jpg)

# Restart Bottles

# Go into Manage Drives, click the "browse" icon next to "K:" and select a different path, I picked Internet Explorer's folder for no particular reason...

![03](https://user-images.githubusercontent.com/38923130/212954867-55c9f331-7103-4f8e-a8d0-a6831d18942c.jpg)

# You can see that the new path has been selected inside Bottles indeed...

![04](https://user-images.githubusercontent.com/38923130/212954950-2bee00f8-df99-4294-9e7e-2dc95ab9831d.jpg)

# Restart Bottles now

# Look in Manage Drives... the path is now reverted to the old path (not the subfolder we tried to change to):

![05](https://user-images.githubusercontent.com/38923130/212955057-7c64d7f4-b79b-4c2e-bbef-391e21b52133.jpg)

![06](https://user-images.githubusercontent.com/38923130/212955078-fb46ae12-d296-4218-b594-c67797a9371d.jpg)

# My conclusion is that Bottles isn't sending the "change location" command or registry edit to Wine. Perhaps it's because I am trying to change from a "drive_c" folder to another one. Perhaps Bottles has code which prevents that change?

**Comment by Bananaman** [comment]
@mirkobrombin Interestingly, using winecfg I am able to change the K: drive to any other paths I want. The changes will be instantly seen in Bottles "Manage Drives".

So I tried changing it to `drive_c/Program Files` in Winecfg and it worked. Then I tried changing this "Program Files" path to something else via Bottles "Manage Drives" and yet again it didn't work.

So the conclusion is that Bottles isn't performing the requested changes.

**Comment by DerKoll0** [comment]
Hey,
i have essentually the same problem.
For me it seems the problem started after having an SD-Card in my slot and starting Bottles. All my drives except C had been "randomized" and showed something else like /home or /dev/sd0. In winecfg there had been no entries except c and d which refered to the SDCard. I deleted that, but still in Bottles i had all drives messed up. Couldnt delete anything, but add a new drive and that would be persistent. I could even delete it again and it stayed deleted. By now the situation is that i can change D: and changes are persistent. The rest i can change, but changes are not saved. And i cant delete those drives...

**Comment by DerKoll0** [comment]
I found a solution that at least helped me in my case.
Apparently the drives are saved as an actual folder in the folder of your Bottle. .....com.usebottles.bottles/data/bottles/bottles/(yourbottle)/dosdevices. There you will find the drives as named folder. I just deleted the "dead ones" and after that everything worked fine again.
