### ISSUE TITLE
[Bug]: bottles-cli doesn't accept anything with spaces

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1969]
### Describe the bug

I decided to check bottles-cli and while I had some success, but that's for another issue, anything that had spaces in the path didn't work. I tried all escaping methods: "x x", 'x x', x\ x and none of them worked. Moving the programs to a folder without spaces made it work. For example I moved notepad++ to a new folder "note pad" and then tried to run it with bottle-cli. Exact same error appeared.

`flatpak run --command=bottles-cli com.usebottles.bottles run -b notepad -e "/home/username/.var/app/com.usebottles.bottles/data/bottles/bottles/notepad/drive_c/note pad/notepad++.exe"`

Posting as picture because formatting issues with ` when pasted here:
![2022-08-21_19-18-08](https://user-images.githubusercontent.com/84787215/185803097-e5a38b67-3d0e-4ad4-a0c6-d09e2570b34e.png)

### To Reproduce

1. Copy any of your program files to a folder in the same bottle, but with spaces
2. Run it with bottles-cli in terminal remembering to escape the spaces
3. Observe the error

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21 Cinnamon

### Troubleshooting Logs

```shell
Version: 2022.8.14-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-46-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.8GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Not able to replicate

**Comment by MrQuerter** [comment]
Found the issue. Vmtouch. I had it on. Turning it off makes it possible to run programs with spaces in their path:
![2022-08-21_23-21-12](https://user-images.githubusercontent.com/84787215/185811428-730414f8-cdbe-40c9-baec-addcb9e89672.png)

**Comment by mirkobrombin** [comment]
tracking here #1977
