### ISSUE TITLE
[Request]: Library mode improvements

### ISSUE THREAD

**Issue by Lekrixsss** [bottlesdevs/Bottles#1973]
### Tell us the problem or your need

Add a feature to connect GOG, Epic games, Ubisoft connect, Steam, Origin and other accounts to see and install all games you own from library mode like in heroic and lutris.

### Describe the solution you'd like

Add a menu with connected accounts somewhere in bottles settings.
Add a feature to see games you own in library mode.
Add a feature to install games from library mode.
Add a feature to install every game in different bottle.

### Additional context and references

Also add an feature to install every game in different bottle.

**Comment by mirkobrombin** [comment]
It’s out of context. Bottles is a wine prefix manager, not a gaming platform. If you want epic, Ubisoft integrations, just install the official application and enable our integrations.
