### ISSUE TITLE
[Request]: Remove sync methods

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#1980]
### Tell us the problem or your need

![image](https://user-images.githubusercontent.com/50847364/186559783-bb9998d3-d796-4393-8616-7b6afc5fbbac.png)

This particular set of options is really confusing, unclear and vary per distribution and runner, as some runners and distributions can have certain features, while others might not. There's no easy way to tell which one is supported by the runner and distribution.

### Describe the solution you'd like

Remove this option completely.

### Other solutions?

Users can add more environments using the Environment Variables option.

### Additional context and references

Related comment: https://github.com/bottlesdevs/Bottles/issues/1198#issuecomment-1218485008.

**Comment by mirkobrombin** [comment]
Managing syncs as env var is not recommended as one cancels the other. In addition, changing the sync requires restarting the prefix so the user should not only know the exact variable to set but also know that he will have to manually restart the prefix. I am working on a way to identify support.

Today almost all runners offer all types of syncs and kernels are patched to support them.

**Comment by TheEvilSkeleton** [comment]
> I am working on a way to identify support.

Should we reopen https://github.com/bottlesdevs/Bottles/issues/1198?

**Comment by mirkobrombin** [comment]
Yes. My solution is defining which sync each runner supports in our repository
