### ISSUE TITLE
[Bug]: Add custom exe does not appear

### ISSUE THREAD

**Issue by thierrybo** [bottlesdevs/Bottles#1982]
### Describe the bug

I have an old game (no installer) that I try to add the exe but nothing appears.

First the directory was outside the bottle. Then I copied the whole directory inside the bottle (.ie ~/.var/app/com.usebottles.bottles/data/bottles/bottles/TALONSOFT-TOAOW-CenturyOfWarfare-2000/drive_c/Games/TOAW Century of Warfare/) 
but it did not helped.

The game run fine but I have to select the exe each time.

### To Reproduce

Select the exe as per (https://docs.usebottles.com/bottles/programs#add-sustom-programs) 

### Package

Flatpak from Flathub

### Distribution

Devuan testing

### Troubleshooting Logs

```shell
Note: the "Debugging Information" says "Distro:Name: GNOME" but actually there is only Openbox  window manager installed.

Version: 2022.8.14-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.0-4-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8361324544
    Free: 8361172992
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.2GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Any useful output launching bottles from your terminal?

**Comment by thierrybo** [comment]
Well I'm confused because from the command line it works ... (I use the same command as the "exec" line is .desktop file).

` /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bottles --file-forwarding com.usebottles.bottles
14:25:03 (INFO) Bottles Started!
14:25:04 (INFO) Catalog components loaded
14:25:04 (INFO) Catalog installers loaded
14:25:05 (INFO) Catalog dependencies loaded
14:25:05 (INFO) Performing Bottles checks…
14:25:05 (INFO) Dxvks found:
	 - dxvk-1.10.3

14:25:05 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6-1-5b73139

14:25:05 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4

14:25:05 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0

14:25:05 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-3

14:25:06 (INFO) Bottles found:
	 - TALONSOFT TOAOW CenturyOfWarfare 2000 v102
	 - test
	 - Strategic Command 2


(bottles:2): Gtk-WARNING **: 14:25:06.996: Failed to set property AdwActionRow.visible to faux: Could not parse boolean 'faux'

(bottles:2): Gtk-WARNING **: 14:25:07.002: Failed to set property AdwActionRow.visible to faux: Could not parse boolean 'faux'

(bottles:2): Gtk-WARNING **: 14:25:07.004: Failed to set property AdwActionRow.visible to faux: Could not parse boolean 'faux'
14:25:07 (INFO) Library saved

(bottles:2): Gtk-WARNING **: 14:26:09.737: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
14:26:09 (INFO) Setting Key 642b6daa-9a4b-42b2-b8bc-d4c81da1042a={'executable': 'Opart CW.exe', 'name': 'Opart CW', 'path': '/home/thierrybo/.var/app/com.usebottles.bottles/data/bottles/bottles/TALONSOFT-TOAOW-CenturyOfWarfare-2000/drive_c/Games/TOAW Century of Warfare/Opart CW.exe', 'id': '642b6daa-9a4b-42b2-b8bc-d4c81da1042a'} for bottle TALONSOFT TOAOW CenturyOfWarfare 2000 v102…

(bottles:2): Gtk-WARNING **: 14:26:35.067: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
`

**Comment by mirkobrombin** [comment]
I tested some executables with spaces and special chars and all works. Idk what to debug in this case

**Comment by thierrybo** [comment]
Never mind. Now it works well running normally from the menu.
