### ISSUE TITLE
[Bug]: apps only see 4gb of available space

### ISSUE THREAD

**Issue by allaeddineomc** [bottlesdevs/Bottles#1988]
### Describe the bug

whenever i launch an app that checks for free space before doing an action it only sees 4gb of free space and in many cases 4gb isn't enough so i can't do that action even though i have 100gb of free space , i'm using flatpak bottles and i'm suspecting this is a flatpak issue .

### To Reproduce

.

### Package

Flatpak from Flathub

### Distribution

fedora silverblue 36

### Troubleshooting Logs

```shell
.
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

.

**Comment by mirkobrombin** [comment]
It's a flatpak issue, we are tracking this in the programs repository for the EA games app (the bug is not EA related).
