### ISSUE TITLE
[Bug]: Dark mode switcher doesn't show up

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#1990]
### Describe the bug

After newest update dark mode switcher disappeared. Not that I need it currently since it remembered to stay in dark mode, but it should be there since Mint doesn't yet support the automatic detection that Bottles uses (and I checked it today again).

### To Reproduce

1. Update Bottles to 2022.08.28
2. Open preferences in the menu
3. Observe the option not being there

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21 Cinnamon

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-46-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.7GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by jannuary** [comment]
Can't replicate on Fedora 34, but can on Mint 21 - either way, we can't do much if Linux Mint lies about supporting the preference.
![Screenshot from 2022-08-28 14-05-28](https://user-images.githubusercontent.com/27908024/187061947-304db320-6bd7-4552-af07-4eccb231bb8d.png)

**Comment by MrQuerter** [comment]
You could just leave this option without hiding it. It doesn't take that much space.

**Comment by mirkobrombin** [comment]
It would create too much confusion for those using the system dark mode and switching this would not see any results.
