### ISSUE TITLE
[Bug]: bottles refuses to load, even after reinstalling and updating.

### ISSUE THREAD

**Issue by effcol** [bottlesdevs/Bottles#1991]
### Describe the bug

I had the same issue nearly a month ago, reported it here: https://github.com/bottlesdevs/Bottles/issues/1893
the bug log looks different though, and it was marked resolved, so I updated in the Discover store, and since then with every update it still refuses to open when I open it, just showing this bug log, but wont submit it is I try and press submit.

It stays indefinitely on 'starting up' with 'fetched 3 of 3 packages' at the bottom.

### To Reproduce

Open Bottles

### Package

Flatpak from Flathub

### Distribution

SteamOS 3.3

### Troubleshooting Logs

```shell
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Katawa-Shoujo/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 841, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 796, in process_bottle
    self.update_config(

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 901, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

On the Steam Deck

**Comment by mirkobrombin** [comment]
Delete the folder mentioned in the log

**Comment by effcol** [comment]
None of the folders in the logs exist though, so there's nothing to delete? I've looked and looked, but even the log itself says the folders don't exist.

**Comment by mirkobrombin** [comment]
Try resetting bottles, delete
.var/app/com.usebottles.bottles/data
This stuff is not removed when uninstalling bottles.

**Comment by effcol** [comment]
Ahh thank you I figured it out, I hadn't realised I needed to show hidden folders and that .var wasn't located in root, so was looking in the wrong place!
Sorry for the misunderstanding, and thank you for helping :)

**Comment by mirkobrombin** [comment]
No worry, I'm glad you solved it.
