### ISSUE TITLE
[Request]: Configuration to Disable Network Access Inside Bottle

### ISSUE THREAD

**Issue by dbready** [bottlesdevs/Bottles#1992]
### Tell us the problem or your need

More and more software embeds telemetry and/or otherwise tries to phone home without my permission. It would be great if there was a way to specify a Bottle as Offline Only and disable all network access for installed programs.

Example, the change to [Audacity](https://github.com/audacity/audacity/pull/835) to include telemetry for what is ostensibly an offline only program. Similar with Unity game telemetry for single player games.

### Describe the solution you'd like

A per Bottle configuration option to disable network access.

### Other solutions?

Flatpak likely provides the mechanism to disable network access for the entire Bottle runtime, but I think it would be an improvement if this capability existed in band. This would then give the user the ability to momentarily override the configuration if required. Would also then be possible for Bottle to be aware of the no-network state and highlight it in the GUI.

**Comment by axtloss** [comment]
This already exists, you'll have to enable pet bottle sandboxes in the bottles settings and then you can disable network in the preferences of the bottle.

**Comment by dbready** [comment]
My apologies, but could you be a bit more specific? I cannot find any reference to "pet bottle" in the documentation or the forum. Nor where the network preferences is located.

**Comment by axtloss** [comment]
Sorry about that, seems like autocorrect changed stuff without me noticing.
You'll first have to go to the bottles preferences located in the Hamburger Menü
Then go to the last tab "experiments"
And enable per bottle sandboxes
Then go to the bottle you want to restrict and go to the preferences of the bottle, scroll down until you see an option mentioning "sandbox" there you can disable network access

**Comment by dbready** [comment]
Great, thanks for the additional instructions. Unfortunately, the only Experiment showing up in my installation is for Library. Different issue, so I will have to poke around and determine why I am not pulling in all experimental features. Regardless, your instructions were specific enough that I should be able to get what I hoped once I can crack this other problem.

Appreciate the help.

**Comment by axtloss** [comment]
How did you install bottles? The latest release shouldn't have the library mode as an experiment.

**Comment by dbready** [comment]
Flatpak. I just ran `flatpak update` and now see the Sandbox experiment. Had not thought to run update in a while, so my own bad.
