### ISSUE TITLE
[Bug]: Add to Steam does not work

### ISSUE THREAD

**Issue by RickAndTired** [bottlesdevs/Bottles#1994]
### Describe the bug

Add to Steam does not work

In Flatseal I added `~/.steam` to my Filesystem permissions 

Running Bottles through the terminal gives me this output when I click `Add to Steam`

`(WARNING) Userdata path is not set `

### To Reproduce

1. Open a bottle
2. Click on a program's 3dot menu
3. Click `Add to Steam`
4. Receive this error `(WARNING) Userdata path is not set `
5. Restart Steam
6. Program is not in Steam Library

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-46-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8340484096
    Free: 8340336640
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 11.5GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Flatseal has `~/.steam` added
I've tried clicking on `Add to Steam` with Steam running and with Steam not running

**Comment by mirkobrombin** [comment]
Does .steam/userdata/<user>/config/localconfig.vdf exists?

**Comment by RickAndTired** [comment]
> Does .steam/userdata//config/localconfig.vdf exists?

No, it's `.steam/debian-installation/userdata/########/config/localconfig.vdf`

**Comment by mirkobrombin** [comment]
That’s the problem, bottles doesn’t support this path. I’ll fix with next release
