### ISSUE TITLE
[Request]: please upgrade to latest GE-Proton/GE-Wine

### ISSUE THREAD

**Issue by lemonzest79** [bottlesdevs/Bottles#1995]
### Tell us the problem or your need

Please upgrade to the latest versions of the GloriousEggroll GE runners (Proton/Wine/Lutris) as Bottles is a few versions behind latest, thanks.

### Describe the solution you'd like

Their current versions are:

Lutris-GE-7.0-5
Wine-GE-Proton7-26
GE-Proton7-30

Previous versions would also be nice, thanks

**Comment by mirkobrombin** [comment]
Wrong repository. The correct one is "components".
The repository is community-driven maintainers.usebotles.com
