### ISSUE TITLE
[Crash report]  'NoneType' object has no att

### ISSUE THREAD

**Issue by radleydark** [bottlesdevs/Bottles#1999]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.8.28-brescia-1

**Log**
```python3
'NoneType' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    if program.get("dxvk") != dxvk:

```

**Comment by mirkobrombin** [comment]
Already fixed https://github.com/bottlesdevs/Bottles/blob/6642b55a7145d9d6cb26a44a9c5ae664f21d99f4/bottles/backend/wine/executor.py#L85
