### ISSUE TITLE
[Bug]: Add Desktop Entry does not work

### ISSUE THREAD

**Issue by ChaosBlades** [bottlesdevs/Bottles#2002]
### Describe the bug

I am trying to add a desktop entry for Autodesk Fusion 360 but it just sends me to the page on how to enable it. I have ran the flatpak override and even went as far as to reboot the PC but it still just sends me to the web page. When viewing the video on how to do it via the GUI my applications menu does not list the options that are in the video.

### To Reproduce

1. Try to click 'Add Desktop Entry' and be sent to the web page on how to enable this feature.
2. Close Bottles
3. Run `sudo flatpak override com.usebottles.bottles --filesystem=xdg-data/applications`
4. Open Bottles
5. Try to click 'Add Desktop Entry' again and be sent to web page even though the feature should be enabled.

### Package

Flatpak from Flathub

### Distribution

Pop!_OS 22.04 LTS x86_64

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-76051900-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16780320768
    Free: 16780173312
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Use the `--user` flag to set the override. There is a wrong instruction in our documentation which I'm going to fix.

```
flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications
```

**Comment by ChaosBlades** [comment]
I finally realized in the video it was using Flatseal and not the normal Gnome applications window in settings. They look almost the same. My fault on that one.

I resolved this by adding `~/.local/share/applications` in Flatseal.

**Comment by Faugus** [comment]
I'm on Arch Linux, using the AUR packaged and "Add Desktop Entry" does nothing.
