### ISSUE TITLE
[Request]: A way to delete entry from library

### ISSUE THREAD

**Issue by Deissson** [bottlesdevs/Bottles#2003]
### Tell us the problem or your need

You can add apps to library, but cant delete them, this may result in duplicated entries

### Describe the solution you'd like

a menu that appears on right click

### Other solutions?

menu button (3 dotted button) that appears when hovering over an entry ()

**Comment by mirkobrombin** [comment]
To remove a program from your library, you simply go to its context menu (top left of the cover) and choose “Remove from Library,” this does not remove the program from the bottle but only from the library.
