### ISSUE TITLE
[Bug]: Infinite loop trying to download soda on first run

### ISSUE THREAD

**Issue by JMS55** [bottlesdevs/Bottles#2004]
### Describe the bug

Bottles is stuck downloading soda in an infinite loop on first run, preventing me from using bottles. There should probably be a max-retries.

### To Reproduce

1. Install bottles
2. Click continue on the welcome screen
3. Wait forever

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
11:31:27 (INFO) Renaming [soda-7.0-3-x86_64.tar.xz] to [soda-7.0-3-x86_64.tar.xz]. 
11:31:36 (ERROR) Extraction failed! Archive ends earlier than expected. 
11:31:36 (INFO) Runners found:
	 - sys-wine-7.0
 
11:31:36 (WARNING) No runners found. 
// The same thing keeps happening again, forever
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by JMS55** [comment]
Looks similar to https://github.com/bottlesdevs/Bottles/issues/1345.

Bottles should definitely have a max retries for this download, and popup an error window when that fails (there's no indication that bottles is stuck in an infinite loop, I had to run it from the terminal and check the logs).

**Comment by JMS55** [comment]
Reinstalling fixed the issue.

**Comment by mirkobrombin** [comment]
I'm not able to replicate in any way.
The official repository works for me. I've tried a custom one forcing a broken archive to replicate but it fails the first time and just give up.

I need more details in some way.

**Comment by JMS55** [comment]
I think this might have been because I was low on disk space. I cleared up some space and it succeeded.

**Comment by mirkobrombin** [comment]
Closing, I'll evaluate some feedback in the onboard.
ping #1598
