### ISSUE TITLE
[Bug]: Can't create bottle

### ISSUE THREAD

**Issue by JMS55** [bottlesdevs/Bottles#2005]
### Describe the bug

Creating a bottle fails

### To Reproduce

1. Create bottle
2. Change to application
3. Enter any bottle name
4. Press create

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Fusion360__172/drive_c/users'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1208, in create_bottle
    for user in os.listdir(f"{bottle_complete_path}/drive_c/users"):
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

I couldn't report this bug through the auto crash reporter. The link it opened was just a blank page:

https://github.com/bottlesdevs/Bottles/issues/new?assignees=mirkobrombin&labels=crash&title=%5BCrash%20report%5D+%20%5BErrno%202%5D%20No%20such%20file%20or%&body=This%20crash%20report%20was%20generated%20by%20Bottles.%0A%0A**Details**%0A*%20**package**:%20Flatpak%0A*%20**version**:%202022.8.28-brescia-2%0A%0A%0A**Log**%0A```python3%0A%5BErrno%202%5D%20No%20such%20file%20or%20directory%3A%20%27/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Fusion360__172/drive_c/users%27%20%20File%20%22/app/share/bottles/bottles/frontend/utils/threading.py%22%2C%20line%2063%2C%20in%20__target%0A%20%20%20%20result%20%3D%20self.task_func%28%2Aargs%2C%20%2A%2Akwargs%29%0A%0A%20%20File%20%22/app/share/bottles/bottles/backend/managers/manager.py%22%2C%20line%201208%2C%20in%20create_bottle%0A%20%20%20%20for%20user%20in%20os.listdir%28f%22%7Bbottle_complete_path%7D/drive_c/users%22%29%3A%0A%0A```

**Comment by mirkobrombin** [comment]
Try deleting the templates folder in ~/.var/app/com.usebottles.bottles/data/bottles and and be sure soda is installed in the runner section
