### ISSUE TITLE
[Feedback]: Remove fake variable __GL_DXVK_OPTIMIZATIONS

### ISSUE THREAD

**Issue by mphojele** [bottlesdevs/Bottles#2009]
### Describe the bug

This variable doesn't exist anywhere and also doesn't make sense because the variables with __GL are nvidia related and there's no way nvidia would now just create a variable to optimise DXVK(see: [What does env variable "__GL_DXVK_OPTIMIZATIONS" do?](https://www.reddit.com/r/linux_gaming/comments/whjlcy/comment/ij8ds4o/?utm_source=share&utm_medium=web2x&context=3)). So I suggest we remove: https://github.com/bottlesdevs/Bottles/blob/d13eedc4e85584abddbf2e713d98fd8f637a87c4/bottles/backend/wine/winecommand.py#L237

### To Reproduce

N/A

### Package

Flatpak from Flathub

### Distribution

N/A

### Troubleshooting Logs

```shell
N/A
```

**Comment by mphojele** [comment]
In hindsight I should have chosen discussion template for this

**Comment by mirkobrombin** [comment]
Thanks for the tip
