### ISSUE TITLE
[Bug]: X Error of failed request using multitouch-gesture

### ISSUE THREAD

**Issue by Emporea** [bottlesdevs/Bottles#2010]
### Describe the bug

Every program i open immidiatly crashes when i switch to another workspace via multitouchgesture on the touchpad.

### To Reproduce

Open program.
Swipe to another workspace with 3 finger gesture on gnome

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  25109
  Current serial number in output stream:  25109
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
X Error of failed request:  BadMatch (invalid parameter attributes)
    Minor opcode of failed request:  28Major opcode of failed request:  131 (XInputExtension)
 (X_GetDeviceButtonMapping)
  Minor opcode of failed request:  28  Serial number of failed request:  197 (X_GetDeviceButtonMapping)

  Current serial number in output stream:  197  
Serial number of failed request:  492
  Current serial number in output stream:  492
```

### Display Protocol

Wayland

### Display Backend used by Bottles

X11

### Additional context

Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.4-1.surface.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 3952750592
    Free: 3952599040
RAM:
    MemTotal: 7.4GiB
    MemAvailable: 3.6GiB
Bottles_envs: null

**Comment by mirkobrombin** [comment]
Sounds like a wine or system related problem
