### ISSUE TITLE
[Bug]: Lucon font cannot be installed

### ISSUE THREAD

**Issue by ramarivera** [bottlesdevs/Bottles#2011]
### Describe the bug

Cannot install lucon dependency

### To Reproduce

1. Create a new bottle (either custom or gaming)
2. Try to install lucon dependency

### Package

Flatpak from Flathub

### Distribution

Arch Linux (Steam Deck)

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778525184
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by ramarivera** [comment]
For some reason I tried again today and I could install lucon without issues. Maybe some kind of cache or faulty network?

Anyway, feel free to close this bug if it works for you

**Comment by mirkobrombin** [comment]
Should have been fixed by https://github.com/bottlesdevs/dependencies/commit/1dd3a20dc6943fcb2bc19455786c98f40a64b1b9

**Comment by ramarivera** [comment]
Nice, thanks!
