### ISSUE TITLE
Send report link not working

### ISSUE THREAD

**Issue by ramarivera** [bottlesdevs/Bottles#2012]
I got a crash report and wanted to report it.

I clicked on report, it opened a github tab, but I got HTTP 400.

Generated URL:
https://github.com/bottlesdevs/Bottles/issues/new?assignees=mirkobrombin&labels=crash&title=%5BCrash%20report%5D+%20Given%20version%20is%20not%20supported.%&body=This%20crash%20report%20was%20generated%20by%20Bottles.%0A%0A**Details**%0A*%20**package**:%20Flatpak%0A*%20**version**:%202022.8.28-brescia-2%0A%0A%0A**Log**%0A```python3%0AGiven%20version%20is%20not%20supported.%20%20File%20%22/app/share/bottles/bottles/frontend/utils/threading.py%22%2C%20line%2063%2C%20in%20__target%0A%20%20%20%20result%20%3D%20self.task_func%28%2Aargs%2C%20%2A%2Akwargs%29%0A%0A%20%20File%20%22/app/share/bottles/bottles/backend/wine/regkeys.py%22%2C%20line%2035%2C%20in%20set_windows%0A%20%20%20%20raise%20ValueError%28%22Given%20version%20is%20not%20supported.%22%29%0A%0A```

**Comment by mirkobrombin** [comment]
Closed by https://github.com/bottlesdevs/Bottles/commit/98e7e1b927e8c0a6e98943f59e396df16f49cea1
