### ISSUE TITLE
[Bug]: Consolas font installation fails silently 

### ISSUE THREAD

**Issue by ramarivera** [bottlesdevs/Bottles#2014]
### Describe the bug

Installing the Consolas font from Dependencies seems to work, but font files are not copied to C/Windows/Fonts, only Registry keys are written.

### To Reproduce

1. Create a new Gaming bottle
2. Install Consolas
3. Open the Explorer for that Bottel
4. Navigate to C:/Windows/Fonts
5. The consola files are not present

### Package

Flatpak from Flathub

### Distribution

Arch Linux (Steam Deck)

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778525184
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 9.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

21:02:50 (INFO) Installing dependency [consolas] in bottle [Ever 117]. 
consolas-fonts-tts.tar.bz2 (94%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (444.0KiB/471.4KiB - 226.4KiBconsolas-fonts-tts.tar.bz2 (94%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (445.0KiB/471.4KiB - 226.8KiBconsolas-fonts-tts.tar.bz2 (94%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (446.0KiB/471.4KiB - 227.3KiBconsolas-fonts-tts.tar.bz2 (94%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (447.0KiB/471.4KiB - 227.8KiBconsolas-fonts-tts.tar.bz2 (95%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (448.0KiB/471.4KiB - 228.3KiBconsolas-fonts-tts.tar.bz2 (95%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (449.0KiB/471.4KiB - 228.8KiBconsolas-fonts-tts.tar.bz2 (95%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (450.0KiB/471.4KiB - 229.3KiBconsolas-fonts-tts.tar.bz2 (95%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (451.0KiB/471.4KiB - 229.8KiBconsolas-fonts-tts.tar.bz2 (95%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (452.0KiB/471.4KiB - 230.3KiBconsolas-fonts-tts.tar.bz2 (96%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (453.0KiB/471.4KiB - 230.8Kiconsolas-fonts-tts.tar.bz2 (96%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (454.0KiB/471.4KiB - 231.3Kiconsolas-fonts-tts.tar.bz2 (96%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (455.0KiB/471.4KiB - 231.8Kiconsolas-fonts-tts.tar.bz2 (96%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (456.0KiB/471.4KiB - 228.6Kiconsolas-fonts-tts.tar.bz2 (96%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (457.0KiB/471.4KiB - 229.0Kiconsolas-fonts-tts.tar.bz2 (97%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (458.0KiB/471.4KiB - 229.5Kiconsolas-fonts-tts.tar.bz2 (97%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (459.0KiB/471.4KiB - 230.0Kiconsolas-fonts-tts.tar.bz2 (97%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (460.0KiB/471.4KiB - 230.5Kiconsolas-fonts-tts.tar.bz2 (97%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (461.0KiB/471.4KiB - 231.0Kiconsolas-fonts-tts.tar.bz2 (98%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (462.0KiB/471.4KiB - 231.5Kconsolas-fonts-tts.tar.bz2 (98%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (463.0KiB/471.4KiB - 232.0Kconsolas-fonts-tts.tar.bz2 (98%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (464.0KiB/471.4KiB - 232.5Kconsolas-fonts-tts.tar.bz2 (98%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (465.0KiB/471.4KiB - 233.0Kconsolas-fonts-tts.tar.bz2 (98%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (466.0KiB/471.4KiB - 233.4Kconsolas-fonts-tts.tar.bz2 (99%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (467.0KiB/471.4KiB - 233.9Kconsolas-fonts-tts.tar.bz2 (99%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (468.0KiB/471.4KiB - 234.4Kconsolas-fonts-tts.tar.bz2 (99%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (469.0KiB/471.4KiB - 234.9Kconsolas-fonts-tts.tar.bz2 (99%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (470.0KiB/471.4KiB - 235.4Kconsolas-fonts-tts.tar.bz2 (99%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (471.0KiB/471.4KiB - 235.9Kconsolas-fonts-tts.tar.bz2 (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (472.0KiB/471.4KiB - 236.2KiB)

patool: Extracting /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar.bz2 ...
patool: running /usr/bin/tar --extract -j --file /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar.bz2 --directory /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar
patool: ... /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar.bz2 extracted to `/home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar'.
21:02:54 (WARNING) Font Consolas-Bold.ttf already exists or is not found. 
21:02:54 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Consolas Bold] and Data: [Consolas-Bold.ttf] in Ever 117 registry 
21:02:54 (INFO) Using Wine Registry CLI -- add 
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
21:02:54 (INFO) reg: The operation completed successfully

 
21:02:54 (WARNING) Font Consolas-Bold-Italic.ttf already exists or is not found. 
21:02:55 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Consolas Bold Italic] and Data: [Consolas-Bold-Italic.ttf] in Ever 117 registry 
21:02:55 (INFO) Using Wine Registry CLI -- add 
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
21:02:55 (INFO) reg: The operation completed successfully

 
21:02:55 (WARNING) Font Consolas-Italic.ttf already exists or is not found. 
21:02:55 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Consolas Italic] and Data: [Consolas-Italic.ttf] in Ever 117 registry 
21:02:55 (INFO) Using Wine Registry CLI -- add 
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
21:02:56 (INFO) reg: The operation completed successfully

 
21:02:56 (WARNING) Font Consolas-Regular.ttf already exists or is not found. 
21:02:56 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Consolas Regular] and Data: [Consolas-Regular.ttf] in Ever 117 registry 
21:02:56 (INFO) Using Wine Registry CLI -- add 
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
21:02:56 (INFO) reg: The operation completed successfully

 
21:02:56 (INFO) Setting Key Installed_Dependencies=['d3dx9', 'msls31', 'arial32', 'times32', 'courie32', 'd3dcompiler_43', 'd3dcompiler_47', 'lucon', 'consolas', 'consolas'] for bottle Ever 117… 
21:02:56 (INFO) Dependency installed: consolas in Ever 117

**Comment by mirkobrombin** [comment]
fixed by https://github.com/bottlesdevs/dependencies/commit/c0e1d4da51bbcb8a5a766b1af162bd22d7a2e74c
