### ISSUE TITLE
[Request]: Will start to check increase the manual update mode or at system startup check only once (check)

### ISSUE THREAD

**Issue by AsimovGod** [bottlesdevs/Bottles#2021]
### Tell us the problem or your need

  Even in a good state of network environment, startup still reached 20s. Bad network conditions can be up to 3 minutes or more. I noticed this because I checked Bottles every time I started it.
Unfortunately, my web environment doesn't have smooth access to github for the most part.  

```
03:44:09 (INFO) Dxvks found:
         - dxvk-1.10.3
 
03:44:09 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
 
03:44:09 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
03:44:09 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
03:44:09 (INFO) Runners found:
         - sys-wine-7.0
         - soda-7.0-3
```  

 I don't know whether this is a bug, because it seems to be the local self-check, but indeed will be affected by the network.

### Describe the solution you'd like

Although it provides a way to shut down the network, it is not a long-term solution. If possible, I would like to change the check to or add a manual check or a timed check. Instead of reading data from the network every time, you can just check for dependencies every time you start.

**Comment by mirkobrombin** [comment]
Use `FORCE_OFFLINE=1` to force offline mode. We can't skip those checks until the new backend is ready.

**Comment by AsimovGod** [comment]
> Use `FORCE_OFFLINE=1` to force offline mode. We can't skip those checks until the new backend is ready.

In fact, when I was disconnected from the network (completely disconnected from the host network) , Bottles opened very quickly without any problems.

If these checks you think really can not be missing, then whether it can improve the startup speed, especially when the network environment is poor. For example, an offline check (keep an offline check list) .

Alternatively, whether or not a system tray and daemon can be provided that does not automatically exit after a single opening (it is better to check only once than every time you open it) .

**Comment by mirkobrombin** [comment]
I'm already working to improve this by rewriting the whole backend, rethinking the repository system

**Comment by chinh4thepro** [comment]
`18:58:28 (INFO) Bottles Started! 
19:13:50 (INFO) Catalog components loaded 
19:16:01 (INFO) Catalog installers loaded 
19:18:12 (INFO) Catalog dependencies loaded 
19:18:12 (INFO) Performing Bottles checks… 
19:18:12 (INFO) Dxvks found:
	 - dxvk-1.10.3
 
19:18:12 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6-1-5b73139
 
19:18:12 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
19:18:12 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
19:18:12 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-3
	 - wine-ge-7-27
 
19:18:30 (INFO) Bottles found:
	 - gaming
 
19:18:30 (INFO) Library saved 

`
