### ISSUE TITLE
[Request]: Import and Export files and directories to other wine prefixes

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#2025]
### Tell us the problem or your need

Import and Export files and directories to other wine prefixes
![Screenshot from 2022-09-03 21-31-01](https://user-images.githubusercontent.com/98482469/188292203-825acd82-fb22-45b5-a7a5-615ef4643fe2.png)
if i could import the appdata from another wineprefix like lutris, i could bring the same lutris save games to bottles, it would be a way to make a backup of my saves if I could export these directories in a simple way.

### Describe the solution you'd like

maybe this requires access to home or not?

### Other solutions?

I don't know

### Additional context and references

![example](https://user-images.githubusercontent.com/98482469/188292684-21085c40-0b1b-434d-bdc7-1ff52d755686.png)
importing lutris save game

**Comment by mirkobrombin** [comment]
Thanks for reporting. 

I think this is a too specific feature. We have already a lot of features and is very difficult to keep the app simple. Can you simply link them on your own?

**Comment by Heus-Sueh** [comment]
> Thanks for reporting. 
> 
> I think this is a too specific feature. We have already a lot of features and is very difficult to keep the app simple. Can you simply link them on your own?

yeah, I thought it would be a very specific function, and I don't know how to link these directories. I will close this issue thanks for the reply

**Comment by mirkobrombin** [comment]
You can use `ln` to make a symbolic link or just your file manager. For `ln`: `ln -s origin/path dest/path`
