### ISSUE TITLE
Drop org.winehq.Wine? 

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#2026]
We depend on the official org.winehq.Wine package, which seems unneccessary - we already have a wide variety of runners, one of which is installed automatically when opening Bottles for the first time. Pulling the official Wine package also increases install times and disk usage and leaves users confused (we'd had a lot of question asking about the sys-wine runner).

**Comment by mirkobrombin** [comment]
By removing org.winehq.Wine we would have to re-insert all those dependencies that we (and third parties) don't provide with runners. That base is not used so much for Wine but for the amount of dependencies we have in common.
