### ISSUE TITLE
[Request]: Mesa selector

### ISSUE THREAD

**Issue by Karagra** [bottlesdevs/Bottles#2027]
### Tell us the problem or your need

Some games like world of warcraft for example only show dx12 in-game if you use flatpak mesa-git vs mesa.

### Describe the solution you'd like

Inside each game a box like how you choose wine versions to select the mesa you use.

**Comment by mirkobrombin** [comment]
It’s not possible to change runner per program, at least until our layering feature is ready.

**Comment by Karagra** [comment]
I can force games to run mesa-git using `FLATPAK_GL_DRIVERS=mesa-git` flatpak run com.usebottles.bottles. was wondering if we could just select mesa-git in the options instead of having to use this line

**Comment by mirkobrombin** [comment]
The problem is that env var should be added from outside the flatpak to make the flatpak works that way. The flatpak should have no access to all mesa versions by default

**Comment by Karagra** [comment]
So for people who want to use bleeding edge mesa-git we just run the command each time launching it? thats fine I figured adding an option to make it perm for each launch was a decent idea but I have no problem just doing it manually

**Comment by mirkobrombin** [comment]
You can use Flatseal to add that flag permanently
