### ISSUE TITLE
[BUG] Bottles fail to validate SSL certificate on fetch_components()

### ISSUE THREAD

**Issue by RafaelLinux** [bottlesdevs/Bottles#203]
**Describe the bug**
After launch Bottles, an empty window appear.
I click in "+" button, and nothing happens

**Installation**
 - Method: Appimage
 - Version: devel (3.1.1)

**To Reproduce**
Sinply, launch AppImage

**Expected behavior**
To see something inside window (even "error: ....")

**Screenshots**
![image](https://user-images.githubusercontent.com/13048959/112470060-7f7ed380-8d6a-11eb-8618-13d5d235c42b.png)

**Desktop (please complete the following information):**
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.3.18-lp152.66-default
OS Type: 64-bit
Graphics Platform: X11

**Additional context**
It happens my two (distinct) openSUSE systems. One is behind a proxy and the other one is directly connected to Internet.

**Comment by mirkobrombin** [comment]
Hi, try running the AppImage from the terminal and check for errors please

**Comment by RafaelLinux** [comment]
Sure, here is
` ./Bottles-devel-x86_64.AppImage 

(bottles:2149): Gtk-WARNING **: 18:07:25.915: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 18:07:25.916: Failed to load module "unity-gtk-module"
Gtk-Message: 18:07:25.977: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:07:25.978: Failed to load module "window-decorations-gtk-module"
2021-03-25 18:07:26 INFO: Connection status: online …
Traceback (most recent call last):
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_BottleIkbVFM///usr/local/share/bottles/bottles/main.py", line 62, in do_open
    self.do_activate()
  File "/tmp/.mount_BottleIkbVFM///usr/local/share/bottles/bottles/main.py", line 102, in do_activate
    win = BottlesWindow(application=self,
  File "/tmp/.mount_BottleIkbVFM///usr/local/share/bottles/bottles/window.py", line 104, in __init__
    self.runner = BottlesRunner(self)
  File "/tmp/.mount_BottleIkbVFM///usr/local/share/bottles/bottles/runner.py", line 154, in __init__
    self.fetch_components()
  File "/tmp/.mount_BottleIkbVFM///usr/local/share/bottles/bottles/runner.py", line 615, in fetch_components
    with urllib.request.urlopen(self.components_repository_index) as url:
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/tmp/.mount_BottleIkbVFM/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>
`

**Comment by mirkobrombin** [comment]
This appears to actually be related to a network problem.

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
```

It is trying to get dependencies from our GitHub repository but for some strange reason it fails to verify the SSL certificate. I should be able to work around this by bypassing the certificate verification although this is not normally a best practice and is not recommended due to security concerns.

**Comment by pkars** [comment]
Hi,
I'm also running into this error using the (currently) latest unstable AppImage build (git commit 0aaad34), which should've fixed this issue. The root issue seems to be that the `requests` package doesn't use system trust store for verifying the SSL certificates [(Source)](https://github.com/psf/requests/issues/2966 ), but instead it uses `certifi` package for verifying.

My suggestion to fix the issue would be to include `certifi` and possibly `ca-certificates` packages in the AppImage. Regrettably I cannot test this solution myself as I have no prior experience with modifying and building AppImages.

**Comment by hthre7** [comment]
@pkars which operating system you are using

**Comment by hthre7** [comment]
> @hthre7 right, I forgot that detail. I'm using Fedora Linux 32 with GNOME 3.38.

in fedora its using different directory for certs `/etc/pki/tls/certs` could check this directory if its available

**Comment by hthre7** [comment]
@pkars could you try this build [Bottles-ssl](https://github.com/hthre7/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage)

**Comment by pkars** [comment]
@hthre7 thanks, I tried running the build. However, the SSL error still persists.

**Comment by hthre7** [comment]
> @hthre7 thanks, I tried running the build. However, the SSL error still persists.

do you have this dir '/etc/pki/tls/certs' in your system or where is the certs directory in your system.

**Comment by pkars** [comment]
> do you have this dir '/etc/pki/tls/certs' in your system or where is the certs directory in your system.

Yes, I have that directory and my system certs are there.

FWIW, the flatpak version of bottles didn't have this issue when I tried it earlier today.

**Comment by mirkobrombin** [comment]
@hthre7 check this https://github.com/niess/python-appimage/issues/24

**Comment by hthre7** [comment]
>Fedora Linux 32 with GNOME 3.38.

workstation or silverblue?

**Comment by pkars** [comment]
> workstation or silverblue?
Workstation.

Taking a closer look at the error message, I realized that the requests module has nothing to do with this. Apologies for the mistake. Anyway, I double-checked the certificate stores in my system.

```
~ $ ls -lhA /etc/ssl/
lrwxrwxrwx. 1 root root 16 17. 6.  2020 certs -> ../pki/tls/certs

~ $ ls -lhA /etc/pki/tls/certs/
lrwxrwxrwx. 1 root root 49 17. 6.  2020 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root 55 17. 6.  2020 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```
So, I have the `/etc/ssl/` folder symlinked to `/etc/pki/tls/certs/`, where are two more symlinks. Apologies again, I was a bit too hasty in declaring that my certs were there. The real certificate folder is under `/etc/pki/ca-trust/`.

I also tested running the AppImage on another computer that has Ubuntu 20.04. Bottles started up without any issues.

**Comment by hthre7** [comment]
@pkars could you try latest build([unstable](https://github.com/hthre7/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage))
