### ISSUE TITLE
[Request]: Hide GPU unrelated options

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2032]
### Tell us the problem or your need

When using an AMD or Intel GPU, we are greeted with NVIDIA related options, and vice-versa.

### Describe the solution you'd like

We should hide all GPU unrelated options. For example, if using an AMD or Intel GPU, it should hide all NVIDIA related options, like DLSS.

**Comment by mirkobrombin** [comment]
This should be achieved using the GPU Utils class
