### ISSUE TITLE
[Request]: Allow us to customize the background image on the library.

### ISSUE THREAD

**Issue by Noobao** [bottlesdevs/Bottles#2033]
### Tell us the problem or your need

There are some issues when using only steamgrid,for example there are some games outside of the grid (such as FUGA: Melodies of steel,that isn't on steamgrid)and to add it to the grid,then you have to request the game to be included there,then you'll need to find a fitting image,submit it,and then only after this happens, bottles will show it on library, this is somewhat of a cumbersome process to go through if such a case happens like it happened to myself.

There are also cases of the game not having anything posted on steamgrid,thus leaving the game on library with only a blank. (7days origins for example)in case of a user not knowing about steamgrid, the game on library will still stay blank, which is not good.

Leaving aside the benefit of the greater customizability,i've also ran into a minor issue of bottles using the same image for 2 different versions of a game,for example, this one.
![image](https://user-images.githubusercontent.com/84132367/188973486-c9e8ee00-3eb3-4d47-b65b-754e3a116c36.png)

Both use the same image,which is lisa the first, these are different versions of the game compared to the background (These are Lisa the painful and Lisa the joyful)This is not good since these are different versions of the game and all.

### Describe the solution you'd like

Allow a way for the user to manually set their prefered grid/hero in the library.

**Comment by mirkobrombin** [comment]
Tracking here #1979
