### ISSUE TITLE
[Request]: Rethinking Display Settings

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2040]
### Tell us the problem or your need

At the moment, Display Settings is tucked under a dropdown:

![image](https://user-images.githubusercontent.com/50847364/189261151-aef839c3-ff31-4c05-b0f6-1ad342a53a61.png)

This approach is inflexible, as we can't use titles to separate certain options.

For example, we can only set resolutions that Bottles provides for virtual desktops:

![image](https://user-images.githubusercontent.com/50847364/189259576-ef71fbcb-5b96-4724-8356-5365ab167987.png)

This approach does not let us input custom resolutions, which is problematic for those who want to use it. And there's no easy or pretty way to implement one when we use a dropdown.

### Describe the solution you'd like

We should implement a dialog for that, as it is flexible and will be more intuitive. That way, we can have an approach where the user can input the resolution they want, similar to Gamescope's dialog:

![image](https://user-images.githubusercontent.com/50847364/189259689-ef56f251-0d96-4e2d-b1d4-ee172966407a.png)

**Comment by mirkobrombin** [comment]
I completely agree with this solution. It was already my plan.

**Comment by KaKi87** [comment]
Hi,
Where are those now ?
Thanks

**Comment by mirkobrombin** [comment]
![image](https://github.com/bottlesdevs/Bottles/assets/9479903/eb60fad6-f39f-4e8d-9097-3772aed4d9bc)
 at the bottom of the page
