### ISSUE TITLE
[Bug]: localconfig.vdf is not being used

### ISSUE THREAD

**Issue by atmurr** [bottlesdevs/Bottles#2046]
### Describe the bug

This seems to be similar to #1994, just with a different path. localconfig.vdf is located at /home/deck/.steam/steam/userdata/[userid]/config/localconfig.vdf by default.

### To Reproduce

1. Open a Bottle
2. Click on the menu button for a program
3. 'Add to Steam'
4. "Warning: Userdata path is not set" in logs
5. Program not added to steam

### Package

Flatpak from Flathub

### Distribution

SteamOS 3.3.1

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778521088
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.7GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

![image](https://user-images.githubusercontent.com/88594233/189492683-3f02a4a0-15c8-41e7-a96c-7efb2f1836e9.png)

**Comment by devedse** [comment]
I'm running into the same issue here. I believe that with a previous version from Bottles it did actually work but with the latest it doesn't anymore.

**Comment by devedse** [comment]
The strange thing is, that the path the OP in this thread linked exists for me, but it points to here:
```
/home/deck/.local/share/Steam/userdata/123456789/config/
```

Which `should` be found by the code. So I have no idea why it's not actually finding it.

**Comment by devedse** [comment]
Ok I fixed it by following the documentation here:
https://docs.usebottles.com/bottles/programs#add-programs-in-steam

It might be usefull to actually show this in a popup message if the command fails.
