### ISSUE TITLE
[Bug]: Directx 12 games not launching

### ISSUE THREAD

**Issue by kuynh** [bottlesdevs/Bottles#2049]
### Describe the bug

When launching a directx 12 game such as borderlands 3 from the epic games store, a message pops up with the words "DX 12 is not supported on your system. Try running without the -dx12 or d3d12 command line argument". I've uploaded an image of what it looks like below.
![image](https://user-images.githubusercontent.com/66544993/189506190-6770df25-4100-45de-b77a-80faf850e388.png)

I've also tried changing the runtime to wine-ge-7-27 and it still has the same issue.

### To Reproduce

1. Open Bottles
2. Go to programs
3. Launch Epic Games Store
4. Launch Borderlands 3

### Package

Flatpak from Flathub

### Distribution

Arch Linux, Steam OS

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778525184
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 8.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

I am playing on the Steam Deck.

**Comment by herbzhao** [comment]
Can confirm the same problem. Temporarily fix is by ADD a -dx11 to launching option.

**Comment by lemonzest79** [comment]
DirectX 12 games need Mesa 22 which is in framework 22.08 Bottles is currently using frameworld 21.08, I confirmed DirectX 12 games to work (with BloodRyane Betrayal: Fresh Bites) when I installed the mesa-git//21.08 drivers but with a lot of things moving to 22.08 like Steam they now clash until Bottles moves to 22.08 or mesa-get gets a 22.08 version and the var works again.

**Comment by lemonzest79** [comment]
You can try to see if it works with the following

flatpak --user install org.freedesktop.Platform.GL.mesa-git//21.08 org.freedesktop.Platform.GL32.mesa-git//21.08

FLATPAK_GL_DRIVERS=mesa-git flatpak run com.usebottles.bottles

**Comment by mirkobrombin** [comment]
Unfortunately this is something we can't fix, at least until the new GNOME Platform is out.

Closing as there is no fix applicable in our end. Feel free to add more comments.

**Comment by kuynh** [comment]
Is there an ETA as to when the GNOME platform would be released? Just wondering as I might buy borderlands 3 on steam right now to play it.

**Comment by jannuary** [comment]
Likely the next Bottles release on Sep 28 will have it.

**Comment by GustavoJCL** [comment]
i have the same issue trying to play Layers of Fears, anyone know how to solve it?
I tried ```
flatpak --user install org.freedesktop.Platform.GL.mesa-git//21.08 org.freedesktop.Platform.GL32.mesa-git//21.08

FLATPAK_GL_DRIVERS=mesa-git flatpak run com.usebottles.bottles
```

**Comment by secretmango** [comment]
is this really not planned? I still have the same issue on latest Flatpak, should I force DX11?
