### ISSUE TITLE
 Add EasyAntiCheat Runtime and BattlEye Runtime

### ISSUE THREAD

**Issue by Sultech** [bottlesdevs/Bottles#2056]
### Tell us the problem or your need

When trying to play games like Fall guys, the game will not work because it does not have the EasyAntiCheat Runtime.

### Describe the solution you'd like

Add a toggle in the settings to enable EasyAntiCheat Runtime and BattlEye Runtime. This is helpful when trying to play games like Fall guys and other EAC and Battleye games that have enabled support but you need the runtimes to make them actually work.

**Comment by mirkobrombin** [comment]
Hi, EAC and BattleEye and always enabled and provided by the bottles runtime when using Flatpak. If you are not using Flatpak, as the maintainer to package it. If you are already using Flatpak, then probably there is something else.
