### ISSUE TITLE
[BUG] APPRUN_ERROR: Permission denied

### ISSUE THREAD

**Issue by RafaelLinux** [bottlesdevs/Bottles#206]
**Describe the bug**
Doesn't launch

**Installation**
 - Method: Appimage
 - Version devel (3.1.2)

**To Reproduce**
1. Open a terminal as non-privileged user (no root)  and launch ./Bottles-devel-x86_64.AppImage 
2. APPRUN_ERROR: Permission denied is showed and no Bottles window

**Expected behavior**
To lauch Bottles

**Desktop (please complete the following information):**
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.3.18-lp152.66-preempt
OS Type: 64-bit
Graphics Platform: X11

**Additional context**
I have no lucky trying your software. Two distinct hardware, Two distinct networks. Two distinct versions (3.1.1 and 3.1.3) Same o.s. and similar result ... can't enjoy with Bottles!!!!! :(

**Comment by mirkobrombin** [comment]
You need to make the AppImage executable before launch:
```
chmod +x Bottles*. AppImage
```

**Comment by RafaelLinux** [comment]
Well, is not just that case. It's a "similar" error, but not the one related to make executable.
First I tried to run from Plasma. Plasma automatically ask if you want to run a file with ".AppImage" extension even if that file is not executable. When I launched from Plasma, without result, then I tried from console. I changed previosly to executable your AppImage (I confirmed it just now) and then tried to launch.

Take a look:
An AppImage without execution permission give me: 
`bash: ./whatever.AppImage: Permission denied  --> Is a message from my system`

but Bottles AppImage throw a distinct error (being executable):
`APPRUN_ERROR: Permission denied   --> Is a message from inside the AppImage`

And the worst is that I can't give you more info, cause as you can see, that iis all output from console.

:(

**Comment by mirkobrombin** [comment]
I'll try to reproduce your bug, looking for some more informations.

Can you use Flatpak for now or download and install the Fedora rpm on suse?

**Comment by RafaelLinux** [comment]
I run away from Flatpak, so I can try Fedora rpm instead

**Comment by RafaelLinux** [comment]
As my system is openSUSE, I installed the Tumbleweed rpm version
`Bottles-2.0.0-28.2.x86_64.rpm 
`but no luck:

```
/usr/share/bottles/bottles/window.py:18: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio, Notify
```
![image](https://user-images.githubusercontent.com/13048959/112689322-6a916580-8e7a-11eb-9c4f-d4ac56139ee5.png)

And that's all. 

I even tried the Fedora (bottles-3.1.2-1.fc35.noarch.rpm) version, but as I guessed, no good idea, cause my system don't have some neccesary (libhandy1) dependencies. 

I'll give a chance when a new release is available.

Good idea anyway, I wish your project work.

;)

bottles-3.1.2-1.fc35.noarch

**Comment by mirkobrombin** [comment]
I thinks this package is no more maintained

**Comment by hthre7** [comment]
> `bash: ./whatever.AppImage: Permission denied --> Is a message from my system`

could you try extracting the appimage(use terminal):
```sh
sudo chmod +x *.appimage
./whatever.AppImage --appimage-extract
cd squashfs-root
./AppRun
```

**Comment by RafaelLinux** [comment]
It gives exactly same error:  [BUG] APPRUN_ERROR: Permission denied

**Comment by mirkobrombin** [comment]
Can you try the latest build?

**Comment by RafaelLinux** [comment]
Same result

**Comment by hthre7** [comment]
> Same result

Could you try `LD_DEBUG=files ./AppRun > output.txt 2>&1` maybe there something you don't have permission to access(let try first). then in the output files search for `APPRUN_ERROR`

**Comment by RafaelLinux** [comment]
Output.txt has exactly same content:  `APPRUN_ERROR: Permission denied`

**Comment by hthre7** [comment]
> Output.txt has exactly same content: `APPRUN_ERROR: Permission denied`

could upload the file

**Comment by RafaelLinux** [comment]
[output.txt](https://github.com/bottlesdevs/Bottles/files/6266937/output.txt)

**Comment by hthre7** [comment]
> [output.txt](https://github.com/bottlesdevs/Bottles/files/6266937/output.txt)

just `APPRUN_ERROR: Permission denied` that weird so there is nothing there (do use sandbox like firejail or anything else)

**Comment by RafaelLinux** [comment]
> > Same result
> 
> Could you try `LD_DEBUG=files ./AppRun > output.txt 2>&1` maybe there something you don't have permission to access(let try first). then in the output file search for `APPRUN_ERROR`.
> N.B: I tried the latest build [This](https://github.com/bottlesdevs/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage) on {openSUSE Leap 15-live} and it work

Live version are based on Tumbleweed (a rolling release) https://download.opensuse.org/distribution/leap/15.2/live/ that have the latest kernel.

I'm using version Leap 15.2 with Plasma latest repositories. I don't know an official live version of 15.2. Stable version repository has no live versions https://download.opensuse.org/distribution/openSUSE-current/iso/. They have a different kernel from Tumbleweed

**Comment by hthre7** [comment]
does this happen with other Appimage or just bottles ?
also did try using different network or stop the proxy

**Comment by RafaelLinux** [comment]
To me, it the first time I see that error when launching an AppImage (and I use a lot). So just happens only in bottles, in two different hardware and networks (one uses a proxy and the other no)

**Comment by mirkobrombin** [comment]
> To me, it the first time I see that error when launching an AppImage (and I use a lot). So just happens only in bottles, in two different hardware and networks (one uses a proxy and the other no)

Can you try with with release? https://github.com/bottlesdevs/Bottles/releases/tag/3.1.0

This build contains bugs fixed in subsequent releases, this is a test and I do not recommend using it in production (if it works).

**Comment by RafaelLinux** [comment]
Distinct error now:
falele@Projects:~/bin> ./Bottles-devel-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_BottleRCI7QO/usr/bin/bottles", line 49, in <module>
    from bottles import main
  File "/tmp/.mount_BottleRCI7QO//usr/local/share/bottles/bottles/main.py", line 49, in <module>
    from .window import BottlesWindow
  File "/tmp/.mount_BottleRCI7QO//usr/local/share/bottles/bottles/window.py", line 21, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available

**Comment by mirkobrombin** [comment]
> Distinct error now:
> 
> ```shell
> falele@Projects:~/bin> ./Bottles-devel-x86_64.AppImage 
> Traceback (most recent call last):
>   File "/tmp/.mount_BottleRCI7QO/usr/bin/bottles", line 49, in <module>
>     from bottles import main
>   File "/tmp/.mount_BottleRCI7QO//usr/local/share/bottles/bottles/main.py", line 49, in <module>
>     from .window import BottlesWindow
>   File "/tmp/.mount_BottleRCI7QO//usr/local/share/bottles/bottles/window.py", line 21, in <module>
>     gi.require_version('Handy', '1')
>   File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 129, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Handy not available
> ```

So this starts .. ignore the error for libhandy, we fixed it a few releases later.

**Comment by mirkobrombin** [comment]
Closing for no responses in 17 days.

**Comment by RafaelLinux** [comment]
I'm sorry for answering so late. I didn't mention "firejail" cause I even don't know what's that command.
