### ISSUE TITLE
[Bug]: Can't launch graphical wine applications

### ISSUE THREAD

**Issue by DivineBicycle** [bottlesdevs/Bottles#2063]
### Describe the bug

Two errors, trying to launch explorer.exe results in a ```0104:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.```

~~Trying to launch a graphical installer through the wine command line results in a nothing happening because now I can only get the first error.~~

I now get this error
```
011c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded
```

### To Reproduce

1. Try to open explorer.exe
2. Nothing happens

### Package

Flatpak from Flathub

### Distribution

ARch Linux

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.19.7-zen2-1-zen
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8041373696
    Free: 8041218048
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 7.4GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
Try issuing a flatpak update to update your flatpak drivers

**Comment by mirkobrombin** [comment]
What's the output of `nvidia-smi`?

**Comment by DivineBicycle** [comment]
```
Thu Sep 15 08:40:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P5    N/A /  N/A |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

The GPU is working for Steam games, and other applications such as ```glxgears```, so I don't think that's the issue.

**Comment by DivineBicycle** [comment]
I can't run vkcube actually, get the following error
```
vkcube: ../main.c:709: VkFormat choose_surface_format(struct vkcube *): Assertion `format != VK_FORMAT_UNDEFINED' failed.
/usr/bin/prime-run: line 2: 24541 Aborted                 (core dumped) __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```

Realised that I had set the wine renderer to vulkan, set it back and it still doesn't work so that's not it.

**Comment by DivineBicycle** [comment]
Back on X, ```vkcube``` now works but still nothing in Bottles.

**Comment by mirkobrombin** [comment]
Just tested on Arch Linux with same drivers and it works. There might be another problem

**Comment by DivineBicycle** [comment]
> Just tested on Arch Linux with same drivers and it works. There might be another problem

What are the specs of that machine, is it a.laptop?

**Comment by mirkobrombin** [comment]
An optimus laptop amd+nvidia

**Comment by DivineBicycle** [comment]
> An optimus laptop amd+nvidia

Interesting, same setup here. Are you using ```optimus-manager``` and the proprietary nvidia drivers, ```nvidia```, ```nvidia-lts``` or ```nvidia-dkms```?

**Comment by mirkobrombin** [comment]
I'm currently on ubuntu with Nvidia 515.65.01 on hybrid

**Comment by DivineBicycle** [comment]
> I'm currently on ubuntu with Nvidia 515.65.01 on hybrid

Well, that might be the difference then, since Ubuntu has (maybe) better optimus support. You might have to try on Arch with the same setup as me to reproduce it: ```nvidia-dkms```, ```optimus-manager-git```, ```linux-zen``` and X.

**Comment by mirkobrombin** [comment]
I tested on Arch at the time of writing.

**Comment by DivineBicycle** [comment]
Damn, don't know what the issue is then. I'll try Steam games quickly

**Comment by DivineBicycle** [comment]
Steam games are working on Wayland, I don't think they were on X though.

**Comment by DivineBicycle** [comment]
Must be something to do with bottles or flatpak

**Comment by fb87** [comment]
Same issue here! I use Steam on flatpak, things work just fine but not with Bottle. The `Synchronization` toggle doesn't work once I click on `Esync`.
