### ISSUE TITLE
[Bug]:  Doesn't use my NVIDIA GPU (no Directx 12)

### ISSUE THREAD

**Issue by RafaelLinux** [bottlesdevs/Bottles#2081]
### Describe the bug

After launching "Shadow of the Tomb Raider" from Epic launcher, it shows me: "Warning, no display adapter installed" and I can click "Continue", but despite my GPU appears in next configuration window:
![imagen](https://user-images.githubusercontent.com/13048959/190791476-36f24211-edbd-469c-9905-a650fd8e5d39.png)

As a result, it seems despite discrete card is detected, is not using my GPU
![imagen](https://user-images.githubusercontent.com/13048959/190797678-02caa250-4eda-4265-91ea-d6b151f6690b.png)

And I don't find in "Components" in Bottles how to install DirectX 12.

Any suggestion?

### To Reproduce

1. "Bottles"
2. "Epic Games Store"

### Package

Other, unofficial package

### Distribution

opensSUSE tumbleweed

### Troubleshooting Logs

```shell
Operating System: openSUSE Tumbleweed 20220719
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.11-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Bottles 2022.5.28-trento-3

**Comment by mirkobrombin** [comment]
Please provide the Health Check: menu -> about -> troubleshooting

**Comment by RafaelLinux** [comment]
I tried that before opening this bug, but it simply opens "https://github.com/bottlesdevs/Bottles/issues" URL, and nothing more.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/191053773-45e2b07b-e6ba-45d7-ac9f-e3368cfa75b4.png)

![image](https://user-images.githubusercontent.com/9479903/191053780-12daddcb-6b22-4017-bdd2-c6cc103ab165.png)

![image](https://user-images.githubusercontent.com/9479903/191053792-aea7b44a-c6fd-41ab-bc9c-a64fc2f65bfa.png)

**Comment by mirkobrombin** [comment]
Nvm just seen you are using a very old release (Bottles 2022.5.28-trento-3), please upgrade to latest one (2022.8.28)

**Comment by RafaelLinux** [comment]
I'm sorry, that is the only one version compiled for opensuse Tumbleweed and unfortunately, there is no  AppImage :(  so I'll need to wait to update in opensuse repo.

Thank you
