### ISSUE TITLE
[Bug]: GameMode disabled

### ISSUE THREAD

**Issue by RafaelLinux** [bottlesdevs/Bottles#2082]
### Describe the bug

I can't enable/disable GameMode in Bottles "Preferences" under "System" section. It shows "This feature is not available in your system" when I put mouse over "Enable/Disable" GameMode button.

Bottles 3.2.3
Operating System: openSUSE Tumbleweed 20220719
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.11-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

### To Reproduce

1. Preferences
2. "System" section
3. Try to change "GameMode" (is locked)

### Package

Other, unofficial package

### Distribution

openSUSE Tumbleweed

### Troubleshooting Logs

```shell
Operating System: openSUSE Tumbleweed 20220719
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.11-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Bottles 3.2.3 is deprecated, please upgrade to 2022.8.28. use flatpak to get the latest releases when fast or ask the maintainer to update it.

**Comment by RafaelLinux** [comment]
Thank you. Flatpak is a headache I unfortunately I don't know who is the maintainer or that repo. No idea of how to ask it about update. I wish some day Bottles have an AppImage version.

**Comment by RafaelLinux** [comment]
Yes, I know. I was referring to this repo maintainer  [Game Tools repository](https://download.opensuse.org/repositories/games:/tools/openSUSE_Tumbleweed/) for Tumbleweed.
