### ISSUE TITLE
[Request]: Add the ability to use the Lutris runtime

### ISSUE THREAD

**Issue by orowith2os** [bottlesdevs/Bottles#2084]
### Tell us the problem or your need

Currently Bottles provides its own runtime, and Steams. However, there is no Lutris runtime. Considering Lutris WINE builds are downloadable in-app, it would make sense to have the Lutris runtime available inside of Bottles.

### Describe the solution you'd like

Add the ability to use the Lutris runtime for a bottle.

### Additional context and references

![image](https://user-images.githubusercontent.com/93224879/190884308-9c462dc0-4859-4e4a-b1e4-86a658494c73.png)

**Comment by mirkobrombin** [comment]
Isn’t the lutris runtime needed outside of flatpak?

**Comment by orowith2os** [comment]
I'm not sure on where or where it's not needed, I'm just making this suggestion since I don't see a Lutris runtime option.

**Comment by TheEvilSkeleton** [comment]
Lutris's runtime is useful solely outside of Flatpak, as it provides a bunch of dependencies. We don't really need that, since we bundle the things we need with Flatpak. I'm closing this issue since it's out of scope.

**Comment by TheEvilSkeleton** [comment]
Honestly, we should drop Bottles runtime too.

**Comment by mirkobrombin** [comment]
The bottles runtime provides eac and be support. We cannot drop it.
