### ISSUE TITLE
[Bug]: Where is Dark Mode?

### ISSUE THREAD

**Issue by SpyderGamer** [bottlesdevs/Bottles#2088]
### Describe the bug

On the website, it appears that Bottles has a dark GUI. However, in the settings, there is no option to enable dark mode.
![image](https://user-images.githubusercontent.com/85440857/190948555-d5c07fee-dc59-42e2-a47d-75502b2c06b4.png)

### To Reproduce

1. Open the Hamburger Menu in the Bottles Page.
2. Press Preferences.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-47-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 1971986432
    Free: 1971834880
RAM:
    MemTotal: 3.7GiB
    MemAvailable: 2.6GiB
Bottles_envs: null
```

**Comment by jannuary** [comment]
Linux Mint lies about supporting dark mode, and we do not expose the setting if the system supports it.

**Comment by SpyderGamer** [comment]
Ah ok, thanks for letting me know :)

**Comment by jannuary** [comment]
FWIW, if you want to work around this you can run these two commands:

`flatpak run --command=bash com.usebottles.bottles
gsettings set com.usebottles.bottles dark-theme true`

**Comment by SpyderGamer** [comment]
Thanks for helping, but I get an error `/usr/bin/gsettings: /usr/bin/gsettings: cannot execute binary file`

**Comment by software-made-easy** [comment]
This are 2 command:  
Run `flatpak run --command=bash com.usebottles.bottles` and afterwards `gsettings set com.usebottles.bottles dark-theme true`.

**Comment by SpyderGamer** [comment]
Alright thanks, I will try that 👍

**Comment by SpyderGamer** [comment]
> gsettings set com.usebottles.bottles dark-theme true

Thank you so much it worked!
