### ISSUE TITLE
Please add Chinese lang support

### ISSUE THREAD

**Issue by Trapshell** [bottlesdevs/Bottles#2090]
我从wine切换到CrossOver, 并且购买, 但是结果让为失望.
I switched from wine to CrossOver, and bought it, but was disappointed.
今天我遇到了Bottles, 我非常惊讶.
I came across Bottles today and I was very surprised.
这是一个伟大的作品. 友好的配置页面, 美丽的UI界面.
This is a great piece of work. Friendly configuration pages, beautiful UI.
学习成本非常低
Learning costs are very low
难以置信这个伟大的作品目前竟然只有3.5K星星, 我相信未来有无限可能!!
I can't believe this great work has only 3.5K stars so far, I believe the possibilities are endless!!!
如果能支持中文语言支持, 我想我会感动
If Chinese language support is available, I think I will be moved
😄 支持!! 感谢这个伟大的作品.
Support!!! Thanks for this great work .

我必须在中国的一些知名论坛推广这个项目!!
I have to promote this project in some well-known forums in China! !

**Comment by jannuary** [comment]
Patches welcome - no one on the dev team speaks Chinese in any significant matter :)

**Comment by mirkobrombin** [comment]
Check #1692
