### ISSUE TITLE
[Request] Option to restrict network access

### ISSUE THREAD

**Issue by gunwald** [bottlesdevs/Bottles#2093]
I use Bottles to run some Windows apps like Acrobat for which there still aren't Linux alternatives. Before I switched to Bottles I used a custom script to run Wine applications which runs them under a specific user who does not have access to the network.

I do this as I don't want those apps not to have access to the network and internet as I don't want them to send data behind my back ›home‹ and for security reasons as some of this applications are about 10 years old and are not secure.

It would be really nice to have an option for each bottle to restrict network and internet access as we have for Flatpak apps.

**Comment by axtloss** [comment]
This already exists as per bottle sandboxes, which is in beta so you'll have to enable it in the settings first, then you can block network access in the preferences of the bottle.

**Comment by axtloss** [comment]
I've not been very active in bottles development anymore and I know that the UI has had some major changes, I'm not sure where to find it, maybe another bottles contributor knows.
