### ISSUE TITLE
[Bug]: Changing wine runner version or windows version inside bottle sometimes takes very long time

### ISSUE THREAD

**Issue by DjoleDzele** [bottlesdevs/Bottles#2104]
### Describe the bug

Sometimes when changing wine runner, or windows version inside bottle, it takes very long time, sometimes even never finishes, its weird since for example in lutris these operations usually take few seconds, here it can take 5-10 minutes to finish, not always but still happens, i tried on both Flatpak version (which seem to take even longer), and with the one from AUR, is there something that i could try to make it do these things faster?

### To Reproduce

1. create new bottle (i used gaming one)
2. go to that bottle -> preferences -> system -> components -> change runner
3. also you can try changing windows version in system preferences
4. it takes very long time, almost 10 minutes in some cases

### Package

Flatpak from Flathub

### Distribution

Manjaro unstable

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/amd_icd64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/amd_icd32.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.11-1-MANJARO
Distro:
    Name: Manjaro Linux
    Version: Unknown
Disk:
    Total: 307019407360
    Free: 240683565056
RAM:
    MemTotal: 30.8GiB
    MemAvailable: 22.1GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

X11

**Comment by mirkobrombin** [comment]
Sadly there is nothing we (and you) can do to improve this. Switching Windows version will re-initialize every DLL Component in the bottle, update the registry keys and perform a boot update to ensure everything is being updated.
