### ISSUE TITLE
[BUG] Programs don't look up at SD Card location

### ISSUE THREAD

**Issue by yongbi85** [bottlesdevs/Bottles#2105]
### Describe the bug

After installing Ubisoft Connect, if I install a game in the default folder (C:/Program Files), the games will be listed in programs, however if i decide to install them on SD Card in /run/media the programs don't list the games.

### To Reproduce

Install Ubisoft Connect installer
Install a game and point it to E: folder that is you SD Card/External drive
At the end of install Ubisoft shows Play correctly but Bottles don't list it in Programs

### Package

Flatpak from Flathub

### Distribution

Steam OS 3

### Troubleshooting Logs

```shell
No specific log as there is not crash or anything, the install goes through but programs doesn't show
```

**Comment by mirkobrombin** [comment]
Read here please https://docs.usebottles.com/flatpak/expose-directories

**Comment by yongbi85** [comment]
I said that i made the rights modification in flatseal so it ain't the problem (besides it sucessfully installs games in the sd card location but then the programs don't show...)
However I used a workaround and set the default bottles native path to SD card.
Thanks for your work but don't always assum the user is dumb and didn't read the documentation
