### ISSUE TITLE
[Bug]: Unknown crash after closing bottles

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2115]
### Describe the bug

Was trying a fresh install of one of my bottles because newest update broke it completely and of course terminal still doesn't work. Installed the program the same way, added program to the list manually because it doesn't detect it automatically (see issue 188 in bottlesdevs/programs repo). Clicked run and nothing happened. Clicked stop. Clicked "run with terminal" button and nothing happened. Closed the bottles and opened it again and this appeared:

```
'arguments'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 121, in run_program
    args=program["arguments"],

```

### To Reproduce

1. Install the game.
2. Add it manually to the programs list
3. Run it with play button and launch from terminal button
4. Close and open bottles
5. ?

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21 Cinnamon

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-48-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356999168
    Free: 8356855808
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "13,6\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

Also I noticed that adding program manually when you have no programs in the list makes it look weird, because it just adds the program entry to the list and doesn't hide the "use the installers section or the "run executable" button" text.
![2022-09-28_17-04-02](https://user-images.githubusercontent.com/84787215/192814826-f2ced1eb-a0ca-41c3-b22a-6730ae209b04.png)

**Comment by mirkobrombin** [comment]
fixed by https://github.com/bottlesdevs/Bottles/commit/604ccb9909f3ce469383656dd01b68dbc757a918
