### ISSUE TITLE
[Bug]: Fix custom Bottle storage folder broken for secondary hard disks

### ISSUE THREAD

**Issue by RichardJECooke** [bottlesdevs/Bottles#2117]
### Describe the bug

I set the custom Bottles folder to my large storage disk, mounted on `/media/me/Storage1TB/Bottles/`.
When I restarted Bottles it said it could not access the folder.

### To Reproduce

- Preferences - Scroll down - Set custom folder to any folder outside your primary hard disk
- Restart
- Folder not found

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Troubleshooting Logs

```shell
Version: 2022.9.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-48-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 33678688256
    Free: 33678532608
RAM:
    MemTotal: "67.4\_GB"
    MemAvailable: "60.3\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Did you give the Flatpak access to that folder? E.g. using Flatseal.
https://docs.usebottles.com/flatpak/expose-directories
