### ISSUE TITLE
[Bug]: Unable to use the virtual desktop

### ISSUE THREAD

**Issue by ghost** [bottlesdevs/Bottles#2120]
### Describe the bug

Greetings, when I try to use the virtual desktop in games they stop being able to start. It is something I have tried a few times with different games, over months with different versions of linux mint and kernels.

I have tried different bottle configurations without success. It is a feature that has always worked and still works for me in lutris (also in its flatpak version), so I assume it is a bottles bug instead of wine.

I have finally been trying to figure out the cause without success. The only apparently relevant thing I have found is that when starting a game with the console and the virtual desktop, this text is added to the console:

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  414
  Current serial number in output stream:  415
```

### To Reproduce

Just set any virtual desktop configuration. So far I can reproduce it 100%

### Package

Flatpak from Flathub

### Distribution

linux mint 21

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.15.0-48-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4123123712
    Free: 4122939392
RAM:
    MemTotal: "8,2\_GB"
    MemAvailable: "5,1\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by TheEvilSkeleton** [comment]
Can you try to install Notepad++ in a separate bottle and use virtual desktop? I want to check if you have problems with virtual desktops in general or only with this in particular.

**Comment by mirkobrombin** [comment]
Virtual desktop works here 
![image](https://user-images.githubusercontent.com/9479903/193426932-dbbf4970-2be2-43ce-af69-8c3182705880.png)

**Comment by mirkobrombin** [comment]
So it fails on windowed mode only?

**Comment by SjoerdV** [comment]
@mirkobrombin I have the same issue as reported by ghost. Does not matter which runner I use. Also on Mint (LMDE5). Notepad starts just fine, only games fail to start (either windowed, borderless window or fullscreen mode.)

```
info:  Device properties:
info:    Device name:     : NVIDIA GeForce GTX 1650
info:    Driver version   : 535.104.5
...
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 159 valid state cache entries
info:  DXVK: Using 7 compiler threads
warn:  winevulkan detected, disabling exclusive fullscreen support
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  407
  Current serial number in output stream:  408
```

**Comment by another-sapiens** [comment]
I used to have this problem when enabling Virtual Desktop from Bottle's menu. 
But for some reason, after enabling it through Legacy Wine Tools -> Configuration -> Graphics -> Emulate Virtual Desktop,  it started working properly.

**Comment by christiansam** [comment]
I'm experiencing the same issue - when Virtual Desktop (regardless if set via Bottle settings, or Legacy Wine Tools) is enabled applications fail to start in general:

- Bottles 51.10 Flatpak (SteamOS)
- The used bottle was created with the Bottle-schema "Application" and is based on "Win64 & soda 8.0.2"
- notepad++ is used a testing application

###  with Virtual Desktop enabled 
- Bottle Virtual Desktop default settings  (1280x720)
- SteamOS KDE Host Desktop is running in 1920x1080
- notepad++ fails to execute

``
 (deck@steamdeck ~)$ flatpak run com.usebottles.bottles bottles:run/desktop/'notepad++'
TypeError: Must be number, not NoneType
(deck@steamdeck ~)$ 09:40:18 (INFO) Forcing offline mode 
Windows path detected. Avoiding validation.
wine: using kernel write watches (experimental).
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
00ec:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00ec:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: using kernel write watches (experimental).
^C
``

###  with Virtual Desktop disabled
- notepad++ succesfully starts and is displayed/useable
- no stderr/console-message like these appear:

> 00ec:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 00ec:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."

**Comment by christiansam** [comment]
i guess this issue is somehow WINE Runner specific/related:

After stumbled upon this: [Need better feedback that virtual desktop is not supported with wine-GE #5196](https://github.com/lutris/lutris/issues/5196) it tried to switch the Bottle's  WINE Runner from

- soda 8.0.2 to soda 7.0.2

now with Virtual Desktop enabled:
- not a single console-message appears - especially no ERR messages
- a WINE Virtual Desktop and notepad++ succesfully started and are displayed/useable

**Comment by cameronbosch** [comment]
I can confirm switching to soda 7.0-9 from 8.0 fixed the issue; I was having it too.
