### ISSUE TITLE
[Bug]: RuntimeError: Gtk couldn't be initialized

### ISSUE THREAD

**Issue by nutta-git** [bottlesdevs/Bottles#2121]
### Describe the bug

Bottles doesn't start. 

### To Reproduce

flatpak run com.usebottles.bottles 

### Package

Flatpak from Flathub

### Distribution

Arch Linux 

### Troubleshooting Logs

```shell
flatpak run com.usebottles.bottles 

(process:2): Gtk-CRITICAL **: 06:19:05.361: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:2): Gtk-CRITICAL **: 06:19:05.361: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed

(bottles:2): Gtk-CRITICAL **: 06:19:05.392: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(bottles:2): Gtk-CRITICAL **: 06:19:05.392: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/main.py", line 181, in do_command_line
    self.do_activate()
  File "/app/share/bottles/bottles/frontend/main.py", line 224, in do_activate
    win = MainWindow(
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 85, in __init__
    super().__init__(**kwargs)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

### Display Protocol

X11

### Display Backend used by Bottles

X11, I don't know

### Additional context

DE: Plasma 5.25.5
WM: KWin
Non-Composited ( System settings > Display and Monitor > Compositor | uncheck "Enable on startup" )

**Comment by jannuary** [comment]
We cannot guarantee that Bottles or GTK works well or at all with uncomposited X11 - this case is very much unsupported and untested for both.

**Comment by jannuary** [comment]
Do any other GTK4 apps run?

**Comment by nutta-git** [comment]
Think soo, I tested both 
https://flathub.org/apps/details/io.github.seadve.Kooha and https://flathub.org/apps/details/com.github.rafostar.Clapper
Should be gtk4 apps according to https://www.reddit.com/r/gnome/comments/pd5bee/gtk_4_which_apps_are_making_use_of_it/

**Comment by mirkobrombin** [comment]
What's the output of `echo $DISPLAY`?

**Comment by nutta-git** [comment]
`
:0
`

**Comment by nutta-git** [comment]
The [AUR](https://aur.archlinux.org/packages/bottles) version works fine

**Comment by axtloss** [comment]
From what I can see in the logs it's either that the flatpak doesn't have x11 permission or the display variable in the flatpak isn't set correctly, what's the output of `flatpak info -M com.usebottles.bottles`

**Comment by nutta-git** [comment]
@axtloss that's seems to be it. Thanks. 
I don't know why I disabled x11 socket, doesn't make any sense. 
This was a mistake on my part. I am sorry for wasting everyone's time, but thank you for helping me out.
