### ISSUE TITLE
[Bug]: Error running program through Wine due to inherited host environment

### ISSUE THREAD

**Issue by davidmartos96** [bottlesdevs/Bottles#2127]
### Describe the bug

Hello!
I've encountered with a peculiar bug when running a game made with [Godot](https://godotengine.org) via Bottles through Wine. The game works perfectly fine with Wine outside Bottles.
The problem is that Godot seems to use the XDG Linux environment variables even when running on Windows: [source](https://github.com/godotengine/godot/blob/55bed82b0541c5dbefcf402cc0974fe5d05e7576/platform/windows/os_windows.cpp#L996)
For instance `XDG_DATA_HOME` when running Bottles it has a value in the Wine runtime (~/.var/app./com.bottles.Bottles/data), whereas a regular wine command does not inherit the value.
This conflicts with the game logic when resolving special directories, like where the save games are stored, making it not work correctly. The XDG variable having a value forces the game to try and save files under ~/.var/app/bottles/... which is not in the wine prefix.

I was wondering what is the usecase for inheriting the environment from the host. I can see that there is some code in `WineEnv` to bypass this inheritance, but it doesn't seem to be used by the regular Wine commands in Bottles.

My proposed solutions would be:
 1. Handle specially these `XDG_*` variables by clearing them
 or
 2. Provide a way to run the bottle wine commands with a clean, non inherited environment

Thanks!

### To Reproduce

1. Create Game Bottle
2. Run executable that reads the environment
3. Should it read the host value? Or should it be completely isolated?

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Bottles version 2022.9.28.1
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by davidmartos96** [comment]
@mirkobrombin Thanks for the fix! Looking at the Godot source code it looks like XDG_CACHE_HOME and XDG_CONFIG_HOME are used as well when on Windows.
Do you think they should get removed as well?

Here is the XDG environment under the wine runtime

![Screenshot_20221009_162837](https://user-images.githubusercontent.com/22084723/194762648-a38a46a8-9d27-4f08-8cdb-a9b097eb1e95.png)

**Comment by mirkobrombin** [comment]
I think `XDG_CACHE_HOME` is going to be used by wine, I've to read about

**Comment by Perkolator** [comment]
I just ran into the same problem. Using Bottles 51.11.

```
ERROR: Could not create directory: /home
   at: (core/os/dir_access.cpp:176)
ERROR: Error attempting to create data dir: /home/USER/.var/app/com.usebottles.bottles/data/Godot/app_userdata/GAMENAME.
   at: (core/os/os.cpp:465)
ERROR: Could not create directory: user://logs
   at: (core/os/dir_access.cpp:176)
```

Freaked me out to see how the game tried to access folders outside the bottle prefix. And what is that `user://logs` folder the game tried to create?

Any idea what's wrong and how this could be prevented?

**Comment by davidmartos96** [comment]
@Perkolator Do you know which version of Godot is being used?
Looking at the Godot source code, version 3.4 appears to match your error logs:

https://github.com/godotengine/godot/blob/206ba70f4b2a3eac4455bb21bd7c8af76285bd86/core/os/dir_access.cpp#L176
https://github.com/godotengine/godot/blob/206ba70f4b2a3eac4455bb21bd7c8af76285bd86/core/os/os.cpp#L465

`user://` seems to be an internal path Godot uses to resolve later as the `user_data_dir`, so nothing strange about that path.

The reason of the error seems to be how the `get_user_data_dir` is resolved, which calls `get_data_dir` under the hood:
https://github.com/godotengine/godot/blob/206ba70f4b2a3eac4455bb21bd7c8af76285bd86/platform/windows/os_windows.cpp#L3368

And then, because there is no `XDG_DATA_HOME` set (thanks to the fix for this Issue), it falls back to `get_config_path`, which uses `XDG_CONFIG_HOME`
https://github.com/godotengine/godot/blob/206ba70f4b2a3eac4455bb21bd7c8af76285bd86/platform/windows/os_windows.cpp#L3353

@mirkobrombin Maybe `XDG_CONFIG_HOME` should be removed as well to avoid issues.

**Comment by Perkolator** [comment]
> Do you know which version of Godot is being used?

Godot Engine v3.4.stable.official.206ba70f4. This is a very new game, released 3 weeks ago.

> And then, because there is no `XDG_DATA_HOME` set (thanks to the fix for this Issue), it falls back to `get_config_path`, which uses `XDG_CONFIG_HOME`, which has the value `/home/USER/.var/app/com.usebottles.bottles/data/`

> The original fix was reverted in #2219 so having `XDG_DATA_HOME` is the culprit.

My OS doesn't seem to have `XDG_DATA_HOME` set at all, nor any `env` that includes a `bottles` string. Both `env | grep -i XDG_DATA_HOME` and `env | grep -i bottles` prints nothing.

> Maybe you could override the `XDG_DATA_HOME` variable in Bottles to have the same value as the variable `APPDATA` in Windows, which is what Godot uses. I think that could be a workaround, but I haven't tried it.

I don't know how. :(

**Comment by davidmartos96** [comment]
@Perkolator Can you try the following? The variable is properly set to a custom value when printing it from cmd

From the specific bottle Settings section, go to Environment Variables and create one for `XDG_DATA_HOME` with the AppData path.
If you then use the `Command Line` option in the bottle detail screen to open a cmd, if you type `set` it should like the environment variable with the custom value. I'm assuming the game should read that variable too.

**Comment by Perkolator** [comment]
> From the specific bottle Settings section, go to Environment Variables and create one for `XDG_DATA_HOME` with the AppData path.

Holy moly, it works. I set it as `C:\users\USER\AppData` (after I first tried the full linux host path, which failed) and game starts fine, no errors in the console and I can see the save files and log file in the appdata folder. Many MANY thanks!!!

**Comment by davidmartos96** [comment]
@Perkolator Awesome, glad to hear that! This issue was really confusing when I encountered it haha
Hopefully it will just resolve itself with time. The XDG behavior in Godot 3.x is weird. And searching by the issue on Github issue will probably make this issue pop up for a workaround.

**Comment by hewasajumperboy** [comment]
> @Perkolator Can you try the following? The variable is properly set to a custom value when printing it from cmd
> 
> From the specific bottle Settings section, go to Environment Variables and create one for `XDG_DATA_HOME` with the AppData path. If you then use the `Command Line` option in the bottle detail screen to open a cmd, if you type `set` it should show the environment variable with the custom value. I'm assuming the game should read that variable too.

This worked for me as well, setting XDG_DATA_HOME to the Windows path to Appdata, thank you!
