### ISSUE TITLE
[Bug]: Language settings bug(japanese yeah)

### ISSUE THREAD

**Issue by Angraman** [bottlesdevs/Bottles#2129]
### Describe the bug

Language settings option in bottle does not sets encode properly.

### To Reproduce

Launch Japanese vn(Majikoi in particular) with language settings set to Japanese.
Try to save/load or import any game settings or files.

### Package

Flatpak from Flathub

### Distribution

Mint Mate 22.04

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-48-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 3060273152
    Free: 3060129792
RAM:
    MemTotal: "6,1\_GB"
    MemAvailable: "692,8\_MB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

There were already several issues set to solved because language option supposedly solves the problem, but...
Game only properly works if you set environment variable manually. If you only use language setting in bottles game won't be able to properly save settings due to invalid encoding.
Here is the picture. On the left if you set environment variable, on the right if you only set japanese language in bottle settings. Game properly display japanese language but won't be able to save game state or settings.
![encode](https://user-images.githubusercontent.com/51082040/193541614-e95eb193-d456-45b3-b1a7-27197300cf69.png)

**Comment by mirkobrombin** [comment]
which env vars did you set?

**Comment by Angraman** [comment]
> which env vars did you set?
LANG=“ja_JP.UTF-8
I used this  https://thenewleafjournal.com/japanese-environment-in-pol-lutris-bottles/ as a reference when language settings inside the bottle didn't work.

**Comment by Angraman** [comment]
Now i tried to play on ubuntu 22.04.1 with similar setup and savegame folder wasn't created at all. Game also can't read it if i try to put it into bottle folder manually. 
I'm guessing it isn't a localization issue, but permission issue or ubuntu bug/conflict.

**Comment by Angraman** [comment]
Okay i tried to launch Stellaris windows gog version in the same bottle and the same way i launched Majikoi.
Stellaris successfully created its Paradox folder in documents.
So it is encode/language issue.
I have installed Japanese language in ubuntu and fonts in bottle, and game display langue properly both in game and on window text. It still refuse to save or load.

**Comment by mirkobrombin** [comment]
Weird, we set the LC_ALL env var which should be the right one (actually tested with the supported langs)

**Comment by sp1cyf0x** [comment]
Any updates on this?
This is the only issue stopping me from using the Flatpak version.

**Comment by xrishox** [comment]
i've also had pretty consistent issues with japanese locale in bottles using flatpak. works perfrectly fine using the fedora non-flatpak version. i suspect it has more to do with the container/bubblewrap/flatpack than it does with bottles.

**Comment by ghost573** [comment]
Tried both the flatpak and AUR and I got issues trying to run Hoshizora no Memoria Eternal Heart HD.
Added `LC_ALL=ja_JP.UTF-8` and `TZ=Asia/Tokyo` but still gets an error when locale isn't set to Japan.

**Comment by kekkoudesu** [comment]
This is what happens when I try to install winetricks dependencies when using the `LC_ALL=ja_JP.UTF-8` env variable.
![2022-11-27-18-10-37](https://user-images.githubusercontent.com/88186997/204123666-3be59018-008a-439e-aef4-f3c2127747e8.png)

**Comment by ghost573** [comment]
> This is what happens when I try to install winetricks dependencies when using the `LC_ALL=ja_JP.UTF-8` env variable. ![2022-11-27-18-10-37](https://user-images.githubusercontent.com/88186997/204123666-3be59018-008a-439e-aef4-f3c2127747e8.png)

[This guide for running VNs on Linux](https://learnjapanese.moe/vn-linux/) has a link to download Japanese fonts that fixes this problem and everything shows up with proper Japanese characters for me, unfortunately the locale is bugged and a lot of VNs give an error and crash.

**Comment by kekkoudesu** [comment]
That's the guide I've relied on for years, too :) It looks like I would have to add those fonts to `/var/lib/flatpak/app/com.usebottles/current/active/files/share/wine/fonts`. Unfortunately, Bottles fails to launch Sonohana 4 for me regardless.

I've never been able to understand what prevents その花 games from launching. It'll work in Lutris's runtime and system WINE, but not CrossOver or Bottles (regardless of the runtime). Depending on the computer. And fjfix usually doesn't make a difference. Hard to tell whether it's caused by flatpak or not because I wasn't able to get Bottles installed from the AUR at the time.

**Comment by latin-1** [comment]
https://github.com/bottlesdevs/Bottles/issues/2189#issuecomment-1354412658

> For those looking for a workaround:
>
> ```sh
> flatpak config --set extra-languages ja_JP.UTF-8
> flatpak update
> ```
>
> and set the environment variable in Bottles (rather than the language setting):
>
> ```
> LANG=ja_JP.UTF-8
> ```

**Comment by ghost573** [comment]
`/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)`
`/bin/bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)`

**Comment by Angraman** [comment]
Probably should be closed, as workaround above works just fine.
