### ISSUE TITLE
[BUG] Chardonnay-6.4-x86_64.tar.gz looks corrupted 3.1.2 and 3.1.3 too

### ISSUE THREAD

**Issue by richieloro** [bottlesdevs/Bottles#213]
Hello I can't install 3.1.2. Dxvk install but I have an error message when chardonay download : 
**"Downloaded file Chardonnay-6.4-x86_64.tar.gz looks corrupted"**

I am on Ubuntu 20.10 when I installed last month 3.1.1 chardonnay (don't remember the version) installed fine.
Can you check I needed to work on a project and now I am stuck. Please and thank you.

Stuck here : 
![Screenshot from 2021-03-30 11-59-16](https://user-images.githubusercontent.com/81038208/112971367-6ea9d580-914f-11eb-882d-ed34ca62290c.png)

**Comment by mirkobrombin** [comment]
I'm checking if the repository is out of date

**Comment by richieloro** [comment]
Thank you. It does it with the flatpak and the appimage for 3.1.3 too.

**Comment by mirkobrombin** [comment]
Can you try to restart Bottles and try again?

**Comment by richieloro** [comment]
Perfect it worked, no error message ! 
Thank you you have great project and are very responsive. Keep up this way.

**Comment by mirkobrombin** [comment]
> Perfect it worked, no error message !
> Thank you you have great project and are very responsive. Keep up this way.

Thanks so much
