### ISSUE TITLE
[Bug]: Inconsistency detected by ld.so: dl-close.c: 277

### ISSUE THREAD

**Issue by silviucc** [bottlesdevs/Bottles#2133]
### Describe the bug

The installer starts and crashes. I get this message in the console:

Inconsistency detected by ld.so: dl-close.c: 277: _dl_close_worker: Assertion `imap->l_type == lt_loaded && !imap->l_nodelete_active' failed!

The installer run fine from Lutris

### To Reproduce

1. Go to https://www.vectric.com/free-trial/aspire
2. Download the free trial software
3. create a new "Application" bottle 
4. run the installer

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.12-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16722046976
    Free: 16721903616
RAM:
    MemTotal: "33.4\_GB"
    MemAvailable: "25.8\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mkalinski** [comment]
I encountered a similar bug with Flatpak Bottles on Fedora 36. It seems to be related to the vaniglia-6.23 runner that's used by default. When I switched the runner to sys-wine-7.0 (the only other one available by default) the bug went away.

**Comment by mirkobrombin** [comment]
2022.9.28.1 Is too old, please upgrade to the latest release. Use flatpak if possible

**Comment by LyesSaadi** [comment]
Can confirm this still happens with vaniglia-6.25 with up to date flatpak bottles :
```
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-530-41-03/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.2.14-300.fc38.x86_64
Disk:
    Total: 16664449024
    Free: 16664268800
RAM:
    MemTotal: 31.0GiB
    MemAvailable: 16.6GiB
Bottles_envs: null
```

**Comment by mkalinski** [comment]
I've since disavowed vaniglia, and never had this problem again.

Just remove vaniglia from your installed runners, and it should install some other default. For me it was "soda". So vaniglia is probably not a recommended default anymore, and it's just a holdover from an older bottles install.

RIP vaniglia
