### ISSUE TITLE
[Bug]: KeyError: '2ed586e9-2819-46c9-aeaa-3282118276b3'

### ISSUE THREAD

**Issue by CBx86** [bottlesdevs/Bottles#2137]
### Describe the bug

Bottles crashing, i cant remove any program.
At start:
'arguments'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 121, in run_program
    args=program["arguments"],

Removing a game using "Remove from list"
out 05 10:11:51 quati plasmashell[35807]: Traceback (most recent call last):
out 05 10:11:51 quati plasmashell[35807]:   File "/app/share/bottles/bottles/frontend/widgets/program.py", line 230, in remove_program
out 05 10:11:51 quati plasmashell[35807]:     self.config = self.manager.update_config(
out 05 10:11:51 quati plasmashell[35807]:   File "/app/share/bottles/bottles/backend/managers/manager.py", line 900, in update_config
out 05 10:11:51 quati plasmashell[35807]:     del config[scope][key]
out 05 10:11:51 quati plasmashell[35807]: KeyError: '2ed586e9-2819-46c9-aeaa-3282118276b3'
out 05 10:11:54 quati plasmashell[35807]: 10:11:54 (INFO) Setting Key 2ed586e9-2819-46c9-aeaa-3282118276b3=None for bottle Games… 

### To Reproduce

Open Bottles
Select a bottle
Remove from list

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.12-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8273932288
    Free: 8273788928
RAM:
    MemTotal: "16.5\_GB"
    MemAvailable: "13.5\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Im using KDE PLASMA, not GNome.

I create other bottle, same problem.

Many Thanks.

**Comment by mirkobrombin** [comment]
fixed by https://github.com/bottlesdevs/Bottles/commit/604ccb9909f3ce469383656dd01b68dbc757a918
