### ISSUE TITLE
[BUG] cant install/run battle.net

### ISSUE THREAD

**Issue by fishxz** [bottlesdevs/Bottles#214]
**Describe the bug**
Unable to install battle.net client. stuck at "updating blizzard agent"

**Installation**
 - Method: flatpak
 - Version: 3.1.3

**Expected behavior**
the client install/run

**Additional context**
```0108:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files (x86)\\Battle.net\\Battle.net.12769\\libcef.dll") not found
0108:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
0108:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files (x86)\\Battle.net\\Battle.net.12769\\libcef.dll") not found
0108:err:module:import_dll Library libcef.dll (which is needed by L"C:\\Program Files (x86)\\Battle.net\\Battle.net.12769\\battle.net.dll") not found
0108:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
0108:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files (x86)\\Battle.net\\Battle.net.12769\\battle.net.dll") not found
```
works with dxvk disabled.

**Comment by mirkobrombin** [comment]
This is more a wine related problem. Bottles is just a wineprefix manager. Anyway, I invite you to use Lutris for the games as it offers support for installers.From Bottles v4 we will provide our version of the installers with related support.

**Comment by mirkobrombin** [comment]
Small tip: use Proton as a runner if you haven't used it already, it comes with better support for a bunch of video games

**Comment by jatin-cbs** [comment]
Blizzard is stable with lutris version (but NOT in bottles as lutris has a tested installer in JSON / YAML) since years now and all of the blizzard games, Overwatch and world of warcraft too work better than native !  @fishxz  Bottles is a great prefix manager however if you want better default configuration I recommend lutris right now.

**Comment by mirkobrombin** [comment]
> Blizzard Battle.net is stable with lutris version (but NOT in bottles as lutris has a tested installer in JSON / YAML) https://lutris.net/games/install/8519/view since years now and all of the blizzard games including Overwatch, hearthstone and world of warcraft too work better than native ! @fishxz Bottles is a great prefix manager however if you want better default configuration I recommend lutris right now.

Starting with bottles v4 we support installers like Lutris but for the moment I recommend using Lutris for Games

**Comment by jatin-cbs** [comment]
Yes I saw the https://github.com/bottlesdevs/programs 
Blizzard battle net will be a good test for this as the lutris installer has DXVK cache, state cache merge, shaders and changed settings.
Love the roadmap of v4 and the correct way of doing stuff !
