### ISSUE TITLE
bottles need a internet connection to satrt !?

### ISSUE THREAD

**Issue by ssmns** [bottlesdevs/Bottles#2141]
!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!
Why the bottles need a internet connection to start?! the bottles doesn't start without a internet connection and it's weird for a desktop application.

**Comment by axtloss** [comment]
Bottles requires an internet connection to be able to fetch the repos for dependencies and programs, you can still use it without the internet connection, in that case it won't pull anything from repos.

**Comment by mirkobrombin** [comment]
Bottles works offline if you have no connection.
