### ISSUE TITLE
[Report] Download failed for any dependency - stuck on infinite loading

### ISSUE THREAD

**Issue by sujal05** [bottlesdevs/Bottles#2144]
**Which dependency?**
d3dx9

**Problem type**
- download failed - stuck at downloading dependency

**Describe the problem**
I installed bottle today and tried to make a default gaming bottle but it also stopped or got stuck at downloading d3dx9. I then made a custom bottle without any addons and it instantly got created. I then went into dependencies and tried to install d3dx9 from there but it got stuck there in downloading (loading image) but i could still use the app and my desktop without any issues (bottle only took 156mb of RAM. I don't know if there are any logs or where to find them, I tried /var/log but there are no folders named bottle or wine. If there is a way to manually install the dependencies.

I want to play a game that needs visual redistributables and directx 9 or higher version and nothing more than that (considering game was published in 2005).
![image](https://user-images.githubusercontent.com/48390360/194370098-ee77c28a-88a8-4d6c-9469-278c5c5484c9.png)

**Comment by mirkobrombin** [comment]
Hi, please provide more info like the output

**Comment by mirkobrombin** [comment]
Please report following the [bug report template](https://github.com/bottlesdevs/Bottles/issues/new/choose)
