### ISSUE TITLE
[Bug]: Epic Games not working on Pop! OS

### ISSUE THREAD

**Issue by GamingBoiYT** [bottlesdevs/Bottles#2146]
### Describe the bug

i installed epic games launcher through your installers. After opening it says gpu error "UNSUPPORTED GPU: there is a problem with your gpu, it its either unsupported or the right drivers are not installed". My gpu is a GT 650M, please integrate support for this gpu. I expected epic games launcher to work. I am also fairly new to linux and don't know how to update the gpu drivers.

### To Reproduce

Go to installers
Install Epic Games Store
Open it
GPU error pops up

### Package

Flatpak from Flathub

### Distribution

Pop! OS

### Troubleshooting Logs

```shell
'arguments'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 121, in run_program
    args=program["arguments"],
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by GamingBoiYT** [comment]
Hi, The package isn't from flathub, i got it from the Pop!Shop.

**Comment by jannuary** [comment]
Hello! We do not support any other packages but the Flathub one. In addition, this is an issue tracker and not a support forum - we cannot help you with updating drivers on PopOS.

**Comment by mirkobrombin** [comment]
If I'm not wrong, Pop OS ship Flathub by default. Please post the output of `flatpak list | grep bottles`
