### ISSUE TITLE
Bottle Need Internet Connection

### ISSUE THREAD

**Issue by ssmns** [bottlesdevs/Bottles#2151]
!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!
I used bottle for my work, this day in Iran we have problem to connect to the internet, my bottle doesn't run any more and need internet connection. 
![image](https://user-images.githubusercontent.com/21356156/194795851-21aad4b8-da36-47ab-99d8-4d69439b3f19.png)

The software does not load for more than 5 minutes

**Comment by mirkobrombin** [comment]
run with FORCE_OFFLINE=1 set
