### ISSUE TITLE
[Bug]: Void Linux: every thing is crash

### ISSUE THREAD

**Issue by ayoubelmhamdi** [bottlesdevs/Bottles#2153]
### Describe the bug

can not start any apps, lot of bugs

### To Reproduce

every things

### Package

Flatpak from Flathub

### Distribution

void-linux

### Troubleshooting Logs

```shell
Can not view log from apps, it's crashed, and very slow,
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by jannuary** [comment]
Hello!
You are free to receive a refund on your purchase of Bottles.

If you'd like, you can also provide more information on **concrete & specific issues** you're facing, with all the relevant info.

**Comment by ayoubelmhamdi** [comment]
how i can help you?

**Comment by mirkobrombin** [comment]
- Describe the bug:
e.g. Bottles crash when I do this thing.
- To Reproduce (follows example):
  - open bottles
  - click A
  - does B
  - ..
