### ISSUE TITLE
using existing prefix?

### ISSUE THREAD

**Issue by ExpandingMan** [bottlesdevs/Bottles#2161]
First of all, got to say that I love how incredibly easy and non-fiddly it is to just run an executable from anywhere in the prefix of a created bottle.  This has got to be by orders of magnitude the easiest way of getting a prefix that works for something that's being a pain in the ass.

However, I still would *really* like to be able to just fix a broken steam prefix rather than running everything in a new one.  Is it possible to do this?  I still don't see any way to select a directory when attempting to import or create a bottle.

For steam in particular this would make life a lot simpler and would eliminate the need to have separate shortcuts to programs that are already listed in the steam library.  It also doesn't look like the steam runtime knows when the program in the bottle is running, which I'm assuming means that steam is not going to know to upload save games and stuff like that.

**Comment by mirkobrombin** [comment]
Bottles are not simple prefixes, the software need them to be compatible. We have a specific integration for steam which lists steam proton prefixes as bottles allowing you to launch applications in there in a compatible way. You can enable it in the Bottles preferences

**Comment by mirkobrombin** [comment]
Where is the .steam path located in your sys?

**Comment by ExpandingMan** [comment]
`~/.local/share/Steam` which I believe is the default.  The soft link `~/.steam` is also present.

**Comment by mirkobrombin** [comment]
fixed in latest commit, I'll push an hotfix soon

**Comment by ExpandingMan** [comment]
Nice, thanks!
