### ISSUE TITLE
How does FSR actually work in Bottles? 

### ISSUE THREAD

**Issue by ghost573** [bottlesdevs/Bottles#2164]
Sorry, there is no documentation for how FSR is meant to work in Bottles.

Am I meant to set the game resolution lower than FSR will upscale it or set the resolution higher then FSR renders the game lower than native and then upscales to the native resolution.
Do I need to turn gamescope on for FSR to work or will it work without gamescope.

Asking because I don't think it's working.

**Comment by mirkobrombin** [comment]
You don't need gamescope, just turn on FSR. If I'm not wrong, the game must support it

**Comment by ghost573** [comment]
> If I'm not wrong, the game must support it

Ah, so it's not like Lossless Scaling on windows where you can "force" FSR to run for all games. 
Is there a way to do that?

**Comment by TheEvilSkeleton** [comment]
The runner must support FSR (I don't know if Caffe does), and the game needs to use Vulkan, as FSR on Linux supports anything that uses Vulkan. wine-ge-custom and proton-ge-custom recently got FSR support again, so it's possible that you were using a runner that didn't support FSR.

**Comment by ghost573** [comment]
> it's possible that you were using a runner that didn't support FSR.

I've been using caffe since it's developed by the same team as bottles.

**Comment by TheEvilSkeleton** [comment]
I'm not involved with Caffe development so I can't comment on Caffe's support for FSR. However, I do know that wine-ge-custom (or GE-Wine in Bottles) does, which was introduced since [7-31](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-31).

**Comment by ghost573** [comment]
I guess I'll switch to ge-wine for the time being.
Thanks for the assistance.

**Comment by mirkobrombin** [comment]
> > Am I meant to set the game resolution lower than FSR will upscale it or set the resolution higher then FSR renders the game lower than native and then upscales to the native resolution.
> 
> If by "game resolution" you are talking about the "Game Resolution" section in the Gamescope settings, then it's up to you. You can downscale the resolution (which will run faster than native), or upscale the resolution (which will run slower than native).
> 
> > Do I need to turn gamescope on for FSR to work or will it work without gamescope.
> 
> You don't need Gamescope to use FSR. As long as the game runs on Vulkan (through DXVK or VKD3D), then FSR should run.
> 
> That being said, the runner must support FSR (I don't know if Caffe does @mirkobrombin can you confirm us on that?), and the game needs to use Vulkan through DXVK or VKD3D, as FSR on Linux supports anything that runs on Vulkan.
> 
> wine-ge-custom and proton-ge-custom recently got FSR support again, so it's possible that you were using a runner that didn't support FSR.

Yes, both Soda and Caffe supports FSR

**Comment by jannuary** [comment]
Can we programmatically tell whether a given runner supports FSR? It seems really obtuse and opaque otherwise.

**Comment by ghost573** [comment]
> Can we programmatically tell whether a given runner supports FSR? It seems really obtuse and opaque otherwise.

Not an issue with Bottles but there isn't a way to tell if FSR is working or not, it's not always obvious.
For example, mangohud can't display whether FSR is on https://github.com/flightlessmango/MangoHud/issues/586.

**Comment by ghost573** [comment]
I guess I was just using FSR wrong, apparently you have to set in game settings to full screen for FSR to actually work.
Borderless doesn't work and it is somewhat visible with text.

**Comment by TheEvilSkeleton** [comment]
Honestly, I don't really know how FSR works on Linux. There's little documentation and many things aren't obvious, so I appreciate for the information.

**Comment by ghost573** [comment]
No problem. Hopefully this can be added to the bottles wiki to help others.

**Comment by TheEvilSkeleton** [comment]
To be honest, I feel like System76's docs would be better since they already have docs for it.
