### ISSUE TITLE
[Bug]: On New Custom 32bit Bottle - it doesn't list out the Dependencies.

### ISSUE THREAD

**Issue by Special-Niewbie** [bottlesdevs/Bottles#2166]
### Describe the bug

Hi, 

when I try to create a New Custom 32bit Bottle, once the bottle is created, if I go to Dependencies, the list of `.dlls` to install does not appear. 

In the 64bit bottles, the Dependencies can be seen and can be easily installed.

### To Reproduce

1. Create New Bottle
2. Choose: Custom
3. Architecture 32 bit
4. Enter into the New Created 32 bit Bottle
5. On list to the left - Go to the voice `Dependencies`
6. And no one `.dll` list is showing.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1 LTS

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.0.1-surface
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16748654592
    Free: 16748494848
RAM:
    MemTotal: "33.5\_GB"
    MemAvailable: "26.8\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by rqmok** [comment]
Can confirm I am facing the exact same issue. Tried different distros such as Ubuntu, Fedora, and Garuda. Same issue on all of them.

**Comment by SirBomble** [comment]
I'm having the same issue on 32bit caffe-7.18 bottle.
OS: Elementary OS Odin 5.19.14 kernel
![image](https://user-images.githubusercontent.com/1883455/196585005-3478987d-8064-425d-9937-ef89a81a6c78.png)

**Comment by suwermave** [comment]
Have this issue too.

**Comment by bridgesense** [comment]
Any workarounds for this?

**Comment by kanopusEye** [comment]
> Any workarounds for this?

Roll back Flatpak package, 2022.8.14-brescia works for me.

```
flatpak remote-info --log flathub com.usebottles.bottles
flatpak update --commit=f416b121e7b420d478828c7cc6827feb7bd6451fb688a6b5e5b8e1f93402bba8 com.usebottles.bottles
```

**Comment by Cediddi** [comment]
I think the problem is this line: https://github.com/bottlesdevs/Bottles/blob/main/bottles/frontend/views/bottle_dependencies.py#L116

The `dep` objects look like this, none of the second items have Arch attribute and thus Amd64 is set as default arch which never matches with `Arch="win32"`  
```
('aairruntime', {'Description': 'Harman AIR runtime', 'Category': 'Essentials'})
('allfonts', {'Description': 'All Microsoft and Adobe essential fonts', 'Category': 'Fonts'})
('andale32', {'Description': 'Microsoft Andale Font', 'Category': 'Fonts'})
...
('xna40', {'Description': 'Microsoft XNA Redistributable 4.0', 'Category': 'Essentials'})
```

**Comment by kinten108101** [comment]
So no one has made a PR on this...

**Comment by natiels** [comment]
Running into the same issue here

**Comment by Zylquinal** [comment]
> I think the problem is this line:
> 
> https://github.com/bottlesdevs/Bottles/blob/fd355fbcf4e3295a2aeeb3f9fff77f7e58d327e8/bottles/frontend/views/bottle_dependencies.py#L116
> 
> The `dep` objects look like this, none of the second items have Arch attribute and thus Amd64 is set as default arch which never matches with `Arch="win32"`
> 
> ```
> ('aairruntime', {'Description': 'Harman AIR runtime', 'Category': 'Essentials'})
> ('allfonts', {'Description': 'All Microsoft and Adobe essential fonts', 'Category': 'Fonts'})
> ('andale32', {'Description': 'Microsoft Andale Font', 'Category': 'Fonts'})
> ...
> ('xna40', {'Description': 'Microsoft XNA Redistributable 4.0', 'Category': 'Essentials'})
> ```
> 
> Workaround is commenting out L116 to L118 and praying for the best joy

Or making it like this

```python
dependency_arch = dep[1].get("Arch");
if dependency_arch is not None and dependency_arch != self.config.get("Arch"):
   continue
```

**Comment by FastThenLeft** [comment]
FYI, I have this same problem with Ubuntu 22.04.2 and Bottles 51.6

**Comment by Kinsteen** [comment]
Work has been done and should be integrated in a release soon

**Comment by eylenburg** [comment]
> Work has been done and should be integrated in a release soon

I saw the pull request is still open, when do you think this new release will come?

**Comment by nimafanniasl** [comment]
Ahh, the same problem is still not fixed.

**Comment by A-Cloud-Ninja** [comment]
Also awaiting this myself!
