### ISSUE TITLE
[Request]: Consider bundling Gamescope

### ISSUE THREAD

**Issue by travier** [bottlesdevs/Bottles#2169]
### Tell us the problem or your need

Gamescope is currently non functional in Bottles: https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/59

### Describe the solution you'd like

Bundling Gamescope directly in the Bottles Flatpak until https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/59 is solved or we find another option.

### Other solutions?

Submitting Gamescope as a standalone extension.

### Additional context and references

Lots in https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/59

**Comment by Adi-ionut** [comment]
I'm a bit confused now... Gamescope seems to be working fine for me? No errors and such. Is there something I'm missing?

**Comment by travier** [comment]
Bottles moved to a 22.08 based Runtime so this is not an issue anymore for now.

**Comment by orowith2os** [comment]
Could this issue be reopened, and possibly implemented? Even if it's not an issue *now*, it *can*, and most likely *will*, be an issue in the future.

Adding gamescope to the flatpak wouldn't hurt much or anything at all anyways, as it would function normally (without risk), and storage isn't a concern, as it can be deduplicated if possible.

**Comment by mirkobrombin** [comment]
Gamescope is already built with the flatpak
