### ISSUE TITLE
[Request]: Create empty library covers when adding to library to allow covers for games not in SteamGridDB 

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2170]
### Tell us the problem or your need

I currently have just one game that detected cover art and I can't figure out how to make custom art for my other games. I don't even get how the Bottles assigned the first one. There are 2 .PNGs in grids folder and only second is used by Bottles which means I can edit it however I want (which is fantastic by the way and also works with the icon so I can easily make distinct game icons for modded versions, please leave it like that). However as I said I can't figure out how Bottles decides what entry is it for. You see they have some weird ID (both of them different) which doesn't appear anywhere in bottles.yml, game icon at least has the same name as name field in bottle.yml (which by the way is confusing at it's own and I would like you to explain it more in my older feedback issue here)
![2022-10-17_21-11-31](https://user-images.githubusercontent.com/84787215/196262676-0e32ef84-ea87-4a9e-ba98-264577c3e7b0.png)
If you want to check bottle.yml yourself check my older issue because I pasted it back then and it's still the same.

Now leaving that issue aside I thought about some kind of hacky solution to allow users to make their own covers for games that are not detected by SteamGridDB. You can kind of see it already in the above image.

### Describe the solution you'd like

To fix this I would always create an empty .png cover when adding a game/program to the library. I tested it out by deleting everything from the used cover essentially just leaving transparent 600x900 png image and it just shows like other entries in the library that don't have the cover art. Users then could go to their bottle's grids folder and make the custom art themselves by using their favorite editor.

### Additional context and references

Also while I'm at it, can we get a slider to choose cover art size in library view? It's gigantic. Here for comparison the covers on Steam:
![2022-10-17_21-24-37](https://user-images.githubusercontent.com/84787215/196264978-052c43a2-69de-4179-a2b8-11abb5c275d7.png)

**Comment by mirkobrombin** [comment]
Thanks for reporting.
Merging with #1277

**Comment by MrQuerter** [comment]
Can you at least share how Bottles decided this cover art name is correct for that entry? I could then make covers for other entries myself while waiting for the official feature.

**Comment by mirkobrombin** [comment]
Bottles uses the streamgriddb api, just passing the program name

**Comment by MrQuerter** [comment]
That's not what I asked about, but never mind. I found it by searching in file contents inside Bottles directory.

If anybody's curious in the future: it's in library.yml

And it's in different format than icon.
Icon uses path and cover art uses grid:name.png
