### ISSUE TITLE
[Bug]: Mangohud doesn't display any information when Gamescope is active

### ISSUE THREAD

**Issue by ghost573** [bottlesdevs/Bottles#2172]
### Describe the bug

When gamescope is active, mangohud doesn't display any information.

### To Reproduce

1. Turn on gamescope
2. Turn on mangohud
3. Launch game
4. Mangohud doesn't appeaar

### Package

Other, unofficial package

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.2-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 1006451294208
    Free: 849016549376
RAM:
    MemTotal: "14.6\_GB"
    MemAvailable: "12.0\_GB"
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Not sure if I'm missing a command but I couldn't find anything on the guide regarding this.

**Comment by Adi-ionut** [comment]
Same here. Mangohud is buggy when used with gamescope. If I hide it I can't unhide it anymore, it remains hidden. It also doesn't show the correct information.

**Comment by mirkobrombin** [comment]
Mangohud is not a Bottles project. We just provide support for it.

**Comment by ghost573** [comment]
> Mangohud is not a Bottles project. We just provide support for it.

No problem , will report on their repo.
