### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by casablanker** [bottlesdevs/Bottles#2173]
### Describe the bug

just when starting bottles...

![Bottles Crash Report_001](https://user-images.githubusercontent.com/55688001/196589545-119b98f1-b730-4c7f-ab36-a4ab412fa9d6.png)

### To Reproduce

just start bottles

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.2-x64v1-xanmod1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16519933952
    Free: 16519794688
RAM:
    MemTotal: "33.0\_GB"
    MemAvailable: "21.8\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Please upgrade, this was already fixed.
