### ISSUE TITLE
[Bug]: Bottles opens Welcome wizard unwantedly

### ISSUE THREAD

**Issue by drws** [bottlesdevs/Bottles#2175]
### Describe the bug

Currently I don't have any active bottles. I also removed all runners from Bottles while I'd like to keep all of my other settings. When there are no runners installed, Bottles will open the welcome screen even though we've known each other for some time. I think it only tests whether there are any runners installed and/or it doesn't save its state properly.

### To Reproduce

1. Remove all bottles (might not be necessary, please test if you can)
2. Remove all runners
3. Restart Bottles
4. Welcome screen will be shown (which is a bug)

### Package

Other, unofficial package

### Distribution

Arch Linux

### Troubleshooting Logs

I cannot access _About Bottles_ and subsequently the _Troubleshooting_ menu since Bottles forces the Welcome wizard upon me. I don't want to go through the Wizard (again), which is the point of the issue. If I close the Wizard, Bottles exits.

**Comment by mirkobrombin** [comment]
Not a bug. There must be at least 1 runner, otherwise Bottles will not works.

**Comment by drws** [comment]
After the last runner is removed, Bottles works just fine for browsing the settings until it is closed. When started the next time, the "Welcome" screen appears. This is an inconsistency.

Also, it is still not clear whether the Welcome wizard overwrites other settings since it's a standard software practice for a Welcome wizard to do so - initialize an application configuration. If not, the name is unfortunately misleading.

Unfortunately it seems I can't reopen, but I believe it should be.
