### ISSUE TITLE
[Bug]: Welcome wizard installs Soda, not Caffe

### ISSUE THREAD

**Issue by drws** [bottlesdevs/Bottles#2177]
### Describe the bug

I read in [Bottles' docs](https://docs.usebottles.com/components/runners) that Caffe is the official runner, but Welcome wizard installs Soda. How so? 

### To Reproduce

1. Start Bottles for a first time
2. Go through the Welcome wizard
3. Work around the #2176
4. Observe installed runners

### Package

Other, unofficial package

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
```

**Comment by mirkobrombin** [comment]
No more, Soda is the new default.
