### ISSUE TITLE
[Bug]: Bottles takes almost 20 minutes to load

### ISSUE THREAD

**Issue by marcegs** [bottlesdevs/Bottles#2179]
### Describe the bug

Installed bottles via flatpak, it takes almost 20 minutes to load everything. Once done, works as expected. (this happens always)

Terminal output:
$ flatpak run com.usebottles.bottles
20:15:38 (INFO) Bottles Started! 
20:31:02 (INFO) Catalog components loaded 
20:33:13 (INFO) Catalog installers loaded 
20:35:24 (INFO) Catalog dependencies loaded 
20:35:24 (INFO) Performing Bottles checks… 
20:35:24 (INFO) Dxvks found:
         - dxvk-1.10.3
 
20:35:24 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
 
20:35:24 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
20:35:24 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
20:35:24 (INFO) Runners found:
         - sys-wine-7.0
         - soda-7.0-4
 
20:35:42 (INFO) Bottles found:
         - Muse Dash
 
20:35:42 (INFO) Library saved 

### To Reproduce

1. open Bottles.

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16795320320
    Free: 16795181056
RAM:
    MemTotal: "33,6\_GB"
    MemAvailable: "30,9\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Related/duplicate #2057
