### ISSUE TITLE
[Bug]: Can't type chinese in bottles app. However chinese can be typed in bare wine install

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#2180]
### Describe the bug

I can't type Chinese in bottles app , no matter line or notepad++. However, when I install in bare wine without bottles , Chinese input works just fine. I think it may be the flatpak sandbox issue but I'm not sure

### To Reproduce

1. use bottle install 'notepad++' (I used custom with sys.wine 7.0)
2. ready for chinese input method(ibus for example) by 'apt install ibus '
3. install 'ibus-chewing' by 'apt install ibus-chewing'
4. change input to 'chewing'(look like '新酷音')

![圖片](https://user-images.githubusercontent.com/66060998/196852500-7c4c2fc9-1b7a-4475-b412-9e485c55e963.png)
5. open notepad++
6. type example word '(su3)' and it should show up a 你 (means you by the way) below i type both in notepad++ and bottles search bar in comparison
![圖片](https://user-images.githubusercontent.com/66060998/196853682-089c4dff-0fdb-4204-9396-f6cbc67a1a0b.png)

if you want to compare welcome to use bare wine install to see the difference

### Package

Flatpak from Flathub

### Distribution

pop os 22.04

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-76051900-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8361349120
    Free: 8361205760
RAM:
    MemTotal: "16.7\_GB"
    MemAvailable: "11.1\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by csc-chicken** [comment]
I think fcitx5 somewhat fix ?? let me try

**Comment by csc-chicken** [comment]
I think it is successful for fcitx5 I think right now maybe

**Comment by jannuary** [comment]
Can't seem to replicate with the default Pinyin ibus IME on Fedora, ignoring the missing fonts:
![image](https://user-images.githubusercontent.com/27908024/196892691-3743db6d-201b-4246-a5d3-98b4c54d80d6.png)

**Comment by csc-chicken** [comment]
does the word show up on area you select on picture??

**Comment by StoneMoe** [comment]
I'm experiencing this issue too with `ibus-pinyin` in flatpak version, with default Application bottle preset.
