### ISSUE TITLE
[Bug]: Remove a Bottle not working on Steam Deck

### ISSUE THREAD

**Issue by LiamDawe** [bottlesdevs/Bottles#2196]
### Describe the bug

It seems the Remove Bottle option on Steam Deck removes it from the list, but doesn't actually remove the folder so it appears again when you reload. Forcing a manual removal of the folder.

See here: https://www.youtube.com/watch?v=6OnKebBoKzY

### To Reproduce

Try it on Deck.

### Package

Flatpak from Flathub

### Distribution

SteamOS Steam Deck

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.3-1-neptune
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 7778668544
    Free: 7778525184
RAM:
    MemTotal: "15.6\_GB"
    MemAvailable: "12.0\_GB"
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Idk what `Totally missed doing this the first time....` means. Provide all the information please.

**Comment by LiamDawe** [comment]
Added
