### ISSUE TITLE
[Request] lib bottles or CLI

### ISSUE THREAD

**Issue by Stew-rt** [bottlesdevs/Bottles#220]
I'd like the ability to create, modify or run bottles from within other applications.
I'd like to be able to do this by importing libbottles.

At a push, it would also be satisfactory to have a CLI utility to popen instead, and may have broader appeal.

**Comment by mirkobrombin** [comment]
Already planned #133

**Comment by Stew-rt** [comment]
Wonderful :+1: closing issue.
