### ISSUE TITLE
[Bug]: Environment variables not really removed until Bottles restart

### ISSUE THREAD

**Issue by mxj4** [bottlesdevs/Bottles#2200]
### Describe the bug

When deleting environment variables from GUI, they are not really removed until I restart Bottles, instead, the values were set to `False` (in some python code? maybe that's equivalent to not setting environment variables in the actual wine commandline but I'm not sure).

If this is not actually a bug, maybe we should remove the logs that are showing removed environment variables as `False`.

### To Reproduce

1. Start Bottles flatpak version from CLI so that we see logs
2. Remove some previously set environment variables, such as `GDK_BACKEND` and `DISPLAY` (I was trying to figure out how to run wine-wayland runner when xwayland was not completely disabled, but that could be another github issue)
3. Launch a legacy wine tool such as Explorer from the UI
4. You will see logs like
   ```
   12:31:18 (INFO) Library saved 
   12:31:36 (INFO) Setting Key GDK_BACKEND=False for bottle gaming… 
   12:31:37 (INFO) Setting Key DISPLAY=False for bottle gaming… 
   12:31:43 (INFO) Using Wine Explorer -- launch
   ```
5. Restart Bottles
6. Launch Explorer again from the UI
7. You will see logs like
   ```
   12:32:40 (INFO) Library saved 
   12:32:46 (INFO) Using Wine Explorer -- launch
   ```

Even without a restart, we shouldn't see
```
12:31:36 (INFO) Setting Key GDK_BACKEND=False for bottle gaming… 
12:31:37 (INFO) Setting Key DISPLAY=False for bottle gaming… 
```

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd: &amp;id002
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.0.2-zen1-1-zen
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8091996160
    Free: 8091852800
RAM:
    MemTotal: "16.2\_GB"
    MemAvailable: "10.1\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
I'm not able to replicate this, even following your exact steps. Do you have some more details?
