### ISSUE TITLE
[Bug]: Starting Bottles takes 30-45 minutes.

### ISSUE THREAD

**Issue by SteveTinkers** [bottlesdevs/Bottles#2201]
### Describe the bug

Starting Bottles takes 30-45 minutes, sometimes an hour.  It does this ever time on every open, and not just the first run on a fresh install.

The loading screen displays and says
"Fetched X of 3 packages"
"Downloading ~20kb of packages..."

It might as well be 20GB of packages... although it's not saturating my network.

### To Reproduce

Fresh system download flatpak and start Bottles.

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.16-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16412930048
    Free: 16412782592
RAM:
    MemTotal: "32.8\_GB"
    MemAvailable: "28.0\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Related/duplicate https://github.com/bottlesdevs/Bottles/issues/2057

**Comment by SteveTinkers** [comment]
Oh I see.  It's quite possible this is a bug related to the download. 

FWIW...
I removed the flatpak version (2022.10.14.1) and installed the version in the regular repo (2022.5.28-trento-3).
Same results, first start is slow.  I'd think a problem with initialization rather than the flatpack itself...

**Comment by mirkobrombin** [comment]
The whole repository manager will be rewriten to avoid the download, so the problem will disappear one day D:

**Comment by ben2talk** [comment]
So no solution here - https://i.imgur.com/Um9wbfb.png
