### ISSUE TITLE
Repeateadly closed, and now locked discussion about CoC matters

### ISSUE THREAD

**Issue by comradekingu** [bottlesdevs/Bottles#2205]
As a reply to [this](https://github.com/bottlesdevs/Bottles/pull/2204#issuecomment-1290213658)
I had a reply written up, that I could not post, so I will leave it here instead of using means of hiding public discourse I don't believe in.

> Hello!
> 
> No.

From the text-file attemptedly codifying conduct.

>We value your participation and want everyone to have an enjoyable and fulfilling experience. Accordingly, all participants are expected to follow this Code of Conduct, and to show respect, understanding, and consideration to one another. Thank you for helping make this a welcoming, friendly community for everyone.

> **Be friendly.** Use welcoming and inclusive language.
 **Be empathetic.** Be respectful of differing viewpoints and experiences.
 **Be respectful.** When we disagree, we do so in a polite and constructive manner.
 **Be considerate.** Remember that decisions are often a difficult choice between competing priorities. Focus on what is best for the community. Keep discussions around technology choices constructive and respectful.
 **Be patient and generous.** If someone asks for help it is because they need it. When documentation is available that answers the question, politely point them to it. If the question is off-topic, suggest a more appropriate online space to seek help.

>Community members asked to stop any inappropriate behavior are expected to comply immediately.
We want all participants in the GNOME community have the best possible experience they can.

I posit that having this language in a text-file is of no particular relevance, and that reading into it that it actually applies tricks vulnerable individuals into thinking that is the case, or mandated.

This particular concern is addressed in this PR #2204

**Comment by jannuary** [comment]
Hello again. 

If you are dissatisfied with the GNOME CoC, you are very much free to contact them or to fork Bottles to remove the so-called "authoritarian" code of conduct. 
On the Bottles side, which is comprised of many marginalized people who these rules specifically are meant to protect, might I add, we are not willing to discuss how we should accept and allow hate speech. If you find that "authoritarian", well, I do not think we can help you with that.
