### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Segm3nts** [bottlesdevs/Bottles#2206]
### Describe the bug

Wine froze when installing Battle.net.

### To Reproduce

1. Create a new bottle with the "gaming" preset
2. Run the Battle.net installer
3. Wait for it to freeze

### Package

Other, unofficial package

### Distribution

Manjaro Linux

### Troubleshooting Logs

```shell
While reading from '/home/USER/Games/Bottles/Gaming/drive_c/users/jozua/Documents/Overwatch/Settings/Settings_v0.ini' [line  8]: option 'movieexport.1' in section 'General.0' already exists  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/installer.py", line 481, in install
    if not self.__perform_steps(_config, steps):

  File "/usr/share/bottles/bottles/backend/managers/installer.py", line 196, in __perform_steps
    self.__step_update_config(config, st)

  File "/usr/share/bottles/bottles/backend/managers/installer.py", line 293, in __step_update_config
    _conf = ConfigManager(config_file=conf_path, config_type=conf_type)

  File "/usr/share/bottles/bottles/backend/managers/conf.py", line 15, in __init__
    self.config_dict = self.read()

  File "/usr/share/bottles/bottles/backend/managers/conf.py", line 33, in read
    config.read(self.config_file)

  File "/usr/lib/python3.10/configparser.py", line 698, in read
    self._read(fp, filename)

  File "/usr/lib/python3.10/configparser.py", line 1097, in _read
    raise DuplicateOptionError(sectname, optname,
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Installed using the package in the Arch User Repository (AUR)

**Comment by mirkobrombin** [comment]
Pleas provide the instructions and attach the right Troubleshooting Logs

**Comment by Segm3nts** [comment]
Trying to replicate but cannot (now that I've tried using caffe it works).
Also don't think I can backtrace to get the logs; I assumed what was posted above were the logs. Where do I find those? It seems I need to replicate it while in the terminal (and I can't seem to replicate it).
Instructions also described above in "To Reproduce" (not very specific I know, but that's what happened).
Since I'm not having this issue anymore it'd probably be alright to close this issue unless you want to suss it out further.

**Comment by mirkobrombin** [comment]
menu > about > troubleshooting > debugging information
