### ISSUE TITLE
Can't launch Overwatch (No compatible grafics hardware was found. OxE00701B0)

### ISSUE THREAD

**Issue by KiritoStorm** [bottlesdevs/Bottles#2210]
Hello, 

I already experienced this issue a few version before but was fixed the next day. (before OW2 Release)
Since the last updates, in the time where Overwatch 2 was released (04.10.22) there were some issue with Battle.net that seems to be fixed now.

I somehow still have the problem that I can't launch Overwatch with the Battle.net Launcher.
![image](https://user-images.githubusercontent.com/46503102/198582943-f62c21a7-d621-4e33-be83-2fea718eadb0.png)

I don't use the predefined installer, because of the night-light mode issues on Zorin #1662, but I can try that if needed, I just need to get some space on my disk.

OS: Zorin OS 16.2, the problem was also happening on 16.1.

**Comment by mirkobrombin** [comment]
Hi, please follow the bug report template https://github.com/bottlesdevs/Bottles/issues/new/choose
