### ISSUE TITLE
[Bug]: Can't launch bottles, missing GTK5

### ISSUE THREAD

**Issue by xenos9** [bottlesdevs/Bottles#2214]
### Describe the bug

When I launch bottles from the menu, nothing happens. Launching from the terminal gives the following
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 28, in <module>
    gi.require_version('GtkSource', '5')
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 5

### To Reproduce

1. Go to applications menu
2. select and click 'bottles' 

### Package

From source

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Can't do
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Not sure about installation "from source". I used the default Discover manager, the installed app doesn't have the flatpak tag

**Comment by mirkobrombin** [comment]
Sorry we don't provide support for that package.
Maybe our packaging wiki can help you https://github.com/bottlesdevs/Bottles/wiki/Packaging
