### ISSUE TITLE
[Request]: Prefix directory names cannot have spaces (Spaces are replaced with a dash)

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#2217]
### Tell us the problem or your need

If I create a new bottle and in the name of that bottle it contains a space, the folder for the bottle will replace the spaces in the name with a dash. For example if my bottle is named "Call Of Duty 4" the bottle directory will be named "/home/john/Wine/Call-Of-Duty-4/"

### Describe the solution you'd like

Would like bottle directory names to allow spaces.

**Comment by mirkobrombin** [comment]
This is intentional to avoid handling future problems with having spaces since that value is used in multiple ways inside the bottles backend.
