### ISSUE TITLE
[Request]: Choose Runner Directories

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#2218]
### Tell us the problem or your need

Runners always having to be stored in a specific directory inside the Bottles application

### Describe the solution you'd like

An setting when you create a bottle to choose a runner in a different directory then the default directory.

And the ability to download and install runners in Bottles to another directory of the users choice.

**Comment by jannuary** [comment]
Usecase? Bottles provides its own runners.

**Comment by trymeouteh** [comment]
> Usecase? Bottles provides its own runners.

A use case for me would be that I have two harddrives. My main harddrive which is what the OS is installed on is a HDD, while my secondary drive is a SSD which I install games on. Would like to have the runner also installed on the SSD for better performance in my games and not have the runner on my HDD which will be slower.

**Comment by jannuary** [comment]
Uh, why do you have it set up like that? 
Either way, I think this is fairly niche, you could just symlink the Bottles runner directory to an external hard drive.

**Comment by trymeouteh** [comment]
> Uh, why do you have it set up like that?

Since SSD drives can be faster to read from.

> you could just symlink the Bottles runner directory to an external hard drive.

True, but this will require the terminal and is not beginner friendly, where as bottles takes out lots of the terminal when using wine.

**Comment by orowith2os** [comment]
You can create symlinks via the GUI - right click a file, and hit "copy". Then go to where you want the link to be placed, right click, and hit "paste as link". 

Like Noëlle said, this is probably fairly niche. I do think it could be useful, but the Bottles devs are focusing on bug fixes right now; there's a severe case of burnout, and nobody has the time to keep working on it. We could come back to it when we have more time to ourselves.
