### ISSUE TITLE
[Bug]: Bottles unsets `XDG_DATA_HOME`

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#2219]
### Describe the bug

Bottles unsets the environment variable `XDG_DATA_HOME`.

### To Reproduce

1. Have the environment variable `XDG_DATA_HOME` and `XDG_CONFIG_HOME` set to a value.
1. Prepend the following start option command to a working program entry:
    `notify-send "${XDG_DATA_HOME:-unset}" && %command%`
3. Have a notification pop up saying "unset".
4. Verify against `XDG_CONFIG_HOME`, which is correctly carried over:
    `notify-send "${XDG_CONFIG_HOME:-unset}" && %command%`
1. A notification pops up with your set environment config_home variable.

### Package

From source

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.5-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 116976529408
    Free: 23112101888
RAM:
    MemTotal: "12,4\_GB"
    MemAvailable: "5,8\_GB"
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

Probably caused by c64cefdf18f66b90e38c822790977124bb16d8af

**Comment by mirkobrombin** [comment]
re-implementing this will result in https://github.com/bottlesdevs/Bottles/issues/2127

**Comment by Lucki** [comment]
That looks like a bug in Godot where this issue should be adressed. Unsetting a perfectly working environment variable seems wrong to me.
