### ISSUE TITLE
Unable to install Bottles

### ISSUE THREAD

**Issue by chiragnahata** [bottlesdevs/Bottles#2221]
### Describe the bug

I am unable to install the bottles app on my computer

### To Reproduce

1. sudo apt install flatpak
2. sudo apt install gnome-software-plugin-flatpak
3.  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
4. flatpak install flathub com.usebottles.bottles

### Package

Flatpak from Flathub

### Distribution

arm64 / aarch64

### Troubleshooting Logs

```shell
None
```

### Additional context

![image](https://user-images.githubusercontent.com/63905783/198844796-170e058f-f961-42df-b12a-5b94c3818a24.png)

**Comment by axtloss** [comment]
Bottles does not provide any form of arm flatpak packages, so flatpak will tell you that it can't find any bottles package since it doesn't exist for the architecture you are using

**Comment by Vitalicus** [comment]
When ARM64 will be available?

**Comment by orowith2os** [comment]
Most likely? Not until all the infra is set up so aarch64 builds of things like Wine-GE are set up. 

You can build *Bottles* for aarch64, but it relies on amd64 binaries basically everywhere. And of course the games need arm64 builds themselves.

Just run Bottles through qemu-user-static. Flatpak works perfectly well with that.
