### ISSUE TITLE
Where did the "Bottles Runtime" and part of the Russian localization go?

### ISSUE THREAD

**Issue by DonnerTechQ2** [bottlesdevs/Bottles#2226]
Where did the "bottles runtime" and part of the Russian localization go?
![Снимок экрана от 2022-10-30 22-57-39](https://user-images.githubusercontent.com/97617295/198899126-76a1b5f0-e398-443f-9dc4-bb3e2dd30014.png)

I am sure that in previous versions this text was localized
![Снимок экрана от 2022-10-30 22-57-22](https://user-images.githubusercontent.com/97617295/198899127-aaedd3be-9032-499e-8e8f-61b02b731dca.png)

**Comment by TheEvilSkeleton** [comment]
If you're using Flatpak, then Bottles Runtime is automatically hidden, as it's not really useful within Flatpak. If you're using an unofficial package, then it will be there. As for Russian localization, those parts weren't translated, so they fall back to English.
