### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BrandowLucas** [bottlesdevs/Bottles#2241]
### Describe the bug

'CSDVersion'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 144, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 286, in __perform_steps
    self.__step_set_windows(

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 675, in __step_set_windows
    rk.set_windows(step.get("version"))

  File "/app/share/bottles/bottles/backend/wine/regkeys.py", line 125, in set_windows
    "data": win_versions.get(version)["CSDVersion"]

### To Reproduce

1. Going to an Application Bottle
2. Dependencies
3. Installing mdac28, consolas, dotnet 35, dotnet 35sp1

### Package

Flatpak from Flathub

### Distribution

Nobara Linux 36

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.5-201.fsync.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 3817582592
    Free: 3817439232
RAM:
    MemTotal: "7.6\_GB"
    MemAvailable: "2.3\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Fixed some commits ago
