### ISSUE TITLE
[Bug]: the problem with the Russian locale in RHEL-9

### ISSUE THREAD

**Issue by UserNameWww** [bottlesdevs/Bottles#2242]
### Describe the bug

At the first installation, the Russian language was completely displayed, but after the rebooting of the system, Kwadratics or Krakjabs were selected to replace the language
And with the other Appendices in Flatpak with the Russian Lokale, everything's fine
Got Bottles only yesterday.

### To Reproduce

Got Bottles through Flatpak.
Reboot the system
Started it through Flatpak

### Package

Flatpak from Flathub

### Distribution

RHEL-9(base Red Hat 9)

### Troubleshooting Logs

```shell
everywhere and all of the Quadratics text, there's no reading
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Here's Log from Terminal

10:53:47 (INFO) Bottles Started! 

(bottles:2): Pango-WARNING **: 10:53:48.059: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Ultra-Bold 20'

(bottles:2): Pango-WARNING **: 10:53:48.059: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.059: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.059: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Ultra-Bold 20'

(bottles:2): Pango-WARNING **: 10:53:48.059: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.059: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.060: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(bottles:2): Pango-WARNING **: 10:53:48.060: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.060: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.061: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(bottles:2): Pango-WARNING **: 10:53:48.061: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.061: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.062: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(bottles:2): Pango-WARNING **: 10:53:48.062: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.062: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.062: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(bottles:2): Pango-WARNING **: 10:53:48.062: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:48.062: scaled_font status is: file not found
10:53:52 (INFO) Catalog components loaded 
10:53:52 (INFO) Catalog installers loaded 
10:53:54 (INFO) Catalog dependencies loaded 
10:53:54 (INFO) Performing Bottles checks… 
10:53:54 (INFO) Dxvks found:
	 - dxvk-1.10.3
 
10:53:54 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.7
 
10:53:54 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
10:53:54 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
10:53:54 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-7
 
10:53:55 (INFO) Bottles found:
	 - BATTLE-NET
 
10:53:55 (INFO) Library saved 

(bottles:2): Pango-WARNING **: 10:53:55.537: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 8.25'

(bottles:2): Pango-WARNING **: 10:53:55.537: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.537: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.538: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 8.25'

(bottles:2): Pango-WARNING **: 10:53:55.538: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.538: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.573: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 9'

(bottles:2): Pango-WARNING **: 10:53:55.573: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.573: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.574: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 9'

(bottles:2): Pango-WARNING **: 10:53:55.574: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:53:55.574: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.134: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Ultra-Bold 15'

(bottles:2): Pango-WARNING **: 10:54:45.134: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.134: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.134: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Ultra-Bold 15'

(bottles:2): Pango-WARNING **: 10:54:45.134: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.134: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.136: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 9.1669921875'

(bottles:2): Pango-WARNING **: 10:54:45.136: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.136: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.137: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 9.1669921875'

(bottles:2): Pango-WARNING **: 10:54:45.137: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.137: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.188: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 9'

(bottles:2): Pango-WARNING **: 10:54:45.188: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.188: scaled_font status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.189: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 9'

(bottles:2): Pango-WARNING **: 10:54:45.189: font_face status is: file not found

(bottles:2): Pango-WARNING **: 10:54:45.189: scaled_font status is: file not found

**Comment by mirkobrombin** [comment]
I think this is distro problem rather than Bottles

**Comment by UserNameWww** [comment]
> 

You are right, in some Programs from Flatpak the same thing, and in some everything is fine.

**Comment by jannuary** [comment]
If "some" > 1, it's likely unrelated to Bottles.
