### ISSUE TITLE
[Bug]: Failure to launch multiple programs in Steam OS Gaming Mode

### ISSUE THREAD

**Issue by GamerGoat112** [bottlesdevs/Bottles#2244]
### Describe the bug

After launching one program through steam, a second one will not launch. It stays on the steam loading screen.

### To Reproduce

1. Add 2 Bottles Programs to Steam
2. Launch one
3. Try to launch the other

### Package

Flatpak from Flathub

### Distribution

Steam OS

### Troubleshooting Logs

```shell
I am unable to do this in gaming mode for some reason.
```

### Display Backend used by Bottles

I don't know

### Additional context

I am trying to run Rocket League with Bakkesmod at the same time in Steam OS Gaming Mode

**Comment by mirkobrombin** [comment]
Closing since the given details does not help me debugging.
