### ISSUE TITLE
[Bug]: Bottle creation dialog is broken.

### ISSUE THREAD

**Issue by markusgod** [bottlesdevs/Bottles#2249]
### Describe the bug

Bottle creation UI acting weird. Maybe this is my system's problem, but I haven't encountered any other gtk4 app with a similar bug.

[video.webm](https://user-images.githubusercontent.com/20001291/201401708-5f555257-ec48-4415-ae89-68d2189d723b.webm)

### To Reproduce

Open bottles
Create new bottle.

(See video example)

### Package

Flatpak from Flathub

### Distribution

openSUSE Tumbleweed

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.7-1-default
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16769114112
    Free: 16768962560
RAM:
    MemTotal: "33.5\_GB"
    MemAvailable: "27.1\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
The video is not loading, Github being Github

**Comment by markusgod** [comment]
Ok, let's try again.

https://user-images.githubusercontent.com/20001291/201492294-7e41b434-14ed-4f73-8756-004e94f14184.mp4

**Comment by markusgod** [comment]
Ok, same bug now affects me in network settings, something gone wrong with my system.
