### ISSUE TITLE
[Request]: Use portal API when selecting a drive's backing folder

### ISSUE THREAD

**Issue by tesfabpel** [bottlesdevs/Bottles#2251]
### Tell us the problem or your need

When using the flatpak version of the software, in the Drive Management window (the one when you can assign drive letters, I'm using a translated UI so the name may not be the same) if you click the folder icon to select the backing directory of a drive, you can't select much folders since Bottles doesn't have such permission.

### Describe the solution you'd like

A modern way to fix this is (I believe) to use the portal API for directory selection (`org.freedesktop.portal.FileChooser` with `directory` option maybe? I don't know).

### Other solutions?

Another solution would be giving blanket access to the host's filesystem, but of course, it's not advisable.

**Comment by TheEvilSkeleton** [comment]
Can you test using the the test build from https://github.com/bottlesdevs/Bottles/suites/9272887593/artifacts/434389571? I made it use the portal which _should_ work, however I'm not too sure about its working condition so I'd prefer if someone could test it for me. Also, create a backup of your directory before testing!

**Comment by tesfabpel** [comment]
I've tried the test build but, sadly, it seems it doesn't work. 
The native file dialog allows me to choose any directory the host has access to, but it doesn't get saved in "Manage Drives". 
I've also tried picking a path Bottles should have access to with no avail, so it seems there is a bug somewhere else which I believe it should be independent from 675f0cc39ae997df22c236deea88229e15e70ac4, since it only changes a single bool (maybe it's useful to have that commit rebased on the latest public release?).
Closing the window and reopening it, the new drive letter is not shown again.
![Image](https://user-images.githubusercontent.com/1371976/201518736-35d11c7d-ecda-4603-940a-549f3e249fb7.png)

I've also tried creating a new (gaming) bottle but the results are the same sadly.

I'm trying to debug what's happening but I can't promise I will manage.

**Comment by tesfabpel** [comment]
Strangely, it seems the native file dialog returns a response of `ACCEPT` instead of `OK`:
![Image](https://user-images.githubusercontent.com/1371976/201524987-ea14b670-c0d2-4069-ad15-8ce701f51850.png)

Changing the line `if _file is None or response != Gtk.ResponseType.OK:` to `if _file is None or response != Gtk.ResponseType.ACCEPT:` fixes it:
![Image](https://user-images.githubusercontent.com/1371976/201525015-9f7afc7b-15bf-45f6-b921-3549ed61026d.png)

I can confirm now that the drive gets added and it works. It also seems that the previous path I've chosen are persisted through launches and reinstallations of Bottles. 
![Image](https://user-images.githubusercontent.com/1371976/201525480-05bc3415-803f-4e91-beb6-24f88f0dc51d.png)

**Comment by TheEvilSkeleton** [comment]
Nice catch. I completely missed that!

**Comment by TheEvilSkeleton** [comment]
Can you try this build https://github.com/bottlesdevs/Bottles/actions/runs/3455802682/jobs/5768080864? Also, as @mirkobrombin asked, does it work after you reboot?

**Comment by tesfabpel** [comment]
I can confirm it persists after reboots and reinstalls (tried with my test version and the one in your last message):
![Image](https://user-images.githubusercontent.com/1371976/201541633-7d5b3a76-2657-4e51-b174-09033fa2b27e.png)

The game installed in the bottle (under `T:`) launches correctly.

As a note though: adding the game's .exe to the bottle's program list via the "Add shortcut" button creates a new document mapping resulting in a virtual directory with only that .exe inside. I have to use Wine's explorer to launch the game by navigating to the .exe location and double clicking it (`T:\...\...\abc.exe`). Maybe it should be possible to select the .exe inside the flatpak document map so that it reuses the previous mapping (in my case the one under `/run/user/1000/doc/19ef51/.../.../abc.exe`).

**Comment by TheEvilSkeleton** [comment]
> As a note though: adding the game's .exe to the bottle's program list via the "Add shortcut" button creates a new document mapping resulting in a virtual directory with only that .exe inside. I have to use Wine's explorer to launch the game by navigating to the .exe location and double clicking it (`T:\...\...\abc.exe`). Maybe it should be possible to select the .exe inside the flatpak document map so that it reuses the previous mapping (in my case the one under `/run/user/1000/doc/19ef51/.../.../abc.exe`).
> EDIT: Or there could be a button titled "Add internal shortcut" that shows a file picker similar to the Wine's explorer such that it works inside the Wine's world... I don't know... Probably needs some conceptual design work.

Does this happen when you are not using the portal? If not, then we can merge this.

**Comment by tesfabpel** [comment]
I haven't tested that since I only have the flatpak version installed, but I believe it only happens inside the flatpak's sandbox since the [documentation](https://docs.gtk.org/gtk4/class.FileChooserNative.html) of GtkFileChooserNative says this:

> When the application is running in a sandboxed environment without direct filesystem access (such as Flatpak), GtkFileChooserNative may call the proper APIs (portals) to let the user choose a file and make it available to the application.

Anyway, it seems that the "Add shortcut" button uses your `FileChooser` class without specifying the `native` argument (which defaults to `True`), so this commit doesn't seem to affect that part of the app. Probably then, it's better to move this new discussion into its own issue...
