### ISSUE TITLE
[Bug]: got on the start as i press play on library and nothing appears

### ISSUE THREAD

**Issue by soulfit15** [bottlesdevs/Bottles#2252]
### Describe the bug

i play hellgate london with bottles and its very good solid performance except that i press play on library and nothing happen

only to launch game through run executable in bottles settings

### To Reproduce

nothhing just as soon as i start bottles

### Package

From source

### Distribution

Arch with LTS

### Troubleshooting Logs

```shell
'NoneType' object has no attribute 'get'  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/wine/executor.py", line 100, in run_program
    if program.get("dxvk") != dxvk:
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Can you share the library.yml file?

**Comment by duarm** [comment]
I'm able to reproduce this by adding a shortcut, adding that shortcut  to my library, and then deleting the shortcut. The game is stuck in the library forever, since we can't remove it from the library window,  deleting the shortcut should also remove the game from the library.
