### ISSUE TITLE
[Bug]: NoneType' object has no attribute 'runners_available'

### ISSUE THREAD

**Issue by kasha695** [bottlesdevs/Bottles#2259]
### Describe the bug

As soon as I launch bottles I get the following error and the app stops:

```
15:22:33 (INFO) Bottles Started! 
15:22:34 (INFO) Catalog components loaded 
15:22:34 (INFO) Catalog installers loaded 
15:22:34 (INFO) Catalog dependencies loaded 
15:22:34 (ERROR) Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x7f4de5b8d360>
	Exception: Expected s to be a str, got <class 'bytes'>
 
  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 205, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 132, in __init__
    self.steam_manager = SteamManager()
  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 59, in __init__
    self.localconfig = self.__get_local_config()
  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 154, in __get_local_config
    data = SteamUtils.parse_acf(f.read().encode('latin-1'))
  File "/usr/share/bottles/bottles/backend/utils/steam.py", line 32, in parse_acf
    return vdf.loads(data)
  File "/usr/share/bottles/bottles/backend/utils/vdf.py", line 207, in loads
    raise TypeError("Expected s to be a str, got %s" % type(s))
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 151, in set_manager
    tmp_runners = [x for x in self.manager.runners_available if not x.startswith('sys-')]
AttributeError: 'NoneType' object has no attribute 'runners_available'
```

### To Reproduce

1. Install Bottles from AUR
2. Launch Bottles

### Package

Other, unofficial package

### Distribution

Arch linux

### Troubleshooting Logs

```shell
App doesn't open to access these options
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by TheEvilSkeleton** [comment]
Can you test Bottles from Flathub and see if it works?

**Comment by kasha695** [comment]
Ive just tested the flathub version and it works there

**Comment by TheEvilSkeleton** [comment]
@mirkobrombin thoughts?

**Comment by mirkobrombin** [comment]
Some weird behavior of the AUR package that I won't be debugging anytime soon.

**Comment by TheEvilSkeleton** [comment]
I think of the same too. I'm closing this issue as we don't support unofficial packages. @kasha695 you can use Bottles on Flathub to not run into this bug.

**Comment by kasha695** [comment]
I have been playing around with this issue and I've replicated it now on the Flathub version now.

If I enable the non-flathub Steam directory override per https://docs.usebottles.com/flatpak/cant-enable-steam-proton-manager and then launch Bottles I get the same error.

**Comment by mirkobrombin** [comment]
I think this bug has been fixed by some commit because I can't replicate it.

**Comment by Kinsteen** [comment]
It seems like Bottles can't decode correctly the localconfig.vdf file of Steam because of some weird characters.

@kasha695, is your system in English? Would you mind sharing this file with me privately (it contains some personal information like friend list)? You can DM me from the Bottles' Discord, I have the same username there
