### ISSUE TITLE
[Bug]: gtk assertions failed in CLI

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2268]
### Describe the bug

Was trying to troubleshoot one of my old bugs that still hasn't been fixed in newest version and I stumbled into some hidden errors when running Bottles from CLI as run flatpak. Don't know if it's anything worth fixing since it doesn't give any errors inside Bottles, but figured I can report it and you can close it if it's nothing worth it.

Weirdly it has 2 kind of errors. One is when you first start Bottles, and the second always happens when you click on any of your created bottles.

first:
(bottles:2): Gtk-CRITICAL **: 14:27:47.775: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed

second and later:
(bottles:2): Gtk-CRITICAL **: 14:28:02.250: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed

### To Reproduce

1. Run Bottles from run flatpak in CLI
2. Observe first error gtk_widget_set_parent
3. Click on any bottle
4. Observe another error gtk_box_append

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356995072
    Free: 8356851712
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "14,4\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Those logs can be safely ignored and are not part of the problem in this context

**Comment by MrQuerter** [comment]
So, the second error was fixed during the version 50. Can't the first one also be tackled?

**Comment by Kinsteen** [comment]
The first one seem to not be able to be fixed, and seems to be an upstream problem.
(I was the one that fixed the other, I also tried to fix this one)
