### ISSUE TITLE
[Bug]: Runner name isn't updated without restarting Bottles

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/Bottles#2271]
### Describe the bug

When you change a runner it doesn't update the name that is seen above the "run executable..." button/pill in the main view. You need to restart Bottles for it to set the new name.

### To Reproduce

1. Change a runner in one of the bottles to another runner
2. Return to main view of your bottle
3. Restart Bottles
4. Go back to the bottle where you changed the runner

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356995072
    Free: 8356851712
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "14,2\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by jntesteves** [comment]
Not only the runner name, but also DXVK and VKD3D are not being applied at all until the app is restarted. I think the settings rework might have broken this. Since 2022.11.14 I need to restart Bottles every time to apply runner changes.
