### ISSUE TITLE
[Bug]: "Launch with Terminal" option behaves differently

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2273]
### Describe the bug

I was trying to see if anything changed with Bottles not running one of my games all of the sudden, but sadly the same things happen. I decided to run Bottles from CLI to see if there is any useful info that I could use, but for me it's not useful. There is a ton of GStreamer-WARNINGS and some GLib errors with missing plugins, but I guess you already have a report for that (I'll post it in more context section though)

However I noticed that there are more programs that behave differently when running normally and when you use "Launch with Terminal" button (not talking about running Bottles in CLI). For example there's the Sacred that I already written about more in programs repo just like I was asked to do. I also found that NFS:U2 runs normally, but when you use "Launch with Terminal" button it asks for inserting the CD Disc. Which is weird because I have a patch that doesn't need the discs.

Also, Pekka Kana 2 has the exact same error I had before when you run it with "Launch with Terminal" button. So it can be some clue as to what happens. You can try it yourself since it's a freeware and installer is just 7MB. More info in issue nr 1045 in this repo.

### To Reproduce

1. Install Pekka Kana 2
2. Restart Bottles
3. Run PK2 to see that it works and close it
4. Run PK2 using "Launch with Terminal" button and wait for the error to appear

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356995072
    Free: 8356851712
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "14,3\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

Here's output from terminal that I talked about:
```
(wine:1276): GStreamer-WARNING **: 15:20:05.985: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsrtp.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsrtp.so: wrong ELF class: ELFCLASS64

(wine:1276): GLib-GObject-WARNING **: 15:20:06.278: type name '-a-png-encoder-pred' contains invalid characters

(wine:1276): GLib-GObject-CRITICAL **: 15:20:06.278: g_type_set_qdata: assertion 'node != NULL' failed

(wine:1276): GLib-GObject-CRITICAL **: 15:20:06.278: g_type_set_qdata: assertion 'node != NULL' failed
winegstreamer error: decodebin0: Your GStreamer installation is missing a plug-in.
winegstreamer error: decodebin0: ../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstBin:bin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)

0128:err:wmvcore:init_stream Failed to connect parser, hr 0x80004005.
wine: Unhandled page fault on read access to 00000024 at address 7014E4A1 (thread 0128), starting debugger...
15:20:29 (INFO) Launching an executable… 
Gtk-Message: 15:20:29.873: Failed to load module "xapp-gtk3-module"

(easyterm.py:1370): VTE-WARNING **: 15:20:29.955: (../src/vtepty.cc:811):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
```

**Comment by Kinsteen** [comment]
For the GStreamer related error, you should install the GStreamer ugly plugins with your package manager. I'm not sure about the Linux Mint repo, but it's under the name `gstreamer1.0-plugins-ugly` on Ubuntu.
This should normally fix the issue with GStreamer, no idea about the other error messages

**Comment by MrQuerter** [comment]
@Kinsteen 
It was already installed in Mint by default I think (but I'll be formatting my PC in December so I'll check it again).
Do I need to somehow enable it or give Bottles access with flatseal? I have no idea what those plugins do.
![2022-11-14_15-49-16](https://user-images.githubusercontent.com/84787215/201690681-9f720acb-a64c-443e-bec1-9577e038e7f8.png)

**Comment by MrQuerter** [comment]
Too bad it didn't make it to this update. Especially with the new longer schedule...

I don't think I can do it. I would need a really detailed guide how to build Bottles with this patch. Never built anything before since there was no need. Maybe if it could quickly make it's way into some little point update or some beta channel it would be quicker.

**Comment by jannuary** [comment]
@MrQuerter The merge request now has CI enabled - you can download, install and test the flatpak package from there.

**Comment by MrQuerter** [comment]
Ok, cloned the repo and executed this change with gh pr checkout. Currently stuck on trying to launch it. But building it with flatpak-builder and info from docs gives "error: org.gnome.Sdk/x86_64/43 not installed"

I'll try it later since I have something to do now. Should I then post it into another issue since technically this one isn't about GStreamer problem?

**Comment by Kinsteen** [comment]
As @jannuary said, you don't have to build it yourself, you can download the build [here](https://github.com/bottlesdevs/Bottles/actions/runs/3460309997).
I think that opening a new issue would be best!
