### ISSUE TITLE
[Bug]: Gstreamer patch testing results

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2276]
### Describe the bug

@Kinsteen
Continuing discussion from https://github.com/bottlesdevs/Bottles/issues/2273

I somehow succeeded in installing this patch since I can see the "Embedded GStreamer" in settings.
Sadly I don't see any change at all when it comes to running the game.
![2022-11-14_19-11-54](https://user-images.githubusercontent.com/84787215/201736455-8528e2fa-0c16-4410-8f51-bf4d64fe177e.png)

On default it was turned on. I then tested the game using play button. Didn't work. Then with the "Launch with Terminal" button. Didn't work. I decided to turn off the "Embeded GStreamer" and test the same things as before. Also didn't work.
Here are the full logs from CLI: 
[gstreamerpatch_testresults.txt](https://github.com/bottlesdevs/Bottles/files/10006004/gstreamerpatch_testresults.txt)

### To Reproduce

1. Read linked topic

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356999168
    Free: 8356855808
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "14,0\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by Kinsteen** [comment]
I just checked, and Wine-GE correctly ships libgstasf.so, which is the plugin you're missing (Advanced Streaming Format). It should function with Wine-GE, and with enabling "Embedded GStreamer", or at least you should have a different error

**Comment by Kinsteen** [comment]
Also, for information, the warnings about "wrong ELF class: ELFCLASS64" are normal: you are using a 64 bits bottle and running a 32 bits program, and GStreamer tries to load the plugins for 64 bits which are not compatible. Those warnings can be safely ignored!

**Comment by MrQuerter** [comment]
Bad news.

The runner I used was Caffe. Caffe 7.20 to be precise, but it happened even on older versions so that doesn't matter.

I downloaded wine-ge-7-34, switched to it and didn't notice any difference. Tested all 4 methods of launching.
Here are the new logs, maybe you can spot something:
[GSp_testing2.txt](https://github.com/bottlesdevs/Bottles/files/10006250/GSp_testing2.txt)

**Comment by Kinsteen** [comment]
Hm, it seems like GStreamer still tries to load your system GStreamer. Normally, the warnings should have the path to your runner, and not to `/usr/lib`.
Does your game crash immediately? If not, it would be great if I could have the environment variables of your launched game. To do so, you need to get the PID of the game, and do `cat /proc/<pid>/environ > env`, and then send me the "env" file.
If it does crash immediately, I don't know a way to have Bottles spit out the complete environment :(

**Comment by MrQuerter** [comment]
Your lucky day. Or maybe not.
I had some problems with doing that because mouse disappeared and I couldn't click on any window, but I placed system monitor and another terminal window on my second screen and it worked.
Here's env file:
[env.txt](https://github.com/bottlesdevs/Bottles/files/10006486/env.txt)
It looks extremely broken, but I'm not an expert in it so maybe it should look like that.

**Comment by Kinsteen** [comment]
Thanks! I see what's going on.
I developed my patch without Flatpak in mind, [which already has a fix for this](https://github.com/bottlesdevs/Bottles/commit/475dec5d3eb3d4212412312c2d6188459b7f07fb) (but buggy maybe?)
Is there a way you could build the branch yourself without Flatpak? I can provide assistance for this, here is my Discord: Kinsteen\<hashtag\>0623

**Comment by MrQuerter** [comment]
I mean, there must be some way, but is there any point in doing so? Bottles only works in flatpak so in the end it needs to work in flatpak.
As for the Discord we would need another way (maybe something throwaway like Kiwi IRC) since I have deleted my Discord account.

**Comment by Kinsteen** [comment]
Bottles definitely works by itself unofficially, for example there is a package in AUR for Arch. I have pushed a fix on my PR for Flatpak, but the CI doesn't run as I'm a first-time contributor.

I have setup the CI on my fork, and you can download the updated version here: https://github.com/Kinsteen/Bottles/actions/runs/3464868296
Try again with this version, and it *should* work!

**Comment by MrQuerter** [comment]
It doesn't. Any logs you're interested in?

**Comment by Kinsteen** [comment]
Yes, can you send the warnings again? And if you can get the environment, I would be grateful :)

**Comment by MrQuerter** [comment]
I don't know if it means anything, but this time the game process was at the bottom of system monitor.
[GSp_test3.txt](https://github.com/bottlesdevs/Bottles/files/10007010/GSp_test3.txt)
[env_2.txt](https://github.com/bottlesdevs/Bottles/files/10007012/env_2.txt)

**Comment by Kinsteen** [comment]
It does help, thanks a lot. It seems that the variable is set somehow by Flatpak before, and that overwriting it in Bottles doesn't change it.

I did a quick patch *again* to override the value, and I would love your feedback (Bottles log + env file again)! Here is the run: https://github.com/Kinsteen/Bottles/actions/runs/3465714523

**Comment by MrQuerter** [comment]
I think there are some new errors now. Something proton related and windows media:
[GSp_test4.txt](https://github.com/bottlesdevs/Bottles/files/10007678/GSp_test4.txt)
[env3.txt](https://github.com/bottlesdevs/Bottles/files/10007679/env3.txt)

**Comment by Kinsteen** [comment]
Ok that's very weird, it's complaining about a plugin missing while I'm pretty sure it's there...
Can you give me the name of the game you're testing with, so I can test by myself?

**Comment by MrQuerter** [comment]
Sure. It's Sacred Gold. To be more precise it's the version from GOG, but they are actually the same everywhere.
However you need to know that overall it got weird in Bottles since some time ago:
https://github.com/bottlesdevs/programs/issues/118
https://github.com/bottlesdevs/Bottles/issues/2047

I have to finish for today so not gonna be able to respond for few hours.

**Comment by Kinsteen** [comment]
Thank you! I'll test by myself and come back here if I find what's wrong. Thanks for helping me test!

**Comment by Kinsteen** [comment]
Okay so update: I have successfully reproduced the bug you had with Flatpak, and I have found a dirty workaround...
The game launches fine if you delete all the files in the `movies` directory.

That means that there is definitely a problem with GStreamer and this specific codec, which should normally not have any problem! If you say that it worked before, there is probably a Wine/GStreamer regression somewhere that would explain the problem, but I can't find anything of the sort.

For further information: with Bottles compiled manually, I don't have any GStreamer warnings, so plugins work fine but the game crashes at launch, with the infamous `Unhandled page fault on read access`. With the video files deleted the game works fine. It's a weird edge-case bug that I think has nothing to do with Bottles.

On the internet, I saw some people having success using `winetricks wmp9`, which would maybe help? But as we're using GStreamer, I'm not sure. There is a dependency called ffdshow in Bottles that is supposed to install the codec in the prefix, but it didn't change anything when I installed it.

**Comment by MrQuerter** [comment]
Well then it was a waste of time. Sorry for that.

I decided to rollback Bottles to two previous versions before it stopped working, but strangely the same error happens. The exact same error happens. Tested with syswine 7.0, caffe 7.20 and wine-ge-7-34. So it really seems like it's not a Bottles bug. It's weird coincidence it appeared exactly with the update.

Versions I checked:
```
dd046f81824a1c4e794f52ef5710ebb31be8f00a687f8d50f9f580528878bd7c
Bump runtime (c804a7ed)
2022-09-23
```
```
497b0cdbc7165972f66a9a43f5972f12b1e983ebae0ba7cc594dc34a54e09bf2
2022.8.28-brescia-2 (67a56551)
2022-08-29
```

To clarify. It really worked flawlessly. You didn't have to install any dependencies. I think intro videos were playing correctly (at the very least you could get to menu without crashing or deleting anything), but now I'm not sure. In-game movies didn't play, but even on windows they were disabled so it's not an issue.

**Comment by Kinsteen** [comment]
No problem! We still got to fix GStreamer not working on Flatpak correctly :)

I'm pretty sure it's a regression on Wine, but I don't think it's beneficial to do research and report upstream. It must be a weird edge case on an old 32 bits game, so... I'm still happy that you're able to play now!

**Comment by MrQuerter** [comment]
If it's a Wine regression shouldn't the older runners work then?
I don't know. Don't have the knowledge to deal with this anymore.

As a last ditch effort I tried running it from Heroic since it has import function and I'm logged there, but the errrors look the same and it certainly crashes the same. I'll try to test it later on clean Mint 21 install without updating any packages. Maybe that's the reason, but it would be pretty funny if the same bug made it both to Arch (you use it right?) and "outdated" Mint.

Closing now as completed, but technically it would need some mix of completed and cantfix.

**Comment by Kinsteen** [comment]
It maybe should work! You didn't say that you tried with older Wine versions, hence my guess.
I do use Arch btw :)

**Comment by MrQuerter** [comment]
I always test older versions of runners since Caffe had some seriously borked releases so I double check before upgrading or reporting.

Anyway, I got too curious of my idea, wasted few GBs of my internet and spent few hours trying to run Bottles in clean Mint 21 install.
I found that Bottles needs way too many flatpak runtimes and that it is in fact not the issue when it comes to this game crashing.

In the end I only had success in installing Mint 21 in Gnome Boxes (flatpak). After way too much time of downloading bottles and the game because for some reason sharing files between guest and host OS is impossible I was able to launch the game. I used a clean Bottles install (the newest 09.28 version), default gaming bottle, soda runner 7.0.7(it is the default one) and didn't change a single bit in the game. Movie folder stayed the same, nothing disabled in cfg file. Straight up everything default. It launched the game without crashing. Movies didn't play so it seems I confused it with the sequel(well prequel to be precise, but doesn't matter) (and here I am 100% certain intro videos in the sequel worked since one of them definitely had them working).

Anyway, as I wrote already sharing files deemed impossible so I only have few screens that I made. Now it's not the full log since it was repeating few times and as usual a ton of GStream warnings.
![2022-11-15_22-19-40](https://user-images.githubusercontent.com/84787215/202030453-a0bee52f-16bc-4eeb-9263-393b014d60f4.png)
![2022-11-15_22-20-08](https://user-images.githubusercontent.com/84787215/202030531-f5f01627-68a4-4ed2-89b0-df461d87672c.png)
![2022-11-15_22-20-52](https://user-images.githubusercontent.com/84787215/202030591-99cd7b9b-be4c-48d3-8e9a-250c3c352b31.png)
![2022-11-15_22-21-11](https://user-images.githubusercontent.com/84787215/202030635-e4492b3d-92b4-41e2-9f94-46f43e6b764d.png)
![2022-11-15_22-22-06](https://user-images.githubusercontent.com/84787215/202030658-af2d4185-480e-4aa1-9756-0c1797c843a3.png)

So. It's not a Wine bug and it's not a Bottles bug. I tested it on clean Mint 21 install. I didn't update even a single package. I did install the multimedia codecs when installing the OS, but I always did that so it's not a problem. Having the results in mind the only logical explanation I can think of is that some Linux package that is present both on Mint and Arch (you did mention that you reproduced the bug) and was updated some time during September.

Now, how to hunt which package is causing this...

**Comment by Kinsteen** [comment]
That's very interesting, and very weird... GStreamer still can't load videos, but it doesn't crash the game, while on our system it crashes (probably) because of videos. Wine and GStreamer are updated... I have no clue what is interfering with videos except those two.

**Comment by Kinsteen** [comment]
A difference that I see it that on your VM there's the mesa Vulkan driver missing, as I'm assuming you're using an emulated GPU in the VM. This problem could be a driver regression, but that would be weird as we have the same error and I'm on NVIDIA and you're on AMD.

**Comment by Qronikarz** [comment]
Just wanted to add that in Bottles 51.11 and Mint 21.3 I don't have to rename videos folder and the videos play without issue (it shows program as not responding, but you can click wait and it works)

Terminal still shows a ton of warnings like these ones though:
```(wine:1328): GStreamer-WARNING **: 15:17:43.957: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsubparse.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsubparse.so: wrong ELF class: ELFCLASS64```
