### ISSUE TITLE
[Bug]: Infinite "Almost done..." on Steam Deck

### ISSUE THREAD

**Issue by ootqa** [bottlesdevs/Bottles#2278]
### Describe the bug

Installed Bottles on my Steam Deck, did both through Discover and Konsole, and always have the same issue where _"Almost Done We need a few more minutes.."_ Actually takes forever and never finishes. I have a very slow download speed in both Discover and Konsole, but I've managed to install/update/run every other app except of Bottles and Lutris (both get stuck at the very beginning). I'm quite sure that problem and download speed has to do with my Chinese internet. 

What I've tried:
1. Waiting for about 3-4 hours
2. Changing DNS
3. Disabling IPv6 (I've seen this helped someone with Lutris problem)
4. Reinstalling Bottles
5. Re-imaging SteamOS
6. Both Wi-Fi & Ethernet

EDIT: I just remembered that I didn’t manage to install another app in Konsole when the guide required me to use _git clone https://github.com/XXXXXXXX_ 
But then I’ve found a Chinese guide for the same app that suggested to use git clone _https://ghproxy.com/github.com/XXXXXXXX_ instead and it worked! Maybe the issue is, that both Lutris and Bottles are trying to connect with GitHub and I could somehow implement that _ghproxy.com_ to make it work? 

Even if I'm quite sure that the problem is on my side, I still hope I can find some workaround/help here. 

### To Reproduce

1. Install Bottles
2. Run

### Package

Flatpak from Flathub

### Distribution

SteamOS 

### Troubleshooting Logs

```shell
Have no option to press anything since the "Almost Down" window is on top.
```

### Display Protocol

X11

**Comment by 256shadesofgrey** [comment]
I have the same issue on Manjaro after installing Bottles through AUR.

**Comment by FNklazo** [comment]
Having the same issue as well on Arch KDE. I installed Bottles through the AUR.

**Comment by shykeiichi** [comment]
The AUR Package is not supported by the Bottles Team and does not work. Use the flatpak package.

**Comment by lightcrater** [comment]
i also have this issue, it seems that there is an issue when trying to download some kind of runtime

10:34:05 (WARNING) No runtime found. 
10:34:06 (INFO) Installing component: [runtime-0.5]. 
10:34:06 (WARNING) File [runtime.tar.gz] already exists in temp, skipping. 
10:34:06 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
10:34:06 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [dc9d0f1cff9f3df062bfb917be57a017] 
10:34:06 (ERROR) Removing corrupted file [runtime.tar.gz]. 
10:34:06 (ERROR) Extraction failed! Archive ends earlier than expected. 
10:34:06 (WARNING) No runtime found.

**Comment by SuperSamus** [comment]
It seems that https://repo.usebottles.com/components/runtimes/ hasn't been updated by the commit https://github.com/bottlesdevs/components/commit/7722ae85b48330016585da7a5a18176d9671fa60.

**Comment by bymkod** [comment]
I'm sorry I don't speak English. This post was written via google translator.
Сreate a file .local/share/bottles/runtimes/runtime-0.5.yml and put this in it

    Name: runtime-0.5
    Provider: bottles
    Channel: stable
    File:
    - file_name: runtime.tar.gz
      url: https://github.com/bottlesdevs/runtime/releases/download/0.5/runtim>
      file_checksum: 1747a350e92bd1e82d4d4e8ae617deeb
      rename: runtime.tar.gz

**Comment by abcRede** [comment]
That worked, @bymkod. 
Thanks.

**Comment by mirkobrombin** [comment]
Fixed at repository level, will be distributed soon.

**Comment by jonathanfelicity** [comment]
> I'm sorry I don't speak English. This post was written via google translator. Сreate a file .local/share/bottles/runtimes/runtime-0.5.yml and put this in it
> 
> ```
> Name: runtime-0.5
> Provider: bottles
> Channel: stable
> File:
> - file_name: runtime.tar.gz
>   url: https://github.com/bottlesdevs/runtime/releases/download/0.5/runtim>
>   file_checksum: 1747a350e92bd1e82d4d4e8ae617deeb
>   rename: runtime.tar.gz
> ```

Worked for me thanks
