### ISSUE TITLE
[Bug]: popup window not picking up theme?

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2280]
### Describe the bug

The popup window from the bottles launch options popup window isnt following the theme, the font is black

![image](https://user-images.githubusercontent.com/26150581/201825083-06c84b6b-e396-4092-a425-cdce608d165b.png)

I'm using picom as my compositor. maybe related to https://github.com/bottlesdevs/Bottles/issues/2207

### To Reproduce

Not sure

### Package

From source

### Distribution

Artix

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.7-zen1-1-zen
Distro:
    Name: Artix Linux
    Version: Unknown
Disk:
    Total: 52521566208
    Free: 16029667328
RAM:
    MemTotal: "16.7\_GB"
    MemAvailable: "12.8\_GB"
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by jannuary** [comment]
We don't supoort alternative themes, and as far as I'm concerned, it isn't replicatable on Adwaita.
