### ISSUE TITLE
Outdated translations on Weblate

### ISSUE THREAD

**Issue by flipflop97** [bottlesdevs/Bottles#2281]
The translation strings on Weblate are quite outdated. The new release contains a lot of strings that are missing and therefore can't be (and aren't) translated.

**Comment by flipflop97** [comment]
@mirkobrombin  
Not sure if you noticed yet, but Weblate now has a merge conflict that needs to be fixed in order for the translations to continue. I'm not able to re-open this issue apparently, but it's not been completely fixed unfortunately.

**Comment by mirkobrombin** [comment]
Fixed
