### ISSUE TITLE
There was an error

### ISSUE THREAD

**Issue by aidmod** [bottlesdevs/Bottles#2288]
not all arguments converted during string formatting  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1345, in create_bottle
    log_update(_("Installing dependency: %s …") % _dep.get("Description", "n/a"))

**Comment by mirkobrombin** [comment]
Hi, please follow the issue layout
