### ISSUE TITLE
[Request]: Option to install all windows dependencies

### ISSUE THREAD

**Issue by Radical4ever** [bottlesdevs/Bottles#2299]
### Tell us the problem or your need

i have to click on all download and install dependencies one by one for getting them all (for photoshop normally)

### Describe the solution you'd like

put a checkbox or option to install all dependencies.

### Other solutions?

maybe using a chooser or a dialog when you can choose wich dependencies you want to install (like a checkbox)

**Comment by mirkobrombin** [comment]
Hi, please read here https://usebottles.com/blog/release-2022.9.28/#multiple-dependencies-installation-deprecation
