### ISSUE TITLE
[Request]: Restore side menu 

### ISSUE THREAD

**Issue by cobk4011** [bottlesdevs/Bottles#2311]
### Tell us the problem or your need

Since the last update, every time I need to switch submenus, I now have to navigate from one end of the window to the other over and over again. The workflow is much worse. 

### Describe the solution you'd like

Restore the side menu or add settings to show it.

**Comment by TheEvilSkeleton** [comment]
There were a couple of duplicated sections in Bottles, which caused confusion among users. There aren't enough tabs for the need of a sidebar. The new layout is much better organized and are laid out correctly. As such, we don't plan to restore the side menu. Sorry.
