### ISSUE TITLE
[Bug]: Bottles stuck on Starting up

### ISSUE THREAD

**Issue by MasterKia** [bottlesdevs/Bottles#2317]
### Describe the bug

When opened after first installation, using the GUI or even from the terminal, the app is stuck on "Starting up".

### To Reproduce

1. Install Bottles from Flathub
2. Open it
3. It gets stuck on "Starting up"

### Package

Flatpak from Flathub

### Distribution

Fedora 36 KDE

### Troubleshooting Logs

```shell
Can't access
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
Related https://github.com/bottlesdevs/Bottles/issues/2057
