### ISSUE TITLE
How to remove programs from library?

### ISSUE THREAD

**Issue by MandiYang** [bottlesdevs/Bottles#2326]
`!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!`
Just a dumb question but I don't find any buttons that removes programs from the library, I tried to remove the program from the bottle shortcut so that the programs also removes from the library but it doesn't work

**Comment by mirkobrombin** [comment]
Look for the 3 dots button in the top left corner of the card

**Comment by MandiYang** [comment]
AAAh, thx it was just the remove button wasn't that visible.
![Screenshot from 2022-11-26 18-36-04](https://user-images.githubusercontent.com/64307609/204101740-a7a8f6cf-dc17-4226-b012-83c06de7a5d5.png)
