### ISSUE TITLE
Trying to create bottle using gaming template hangs

### ISSUE THREAD

**Issue by luimu64** [bottlesdevs/Bottles#2328]
While trying to create bottle with "gaming" template the process never progresses further from "Template found, applying…" while simultaneously filling the whole disk with bogus nested folders.
![image](https://user-images.githubusercontent.com/54173370/204093564-4009cdc7-22ae-48cf-8e33-7b415e22a91d.png)
![image](https://user-images.githubusercontent.com/54173370/204093579-99e96002-a567-4f00-81e9-742fd28f434c.png)
![image](https://user-images.githubusercontent.com/54173370/204093592-9f1e02d8-b93d-4198-b079-f6b5b3e69b84.png)

**Comment by mirkobrombin** [comment]
Hi, please follow the [bug report template](https://github.com/bottlesdevs/Bottles/issues/new?assignees=mirkobrombin&labels=bug%2Ctriage&template=bug.yml&title=%5BBug%5D%3A+).
