### ISSUE TITLE
Where is the "Utilities" ->"Browse" function button of the latest version?

### ISSUE THREAD

**Issue by daxiwow** [bottlesdevs/Bottles#2329]
!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!
Where is the "Utilities" ->"Browse" function button of the latest version?

**Comment by mirkobrombin** [comment]
Browse files is now placed in the headerbar: ![image](https://user-images.githubusercontent.com/9479903/204098038-a591c280-0b77-48b5-b9a0-e8b1027b44cb.png)
