### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mup0** [bottlesdevs/Bottles#2336]
### Describe the bug

I went to launch and I think this happened before but I did not see the traceback til now. Attempting to launch Bottles from my Application launcher.  

### To Reproduce

Clicked Application Launcher
Type Bottles
Press Enter
Launched with the Bottles Crash Report.  I do not seem to be able to launch my Bottles until I send this off.  

### Package

Flatpak from Flathub

### Distribution

Fedora 36 KDE

### Troubleshooting Logs

```shell
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 26, in send_status
    if status == 0 and not WineServer(self.config).is_alive():

  File "/app/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
    return f(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
    if not config.get("Runner"):
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Attempting to launch Ubisoft Connect while the Crash Report is up gives me a 'Mad Linux Noise'.  Just last night I was able to run ESOx64.exe for my daily login, today I am unsure if anything changed.  I did not update since then, didn't intend to run any updaters [dnf --refresh update, flatpak update, snap refresh] til tomorrow.

**Comment by mirkobrombin** [comment]
Related https://github.com/bottlesdevs/Bottles/issues/2307
