### ISSUE TITLE
[BUG] Wrong dates for releases

### ISSUE THREAD

**Issue by leeford** [bottlesdevs/Bottles#234]
**Describe the bug**
Wrong date against versions, which may lead to users believing they have an older build than it actually is.

3.1.5 has been marked as released on 2020-04-20, when it is actually **2021**-04-20

This is being brought up from `com.usebottles.bottles.appdata.xml.in` being incorrect.

Are you happy for me to do a PR and I will attach this issue to it?

**Installation**
 - Method: Flatpak
 - Version: 3.1.5

**To Reproduce**
Look at releases

**Expected behavior**
The dates for all the 3.x releases should be 2021, not 2020.

**Screenshots**
![image](https://user-images.githubusercontent.com/472320/115688991-90176f00-a353-11eb-9d70-020513c64724.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Comment by mirkobrombin** [comment]
This is embarassing

**Comment by leeford** [comment]
Hey, at least it is an easy fix, right :-)

**Comment by mirkobrombin** [comment]
Fortunately, it is an easy fix. If you want to do the PR thank you very much!
