### ISSUE TITLE
[Bug]: Error when installing DXVK in bottle

### ISSUE THREAD

**Issue by shykeiichi** [bottlesdevs/Bottles#2348]
### Describe the bug

When creating a bottle of any variety the error "There was an error creating the bottle" appears as seen in the error message provided below.

### To Reproduce

1. Open bottles
2. Click the plus
3. Give a name
4. Select gaming
5. Press create

### Package

Flatpak from Flathub Beta

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.11-arch1-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8023773184
    Free: 8023633920
RAM:
    MemTotal: "16.0\_GB"
    MemAvailable: "12.3\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

![image](https://user-images.githubusercontent.com/60363370/205881546-70ccb85e-eb1a-486d-9fc5-03210a91c814.png)

**Comment by mirkobrombin** [comment]
Flathub beta is not updated since months now.
