### ISSUE TITLE
[Request]: Multiple locations for bottles to reside

### ISSUE THREAD

**Issue by VashStampedeTRI14** [bottlesdevs/Bottles#2359]
### Tell us the problem or your need

I have several disks in my computer that I would like to extend the use of by having bottles stored across various disk drives. Currently it looks like you can only have one default location in the preferences. Thanks for your time and consideration!

### Describe the solution you'd like

Instead of having just a default location for all bottles would it be possible to choose where to save an individual bottle? 

### Other solutions?

Possibly even an option to migrate the bottle to another disk would be very useful.

**Comment by mirkobrombin** [comment]
You can choose a custom path for every bottle during creation. Choose the Custom environment, pick the path, choose another env then save
