### ISSUE TITLE
[Request]: Tooltips for missing vkBasalt and GameScope

### ISSUE THREAD

**Issue by Eonfge** [bottlesdevs/Bottles#2360]
### Tell us the problem or your need

Nothing in this window tells the user, what to do about the greyed out vkBasalt option:

![Screenshot from 2022-12-12 20-54-58](https://user-images.githubusercontent.com/33983090/207141524-d1cf6862-c76b-46f3-b672-55b5297e1193.png)

### Describe the solution you'd like

If a user were to click on it, it might be best to forward the user to a support article, or to give a tooltip about installing the corresponding component.

Right now, a user can only install those extensions using the Terminal, but it would still be better then showing greyed out options without any indication why.

### Other solutions?

RTFM. I only realised that this was a problem by googling it and finding this issue: https://github.com/bottlesdevs/Bottles/issues/1723 judging by the comments on that issue, this is not the first time that people don't understand the UI.

### Additional context and references

It's a bit of a UX problem to give users a 'dead end'. It's better to forward them to an explanation and a possible fix, or to hide the option entirely until they install the right package.

**Comment by TheEvilSkeleton** [comment]
I agree. Honestly, We've been wanting to have vkBasalt and Gamescope installed automatically so the user won't have to install manually, per https://github.com/bottlesdevs/Bottles/issues/2008.

I guess, for the time being, we should use tooltips.
