### ISSUE TITLE
[Request]: Request for a snap package

### ISSUE THREAD

**Issue by ghost** [bottlesdevs/Bottles#2364]
### Tell us the problem or your need

Would you please consider packaging bottles as snap. Some times one needs certain software which is only available on Windows and most work environments have Ubuntu where snap is pre installed. Also snaps takes less space and are easier to package.

### Describe the solution you'd like

If you can allow it, then I could package it as snap in your behalf.

**Comment by TheEvilSkeleton** [comment]
We do not plan to support formats other than Flatpak, as Flatpak covers most use cases and a lot more people prefer Flatpak over Snap. You are still free to package it, but we won't support it. Sorry.
