### ISSUE TITLE
[Bug]: Multiple bwrap instance created when not wanted in flatpak

### ISSUE THREAD

**Issue by RushingAlien** [bottlesdevs/Bottles#2372]
### Describe the bug

As the title suggest, there are cases where bottles opens something in a different bwrap container. This causes the exe launched in the other bwrap sandbox to fail to run, since the wineserver of the wineprefix is already running in another bwrap instance.
This is a boon since one of the appeal of bottles is to have the same prefix to have multiple apps.

### To Reproduce

1. Open Bottles
2. Open a bottle with multiple app (app 1 and app 2)
3. run app 1 via bottles
4. run app 2 via desktop entry (observe for a second that app 2 is in a different bwrap instance)
5. see ass app 2 does not launch

another case would be
1. Run app 1 via desktop entry
2. open bottles (observe that app 1 runs in a different bwrap instance than bottles)
3. run app 2 of the same bottle/prefix
4. See as app 2 does not launch

another one
1. run bottles
2. open a bottle with multiple apps
3. run app 1
4. close bottles while leaving app running
6. open bottles again (now bottles will be in a different bwrap instance)
7. try to run app 2 which has the same prefix as app 1

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-zen1-1-zen
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 5187645440
    Free: 5187489792
RAM:
    MemTotal: 9.7GiB
    MemAvailable: 5.1GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by RushingAlien** [comment]
UPDATE :
The issue was cause by fsync
for cross sandbox wineserver communication, fsync needs access to shm
allowing shm to the flatpak seems to fix the issue

**Comment by mirkobrombin** [comment]
Thanks for reporting. This is not really a bug in our hands and we can’t do anything about

**Comment by RushingAlien** [comment]
that makes sense, but would you be open to having `allow=per-app-dev-shm` in the flatpak manifest bwrap instances can share the same wineserver? This wouldn't solve the multiple bwrap instance part, but at least the effect of it breaking launching of programs can be fixed.

**Comment by mirkobrombin** [comment]
I think it's doable without cons
