### ISSUE TITLE
[Bug]: EA App - Disk space required

### ISSUE THREAD

**Issue by Zukureneno** [bottlesdevs/Bottles#2378]
### Describe the bug

When trying to download anything outside of the main drive (/mnt) it gives a warning that there's not enough disk space.
Same apply if your trying to find an existing installation. (this doesn't happen on Origin App).

![image](https://user-images.githubusercontent.com/60487234/208077050-31248778-e005-4e64-82c4-ae43ce425976.png)

![image](https://user-images.githubusercontent.com/60487234/208077496-93c1af74-0598-4630-bb8c-530c6be92b64.png)

![image](https://user-images.githubusercontent.com/60487234/208077615-573bfd93-03be-481e-8cdc-adc873b8441a.png)

![image](https://user-images.githubusercontent.com/60487234/208077736-6c463988-c1a4-4cf7-9b34-656e2a857d2d.png)

### To Reproduce

1. Launch EA App
2. My Library
3. Select game
4. Install
5. Change Install Location
6. Select Directory within /mnt

### Package

Flatpak from Flathub

### Distribution

Nobara 36 - Official 

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.10-201.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16783728640
    Free: 16783568896
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 17.4GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

This only happens on Flatpaks (I tried on Lutris RPM and this doesn't happen)

**Comment by mirkobrombin** [comment]
duplicate https://github.com/bottlesdevs/programs/issues/75

**Comment by Libroru** [comment]
> > duplicate [bottlesdevs/programs#75](https://github.com/bottlesdevs/programs/issues/75)
> 
> I don't think so. The issue linked is about EA Client being not usable (access to the library). This is about reporting the wrong disk space.
> 
> From [this forum](https://askubuntu.com/questions/1058430/how-to-give-wine-prefix-more-space), it seems that this is a problem with Wine not properly reporting disk space. And I can confirm that changing the Windows version (Some Bottle > Settings > Compatibility > ...), fixes the issue. I tested with Windows 7, btw.

Having the exact same issue right now with Ubisoft Connect.

What Windows version did you end up using?
