### ISSUE TITLE
[Bug]: 32 bit dependiencies/installers unavailable

### ISSUE THREAD

**Issue by arazadaz** [bottlesdevs/Bottles#2384]
### Describe the bug

Upon one of the previous updates to bottles, all 32 bit bottles show an empty tab for dependency installers or program installers. 64 bit bottles still work perfectly fine, but 32 bit bottles do not. 

### To Reproduce

1. Create a 32 bit bottle
2. go to the dependencies tab or program installers tab. Both show an empty tab. 

### Package

Flatpak from Flathub

### Distribution

Manjaro

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.15.78-1-MANJARO
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16687292416
    Free: 16687128576
RAM:
    MemTotal: 31.1GiB
    MemAvailable: 21.6GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
This is not a bug, [our dependencies are tested/compatible with Win64 bottles only](https://github.com/search?q=repo%3Abottlesdevs%2Fdependencies+win32&type=code).

I do not exclude that one o more of our dependencies works on a Win32 bottle but this require testing. If you want to help us doing so, [host your local repository](https://maintainers.usebottles.com ) then add `Arch: win32` to the dependency you want to test.
