### ISSUE TITLE
[Bug]: Cannot create new bottle

### ISSUE THREAD

**Issue by tonysilva16** [bottlesdevs/Bottles#2387]
### Describe the bug

Hello,

When creating a new bottles (gaming), it throws an error after installing DXVK.

```
Error while running async job: <bound method Manager.create_bottle of <bottles.backend.managers.manager.Manager object at 0x7feff9311390>>
	Exception: not all arguments converted during string formatting
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1277, in create_bottle
    log_update(_("Installing dependency: %s …") % _dep.get("Description", "n/a"))

```

### To Reproduce

1. Create a new bottle
2. Choose a gaming env
3. Click to create bottle and check of the error after installing dxvk.

### Package

Flatpak from Flathub

### Distribution

Fedora 37

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.0.12-300.fc37.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8314830848
    Free: 8314662912
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.3GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by vicevi** [comment]
same problem dude, tried to install `wine-dxvk`, installed but problem remains the same

**Comment by StoneMoe** [comment]
@mirkobrombin this may be related to outdated translation resource
https://github.com/bottlesdevs/Bottles/blob/b7ed61e6788143052dbefef722531bca370e729c/po/nb_NO.po#L123-L128
to resolve this issue, here is my advice:
1. Add strictly auto code linting or code style guide for string formatting, only use one type format string in whole codebase, and forbidding devs to change them
2. include user language setting in Bottles' debugging information, so we can determine which language is outdated when user reporting errors
3. Add unit test for translation resource and remove invalid formatting strings automatically

**Comment by 2ndBillGates** [comment]
I also have the issue. Fedora 37 (6.1.6-1.surface.fc37.x86_64) 
I installed bottles from DNF

**Comment by 2ndBillGates** [comment]
Here's my debug output 
```
12:15:51 (INFO) Applying environment: [gaming]… 
12:15:53 (INFO) Installing DXVK… 
12:15:53 (ERROR) Error while running async job: <bound method Manager.create_bottle of <bottles.backend.managers.manager.Manager object at 0x7fc37f973750>>
        Exception: list indices must be integers or slices, not str
 
  File "/usr/share/bottles/bottles/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1256, in create_bottle
    self.install_dll_component(config, "dxvk", version=dxvk_name)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1446, in install_dll_component
    manager = DXVKComponent(_version)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 38, in __init__
    self.check()
  File "/usr/share/bottles/bottles/backend/dlls/dll.py", line 55, in check
    del found[path][dll]
        ~~~~~~~~~~~^^^^^

```

**Comment by StoneMoe** [comment]
> Here's my debug output
> 
> ```
> 12:15:51 (INFO) Applying environment: [gaming]… 
> 12:15:53 (INFO) Installing DXVK… 
> 12:15:53 (ERROR) Error while running async job: <bound method Manager.create_bottle of <bottles.backend.managers.manager.Manager object at 0x7fc37f973750>>
>         Exception: list indices must be integers or slices, not str
>  

Seems like you ran into different situation, please open a new issue for it, thanks!
