### ISSUE TITLE
[Bug]: vmtouch breaks "launch with terminal" option

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2390]
### Describe the bug

I was retrying my old bug reports and I noticed that vmtouch is broken even when there are no spaces in the path. Without it Notepad++ launches normally, but turning it on makes the "launch with terminal" button launch an empty EasyTerm window and nothing else happens.
Might be related to issue nr 1966, but I'm not sure.

### To Reproduce

1. Install notepad++
2. Launch notepad++ with terminal button
3. Enable "Preload game files" option in settings 
4. Try to launch notepad++ with terminal button

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21 Cinnamon

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-56-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.6GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

Here's stuff that shows when you run Bottles from terminal:
```
23:19:03 (INFO) Library saved 
23:19:05 (INFO) Setting Key vmtouch=True for bottle notepad plus plus… 

(bottles:2): Gtk-CRITICAL **: 23:19:05.940: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
23:19:08 (INFO) Launching an executable… 
23:19:08 (WARNING) Windows path detected. Avoiding validation. 
23:19:08 (INFO) Using Wine Starter -- run 
Gtk-Message: 23:19:08.662: Failed to load module "xapp-gtk3-module"

(easyterm.py:111): VTE-WARNING **: 23:19:08.744: (../src/vtepty.cc:811):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
```

**Comment by orowith2os** [comment]
Can confirm that this is an issue for me as well, just enable vmtouch and launch an application using the terminal.
