### ISSUE TITLE
[Bug]: cant launch shourtcuts made from bottles (Bottles  -- %u not found)

### ISSUE THREAD

**Issue by XDM-Inc** [bottlesdevs/Bottles#2397]
### Describe the bug

when trying to launch a desktop  shortcut that was made from bottles app clicking on it does not launch anything. When i open the .desktop file and try to put the command its trying to do in the terminal it outputs "Bottles  -- %u not found" tested on 2  different  computers both different arch linux distros, one endeavor OS and the other manjaro (both KDE DE) 
i am using the AUR

### To Reproduce

1.make application shortcut in bottles
2.add desktop entry
3.try to launch that shortcut (fails)
4. try to launch with cli (gets Bottles  -- %u not found)

### Package

Flatpak from GitHub Artifacts

### Distribution

Arch linux

### Troubleshooting Logs

```shell
Debugging Information option missing.
```

### Additional context

i am using the AUR arch download at version "bottles 2022.12.14-1"

**Comment by StoneMoe** [comment]
it's a known issue and had been fixed in https://github.com/bottlesdevs/Bottles/pull/2371, but not release so far.

**Comment by XDM-Inc** [comment]
> it's a known issue and had been fixed in #2371, but not release so far.

ah ok, so im assuming in an upcoming release?

**Comment by StoneMoe** [comment]
> so im assuming in an upcoming release?

Yeah I think so. I'm waiting for release too.

**Comment by XDM-Inc** [comment]
> > so im assuming in an upcoming release?
> 
> Yeah I think so. I'm waiting for release too.

think that will also fix the issue of not being able to launch exe's directly on click? i assume so as i think its the same issue (the app not filling in a wildcard call info)

**Comment by StoneMoe** [comment]
> > > so im assuming in an upcoming release?
> > 
> > 
> > Yeah I think so. I'm waiting for release too.
> 
> think that will also fix the issue of not being able to launch exe's directly on click? i assume so as i think its the same issue (the app not filling in a wildcard call info)

Yes. this error message you got from cli is the reason that you cannot launch windows app with a shortcut click

**Comment by mirkobrombin** [comment]
fixed by #2371
