### ISSUE TITLE
Manifest CDN is down

### ISSUE THREAD

**Issue by StoneMoe** [bottlesdevs/Bottles#2398]
`https://proxy.usebottles.com/repo` redirects me to `https://bottles.mirror.garr.it/repo`, which is down.

What's the reason to use a self-host manifest server if we still need to download the files from GitHub?
Why not just use GitHub for manifest too?
A service backed by Microsoft should be way better than FOSS self-host from my experience

**Comment by mirkobrombin** [comment]
Does not result down and the purpose is "mirrors". About the resources, we are planning to move all of them.

**Comment by StoneMoe** [comment]
Still cannot connect to the mirror, anyway glad to hear that server works for you :)
