### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by carrotfarmer** [bottlesdevs/Bottles#240]
**Describe the bug**
When I try to run Bottles, it errors out with this message:
```py
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Installation**
 - Method: [Arch User Repository - bottles-git](https://aur.archlinux.org/packages/bottles-git/)

**To Reproduce**
1. Install the `bottles-git` repository from the AUR using any AUR helper or directly using `makepkg`
2. Run the `bottles` command in the terminal
3. See error: `ModuleNotFoundError: No module named 'gi'`

**Expected behavior**
The Bottles GUI launches without any crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/66675022/115957544-b63e3a00-a520-11eb-89cf-a8bb02c326ff.png)

**Desktop**
 - OS: Arch Linux
 - Kernel Version:  `5.11.15-arch1-2`
 - Desktop Environment: GNOME 40

**Additional context**
This seems to be an error related to python but when I tried a `pip3 install gi`, pip returned this error:
![image](https://user-images.githubusercontent.com/66675022/115957736-c60a4e00-a521-11eb-8f03-027ce688b2b9.png)

**Comment by mirkobrombin** [comment]
Does it work if you install the python-gobject package?

**Comment by carrotfarmer** [comment]
![image](https://user-images.githubusercontent.com/66675022/115957882-9dcf1f00-a522-11eb-8d5f-28b618c8aa9d.png)
`pip` does not seem to find any such package...

**Comment by carrotfarmer** [comment]
No, I already have `python-gobject` but I tried updating it anyway using this command:
```fish
sudo pacman -S python-gobject
```
and the same error occurs
![image](https://user-images.githubusercontent.com/66675022/115957987-fb636b80-a522-11eb-9e1b-c289b2fe5ca1.png)

**Comment by mirkobrombin** [comment]
I don't have Arch Linux on my PC, if the package is there I see no reason why it shouldn't works. 
Try installing PyGObject from pip:
`pip install PyGObject`

**Comment by carrotfarmer** [comment]
It actually worked after installing `PyGObject`, thanks a lot!
