### ISSUE TITLE
[Bug]: fallout 4 in bottles background audio stop working after newest update(2022.12.14-1)

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#2413]
### Describe the bug

After the update yesterday fallout 4 in bottles menu music and background music in game disappeared. For this I test on my backup linux mint machine as well and test before update and after. Yes, after update it failed. I know protondb said that fallout 4 used to have audio issue last year but solved by new proton 7.0 release early this year, and I have no issue playing it for 2 months until yesterday.

### To Reproduce

1. prepare a fallout 4 full game directory
2. open it

### Package

Flatpak from Flathub

### Distribution

Manjaro kde, linux mint 21

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-56-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8361644032
    Free: 8361484288
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.3GiB
Bottles_envs: null
```

**Comment by Kinsteen** [comment]
Is there any logs in Bottles when you launch the game?

**Comment by csc-chicken** [comment]
Oh!! I just tested on **lutris** in main machine Manjaro and it also no audio now. So, it's more a driver update issue i guess???(proton  version is the same before so no issue) So maybe I can close the issue??

**Comment by jannuary** [comment]
It wouldn't be in this repo either way.

**Comment by csc-chicken** [comment]
@Kinsteen @jannuary thanks for your time and help!! Just cross testing that whether is bottle specific problem

**Comment by csc-chicken** [comment]
Oh my god! After some investigation it turns out that it is really bottle's problem. After bottles update(2022.12.14-1) the audio dependency required for fallout 4  **faudio** become external one and need to be downloaded manually unlike previous version. After installed manually it works again. Anyway, @Kinsteen thank you. I saw an interview of bottle devs before that bottles wants to implement an auto external dependencies detection and installation. Hope in near future this can become public and make our lives easier and better.
![圖片](https://user-images.githubusercontent.com/66060998/208956303-5360618a-8f41-4b84-b1ff-950a5d0580aa.png)

**Comment by Kinsteen** [comment]
Happy for you that you solved your problem!

**Comment by csc-chicken** [comment]
I Tested between new version and 11.14 version and with fallout 3 as well. Then fallout 3 #2023 old issue reappeared in new version(same log as well). Maybe some update influence gstreamer settings I think. Only bethesda games are influenced. Bethesda, Bethesda never changes.

**Comment by Kinsteen** [comment]
There is a bug currently regarding GStreamer, there's a new environment variable that should fix it temporarily, while the fix is to be released next month:  `BOTTLES_USE_SYSTEM_GSTREAMER`

**Comment by csc-chicken** [comment]
Oh! No wonder. Thanks for your dedication!! Looking forward to seeing more quality app in the future.
