### ISSUE TITLE
[Bug]: Bottles stuck/broken on Starting Up

### ISSUE THREAD

**Issue by Sabering1** [bottlesdevs/Bottles#2416]
### Describe the bug

After installing bottles software from flathub bottles is stuck on Starting Up... 3/3 screen
I have a gigabit internet so thats not a problem, i tried to remove the network access but it still wont work

### To Reproduce

Start bottles

### Package

Flatpak from Flathub

### Distribution

Fedora 37

### Troubleshooting Logs

```shell
As bottles wont start there is no way to provide this data, but im on the latest Fedora 37 Kernel/Update using Wayland with an AMD CPU/GPU system
```

**Comment by Kinsteen** [comment]
Hi, can you start Bottles from the command line with `flatpak run com.usebottles.bottles` and send here the logs please?

**Comment by Sabering1** [comment]
-------------------------------------

7:36:27 (INFO) Bottles Started! 
17:36:31 (INFO) Catalog components loaded 
17:36:31 (INFO) Catalog installers loaded 
17:36:32 (INFO) Catalog dependencies loaded 
17:36:32 (INFO) Performing Bottles checks… 
17:36:32 (INFO) Dxvks found:
	 - dxvk-2.0
 
17:36:32 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.7
 
17:36:32 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
17:36:32 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
17:36:32 (INFO) Runners found:
	 - sys-wine-7.0.1
	 - soda-7.0-7
	 - GE-Proton7-39
 
17:36:32 (INFO) Bottles found:
	 - Video Games
	 - Aplikacije
 

(bottles:2): Gtk-CRITICAL **: 17:36:32.942: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
17:36:33 (INFO) Library saved 
17:36:33 (ERROR) Grid not found: /home/sabering/.var/app/com.usebottles.bottles/data/bottles/bottles/Video-Games/grids/4416b34d-6d8a-4983-b6fe-02d0242d8fb3.png 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 155, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/frontend/views/library.py", line 43, in __init__
    self.update()
  File "/app/share/bottles/bottles/frontend/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/frontend/widgets/library.py", line 77, in __init__
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(path, 240, 360)
TypeError: Argument 0 does not allow None as a value

--------------------------

**Comment by Kinsteen** [comment]
It seems like an image from the library has been deleted. You can try to delete the file `$HOME/.var/app/com.usebottles.bottles/data/bottles/library.yml`, and Bottles will start. It will however delete your library, but you can add back the programs that were there!

**Comment by Sabering1** [comment]
Oh yea that seems to work kinda stupid that a missing png borkes everything, i hope that devs fix this soon, Also thanks for your help Kinsteen your a real one!
