### ISSUE TITLE
Adding New Font to Dependencies?

### ISSUE THREAD

**Issue by rjrich** [bottlesdevs/Bottles#2429]
Is it possible to add a new font to the Dependencies in Bottles?
For example, I have my TTF files for the Segoe UI font, and I would like to add these to a Bottle. Thank you.

**Comment by StoneMoe** [comment]
1. Copy your font file to ``
2. Registering them in `HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Fonts`
3. [Optional] Replace fonts in `HKEY_CURRENT_USER\\Software\\Wine\\Fonts\\Replacements`

**Comment by mirkobrombin** [comment]
Or you can make your custom dependencies: https://maintainers.usebottles.com/

**Comment by shakib04** [comment]
![Screenshot from 2023-06-18 22-22-01](https://github.com/bottlesdevs/Bottles/assets/51458806/5dac8445-79d9-4f51-bd1d-84c82762205c)

I do not find the /fonts directory

@StoneMoe

**Comment by Ambient-Impact** [comment]
I don't know if this was added recently, but I discovered that if I gave the Bottles flatpak access to my home fonts directory (`/home/ambientimpact/.fonts`), it automagically created the registry entries for the custom fonts I added the next time I started up Bottles. I expected to have to add a whole bunch of custom fonts by hand, but to my pleasant surprise, they were all already there.
