### ISSUE TITLE
Nothing just wish guys a merry Christmas 

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#2431]

**Comment by WowItsKaylie** [comment]
Here's to another year of Bottles and VanillaOS 🍻

**Comment by TheEvilSkeleton** [comment]
Thank you and merry Christmas to everyone!! :tada:

**Comment by Neon-44** [comment]
@csc-chicken let's reopen this next year :)

**Comment by csc-chicken** [comment]
@Neon-44 why not?? Just remind me to reopen because I'm from Taiwan and we celebrate Chinese new year.
