### ISSUE TITLE
[Translation] Bottles' name in Arabic

### ISSUE THREAD

**Issue by Ali-x98** [bottlesdevs/Bottles#2433]
Bottles' app name in Arabic is "زجاجات" , literally meaning glasses, as in bottles made of glass.

![image](https://user-images.githubusercontent.com/25479373/209321072-5fcb5fc8-b894-4f6a-a650-1413028e907b.png)

I believe that this is a mistake.

In the Arabic translations, I made sure to call the app by its original name. i.e., "Bottles" was transliterated into Arabic as "بوتلز".

So, the "official" app name should not be "زجاجات" as it appears on Gnome Software. Rather, it should be:
1- "Bottles" if the name is not to be transliterated
2- If the name is transliterated, it should be "بوتلز"
3- Or if it is to be translated, it should be "قوارير" which, in my opinion, is a better word than "زجاجات"

The word "قوارير" is the plural of "قارورة". It means "bottles".

I am not sure how changing the name is done, so I am opening this issue.

**Comment by Kinsteen** [comment]
All translations are done through Weblate, here: https://hosted.weblate.org/engage/bottles/
You can suggest a change, and it will be updated in the code automatically!

**Comment by Ali-x98** [comment]
Unless I'm missing it, I do not believe there is a string for the application name on Weblate.

**Comment by Kinsteen** [comment]
According to the file here: https://github.com/bottlesdevs/Bottles/blob/9fe1767f538be0befb9fd25849f9b806fec4234f/po/ar.po#L1842, this translation should be used in the .desktop file...

**Comment by jannuary** [comment]
There is, but there shouldn't be.

Also, @Kinsteen pointed out it's used in the .desktop files, I deleted that comment to avoid spam because Github erroneously displayed it thrice, sorry for that :/
