### ISSUE TITLE
[Bug]: Bottles isn't starting when offline

### ISSUE THREAD

**Issue by stefanobartoletti** [bottlesdevs/Bottles#2438]
### Describe the bug

Using the flatpak version, Bottles isn't starting when internet connection is off.
It just stops at the opening splash screen, the one where you are notified about fetching new packages, but no message is displayed at all and the program just stay on that screen forever.
Turning on the connection solves the problem, if you close bottles and launch it again it will start normally.
Don't know if it is related to package fetching, it just does not start and shows no messages.

### To Reproduce

1. try to start Bottle with no internet
2. wait
3. nothing happens :)
4. turn on internet
5. start bottles again
6. bottles launches

### Package

Flatpak from Flathub

### Distribution

openSUSE Tumbleweed

### Troubleshooting Logs

```shell
I cannot even get to the main window where this info can be collected
```

**Comment by Kinsteen** [comment]
Hi, can you run Bottles from the console (`flatpak run com.usebottles.bottles`) and send the logs here? Bottles should be able to start without a connection

**Comment by dr-nemesis-96** [comment]
@stefanobartoletti yes it happens if you have connected to a wifi/wired connection with no internet, disconnect from them and it will start normally

**Comment by stefanobartoletti** [comment]
Sorry for the delay.

I can confirm that the issue was related to being connected to a network without internet access. Bottles starts correctly if launched without being connected. I cannot reproduce the original issue at the moment.

Here is the log when starting it without being connected:

```
> flatpak run com.usebottles.bottles
16:31:09 (WARNING) Connection status: offline … 
16:31:09 (INFO) Bottles Started! 
16:31:09 (WARNING) Connection status: offline … 
16:31:19 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 10000 milliseconds') 
16:31:19 (ERROR) Could not get index for dependencies repository: (6, 'Could not resolve host: proxy.usebottles.com') 
16:31:19 (ERROR) Could not get index for installers repository: (6, 'Could not resolve host: proxy.usebottles.com') 
16:31:19 (INFO) Performing Bottles checks… 
16:31:19 (INFO) Dxvks found:
         - dxvk-2.0
         - dxvk-async-2.0
 
16:31:19 (INFO) Vkd3ds found:
         - vkd3d-proton-2.8
 
16:31:19 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
         - dxvk-nvapi-v0.6
 
16:31:19 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
16:31:19 (INFO) Runners found:
         - sys-wine-7.0.1
         - caffe-7.20
         - caffe-7.20-x86_64
         - soda-7.0-8
 
16:31:29 (WARNING) Connection status: offline … 
16:31:29 (INFO) No components found. 
16:31:29 (INFO) Temp directory cleaned successfully! 
16:31:29 (WARNING) Connection status: offline … 
16:31:29 (INFO) No dependencies found! 
16:31:29 (WARNING) Connection status: offline … 
16:31:29 (INFO) No installers found! 
16:31:29 (INFO) Bottles found:
         - Games
 

(bottles:2): Gtk-CRITICAL **: 16:31:29.865: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
16:31:30 (INFO) Library saved 
```
