### ISSUE TITLE
MangoHud and OBS VkCapture tools grey despite being installed

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#2450]
2022.12.14.1

Hi, mangohud and obs is grey/untoggleable even though I have the flatpak equivalent installed. Do i need to do something else in flatseal or elsewhere? They used to work a couple months ago in older versions. gamescope still lets me toggle even though that is external dependency. Thank you

![grey](https://user-images.githubusercontent.com/69682350/209743581-461dca2f-0ccc-4ffe-a00c-7609f781a375.png)

**Comment by Sunspark-007** [comment]
I have made the same observation. If Gamescope flatpak is installed it becomes toggleable in bottles flatpak and the settings for it become visible. However, if the MangoHud flatpak is installed, it is greyed out in bottles. So it appears as if bottles is seeing one flatpak, but not the other flatpak.

**Comment by Sunspark-007** [comment]
https://github.com/bottlesdevs/Bottles/issues/2297

**Comment by TheEvilSkeleton** [comment]
I'm unable to reproduce it on my end. What branch are MangoHud and OBS VkCapture tools installed on?

**Comment by ghtesting2020** [comment]
> I'm unable to reproduce it on my end. What branch are MangoHud and OBS VkCapture tools installed on?

I am not sure if I understand exactly what you mean by the "branch" it is installed on but in flatseal this is what i have for variables
```PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/```
which always worked in the past

**Comment by TheEvilSkeleton** [comment]
> I am not sure if I understand exactly what you mean by the "branch" it is installed on but in flatseal this is what i have for variables

When you run `flatpak list`, the fourth column is called "Branch". I'd like to know what branch MangoHud and OBS VkCapture are on.

**Comment by ghtesting2020** [comment]
> > I am not sure if I understand exactly what you mean by the "branch" it is installed on but in flatseal this is what i have for variables
> 
> When you run `flatpak list`, the fourth column is called "Branch". I'd like to know what branch MangoHud and OBS VkCapture are on.

thank you for clarifying.
```

flatpak update says no updates are available
Name                            Application ID                               Version    Branch       Installation

MangoHud                        ?g.freedesktop.Platform.VulkanLayer.MangoHud 0.6.8      21.08        system
OBS VkCapture tools             ?eedesktop.Platform.VulkanLayer.OBSVkCapture 1.2.2      21.08        system
```

**Comment by TheEvilSkeleton** [comment]
I see you have them installed from the `21.08` branch. Can you install from the `22.08` branch?

**Comment by ghtesting2020** [comment]
> I see you have them installed from the `21.08` branch. Can you install from the `22.08` branch?

Solved, thank you @TheEvilSkeleton

**Comment by Sunspark-007** [comment]
@ghtesting2020 How did you update it to the 22.08 branch? Flathub is still on the 21.08 branch.

**Comment by orowith2os** [comment]
Flathub already has, and has had, a 22.08 branch of OBSVkCapture for a while now.
