### ISSUE TITLE
[Bug]: Cannot run more than one executable per launch of Bottles

### ISSUE THREAD

**Issue by har-nick** [bottlesdevs/Bottles#2453]
### Describe the bug

Using the Run Executable option only works once per instance of Bottles.

The first launch executes as planned. Further launches of any executable fail silently.

When closing the first executable, an error is output.

A differing error is output during the life of the second executable, but I don't know if it occurs on launch or on closing. These errors have been added to the Additional Context section.

### To Reproduce

1. Open any Bottle
2. Select the "Run Executable..." option
3. Select any executable, and close it
4. Repeat step 2 and 3

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-artix1-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8337489920
    Free: 8337346560
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Additional context

<details>
<summary>
First Launch Error:
</summary>

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```

</details>

<details>
<summary>
Subsequent Launch Errors:
</summary>

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 403, in __execute
    args = self.config.get("session_arguments")
AttributeError: 'Result' object has no attribute 'get'
```

</details>

**Comment by Kinsteen** [comment]
Thanks for the detailed bug report! This bug has a PR which will fix the bug. For now, closing and re-opening the bottle fixes the bug temporarily!

**Comment by har-nick** [comment]
Thanks for the quick response.
