### ISSUE TITLE
[BUG] Since Chardonnay 6.4 my apps can't install as adminiastror 

### ISSUE THREAD

**Issue by richieloro** [bottlesdevs/Bottles#246]
**Describe the bug**
When I install an app in a Chandonnay 6.4 (or Lutris and Proton 6.4) it requires UAC elevation, or running as admin in windows. It does not happen with Chardonnay/Lutris/Proton 6.0. My program just Install fine in version <=6.0.

**Installation**
Flatpak version 3.1.6 on Ubuntu 20.04

![Screenshot from 2021-04-29 18-18-00](https://user-images.githubusercontent.com/81038208/116584104-4a404500-a917-11eb-82b0-3d27a817f405.png)
EDIT : Sorry if it was not a bug. But I could not find information about it. Thanks.

**Comment by mirkobrombin** [comment]
Hi. Wine runs every app as Administrator by its structure. Please read here: https://www.reddit.com/r/linuxquestions/comments/c48cyq/is_it_possible_to_emulate_user_account_control/ervcdso

Oddly it believes it is not started as an administrator but it actually is.

**Comment by richieloro** [comment]
It does not happen in Chardonnay 6.0, Lutris 5.21 and old version under V6.0. Why ?
Did something changed in Wine ?

**Comment by mirkobrombin** [comment]
> It does not happen in Chardonnay 6.0, Lutris 5.21 and old version under V6.0. Why ?
> Did something changed in Wine ?

Each release of Wine brings with it many changes. Something has probably changed and broken compatibility with that program. The message you read may not be the real problem but a mask for something deeper.

**Comment by richieloro** [comment]
Ok thank you. By something deeper you mean in wine or this program ?

Please don't remove the old version of the runner in bottles, someone might need them like in this case ;)
Thank you as always.

**Comment by mirkobrombin** [comment]
> Ok thank you. By something deeper you mean in wine or this program ?
> 
> Please don't remove (too many) old version of the runner in bottles, someone might need them like in this case ;)
> Thank you as always.

In wine that break something in the program

**Comment by richieloro** [comment]
Thank you have a good day.

**Comment by guihkx** [comment]
I don't know if Chardonnay uses patches from Staging, but this issue sounds much like this one:

https://bugs.winehq.org/show_bug.cgi?id=51000

**Comment by mirkobrombin** [comment]
> I don't know if Chardonnay uses patches from Staging, but this issue sounds much like this one:
> 
> https://bugs.winehq.org/show_bug.cgi?id=51000

we actually use the staging patch, thanks for reporting
