### ISSUE TITLE
[BUG] failed to load winex11.drv.so

### ISSUE THREAD

**Issue by gabrielluz-br** [bottlesdevs/Bottles#247]
**Describe the bug**
Basically, I can't open some .exe files I have but I've managed to use them for days 2 weeks ago using Chardonnay 6.4.

**Installation**
 - Method: Appimage
 - Version: 2882c06

**To Reproduce**
1. Open Bottles
2. Create a Bottle with all the dependencies or with just a few of them
3. I try to open an .exe file
4. See error on the console

**Expected behavior**
It should open my .exe file because it was opening 2 weeks ago but then I had to reinstall the OS due to problems with hard drives.

**Desktop (please complete the following information):**
 - OS: Parrot Security
 - Version 4.11.1

**Additional context**
Using Mate as a desktop. I don't have Wine installed.
Apps I've tried: TeamViewer 8 and ShanaEncoder.
Using Chardonnay 6.4. I've also tried Proton 6.5 just for testing purposes.
```
https://www.videohelp.com/software/ShanaEncoder
https://download.teamviewer.com/download/version_8x/TeamViewerPortable.zip
```

$./Bottles-devel-x86_64.AppImage 

(bottles:8722): Gtk-WARNING **: 16:59:13.000: Theme parsing error: gtk.css:17:25: negative values are not allowed.

(bottles:8722): Gtk-WARNING **: 16:59:13.517: Theme parsing error: gtk.css:17:25: negative values are not allowed.
2021-04-30 16:59:13 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2]
2021-04-30 16:59:13 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-30 16:59:16 INFO: Connection status: online …
https://raw.githubusercontent.com/bottlesdevs/components/main//index.json
2021-04-30 16:59:17 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-30 16:59:17 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2]
2021-04-30 16:59:17 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-04-30 16:59:17 INFO: Connection status: online …
2021-04-30 16:59:17 INFO: Connection status: online …
2021-04-30 16:59:17 INFO: Connection status: online …
2021-04-30 16:59:18 INFO: Connection status: online …
2021-04-30 16:59:18 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-04-30 16:59:18 INFO: Bottles Started!
2021-04-30 16:59:20 INFO: Setting Key: [sync] to [wine] for bottle: [WIN7fileoptimizer] …
2021-04-30 16:59:24 INFO: Running an executable on the wineprefix …
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
01b4:err:module:open_builtin_file failed to load .so lib "/home/linuxuser/.local/share/bottles/runners/chardonnay-6.4/lib/wine/winex11.drv.so"
01b4:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
01b4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01b4:err:winediag:nodrv_CreateWindow The explorer process failed to start.

**Comment by gabrielluz-br** [comment]
fileoptimizer works. That's the name of my Bottle.

**Comment by mirkobrombin** [comment]
Apparently you are missing some dependency of wine in the system. Can you try to install the `wine` package and try again using Bottles?

**Comment by gabrielluz-br** [comment]
> Some wine dependencies are missing in your system. Can you try the latest [unstable](https://github.com/bottlesdevs/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage) build?
> 
> If that doesn't work, try installing the `wine `package manually.

Ok, Sir. I've downloaded and ran the latest unstable build. Didn't work for me.
Also, I've tried installing Wine and I''ve managed to do so, but my Wine is 5.0 and Parrot Security does not allows users to add new repositories. Also, sorry for asking, but the point of using Bottles as an appimage is exactly NOT installing Wine? Or maybe you just asked me for a test case? Sorry for asking. I don't want to sound impolite.

My log below:
```
./Bottles-devel-x86_64.AppImage 

(bottles:17315): Gtk-WARNING **: 20:34:30.040: Theme parsing error: gtk.css:17:25: negative values are not allowed.

(bottles:17315): Gtk-WARNING **: 20:34:30.474: Theme parsing error: gtk.css:17:25: negative values are not allowed.
2021-04-30 20:34:30 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2]
2021-04-30 20:34:30 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-30 20:34:32 INFO: Connection status: online …
https://raw.githubusercontent.com/bottlesdevs/components/main//index.json
2021-04-30 20:34:32 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-30 20:34:32 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2]
2021-04-30 20:34:32 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-04-30 20:34:32 INFO: Connection status: online …
2021-04-30 20:34:33 INFO: Connection status: online …
2021-04-30 20:34:33 INFO: Connection status: online …
2021-04-30 20:34:33 INFO: Connection status: online …
2021-04-30 20:34:33 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-04-30 20:34:33 INFO: Bottles Started!
2021-04-30 20:34:36 INFO: Setting Key: [sync] to [wine] for bottle: [WIN7fileoptimizer] …
2021-04-30 20:34:40 INFO: Running an executable on the wineprefix …
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
024c:err:module:open_builtin_file failed to load .so lib "/home/linuxuser/.local/share/bottles/runners/chardonnay-6.4/lib/wine/winex11.drv.so"
024c:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
024c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
024c:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

**Comment by mirkobrombin** [comment]
>. Also, sorry for asking, but the point of using Bottles as an appimage is exactly NOT installing Wine? 

This is just for testing purpose.

> Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.

I missed this line, install the freetype fonts:
```
apt install libfreetype6:i386
```

**Comment by gabrielluz-br** [comment]
> > . Also, sorry for asking, but the point of using Bottles as an appimage is exactly NOT installing Wine?
> 
> This is just for testing purpose.
> 
> > Wine cannot find the FreeType font library.  To enable Wine to
> > use TrueType fonts please install a version of FreeType greater than
> > or equal to 2.0.5.
> 
> I missed this line, install the freetype fonts:
> 
> ```
> apt install libfreetype6:i386
> ```

The ttf font problem was solved with your command.

**Comment by gabrielluz-br** [comment]
> > . Also, sorry for asking, but the point of using Bottles as an appimage is exactly NOT installing Wine?
> 
> This is just for testing purpose.
> 
> > Wine cannot find the FreeType font library.  To enable Wine to
> > use TrueType fonts please install a version of FreeType greater than
> > or equal to 2.0.5.
> 
> I missed this line, install the freetype fonts:
> 
> ```
> apt install libfreetype6:i386
> ```

So I've managed to install Wine-Staging 6.7. I've basically downloaded all the deb packages for Debian Buster.
I've tried running some apps that weren't working with Bottles and all of the run no without any problems so far.
The message below disappeared:
```
024c:err:module:open_builtin_file failed to load .so lib "/home/linuxuser/.local/share/bottles/runners/chardonnay-6.4/lib/wine/winex11.drv.so"
024c:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
024c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
024c:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```
Here's my output now from Bottles:
└──╼ $./Bottles-devel-x86_64.AppImage 

```
(bottles:194995): Gtk-WARNING **: 16:57:10.157: Theme parsing error: gtk.css:17:25: negative values are not allowed.

(bottles:194995): Gtk-WARNING **: 16:57:11.228: Theme parsing error: gtk.css:17:25: negative values are not allowed.
2021-05-01 16:57:11 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2, chardonnay-6.0]
2021-05-01 16:57:11 INFO: Dxvk found: [dxvk-1.8.1]
2021-05-01 16:57:14 INFO: Connection status: online …
https://raw.githubusercontent.com/bottlesdevs/components/main//index.json
2021-05-01 16:57:15 INFO: Dxvk found: [dxvk-1.8.1]
2021-05-01 16:57:15 INFO: Runners found: [chardonnay-6.4, lutris-6.4, Proton-6.5-GE-2, chardonnay-6.0]
2021-05-01 16:57:15 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-05-01 16:57:15 INFO: Connection status: online …
2021-05-01 16:57:15 INFO: Connection status: online …
2021-05-01 16:57:15 INFO: Connection status: online …
2021-05-01 16:57:15 INFO: Connection status: online …
2021-05-01 16:57:15 INFO: Bottles found: WIN7fileoptimizer, videoTools
2021-05-01 16:57:16 INFO: Bottles Started!
2021-05-01 16:57:18 INFO: Setting Key: [sync] to [wine] for bottle: [WIN7fileoptimizer] …
2021-05-01 16:57:33 INFO: Running an executable on the wineprefix 
```

**Comment by gabrielluz-br** [comment]
Maybe you guys will have to embed the Wine itself. I don't know.
Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?

**Comment by mirkobrombin** [comment]
> Maybe you guys will have to embed the Wine itself. I don't know.
> Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?

There is no need for wine, we added the missing freetype dependency one commit ago. Now should work.

**Comment by gabrielluz-br** [comment]
> > Maybe you guys will have to embed the Wine itself. I don't know.
> > Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?
> 
> There is no need for wine, we added the missing freetype dependency one commit ago. Now should work.

It won't work if I uninstall Wine, though.

**Comment by mirkobrombin** [comment]
> > > Maybe you guys will have to embed the Wine itself. I don't know.
> > > Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?
> > 
> > 
> > There is no need for wine, we added the missing freetype dependency one commit ago. Now should work.
> 
> It won't work if I uninstall Wine, though.

Because uninstalling it removes some dependencies. I'm looking at wine dependencies to figure out which ones I need to include in bottles.

**Comment by gabrielluz-br** [comment]
> > > > Maybe you guys will have to embed the Wine itself. I don't know.
> > > > Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?
> > > 
> > > 
> > > There is no need for wine, we added the missing freetype dependency one commit ago. Now should work.
> > 
> > 
> > It won't work if I uninstall Wine, though.
> 
> Because uninstalling it removes some dependencies. I'm looking at wine dependencies to figure out which ones I need to include in bottles.

Can I close this issue? Looks fixed to me.

**Comment by mirkobrombin** [comment]
> > > > > Maybe you guys will have to embed the Wine itself. I don't know.
> > > > > Also, my question is: since I need an app, can I install it using Wine (not Bottles). Will it spoil Bottles' setup?
> > > > 
> > > > 
> > > > There is no need for wine, we added the missing freetype dependency one commit ago. Now should work.
> > > 
> > > 
> > > It won't work if I uninstall Wine, though.
> > 
> > 
> > Because uninstalling it removes some dependencies. I'm looking at wine dependencies to figure out which ones I need to include in bottles.
> 
> Can I close this issue? Looks fixed to me.

I forgot about it. I have opened another issue for dependency issues and since you have solved it, I close this one.

**Comment by Ashvith** [comment]
> Some wine dependencies are missing in your system. Can you try the latest [unstable](https://github.com/bottlesdevs/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage) build?
> 
> If that doesn't work, try installing the `wine `package manually.

What are the compulsory dependencies that have to be installed? I want to avoid the `sudo dnf install wine` route, because it creates a mess in my system, and it is hard to remove most of them.

**Comment by mirkobrombin** [comment]
Why not flatpak then?  Btw idk the specific packages, you should check what wine install
