### ISSUE TITLE
newBottle: Error message not visible

### ISSUE THREAD

**Issue by sophie-h** [bottlesdevs/Bottles#2471]
![image](https://user-images.githubusercontent.com/3466497/210151373-e6ea34b0-c2b2-47fb-95e2-3ce95c154794.png)

![image](https://user-images.githubusercontent.com/3466497/210151396-8339685a-de10-40fa-b247-9f9462435a1b.png)

Not sure if the toasts are a good idea in the first place. But certainly not in a different window.

Also, pressing enter does not actives create.

Also, would make it scrolled instead of changing the window size on expanding.

**Comment by TheEvilSkeleton** [comment]
> Also, pressing enter does not actives create.

This seems problematic. If the user prefers to use their keyboard, then pressing Enter would create the bottle instead.

**Comment by mirkobrombin** [comment]
I think they means that pressing Enter on the AdwEntryRow should trigger the creation, not on the AdwActionRow(s)

**Comment by TheEvilSkeleton** [comment]
Honestly, I have no idea how to implement this.
