### ISSUE TITLE
non-systemD support

### ISSUE THREAD

**Issue by cecxl** [bottlesdevs/Bottles#2473]
I have installed bottles through flatpak on Void and am having couple of problems, parts not working, I'm not seeing other people report those potential bugs. are non-systemD distros not supported or am I having problems for some other reason?

**Comment by TheEvilSkeleton** [comment]
Bottles is supposed to work without systemd. We can't help if no information is provided.

**Comment by cecxl** [comment]
Thank for the answer, just wanted to make sure before reporting the problems.
