### ISSUE TITLE
[Bug]: Cannot disable VKD3D

### ISSUE THREAD

**Issue by Sunspark-007** [bottlesdevs/Bottles#2474]
### Describe the bug

Once VKD3D is enabled in a bottle, you cannot disable it. 

Expected behaviour is to have it stay disabled if disable is selected.

### To Reproduce

Bottles 2022.12.14.1

Clicking disable on VKD3D, exiting the bottle, and returning to it shows that it has been re-enabled again in the settings.

### Package

Flatpak from Flathub

### Distribution

SteamOS 3.3.2

### Troubleshooting Logs

```shell
n/a
```

**Comment by TheEvilSkeleton** [comment]
Can confirm it works.

**Comment by mirkobrombin** [comment]
Provide Troubleshooting Logs please.
