### ISSUE TITLE
[Bug]: Browse path error

### ISSUE THREAD

**Issue by cecxl** [bottlesdevs/Bottles#2475]
### Describe the bug

If I press the browse path button in a program's hamburger menu or press browse files in hamburger menu on top-right I get an error: "**Could not show link** GDBus.error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files". I'm unable to access the paths.

### To Reproduce

create a bottle
select the bottle
access the top-right hamburger menu
press "Browser Files..."

### Package

Flatpak from Flathub

### Distribution

Void Linux

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.0.15_1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4113145856
    Free: 4112977920
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 4.9GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Desktop env?

**Comment by cecxl** [comment]
XFCE

**Comment by cecxl** [comment]
I figured out that I wasn't running dbus-run-session and that might be the problem, when I ran it I got another error: **Could not show link** GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface "org.freedesktop.portal.OpenURI" on object at path /org/freedesktop/portal/desktop

then I installed xdg-desktop-portal xdg-desktop-portal-gtk and that finally fixed it.

**Comment by AstroMuck** [comment]
Thanks ghost!  This resolved the issue for me on MX Linux!
