### ISSUE TITLE
[Bug]: Could not get index for repositories

### ISSUE THREAD

**Issue by amiruldevkun** [bottlesdevs/Bottles#2477]
### Describe the bug

Bottles can't connect or get indexes from the repositories, saying resolving timed out after ---- milliseconds.

### To Reproduce

1. Open bottles on terminal / normally
2.  See the error
![lol](https://user-images.githubusercontent.com/78654637/210165265-c73051ae-d85f-4cd6-9ed9-eda20620bfea.png)

### Package

Flatpak from Flathub

### Distribution

Manjaro 22.0

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.1-1-MANJARO
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8321257472
    Free: 8321105920
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.0GiB
Bottles_envs: null
```

### Additional context

I can get a response if I ping repo.usebottles.com directly. But the timing is always 165ms.
![Screenshot_20230101_163958](https://user-images.githubusercontent.com/78654637/210165305-d36c13c5-235f-4361-9445-291c86dadfb2.png)

**Comment by francescomasala** [comment]
Try to ping proxy.usebottles.com and try to open it, if you can specify your country is better

**Comment by francescomasala** [comment]
Sorry, by any chance can you also add `dig proxy.usebottles.com`?

**Comment by francescomasala** [comment]
ping @amiruldevkun

**Comment by amiruldevkun** [comment]
Oh sorry. Didn't see it.
I already changed to windows but will try it in wsl2. I'll try pinging it in windows and wsl2 when I have the time

**Comment by amiruldevkun** [comment]
> Try to ping proxy.usebottles.com and try to open it, if you can specify your country is better

Malaysia

**Comment by francescomasala** [comment]
> Oh sorry. Didn't see it.
> 
> I already changed to windows but will try it in wsl2. I'll try pinging it in windows and wsl2 when I have the time
> 
> 

Okay! It's better if you try to ping from linux

**Comment by amiruldevkun** [comment]
Hey! Sorry to leave you hanging but I think I know the problem. If i pinged using ipv4, the ttl is longer. But, if i use ipv6 its shorter. Is there any way to change bottles from using ipv4 as default?

**Comment by francescomasala** [comment]
we have updated our infra, now it should work

**Comment by amiruldevkun** [comment]
It still doesn't work from my side

**Comment by amiruldevkun** [comment]
its on a fresh install too

**Comment by francescomasala** [comment]
can you open https://proxy.usebottles.com ?

**Comment by amiruldevkun** [comment]
on the browser yes

**Comment by francescomasala** [comment]
in theory it redirects you to mirror.usebottles.com right?

**Comment by amiruldevkun** [comment]
Yes sir

**Comment by francescomasala** [comment]
try to do a `mtr` V4 and V6 on that please

**Comment by amiruldevkun** [comment]
oh could you explain what it is?

**Comment by amiruldevkun** [comment]
ok so what should i look at here
![Screenshot_20230213_103346](https://user-images.githubusercontent.com/78654637/218330007-7e0ecbbc-e9d8-4ef9-8bd1-2c1ee5f61e81.png)

**Comment by francescomasala** [comment]
try to do that on mirror.usebottles.com

**Comment by amiruldevkun** [comment]
![Screenshot_20230213_023510](https://user-images.githubusercontent.com/78654637/218330077-c1dccb74-911a-4b3b-9ab0-fcfd4974cb2b.png)
alright

**Comment by francescomasala** [comment]
Okay, from what I've seen the problem is not with us but with your connection (latency), one advice I can give you is to download the dependencies and use them locally, you can find a guide [here](https://maintainers.usebottles.com/Testing)

**Comment by francescomasala** [comment]
Btw: Meanwhile, I asked the devs if they can increase the waiting time for downloading files
