### ISSUE TITLE
[Bug]: Application works fine but when I press a menu button, it minimizes the window

### ISSUE THREAD

**Issue by BarbzYHOOL** [bottlesdevs/Bottles#2478]
### Describe the bug

I have Bottles 2022.12.14.1 on Pop OS 22.04

I installed Metatrader 4 easily as my first app.
When I click on SOME menus confirmation buttons, it suddenly minimizes the window and I have to reclick it to focus it.

**Note that I had installed this same app long ago and used it a lot, with raw wine (or playonlinux) and never had this issue.**

### To Reproduce

1. Download https://download.fxcorporate.com/FXCM-MT4Install.exe
2. Install by selecting an app environment
3. Click Tools -> Options -> PRESS "OK"
4. It should minimize/switch the window (like pressing Alt+Tab)

### Package

Flatpak from Flathub

### Distribution

Pop OS 22.04

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.6-76060006-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8370364416
    Free: 8370216960
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 6.9GiB
Bottles_envs: null
```

### Additional context

This app is extremely popular for traders and there is no linux version.

**Comment by Kinsteen** [comment]
I tried to reproduce your bug without success, can you reproduce it consistently? If yes, can you do a step by step?

**Comment by BarbzYHOOL** [comment]
> I tried to reproduce your bug without success, can you reproduce it consistently? If yes, can you do a step by step?

Thank you for taking the time to try it out!!

As I explained, the steps are:

-     Download https://www.fxcm.com/fr/plateforme/metatrader-4/telechargement/
-     Install
-     Click Tools -> Options -> PRESS "OK"
-  It should minimize/switch the window (like pressing Alt+Tab)


Yes, it happens all the time, each time it has the surprise effect

**Comment by Kinsteen** [comment]
I can't seem to be able to reproduce this issue on my side. What version of Wine are you using in the bottle? Does this behavior also happens on Wine without Bottles?

**Comment by BarbzYHOOL** [comment]
I have no idea, I just used the default settings.

How should I test it in Wine without Bottles? I remember it asked me to install more Wine stuff for 32bit so I decided to go with Bottles to avoid the headache.

When I look into bottles, it says "Runner: soda-7.0-8" and apparently i can change to another wine called "sys-wine-7.0.1"
Ok, while writing this, I changed to the other wine runner, and now this bug doesn't occur anymore, I just hope there isn't another bug caused by this change. Which Runner do you have it set up to?

PS: I had installed Wine stable prior to Bottles, dunno if it matters

**Comment by Kinsteen** [comment]
I used Wine GE on my side. I would suggest using it then, as "sys-wine", which is your system Wine maybe lacks some dependencies. But if it works, I think it will be okay!

**Comment by BarbzYHOOL** [comment]
I could only select Soda or Sys-wine, no Wine GE or other runners, why?

**Comment by mirkobrombin** [comment]
This is more a wine bug then Bottles. Closing, feel free to continue the conversation.
