### ISSUE TITLE
[Bug]: Runtime download infinite loop

### ISSUE THREAD

**Issue by erentar** [bottlesdevs/Bottles#2484]
### Describe the bug

What i can judge from the log is that runtime download does not match with checksum, and the application goes to infinite loop until killed.

### To Reproduce

```
sudo dnf install -y bottles && bottles
```
is what i did

### Package

Flatpak from Flathub

### Distribution

fedora 37

### Troubleshooting Logs

```shell
none of the system specs or anything is relevant but have my neofetch if it is so important

 OS: Fedora 
 Kernel: x86_64 Linux 6.0.15-300.fc37.x86_64
 Uptime: 1d 17h 56m
 Packages: 8269
 Shell: sh
 Resolution: 2560x1600
 DE: KDE 5.101.0 / Plasma 5.26.4
 WM: KWin
 GTK Theme:  [GTK2/3]
 Disk: 1.2T / 1.3T (96%)
 CPU: AMD Ryzen 9 5900HX with Radeon Graphics @ 16x 4.675GHz
 GPU: NVIDIA GeForce RTX 3050 Laptop GPU
 RAM: 18951MiB / 27914MiB
```

### Additional context

![image](https://user-images.githubusercontent.com/40326736/210471599-52acf17d-e291-4509-93e7-1ad6ead2250b.png)

**Comment by jannuary** [comment]
> sudo dnf install -y bottles && bottles

Please install the official package and tell if that is reproduced there.
