### ISSUE TITLE
[Bug]: wont install d3dx9, d3dcompiler_43, d3dcompiler_47 and maybe other Dependencies

### ISSUE THREAD

**Issue by dkeruza-neo** [bottlesdevs/Bottles#2491]
### Describe the bug

When creating a bottle, the file d3dx9.tar.xz is not extracted inside the prefix, windows/system32/

Wont even won't reinstalling the dependency.

### To Reproduce

Create a bottle or reinstall the dependency.

### Package

Flatpak from GitHub Artifacts

### Distribution

Arch

### Troubleshooting Logs

```shell
Official Package: false
Version: 2022.12.14.1
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-arch1-g14-2
Disk:
    Total: 1496019107840
    Free: 944889794560
RAM:
    MemTotal: 14.9GiB
    MemAvailable: 8.0GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Additional context

It works from the flatpak version, but there are other issues with it.

**Comment by Kinsteen** [comment]
When you say the version from Github artifacts, which one exactly are you talking about?

**Comment by dkeruza-neo** [comment]
> When you say the version from Github artifacts, which one exactly are you talking about?
> 
> Also, what do you mean it's not copying DLLs? Can you provide logs when installing a dependency?

I pulled the source with git pull, I tried downloading the zip file from github and also built from sources with yay in Arch.
I open the bottle, click on dependencies, I remove and reinstall for example d3dcompiler_43. GUI says its succefully installed, but checking the prefix folder/windows/system32 and the d3dcompiler_43.dll has not been replaced.
How do I get logs?

**Comment by Kinsteen** [comment]
To get logs, simply launch Bottles from the command line.

On my side using latest sources, it works correctly: stubs have a size of 298.6 kbytes, and the real DLLs have a size > 2MB.

Are you sure they are not replaced?
![image](https://user-images.githubusercontent.com/5410562/211083194-f9090c68-c3c9-40b8-903f-2ef6a65892c4.png)

**Comment by dkeruza-neo** [comment]
Brand new pull from Github
![image](https://user-images.githubusercontent.com/16725214/211085499-09d8a9f3-c0bb-483f-83b5-89b4dfb474bb.png)
Opened bottles and created a new bottle.
![image](https://user-images.githubusercontent.com/16725214/211087690-fd76dac4-59a3-4d66-9568-2ae70486191a.png)
![image](https://user-images.githubusercontent.com/16725214/211087810-93276a1d-b05e-407a-80ec-04d619049bff.png)
![image](https://user-images.githubusercontent.com/16725214/211088284-d1822662-5928-4e23-ab08-8ef444e33bd4.png)
Files are nor replaced, I still have the stub files.

Another bug I found is not related to this one, but if I have the variable WINEARCH set in my env and I run bottles from the terminal, wine will use the value of that variable.

**Comment by Kinsteen** [comment]
How are you compiling/running Bottles when you pull from source?

I see in the logs that Bottles isn't trying to copy the DLLs, it should say something like:
![image](https://user-images.githubusercontent.com/5410562/211100410-c88e86d2-8ff6-444c-8c18-0f50ccd2dbbd.png)

**Comment by dkeruza-neo** [comment]
I run ./install.sh inside of the Bottles directory, once installed, I run bottles from the terminal.

I saw the same thing, but its not copying the .dlls from .tar.xz files.
Permissions are fine also.

**Comment by dkeruza-neo** [comment]
Ok, this is weird.
I copied the folder bottles with all the python source from the flatpak installation to the folder that the installer from github source installed in /usr/local/share and still, does not copy the .dlls. But if I run it from the flatpak installation, it works.

**Comment by Kinsteen** [comment]
I have no clue what is going on then.

https://github.com/bottlesdevs/dependencies/blob/main/Essentials/d3dcompiler_43.yml

The dependency installer is supposed to follow this manifest, which it seems like it does but it skips the copy_dlls step for an unknown reason. I'm quite sure the copy_dll should log something when something goes wrong, but it seems like it doesn't. Also, if something went wrong it shouldn't continue with the registry step...

**Comment by dkeruza-neo** [comment]
I found the issue. It is patoolib. Refer to this link: https://github.com/wummel/patool/issues/94

The difference is that with the flatpack edition, xz is not included in the bottles flatpack so patoolib defaults to tar, but as I do have xz installed in my system, patoolib defaults to xz to uncompress the .tar.xz files and fails because of the bug mentioned above.

**Comment by dkeruza-neo** [comment]
this should fix it.
https://github.com/bottlesdevs/Bottles/commit/4d8647566c988fe8350d15f80129dd6f5ee8550d

**Comment by dkeruza-neo** [comment]
I added a check to make sure the source files exist.
I never used github. I cannot commit changes so I created a branch. I don't know if you can merge from my branch.

https://github.com/dkeruza-neo/Bottles/commit/881ab5cfbc6fedd7a0d1cbbea2b50a465cad3e94

**Comment by Kinsteen** [comment]
You can create a PR here: https://github.com/bottlesdevs/Bottles/compare. Select "compare across forks", and compare this repo main branch to your fork main branch!

**Comment by dkeruza-neo** [comment]
As sugested by @Kinsteen  I created a PR.

#2498
