### ISSUE TITLE
[BUG] Can't import Lutris bottles

### ISSUE THREAD

**Issue by heylix** [bottlesdevs/Bottles#250]
**Describe the bug**
In the import dialog, refreshing leads to `INFO: Found 0 wineprefixes ..`.

**Installation**
 - Method: Flatpak
 - `Release 3.1.6 (2fb1b0e2)` (found in `flatpak info com.usebottles.bottles`)

**To Reproduce**
1. Go to Menu → Import and export
2. Click on "refresh"

**Expected behavior**
Me being able to import Lutris' bottles and/or select a folder to import from.

**Screenshots**
![image](https://user-images.githubusercontent.com/36211486/116813658-1eaa9e00-ab55-11eb-852d-1a9a52281cfd.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Additional context**
Installed Lutris through Flatpak, too.

**Comment by mirkobrombin** [comment]
I think that the Lutris flatpak is storing the wineprefixes in a different path then the non-flatpak package.

**Comment by heylix** [comment]
Same with local package. I changed the default installation folder, it was `~/Games` IIRC.

**Comment by mirkobrombin** [comment]
Maybe our flatpak has no permissions. Can you check if you have the same problem with the AppImage?

**Comment by heylix** [comment]
Yes, same problem with AppImage v3.1.7 and AppImage v3.1.5.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/116873651-5595b800-ac18-11eb-9e92-d72b2e365476.png)
It is working on my side. Can you verify that the `/home/USER/Games` path contains files?

**Comment by mirkobrombin** [comment]
Closing for no response in 16 days.
Note: the tests performed with 3.1.8 (current stable) were positive using: Flatpak (Silverblue), Snap (Ubuntu 21.04), AppImage (Ubuntu 21.04), deb (Ubuntu 21.04), rpm (from Fedora repository), bottles from AUR.
