### ISSUE TITLE
[Bug]: Crash Report

### ISSUE THREAD

**Issue by jemail99** [bottlesdevs/Bottles#2509]
### Describe the bug

Waiting for .net to install I left the PC. Firewall blocked the download in the meantime then crash occurred.

### To Reproduce

Download .net.
wait 
let firewall block the fownload
wait
crash

### Package

Flatpak from Flathub

### Distribution

Opensuse Tumbleweed

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.2-1-default
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16775876608
    Free: 16775720960
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 25.8GiB
Bottles_envs: null
```

### Additional context

name 'requests' is not defined  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 135, in install
    _res = self.install(config, [_ext_dep, _dep])

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 144, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 224, in __perform_steps
    if not self.__step_install_exe_msi(config=config, step=step):

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 351, in __step_install_exe_msi
    download = self.__manager.component_manager.download(

  File "/app/share/bottles/bottles/backend/managers/component.py", line 203, in download
    except requests.exceptions.RequestException:

**Comment by Kinsteen** [comment]
This is a known bug and already fixed, will be published in next release!
