### ISSUE TITLE
[Bug]: Deleted bottle through the terminal, error after opening

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2514]
### Describe the bug

Deleted a bottle through the terminal, can't open bottles anymore

```
[Errno 2] No such file or directory: '/home/USER/.local/share/bottles/bottles/GE/bottle.yml'  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 202, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 189, in checks
    self.check_bottles()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 798, in check_bottles
    process_bottle(b)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 755, in process_bottle
    self.update_config(

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 868, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

Bottles should ignore the missing file and procede. Maybe warn in the UI that the file was not found.

### To Reproduce

1. Create new bottle
2. Delete it through the terminal. `rm -rf bottles/GE/`
3. Try to open Bottles

### Troubleshoot

```
Official Package: false
Version: 2022.12.14.1
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.3-zen1-1-zen
Disk:
    Total: 52521566208
    Free: 11174727680
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 14.1GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Package

Local

### Distribution

Artix

**Comment by mirkobrombin** [comment]
Assuming that it is wrong to alter an application's files manually, Bottles shouldn't throw this exception anyway. I tried to replicate the issue without success. Are you sure all the files was removed before starting Bottles again? Also .local/share/bottles/bottles/GE/bottle.yml is not the flatpak path, did you change the default locations for bottles? Which version is this? Can you provide the troubleshooting log which the bug report template mention?

**Comment by mirkobrombin** [comment]
I’ll try that version

**Comment by Kinsteen** [comment]
@duarm Can you still reproduce the problem, or can we close this?

**Comment by duarm** [comment]
I think that GE bottle was borked since the beggining, It wasn't showing up in the UI and I remember deleting it through the UI some time ago, but it was still on disk, when I deleted it, bottles behaved like I described in the issue. But indeed If I just follow the normal workflow on bottles-git 1:2022.12.14.1.r31.g061cd04e-1, bottles works correctly
