### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Greg1996** [bottlesdevs/Bottles#2515]
### Describe the bug

Seems to be a crash issue. Opened the bottles flatpak application, and was met with this screen.

### To Reproduce

1. Open application (at least for me).

### Package

Flatpak from Flathub

### Distribution

OpenSUSE Tumbleweed

### Troubleshooting Logs

```shell
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 26, in send_status
    if status == 0 and not WineServer(self.config).is_alive():

  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
```

**Comment by EnfrigFalco** [comment]
I get the same issue, constantly, across multiple OS installations including fresh install of Fedora 37

The crash is actually spawned from the previous Bottle instance. For whatever reason wine apps/games stop responding, even to force kills from bottles. You have close Bottles and reopen it.

**Comment by mirkobrombin** [comment]
Fixed some commits ago, will be distributed with next release

**Comment by Termuellinator** [comment]
Happened to me just now after adding a path override while bottles was running - maybe related to that?

**Comment by Kinsteen** [comment]
@Termuellinator are you using latest release (Bottles 50.1)?

**Comment by Termuellinator** [comment]
@Kinsteen info is saying `2022.12.14.1` (installed from flathub), so probably not?
Sorry i missed that comment about the next release!
And i must admit that i didn't save the crash log from the dialogue but just opened the proposed link - that's what you get for trying things before breakfast i guess ^^

**Comment by Kinsteen** [comment]
@Termuellinator No problem! Please update and see if you still have problems, and if you do, open a new issue please 😊

**Comment by Termuellinator** [comment]
Will do!
Thanks for you amazing work! <3
