### ISSUE TITLE
Bottles "Almost ready"

### ISSUE THREAD

**Issue by euakll** [bottlesdevs/Bottles#2517]
After installation with the Software Manager GUI the bottles try to configure initially.
This operation takes forever and never ends stuck in the screen of "Almost ready..."

System Information:
New Installation of Fedora 37 (workstation)
GNOME Version 43.2 with Wayland
AMD Ryzen 5 5500U with Radeon graphics
[](url)

**Comment by Kinsteen** [comment]
Hi, can you give us the version of Bottles? Also, can you launch Bottles from the terminal and send logs here? Thank you!

**Comment by Kinsteen** [comment]
This version is not supported, you should update and see if the problem still exists.

**Comment by euakll** [comment]
Thanks for your answer. But which version is not supported? Fedora 37?
And what ya mean with update? There is no "up"

**Comment by Kinsteen** [comment]
Bottles package in Fedora is not up to date (the version shipped is from July...). The official way to get Bottles is via Flatpak, see https://docs.usebottles.com/getting-started/installation

**Comment by TheEvilSkeleton** [comment]
Closing this since it's a third-party problem.
