### ISSUE TITLE
[Request]: Notify user when bottle is created when unfocused

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2543]
### Tell us the problem or your need

Each bottle can take time to create. Many users (including myself) would leave Bottles in the background, do something else and wait until it's done. However, there's no indication outside of Bottles that will tell you that the creation is done.

### Describe the solution you'd like

A notification that tells the user that the bottle has been created would certainly help in this case. The notification should only appear when the window is unfocused.

### Additional context and references

https://gitlab.com/TheEvilSkeleton/Upscaler/-/merge_requests/34

**Comment by TheEvilSkeleton** [comment]
@gregorni hey, I'm going to base your contributions from [Upscaler MR #34](https://gitlab.com/TheEvilSkeleton/Upscaler/-/merge_requests/34) to https://github.com/bottlesdevs/Bottles/pull/2505. Do you want to be credited?

**Comment by gregorni** [comment]
Er, sure, I guess.

**Comment by TheEvilSkeleton** [comment]
Is there anything wrong, as in any concern? I'm probably reading too much into your message :sweat_smile:

**Comment by gregorni** [comment]
> Is there anything wrong, as in any concern? I'm probably reading too much into your message 

You are. I was just a bit surprised that all of a sudden someone thought my code was good enough to be worth building from. It's kind of a new experience to me.
