### ISSUE TITLE
[Bug]: Unable to open Bottles

### ISSUE THREAD

**Issue by Petrelis-Efstratios** [bottlesdevs/Bottles#2549]
### Describe the bug

When the app open, it get's stuck on _Fetched 3 of 3 packages_. I close the app and when I reopen it, it shows me the following logs. This issue showed up when I updated to 50.1

### To Reproduce

Open the app

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1 LTS

### Troubleshooting Logs

```shell
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Opera-GX__185/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 194, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 189, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 804, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 758, in process_bottle
    self.update_config(

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 874, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

**Comment by Kinsteen** [comment]
Hi @Petrelis-Efstratios, can you send a screenshot of your `/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles` folder please?

**Comment by Petrelis-Efstratios** [comment]
> Hi @Petrelis-Efstratios, can you send a screenshot of your `/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles` folder please?

![Screenshot from 2023-01-18 19-20-08](https://user-images.githubusercontent.com/121340191/213250963-f11a2623-8ef6-4efd-8e8d-236141bb6540.png)
I've also updated to 50.2 and the issue haven't changed

**Comment by Kinsteen** [comment]
This will be fix in the next release of Bottles. In the meantime, rename this folder to `Opera-GX__185`. Tell me if it's fixed!

**Comment by Petrelis-Efstratios** [comment]
> This will be fix in the next release of Bottles. In the meantime, rename this folder to `Opera-GX__185`. Tell me if it's fixed!

Yes, the fix worked

**Comment by Kinsteen** [comment]
Great! In version 50.3/51, you'll be able to rename your folder however you want.
