### ISSUE TITLE
Improve the snapcraft build recipe

### ISSUE THREAD

**Issue by keshavbhatt** [bottlesdevs/Bottles#255]
I don't think you need to add those lib-dev packages in the stage packages, lib-dev packages are the header files for the library and are not supposed to be packaged with the runtime dependency as they are only required while building something from source code.

Removing them will reduce the size of resulting snap package.

**Comment by mirkobrombin** [comment]
Those libraries may be there by mistake, I have to make sure these are not indispensable to python to run. Are you able to test and submit a pr?
