### ISSUE TITLE
[Bug]: ?

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#2552]
### Describe the bug

illegal environment variable name  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 170, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 123, in run_program
    ).run()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 212, in run
    return self.__launch_with_bridge()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 240, in __launch_with_bridge
    return self.__launch_exe()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 271, in __launch_exe
    res = winecmd.run()

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 641, in run
    proc = subprocess.Popen(

  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.10/subprocess.py", line 1764, in _execute_child
    raise ValueError("illegal environment variable name")

### To Reproduce

.

### Package

Flatpak from Flathub

### Distribution

Vanilla OS

### Troubleshooting Logs

```shell
Official Package: true
Version: '50.1'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-60-11/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-29-generic
Disk:
    Total: 8351514624
    Free: 8351354880
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.1GiB
Bottles_envs: null
```

**Comment by TheEvilSkeleton** [comment]
We can't troubleshoot issues if the issuer didn't put the effort to explain what happens and what the steps to reproduce are.

**Comment by Heus-Sueh** [comment]
> We can't troubleshoot issues if the issuer didn't put the effort to explain what happens and what the steps to reproduce are.

sorry man, apparently I'm a bug magnet, this bug just happened out of nowhere

**Comment by notpeelz** [comment]
Looks like it happens when you define environment variable *names* with illegal characters in them (e.g. `=`)
