### ISSUE TITLE
Am i missing something or are we shouldn't supposed to change runners?

### ISSUE THREAD

**Issue by Dhizaes** [bottlesdevs/Bottles#2557]
Hi,
I remember that i've changed runners before for already created Bottles but now when i try to change it, it just stucks and there is no resource usage happening. It is not related to V50 but it is still happening in V50. I don't remember when it started but it is probably few versions before, including minor versions. And this problem is brokes my bottles since it isn't doing a thing and i need to kill Bottles app. I can still play my games in these bottles but runner change isn't doing its job for me. It is failing i presume but in the settings it shows the last selected runner while using the old one. Are we shouldn't supposed to change runners or is it a bug? I'm not sure which one is it so i'm opening this as feedback since i need to learn what is the problem. I'm using Flatpak version and i'm on Arch.

**Comment by jannuary** [comment]
If you weren't "supposed" to change runners, it wouldn't have been an option. Please report this with the proper issue template.
