### ISSUE TITLE
[Bug]: Stuck at runner change and can't change runner properly

### ISSUE THREAD

**Issue by Dhizaes** [bottlesdevs/Bottles#2558]
### Describe the bug

I've created my Bottles few versions before. One of them used Soda and the others used Proton-GE. After i learned that Proton-GE isn't a necessary thing outside of Steam, i changed them to wine-ge, and i changed Soda used bottle to wine-ge too. The first issue happened after i tried to open one specific game launcher isn't given by Bottles. It isn't worked properly under wine-ge so i changed bottle runner to Soda. Then i saw that runner changing just stucks, running infinite amount of time and there is no resource usage in the system monitor. After a long time i terminated Bottles app and reopened it. Now my bottle shows what i selected before termination, but i have same issues as wine-ge. At first i thought that it is wine related or something but still doesn't explain why it is stuck. I tried to compare file size of my bottle while changing runner. It isn't changing, the sizes are same. It shows Soda as a runner in the bottle settings but it is still uses wine-ge i'm sure of it because of the bugs in a specific game. One of my bottle just have one game launcher in it so i decided to remove it and create a new bottle with Soda as a runner. The issues i had previously on a specific game is almost fixed thanks to Soda. 

When i put all of them together i'm sure i can't change runners. Also, i think i have this issue after 2022.12. I started using Bottles and created my first bottles with 2022.11.

### To Reproduce

1. Open any Bottle
2. Go to Settings
3. Change runner to any other runner
4. It tries to change runner, but it never ends, and the end of the day it isn't changing runner
5. Terminate Bottles
6. Open Bottles again and repeat until section 2. 
7. Runner name is changed to what you selected at section 3., but it isn't changed anything

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Official Package: true
Version: '50.1'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-78-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.6-arch1-1
Disk:
    Total: 16789970944
    Free: 16789803008
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.1GiB
Bottles_envs: null
```

**Comment by Kinsteen** [comment]
Can you run Bottles from the command line (`flatpak run com.usebottles.bottles`) and try to change runners?

**Comment by Dhizaes** [comment]
I didn't think of it and i feel bad now. This one is repeats itself few times and looks like it then crashes.

```
19:09:44 (INFO)  
19:09:44 (INFO) Importing bundle to UbisoftConnect registry 
19:09:45 (INFO) Using Wine Registry CLI -- import_bundle 
19:09:45 (WARNING) Steam runtime was requested but not found 
19:09:45 (WARNING) Steam runtime was requested and found but there are no valid combinations 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
19:09:47 (INFO)  
19:09:47 (INFO) Importing bundle to UbisoftConnect registry 
19:09:48 (INFO) Using Wine Registry CLI -- import_bundle 
19:09:48 (WARNING) Steam runtime was requested but not found 
19:09:48 (WARNING) Steam runtime was requested and found but there are no valid combinations 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
19:09:50 (INFO)  
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_preferences.py", line 809, in update
    self.switch_steam_runtime.handler_block_by_func(self.__toggle_steam_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_steam_runtime of <bottle_preferences.PreferencesView object at 0x7f2967b0ad80 (DetailsPreferences at 0x55b1a7753aa0)>>
```

I'm sure i disabled Steam runtime for all of my Bottles since it is just needed for Proton-GE. Looks like it is somehow turned on and now i can't find Steam runtime option in bottle. Should i find and remove it from config files by hand?
