### ISSUE TITLE
[Bug]: Bottles ran the software (OpenMPT) fine the first time. When restarting it just froze...

### ISSUE THREAD

**Issue by TinyXL** [bottlesdevs/Bottles#2571]
### Describe the bug

Bottles ran the software (OpenMPT) fine the first time. When restarting it just froze - when shutting down bottles and restarting it again it gave the error message pasted below.

### To Reproduce

1. Install OpenMPT
2. Run it once 
3. In OpenMPT setup screen set to use Wine option
4. restart Bottles. 

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Troubleshooting Logs

```shell
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 26, in send_status
    if status == 0 and not WineServer(self.config).is_alive():

  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
```

**Comment by Kinsteen** [comment]
This problem should be fixed with Bottles 50.2, please update and comment if you still get the issue
