### ISSUE TITLE
[Bug]: Manifest parameter doesn't change bottle when testing installer locally

### ISSUE THREAD

**Issue by HaydenS3** [bottlesdevs/Bottles#2575]
### Describe the bug

I added the following to a manifest I am developing
```
Paramaters:
  renderer: vulkan
```
When I tested the installer locally, the installer worked as expected, however it had not changed the Advanced Display Settings >> Renderer setting to Vulkan.

Maybe I'm using the incorrect syntax for the parameter. Any help would be appreciated!

### To Reproduce

1. Add the following as a local installer: [https://pastebin.com/JT3BmHeH](https://pastebin.com/JT3BmHeH)
2. Create a clean bottle using caffe-7.20, 64 bit
3. Run installer for Rapid Harness

### Package

Flatpak from Flathub

### Distribution

Pop!_OS 22.04

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: pop
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-76060006-generic
Disk:
    Total: 8238174208
    Free: 8238022656
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 10.0GiB
Bottles_envs:
    LOCAL_INSTALLERS: /home/hayden/repos/bottles/programs/
```

**Comment by Kinsteen** [comment]
Hello, this should normally work. It seems like you made a typo: it should be:
```
Parameters:
  renderer: vulkan
```

**Comment by HaydenS3** [comment]
Oops, that's a little embarrassing. Thanks!
