### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by eson57** [bottlesdevs/Bottles#258]
**Describe the bug**
Swedish translation do not work

**Installation**
 - Method: Flatpak
 - Version 3.1.7

Launch Bottles

**Expected behavior**
App gui in Swedish

**Desktop : Cinnamon
 - OS: Linux Mint
 - Version 20.1

**Comment by mirkobrombin** [comment]
Duplicate of #174 
I close the discussion as it is the same problem as a previous issue. Comment them in case you have more details.
