### ISSUE TITLE
[Bug]: cjkfonts cannot installed.

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#2582]
### Describe the bug

I cannot install cjkfont to use line in Chinese is noto sans hans etc.. from log ttc was downloaded successfully but extract with error .

### To Reproduce

1. create a bottle
2. go to dependency
3. press cjkfonts

### Package

Flatpak from Flathub

### Distribution

Manjaro kde 21

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.85-1-MANJARO
Disk:
    Total: 8360501248
    Free: 8360357888
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 4.6GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
00:40:35 (INFO) Installing dependency [cjkfonts] in bottle [line]. 
00:40:36 (WARNING) File [SourceHanSans.ttc.zip] already exists in temp, skipping. 
patool: Extracting /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip ...
patool: running /app/bin/7z x -o/home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc -- /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip
patool: ... /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip extracted to `/home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc'.
patool: Extracting /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc/SourceHanSans.ttc ...
```

### Additional context

maybe #2375 #2376 reappeared after 50.2 hot fix?? or maybe i need a clean install of bottles instead of upgrading from last one

**Comment by csc-chicken** [comment]
I also tested on Ubuntu 22.04 in virtualbox with brand new install of bottles and also not working.

**Comment by csc-chicken** [comment]
I found that why do we extract twice?? `patool: Extracting /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc/SourceHanSans.ttc ...` doesn't make sense. the ttc file is already extracted from first extraction from log.

```log
00:40:35 (INFO) Installing dependency [cjkfonts] in bottle [line]. 
00:40:36 (WARNING) File [SourceHanSans.ttc.zip] already exists in temp, skipping. 
patool: Extracting /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip ...
patool: running /app/bin/7z x -o/home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc -- /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip
patool: ... /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip extracted to `/home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc'.
patool: Extracting /home/leon/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc/SourceHanSans.ttc ...

```
![image](https://user-images.githubusercontent.com/66060998/213628392-4b5c5cb8-11e4-4ca8-b55f-c2b0f6ddc72f.png)

**Comment by StoneMoe** [comment]
Hi, thanks for reporting this issue
could you please provide the output of these command please?
```bash
# run these command on your host
env | grep LC
flatpak config --list
flatpak config --user --list
```
also, can you provide FULL log from the bottles started to the `cjkfonts` installed? thanks

and what exactly you are seeing about this issue? font missing? program crash? or something else?

**Comment by csc-chicken** [comment]
found it ! below code is used in tar.xz file , no wonder it will extract twice(decompress and archive). However, font files is only in zip so we only need to extract once. But sorry I don't know how to fix or contribute. Maybe @dkeruza-neo from #2498 knows.

![image](https://user-images.githubusercontent.com/66060998/213633379-3b2ed162-58de-4c5b-9225-bfde7bacf692.png)

**Comment by csc-chicken** [comment]
the line 508 should add check if file format is tar. first extract from 505 will extract zip ,gz or xz etc. Then the second extraction will dearchive tar

**Comment by Kinsteen** [comment]
Thank you for your detailed report! I'll fix this

**Comment by csc-chicken** [comment]
@StoneMoe here it is.
I used line(message app in Taiwan and Japan) which use Chinese font. unifont is good but SourceHanSans from cjkfont is better.
![image](https://user-images.githubusercontent.com/66060998/213637618-bc085511-185f-49bc-9e3a-847206a20cf5.png)

**Comment by csc-chicken** [comment]
> Thank you for your detailed report! I'll fix this

@Kinsteen 
You're welcome!! Just a guy who don't know how to fix and make pull request haha!! Time for my Chinese new year in Taiwan.

**Comment by StoneMoe** [comment]
感謝，新年快樂 :D
也歡迎來 Discord 一起捉蟲

**Comment by csc-chicken** [comment]
Oh! I didn't expect that!! Happy new year!
@StoneMoe 新年快樂，過年後再來dc。

**Comment by Kinsteen** [comment]
I made a dirty hack that should fix it, it will be released soon!

**Comment by csc-chicken** [comment]
Sure!! Just remember to comment why dirty hack is here.

**Comment by Kinsteen** [comment]
With git blame you can find quite quickly why is this here! It's also discussed to make a proper implementation of a better way to extract files anyway

**Comment by dkeruza-neo** [comment]
I fixed it, I'll post the fix in a minute.
I still don't quite understand GitHub.

**Comment by Kinsteen** [comment]
@dkeruza-neo I already created a fix!

**Comment by HubKing** [comment]
Has this already been fixed in the Flatpak version? I installed Bottles from Flatpak. The version is 50.2. I tried to install "cjk fonts" and it keeps failing. In the "Temp" directory, I see `SourceHanSans.ttc.zip` and the extracted file. I do not know how I can see the error message; the UI just says it has failed.

[cjk.webm](https://user-images.githubusercontent.com/10900489/219954222-134b3634-07be-44c0-ac30-5c59dd2c89d5.webm)

**Comment by StoneMoe** [comment]
> I do not know how I can see the error message; the UI just says it has failed.

@HubKing you can run `flatpak install com.usebottles.bottles` to see error message

**Comment by weaksloth** [comment]
> 



> Has this already been fixed in the Flatpak version? I installed Bottles from Flatpak. The version is 50.2. I tried to install "cjk fonts" and it keeps failing. In the "Temp" directory, I see `SourceHanSans.ttc.zip` and the extracted file. I do not know how I can see the error message; the UI just says it has failed.
Me too! !I think flatpak version has not been fixed,hope release soon @StoneMoe

**Comment by Kinsteen** [comment]
A release will be up tomorrow or today that will fix the bug probably. If it still happens on Bottles 51.0, please fill a new issue!

**Comment by HubKing** [comment]
> If it still happens on Bottles 51.0, please fill a new issue!

Upgraded Flatpak 51.0; the same problem. I ran Bottles in terminal and the output was like below. One thing I noticed is that Wine is trying to open `unix\\home\\username\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\General\\`. Is not normal that the path starts with `unix\\`, not `\\`?

> 13:01:13 (INFO) Installing dependency [cjkfonts] in bottle [General]. 
> 13:01:14 (WARNING) File [SourceHanSans.ttc.zip] already exists in temp, skipping. 
> patool: Extracting /home/username/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip ...
> patool: running /app/bin/7z x -o/home/username/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc -- /home/username/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip
> patool: ... /home/username/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc.zip extracted to `/home/username/.var/app/com.usebottles.bottles/data/bottles/temp/SourceHanSans.ttc'.
> 13:01:15 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Source Han Sans SC ExtraLight] and Data: [SourceHanSans.ttc] in General registry 
> 13:01:15 (INFO) Using Wine Registry CLI -- add 
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (ja_JP)
> wineserver: using server-side synchronization.
> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
> wine: could not open working directory L"unix\\home\\username\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\General\\", starting in the Windows directory.
> wine: could not open working directory L"unix\\home\\username\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\General\\", starting in the Windows directory.
> 13:01:16 (ERROR) Error while running async job: <bound method DependencyManager.install of <bottles.backend.managers.dependency.DependencyManager object at 0x7f75d3b96da0>>
> 	Exception: a bytes-like object is required, not 'str'
>  
>   File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
>     result = self.task_func(*args, **kwargs)
>   File "/app/share/bottles/bottles/backend/managers/dependency.py", line 148, in install
>     res = self.__perform_steps(config, step)
>   File "/app/share/bottles/bottles/backend/managers/dependency.py", line 278, in __perform_steps
>     self.__step_register_font(
>   File "/app/share/bottles/bottles/backend/managers/dependency.py", line 658, in __step_register_font
>     reg.add(
>   File "/app/share/bottles/bottles/backend/wine/reg.py", line 79, in add
>     logging.info(res, )
>   File "/app/share/bottles/bottles/backend/logger.py", line 69, in info
>     self.root.info(self.__color("info", message), )
>   File "/app/share/bottles/bottles/backend/logger.py", line 48, in __color
>     if message and "\n" in message:

**Comment by HubKing** [comment]
I changed Settings > Compatibility > Language from Japanese to System then tried again, and this time it said it succeeded, although the console printed errors like the same Wine could not open directory error, `002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
`, and  `reg: The file '/home/dog/.var/app/com.usebottles.bottles/data/bottles/temp/bulk_1676952587_EDG5A93R.reg' was not found.`

And, I don't know if this is because of the errors above, but Japanese text in an Windows app is still displayed as squares.

**Comment by csc-chicken** [comment]
@HubKing For me in 51.0 it's fixed. And seems like your issue in #2708 is fixed as well.

by the way, @StoneMoe discord?? Just curious what you do in discord server

**Comment by StoneMoe** [comment]
> by the way, @StoneMoe discord?? Just curious what you do in discord server

I do anything I can do :D
