### ISSUE TITLE
[Bug]: The Icon for the library is bugged for me

### ISSUE THREAD

**Issue by elmagio** [bottlesdevs/Bottles#2587]
### Describe the bug

It's a very minor issue, but the Library icon doesn't display properly for me, it looks like this: 
![Capture d’écran du 2023-01-20 11-39-55](https://user-images.githubusercontent.com/14126056/213676248-57fa0959-8188-4e04-addc-fbbade018524.png)

### To Reproduce

It has always been like that since the feature launched. Only thing of note is I was using the Library already when it was experimental.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-29-generic
Disk:
    Total: 8268873728
    Free: 8268726272
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 10.9GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
duplicate https://github.com/bottlesdevs/Bottles/issues/2399

**Comment by elmagio** [comment]
Ah, I didn't realize Bottles inherited that icon from Adwaita. Well, I'm not using KDE but I am using an icon theme (Qogir) which did not list Adwaita as a icon theme to inherit from, only hicolor. I added Adwaita and it fixed the issue. Thanks for the pointer !

**Comment by mirkobrombin** [comment]
yw
