### ISSUE TITLE
[Concept] Icon set for Programs and Bottles 

### ISSUE THREAD

**Issue by shuriken1812** [bottlesdevs/Bottles#260]
1.Shortcut/Menu Program icons - These can be a part of :)
https://github.com/bottlesdevs/programs  
@jannuary can maybe give a follow up on this. Thanks for the amazing bottles icon.

I really liked them, this makes the programs more tied up to the Bottles eco system !

![Battle net Launcher_bottles](https://user-images.githubusercontent.com/40650341/117173507-76ae0280-adea-11eb-9d31-e26f9d9848a0.png)
![EpicGamesLauncher_bottles](https://user-images.githubusercontent.com/40650341/117173530-7ca3e380-adea-11eb-83d9-0837da761274.png)

2. I tried some other stuff as well, maybe for in Bottles (in-app) - Ignore those bad crops I did this just as a prototype.

![bottles_redbottle_origin](https://user-images.githubusercontent.com/40650341/117173973-e9b77900-adea-11eb-8420-25ca10c0647e.png)
![bottles_Greenbottle_Battle net Launcher](https://user-images.githubusercontent.com/40650341/117173897-d6a4a900-adea-11eb-80f6-cea77ac5fde0.png)
![bottles_Orangebottle_EpicGamesLauncher](https://user-images.githubusercontent.com/40650341/117173792-c096e880-adea-11eb-9370-3905d13d382f.png)

3. I also tried this one, this doesn't make sense as an app is inside a Bottle not Bottles. but still part of my experiment :)

![Bottles_EpicGamesLauncher](https://user-images.githubusercontent.com/40650341/117174027-f4720e00-adea-11eb-9f92-7feb9f6c7e46.png)

**Comment by mirkobrombin** [comment]
We are discussing this in the telegram group

**Comment by Docmine17** [comment]
Shortcuts on the menu/desktop would be great

**Comment by mirkobrombin** [comment]
You can generate a desktop entry from the programs list but this is not implemented in Flatpak due the Sandbox.

**Comment by mpetuska** [comment]
@mirkobrombin does that mean that flatpak version will never be able to support menu shortcuts?

**Comment by mirkobrombin** [comment]
> @mirkobrombin does that mean that flatpak version will never be able to support menu shortcuts?

We are waiting the right portal which allow this.

**Comment by mirkobrombin** [comment]
No more planned. Thanks for the proposal.
