### ISSUE TITLE
Game Launchers issue in flatpak version.

### ISSUE THREAD

**Issue by Angraman** [bottlesdevs/Bottles#2602]
There are some games that have dedicated launchers.
Paradox Launcher for paradox games, or Distant Worlds 2 launcher for example.
They don't launch, while the games work by themselves  in flatpak version of bottles.
I assume this is container/isolation/sandboxing issue.
I'm looking for a workaround/setting, but can't find any.

**Comment by Kinsteen** [comment]
Please follow the issue template, and report logs about the games that don't work
