### ISSUE TITLE
[Bug]: Flatseal fails to see the icon

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2603]
### Describe the bug

When opening the Bottles entry in Flatseal, it fails to show the file:

![image](https://user-images.githubusercontent.com/50847364/213895145-27dce205-4c3c-4855-9e63-afb3400e7ec9.png)

### To Reproduce

1. Install Flatseal https://beta.flathub.org/apps/details/com.github.tchx84.Flatseal
2. Open and go to the Bottles entry

### Package

Flatpak from Flathub

### Distribution

Fedora 37 Silverblue

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.6-200.fc37.x86_64
Disk:
    Total: 4134936576
    Free: 4134776832
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 2.2GiB
Bottles_envs: null
```

### Additional context

Very likely a regression caused by https://github.com/bottlesdevs/Bottles/pull/2430

**Comment by B4rabbas** [comment]
Same for me.
