### ISSUE TITLE
[Bug]: Problem with flatpak sandbox?

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2608]
### Describe the bug

Stumbled upon an issue while testing the NVAPI fix. Trying to install this game https://portableapps.com/apps/games/big_solitaires_portable the installer assumes the Z: drive as default instead of the C: drive. When you add it manually to the program list it has this path: `/run/user/1000/doc/70f7a9b3/BigSolitairesPortable_1.4_Rev_3_English.paf.exe` which probably is flatpak sandbox or something like that.

### To Reproduce

1. Try to install the game from the BigSolitairesPortable_1.4_Rev_3_English.paf.exe
2. Add the installer to programs list
3. Restart Bottles (to make the location saved)
4. Click the "browse path" button for the new entry in programs list

### Package

Flatpak from GitHub Artifacts

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: 50.2-aac5407
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-58-generic
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.8GiB
Bottles_envs: null
```

### Additional context

Issue was found in this discussion:
https://github.com/bottlesdevs/Bottles/pull/2607#issuecomment-1399537101

**Comment by Kinsteen** [comment]
For this, you should give access to the path you're trying to use, like this: https://docs.usebottles.com/flatpak/expose-directories

**Comment by MrQuerter** [comment]
You see, the point of this problem is that the installer is already in location that should be exposed to Bottles. I use Bottles for quite some time now. Started when there was a problem with installers that use more than the .exe file so I always place the installers in `.var/app/com.usebottles.bottles/data/bottles/bottles/bottlenamehere/drive_c` meaning this should not be a problem. Also, adding anything to program list shouldn't result in the program having the `/run/user/` location.

**Comment by 2ndBillGates** [comment]
> hould not be a



> You see, the point of this problem is that the installer is already in location that should be exposed to Bottles. I use Bottles for quite some time now. Started when there was a problem with installers that use more than the .exe file so I always place the installers in `.var/app/com.usebottles.bottles/data/bottles/bottles/bottlenamehere/drive_c` meaning this should not be a problem. Also, adding anything to program list shouldn't result in the program having the `/run/user/` location.

I've the same issue when installing LOL on my bottles (flatpak).
The installer complained not enough space for C: drive


I had to change Bottles default location from preference and recreate a bottle.

**Comment by MrQuerter** [comment]
After reading https://github.com/bottlesdevs/Bottles/issues/2635 I have downgraded my Bottles to 50.1 and tested the same steps as in my first post here.
50.1 worked without problems as expected. This time I didn't have problems with NVAPI so I could test 50.2 and it also worked without problems which surprised me. At the end I decided to return to the dev version again just to check if it's still valid and yes, the issue is still here.

https://github.com/bottlesdevs/Bottles/actions/runs/3980083973
I used this github action so the problem should be somewhere between 50.2 and this dev version? If not maybe it's because of other branch and it's permissions when you install it? Everything else is exactly the same.
```
Permissions com.usebottles.bottles:
    ipc                network            pulseaudio                wayland
    x11                devices            devel                     multiarch
    per-app-dev-shm    file access [1]    system dbus access [2]

    [1] xdg-download
    [2] org.freedesktop.UDisks2
```
After installing:
```
Bottles    com.usebottles.bottles    50.2    master    bottles-origin    system
Bottles    com.usebottles.bottles    50.2    stable    flathub           system
```

**Comment by TheEvilSkeleton** [comment]
Oddly enough, I tried on 2022-12-17 and 2022.11.14. I was able to reproduce the same issue of https://github.com/bottlesdevs/Bottles/issues/2635 on both.

**Comment by MrQuerter** [comment]
Yes, I know. That's why I decided to test it again. I never had troubles with Unity games in Bottles so didn't bother testing that game.

**Comment by MrQuerter** [comment]
Should I close this issue? It only happens on version from github artifacts so I'm not sure if it's something that can be fixed or even if it does matter since most people will only ever use the flathub version.

**Comment by TheEvilSkeleton** [comment]
Yeah, closing it should be fine. Thanks.
