### ISSUE TITLE
[Bug]: Program location doesn't work until Bottles restart

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/Bottles#2609]
### Describe the bug

(I currently use the version from github artifacts but I know it is also present in normal one since quite some time)

When you add anything to the programs list manually you need to restart Bottles to make the "Browse path" button work. It was like that for quite some time, but wasn't a big deal since you could always just restart Bottles to make it work and it takes like 10 seconds max.

It seems like Bottles saves the info at first to some temp place and when you close it it saves to the correct file (at least if we're speaking about manually added programs since the automatic ones are always hidden from bottle.yml)

### To Reproduce

1. Add anything to programs list manually
2. Try to "browse path"
3. Restart Bottles
4. Try "browse path" button again

### Package

Flatpak from GitHub Artifacts

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: 50.2-aac5407
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-58-generic
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.8GiB
Bottles_envs: null
```

**Comment by MrQuerter** [comment]
Here are logs from the terminal when you click the "browse path" button without restarting Bottles:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 282, in browse_program_folder
    custom_path=self.program["folder"]
KeyError: 'folder'
```

**Comment by Kinsteen** [comment]
I've successfully reproduced the bug, but I'm not sure what's the best way to fix this. It will eventually get fixed, thanks for you report!
I'm keeping this open so we can have a trace of this, until someone wants to tackle the task.

**Comment by Qronikarz** [comment]
Don't know when it happened, but fixed now.
