### ISSUE TITLE
Error: Failed to connect to mirror.usebottles.com... when trying to use Bottles after a fresh install.

### ISSUE THREAD

**Issue by lemon-sh** [bottlesdevs/Bottles#2624]
### Prerequisites

- [x] I am sure that this problem has NEVER been discussed in [other issues](https://github.com/bottlesdevs/Bottles/issues).

### What happened

I've installed Bottles on my computer (Arch Linux x64), but when I try to click "Continue" on the setup screen, a progress bar appears for a brief period of time and then disappears. The logs when I start the app mention:
```
17:39:49 (ERROR) Could not get index for components repository: (28, "Failed to connect to mirror.usebottles.com port 443 after 5160 ms: Couldn't connect to server") 
17:39:49 (ERROR) Could not get index for components repository 
17:39:54 (ERROR) Could not get index for dependencies repository: (28, "Failed to connect to mirror.usebottles.com port 443 after 5156 ms: Couldn't connect to server") 
17:39:54 (ERROR) Could not get index for dependencies repository
```

### What you expected to happen

I expected Bottles to download the components.

### How to reproduce it

Do a fresh install of Bottles and try to get past the welcome screen.

### Ping proxy.usebottles.com

```log
PING proxy.usebottles.com (172.67.153.15) 56(84) bytes of data.
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=1 ttl=58 time=18.6 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=2 ttl=58 time=14.4 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=3 ttl=58 time=13.4 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=4 ttl=58 time=11.6 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=5 ttl=58 time=10.4 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=6 ttl=58 time=12.2 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=7 ttl=58 time=13.8 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=8 ttl=58 time=9.20 ms

--- proxy.usebottles.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7012ms
rtt min/avg/max/mdev = 9.197/12.947/18.611/2.687 ms

```
### Dig proxy.usebottles.com

```log
; <<>> DiG 9.18.10 <<>> proxy.usebottles.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3134
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;proxy.usebottles.com.		IN	A

;; ANSWER SECTION:
proxy.usebottles.com.	148	IN	A	172.67.153.15
proxy.usebottles.com.	148	IN	A	104.21.40.150

;; Query time: 16 msec
;; SERVER: 62.179.1.61#53(62.179.1.61) (UDP)
;; WHEN: Thu Jan 26 17:37:40 CET 2023
;; MSG SIZE  rcvd: 81
```

### Your Internet Service Provider (ISP) name

UPC (Liberty Global)

### Your Country/Area

Poland

### Anything else we need to know

* I tried relaunching the app many times, which led to a successful install of a few components (latencyflex, nvapi and vkd3d), but not any runners or dxvk.
* I can load the directory listing on the mirror in my browser just fine, but it takes some time. I suspect the low timeout of around 5s could be the culprit here, apart from the mirror responding slowly.

**Comment by lemon-sh** [comment]
I've remoted into my server hosted at Alwyzon and from there I can access the mirror just fine. Looks like a routing issue.

**Comment by gioan777** [comment]
I had a somewhat similar issue with connecting to bottles servers, including pinging the servers resolving the servers manually, but for some reason bottles itself couldn't connect the servers. In my case this was [solved by changing my DNS to IPv4](https://github.com/bottlesdevs/Bottles/issues/2421#issuecomment-1401800281).

**Comment by francescomasala** [comment]
I'll recheck the DNS Entries on Cloudflare!

I'll keep everyone updated

**Comment by lemon-sh** [comment]
I figured a traceroute might be useful.
This is `mtr` running on my PC (no reply):
![image](https://user-images.githubusercontent.com/26277478/215083413-5ba61572-735f-4365-83be-cf0eaac45b33.png)
And on my Alwyzon server I've mentioned earlier (replies fine):
![image](https://user-images.githubusercontent.com/26277478/215083716-c4c833c1-8a90-4129-9767-bd0dd942b0c7.png)
So I don't think this is a DNS issue. I'm fairly certain this is a routing problem, whether it's on my ISP's side or the CDN's is the question.

**Comment by francescomasala** [comment]
We are trying to add new nodes to our infra, maybe that can fix a couple of things

**Comment by lemon-sh** [comment]
![image](https://user-images.githubusercontent.com/26277478/216837093-e2b932cb-fc4d-45ef-b0f6-a052b6570aa7.png)
The issue seems to be fixed, at least temporarily.

**Comment by francescomasala** [comment]
Fantastic! We have moved the main mirror to a new server

**Comment by francescomasala** [comment]
Any news?

**Comment by lemon-sh** [comment]
It worked for quite some time (like, 2 weeks) but recently I've been randomly coming across this issue again. Basically, sometimes I can connect and sometimes I can't. I will keep you updated if I find out anything else about this.

**Comment by lemon-sh** [comment]
I've been using Bottles with zero issues for the last month, so I think the issue has been solved. Huge thanks!

**Comment by francescomasala** [comment]
> I've been using Bottles with zero issues for the last month, so I think the issue has been solved. Huge thanks!

Perfect!

**Comment by francescomasala** [comment]
@gxtu Hi, I was updating the server, try it now!
