### ISSUE TITLE
[Bug]: Bottles GUI is missing Letters

### ISSUE THREAD

**Issue by Berinkton** [bottlesdevs/Bottles#2626]
### Temporary Workaround

Quoting from Flatpak Matrix:

> okay everyone, as a temporary workaround, you can rollback the org.freedesktop.Platform.GL.default//22.08-extra extension with:
> ```
> sudo flatpak update --commit=4c6ff4f8c2418f647a814fd14d8c7500d1de7bfd14f10c192eb96a9f638762cf org.freedesktop.Platform.GL.default//22.08-extra
> ```
> or, if you have org.freedesktop.Platform.GL.default//22.08 installed, with:
> ```
> sudo flatpak update --commit=bf66cf0adc4293974c628834984b689549fb0906036f6af7bbc62f4d458d516a org.freedesktop.Platform.GL.default//22.08
> ```
> 
> if in doubt, try both. they're harmless

To add more, if you installed flatpaks with `--user`, then omit `sudo` and add `--user`.

### Describe the bug

I installed Debian 11 with KDE Plasma on my new NVMe SSD. Then i updated the Kernel to the version 6.0 so i can use my AMD RX 6950 XT.
I installed flatpak and the Discover - Flatpak backend.
After installing Bottles i noticed a graphical issue i had not seen on my previous Debian 11 install i used a few days ago.
The text in the GUI is unreadable. There are a bunch of Letters missing and i need to guess where the menu button is to open the preferences menu.

I installed kernel version 6.1.0-2-amd64 so i can play Cyberpunk 2077 just FYI.

### To Reproduce

1. Install Debian 11 with KDE Plasma and Kernel version 6.0.0-0.deb11.6-amd64
2. Install flapak with Discover - Flatpak backend
3. Restart System
4. Install Bottles via Discover
5. Launch Bottles

### Package

Flatpak from Flathub

### Distribution

Debian 11.6

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-2-amd64
Disk:
    Total: 16789069824
    Free: 16788922368
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(process:2): Gtk-CRITICAL **: 17:57:10.482: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:2): Gtk-CRITICAL **: 17:57:10.482: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed

(bottles:2): Gtk-CRITICAL **: 17:57:10.500: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(bottles:2): Gtk-CRITICAL **: 17:57:10.500: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/main.py", line 188, in do_command_line
    self.do_activate()
  File "/app/share/bottles/bottles/frontend/main.py", line 231, in do_activate
    win = MainWindow(
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 78, in __init__
    super().__init__(**kwargs)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

### Additional context

I also checked in `journalctl -r` and found this.
```
Jan 27 18:00:26 debian-797cc6 xdg-desktop-por[2307]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/portal/desktop/session/1_159/gtk804011485'
Jan 27 18:00:26 debian-797cc6 xdg-desktop-por[2307]: A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'CreateMonitor' in interface 'org.freedesktop.impl.portal.Inhibit' at object path '/org/freedesktop/portal/desktop' (signature 'ooss')
Jan 27 18:00:25 debian-797cc6 systemd[1067]: app-com.usebottles.bottles-9e4c1f2408854329a63bc68fc65a6267.scope: Succeeded.
Jan 27 18:00:25 debian-797cc6 systemd[1067]: Started app-flatpak-com.usebottles.bottles-10953.scope.
Jan 27 18:00:25 debian-797cc6 systemd[1067]: Started Bottles.
```

**Comment by jannuary** [comment]
Given how GTK completely fails, I'm more inclined to assume your system is broken.

Do any other GTK4 apps work?

**Comment by gam3boy1** [comment]
I can confirm that this issue is present on the steam deck as well
![image](https://user-images.githubusercontent.com/22109624/215158282-69db4276-d07e-41ad-8433-41f9003bbb0a.png)

**Comment by jleonardfl** [comment]
I just updated flatpaks through discover on my steam deck and I have the same issue.  
<details>
    <summary> flatpak info </summary>
    
     (deck@steamdeck ~)$ flatpak info com.usebottles.bottles
 
    Bottles - Run Windows Software
 
          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 50.2
     License: GPL-3.0-only
      Origin: flathub
    Collection: org.flathub.Stable
    Installation: system
     Installed: 472.4 MB
       Runtime: org.gnome.Platform/x86_64/43
          Sdk: org.gnome.Sdk/x86_64/43
 
      Commit: cd1ba2d77ded5ad6f72ed3656638eff26f24634aa287e1e5d383e5c025e71434
      Parent: 07e77331e1648d7ef1c80e80bf4f8eb4f12f31043a3d77231aba3939dfb6c302
     Subject: 50.2 (d0cbdad8)
        Date: 2023-01-18 10:33:17 +0000
</details>

<details>
    <summary> bottles log </summary>

(deck@steamdeck ~)$ flatpak run -v com.usebottles.bottles
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/ff25bb0c5f8225e73b43cf40669f5935f68bbde67b00871e13f6c1261d6dc966/files/lib32 does not exist
F: Cleaning up unused container id 1310553744
F: Cleaning up per-app-ID state for com.usebottles.bottles
F: Allocated instance id 836687486
F: Add defaults in dir /com/usebottles/bottles/
F: Add locks in dir /com/usebottles/bottles/
F: Allowing host-fs access
F: ignoring blocking autofs path /efi
F: ignoring blocking autofs path /esp
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/deck/.config/pulse/client.conf': Error opening file /home/deck/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 43 xdg-dbus-proxy --args=45'
F: Running 'bwrap --args 43 bottles'
12:49:28 (INFO) Bottles Started! 
12:49:33 (INFO) Performing Bottles checks… 
12:49:33 (INFO) Dxvks found:
         - dxvk-1.10.3
 
12:49:33 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
 
12:49:33 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
12:49:33 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
12:49:33 (INFO) Runners found:
         - sys-wine-7.0.1
         - GE-Proton7-28
         - vaniglia-7.15
         - wine-ge-7-27
         - caffe-7.15
         - soda-7.0-3
 
12:49:33 (INFO) Bottles found:
         - Vortex
         - Battlenet
         - Mod Manager
 

(bottles:2): Gtk-CRITICAL **: 12:49:33.272: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
12:49:33 (INFO) Library saved 
12:49:33 (INFO) Catalog installers loaded 
12:49:33 (INFO) Catalog dependencies loaded 
12:49:33 (INFO) Catalog components loaded 

</details>

**Comment by Kinsteen** [comment]
Did this issue occur on previous versions of Bottles? Was there something else that was updated that could cause this problem?

**Comment by gam3boy1** [comment]
idk - this is the first time im installing this app. how can I download an older version of this app so that I can use it?

**Comment by TheEvilSkeleton** [comment]
FYI, this isn't a Bottles bug, nor a system bug. This is a bug with one of Freedesktop runtimes.

**Comment by Adi-ionut** [comment]
I have this problem too, but will almost all flatpaks not just bottles. Something is broke on the flatpak side.

**Comment by TheEvilSkeleton** [comment]
Your distribution might have a package available, but we won't really support it.

**Comment by gam3boy1** [comment]
wdym? Are you suggesting I get an older version of flatpak and install bottles from there?

**Comment by Kinsteen** [comment]
That probably won't work either. The best way is to wait for a fix from Flatpak side

**Comment by gam3boy1** [comment]
Any idea when a new update will arrive?

**Comment by dwebim** [comment]
I just did I fresh install of Fedora and I'm having the same issue with missing letters in Bottles, which wasn't happening on my old install yesterday. I would just install the one from Fedora repos, but for some reason that one gets stuck indefinitely on "We need a few more minutes to set everything up...".

**Comment by Kinsteen** [comment]
@gam3boy1 It depends, we're not devs of Flatpak

@dwebim Please read the thread. Also, the version from Fedora repos is severely outdated and will not work anymore

**Comment by TheEvilSkeleton** [comment]
> Any idea when a new update will arrive?

Unfortunately, no. All I know is that they're still investigating it. If you're interested, you can read the chat at [#flatpak:matrix.org](https://matrix.to/#/#flatpak:matrix.org)

**Comment by dwebim** [comment]
@Kinsteen I'm aware that non-flatpak packages are unsupported. I was mentioning that the (presumably) same version of Bottles I was using yesterday now exhibits this bug.

**Comment by TheEvilSkeleton** [comment]
Alright, so we found a temporary workaround to get it working again.

You'll have to use the terminal to downgrade a package to a specific commit.

```
sudo flatpak update --commit=4c6ff4f8c2418f647a814fd14d8c7500d1de7bfd14f10c192eb96a9f638762cf org.freedesktop.Platform.GL.default//22.08-extra
```

If you installed everything using `--user`, then run the command without `sudo` but with `--user.`

Unfortunately, I don't know when this will be resolved.

**Comment by farribeiro** [comment]
@Kinsteen Fedora packager is Retiring Bottles https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VJNMRCJBEBYDPA6P3HTUCNCYRY5HOYTX/

**Comment by TheEvilSkeleton** [comment]
Alright, this was resolved by the Flathub maintainers. I'm closing this issue.

**Comment by gam3boy1** [comment]
@TheEvilSkeleton worked like a charm! Thanks for the help!
