### ISSUE TITLE
[Bug]: Some letters don't render

### ISSUE THREAD

**Issue by FriederHannenheim** [bottlesdevs/Bottles#2627]
### Describe the bug

I installed Bottles from Flatpak and some letters don't render. It looks like this:
![Screenshot from 2023-01-27 21-23-23](https://user-images.githubusercontent.com/41985738/215190152-3fee8582-60a3-4a74-b9c9-e6424502d276.png)
![Screenshot from 2023-01-27 21-23-43](https://user-images.githubusercontent.com/41985738/215190155-6437cf17-83ec-423d-94fa-baaee3456718.png)

### To Reproduce

1. Install Bottles from Flatpak
2. Run

### Package

Flatpak from Flathub

### Distribution

Fedora 37

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.7-200.fc37.x86_64
Disk:
    Total: 8300707840
    Free: 8300560384
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.2GiB
Bottles_envs: null
```

**Comment by Kinsteen** [comment]
Duplicate, see here for a workaround: https://github.com/bottlesdevs/Bottles/issues/2626
