### ISSUE TITLE
[Request]: Add D8VK support

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2641]
### Tell us the problem or your need

Currently, there is no way to run Direct3D 8 titles on Vulkan on Bottles.

### Describe the solution you'd like

I'd like to propose integrating D8VK. I don't really know much about it, but we could use it and make it available for those who want to play Direct3D 8 on Vulkan.

### Additional context and references

Project: https://github.com/AlpyneDreams/d8vk

**Comment by Blisto91** [comment]
oho
https://github.com/AlpyneDreams/d8vk/commit/b3fb153dc5d3201e6c860a676ec5d53f7ac9ab3d

**Comment by AlpyneDreams** [comment]
> It might be a good idea to wait until [AlpyneDreams/d8vk#19](https://github.com/AlpyneDreams/d8vk/issues/19) have been solved.

This has been solved now and the next release will only require one DLL.

> https://github.com/crosire/d3d8to9 ?

See https://github.com/AlpyneDreams/d8vk/issues/114 for discussion about the differences between the two projects. d8vk is more Linux and Wine oriented. There are still some cases where d8vk has issues and d3d8to9 might be good to provide as a backup option.

**Comment by AlpyneDreams** [comment]
The next release, [version 1.0](https://github.com/AlpyneDreams/d8vk/releases/tag/d8vk-v1.0) is out! You only need one `d3d8.dll` now, so now would probably be a good time to add it to Bottles.

**Comment by Kinsteen** [comment]
Well done on this release! I agree it would be great to have. It does require a bit of work to make it available to Bottles users on our side, and I may be able to do that in the next few days :)

**Comment by AlpyneDreams** [comment]
I am pleased to report that d8vk has been upstreamed to dxvk. (doitsujin/dxvk#3411). This means that the next release of DXVK will support D3D8. This means d8vk has been merged into dxvk. So for the next dxvk release, Bottles can probably just update [dxvk.py](https://github.com/bottlesdevs/Bottles/blob/540f6fc0d4c2853e2a62cab98548ce3210c7352a/bottles/backend/dlls/dxvk.py) to also copy `d3d8.dll`  and update the description of dxvk in the UI to include Direct3D 8.
