### ISSUE TITLE
[Bug]: Included Wine tools bugs

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/Bottles#2642]
### Describe the bug

When looking for things that give output in terminal when you run Bottles from it I found few bugs(?) in some included programs.
1. Command Line
![cmd](https://user-images.githubusercontent.com/84787215/215668109-b9f4d8c1-d914-4048-9e29-5eeb4241c0eb.png)
2. Debugger
![dbg](https://user-images.githubusercontent.com/84787215/215668152-01181ecc-e80e-4815-b70b-7fceefb1277b.png)
Both command line and debugger have this very weird looking letter spacing and they give similar "errors" in the terminal
3. Uninstaller
![unin](https://user-images.githubusercontent.com/84787215/215668205-1b92b0d5-c643-40e9-abde-aceff7c15196.png)
Uninstaller straight up crashes with Wine bug window. It even caused my Cinnamon to restart (memory leak "protection")

I posted the outputs from terminal in the section below.

### To Reproduce

1. Launch Bottles from terminal.
2. Open any bottle
3. Click on "command line"
4. Click on "debugger"
5. Click on "Uninstaller"

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-58-generic
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.8GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
05:36:08 (INFO) Using Wine Command Line -- launch_terminal 
Gtk-Message: 05:36:08.845: Failed to load module "xapp-gtk3-module"

(easyterm.py:120): VTE-WARNING **: 05:36:08.931: (../src/vtepty.cc:811):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)


05:36:47 (INFO) Using Wine debug tool -- launch_terminal 
Gtk-Message: 05:36:48.053: Failed to load module "xapp-gtk3-module"

(easyterm.py:310): VTE-WARNING **: 05:36:48.139: (../src/vtepty.cc:811):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)


05:36:59 (INFO) Using Wine Uninstaller -- launch 
wine: Unhandled page fault on read access to 0000000000000002 at address 00000002FB439334 (thread 01f0), starting debugger...
0218:err:ole:CoUninitialize Mismatched CoUninitialize
```

**Comment by bogiord** [comment]
I'm seeing the same issues with the command line and the debugger, but the uninstaller works fine here.

Additional data: 
- also on Mint 21.1
- sys-wine-8.0 runner 
- 4k monitor with 2x scaling
- both tools run normally if started from bash run inside the sandbox (they both issue the error about C:\\windows\\system32\\winemenubuilder.exe, but start nonetheless).

**Comment by MrQuerter** [comment]
Yes I can confirm, uninstaller with sys-wine-8.0 works. So, it also uses runners... Whatever, at least it works.

**Comment by Qronikarz** [comment]
(Mint 21.3 + Bottles 51.11)
Command line and Debugger don't have the issue with font spacing anymore and Uninstaller works.
