### ISSUE TITLE
[Bug]: New update breaks Ubisoft Connect (Curated Program)

### ISSUE THREAD

**Issue by FishBulbish** [bottlesdevs/Bottles#2648]
### Describe the bug

Once Ubisoft Connect is installed on a clean Gaming Bottle with no tweaks applied, it initially starts, and receives a 181 mb patch, the program successfully initializes after the patch has been applied, however it crashes soon after, giving the following error message

![image](https://user-images.githubusercontent.com/88989413/216118657-31e1a814-280e-46c2-ba7c-557855a1f56a.png)

I was able to recreate the issue with the following forks of wine:

Soda 7.0-8, ge-proton7-35, and Caffe-7.20

All other settings being gaming defaults

### To Reproduce

1. Create a new gaming bottle
2. Head to the installers menu, and install the Ubisoft Connect Package
3. Click on the new program's run button
4. Wait for error to naturally occur

### Package

Flatpak from Flathub

### Distribution

Endeavour OS (Arch)

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-85-05/extra/nvidia/wine
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.1.8-zen1-1-zen
Disk:
    Total: 8048291840
    Free: 8048128000
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Additional context

Running the program via Xwayland due to issues with wine and wayland touch gestures, these are upstream issues, and they have already been reported

**Comment by FishBulbish** [comment]
Accidentally closed issue

**Comment by MrQuerter** [comment]
It may not be Bottles fault.
https://www.gamingonlinux.com/2023/02/ubisoft-broke-their-games-on-linux-desktop-and-steam-deck
Issue is said to be fixed on Proton Experimental.

**Comment by Blisto91** [comment]
Yes Proton experimental have received a different workaround (from the previous workaround)
https://github.com/ValveSoftware/wine/commit/ae2fad7338cc2f914536469656448ecb5fdcf294

**Comment by gegoxaren** [comment]
Ok, I got it working.

What you need to do is copy the `kernelbase.dll` and `kernel32.dll` from Proton Experimental Bleeding Edge. You need to copy both the 32bit version and the 64bit version.

Folders to look for the files:
`/Proton - Experimental/files/lib/wine/i386-windows/`
and
`Proton - Experimental/files/lib64/wine/x86_64-windows/`

I made a copy of a wine-pronon-ge version and pasted them in the correct place, and it works.

Have fun!

**Comment by wxlfsangel** [comment]
> Ok, I got it working.
> 
> What you need to do is copy the `kernelbase.dll` and `kernel32.dll` from Proton Experimental Bleeding Edge. You need to copy both the 32bit version and the 64bit version.
> 
> Folders to look for the files: `/Proton - Experimental/files/lib/wine/i386-windows/` and `Proton - Experimental/files/lib64/wine/x86_64-windows/`
> 
> I made a copy of a wine-pronon-ge version and pasted them in the correct place, and it works.
> 
> Have fun!

Any specific version of Wine-proton-ge? i tried doing the same but now the wine terminal throws out "Could not load kernel32.dll, status c000007b" twice. I did it to a GE-Proton7-48 prefix

**Comment by gegoxaren** [comment]
> > Ok, I got it working.
> > What you need to do is copy the `kernelbase.dll` and `kernel32.dll` from Proton Experimental Bleeding Edge. You need to copy both the 32bit version and the 64bit version.
> > Folders to look for the files: `/Proton - Experimental/files/lib/wine/i386-windows/` and `Proton - Experimental/files/lib64/wine/x86_64-windows/`
> > I made a copy of a wine-pronon-ge version and pasted them in the correct place, and it works.
> > Have fun!
> 
> Any specific version of Wine-proton-ge? i tried doing the same but now the wine terminal throws out "Could not load kernel32.dll, status c000007b" twice. I did it to a GE-Proton7-48 prefix

I'm using this: https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-36

**Comment by wxlfsangel** [comment]
> > > Ok, I got it working.
> > > What you need to do is copy the `kernelbase.dll` and `kernel32.dll` from Proton Experimental Bleeding Edge. You need to copy both the 32bit version and the 64bit version.
> > > Folders to look for the files: `/Proton - Experimental/files/lib/wine/i386-windows/` and `Proton - Experimental/files/lib64/wine/x86_64-windows/`
> > > I made a copy of a wine-pronon-ge version and pasted them in the correct place, and it works.
> > > Have fun!
> > 
> > 
> > Any specific version of Wine-proton-ge? i tried doing the same but now the wine terminal throws out "Could not load kernel32.dll, status c000007b" twice. I did it to a GE-Proton7-48 prefix
> 
> I'm using this: https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-36
> 
> It's not Steam Proton, this is without the Steam specific patches.
> 
> Also, did you put it in the same directory as you got them from? (ie: i386 to i386, and x86_64 to x86_64 ) If not... Then it will not work.

Didn't put them in the same folder! For some reason i went into the wine prefix i was using and into system32 and syswow64 since its where i was finding those two files to replace, but lo and behold theres actually the same folder structure for GE-Proton if i go into .local/share/lutris/wine/runners or in the case of bottles .var/app/com.usebottles.bottles/data/bottles/runners . Placed those now in the proper folders and Ubisoft Connect starts without issue. Thank you for the help

**Comment by Blisto91** [comment]
The workaround have also been added to proton next (7.0-6)

Once the bottle devs release a new soda version it should get pulled in.

**Comment by mirkobrombin** [comment]
Soda 7.0-9 released. Will be available soon.

**Comment by CannonFather** [comment]
While connect works (though sometimes i get a Uplay-webcore mscvrt.dll error, doesn't crash connect), I can't play Farcry 4 anymore when I used to have no issues running either. Tried various runners same error. If anyone else has this issue and/or fixed it, please let me know.
[backtrace.txt](https://github.com/bottlesdevs/Bottles/files/10739901/backtrace.txt)
[Wbcorebacktrace.txt](https://github.com/bottlesdevs/Bottles/files/10739902/Wbcorebacktrace.txt)

Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  TUF GAMING X570-PLUS (WI-FI)
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 5950X 16-Core Processor            
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  5980 Mhz
    32 logical processors
    16 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Pop!_OS 22.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.0.12-76060006-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101003
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20221019.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 525.85.05
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x2208
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3440 x 1440
    Desktop Resolution: 3440 x 1440
    Primary Display Size: 31.50" x 13.19" (34.13" diag)
                                            80.0cm x 33.5cm (86.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 12288 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 9a HDMI/DP

Memory:
    RAM:  32009 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Total Hard Disk Space Available:  949739 MB
    Largest Free Hard Disk Block:  272296 MB

Storage:
    Number of SSDs: 3
    SSD sizes: 2000G,1024G,1000G
    Number of HDDs: 0
