### ISSUE TITLE
[Bug]: Multifile gog installers, not works correctly with non casual folders(other than Downloads, Pictures etc.)

### ISSUE THREAD

**Issue by qarmin** [bottlesdevs/Bottles#2653]
### Describe the bug

When running Gog installer from e.g. `/home/user/Game/installer.exe` path, that is created with more than one file(e.g. Bioshock - `setup_bioshock_remastered_1.0.122872_(25715).exe`, `setup_bioshock_remastered_1.0.122872_(25715)-1.bin`, `setup_bioshock_remastered_1.0.122872_(25715)-2.bin`, `setup_bioshock_remastered_1.0.122872_(25715)-3.bin`, `setup_bioshock_remastered_1.0.122872_(25715)-4.bin`), the installer after choosing language, shows dialog that cannot find `.bin` files

![Screenshot from 2023-02-05 10-20-11](https://user-images.githubusercontent.com/41945903/216811496-a75341b7-d52e-4e7b-a3f3-2f0291fcd0ed.png)

Tested on Bioshock Infinite, Bioshock 1 Remastered but also happens with other multi file installers

As workaround I put files into `/home/user/Downloads` instead `/home/user/Game` and then installer properly runs, but this is really annoying to copy every multi file installer to certain location.

### To Reproduce

- Create empty bottle
- Put gog installation exe(with also bin files together - problem not happens with only one exe file) inside `/home/user/Game/` folder
- Open this file via "Run Executable..."
- Choose language
- Dialog shows with "Installer needs next disk - Please insert disk 4 and click ok"

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Debugging Information

```shell
Official Package: true
Version: '50.1'
DE/WM: ubuntu-xorg
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-29-generic
Disk:
    Total: 12562386944
    Free: 12562239488
RAM:
    MemTotal: 23.4GiB
    MemAvailable: 18.1GiB
Bottles_envs: null
```

**Comment by jannuary** [comment]
Not something we can fix at the moment — that needs to happen on xdg-desktop-portal side. As a workaround, you might want to grant permissions to ~/Game with Flatseal.
