### ISSUE TITLE
Endless loop of installing runtime on fedora 37

### ISSUE THREAD

**Issue by katepavel** [bottlesdevs/Bottles#2664]
steps to reproduce:
- install Fedora 37
- install bottles (rpm version)
- launch

`[kate@slate-lin ~]$ bottles

(process:9305): Adwaita-WARNING **: 21:00:26.331: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
21:00:26 (INFO) Bottles Started! 
21:00:27 (INFO) Catalog components loaded 
21:00:27 (INFO) Catalog installers loaded 
21:00:28 (INFO) Catalog dependencies loaded 
21:00:28 (INFO) Performing Bottles checks… 
21:00:28 (INFO) Dxvks found:
         - dxvk-2.0
 
21:00:28 (INFO) Vkd3ds found:
         - vkd3d-proton-2.7
 
21:00:28 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
21:00:28 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
21:00:28 (INFO) Library saved 
21:00:33 (INFO) Performing Bottles checks… 
21:00:33 (INFO) Dxvks found:
         - dxvk-2.0
 
21:00:33 (INFO) Vkd3ds found:
         - vkd3d-proton-2.7
 
21:00:33 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
21:00:33 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
21:00:33 (WARNING) No runtime found. 
21:00:34 (INFO) Installing component: [runtime-0.5]. 
runtime.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (16.2MiB/16.2MiB - 11.6MiB)

21:00:36 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz]. 
21:00:36 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
21:00:36 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [c68c5c8df840a5c70bcfec32514e3af0] 
21:00:36 (ERROR) Removing corrupted file [runtime.tar.gz]. 
21:00:36 (ERROR) Extraction failed! Archive ends earlier than expected. 
21:00:36 (WARNING) No runtime found. 
21:00:36 (INFO) Installing component: [runtime-0.5]. 
runtime.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (16.2MiB/16.2MiB - 11.7MiB)

21:00:38 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz]. 
21:00:38 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
21:00:38 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [c68c5c8df840a5c70bcfec32514e3af0] 
21:00:38 (ERROR) Removing corrupted file [runtime.tar.gz]. 
21:00:38 (ERROR) Extraction failed! Archive ends earlier than expected. 
21:00:38 (WARNING) No runtime found. 
21:00:38 (INFO) Installing component: [runtime-0.5]. 
runtime.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (16.2MiB/16.2MiB - 11.3MiB)

21:00:40 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz]. 
21:00:40 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
21:00:40 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [c68c5c8df840a5c70bcfec32514e3af0] 
21:00:40 (ERROR) Removing corrupted file [runtime.tar.gz]. 
21:00:40 (ERROR) Extraction failed! Archive ends earlier than expected. 
21:00:40 (WARNING) No runtime found. 
21:00:40 (INFO) Installing component: [runtime-0.5]. 
^C
`

**Comment by Kinsteen** [comment]
Fedora package is not supported and is several month old, please update to latest Flatpak
