### ISSUE TITLE
[Crash report]  list indices must be integers 

### ISSUE THREAD

**Issue by turtle72** [bottlesdevs/Bottles#2685]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.8.28-brescia-2

**Log**
```python3
list indices must be integers or slices, not str  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1306, in create_bottle
    self.install_dll_component(config, "dxvk", version=dxvk_name)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1496, in install_dll_component
    manager = DXVKComponent(_version)

  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 39, in __init__
    self.check()

  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 56, in check
    del found[path][dll]

```

**Comment by turtle72** [comment]
I updated it with flatpak update and still get the error, any better ways I should do it?

**Comment by Kinsteen** [comment]
Uninstall the Bottles package from Fedora, you are probably not running the flatpak version

**Comment by turtle72** [comment]
I didn't install it with Fedora, I only did it with flatpak

**Comment by Kinsteen** [comment]
Then it is not up to date, the version you reported is 5 months old, and there was around 10 versions in between

**Comment by turtle72** [comment]
The most up to date version I could find is 2022.8.28-brescia-2. Should I compile the source code myself to get a more up to date version or is there a pre-compiled more up to date version? Im finding the versions at [https://docs.usebottles.com/getting-started/installation](url) and the beta tab.

**Comment by Kinsteen** [comment]
Ah I see! The flatpak beta branch is deprecated, it is not up to date. You should switch to stable, sorry for the confusion. I forgot that Beta was still a thing

**Comment by turtle72** [comment]
Thanks for the help!
