### ISSUE TITLE
[Bug]: Program rename bug(s)

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2692]
### Describe the bug

I noticed that renaming programs gives wrong text notification at the bottom. Also while looking terminal has any clue I noticed a Gtk-CRITICAL error that shows on every click of rename button.

The notification text is wrong because it shows the rename twice and doesn't show how it was named before:
![rename](https://user-images.githubusercontent.com/84787215/219882290-a9db9df2-29f5-4154-b9d1-cc3f34173e94.png)

Gtk-CRITICAL error will be posted in later section.

### To Reproduce

1. Launch bottles from terminal
2. Install anything so it appears in programs list (for example notepad)
3. Rename the program/game

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-60-generic
Disk:
    Total: 8321306624
    Free: 8321155072
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 12.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(bottles:2): Gtk-CRITICAL **: 19:19:52.269: gtk_widget_add_controller: assertion 'gtk_event_controller_get_widget (controller) == NULL' failed
```

**Comment by TheEvilSkeleton** [comment]
Thanks! This was fixed in https://github.com/bottlesdevs/Bottles/commit/988298159dcafff2c5d7d02e2ef02ada0d49d6e3.
