### ISSUE TITLE
[Bug]: "Working Directory" & "Post-run Script" buttons don't work

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2693]
### Describe the bug

While looking yet again at bottle.yml to discover how it works I noticed some programs (at least the ones that actually show in it) have `script: ''` and some of them have `script: null`. I tried to put some basic python code for testing and I wondered if it would show anywhere. It didn't work, but I noticed it showed below "Post-run Script" in "Change Launch Options..." window. I then clicked on a button next to it, but canceled it and it showed an error in the terminal. I then tried to select a random .txt file and it also showed the same error and the script didn't change. Same thing happened with "Working Directory", but the error was a little different.

### To Reproduce

1. Launch Bottles from terminal
2. Go to any of your programs
3. Click on three dots button and then on "Change Launch Options..."
4. Click on "Choose a Script" button
5. Select a script or click on cancel button
6. Error in terminal
7. Click on "Choose a Directory" button
8. Select a directory or click on cancel button
9. Error in terminal

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-60-generic
Disk:
    Total: 8321306624
    Free: 8321155072
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.1GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
TypeError: LaunchOptionsDialog.__choose_script.<locals>.set_path() missing 1 required positional argument: '_file_dialog'

TypeError: LaunchOptionsDialog.__choose_cwd.<locals>.set_path() missing 1 required positional argument: '_file_dialog'
```

**Comment by TheEvilSkeleton** [comment]
Thank you for explaining thoroughly! I can reproduce it on my end.
