### ISSUE TITLE
[Request]: Remove vmtouch

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2701]
### Tell us the problem or your need

[vmtouch](https://github.com/hoytech/vmtouch) is a utility to cache data. Based on my experience, I have never noticed any of its benefits, but I have noticed excessive RAM consumption. Plus, we have to support that feature.

### Describe the solution you'd like

We should remove it and close https://github.com/bottlesdevs/Bottles/issues/1941.

**Comment by emansom** [comment]
> but I have noticed excessive RAM consumption.

[Nope](https://www.linuxatemyram.com/).

**Comment by TheEvilSkeleton** [comment]
My system went OOM multiple times.

**Comment by emansom** [comment]
Bottles shouldn't launch `vmtouch` with the `-l` command line flag [here](https://github.com/bottlesdevs/Bottles/blob/71a2ca7a38d58fdbf9fbf738e26dde589bd23f40/bottles/backend/wine/winecommand.py#L578), as the `mlock` behavior causes the kernel file cache to not dereference files.

Removing that flag would make it fall back to the more efficient touch/mmap based approach.

**Comment by Kinsteen** [comment]
@emansom, you seem to know vmtouch. Do you use it? Have you found real interest to use it? I'm asking because I would also like to remove it, but if there is a real use case where it can be useful, then I guess we can keep it.

**Comment by jannuary** [comment]
I'm inclined to ax it. It seems no one knows how to use it, including our own developers, and it also requires a lot of shit work to even use, all for seemingly dubious benefit.

**Comment by emansom** [comment]
> @emansom, you seem to know vmtouch. Do you use it? Have you found real interest to use it? I'm asking because I would also like to remove it, but if there is a real use case where it can be useful, then I guess we can keep it.

It helps as pre-warm, making initial loading of assets faster.

All marginal on modern hardware, given modern NVMe is ridiculously fast. On old hardware however, especially on HDDs, it could help a lot.

I'm fine with it being axed, but it doesn't have to, dropping `-l` from would solve the OOM issues too.

**Comment by TheEvilSkeleton** [comment]
Hmm... I'm not sure anymore, as I know nothing about using vmtouch.

**Comment by ikcikoR** [comment]
> [vmtouch](https://github.com/hoytech/vmtouch) is a utility to cache data. Based on my experience, I have never noticed any of its benefits, but I have noticed excessive RAM consumption.

Doesn't that basically improve loading times for slow harddrives? With SSD there will probably be little to no difference but I'm quite sure folks with slow HDDs might benefit from it a good amount.

**Comment by TheEvilSkeleton** [comment]
I'm closing this because it has benefited many users while mitigating stutters and microstutters.
