### ISSUE TITLE
[Bug]: cannot install riched20: riched20.dl_ not found

### ISSUE THREAD

**Issue by RAMChYLD** [bottlesdevs/Bottles#2720]
### Describe the bug

When attempting to install the riched20 dependency on Bottles, the installation will always fail with the error
`23:11:14 (ERROR) Cab file /home/leecy/.local/share/bottles/temp/riched20/i386/riched20.dl_`

### To Reproduce

1. Open the desired bottle
2. Click on Dependencies
3. Click on the floppy disk next to riched20

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: false
Version: '50.2'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/amd_icd64.json:/usr/share/vulkan/icd.d/amd_icd32.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.12-zen1-1-zen
Disk:
    Total: 249512853504
    Free: 180476796928
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 21.9GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.37'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Troubleshooting Logs

```shell
23:23:05 (WARNING) File [w2ksp4_en.exe] already exists in temp, skipping. 
/home/leecy/.local/share/bottles/temp/riched20//i386/riched20.dl_: No such file or directory
23:23:05 (INFO) Cabinet  extracted successfully 
23:23:05 (ERROR) Cab file /home/leecy/.local/share/bottles/temp/riched20/i386/riched20.dl_ not found
```

### Additional context

I suspect the issue may be related to this winetricks bugreport: https://github.com/Winetricks/winetricks/issues/2023 , which in summary, states that a behavioral change in cabextract 1.10 is the cause of the issue. A potential fix is documented at https://github.com/Winetricks/winetricks/pull/2025.

**Comment by RAMChYLD** [comment]
Update:　Manually adding the --keep-symlinks file to /usr/share/bottles/bottles/backend/cabextract.py fixed the issue, which validates that the issue is related to the abovementioned winetricks bugreport.

**Comment by Kinsteen** [comment]
This might affect only AUR users, as on Flatpak our dependencies are frozen. We can't fix by adding the argument, as it will break Bottles for Flatpak users. The workaround in the Winetricks issue might work, but we don't want to have workarounds for non-flatpak users.

Not sure what to do about this, as personally I would like to fix it, but some other devs would not (cc @TheEvilSkeleton)

**Comment by RAMChYLD** [comment]
@Kinsteen I don't follow. Does the flatpak version of bottles ship with it's own copy of cabextract?

Alternatively, I could make a patch and submit it to the AUR so it's only applied on the AUR version of Bottles, but I think just ignoring it isn't going to make it go away, since Bottles surely will need to upgrade to a newer version of cabextract eventually?

**Comment by Kinsteen** [comment]
By definition, Flatpak have runtimes that have select versions of software. On our flatpak runtime that we use, cabextract is version 1.9.1, which is not affected by this bug.

It is true that we shouldn't ignore it, but we're not planning on upgrading runtimes soon, so it will be a problem for later. You can go ahead a propose a fix for the AUR, I think

**Comment by RAMChYLD** [comment]
Understood. Thanks for the feedback, I will work on that.
