### ISSUE TITLE
[Request]: Update notifier

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2728]
### Tell us the problem or your need

Sometimes there were few hotfix releases of Bottles that used to come very quickly so users might have assumed they already are on the newest when in fact they weren't and the hotfixes included some important bugs. I even did few times in the past, but fortunately didn't report any already fixed bugs.

Also there's situation where users might not know they need to update their flatpaks manually by running `flatpak update`. For example Linux Mint added flatpak updates in the manager just in the newest 21.1 version. So someone might still be on older release and not know of flatpak updates. However I don't know how many other distributions have support for something like that.

### Describe the solution you'd like

Adding some kind of notification inside Bottles that would inform users that there is an update available and that they should run 'flatpak update' or update through their software manager if it supports such a way.

### Other solutions?

Maybe it could also be improved in such a way that it shows that an update is already on it's way. Some of Bottles updates used to take more than 12 hours to appear in Flathub while the release was already on GitHub. Could the server that handles the fetching resources during start up also ping the newest version that is either available or will be available shortly?

**Comment by TheEvilSkeleton** [comment]
We don't want to make unnecessary internet requests over something that isn't needed - updates should be managed and displayed by the software center or directly by the user; some software centers even do automatic updates. If they decide to pick the 'wrong' distribution or the 'wrong' desktop environment or window manager, then that's their problem.

**Comment by jannuary** [comment]
We had this before and it was deservedly cut — I don't see the need to duplicate functionality of package managers, not to mention it's pretty weird UI-wise.
