### ISSUE TITLE
No connection found in NixOS

### ISSUE THREAD

**Issue by PassiveLemon** [bottlesdevs/Bottles#2739]
### Prerequisites

- [X] I am sure that this problem has NEVER been discussed in [other issues](https://github.com/bottlesdevs/Bottles/issues).

### What happened

Added bottles to my system configuration.nix

### What you expected to happen

It runs, downloads its dependencies, and allows me to create bottles

### How to reproduce it

It could be specific to my system

Add bottles to system configuration.nix
Rebuild packages
Run bottles
Find out that it cant connect to the internet and download dependencies

### Ping proxy.usebottles.com

```log
[lemon@citrus-tree:~]$ ping proxy.usebottles.com
PING proxy.usebottles.com (172.67.153.15) 56(84) bytes of data.
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=1 ttl=57 time=4.30 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=2 ttl=57 time=4.77 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=3 ttl=57 time=4.83 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=4 ttl=57 time=5.28 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=5 ttl=57 time=4.73 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=6 ttl=57 time=4.77 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=7 ttl=57 time=4.84 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=8 ttl=57 time=4.66 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=9 ttl=57 time=4.39 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=10 ttl=57 time=4.55 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=11 ttl=57 time=4.47 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=12 ttl=57 time=4.66 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=13 ttl=57 time=4.70 ms
^C
--- proxy.usebottles.com ping statistics ---
13 packets transmitted, 13 received, 0% packet loss, time 14253ms
rtt min/avg/max/mdev = 4.295/4.687/5.278/0.234 ms
```

### Dig proxy.usebottles.com

```log
[lemon@citrus-tree:~]$ dig proxy.usebottles.com

; <<>> DiG 9.18.8 <<>> proxy.usebottles.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50785
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;proxy.usebottles.com.		IN	A

;; ANSWER SECTION:
proxy.usebottles.com.	241	IN	A	104.21.40.150
proxy.usebottles.com.	241	IN	A	172.67.153.15

;; Query time: 1 msec
;; SERVER: 192.168.1.1#53(192.168.1.1) (UDP)
;; WHEN: Fri Feb 24 17:12:22 EST 2023
;; MSG SIZE  rcvd: 81
```

### Your Internet Service Provider (ISP) name

AT&T

### Your Country/Area

Georgia, United States

### Anything else we need to know

I have tried on both wired and wireless with the same result. Tried with ipv4 on auto and manual, with and without ipv6.

**Comment by PassiveLemon** [comment]
Update: It seems to run perfectly fine from Flatpak. This isn't the ideal solution as it's not immutable so I'm going to keep this open.

**Comment by SuperSamus** [comment]
Are you using NixOS stable (22.11) or unstable? I don't have any issues on unstable.

**Comment by PassiveLemon** [comment]
I am on 22.11 currently. I did some stuff in my config to allow me to specify certain unstable packages and using the unstable Bottles seems to work and this is a satisfactory enough solution for me. Thanks for the idea
