### ISSUE TITLE
The icon for the "Bottle" view has several bottles

### ISSUE THREAD

**Issue by Kekun** [bottlesdevs/Bottles#274]
The details view of a bottle called Bottle has several bottles. Maybe it should only have one to match the semantic of the view?

![Capture d’écran de 2021-05-14 12-16-01](https://user-images.githubusercontent.com/2536339/118257022-6fec5300-b4ae-11eb-8c7b-2c16c1eccb2d.png)

**Comment by mirkobrombin** [comment]
This actually makes sense @jannuary @alvarlagerlof

**Comment by alvarlagerlof** [comment]
Yeah this should me one probably. There can be multiple programs, but not bottles in bottles
