### ISSUE TITLE
[Request]: Bottle Data Limit Manager, Grid View and Icons for Bottles

### ISSUE THREAD

**Issue by BasicZorinUser** [bottlesdevs/Bottles#2744]
### Tell us the problem or your need

Long story short, I tried to download Oculus software on Zorin 16.2L using a Glass of red Ubuntu flavoured Wine, and I got an Error about not having enough storage. And I don't know if Bottles are using the hard drive where it is installed to use Windows .exe's and .msi's. I'm also frustrated that I can't customize the Bottles, and don't have a grid view for them.

### Describe the solution you'd like

To fix the first issue (if I was a master at coding), I would add a data limit manager like in VM managers (VirtualBox, VMWare Workstation etc.) Just a slider and a text box for storage limits. This may be long to make, but trust me. It's gonna be worth the sweats and nerves. To fix the second and third issue, I would add a grid view, and add icons for the bottles.

### Additional context and references

Examples for icons: Milk Bottle, Juice Bottle, Bottle with a controller label (Gamer Juice), Water Bottle.

**Comment by jannuary** [comment]
Please follow the issue template and file issues one by one — otherwise it's harder to triage, follow and solve issues.

**Comment by BasicZorinUser** [comment]
Excuse me but this is a feature request not an issue

**Comment by jannuary** [comment]
Feature requests are a subset of issues.
