### ISSUE TITLE
[Visual BUG] double row border into preferences

### ISSUE THREAD

**Issue by Jupi007** [bottlesdevs/Bottles#275]
**Describe the bug**
It is not a "bug" itself but more a visual glitch: listviews in the settings rows have a double border (without border-radius btw).

**Installation**
 - Method: snap
 - Version 3.1.8

**To Reproduce**
1. Go to preferences
2. See double row border

**Expected behavior**
These extra borders shouldn't be here.

**Screenshots**
![Capture d’écran du 2021-05-14 15-10-15](https://user-images.githubusercontent.com/36476595/118275301-8c948500-b4c6-11eb-811b-b4dbc67c3b25.png)

**Desktop:**
 - OS: Ubuntu
 - Version 21.04

**Comment by mirkobrombin** [comment]
These bordwra should only be visible using the Yaru theme. I see the snap uses Adwaita, what is your system theme?

**Comment by Jupi007** [comment]
I'm using Yaru, but the problem is also present with Adwaita.

**Comment by Jupi007** [comment]
I tested some things and it looks that drop these lines fix the problem:
https://github.com/bottlesdevs/Bottles/blob/2c75f40094821c74f4345a9e8e65a47384051f57/src/ui/yaru.css#L1-L3

**Comment by mirkobrombin** [comment]
> I tested some things and it looks that drop these lines fix the problem:
> https://github.com/bottlesdevs/Bottles/blob/2c75f40094821c74f4345a9e8e65a47384051f57/src/ui/yaru.css#L1-L3

These lines shouldn't load if you don't use the Yaru theme. From your screen Bottles is using Adwaita

**Comment by Jupi007** [comment]
Great 🎉
Thanks @mirkobrombin
