### ISSUE TITLE
Missing charset_normalizer from packaging wiki

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2757]
running without it results in 

```
Traceback (most recent call last):
  File "/usr/bin/bottles", line 40, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line
27, in <module>
    from bottles.backend.health import HealthChecker
  File "/usr/share/bottles/bottles/backend/health.py", line 26, in <module>
    from bottles.backend.utils.generic import is_glibc_min_available
  File "/usr/share/bottles/bottles/backend/utils/generic.py", line 25, in
<module>
    from charset_normalizer import from_bytes
ModuleNotFoundError: No module named 'charset_normalizer'

```

**Comment by StoneMoe** [comment]
Hi, thanks for reporting
Are you using git version?
This change may(or maybe not) be included in next next release, which we are still working on.

**Comment by duarm** [comment]
Yes, I'm using the git version, the packaging wiki is useful resource for building bottles yourself.

**Comment by duarm** [comment]
Hello, not sure what the linked pull request does, but this issue was about the missing dependency charset_normalizer on the packaging wiki, this page https://github.com/bottlesdevs/Bottles/wiki/Packaging

**Comment by duarm** [comment]
I see, thanks

**Comment by E-D-W-I-N** [comment]
Sadly, latest release doesn't have this PR included. So many people have to install `python-charset-normalizer` to fix the above issue. Looks like a new release with this PR is needed
