### ISSUE TITLE
Bottles Crashed and it told me to send you this report

### ISSUE THREAD

**Issue by yuenanojyona** [bottlesdevs/Bottles#2758]
I was just following instructions to add permissions to let Bottles add games to Steam. When I restarted Bottles, I got this error:

SteamManager.add_shortcut() missing 1 required positional argument: 'program_path'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

**Comment by Kinsteen** [comment]
Please update to latest 51.5
