### ISSUE TITLE
Feedback about the usability of the UI as a new user

### ISSUE THREAD

**Issue by raploz** [bottlesdevs/Bottles#2762]
As a new user of Bottles, I had some trouble with the UI/UX. I'd like to leave my feedback.

I downloaded Bottles and clicked on the + button, then I added my first Bottle. During the setup, it hang for over 10 minutes while installing Windows fonts. There was no cancel button and no information about what was happening. I force quit Bottles and executed it from the terminal, only to realize (with the use of the information on the terminal) that, for some reason, the font download was extremely slow, at about 2KB/s. I tested my internet with Speed Test and it was fine, other websites were fine too, so I don't know what happened there.

**Suggestion**: Add a cancel button during the setup
**Suggestion**: Include information about the download speed, either through text or through some fancy loading indicator

Then, after finally waiting and creating my Bottle, I clicked on the big blue button to execute the software I wanted. I navigated through the folders and found it. I closed it and clicked on the blue button again, only to notice it would ask me to select the executable again every time. I had to pay a little bit more attention and realize there's a button to add a shortcut to a program right below the blue button. I wonder how often someone would want to execute a program a single time. If I had to guess, I'd say adding a program to the Bottle is probably more common than just executing a random .exe.

**Suggestion**: Make the button to add a shortcut the default (make it the big blue button!)

I have to say too that, as a new user, it's not immediately clear what a bottle is for exactly. When I added a Bottle with the + button for the first time, I thought I was only adding a shortcut to an .exe. Only later I realized a Bottle is a place where you can add multiple applications.

**Suggestion**: On the first start-up, show a dialog explaining what a Bottle is supposed to be.

After adding a shortcut for the program I wanted on my new bottle, I went to the Library tab (at least that's what it's called in the Portuguese translation), and noticed there was nothing there even though I had just added a shortcut in the bottle. I thought about clicking on the + button again in that tab to add the program to my library, but it only prompted me to create another bottle. I had to look thoroughly for about 5 minutes before I found the option to add the program to the library under the ... menu of the shortcut.

**Suggestion**: Hide the + button on the library tab. It leads the user to think that clicking on it would open a page to add existing applications to it. That's the simple solution though. If dev power is not a problem, then clicking on it should do exactly that: show a page that lists all applications added to all Bottles and a + button to add them to the Library.

As a user, I do not understand the difference between adding a shortcut to a Bottle and adding it to my library. To me, a library of applications should be a place with the shortcuts of the programs I added, in that case, the separation between the two doesn't make much sense.

**Possible suggestions:**

1. Add applications added to a Bottle automatically to the library
2. If adding them automatically is not desired, then the button to move an application to the library should be easily visible right on the list of applications added to a Bottle (aka. not hidden in the ... menu) 
3. If the library is meant to only contain specific apps the user adds, it should probably be renamed to "Favorites" to make its intended use clearer

Well, after finally adding my program to the Library, I noticed it showed a blank square on the Library page. Hovering over the square showed the name of the program and a button to start. Right-clicking didn't show any option to select an icon or to change the name of the .exe for something more friendly.

**Suggestion**: When an application doesn't have an icon, show a placeholder.
**Suggestion**: Allow renaming the application
**Suggestion**: I do not have one, but I wonder how the "hover to see the application name" would work on a touch-only device. Maybe the label of the program should always be visible.

That's all I have to say from my first experience with Bottles. I did find out that after deleting an app from the Library page the button to add it back doesn't show up in the ... menu in the list of applications on the Bottle, but that should probably be left for another bug report.

Thank you for making this application, it really helps with running Windows applications on Linux. I hope the best to all developers. I'm at your disposal if you have any questions about what I wrote.

**Comment by jannuary** [comment]
Once again, please file issues one by one so that we can actually discuss & fix them :)
