### ISSUE TITLE
[Request]: Explain what a Bottle is the first time the program is opened

### ISSUE THREAD

**Issue by raploz** [bottlesdevs/Bottles#2765]
### Tell us the problem or your need

As a new user, it's not immediately clear what a bottle is for exactly. When I added a Bottle with the + button for the first time, I thought I was only adding a shortcut to an .exe. Only later I realized a Bottle is a place where you can add multiple applications.

### Describe the solution you'd like

Suggestion: On the first start-up, show a dialog explaining what a Bottle is supposed to be.

### Additional context and references

Refer to https://github.com/bottlesdevs/Bottles/issues/2762 for more context

**Comment by tlneondo** [comment]
Honestly a quick primer on a Bottle/Wineprefix, and what the Windows program sees as a C drive vs the Z drive containing your Linux root would be a great idea.

**Comment by TheEvilSkeleton** [comment]
Duplicate of #2472

**Comment by TheEvilSkeleton** [comment]
Also, this will be closed by https://github.com/bottlesdevs/Bottles/pull/2615.
