### ISSUE TITLE
[BUG] Broken UI on Breeze theme

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#277]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68649672/118383024-ae8f2400-b5fa-11eb-8fa4-6e5280dab76b.png)
Things like the text don't appear.
And also the 3 buttons at the top right appear even though I set that it disables the gtk borders,and also the icon at the top left is still there in this mode (I use a program called "GTK3-nocsd" to disable the gtk borders).
And also there are those strange black borders.

**Installation**
AUR 3.1.8-1

**To Reproduce**
Open the program

**Desktop (please complete the following information):**
 - OS: Arch
 - Version Newest Stable Kernel

**Comment by mirkobrombin** [comment]
Unfortunately I cannot guarantee compatibility with every gtk theme and window manager.Bottles was designed for adwaita and yaru, using the libhandy library which contains modern elements that may not yet be supported by breeze.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/122633492-4cce4800-d0d9-11eb-9264-6d113c42b119.png)
I tried to reproduce your bug with no success

**Comment by mirkobrombin** [comment]
I close because I can't replicate the problem (as you can see from the screenshot above). We will reopen the issue if other users have the same bug.

**Comment by arutkowski00** [comment]
I have the same issue on [Arc-Dark](https://github.com/jnsh/arc-theme) theme.

**Installation**
AUR: bottles-git-1:r2421.f74c2c3-1
**OR**
AUR: bottles-2021.10.28-1

![Screenshot from 2021-11-13 15-37-02](https://user-images.githubusercontent.com/8336970/141647820-9d0fe8a6-f987-4beb-9e8d-7a9a75dff75e.png)
