### ISSUE TITLE
[Bug]: Bottles freeze the whole system when trying to open the hamburger menu

### ISSUE THREAD

**Issue by Vilianexe** [bottlesdevs/Bottles#2770]
### Describe the bug

https://user-images.githubusercontent.com/72302817/222783899-91b3b99d-f357-432a-907e-ffb5111dc41b.mp4

yes, i was trying moving my mouse the whole time, and i can't alt tab, open the system activity, nor log out, nothing

### To Reproduce

1. Open bottles
2. click in the hamburger menu

### Package

Flatpak from Flathub

### Distribution

Arch linux

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.1-arch1-1
Disk:
    Total: 4138012672
    Free: 4137865216
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 5.3GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
flatpak run com.usebottles.bottles
14:00:52 (INFO) Bottles Started! 
14:00:55 (INFO) Performing Bottles checks… 
14:00:55 (INFO) Dxvks found:
         - dxvk-2.1-1-0811813
 
14:00:55 (INFO) Vkd3ds found:
         - vkd3d-proton-2.8-1-7be64c2
 
14:00:55 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.1-1-0c54f06
 
14:00:55 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
14:00:55 (INFO) Runners found:
         - soda-7.0-9
         - sys-wine-8.0
 
14:00:55 (INFO) Bottles found:
         - game
 
14:00:56 (INFO) Catalog dependencies loaded 
14:00:56 (INFO) Catalog installers loaded 
14:00:56 (INFO) Catalog components loaded 

(bottles:2): Gtk-WARNING **: 14:01:03.589: Screen coordinates not supported, reported positions will be wrong
```

### Additional context

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.2.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i3-9100F CPU @ 3.60GHz
Memory: 7,7 GiB of RAM
Graphics Processor: AMD CEDAR
Manufacturer: PCWARE
Product Name: IPMH310G

https://user-images.githubusercontent.com/72302817/222785774-4c7d9535-79b8-40a1-b2af-44a44043fd06.mp4

well, this was such a huge cpu spike,

**Comment by TheEvilSkeleton** [comment]
Can you install a couple of libadwaita apps and see if you can reproduce there?

**Comment by Vilianexe** [comment]
i don't know any libadwaita apps, can you send me some?

**Comment by TheEvilSkeleton** [comment]
Sure, here are some:
- https://flathub.org/apps/me.iepure.devtoolbox
- https://flathub.org/apps/app.drey.Elastic
- https://flathub.org/apps/org.nickvision.tubeconverter
- https://flathub.org/apps/com.vixalien.sticky

**Comment by Vilianexe** [comment]
yah, elastic has the same bug in the hamburger menu, so i guess it isn't a bottle issue, sorry
