### ISSUE TITLE
[Bug]: a mispell issue but it is funny no urge to correct it

### ISSUE THREAD

**Issue by csc-chicken** [bottlesdevs/Bottles#2779]
### Describe the bug

![圖片](https://user-images.githubusercontent.com/66060998/223187107-c7b4ff41-f6e3-4d60-b1b9-fed47282dae6.png)
I love to be hugged by mango haha!!

### To Reproduce

go to setting in zh-tw maybe

### Package

Flatpak from Flathub

### Distribution

Manjaro kde 21

### Debugging Information

```shell
no need
```

**Comment by StoneMoe** [comment]
This seems related to Traditional Chinese translation, could you help us to correct it?
you can read [this](https://github.com/bottlesdevs/Bottles/tree/main/po#readme) for more info.

**Comment by csc-chicken** [comment]
Oh I have to learn how to push the branch and pull request to github. I haven't do that after github use token to verification and somewhat confuse me.

**Comment by Kinsteen** [comment]
No you don't have to use Git, every translation is in Weblate

**Comment by csc-chicken** [comment]
I fixed it.

**Comment by csc-chicken** [comment]
Actually quite simple to correct it.
