### ISSUE TITLE
Add Qt/QML frontend

### ISSUE THREAD

**Issue by eszlari** [bottlesdevs/Bottles#2794]
advantages:
* supports fractional scaling on X11 and (since v6.5) on Wayland
* can be integrated well into different desktop environments through theming
* QML GUIs can be created visually with Qt Creator (Qt Quick Designer plugin)
* QML is more matured than blueprint and officially supported by Qt
* the Python bindings (Pyside) are offically developed by Qt (unlike PyGObject: https://www.bassi.io/articles/2022/12/02/on-pygobject/)

**Comment by TheEvilSkeleton** [comment]
Unfortunately, we don't have the experience and time to work on a front-end. That being said, we're completely okay with people making a Qt/QML front-end and collaborating with us.
