### ISSUE TITLE
[Bug]: Unresponsive after downloading/fetching

### ISSUE THREAD

**Issue by brandonnola** [bottlesdevs/Bottles#2795]
### Describe the bug

installed originally and used to run a stock market trading platform app and at first worked perfectly however after updating the bottles software the bottles application will begin to start and then the splash screen will show that it is downloading/fetching 2 of 3 and then 3 of 3 and then it appears that it freezes at that point and never responds. I have tried uninstalling and reinstalling bottles and still nothing exactly the same thing.

### To Reproduce

1. Applications menu
2. click on the Bottles application title
3. Allow to start the loading process

### Package

Flatpak from Flathub

### Distribution

Arco / Arch

### Debugging Information

```shell
Official Package: false
Version: '51.5'
DE/WM: xfce
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_hasvk_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.2-arch1-1
Disk:
    Total: 502605742080
    Free: 186676461568
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 20.3GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.37'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Additional context

Here are some screen shots of the issue at hand as well as settings screenshots just in case they are needed!

![bottles-broken-startup-splash-screen](https://user-images.githubusercontent.com/74946677/224565130-8770f528-8c8c-4b7c-a129-c017f1f8d189.png)
![bottles-help-menu-version-number](https://user-images.githubusercontent.com/74946677/224565146-5fbc9526-90fd-40e3-b353-0ed565c77c68.png)
![bottles-preferences-general](https://user-images.githubusercontent.com/74946677/224565156-dcb9eacd-2be6-4c1d-aa87-031d48537029.png)
![bottles-preference-DLL_Components](https://user-images.githubusercontent.com/74946677/224565161-eff55010-2b49-49c8-a49f-ce51a13a8782.png)
![bottle-preference-runners](https://user-images.githubusercontent.com/74946677/224565172-4150e476-3a6c-48ce-97c2-93c5435e54ea.png)

**Comment by TheEvilSkeleton** [comment]
Can you launch Bottles from the terminal and send the output?

**Comment by articuno1au** [comment]
So I'm running into this too. The output is
```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 149, in set_manager
    self.page_details = DetailsView(self)
  File "/usr/share/bottles/bottles/frontend/views/details.py", line 78, in __init__
    self.view_bottle = BottleView(self, config)
  File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 163, in __init__
    self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```
Seems to be related to the new version of gtk. If you want an immediate fix, you can check out https://aur.archlinux.org/packages/bottles#comment-905088 however this is only one of the issues you'll run into. Basically you either need to downgrade gtk or wait for the devs to support the new version in bottles.

**Comment by Kinsteen** [comment]
The bug you are talking about is discussed here, and we won't fix it for now: https://github.com/bottlesdevs/Bottles/issues/2788

It probably isn't a problem from us but from GTK bindings, it would seem. The PR you linked is now closed as it would break on Flatpak.

The solution for Arch AUR users are either:
- use the flatpak version (recommended)
- apply the fix from the AUR

**Comment by articuno1au** [comment]
Is there any chance we could get a hand with regards to the second issue I listed above? I can put an answer in for the AUR users to help them patch it.

I checked the [Gtk developer docs](https://docs.gtk.org/gtk3/method.CssProvider.load_from_data.html) but am not sure how to correct it (I speak zero python unfortunately).

**Comment by Kinsteen** [comment]
What issue are you talking about? The AUR already has a comment about how to patch it

**Comment by articuno1au** [comment]
This one
```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/widgets/installer.py", line 101, in __execute_installer
    InstallerDialog(self.window, self.config, self.installer).present()
  File "/usr/share/bottles/bottles/frontend/windows/installer.py", line 99, in __init__
    self.style_provider.load_from_data(b"progressbar { line-height: 2.0; }")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```
It's a different issue and can't be fixed by the same fix provided in the AUR thread.

**Comment by articuno1au** [comment]
Ignore me, as you say, there's a fix in the PR. I'm having a moment. Thanks :)

**Comment by Kinsteen** [comment]
Ah I see, it's the same problem just in a different location

**Comment by Kinsteen** [comment]
I'm closing this as it's not going anywhere and shouldn't be fixed yet
