### ISSUE TITLE
[Bug]: Unable to load libGLX_nvidia.so.0 

### ISSUE THREAD

**Issue by mlauronen** [bottlesdevs/Bottles#2800]
### Describe the bug

While starting the Bottles I am getting the following error and warning messages in console:

10:07:37 (ERROR) Unable to load libGLX_nvidia.so.0 
10:07:37 (WARNING) Unable to locate libGLX_nvidia 

### To Reproduce

1. Goto terminal
2. Give a command: flatpak run com.usebottles.bottles

### Package

Flatpak from Flathub

### Distribution

Debian 11 stable

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: lightdm-xsession
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
            nvngx_path: null
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.0-0.deb11.6-amd64
Disk:
    Total: 16786608128
    Free: 16786460672
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 28.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
mika@pc3 ~ $ flatpak run com.usebottles.bottles
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI2: failed to authenticate
10:07:37 (ERROR) Unable to load libGLX_nvidia.so.0 
10:07:37 (WARNING) Unable to locate libGLX_nvidia 
10:07:37 (INFO) Bottles Started! 
10:07:39 (INFO) Performing Bottles checks… 
10:07:39 (INFO) Dxvks found:
	 - dxvk-2.0-1-196fefe
 
10:07:39 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8-1-f09e31a
 
10:07:39 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6-1-0827efb
 
10:07:39 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
10:07:39 (INFO) Runners found:
	 - sys-wine-7.0.1
	 - soda-7.0-8
 
10:07:39 (INFO) Bottles found:
	 - AmiBroker
	 - SierraChart
	 - Admin
 

(bottles:2): Gtk-CRITICAL **: 10:07:39.318: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
10:07:39 (INFO) Library saved 
10:07:39 (INFO) Catalog installers loaded 
10:07:39 (INFO) Catalog dependencies loaded 
10:07:39 (INFO) Catalog components loaded
```

### Additional context

**The library in question should be in the system. Please see the following command outputs:**

mika@pc3 ~ $ lspci | grep VGA
06:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

mika@pc3 ~ $ nvidia-smi | grep Version
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |

mika@pc3 ~ $ sudo apt-file search libGLX_nvidia.so.0
libglx-nvidia-legacy-390xx0: /usr/lib/x86_64-linux-gnu/nvidia/legacy-390xx/libGLX_nvidia.so.0
libglx-nvidia-tesla-418-0: /usr/lib/x86_64-linux-gnu/nvidia/tesla-418/libGLX_nvidia.so.0
libglx-nvidia-tesla-450-0: /usr/lib/x86_64-linux-gnu/nvidia/tesla-450/libGLX_nvidia.so.0
libglx-nvidia-tesla-460-0: /usr/lib/x86_64-linux-gnu/nvidia/tesla-460/libGLX_nvidia.so.0
libglx-nvidia-tesla-470-0: /usr/lib/x86_64-linux-gnu/nvidia/tesla-470/libGLX_nvidia.so.0
libglx-nvidia0: /usr/lib/x86_64-linux-gnu/nvidia/current/libGLX_nvidia.so.0

mika@pc3 ~ $ sudo apt list --installed | grep libglx
libglx-mesa0/stable,now 20.3.5-1 amd64 [installed,automatic]
libglx-mesa0/stable,now 20.3.5-1 i386 [installed,automatic]
libglx-nvidia0/stable,now 470.161.03-1 amd64 [installed,automatic]
libglx-nvidia0/stable,now 470.161.03-1 i386 [installed,automatic]
libglx0/stable,now 1.3.2-1 amd64 [installed,automatic]
libglx0/stable,now 1.3.2-1 i386 [installed,automatic]

mika@pc3 /usr/lib/x86_64-linux-gnu/nvidia/current $ ls /usr/lib/x86_64-linux-gnu/nvidia/current/libGLX_nvidia.so.*
/usr/lib/x86_64-linux-gnu/nvidia/current/libGLX_nvidia.so.0 -> libGLX_nvidia.so.470.161.03
/usr/lib/x86_64-linux-gnu/nvidia/current/libGLX_nvidia.so.470.161.03

**Comment by mlauronen** [comment]
For me it looks like the reason is in the debugging output "nvngx_path: null".

**Comment by Kinsteen** [comment]
Can you do `flatpak list --runtime` please? My suspicion is that Flatpak doesn't have the Nvidia runtime that provides this library inside the Flatpak sandbox. It might be because you use an old driver as well

**Comment by mlauronen** [comment]
mika@pc3 ~ $ flatpak list --runtime
Name                                Application ID                                Version Branch       Installation
bottles translations                com.usebottles.bottles.Locale                         stable       system
Mesa                                org.freedesktop.Platform.GL.default           22.3.2  22.08        system
Mesa (Extra)                        org.freedesktop.Platform.GL.default           22.3.2  22.08-extra  system
nvidia-525-60-13                    org.freedesktop.Platform.GL.nvidia-525-60-13          1.4          system
Mesa                                org.freedesktop.Platform.GL32.default         22.3.2  22.08        system
nvidia-525-60-13                    …g.freedesktop.Platform.GL32.nvidia-525-60-13         1.4          system
ffmpeg-full                         org.freedesktop.Platform.ffmpeg-full                  22.08        system
openh264                            org.freedesktop.Platform.openh264             2.1.0   2.2.0        system
GNOME Application Platform version… org.gnome.Platform                                    43           system
i386                                org.gnome.Platform.Compat.i386                        43           system
DXVK                                org.winehq.Wine.DLLs.dxvk                     1.10.3  stable-22.08 system
Gecko                               org.winehq.Wine.gecko                                 stable-22.08 system
Mono                                org.winehq.Wine.mono                                  stable-22.08 system

**Comment by Kinsteen** [comment]
Okay, so for some reason the Nvidia driver runtime doesn't match your driver's version, which is why it doesn't work. I'm not sure how to fix this, I'm not sure a runtime exists for your driver version

**Comment by mlauronen** [comment]
I removed the current stable repository nvidia drivers and installed the newest drivers from nvidia reposotiry

mika@pc3 ~ $ nvidia-smi | grep Driver
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |

But it didn't give any help...

**Comment by mlauronen** [comment]
I did the flatpak update and now the system's nvidia driver version 530.30.02 matches with the flatpak newest nvidia drivers and the problem is fixed.

Thank you.
