### ISSUE TITLE
[Request]: Disable Internet for a Bottle or Program

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#2802]
### Tell us the problem or your need

Sometimes there's a need to turn off internet access for some programs/games and there's no way to do that per bottle, or per program in a bottle.

### Describe the solution you'd like

- Setting to turn off internet for a bottle
- Setting to turn off internet for a single program

### Additional context and references

Does "turning off internet" actually mean that the network card has to be disabled per bottle or program? I'd like to see an implementation where LAN would work normally (e.g. access to local network NAS) but internet access would be cut off completely.

**Comment by TheEvilSkeleton** [comment]
1. Go to: Preferences -> Experiments -> Sandbox per bottle
2. Open a bottle, go to Settings, then scroll down to Dedicated Sandbox. Open the cogwheel and you should be able to disable network.

Just keep in mind that it's experimental and we can't guarantee that it'll work well and when it'll be in stable. It can only be done per bottle and not per program; there's no plan in implementing it per program

**Comment by Perkolator** [comment]
Ok. Does enabling the "Sandbox per bottle" affect all bottles right away, or do I still need to turn it on per bottle? I'm hesitant to enable/use it if it's not stable and affects all bottles (which I guess it does). I'll have to try to install TinyWall firewall to the bottle I need to control web access (though I have a feeling it won't work).

**Comment by TheEvilSkeleton** [comment]
> Does enabling the "Sandbox per bottle" affect all bottles right away, or do I still need to turn it on per bottle?

You need to enable it per bottle

**Comment by Perkolator** [comment]
> How were you able to get the internet to work inside of a bottle? I cannot get any way to get internet working

I can't help you since I didn't have to do anything, it just works.
