### ISSUE TITLE
[Bug]: Installer for Epic Games Store and Origin using outdated download URL

### ISSUE THREAD

**Issue by slavexe** [bottlesdevs/Bottles#2804]
### Describe the bug

It seems Bottles is using an outdated version of the manifests for installing Epic Games Store and Origin.
The installer download URLs were updated from 
`https://cdn.usebottles.com/programs/EpicGamesLauncherInstaller.msi`
`https://cdn.usebottles.com/programs/OriginSetup.exe`
to
`https://proxy.usebottles.com/redistributable/programs/EpicGamesLauncherInstaller.msi`
`https://proxy.usebottles.com/redistributable/programs/OriginSetup.exe`

in this [pull request](https://github.com/bottlesdevs/programs/commit/a726ad948f58d2abe3f8b4414d524c87d10e4983), but Bottles is still attempting to download from the old URLs.

### To Reproduce

1. Try to install Epic Games Store or Origin through "Install Programs" menu

### Package

Flatpak from Flathub

### Distribution

Manjaro

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.6-1-MANJARO
Disk:
    Total: 16692776960
    Free: 16692629504
RAM:
    MemTotal: 31.1GiB
    MemAvailable: 25.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
18:31:34 (INFO) Executing installer steps 
18:31:34 (ERROR) Failed to download [https://cdn.usebottles.com/programs/EpicGamesLauncherInstaller.msi] 
18:31:34 (ERROR) Failed to download EpicGamesLauncherInstaller.msi, or checksum failed.

15:23:52 (INFO) Executing installer steps 
15:23:53 (ERROR) Failed to download [https://cdn.usebottles.com/programs/OriginSetup.exe] 
15:23:53 (ERROR) Failed to download OriginSetup.exe, or checksum failed. 
```

**Comment by jannuary** [comment]
Can you try again now?

**Comment by slavexe** [comment]
Yes, the same error occurs.

**Comment by cchuster** [comment]
I have this error as well!

**Comment by slavexe** [comment]
Title updated as the installer for Origin fails to download for the same reason.

**Comment by Kinsteen** [comment]
Tracked at https://github.com/bottlesdevs/programs/issues/212

**Comment by slavexe** [comment]
Fixed in [bottlesdevs/programs/issues/212](https://github.com/bottlesdevs/programs/issues/212)

**Comment by ITEvo** [comment]
How???' How did you install that? I keep on getting crashes when I open the launcher... installed allfonts, dx9, dx11, I even RENDER with iray using my prefix. How did you get the Epic Games Launcher run???
