### ISSUE TITLE
[Bug]: Drive Path Inconsistency Among Reboots

### ISSUE THREAD

**Issue by Ruok2bu** [bottlesdevs/Bottles#2805]
### Describe the bug

In all my bottles, when i add a drive, it uses the "/run/user/1000/doc" path to the drive. It works for the duration of the session. But when i restart my computer, the path to the drive changes and as a result, the drive can't be accessed anymore. Why can't bottles use the mount path instead (eg. /mnt/Example)?

### To Reproduce

1. Add drive to bottle and select a valid drive.
2. Open file that resides in the drive in the application in the bottle to confirm it works.
3. Restart computer.
4. Try to open file that resides in the drive that was added previously. Application in bottle can't find it!

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: xfce
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-67-generic
Disk:
    Total: 16485687296
    Free: 16485539840
RAM:
    MemTotal: 30.7GiB
    MemAvailable: 25.5GiB
Bottles_envs: null
```

**Comment by jannuary** [comment]
It's a quirk of how files are exposed through xdg-desktop-portal — we cannot control it.

**Comment by Ruok2bu** [comment]
CrossOver was able to figure out how though :(

**Comment by jannuary** [comment]
Is it available as Flatpak with robust sandboxing though? :)
