### ISSUE TITLE
[Request] Adding a loading screen

### ISSUE THREAD

**Issue by shuriken1812** [bottlesdevs/Bottles#283]
As discussed, we should add a loading screen for slower systems, on terminal I can see it connecting but on GUI it is more like what is happening for approx "6 seconds" (for a normal/average user's eye). On my main system too it is about 3-4 seconds..

As an example we can have it minimal and similar to a very light loading screen in lutris - 
![Screenshot from 2021-05-20 14-53-19](https://user-images.githubusercontent.com/40650341/119150219-db649080-ba6b-11eb-91b5-9ae58dce71f3.png)

**Comment by mirkobrombin** [comment]
I'm not a fan of Lutris loading, it would be necessary to design a concept that shows the loading inside the app GUI. I don't know if there is a GNOME guideline on this. In any case, reviewing the structure of Bottles v4 in the last few days, this loading may no longer be necessary as the connection check will be immediate. However, I keep the issue open, at least until there is a version of Bottles v4 to test.

**Comment by mirkobrombin** [comment]
Ping https://github.com/bottlesdevs/libbottles/issues/1

**Comment by alvarlagerlof** [comment]
Not a fan of this either. If done, it should be inside the main window like Gnome Software does when reloading repos. But no loading screen is ofc better.

**Comment by tati1454** [comment]
For me it doesn't matter how it gets done, as long as bottles shows an instant feedback of it being launched. I think a progress indicator inside the main window like the one that shows when you install a dependency its nice. The thing is if these things that bottles do at the start are super critical, bottles should prevent the user from interacting until it finishes doing these things.

**Comment by alvarlagerlof** [comment]
Yeah, we could have a white window like mobile apps showing the logo.

**Comment by mirkobrombin** [comment]
The next version reduces the start time, we'll see if it still necessary to be implemented
