### ISSUE TITLE
Wine

### ISSUE THREAD

**Issue by zdzislaw623** [bottlesdevs/Bottles#2835]
### Describe the bug

'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1286, in create_bottle
    env = yaml.load(f.read())

  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

### To Reproduce

'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1286, in create_bottle
    env = yaml.load(f.read())

  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

### Package

Flatpak from Flathub

### Distribution

CachyOs Linux KDE

### Debugging Information

```shell
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 1286, in create_bottle
    env = yaml.load(f.read())

  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

### Additional context

Proszę o pomoc jak rozwiązać opisany problem .Pozdrawiam Zdzisław.

**Comment by StoneMoe** [comment]
Could you please follow the bug report template to submit your issue report?

**Comment by mirkobrombin** [comment]
Closing all issues with no proper title.
