### ISSUE TITLE
Default Display spacing off compared to provided screenshots

### ISSUE THREAD

**Issue by TobiTenno** [bottlesdevs/Bottles#2839]
I have no themes (I'm using flatseal to manage permissions & overrides, and I've not set anything in there), and I'm running default themes on the rest of my system.

Currently running 51.5 on debian bookworm

If there's something else I'm missing, let me know, and I'll go on my way and try to document for others for the future.

<details>
<summary>Screenshots</summary>

unfocused:
![image](https://user-images.githubusercontent.com/7128721/229944645-e279863d-6215-487c-bc5a-f9a7d5105bb8.png)

focused:
![image](https://user-images.githubusercontent.com/7128721/229945165-d770356e-625d-4979-a6d4-2158e35d8734.png)

preferences: 
![image](https://user-images.githubusercontent.com/7128721/229945208-66a47b22-833d-43ed-a277-a9b90ba17a0b.png)
</summary>

**Comment by jolty1** [comment]
Have the same issue in openSUSE TW.

**Comment by orowith2os** [comment]
Fixed in 51.7, with the disabling of the GTK_THEME environment variable.
