### ISSUE TITLE
[BUG] Unable to create more than one bottle (or that it takes unreasonable long time)

### ISSUE THREAD

**Issue by ddund** [bottlesdevs/Bottles#284]
**Describe the bug**
I recently installed Bottles and create a software bottle. However when I try to add another bottle of any type (software/gaming/custom) the process seems to get stuck on "Creating bottle...". I have tried letting it run for 2 respective 1 hour without getting anywhere. The first bottle did take less than a minute to create and I'm guessing it's unreasonable that it should take hours to create more of them.

**Installation**
 - Method: Flatpak
 - Version: 3.1.9

**Screenshots**
![stuck](https://user-images.githubusercontent.com/68921570/119155359-65542f80-ba53-11eb-843f-20430dd748fd.png)

**Desktop:**
 - OS: Fedora
 - Version: 34

**Comment by mirkobrombin** [comment]
Launch it in a console to see if there are any errors or logs:

```bash
flatpak run com.usebottles.bottles
```

**Comment by zer0exia** [comment]
I have the same problem right now, except trying to create a single software bottles (without other bottles created prior). The app stuck at "Creating bottle..." for quite a long time.
Here's the log when it is ran from terminal. The progress bar is still running at this time, but there aren't any additional logs after : 

`2021-05-22 07:33:08 INFO: Runners found: [Proton-6.8-GE-2, chardonnay-6.4, lutris-6.4]
2021-05-22 07:33:08 INFO: Dxvk found: [dxvk-1.8.1]
2021-05-22 07:33:10 INFO: Connection status: online …
https://raw.githubusercontent.com/bottlesdevs/components/main//index.json
2021-05-22 07:33:18 INFO: Dxvk found: [dxvk-1.8.1]
2021-05-22 07:33:18 INFO: Runners found: [Proton-6.8-GE-2, chardonnay-6.4, lutris-6.4]
2021-05-22 07:33:18 INFO: Connection status: online …
2021-05-22 07:33:25 INFO: Connection status: online …
2021-05-22 07:33:27 INFO: Connection status: online …
2021-05-22 07:33:28 INFO: Connection status: online …

(bottles:24218): Gtk-WARNING **: 07:33:31.405: Failed to set property GtkListBox.selection-mode to None: Could not parse enum: 'None'

(bottles:24218): Gtk-WARNING **: 07:33:31.405: Failed to set property GtkListBox.selection-mode to None: Could not parse enum: 'None'
2021-05-22 07:33:31 INFO: Bottles Started!
2021-05-22 07:33:45 INFO: Creating the wineprefix …
/bin/sh: line 1: /home/fate/.local/share/bottles/runners/Proton-6.8-GE-2/dist/bin/wine64: No such file or directory
2021-05-22 07:33:46 INFO: Generating Bottle configuration file …
2021-05-22 07:33:46 INFO: Applying environment: [Software] …
2021-05-22 07:33:47 ERROR: Error while running async job: <bound method BottlesRunner.async_create_bottle of <bottles.runner.BottlesRunner object at 0x7fd1ee4aed60>>
Exception: [Errno 2] No such file or directory: '/home/fate/.local/share/bottles/bottles/testing/bottle.json'
  File "/usr/local/share/bottles/bottles/utils.py", line 181, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/local/share/bottles/bottles/runner.py", line 858, in async_create_bottle
    with open("%s/bottle.json" % bottle_complete_path,`

OS : EndeavorOS
Version : 3.1.9

**Comment by ddund** [comment]
> I have the same problem right now, except trying to create a single software bottles (without other bottles created prior). The app stuck at "Creating bottle..." for quite a long time.
> Here's the log when it is ran from terminal. The progress bar is still running at this time, but there aren't any additional logs after :
> 
> ```
> 
> 2021-05-22 07:33:08 INFO: Runners found: [Proton-6.8-GE-2, chardonnay-6.4, lutris-6.4]
> 2021-05-22 07:33:08 INFO: Dxvk found: [dxvk-1.8.1]
> 2021-05-22 07:33:10 INFO: Connection status: online …
> https://raw.githubusercontent.com/bottlesdevs/components/main//index.json
> 2021-05-22 07:33:18 INFO: Dxvk found: [dxvk-1.8.1]
> 2021-05-22 07:33:18 INFO: Runners found: [Proton-6.8-GE-2, chardonnay-6.4, lutris-6.4]
> 2021-05-22 07:33:18 INFO: Connection status: online …
> 2021-05-22 07:33:25 INFO: Connection status: online …
> 2021-05-22 07:33:27 INFO: Connection status: online …
> 2021-05-22 07:33:28 INFO: Connection status: online …
> 
> (bottles:24218): Gtk-WARNING **: 07:33:31.405: Failed to set property GtkListBox.selection-mode to None: Could not parse enum: 'None'
> 
> (bottles:24218): Gtk-WARNING **: 07:33:31.405: Failed to set property GtkListBox.selection-mode to None: Could not parse enum: 'None'
> 2021-05-22 07:33:31 INFO: Bottles Started!
> 2021-05-22 07:33:45 INFO: Creating the wineprefix …
> /bin/sh: line 1: /home/user/.local/share/bottles/runners/Proton-6.8-GE-2/dist/bin/wine64: No such file or directory
> 2021-05-22 07:33:46 INFO: Generating Bottle configuration file …
> 2021-05-22 07:33:46 INFO: Applying environment: [Software] …
> 2021-05-22 07:33:47 ERROR: Error while running async job: <bound method BottlesRunner.async_create_bottle of <bottles.runner.BottlesRunner object at 0x7fd1ee4aed60>>
> Exception: [Errno 2] No such file or directory: '/home/user/.local/share/bottles/bottles/testing/bottle.json'
>   File "/usr/local/share/bottles/bottles/utils.py", line 181, in target
>     result = self.task_func(*args, **kwargs)
>   File "/usr/local/share/bottles/bottles/runner.py", line 858, in async_create_bottle
>     with open("%s/bottle.json" % bottle_complete_path,
> ```
> 
> **Edit** : Trying to create any bottle produce the same problem. (Not just software)
> 
> OS : EndeavorOS
> Version : 3.1.9

I get the response as you get when I run Bottles from the terminal.

**Comment by mirkobrombin** [comment]
Does the problem also occur with other packages then flatpak?
