### ISSUE TITLE
[Bug]: Bottles can't connect to internet even though my computer is connected. 

### ISSUE THREAD

**Issue by beni003** [bottlesdevs/Bottles#2863]
### Describe the bug

Bottles doesn't connect to the internet. None of the other Applications have this issue.

If I try to create a new bottle it displays: "Creating a Bottle... Take a break, it may take a while." but nothing happens. Probably because there's no internet connection.

If I click the connection button nothing happens.

![Screenshot from 2023-04-26 17-51-37](https://user-images.githubusercontent.com/131895918/234631757-b2c99286-61c6-45ba-aca0-e378a08aa2b8.png)

### To Reproduce

1.Start Bottles
2.Click on Create a new Bottle
3. see this dialog
![Screenshot from 2023-04-26 17-51-37](https://user-images.githubusercontent.com/131895918/234634627-eea94949-9f2a-41ec-9137-a7a8ef3830e2.png)
4. Nothing happens
5. Close the dialog
6. Hover over the internet connection icon: You don't seem to be connected to the internet.
7. Click the icon: Nothing happens

### Package

Flatpak from Flathub

### Distribution

Fedora 37

### Debugging Information

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.7-301.fc37.x86_64
Distro:
    Name: Fedora Linux
    Version: '37'
Disk:
    Total: 1022505254912
    Free: 449618903040
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 11.0GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.36'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

**Comment by succeedmr123** [comment]
Unfortunately, I second that (problem) still in 2025. Does that need some firewall exception, flatpak adjustment, recoding..  If I am not deep into programming there is no point to send anything but simple statement, people sent it over and over. It does not work for almost a month
