### ISSUE TITLE
[Question] Does bottles support bumblebee?

### ISSUE THREAD

**Issue by pro-anon** [bottlesdevs/Bottles#2875]
I wonder if Bottles uses `primusrun` to run games, and if not, is there a way to add a command before the game like with steam and proton?
An example of what I want to do is shown with `wine`:
```bash
primusrun wine ./game.exe
```
Which runs the game with nvidia graphics card instead of Intel's in my case.

**Comment by Kinsteen** [comment]
There is a "Dedicated GPU" option in the Bottle that will enable your Nvidia GPU on Optimus systems
