### ISSUE TITLE
[Bug]: Internet conectivity within container

### ISSUE THREAD

**Issue by ZethiaZ** [bottlesdevs/Bottles#2880]
### Describe the bug

When I launch Minecraft within the bottles container it fails to connect to any Minecraft server, even though they all work on my host machine and other devices on the same network. The launcher, MultiMC, within the container is able to connect to the internet just fine, but when I actually launch a Minecraft instance it is unable to.

### To Reproduce

1. Create a gaming container (although I have tested and the same issue occurs with all container types)
2. Install Azul jdk or jre 8
3. Install MultiMC 
4. Create a Minecraft instance, in my case 1.8.9 Forge, and launch it.
5. Attempt to connect to any minecraft server, pings and connections all fail.

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome-xorg
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
            nvngx_path: null
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.2.14-300.fc38.x86_64
Disk:
    Total: 7974477824
    Free: 7974322176
RAM:
    MemTotal: 14.9GiB
    MemAvailable: 12.4GiB
Bottles_envs: null
```

### Additional context

I have tried disabling my computers firewall, firewalld, and the issue was not resolved. In addition, I am sorry if this issue is a repeat or belongs somewhere else, I could not find an existing version of the issue.

**Comment by ZethiaZ** [comment]
Discovered it is a wine issue- will be reporting there instead

**Comment by irasponsible** [comment]
I would also appreciate a link to that report - I'm having the same issue, no pings inside a bottle work. The WineHQ solutions for solving the problem don't seem to work with Bottles.

**Comment by ZethiaZ** [comment]
Sorry for the slow response but I never got around to reporting the issue in Wine. I was able to determine it was a wine issue as when I used Proton from the AUR it was resolved, even when on the same arch machine Wine and Bottles both had the same issue. 


It was a while ago, so I could be wrong. However, I recall being able to ping websites from within the bottle but I was unable to ever get Minecraft to ping a server. (I could be misremembering this part tho)

Hope that helps, feel free to open an issue on Wine, it won't be a duplicate (at least from me).
If you do make one, feel free to post a link here.

**Comment by irasponsible** [comment]
Wiping everything, starting over, and installing Windows Firefox ESR in the bottle, I can connect to the internet. The specific application I'm trying to run still can, but I don't think it's the same issue. (possibly something to do with TLS)
