### ISSUE TITLE
[Request]: Add vcredist2022 to dependency list

### ISSUE THREAD

**Issue by Uptaker** [bottlesdevs/Bottles#2881]
### Tell us the problem or your need

MS C++ Redistributable 2015 - 2022 is currently missing in the dependencies list.

![image](https://user-images.githubusercontent.com/16374628/236616031-5310d8c0-20ae-48a7-a6e3-70df1c1abe46.png)

It's required for some games such as The Last of Us to run.

Would be of great convenience if this was added!

### Describe the solution you'd like

Protontricks has it if needed as well.

**Comment by Kinsteen** [comment]
Please open an issue on https://github.com/bottlesdevs/dependencies, not here
