### ISSUE TITLE
[Request]: Create .desktop shortcuts for bottles/programs

### ISSUE THREAD

**Issue by lebao3105** [bottlesdevs/Bottles#2889]
### Tell us the problem or your need

Bottles can run programs installed from a specific bottle by using command-line options.

### Describe the solution you'd like

Create an option which creates generic Linux shortcuts (.desktop) for specific program/bottle, place in ```~/.local/share/applications```.

**Comment by jannuary** [comment]
Bottles already has a feature to create shortcuts in the app grid. (However, it should be redone to no longer poke a hole in the sandbox, which is a different issue entirely)
