### ISSUE TITLE
[Bug]: Artifacting & Inability to Locate Files in Same Directory

### ISSUE THREAD

**Issue by IfGremlinThen** [bottlesdevs/Bottles#2895]
### Describe the bug

I have not had much luck with the latest version of Bottles which I'm trying out for the first time.  Videos demonstrating how it's used make it look much easier than it works for me in practice, and across the applications I've attempted, running a .exe directly from a vanilla install of winehq-stable works flawslessly.

My first issue is that is that all of the hover-over menus result in artifacting which render the contents illegible.  I can't imagine what could be causing this on my end since I don't believe I'm running anything that tampers with the display of windows.  The GUI otherwise appears to work just fine.
![artifact](https://github.com/bottlesdevs/Bottles/assets/81646252/e6dbf26c-9a73-41ac-af40-370939ac5b88)

My second issue is... perhaps I don't understand how Bottles handles executables?  I'm been attempting to run .exes which come in a folder of other resources the .exe reads from (rather than a single installer), but for whatever reason Bottles is unable to detect these files.

My best example is eDuke32 which, under Wine normally, opens a menu and automatically detects the .grp file in the same directory (which is required to launch the game), but under Bottles it can't detect the .grp file at all and therefor returns an error indicating there is no .grp file and therefor can't launch Duke Nukem.

I've tried switching from the default Windows 10 to Windows XP version in Bottles, and even switched runners from the default Soda to Caffe, but it's simply unable to locate the .grp file.  I have no idea if there's a dependency in the list that I need for Bottles to be able to see other files in the same directory as the executable I'm launching, but it hardly seems like that should be an issue.  Am I using Bottles wrong?

### To Reproduce

For first issue, hover over any GUI element with a hover-over menu.

For second issue, run any .exe with necessary resources in the same directory.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 20.3

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-139-generic
Disk:
    Total: 7319379968
    Free: 7319224320
RAM:
    MemTotal: 13.6GiB
    MemAvailable: 5.2GiB
Bottles_envs: null
```

**Comment by jannuary** [comment]
For the first, it is quite unlikely to be a Bottles issue, but something related to GTK, your graphics drivers, X or something else - we don't do anything specific with popover rendering. I'd recommend to check other GTK4 apps to see if the issue persists.

For the second - that isn't an issue but merely a byproduct of the Bottles sandboxing - Bottles cannot access your files (or, unfortunately, even neighboring files currently) so you need to drag the files into your bottle's directory manually, which Bottles tells you to do when first using the "Run executable" button

And finally, try to keep separate issues in separate tickets next time, it makes triaging easier :)

**Comment by IfGremlinThen** [comment]
> that isn't an issue but merely a byproduct of the Bottles sandboxing - Bottles cannot access your files (or, unfortunately, even neighboring files currently) so you need to drag the files into your bottle's directory manually, which Bottles tells you to do when first using the "Run executable" button

I don't recall seeing that, that doesn't appear to be mentioned in the Bottles install and "how to run" guide, and isn't referenced whatsoever in the videos I've watched demonstrating how it works, so I don't know what's going on there.

I just moved the entire program folder into the created Program Files and Program Files (x86) folders in the Windows C:\ directory Bottles makes and it still is not detecting the file.
