### ISSUE TITLE
The program question

### ISSUE THREAD

**Issue by jokuityue** [bottlesdevs/Bottles#2910]
so i just new in linux os so i dont have many experience but my question is can i run a program that dont appear on the list like "profits" because i need it, if can how to install and launch them (because when i click the program doesnt appear). thank you
![Screenshot from 2023-05-31 09-27-38](https://github.com/bottlesdevs/Bottles/assets/123615766/adaebb92-f0e9-45a5-a479-b36b5878e055)

**Comment by duarm** [comment]
Yes, click the "Run Executable" blue button and select the .exe you want to execute, you can also press the "Add Shortcuts" button and select the same .exe, and it will appear in the list where PROFITS is.
