### ISSUE TITLE
EA app do not read disk capacity corectly

### ISSUE THREAD

**Issue by musicfunfan** [bottlesdevs/Bottles#2911]
Hello there i use bottles (flatpak) on my system. 
archlinux
r5 3600
16gb ram
rx560 4gb

On sway(wlrt wayland) 

And i installed EA app. 

I was trying to install battlefront 2. And the EA reports that i do not have enough space on my hard drive. This is simple not true. My drive has 233GB free. The game needs 90GB i thing. 

How can i fix this ? I had give the access to the drive to bottles via flatseal. And most of the stuff i use bottles for works fine. I do not know why EA app do not. 

Any ideas ?

**Comment by SuperSamus** [comment]
Duplicate of #1295?

**Comment by musicfunfan** [comment]
I think so. 
I will close this then.
