### ISSUE TITLE
[Bug]: Empty dependencies page on 32-bit prefix

### ISSUE THREAD

**Issue by RushingAlien** [bottlesdevs/Bottles#2918]
### Describe the bug

When I try to manage dependencies of a wine prefix in Bottles, and the prefix is 32-bit, the dependencies page is empty.
![image](https://github.com/bottlesdevs/Bottles/assets/80886145/639cf46d-a527-436d-8b32-dd934e3bafb9)

### To Reproduce

1. Create 32-bit bottle
2. Enter dependencies page of said bottle

### Package

Flatpak from Flathub

### Distribution

Arch Linux rolling

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.6-arch1-1
Disk:
    Total: 5187477504
    Free: 5187309568
RAM:
    MemTotal: 9.7GiB
    MemAvailable: 5.3GiB
Bottles_envs: null
```

**Comment by edisionnano** [comment]
Can confirm, it happens here too
