### ISSUE TITLE
Using crossover as runner

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [bottlesdevs/Bottles#2919]
### Tell us the problem or your need

Sometimes apps don't run under vanilla wine

### Describe the solution you'd like

Codeweavers publishes the source code for [crossover](https://media.codeweavers.com/pub/crossover/source/).  Would it be possible to compile this and use it as a runner in bottles?

It would also be nice to have a parser for crossties

**Comment by A-childs-encyclopedia** [comment]
Helloooo??

**Comment by jannuary** [comment]
You can try compile it at your own accord and place it in the Bottles' runners directory. As for shipping it with Bottles, we might look into it at some point, but we are busy and we sadly do not have very limited capacity for doing so.

Also, try to avoid bumping issues you opened a day ago - it won't solve your issue faster, but it does make you look rude and entitled.
