### ISSUE TITLE
[Bug]: Wine-Gecko not installed on bottles

### ISSUE THREAD

**Issue by SeongGino** [bottlesdevs/Bottles#2940]
### Describe the bug

For whatever reason, and only *specifically* on prefixes made with Bottles, Wine-gecko does not install/register itself properly.

Regardless if Gecko is installed either via:
 - Bottle dependencies panel, or
 - The .msi installer provided directly from the Wine project

Any time an app that depends on ie/gecko is run in said prefix, the end result is:
```
00d8:fixme:urlmon:create_object Could not find object for MIME L"text/html"
00d8:fixme:ieframe:handle_navigation_error Navigate to error page
```
and the 'page' is left blank.

This only happens specifically with prefixes created and managed by Bottles; using either Lutris, or manually creating a prefix by invoking Wine directly with *the exact same Wine runner that Bottles is using* works fine. I can only guess this because, when comparing what's on the registry from a Bottles' generated prefix vs. from Wine itself or Lutris, there's significantly less entries in the Wine registry - mainly speaking of `HKEY_CLASSES_ROOT`

### To Reproduce

1. Create a new Bottle (Custom, Application, or Gaming profile doesn't matter).
2. Install Gecko from the Dependencies panel.
3. Run the prefix's `iexplore.exe` either from the Run Executable button or from the "Command Line" option in the Bottles menu.
4. Observe nothing loading.
5. Create a new prefix using Wine directly: `WINEPREFIX=/path/to/newPrefix ~/.local/share/bottles/runners/wine-version/bin/wine iexplore.exe`
6. Observe the default page able to be loaded this way.

### Package

Flatpak from GitHub Artifacts

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: false
Version: '51.6'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.9-273-tkg-pds
Disk:
    Total: 96634667008
    Free: 12052750336
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.8GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.37'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Additional context

Installed from the AUR and tested using both Soda 7.0-9 and Wine-GE-Proton8-8 as downloaded through Bottles' integrated Wine manager. Not using a Flatpak (and won't), but I'm certain this problem still exists for Flat users as evidenced by https://github.com/bottlesdevs/dependencies/issues/111 (Regarding the dependency itself) and https://github.com/bottlesdevs/wine/issues/47 (regarding Bottles' default runners) - since this affects prefixes only made with Bottles regardless of Wine version, it seemed appropriate to post the issue here.

**Comment by MrQuerter** [comment]
Last time I checked it also happened on Heroic Games Launcher (flatpak). It would be fantastic to find a fix for that since I've seen few reports of not loading some website elements in programs and so far couldn't suggest anything to solve it.

**Comment by tomer-1** [comment]
i'm experiencing the same behaviour in fedora using bottles in flatpak.

**Comment by SeongGino** [comment]
Can confirm that, at least with current -git, making a new prefix and installing gecko in that from dependencies gets correct working behavior now. Doesn't seem to retroactively affect old prefixes though.

**Comment by orowith2os** [comment]
Old prefixes probably can't be fixed - but I can try getting a release out soon (ideally, in a week or so) with all the fixes necessary.

**Comment by mc-crafty** [comment]
Just a note, when I use the latest nightly build or build directly from source:
gecko installs and works properly, but when I try to open a game I receive errors about missing DLLs
```
00f0:err:module:import_dll Library binkw32.dll not found
00f0:err:module:import_dll Library ijl15.dll not found
00f0:err:module:import_dll Library mss32.dll not found
00f0:err:module:import_dll Library cps.dll not found
00f0:err:module:import_dll Library granny2.dll not found
```
When I uninstall the nightly/manual build Gecko will not work but there are no missing DLL errors and the game window loads

**Comment by Yuzuru-Yamazaki** [comment]
> i'm experiencing the same behaviour in fedora 37 using bottles in flatpak.

same issue on 40 did you find the fix?
