### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by D13537** [bottlesdevs/Bottles#2943]
### Describe the bug

The issue I've found is the inability to update the .exe file upon update/restart request of the battle.net.exe file. I'm sure you're aware of this, however, I'm still seeking a solution. Aside, I'm really enjoying Bottles! Thanks in advance. 

### To Reproduce

1. update/restart battle.net.exe file

### Package

Flatpak from Flathub

### Distribution

Ubuntu 23.04

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.0-24-generic
Disk:
    Total: 8173727744
    Free: 8173568000
RAM:
    MemTotal: 15.2GiB
    MemAvailable: 11.7GiB
Bottles_envs: null
```

### Additional context

THX!

**Comment by mirkobrombin** [comment]
Hi, I do not understand the issue. What do you mean with “restart the file”?
