### ISSUE TITLE
[Request]: ArchImage, an AppImage built on top of JuNest (Arch Linux) to work on any GNU/Linux distro

### ISSUE THREAD

**Issue by ivan-hc** [bottlesdevs/Bottles#2947]
### Tell us the problem or your need

Bottles is only available as a Flatpak and (unofficially) as a PKBUILD on AUR (Arch Linux Repository), there are no more options available. I'd like to use a portable version of it.

### Describe the solution you'd like

I've started a repository named "ArchImage", i.e. AppImages built on top of JuNest, a lightweight Arch Linux that runs on every distro. I've also created an experimental script to built "Bottles".

## Usage
Read the script before you run it, this is just a script:

    wget https://raw.githubusercontent.com/ivan-hc/ArchImage/main/apps/bottles-junest.sh
    chmod a+x ./bottles-junest.sh
    ./bottles-junest.sh
At the end of the process, you can start the AppImage with the command

    ./*AppImage

### What works?
- the app runs, can create "bottles" and dependences, by default there is Adwaita-dark as GTK theme enabled in the AppRun

### What not works?
- tried to launch Diablo 2 and FIFA 2004, it seems to be a problem with "wineserver"

### Other solutions?

If compared with the main issue https://github.com/bottlesdevs/Bottles/issues/1272 my script should work better, I don't play or use WINE from years and I'm not a gamer, I think that you can work better on this script, if you want. 

I've already built [OBS Studio](https://github.com/ivan-hc/OBS-Studio-appimage) using this method and works well. 

What may seem unconvincing is the size of the final package, Bottles is around 700 MB. It will certainly be easier to lighten it, having everything ready. In the past, when building AppImage packages, we had to start with a few DEBs packages and guess what was missing, and if nothing worked, we ended up blowing the package out of proportion. At least here we know what we have and what we don't need to make Bottles work.

### Additional context and references

ArchImage https://github.com/ivan-hc/ArchImage
JuNest https://github.com/fsquillace/junest

**Comment by ivan-hc** [comment]
Since none have seen this feature request, I've decided to create a repo on wich you can download the AppImage for testing purposes:

https://github.com/ivan-hc/Bottles-appimage

@mirkobrombin potrebbe interessarti?

**Comment by RafaelLinux** [comment]
I just read you thread now. I left Flatpak after discover some "features" that AppImages doesn't have and would like to have again an AppImage version. I'll try your version.

**Comment by orowith2os** [comment]
Not planned, for various reasons. You can dig around the issue tracker for more context. Just use the Flatpak, that's as portable as it gets, without the downsides of.... whatever you just did.

**Comment by ivan-hc** [comment]
> Not planned, for various reasons

OK, I think I've found the reason... on your profile:

![Istantanea_2023-08-08_00-28-12](https://github.com/bottlesdevs/Bottles/assets/88724353/be7235e6-a1c5-4f2a-88d6-ba11d92cb5eb)

also your answer

> Just use the Flatpak

is all a plan, an I hope this plan is only your.

My work to package Bottles as AppImage I'm doing alone, free and on my own initiative, since there are also people who hate Flatpaks! Here I was looking for support to find an alternative solution together with those who really wanted an AppImage.You may be one of the lead developers on Bottles, but you can't treat other people's projects like trash without even allowing others to care, just because you want to "Flatpak the others"!

Adios!

**Comment by orowith2os** [comment]
This is the view of the Bottles developers, not just me. You will not gain any footing here by trying to get personal. AppImages, and every other packaging format, is not maintained by us, and we **do not support it**, nor do we have plans to. Unless we have reasonable cause to, Flatpak will be the only supported packaging format for the forseeable future.
