### ISSUE TITLE
[Request]: Make packages update in startup optional

### ISSUE THREAD

**Issue by dartvader316** [bottlesdevs/Bottles#2954]
### Tell us the problem or your need

Every time i start Bottles, i see a progress of updating its packages. This can take a pretty long time on unstable and slow connections so i have to disable network completely to avoid that and immediately get to my bottles. This is pretty annoying, to be honest.

### Describe the solution you'd like

I think the good solution will be:
- Make an option in Preferences to disable downloading package updates at startup. 
- Add a button for manual updates of packages.

### Other solutions?

This can be also solved by connection timeout, but such solution keeps annoying latency at Bottles startup.

**Comment by MrQuerter** [comment]
That's a good feature that I would use, but just dropping in to say that currently you can disable the internet connection in Flatseal (it should be the first switch) if you don't need the programs/games inside to have connection.
