### ISSUE TITLE
[Bug]: Battle.net does not update

### ISSUE THREAD

**Issue by zero-thermo** [bottlesdevs/Bottles#2955]
### Describe the bug

Battle.net displays an update notification, but does not update after selecting "Restart and Update" in the Battle.net menu.

### To Reproduce

1. Install Battle.net with default soda-7.0-9 runner
2. Change to lutris-GE-Proton8-7-x86_64 runner to run Battle.net
3. Click on "Restart and Update" in Battle.net menu
4. Wait for Battle.net to shutdown, then restart using Bottles

OBSERVED BEHAVIOR: Battle.net is not updated, and update notification still persists

EXPECTED BEHAVIOR: Battle.net successfully updates, and update notification is gone

### Package

Flatpak from Flathub

### Distribution

Pop!_OS 20.04

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: pop
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-76060012-generic
Disk:
    Total: 16784662528
    Free: 16784498688
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 12.3GiB
Bottles_envs: null
```

**Comment by SkalCore** [comment]
same here

**Comment by Bantscho** [comment]
Same!

**Comment by mirkobrombin** [comment]
use the pprograms repo ppls
