### ISSUE TITLE
[Bug]: Old pre-release component versisons not shown

### ISSUE THREAD

**Issue by JamiKettunen** [bottlesdevs/Bottles#2956]
### Describe the bug

Installed previous pre-release versions of components (such as VKD3D) cannot be removed as no entry for them is shown under `Preferences` > `DLL Components`.

### To Reproduce

1. Enable pre-releases under `Preferences`
2. Download a pre-release version of VKD3D under `Preferences` > `DLL Components` for example
3. Once a new release is available the old already-installed version (e.g. `vkd3d-proton-2.9-1-87b0c4a`) is no longer shown, making it not possible to reclaim the disk space it uses in-app after updating to the new pre-release (e.g. `vkd3d-proton-2.9-2-ff32968`)

### Package

Flatpak from Flathub

### Distribution

Void Linux

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.12_1
Disk:
    Total: 16791138304
    Free: 16790982656
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 15.5GiB
Bottles_envs: null
deathmist@palkia:~$
```

### Troubleshooting Logs

```shell
$ flatpak run com.usebottles.bottles
21:56:13 (INFO) Bottles Started! 
21:56:14 (INFO) Performing Bottles checks… 
21:56:14 (INFO) Dxvks found:
	- dxvk-2.1-1-0811813
	- dxvk-2.2-1-8b6cbda
	- dxvk-2.2-2-bd575a4
	- dxvk-2.2-3-3a368f4
 
21:56:14 (INFO) Vkd3ds found:
	- vkd3d-proton-2.6-1-5b73139
	- vkd3d-proton-2.8-1-7be64c2
	- vkd3d-proton-2.8-2-453d274
	- vkd3d-proton-2.9-1-87b0c4a
	- vkd3d-proton-2.9-2-ff32968
 
21:56:14 (INFO) Nvapis found:
	- dxvk-nvapi-v0.5.4
 
21:56:14 (INFO) Latencyflexs found:
	- latencyflex-v0.1.1-2-3bc9636
	- latencyflex-v0.1.1-1-73bcb07
 
21:56:14 (INFO) Runners found:
	- wine-ge-7-27
	- kron4ek-wine-8.11-amd64
	- GE-Proton7-49
	- sys-wine-8.0
 
21:56:14 (INFO) Bottles found:
	- osu
 
21:56:15 (INFO) Catalog installers loaded 
21:56:15 (INFO) Catalog dependencies loaded 
21:56:15 (INFO) Catalog components loaded
```

### Additional context

![image](https://github.com/bottlesdevs/Bottles/assets/47358222/23e99709-ece2-4ca7-a0ea-87fc17ea1232)

**Comment by JamiKettunen** [comment]
In https://github.com/bottlesdevs/components/commit/800c283df60c67acf63b8169be762f5af6d7568e `index.yml` and `13-vkd3d-proton.yml` just have the previous versions completely dropped which I assume is the cause of this, and the UI doesn't show any entries for "offline" (already downloaded) components

**Comment by koplo199** [comment]
Issue similar to #1244: Unfortunately the `DLL Components` does not work offline _and_ does not list already installed component. This is especially annoying for unstable components which as you noted, are replaced in the online manifest each time there's an update.

Those two issues should be merged into one as they are fundamentally duplicate, only the severity has changed : what could be viewed as a `[Feature Request]` is now definitively a `[Bug]`.
