### ISSUE TITLE
chore: Update manifest dependencies

### ISSUE THREAD

**Issue by koplo199** [bottlesdevs/Bottles#2963]
A lot of dependencies are outdated in the flatpak manifest [com.usebottles.bottles.yml](https://github.com/bottlesdevs/Bottles/blob/main/com.usebottles.bottles.yml). Updating them and regenerating [com.usebottles.bottles.pypi-deps.yaml](https://github.com/bottlesdevs/Bottles/blob/main/com.usebottles.bottles.pypi-deps.yaml) probably wouldn't hurt.

**Comment by orowith2os** [comment]
Also some preparatory work for https://github.com/flathub/flathub/pull/4329.

**Comment by koplo199** [comment]
@orowith2os If I read correctly, with https://github.com/flathub/flathub/pull/4329 the `gamescope` bin location changed from `/app/utils/gamescope/bin` to `/usr/lib/extensions/vulkan/gamescope/bin` meaning this line in the manifest should be updated to include it:
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L22

Is this correct?

Looking at the code I see at least one another place where a change would be necessary:
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/bottles/frontend/views/bottle_preferences.py#L198

**Comment by orowith2os** [comment]
Yep, sounds about right. Bottles should be using a generic `gamescope` binary from PATH otherwise.

**Comment by rporter220** [comment]
I have started receiving the following warning from flatpak:

```
Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
Info: applications using this extension:
   com.usebottles.bottles
```

Searching here this seemed that it would correct the above warning, or needs to be updated to the freedesktop branch. :-)

**Comment by orowith2os** [comment]
It needs to be updated both here and on Flathub; I don't believe I have the appropriate permissions to merge anything yet, but I will get on what I can do later.
