### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abderrahmanebenhalima** [bottlesdevs/Bottles#2965]
### Describe the bug

i'm facing this problem while installing 
.net framework 3.5 SP1
and 
.net framework 3.5
i tried to switch from win 10 to 7 even to win XP and i faced the same problem
[screenshort below]
[https://media.discordapp.net/attachments/956654626671845446/1130160303359934504/image.png?width=431&height=455](url)

### To Reproduce

when even i try to install dependency of dotnet35 and dotnet35 sp1

### Package

Flatpak from Flathub

### Distribution

linux mint

### Debugging Information

```shell
i guess it's all gui, there's no command
```

**Comment by jannuary** [comment]
Please use the issue template - we can't tell what's the issue (or even if there is one) otherwise.
