### ISSUE TITLE
[ERROR] bottle snap is not updated

### ISSUE THREAD

**Issue by Lvaskz** [bottlesdevs/Bottles#297]
**Describe the bug**
A bottle snap package is not Updated 

**Installation**
 - Method: snap package 
 - Versión     
stable 0+git.1fb2562
**To Reproduce**
1. Go to discover kde, find bottles snap
2. Click on install
3. Open bottles, go to about bottles, watch versión 3.1.10 not 3.1.12

**Expected behavior**
Have installed the version 3.1.12

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [kde neon]
 - Version [5.21.5]

**Additional context**
Translations are not working in snap package

**Comment by mirkobrombin** [comment]
Just released.

**Comment by Lvaskz** [comment]
The version of bottles 3.1.15 is not Updated in snap.  Can you update?

**Comment by mirkobrombin** [comment]
> The version of bottles 3.1.15 is not Updated in snap. Can you update?

Done!
