### ISSUE TITLE
VKD3D tied to DXVK?

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/Bottles#2973]
Quick question, is VKD3D supposed to be tied to DXVK?

I noticed if you disable DXVK in bottle settings then VKD3D also gets disabled. When you enable DXVK then VKD3D is still disabled, but if you enable VKD3D when both of them are disabled then DXVK also gets enabled.

**Comment by koplo199** [comment]
[Yes](https://github.com/HansKristian-Work/vkd3d-proton#using-vkd3d-proton).

**Comment by MrQuerter** [comment]
Alright, understandable. Closing this.
