### ISSUE TITLE
[Bug]: Can no longer browse files, "Could not show link"

### ISSUE THREAD

**Issue by brittyazel** [bottlesdevs/Bottles#2976]
### Describe the bug

When trying to browse files for one of my bottles I consistently get the error "Could not show link" "Launch failed". This happens 100% of the time across all of my bottles.

I used to be able to perform this action just fine, albeit I can't remember the last time I tried it, but I'm just coming across this regression today. Likewise, I can access the bottle files directly in the file browser (i.e. ~/.var/app/com.usebottles.bottles/data/bottles/bottles/<bottle>/drive_c) without any issue, and I have proper permissions to read/write.

![Screenshot from 2023-07-20 10-23-05](https://github.com/bottlesdevs/Bottles/assets/3747347/ba08df21-4403-4c52-a122-1b2aa1f45327)

I am using Arch Linux with GNOME 44.3, and my Bottles came from FlatHub running on Flatpak 1.15.4. I have xdg-desktop-portal and xdg-desktop-portal-gtk installed and verified working, and I have not made any permission changes for Bottles using Flatseal.

### To Reproduce

1. Enter a bottle
2. Click the "Secondary Menu" option
3. Select "Browse files..."

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.4-zen1-1-zen
Disk:
    Total: 16784289792
    Free: 16784134144
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.5GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Looks like a portal issue which I am not able to replicate. Waiting for others.

Thanks for your report!

**Comment by JHerseth** [comment]
I'm having the same issue on a Steamdeck. Working as intended on my Fedora box.

**Comment by mirkobrombin** [comment]
I have to confirm that this problem does not happen for me. It must be a portal issue. What's your file manager?

**Comment by brittyazel** [comment]
I am on Arch Linux and my file browser is Nautilus.

**Comment by mirkobrombin** [comment]
Looks like a portal issue or a missing xdg dependency. Are you able to launch the file dialog from another app? Like Lutris.

**Comment by brittyazel** [comment]
Yes sir, every other Flatpak app that uses xdg-desktop-portal-gnome has the GTK4 file dialog working fine. Granted, the GTK4 file dialog =/= Nautilus, so this isn't necessarily a reflection of the bug at hand.

To be clear, I don't have any issue with the GTK4 file dialog, and Bottles's use of the file dialog is working perfectly fine, it's just the "browse files" option that doesn't work, as it's attempting to open Nautilus itself.

**Comment by orowith2os** [comment]
VSCode likes to do that sometimes, I'm sure it's tracked somewhere.

**Comment by SeanRamey** [comment]
I have this issue as well. Using EndeavourOS.
I'm using Bottles 51.9 from flathub.

**Comment by 31kpc** [comment]
I fixed this by switching to the AUR version of Bottles

**Comment by 31kpc** [comment]
> I have this issue as well. Using EndeavourOS. I'm using Bottles 51.9 from flathub.

I fixed this by switching to the AUR version of Bottles

**Comment by Lalarian** [comment]
Any news on this? AUR verison is broken and won't run .. and flatpack version suffers from this bug :(

**Comment by brittyazel** [comment]
> Any news on this? AUR verison is broken and won't run .. and flatpack version suffers from this bug :(

This is a bug with Bottles. Somehow my default file browser got set to VSCode, and I needed to swap it back to Nautilus (or whatever file browser you use).

**Comment by Lalarian** [comment]
Thanbk you. You where right in that it was set wroing for me, too (7zFM) .
I set it to thunar.desktop and there now is another error instead, that I will have to search for.
(Like GDBus Error Unknonw Method, no such interface)
