### ISSUE TITLE
[Request] Automatic populate the Task Manager when opening

### ISSUE THREAD

**Issue by miikkuu** [bottlesdevs/Bottles#2981]
### Describe the bug

When opening the Task Manager page, no processes are shown by default. To show all processes, the user needs to explicitly click the refresh button.

### To Reproduce

Open any bottle, then go to Task Manager.

### Additional context

![image](https://github.com/bottlesdevs/Bottles/assets/50847364/8447af90-8235-463b-ab0d-32e3e67a265d)

**Comment by TheEvilSkeleton** [comment]
You need to press the Refresh button at the top right for it to detect all processes. That said, I will admit that it's bad experience; it should show it the moment you open the page.
