### ISSUE TITLE
[Bug]: flatpak: `org.gnome.Platform.Compat.i386` should be updated to `"44"`

### ISSUE THREAD

**Issue by latin-1** [bottlesdevs/Bottles#2983]
### Describe the bug

https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L37
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L41

according to

https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L6

### To Reproduce

.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
.
```

**Comment by TheEvilSkeleton** [comment]
Thanks. This will be fixed by https://github.com/bottlesdevs/Bottles/pull/2964

**Comment by mirkobrombin** [comment]
This is causing a problem with ld.so, breaking Wine. I have to investigate before doing the change.

**Comment by koplo199** [comment]
That would be strange, Lutris is using those versions without issues it seems: https://github.com/flathub/net.lutris.Lutris/blob/031ea7128eda82741d002f1243b7b2f606b98f62/net.lutris.Lutris.yml#L45-L52
