### ISSUE TITLE
[Bug]: Manage Drives - " I " selected as the Drive Letter

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#2988]
### Describe the bug

In bottle `Manage Drives` settings, selecting `I` as the drive letter, it doesn't appear beside the drop-down icon. All other drive letters do show.

![bottles_drives_i](https://github.com/bottlesdevs/Bottles/assets/53913724/958b6b4a-98ac-4d8f-ae85-3b6365771c9e)

### To Reproduce

1. Go to a bottle
2. Open Settings -> Manage Drives
3. From `Letter` drop-down selector, select `I`

### Package

Flatpak from Flathub

### Distribution

Linux Mint 20.3 Cinnamon

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-54-03/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-153-generic
Disk:
    Total: 8339095552
    Free: 8338927616
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
I am able to replicate but I think this is somewhat related to libadwaita

**Comment by mirkobrombin** [comment]
After some GTK inspection, I was able to show the "I", it's due to the composition of the AdwComboRow widget. Please report to GNOME.

**Comment by Perkolator** [comment]
Don't know where. They are not in github, I don't have accounts anywhere else.
