### ISSUE TITLE
[BUG] Path to wine in desktop file after install of windows app incorrect

### ISSUE THREAD

**Issue by jpenguin** [bottlesdevs/Bottles#299]
**Describe the bug**
Path to wine in desktop file after install of windows app incorrect

**Installation**
 - Method:  Appimage
 - Version 3.1.12

**To Reproduce**
1. Crete new software bottle
2. Install theword.net
3. Open creat desktop file in text editor
4. Look at exec line

**Expected behavior**
Exec line should read `env WINEPREFIX="/home/jpenguin/.local/share/bottles/bottles/TheWord" /home/jpenguin/.local/share/bottles/runners/chardonnay-6.8/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/jpenguin/.local/share/bottles/bottles/TheWord/dosdevices/c:/users/Public/Desktop/theWord.lnk` not `Exec=env WINEPREFIX="/home/jpenguin/.local/share/bottles/bottles/TheWord" /home/runner/work/wine/wine/winebuild_64/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/jpenguin/.local/share/bottles/bottles/TheWord/dosdevices/c:/users/Public/Desktop/theWord.lnk`
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OpenSUSE KDE
 - Version Tumbleweed

**Additional context**

**Comment by mirkobrombin** [comment]
These files are created by Wine, not Bottles, we have no control on these files. We will handle this in v4.
Ref #115
