### ISSUE TITLE
The discrete GPU selection is poorly designed and broken

### ISSUE THREAD

**Issue by Joshua-Ashton** [bottlesdevs/Bottles#2992]
The current method of grepping lspci for the GPUs is a very bad approach.

I have an AMD GPU that's my dedicated GPU, and an NV GPU that is reserved purely for VMs with no kernel or Vulkan driver associated with it.

The current approach attempts to select the NVIDIA GPU, with some non-existant ICD because there is some PCIe device with NVIDIA on it leading to no applications working in Bottles as VK_ICD_FILENAMES is an empty string. The Vulkan loader interprets this to not load any drivers at all.

Bottles should be doing absolutely nothing with ICD filenames (even what it is doing with LFX is wrong, as it isn't an ICD at all, it should be touching LFX=1 and DISABLE_LFX=1).

Even if we put aside that Bottles shouldn't be touching ICDs, this whole approach is completely flawed as... you can have DGPU and IGPUs from the same vendor very commonly in laptops which this system does not handle.

Please, leave it up to something like the Mesa Device Selection Layer that will actually do the job properly based on information the drivers give about the physical devices. This layer could easily be shipped inside the flatpak and enabled.

**Comment by TheEvilSkeleton** [comment]
Thanks. I'm unfamiliar with Vulkan and Mesa, and the code wasn't written by me. Can you give me some pointers so that I can take a look at it? If possible, is it okay to ping you so that you can review the code in future MRs?

**Comment by mirkobrombin** [comment]
Hi, please open an issue for each of the problems/requests following the template.
