### ISSUE TITLE
d3dx11 not installed with Gaming environment?

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#2998]
Is there a reason why the `d3dx11` dependency is not installed by default with the Gaming bottle environment?

**Comment by orowith2os** [comment]
I don't believe so, if d3dx9 is installed too. Should we be installing it by default? Does it matter enough to?

**Comment by Perkolator** [comment]
> d3dx9

That is installed by default in the Gaming environment. That prompted me to ask. You have good questions. Unfortunately I'm not able to answer. I don't understand these things enough. I just thought that for directx11 games one would need the `d3dx11` installed, and, as it's rather fast to install, why not have it installed by default? Though, why isn't there a `d3dx8`, `d3dx10` & `d3dx12` dependencies, I don't understand. Are these "d3d" things like .NET, as in, same product name, only versions change, though those are not real versions, i.e. updates to previous .NET's, kind of messy stuff that Microsoft is famous for? ;)

**Comment by mirkobrombin** [comment]
d3dx11 DLLs are already covered (for the majority) by DXVK and cause conflicts or reduced performance

**Comment by GrabbenD** [comment]
Thanks @mirkobrombin 

Here's a follow-up question:
Is there any reason to include `d3dx9` dependency in the default gaming profile if it's already supported by DXVK?
- `DXVK` = Direct3D 9/10/11
- `VKD3D` = Direct3D 12
