### ISSUE TITLE
Manage Drives - mounted SMB / CIFS share folders

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#2999]
I had a weird problem for a long time with custom Bottles Drives suddenly showing them as empty in running programs.

The problem is that when you have set a Drive to point to a (fstab) mounted SMB/CIFS share folder, at least reboot of the pc makes the drives show as empty in running programs. I don't reboot my laptop that often, and I **suspect** that this problem happened few times without a reboot, though I'm not able to say what would have triggered it.

I have mounted all my SMB shares under `~/.smb` folder, like `~/.smb/music`.

If I add that `~/.smb/music` folder as a drive in a bottle, it is set as `/run/user/1000/doc/<random>/music`.

After reboot (and possibly with some other event), the Drive is shown as empty in running programs. "Manage Drives" still show the drive as set.

Solution was to set the `~/.smb` as a Drive. It's a "normal" folder so it works as a Drive after reboot.

I guess this is something Bottles can't fix, it's Flatpak portals that is to blame(?). But maybe the (online) documentation could warn about this?

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. As you pointed this is not something we can fix and should be managed by the portal itself. Closing, we can continue the discussion in the #413 for the permissions part.
