### ISSUE TITLE
[Bug]: Bottles is crashing with proton feature enabled

### ISSUE THREAD

**Issue by brianx87** [bottlesdevs/Bottles#3009]
### Describe the bug

Bottles is crashing every boot within a minute of it launching, there is little else I can describe that this.

### To Reproduce

Every boot. Reinstalled, cleared user data and reinstalled, same results.

### Package

Flatpak from Flathub

### Distribution

SteamOS latest

### Debugging Information

```shell
Official Package: true
Version: '51.0'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve36-1-neptune
Disk:
    Total: 6183772160
    Free: 6183620608
RAM:
    MemTotal: 11.5GiB
    MemAvailable: 5.1GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
'LastUpdated'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 199, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 142, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 196, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 856, in check_bottles
    self.steam_manager.update_bottles()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 321, in update_bottles
    prefixes = self.list_prefixes()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 306, in list_prefixes
    int(_acf["AppState"]["LastUpdated"])
```

**Comment by larina3315** [comment]
You could open a terminal and type
flatpak run com.usebottles.bottles

this should give you/the devs some clues as to what is going wrong

**Comment by brianx87** [comment]
> You could open a terminal and type flatpak run com.usebottles.bottles
> 
> this should give you/the devs some clues as to what is going wrong

`05:41:11 (INFO) Bottles Started! 
05:41:13 (INFO) Performing Bottles checks… 
05:41:13 (INFO) Dxvks found:
         - dxvk-2.2
 
05:41:13 (INFO) Vkd3ds found:
         - vkd3d-proton-2.9
 
05:41:13 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.3
 
05:41:13 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
05:41:13 (INFO) Runners found:
         - soda-7.0-9
         - sys-wine-8.0
 
05:41:13 (INFO) Bottles found:
         - 4GB Patch
         - REHDHook
 
05:41:13 (INFO) Catalog installers loaded 
05:41:13 (INFO) Catalog dependencies loaded 
05:41:14 (INFO) Catalog components loaded 
`

**Comment by brianx87** [comment]
I seem to have resolved the issue, it appears to have been an issue with Flatseals. I reset the permissions in Flatseals, reinstalled Bottles and enabled steam proton manager for Bottles. All seems to be working without issue now.

**Comment by mirkobrombin** [comment]
Can you try to update? Latest version is 51.6, I see 51 in your log.

**Comment by brianx87** [comment]
> Can you try to update? Latest version is 51.6, I see 51 in your log.

Already updated to latest, no change, Bottles hangs once it opens so I can't disable the Steam prefix setting without having to reinstall and clear data.

**Comment by larina3315** [comment]
> without having to reinstall and clear data
you can just remove ~/.var/com.usebottles.bottles directory and it will clear your Bottles data and reset it without reinstall

**Comment by larina3315** [comment]
> > without having to reinstall and clear data

you can just remove ~/.var/com.usebottles.bottles directory and it will clear your Bottles data and reset it without reinstall
