### ISSUE TITLE
[BUG] 32bit installer doesn't work on snap

### ISSUE THREAD

**Issue by Lvaskz** [bottlesdevs/Bottles#301]
**Describe the bug**
Bottles can not install any windows app

**Installation**
 - Method: [snap package]
 - Version [/stable 0+git.652c441  ]

**To Reproduce**
1. Go to kde discover
2. Find bottles snap
3. After install create a software environment 
4. Install all dependences
5. Try to install any windows app

**Expected behavior**
Install and run any windows app into the bottles

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [kde neon 5.21.5]
 - Version [5.21.5

**Additional context**
Mlsml6 dependency can not be installed

**Comment by mirkobrombin** [comment]
Please provide a log or something next time.

By installing the snap and analyzing the log, I notice that a dependency is missing:
```
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0100:err:module:open_builtin_so_file failed to load .so lib "/home/mirko/snap/bottles/x1/.local/share/bottles/runners/chardonnay-6.8/lib/wine/i386-unix/winex11.drv.so"
0100:err:user:load_desktop_driver failed to load L"winex11.drv"
0100:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0100:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

**Comment by mirkobrombin** [comment]
Please be more specific next time, providing a log for example.
Some dependencies seem to be missing:
```
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0144:err:module:open_builtin_file failed to load .so lib "/home/mirko/snap/bottles/x2/.local/share/bottles/runners/lutris-6.4/lib/wine/winex11.drv.so"
0144:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
```

**Comment by mirkobrombin** [comment]
Tracked in #467
