### ISSUE TITLE
[Request]: Make Creating Bottle loading progress more pleasant

### ISSUE THREAD

**Issue by DartDeaDia** [bottlesdevs/Bottles#3010]
### Tell us the problem or your need

When creating a bottle, you can see a bunch of text at the bottom that tells some info about the loading progress, it can only be understood by advanced users + it doesn't look very nice.

![Creating Bottle](https://github.com/bottlesdevs/Bottles/assets/122628420/82ab4b36-6d72-41e4-ba09-0be4eb72a1f4)

I think it would be better to replace that text with a progress bar.

### Describe the solution you'd like

For example, app installing progress already has a progress bar.

![Installing](https://github.com/bottlesdevs/Bottles/assets/122628420/d2cbb3fb-ef93-4c97-abfd-2bd40e905a6f)

**Comment by orowith2os** [comment]
I'd see this as a regression, as the information shown in the logs is pretty useful - imo it would be useful to have a progress bar *and* a toggle to view the logs, if that's possible. It wouldn't be *as clean*, but it would keep the usefulness.

**Comment by mirkobrombin** [comment]
> I'd see this as a regression, as the information shown in the logs is pretty useful - imo it would be useful to have a progress bar _and_ a toggle to view the logs, if that's possible. It wouldn't be _as clean_, but it would keep the usefulness.

I agree with this.

**Comment by mirkobrombin** [comment]
as much as we want to make the experience as simple and clear as possible, wine is a tool that requires advanced knowledge and hiding that log would only be an impediment for the biggest type of user using Bottles: the power user
