### ISSUE TITLE
[Request]: Latest Dependencies

### ISSUE THREAD

**Issue by DartDeaDia** [bottlesdevs/Bottles#3012]
### Tell us the problem or your need

It's a very strange situation with dependencies, it is impossible to use the latest versions of dependencies.

Dependencies always need to be manually updated, which is quite boring and routine _(especially when you are a perfectionist and want always to have the latest versions)_

Just look at how many dependencies there are, and each has a own version.
![1](https://github.com/bottlesdevs/Bottles/assets/122628420/18c1f9e4-6c35-4997-a0fc-2ae160b13560)
![2](https://github.com/bottlesdevs/Bottles/assets/122628420/e4c5b8b8-233f-4745-9313-66c2b2f7dc7d)
![3](https://github.com/bottlesdevs/Bottles/assets/122628420/2db5c33f-8ba6-4048-8a31-1725906f10a1)

### Describe the solution you'd like

Dependencies should have a Latest release versions.

For example it could have names like:
DXVK-latest
Soda-latest
GE Wine-latest
GE Proton-latest

When using these dependencies versions, it would automatically download and use the latest version.

### Additional context and references

As an example, I can refer to Minecraft Launcher. Where players many often keep specific versions, because they play with mods, wich works only on specific versions, or play previous versions because there's a different generation of the world which is different from the newer versions.

On the launcher there's an option **Latest Release** and **Latest Snapshot** that are automatically download and use latest version.
![Minecraft Installations](https://github.com/bottlesdevs/Bottles/assets/122628420/009200ca-d965-4dc0-b246-b1f148911494)

**Comment by mirkobrombin** [comment]
Thanks for reporting. Merging with https://github.com/bottlesdevs/Bottles/issues/333
