### ISSUE TITLE
[Request] Add wine-ge-custom as runner

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#302]
Recently, the creator of proton-ge-custom, GloriousEggroll, released [wine-ge-custom](https://github.com/GloriousEggroll/wine-ge-custom), which is a custom build of WINE for Lutris.

I don't know much about WINE, but I open this issue to let you know that wine-ge-custom now exists, so you can take a look and decide whether to include in Bottles or not.

**Comment by mirkobrombin** [comment]
Thanks for reporting, I'll test it

**Comment by mirkobrombin** [comment]
Implemented in https://github.com/bottlesdevs/components/pull/21
