### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by oliiestone** [bottlesdevs/Bottles#3029]
### Describe the bug

try to launch but is not showing

### To Reproduce

  1.  Be precise.
 2.   Include exact data used during testing for easy reference.
3.    The steps have to be in the exact order.
   4. Mention pre-requisites when applicable.
 5.   Do not write composite steps. ...
6.    Always recheck your steps to reproduce on a new system, clearing all cookies and cache memory.

### Package

Flatpak from Flathub

### Distribution

steam os

### Debugging Information

```shell
'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk
```

### Troubleshooting Logs

```shell
0:25:57 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
20:25:57
```

### Additional context

i try to close the program and it shows something like a error im trying to lanch fl stuidos and not work

**Comment by oliiestone** [comment]
is true
it not work

**Comment by orowith2os** [comment]
Issues without a proper title will be closed; recreate with a title containing a short summary of the problem. Also fill out the given form.
