### ISSUE TITLE
[Request] Wayland support for Appimage

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#303]
**Describe the bug**
I cannot launch Bottles in Wayland. However, it works fine on X11.

**Installation**
 - Method: AppImage
 - Version: 3.1.12-x86_64

**To Reproduce**
1. Use Wayland
2. Launch the AppImage

**Expected behavior**
It should launch.

Output:

```
❯ ./Bottles-3.1.12-x86_64.AppImage

(bottles:54428): GLib-GIO-ERROR **: 15:21:00.632: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
fish: Job 1, './Bottles-3.1.12-x86_64.AppImage' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 34

**Comment by mirkobrombin** [comment]
Wine doesn't work on Wayland (since last time I saw it). So Bottles does not work on Wayland, it would be useless to allow the user to run it on Wayland when he cannot actually use the runners because they are incompatible. However I am monitoring Wine forks which make it compatible with Wayland but I am still waiting for an official solution.

**Comment by TheEvilSkeleton** [comment]
The app should at least launch in Xwayland. I can play games in WINE on Wayland with the help of Xwayland. However, I cannot launch the Bottles AppImage on Xwayland. I need to strictly use GNOME on X11.

**Comment by mirkobrombin** [comment]
> The app should at least launch in Xwayland. I can play games in WINE on Wayland with the help of Xwayland. However, I cannot launch the Bottles AppImage on Xwayland. I need to strictly use GNOME on X11.

We haven't included several dependencies and permissions needed to run on Wayland. I'm not sure if I can offer a good user experience there too (not being able to use Wayland) but maybe in the future (definitely after Bottles v4) I will consider that. I keep the issue open in case someone wants to collaborate by opening a PR proposing the fix.

**Comment by mirkobrombin** [comment]
I have transformed the report into a feature request, as I want to allow the use of Bottles via Wayland from 4.0. Unfortunately I cannot use Wayland due to my optimus setup but I hope to be able to test somehow anyway.

**Comment by TheEvilSkeleton** [comment]
I might be able to test for you.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/123083795-f67e4380-d40f-11eb-8d81-faed37f5f10f.png)
It seems to work in Wayland (I managed to start it using the AMD GPU) via the AUR version, I think it is a problem of the AppImage, probably some dependencies are missing.

**Comment by TheEvilSkeleton** [comment]
Yup, that was what I was trying to say all along. It's supposed to be using Xwayland but it just doesn't.

**Comment by mirkobrombin** [comment]
> Yup, that was what I was trying to say all along. It's supposed to be using Xwayland but it just doesn't.

Maybe related: https://gitlab.gnome.org/GNOME/gtk/-/issues/3680

**Comment by mirkobrombin** [comment]
Should be fixed with latest unstable release can you give me feedback?

**Comment by TheEvilSkeleton** [comment]
Nope, still doesn't work:
```
❯ ./Bottles-devel-x86_64.AppImage 
APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2

(bottles:23683): GLib-GIO-ERROR **: 16:32:30.061: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
fish: Job 1, './Bottles-devel-x86_64.AppImage' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by mirkobrombin** [comment]
> Nope, still doesn't work:
> 
> ```
> ❯ ./Bottles-devel-x86_64.AppImage 
> APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2
> 
> (bottles:23683): GLib-GIO-ERROR **: 16:32:30.061: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
> fish: Job 1, './Bottles-devel-x86_64.AppImage' terminated by signal SIGTRAP (Trace or breakpoint trap)
> ```

I was able to start it in my VM 🤔

**Comment by TheEvilSkeleton** [comment]
I'll try it on a VM then.

**Comment by mirkobrombin** [comment]
> I'll try it on a VM then.

It might depend on the desktop environment in use, I'll do more tests as soon as I can

**Comment by TheEvilSkeleton** [comment]
Reproducible on Arch GNOME VM:

![image](https://user-images.githubusercontent.com/50847364/124366503-58b02300-dc1e-11eb-900b-303a00f8e1c8.png)

Also on Arch Plasma:

![image](https://user-images.githubusercontent.com/50847364/124366531-809f8680-dc1e-11eb-8494-98f64b6ce1a0.png)

**Comment by mirkobrombin** [comment]
Maybe there is some difference in the version I compiled from my PC compared to the one compiled by GitHub

**Comment by mirkobrombin** [comment]
This is embarrassing, after testing with `echo $XDG_SESSION_TYPE` the session in use, I noticed that `x11` was used, for some reason despite choosing the Wayland session from GDM.

I can replicate the problem on a Silverblue VM (with Wayland) and after several tests I gave up. 
![image](https://user-images.githubusercontent.com/9479903/124377735-c3f50600-dcad-11eb-8031-50f310683ebe.png)

I opened an issue in the AppImage discourse, hoping someone will put me on the right way: https://discourse.appimage.org/t/appimage-doesnt-work-on-wayland-due-to-antialiasing-key-missing/2416

**Comment by mirkobrombin** [comment]
Update: to date I have not yet found a fix to the problem

**Comment by TheEvilSkeleton** [comment]
Ouch, bummer. But hey, it's better than it not working at all.

**Comment by pyrotek45** [comment]
seems like developing using flatpak would be a better format to target rather  than appimage for problems like this.

**Comment by mirkobrombin** [comment]
> seems like developing using flatpak would be a better format to target rather than appimage for problems like this.

Personally I don't use flatpak, however Bottles is already offered as Flatpak as well.

**Comment by pyrotek45** [comment]
yeah the flatpak version works great. best part about flatpaks is that theyre in their own environment. easy to install on pretty much any distro and easy to remove. appimages are kinda....eh.

**Comment by lfom** [comment]
Maybe it is related to Fedora only? I have been using Bottles (and I love it. thanks!) AppImage for a long time on Pop!_OS (it is based on Ubuntu) running Gnome 3.36/3.38 on Wayland and ir works fine (when it launches, see #481). It doesn't even require Xwayland, and I could verify using `xprop`.

**Comment by mirkobrombin** [comment]
> Maybe it is related to Fedora only? I have been using Bottles (and I love it. thanks!) AppImage for a long time on Pop!_OS (it is based on Ubuntu) running Gnome 3.36/3.38 on Wayland and ir works fine (when it launches, see #481). It doesn't even require Xwayland, and I could verify using `xprop`.

The latest releases detect wayland and fall back to xwayland automatically when running wine. Maybe one of the latest releases solved the problem?

**Comment by laxtiz** [comment]
![2021-10-04 07-25-36 的屏幕截图](https://user-images.githubusercontent.com/3883767/135775488-d850243a-eb06-482e-ba2a-8b4fcb0586ad.png)

I don't know what wrong.
But I find similar schema in `org.gnome.settings-daemon.plugins.xsettings.deprecated`

**Comment by lfom** [comment]
No problems here (Pop!_OS 21.04, Gnome 3.38.5). All `gsettings` above are found in _xsettings_, no _deprecated_ subgroup.

**Comment by mirkobrombin** [comment]
> No problems here (Pop!_OS 21.04, Gnome 3.38.5). All `gsettings` above are found in _xsettings_, no _deprecated_ subgroup.

So using wayland?

**Comment by lfom** [comment]
@mirkobrombin Yes, using Wayland here.

**Comment by mirkobrombin** [comment]
> @mirkobrombin Yes, using Wayland here.

Woo maybe one commit fixed it

**Comment by p-sam** [comment]
AFAIK Pop!_OS does not uses Wayland by default, which would be why it currently works there

**Comment by mirkobrombin** [comment]
> AFAIK Pop!_OS does not uses Wayland by default, which would be why it currently works there

I think @lfom was explicitly using wayland

**Comment by lfom** [comment]
@mirkobrombin I have updated today to Pop!_OS 21.10 and now it uses Gnome 40.4.0, and I started to have the exact same behavior as https://github.com/bottlesdevs/Bottles/issues/303#issuecomment-933050240 (Bottles will not launch anymore :cry: ).

**Comment by mirkobrombin** [comment]
> @mirkobrombin I have updated today to Pop!_OS 21.10 and now it uses Gnome 40.4.0, and I started to have the exact same behavior as [#303 (comment)](https://github.com/bottlesdevs/Bottles/issues/303#issuecomment-933050240) (Bottles will not launch anymore 😢 ).

I have been looking for a solution for months now, apparently there are many AppImages that have problems with Wayland, maybe I should force the use of XWayland.

**Comment by lfom** [comment]
Yes, WINE/Proton runs on Xwayland anyway. I think that what was happening automatically before Gnome 40.

**Comment by mirkobrombin** [comment]
> Yes, WINE/Proton runs on Xwayland anyway. I think that what was happening automatically before Gnome 40.

Prob. Can you check if it still works with xwayland?

**Comment by lfom** [comment]
`GDK_BACKEND=x11 bottles` works here (Pop!_OS 21.10, Gnome 40.4.0, Bottles 2021.12.14).

**Comment by mirkobrombin** [comment]
> `GDK_BACKEND=x11 bottles` works here (Pop!_OS 21.10, Gnome 40.4.0 + Wayland, Bottles 2021.12.14).

Nice, I'll force it, thanks
