### ISSUE TITLE
Pull requests: Update required checks

### ISSUE THREAD

**Issue by koplo199** [bottlesdevs/Bottles#3039]
With https://github.com/bottlesdevs/Bottles/commit/fbab5f186fbfc790793ab0d3481d4248b0eb69a3 SonarQube got fixed and now resides in its own [sonar.yml](https://github.com/bottlesdevs/Bottles/blob/main/.github/workflows/sonar.yml) workflow file. It seems to have been picked up automatically as check for pull requests, but it also seems the "old" one did not get deleted: it is now shown as `Expected — Waiting for status to be reported`.

It probably require a small update in the branch [settings](https://github.com/bottlesdevs/Bottles/settings/branches).

<img width="923" alt="screenshot-sonar" src="https://github.com/bottlesdevs/Bottles/assets/85577251/9bbcd4fa-8a7e-4c10-8ae2-a816e801dd88">

**Comment by pietrodicaprio** [comment]
@koplo199 do I understand correctly that the configuration has been changed after the PR was opened?

In that case a repo admin can skip the requirement
![image](https://github.com/bottlesdevs/Bottles/assets/37634431/ec346645-f77e-4f25-819a-792c70879b2b)
but I also notice that the new check does not have the `Required` label. I'll give a look to that

**Comment by koplo199** [comment]
@pietrodicaprio This behavior began after #3034 was _merged_.

The new check does have the `Required` label as shown in the screenshot, this is not the issue. The issue is that there's now two Sonar checks: the right/new one (`Sonar / Checker (pull_request_target)` in the screenshot), and  the broken/old one (`Sonar Expected — Waiting for status to be reported` in the screenshot). The old one just need to be removed from the checks, this is the only needed change.

**Comment by pietrodicaprio** [comment]
Thank you for the explanation @koplo199 , #3044 looks to be fixed now while others, like #3016 , do not show the new workflow, they may need to be rebased to trigger the new checks

**Comment by koplo199** [comment]
@pietrodicaprio I made a dummy commit in #3044 to verify it will also work for other PR, and yes it now appears to be working flawlessly :+1: I guess this issue could be closed.
