### ISSUE TITLE
[Bug]: --version currently broken

### ISSUE THREAD

**Issue by drws** [bottlesdevs/Bottles#3040]
### Describe the bug

Running `bottles -v` in v51.6 produces:

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/main.py", line 169, in do_command_line
    print(VERSION)
          ^^^^^^^
NameError: name 'VERSION' is not defined
```

### To Reproduce

1. `bottles -v`

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
no debug info
```

**Comment by orowith2os** [comment]
This appears to be an issue with an unofficial Bottles package, not the Flatpak. We don't support anything but the Flatpak, and the details you provided on this issue were a lie.
