### ISSUE TITLE
[Bug]: Not all stable DLL Components are listed after update to 51.7 (when Pre-Release setting is OFF)

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#3047]
### Describe the bug

After update to 51.7, the `DLL Components` list in Preferences does not show all stable components (when Preferences -> General -> Pre-Release = OFF). Worked fine in 51.6.

![image](https://github.com/bottlesdevs/Bottles/assets/53913724/d27581bf-45a3-4768-9bed-d22904a4665a)

### To Reproduce

1. Update to 51.7.
2. Turn OFF Preferences -> General -> Pre-Release setting.
3. Check the DLL Components list.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 20.3 Cinnamon

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-54-03/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-153-generic
Disk:
    Total: 8339095552
    Free: 8338927616
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 9.5GiB
Bottles_envs: null
```

### Additional context

"Debugging Information" shows wrong Bottles version (#3046).

**Comment by Perkolator** [comment]
`LatencyFlex` is the only one that shows all stable versions (at least now).

**Comment by Perkolator** [comment]
After uninstalling old pre-release versions (that were installed when I first installed Bottles) for DXVK, VKD3D & DXVK-NVAPI, I can see all stable versions for all components even when Pre-Release setting is OFF.

LatencyFlex list wasn't affected because I had no pre-release versions installed for that when I installed Bottles.

**Comment by koplo199** [comment]
I can reproduce, I'll produce a fix today.

**Comment by koplo199** [comment]
@Perkolator Can you confirm #3049 fixes the bug for you? You can download the build artifact [here](https://github.com/bottlesdevs/Bottles/suites/15298702923/artifacts/873594373). To install it, unzip the archive and run `flatpak install bottles.flatpak`.

You can then run it with:
`flatpak run com.usebottles.bottles//master`
To uninstall:
`flatpak run com.usebottles.bottles//master`

**Comment by Perkolator** [comment]
How can I test it without having any of the old unstable/pre-release components? Like I wrote earlier, I uninstalled all the old unstable/pre-release components. Unfortunately.

**Comment by Perkolator** [comment]
Is there a way to install old unstable/pre-release components that do not show in the GUI list? OR, could I install older Bottles version first (to get the old unstable components) somehow? I could do that in Virtualbox, then try your fix.

**Comment by koplo199** [comment]
@Perkolator That is not necessary, you could easily create "fake" pre-release components using the following method:
`cd ~/.var/app/com.usebottles.bottles/data/bottles`

From there, let's say you want to create a fake dxvk:
`mkdir dxvk/dxvk-2.3-deadbeef`

**Comment by Perkolator** [comment]
Fix confirmed. (I tested it in vbox nonetheless) Thanks!
