### ISSUE TITLE
Killing the app while it makes a bottle destroys it.

### ISSUE THREAD

**Issue by aggalex** [bottlesdevs/Bottles#305]
**Describe the bug**
Ran low on disk space when creating a bottle. The process got stuck and had to kill bottles and relaunch. Now all I get is a blank window

**Installation**
 - Method: Flathub
 - Version 3.1.11

**To Reproduce**
1. Make a new gaming bottle
2. Kill the app while it's working
3. reopen

**Expected behavior**
The window should open normally, not listing the botched bottle, or listing it as corrupted.

**Screenshots**
![image](https://user-images.githubusercontent.com/11951328/121233136-fcfeae00-c89a-11eb-8c0f-2eebb22f619a.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Comment by aggalex** [comment]
*Workaround*
Go to ~/.local/share/bottles/bottles, find the botched wineprefix and delete it.

**Comment by mirkobrombin** [comment]
This is weird, this situation should already be handled. I'll take a look

**Comment by mirkobrombin** [comment]
The bottle is now marked as broken and can be repaired directly from the bottle list.
