### ISSUE TITLE
[Bug]: Creation of new Bottle doesn't fail / give GUI error when failed to fetch dependencies

### ISSUE THREAD

**Issue by Pengukov** [bottlesdevs/Bottles#3061]
### Describe the bug

When creating a new Bottle and the dependencies fail to download, a "Success" screen is given without warning.

### To Reproduce

Note: this only works when dependencies have not yet been downloaded before or are otherwise available.
1. Start Bottles while offline (e.g. with "sudo ip link set {DEVICE} down")
2. Create new Bottle with gaming environment
3. The installer log will mention installing dependencies but skipping over them fast
4. Bottle will be created without error in the GUI ("Success Screen")
5. Dependencies will not be installed (Bottle -> Dependencies)

Files were cleaned by running "flatpak uninstall --unused --delete-data" after uninstalling Bottles for reinstall.

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue / Arch Linux

### Debugging Information

```shell
Official Package: false
Version: '51.9'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/amd_icd32.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.12-arch1-1
Disk:
    Total: 314572800000
    Free: 260489109504
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 24.3GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.38'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Troubleshooting Logs

```shell
14:57:38 (INFO) Import bundle result: ''
14:57:38 (INFO) Installing dependency [d3dx9] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [msls31] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [arial32] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [times32] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [courie32] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [d3dcompiler_43] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) Installing dependency [d3dcompiler_47] in bottle [test2].
14:57:38 (ERROR) Cannot fetch dependencies manifest.
14:57:38 (INFO) New bottle created: test2
```

### Additional context

I think in my case the problem was an active VPN, starting Bottles worked while installing dependencies failed. 
In case of internet outage or repository issues there will be no warning except in the command line.
Tested with Flatpak and non-Flatpak versions on Fedora Silverblue and Arch Linux, respectively.
In successive Bottle creations the installer also didn't mention applying the dependencies.

Related (closed) issues:
[[BUG] Installers doesn't fail if dependencies are not being installed #769](https://github.com/bottlesdevs/Bottles/issues/769)
and
[[BUG] Download fails do not block the installation process resulting in an error #929](https://github.com/bottlesdevs/Bottles/issues/929)

Expected behavior would be some sort of error message which dependencies failed before the end screen, maybe with re-try and continue option.

**Comment by koplo199** [comment]
Changing:
https://github.com/bottlesdevs/Bottles/blob/5627b5b7cc5ad2666391daf5db0c8a707af14c7f/bottles/backend/repos/repo.py#L84
To:
```Python
return False
```
Will probably fix the issue here.

**Comment by koplo199** [comment]
@Pengukov  Can you confirm #3062 fixes the bug for you? You can download the build artifact [here](https://github.com/bottlesdevs/Bottles/suites/15635300461/artifacts/892385132). To install it, unzip the archive and run `flatpak install bottles.flatpak`.

You can then run it with:
`flatpak run com.usebottles.bottles//master`
To uninstall:
`flatpak remove com.usebottles.bottles//master`

**Comment by Pengukov** [comment]
Sadly it does not, still don't get errors and just the screen with

```
Bottle Created
"test" was created successfully
[Close]
```
What did change were two lines in terminal, this does not happen on live from flathub (might be just debug info?)
```
10:26:13 (ERROR) Template 1d8fd78a-d563-43ab-a08e-2b3cdd39d62f is too small!
10:26:13 (ERROR) Template validation failed, will retry with next bottle.
```
This will not happen when dependencies are installed successfully.

The install prompt looks like this

```
Generating bottle configuration…
The Wine config is being updated…
Wine config updated!
Running as Flatpak, sandboxing userdir…
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: gaming…
Installing DXVK…
Installing VKD3D…
Installing dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable …
Installing dependency: Microsoft Line Services …
Installing dependency: Microsoft Arial Font …
Installing dependency: Microsoft Times New Roman Font …
Installing dependency: Microsoft Courier New Font …
Installing dependency: Microsoft d3dcompiler_43.dll …
Installing dependency: Microsoft d3dcompiler_47.dll …
Installing dependency: Wine mono …
Installing dependency: Wine gecko …
Installing dependency: FAudio (xaudio reimplementation, with xna support) builds for win32 …
Finalizing…
```

Terminal log:

```
10:26:09 (INFO) Import bundle result: ''
10:26:09 (INFO) Installing dependency [d3dx9] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [msls31] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [arial32] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [times32] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [courie32] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [d3dcompiler_43] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [d3dcompiler_47] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [mono] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [gecko] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) Installing dependency [faudio] in bottle [test].
10:26:09 (ERROR) Cannot fetch dependencies manifest.
10:26:09 (INFO) New bottle created: test
10:26:09 (INFO) Using Wine Runtime tool -- send_status(-u)
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: configuration in L"/var/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/test" has been updated.
10:26:13 (INFO) Caching template…
10:26:13 (INFO) Creating new template: 1d8fd78a-d563-43ab-a08e-2b3cdd39d62f
10:26:13 (INFO) Copying files …
10:26:13 (INFO) New template gaming created
10:26:13 (ERROR) Template 1d8fd78a-d563-43ab-a08e-2b3cdd39d62f is too small!
10:26:13 (ERROR) Template validation failed, will retry with next bottle.
10:26:13 (INFO) Bottles found:
	 - test
```

Debug info:

```
Official Package: true
Version: 51.9-e39a8ec
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.10-200.fc38.x86_64
Disk:
    Total: 16773406720
    Free: 16773283840
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 26.5GiB
Bottles_envs: null
```
**Offline**
What is also kinda weird is that the installer will not mention dependencies (installer window or terminal) when started in offline mode (internet cut before starting). Guess it is to be expected to not download them in offline mode but might still be confusing.
```
Generating bottle configuration…
The Wine config is being updated…
Wine config updated!
Running as Flatpak, sandboxing userdir…
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: gaming…
Installing DXVK…
Installing VKD3D…
Finalizing…
```

```
11:36:40 (INFO) Import bundle result: '' 
11:36:40 (INFO) New bottle created: test 
11:36:40 (INFO) Using Wine Runtime tool -- send_status(-u) 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: configuration in L"/var/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/test" has been updated.
11:36:44 (INFO) Caching template… 
11:36:44 (INFO) Creating new template: df86dcf8-a391-4de2-b04a-07bc5a85f0e9 
11:36:44 (INFO) Copying files … 
11:36:45 (INFO) New template gaming created 
11:36:45 (ERROR) Template df86dcf8-a391-4de2-b04a-07bc5a85f0e9 is too small! 
11:36:45 (ERROR) Template validation failed, will retry with next bottle. 
11:36:45 (INFO) Bottles found:


```
**Cut Internet**
And when I cut Internet after starting Bottles, it mentions the dependencies on the installer and log when creating the first bottle. But the second bottle will not have errors in the terminal. If I restart Bottles between the creations (and cut internet after starting Bottles), it will give errors.

```
10:32:26 (INFO) Import bundle result: '' 
10:32:26 (INFO) Installing dependency [d3dx9] in bottle [test]. 
10:32:26 (INFO) Installing dependency [msls31] in bottle [test]. 
10:32:26 (INFO) Installing dependency [arial32] in bottle [test]. 
10:32:26 (INFO) Installing dependency [times32] in bottle [test]. 
10:32:26 (INFO) Installing dependency [courie32] in bottle [test]. 
10:32:26 (INFO) Installing dependency [d3dcompiler_43] in bottle [test]. 
10:32:26 (INFO) Installing dependency [d3dcompiler_47] in bottle [test]. 
10:32:26 (INFO) Installing dependency [mono] in bottle [test]. 
10:32:26 (INFO) Installing dependency [gecko] in bottle [test]. 
10:32:26 (INFO) Installing dependency [faudio] in bottle [test]. 
10:32:26 (INFO) New bottle created: test 
10:32:26 (INFO) Using Wine Runtime tool -- send_status(-u) 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: configuration in L"/var/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/test" has been updated.
10:32:31 (INFO) Caching template… 
10:32:31 (INFO) Creating new template: a6044eb8-7c86-467a-9ca3-d91874d07b6c 
10:32:31 (INFO) Copying files … 
10:32:31 (INFO) New template gaming created 
10:32:31 (ERROR) Template a6044eb8-7c86-467a-9ca3-d91874d07b6c is too small! 
10:32:31 (ERROR) Template validation failed, will retry with next bottle. 
```
While no dependencies were installed.
(Tested both on live and artifact)

Cheers

**Comment by koplo199** [comment]
@Pengukov Thanks for your feedback. I made a correction and it should now work as expected. Can you verify it indeed fixes the issue for good using the latest [build artifact](https://github.com/bottlesdevs/Bottles/suites/15644871657/artifacts/892958360)?

**Comment by Pengukov** [comment]
It does fail the installer with a window that says "Unable to Create Bottle" and a [Close] button.

Installer:
```
Generating bottle configuration…
The Wine config is being updated…
Wine config updated!
Running as Flatpak, sandboxing userdir…
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: gaming…
Installing DXVK…
Installing VKD3D…
Installing dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable …
Failed to install dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable
```
Terminal:
```
14:44:35 (INFO) Import bundle result: ''
14:44:35 (INFO) Installing dependency [d3dx9] in bottle [test].
14:44:35 (ERROR) Cannot fetch dependencies manifest.
14:44:35 (ERROR) Failed to install dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable
```

I also cut the internet while installing, this resulted in two different behaviours
1. The installer fails like above
2. The installer hangs on "Installing dependency: Microsoft Arial Font …" (or other)
It should resume when internet is back up, but failed for me when it was down a bit longer (timeout?).
After that the installer was stuck and could be closed (except ctrl+c or other).

After failing, enabling internet and creating a new bottle will fail, and there is no indication for being offline or ability to reconnect.
Connected to #2972 

Also the folders are still present after failing, but will not show up in bottles expect when at least one (?) dependency was installed.
The bottle will also not show up until Bottles is restarted, connected to #3021 ?

Creating a bottle while in offline mode will not fail or give warning, but that seems expected behaviour (to at least get a base install).
It will give an error in the terminal
```
15:09:49 (ERROR) Template d8365677-beba-48c2-bda8-10e12e6817d3 is too small!
15:09:49 (ERROR) Template validation failed, will retry with next bottle.
```

But overall this seems like expected behaviour with feedback to the user that something went wrong.
Cheers and thanks for all the work you guys do!

**Comment by koplo199** [comment]
Thank you for your detailed report. Could you share the relevant parts of your finding (e.g the bottle not showing before a restart, and the offline breakage) in https://github.com/bottlesdevs/Bottles/issues/3021 and #2972?

It will help to understand what exactly goes wrong, and as #3062 will close this issue it will also ensure these informations stay easily accessible.

**Comment by Pengukov** [comment]
Made comments in the other issues. Hope it helps.
Have a good one, cheers
