### ISSUE TITLE
[Bug]: Applications will fail to launch with FSR and gamescope.

### ISSUE THREAD

**Issue by Equivocal90** [bottlesdevs/Bottles#3065]
### Describe the bug

Applications immediately exit if launched with FSR and gamescope enabled.

I'm pretty certain this is because gamescope changed the argument for FSR and no longer recognizes the old one.

Running app in terminal shows the below.

`gamescope-brokey: invalid option -- 'U'
See --help for a list of options.
`

### To Reproduce

1. Enable both FSR and Gamescope.
2. Launch app
3. App exits immediately.

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.11-200.fc38.x86_64
Disk:
    Total: 16777814016
    Free: 16777662464
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 25.6GiB
Bottles_envs: null
```

**Comment by orowith2os** [comment]
> I'm pretty certain this is because gamescope changed the argument for FSR and no longer recognizes the old one.

This is indeed the case. Some movement on https://github.com/bottlesdevs/Bottles/pull/2840 should fix it up, hopefully.
