### ISSUE TITLE
[Bug]: Changing Runners Sometimes Mess Up the Bottle Environment 

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#3076]
### Describe the bug

Just by changing runners several times (when game/app not working (perfectly or at all) with Soda runner, or with the 2nd runner I chose) something seems to mess up the bottle environment.

I have seen this happen with several games, and applications too. Almost every time I have changed the runner many times, this same problem has happened.

When trying to create re-producible steps for this issue, I tried few free games and at first I couldn't replicate the problem, but then I found a free game that everyone can try to replicate this.

This is really unfortunate because if the user needs to test many different runners when trying to make a game/app work, the user does not know at which point the bottle environment gets messed up and some (or perhaps all?) runners won't start the game because of that. Basically the only safe option to test many runners for a game/app is to always create a new bottle after changing the runner one time in a bottle.

Is a certain runner ("family") causing this? Or does this problem happen because of changing between different kind of runners? I have no idea what is going on. I tried to look at the terminal messages of bottles when replicating this problem but there were nothing relevant as far as I could see.

### To Reproduce

1. Download the Windows version of this game: https://georgebroussard.itch.io/the-third-wish (use the "No thanks, just take me to the downloads" link above the price field).
2. Create a new `gaming` bottle (default `Soda` runner).
3. Unpack & copy the game folder to `drive_c`.
4. Add shortcut to game .exe file.
5. Start game (Launch with terminal).

= Game works.

6. Change runner to `Caffe 7.20`.
7. Start game (Launch with terminal).

= Game works.

8. Change runner to `kron4ek-wine-8.15-staging-tkg-amd64`.
9. Start game (Launch with terminal).

= Game works.

10. Change runner back to `Caffe 7.20`.
11. Start game (Launch with terminal).

= Game doesn't start at all! Game `.exe` and `wineserver` processes are using CPU, but there's no window at all for the game. Messages in terminal:

```
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: The Third Wish.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3ed0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce RTX 2060:
info:    Driver : NVIDIA 535.54.3
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11929 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
```

### Package

Flatpak from Flathub

### Distribution

Mint 20.3 Cinnamon

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-54-03/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-153-generic
Disk:
    Total: 8339095552
    Free: 8338927616
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.2GiB
Bottles_envs: null
```

**Comment by orowith2os** [comment]
This isn't a Bottles problem. You can find similar things with other Wine-based apps and even Proton. 

You should be making a backup whenever you change the runner if it breaking is a worry for you.

**Comment by Perkolator** [comment]
How is this not a Bottles problem? Bottles allows to change a runner, doesn't warn about it in any way, nor there's documentation about it! This is ridiculous. Bottles is the one that changes the bottle environment when changing a runner for a bottle. Of course this is a Bottles problem.

**Comment by orowith2os** [comment]
Report Bottles problems here, and we can accept them - but we won't deal with what are, to be completely honest, not at all a fault of Bottles. 

*You* change the runner, *you* opt into the danger of breaking it. It could be better exposed to the user, but that's a separate problem. *We* don't do anything to affect you here. *We* don't break your bottles.
