### ISSUE TITLE
Sync translation updates from Weblate

### ISSUE THREAD

**Issue by AsciiWolf** [bottlesdevs/Bottles#3079]
There were some typos in the Czech translation of Bottles, which I have already corrected on Weblate. Unfortunately, they are not fixed in the latest version of Bottles, as the last translation sync from Weblate seems to be almost half a year ago.

Please, consider syncing the translations (merging #2883) before the next Bottles release. Thanks!

**Comment by orowith2os** [comment]
https://github.com/bottlesdevs/Bottles/commit/d33dcd979829640faf33661b2c5fdce724e2188d :)
