### ISSUE TITLE
[Bug]: When enabling "Preload Game Files" in a specific bottle's settings', executable fails to launch if path to it contains an apostrophe.

### ISSUE THREAD

**Issue by IPlayZed** [bottlesdevs/Bottles#3081]
### Describe the bug

When enabling "Preload Game Files" in a specific bottle's settings', executable fails to launch if path to it contains `'`, for instance `/home/gaming/.var/app/com.usebottles.bottles/data/bottles/bottles/Baldur's-Gate-3`.

I could not reproduce this issue when the path to the executable did not contain `'`.

### To Reproduce

1. Create a Bottle with a name containing `'` or choose an executable to launch with `'` to it's path.
2. Enable "Preload Game Files" in a bottle which you wish to launch it from.
3. Launch the executable.
4. Nothing happens.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd: &amp;id002
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.4.11-hardened1-1-hardened
Disk:
    Total: 67488403456
    Free: 67488247808
RAM:
    MemTotal: 125.7GiB
    MemAvailable: 119.3GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
18:36:08 (INFO) Launching an executable… 
18:36:08 (INFO) Using EasyAntiCheat runtime 
18:36:08 (INFO) Using BattlEye runtime 
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
/bin/sh: -c: line 1: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 2: syntax error: unexpected end of file
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

### Additional context

It is not evident _why_ the failure happens. An error message popup containing a message would be useful as a normal user might not understand that one has to launch the Bottles flatpak from the terminal to see additional information.

There should either be a check to prevent the user from choosing such path or creating a bottle with such name, but in my opinion the problem is that the shell script handling the preload is buggy, on the long term it would be better to fix it as `'` is a valid character under UNIX.

It is also true that renaming the bottle does not rename the folder's name containing the bottle, which I have realized during experimenting to narrow the issue's source. Even if it is a technical effort, the folder should be renamed as when creating the bottle the bottle's name is used, but on subsequent changes the folder's name and the name displayed by Bottles will get out of sync, causing potential confusion.

**Comment by orowith2os** [comment]
Probably fixed by quoting the commands in the launch script(s) - Bottles is, after all, more or less just that: a giant wrapper for a launch script. A stray quote could mean it all goes to hell.

Poking around the source, you should just need to change how it's utilized here (self.command, specifically):
https://github.com/bottlesdevs/Bottles/blob/ec424cbda73e9df327abc1701d1178d04c2a7da2/bottles/backend/wine/winecommand.py#L578

**Comment by IPlayZed** [comment]
> Probably fixed by quoting the commands in the launch script(s) - Bottles is, after all, more or less just that: a giant wrapper for a launch script. A stray quote could mean it all goes to hell.
> 
> Poking around the source, you should just need to change how it's utilized here (self.command, specifically):
> 
> https://github.com/bottlesdevs/Bottles/blob/ec424cbda73e9df327abc1701d1178d04c2a7da2/bottles/backend/wine/winecommand.py#L578

I do not have the setup to build and test this change in the near future, by any chance can you test it?
