### ISSUE TITLE
[Request]: Wrapper support

### ISSUE THREAD

**Issue by Rathmox** [bottlesdevs/Bottles#3088]
### Tell us the problem or your need

I need to run Wine with obs-gamecapture

### Describe the solution you'd like

Add any wrapper to the command line

like: obs-gamecapture %command%

### Additional context and references

I found how to use OBS Game capture, I needed to install a flatpak runtime. But for any other wrapper I wouldn't be able to use it.

**Comment by orowith2os** [comment]
This is already possible. See the Launch Options on each Program in your bottle, and the Launch Options bit on the gear next to Run Executable.

**Comment by Rathmox** [comment]
> This is already possible. See the Launch Options on each Program in your bottle, and the Launch Options bit on the gear next to Run Executable.

I can add parameters but I can't define a command to place before the program in the command line

I want to make `$ game` become `$ wrapper game` (wrapper being something like gamemode or mangohud)

**Comment by orowith2os** [comment]
Like I said, it's already possible, and you can use the `%command%` syntax.

**Comment by Rathmox** [comment]
> Like I said, it's already possible, and you can use the `%command%` syntax.

Oh, ok, I tried but it didn't work. it may be because of the flatpak
