### ISSUE TITLE
[Bug]: Bottles Font install issue ?

### ISSUE THREAD

**Issue by larina3315** [bottlesdevs/Bottles#3096]
### Describe the bug

I was trying to play the Windows version of Rimworld (GOG) inside a wineprefix, the game worked fine but it had no fonts.
As in places where there should be text was entirely blank.

https://www.reddit.com/r/RimWorld/comments/tb2265/rimworld_on_linux_kinda_broken/
According to this, I needed to have the Arial font installed.

I previously used Lutris, in Lutris using winetricks to install the necessary Arial font resolved my issue.
But in Bottles, even after I installed the Arial font dependency, text in the game still did not appear.
It was only after I downloaded a copy of Arial.ttf off of the internet and placed it in C:\Windows\Fonts did the text finally appear.

This leads me to believe this is a bug/regression in Bottles, as I also clearly remember using Bottles to play Rimworld a few months ago and the Arial font dependency install working fine just like Lutris.

### To Reproduce

1. Download Rimworld (GOG)
2. Install it inside a "Custom" wine-ge-proton-8-14 Bottle with Windows version set to Windows 7
3. Launch game, no fonts in the menu or anywhere else.
4. Close game, install the Arial32 font from the Dependencies tab.
5. Launch game again, still no fonts
6. Download Arial font from https://www.cufonfonts.com/get/font/download/5f28f88e2375c87237a2aef1b4b8851c
7. Extract the archive, copy the Arial.ttf file to the wineprefix/Bottle's C:\Windows\Fonts directory
8. Relaunch game, game now has fonts.

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue 39 Beta

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.4-300.fc39.x86_64
Disk:
    Total: 3039551488
    Free: 3039395840
RAM:
    MemTotal: 5.7GiB
    MemAvailable: 3.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
None
```

**Comment by larina3315** [comment]
I also took a look at another Bottles C:\Windows\Fonts where I installed the Allfonts and other font dependencies, It had ttf files for alot of MS fonts like Tahoma, Lucon etc but Arial ttf was missing, I then Installed the Arial32 dependency and Arial ttf is still missing in there.

**Comment by thunze** [comment]
The URLs provided in the `corefonts`-related manifests in [bottlesdevs/dependencies](https://github.com/bottlesdevs/dependencies) seem to be outdated. I submitted bottlesdevs/dependencies#200 to fix this.

**Comment by Rustring** [comment]
I'm now facing the same issue

**Comment by esrevinue** [comment]
Likewise, although I have installed Microsoft fonts on my system (Arch), both with and without installing allfonts on the bottle (using latest flatpak version), fonts appear terrible and unreadable.
