### ISSUE TITLE
Update to GNOME 45, Bottles 51.10

### ISSUE THREAD

**Issue by orowith2os** [bottlesdevs/Bottles#3098]
GNOME 45 was released not too long ago, and we should probably update to it so we can nab some [glib-related issues](https://github.com/bottlesdevs/wine/issues/54) along the way. While we're at it, bump the Bottles version; once https://github.com/bottlesdevs/Bottles/pull/2840 lands, we can make 51.10. 

Also see https://github.com/bottlesdevs/Bottles/pull/2977 so we can land it. 

I'd do a 52 release, but we need more activity on [the 52 milestone](https://github.com/bottlesdevs/Bottles/milestone/20)

@koplo199 would you mind making the pull request for the release and Bottles update, as well as testing the linked pull request(s)? Sorry to push so much onto you.

**Comment by koplo199** [comment]
No worries, I'll look into it.

**Comment by kbdharun** [comment]
> Also see https://github.com/bottlesdevs/Bottles/pull/2977 so we can land it.

I will merge the branch with the main and update the POT file for any new strings. After it, the PR would be synced.

**Comment by orowith2os** [comment]
Cleanups https://github.com/bottlesdevs/Bottles/pull/2531 would be nice, waiting to see if Skel had any more improvements planned for that.

**Comment by TheEvilSkeleton** [comment]
Sorry. Life has been affecting my mental health for the past few months and I'm not in a position to suggest changes. Please refrain from pinging me, as I'm not won't be contributing to Bottles anytime soon
