### ISSUE TITLE
MangoHud 0.7.0 (branch 23.08) doesn't work with Bottles

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#3107]
The new Flatpak MangoHud 0.7.0 version (branch 23.08) doesn't work with Bottles.

**Comment by orowith2os** [comment]
Going to need more information than that.

**Comment by Perkolator** [comment]
Huh? There's a setting for a bottle to enable MangoHud, a `org.freedesktop.Platform.VulkanLayer.MangoHud` branch 22.08 Flatpak needs to be installed in order to put the setting ON. On branch 22.08, MangoHud is on version 0.6.9-1, and probably isn't going to be updated anymore. New 0.7.0 version of Flatpak MangoHud is on branch 23.08, which doesn't work in Bottles. Was there are reason why you asked more information AND closed the issue at the same time? I don't get it.

**Comment by Perkolator** [comment]
> Once the [build artifact](https://github.com/bottlesdevs/Bottles/actions/runs/6372523127?pr=3112) is available, could you check if it resolve the issue?

Installed the build and Flatpak MangoHud, branch 23.08, in a "clean" VirtualBox environment and it doesn't work, Bottles still says that it's unavailable (started Bottles after installing MangoHud).

![image](https://github.com/bottlesdevs/Bottles/assets/53913724/f47e3845-7a3c-4300-93bc-f3bd43f03051)


I see that the Bottles build instructs to run `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud`, no mention of branch anymore. I think it would be user-friendly to tell something about the branches (what is the highest branch version that is supported? if there's a limitation in the future too), if not in the tooltip, but at least in the manual. Running that command gives this:

```
$ flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud
Looking for matches…
Similar refs found for ‘org.freedesktop.Platform.VulkanLayer.MangoHud’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08
   2) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08
   3) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08

Which do you want to use (0 to abort)? [0-3]:
```

> issue descriptions type "xxx isn't working" aren't helping anybody

To be honest, I'm rather surprised that more information was needed. I was trying to be quick and to the point, and save time for everybody. Bottles has a feature that uses Flatpak MangoHud, a specific branch. So I pointed out that the newest/latest version of Flatpak MangoHud is available in other branch, which doesn't work with Bottles. I thought that that was enough info.

**Comment by koplo199** [comment]
> I see that the Bottles build instructs to run `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud`, no mention of branch anymore. I think it would be user-friendly to tell something about the branches (what is the highest branch version that is supported? if there's a limitation in the future too), if not in the tooltip, but at least in the manual.

It would indeed be more user friendly, but as it is basically hardcoded the risk is that it will be forgotten on the next update and will point users to install an outdated version. Which arguably is a much worst user experience that having to manually select the latest version. Something like `org.freedesktop.Platform.VulkanLayer.MangoHud//latest` would be optimal, but afaik there's no way to specify a version like that.

> To be honest, I'm rather surprised that more information was needed. I was trying to be quick and to the point, and save time for everybody. Bottles has a feature that uses Flatpak MangoHud, a specific branch. So I pointed out that the newest/latest version of Flatpak MangoHud is available in other branch, which doesn't work with Bottles. I thought that that was enough info.

Yeah, it in fact was totally fine: I missed the "(branch 23.08)" on your initial description, which is the crucial info here. My bad.

> Installed the build and Flatpak MangoHud, branch 23.08, in a "clean" VirtualBox environment and it doesn't work, Bottles still says that it's unavailable (re-started Bottles after installing MangoHud).

I unfortunately can't reproduce. Seems the detection is a simple `wich` command, if you do a `flatpak run --command=sh com.usebottles.bottles ` followed by a `which mangohud`, what's the output?

It should be:
```
/usr/lib/extensions/vulkan/MangoHud/bin/mangohud
```

**Comment by Perkolator** [comment]
`which: no mangohud in (/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/:/usr/lib/extensions/vulkan/gamescope/bin/)`

**Comment by koplo199** [comment]
Ok I found the issue, it will be fixed on the next Bottles update (51.10). If you're willing to, you can check it also works for you with [this](https://github.com/bottlesdevs/Bottles/actions/runs/6323574716) build artifact.

**Comment by koplo199** [comment]
I also updated #3112 to include the versions, because it's not an updated/outdated issue; if the versions don't match it will simply not work.

**Comment by Perkolator** [comment]
> if you're willing to, you can check it also works for you with [this](https://github.com/bottlesdevs/Bottles/actions/runs/6323574716) build artifact.

Works. I was even able to run a small Unity game in VBox and MangoHud worked fine with it. The new version has great new features. I've been waiting very long for this update (since I saw the "Text outline" feature commit back in May 28). :)

In case you didn't know, Flatpak MangoHud won't automatically update from the 22.08 branch to the newer branch. The user has to manually do it (perhaps even first uninstall the old one). So, it might be wise to include this information in the 51.10 changelog for end users. Otherwise you might see a flood of new issues/comments how MangoHud stopped working after update. :)

**Comment by koplo199** [comment]
I believe it is not automatically updated precisely because it would break, but once Bottles (and other flatpaks that use it?) add support in their manifest, a `flatpak update` _should_ update it. It needs verification though, but it should do it.

**Comment by Perkolator** [comment]
FYI: Branch 22.08 was updated today to 0.7.0.

> It needs verification though, but it should do it.

I've never seen it happen before, though it's just my experience with these Flatpak branches. I have read some comments about this in github before and have understood that user has to do it manually.

**Comment by Perkolator** [comment]
@koplo199: Just updated Bottles to 51.10 and as I suspected, the MangoHud Flatpak did not update automatically and now it's not working in Bottles. Users needs to update it manually to make it work again. This is really unfortunate. I suggest that a notice in the release notes is published when a manual branch update is needed.

**Comment by koplo199** [comment]
There's already a notice when hovering the mouse over the now grayed out area. But it can be [improved](https://github.com/bottlesdevs/Bottles/issues/2801#issuecomment-1473024875), so pull request are welcome.

**Comment by Perkolator** [comment]
> There's already a notice when hovering the mouse over the now grayed out area. But it can be [improved](https://github.com/bottlesdevs/Bottles/issues/2801#issuecomment-1473024875), so pull request are welcome.

I meant that add a notice of this in the release in github when a branch change is made by the update. But, yeah, that suggested change in the issue you referenced would make the bottle mangohud setting/warning better.. dunno why TheEvilSkeleton didn't finish it.. his screenshot indicates that he already made some changes to the code.

**Comment by koplo199** [comment]
Because it was only a [prototype](https://github.com/bottlesdevs/Bottles/compare/main...popover-extensions) and not a full implementation.
