### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HelloMagi** [bottlesdevs/Bottles#3115]
### Describe the bug

Hi I wonder if anyone can assist me with this problem please. I'm not very tech savy but an very happy Linux user Mint 21.2.& So So excited to stumble across "bottles"which I installed from the Linux Software Manager I have tried many times to activate "Steam Proton Prefixes" without any success. I use the terminal & enter ... the copied text command….sudo “flatpak override --user com.usebottles.bottles--filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam”
  then enter my password.
But it doesn't change the prefix I have deleted bottle/s & tried but it doesn't make any difference. Are you able to walk me through to make this happen please. Thanks in advance Regards

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.2

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-86-05/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-83-generic
Disk:
    Total: 8347721728
    Free: 8347553792
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 12.1GiB
Bottles_envs: null
```

### Additional context

Hope you can help

**Comment by koplo199** [comment]
There's a missing space between `com.usebottles.bottles` and `--filsystem` here: `com.usebottles.bottles--filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam`
