### ISSUE TITLE
[Bug]: Could not get index for dependencies, installers, components repository

### ISSUE THREAD

**Issue by Rajala1404** [bottlesdevs/Bottles#3132]
### Describe the bug

If i try to open bottles it just wont setup

### To Reproduce

1. Start Bottles
2. Click throug Setup and then click on Continue
3. Makes something and just stops

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.5.7-arch1-1
Disk:
    Total: 6130483200
    Free: 6130311168
RAM:
    MemTotal: 11.4GiB
    MemAvailable: 4.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
20:04:56 (INFO) Bottles Started! 
20:05:22 (ERROR) Could not get index for dependencies repository: (28, 'Resolving timed out after 4793 milliseconds') 
20:05:22 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4788 milliseconds') 
20:05:22 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 4787 milliseconds') 
20:05:22 (ERROR) Could not get index for installers repository 
20:05:22 (ERROR) Could not get index for components repository 
20:05:22 (ERROR) Could not get index for dependencies repository 
20:05:22 (INFO) Performing Bottles checks… 
20:05:22 (INFO) Runners found:
         - sys-wine-8.0.2
 
20:05:27 (INFO) No installers found! 
20:05:27 (INFO) No dependencies found! 
20:05:36 (INFO) Performing Bottles checks… 
20:05:36 (WARNING) No dxvk found. 
20:05:41 (WARNING) No vkd3d found. 
20:05:46 (WARNING) No nvapi found. 
20:05:51 (WARNING) No latencyflex found. 
20:06:02 (WARNING) No WineBridge found. 
20:06:02 (INFO) Runners found:
         - sys-wine-8.0.2
 
20:06:02 (WARNING) No managed runners found. 
20:06:07 (INFO) No dependencies found! 
20:06:07 (INFO) No installers found!
```

### Additional context

I see the same issue but the Soulutions not Working and im in Germany

**Comment by xioren** [comment]
This looks like a DNS issue with your pc/network.

**Comment by Rajala1404** [comment]
> This looks like a DNS issue with your pc/network.

This is not the Case because i can reach the Site with my browser and i have the Cloudflare DNS server and also tried the Google DNS Server

**Comment by xioren** [comment]
```(28, 'Resolving timed out after 4793 milliseconds')``` is a cURL error stating it timed out while performing a DNS lookup. This seems to be a network issue, not a Bottles issue and is not reproducible. Please verify B

**Comment by Rajala1404** [comment]
> ```(28, 'Resolving timed out after 4793 milliseconds')``` is a [cURL](https://curl.se/docs/manpage.html) error stating it timed out while performing a DNS lookup. This is not reproducible and does not appear to be a Bottles issue. Please verify Bottles has the correct network permissions.

But why where was an DNS look up error it makes no sense and how can i fix this

**Comment by soufrabi** [comment]
is there a way to manully add those indexes ?

**Comment by Rajala1404** [comment]
> is there a way to manually add those indexes ? Are the indexes being pulled using raw.githubusercontent urls ?
Its possible but it will not work to use the App or create any bottles or add modules

**Comment by soufrabi** [comment]
Well i found a way
use torctl  to route traffic through tor
open the flatpak
once the installer downloads the components 
then disable torctl

@Rajala1404 could you please check if you can download the components after using torctl.
Its a simple script at <https://github.com/BlackArch/torctl/>

**Comment by Rajala1404** [comment]
> Well i found a way use torctl to route traffic through tor open the flatpak once the installer downloads the components then disable torctl
> 
> @Rajala1404 could you please check if you can download the components after using torctl. Its a simple script at https://github.com/BlackArch/torctl/

Yes this works
