### ISSUE TITLE
[Bug]: Health check does not consider WAYLAND_SOCKET

### ISSUE THREAD

**Issue by i509VCB** [bottlesdevs/Bottles#3134]
### Describe the bug

The health check does not check for a `WAYLAND_SOCKET` environment variable when detecting Wayland. https://github.com/bottlesdevs/Bottles/blob/af3a7ccf44cd17d40160b1db66a5c8177b6f4cf5/bottles/backend/health.py#L105-L109

Is is possible for `WAYLAND_SOCKET` to be used in a case where the compositor may directly spawn bottles vs bottles connecting via the normal `WAYLAND_DISPLAY` name. When `WAYLAND_SOCKET` is in the environment, libwayland-client will use the direct socket over the display variable.

### To Reproduce

N/A

### Package

Flatpak from Flathub

### Distribution

N/A

### Debugging Information

```shell
N/A
```

### Troubleshooting Logs

```shell
N/A
```

**Comment by orowith2os** [comment]
You can just do an `or` check for `WAYLAND_SOCKET` and submit a patch; it might take a hot minute to land though, nobody's really working on Bottles right now.
