### ISSUE TITLE
[Bug]:  critical error when starting taxpool accounting program on bottles

### ISSUE THREAD

**Issue by gilunixuser** [bottlesdevs/Bottles#3136]
### Describe the bug

If I start an already self installed accounting programm named  taxpool:
https://www.taxpool.net/downloads/taxpool-buchhalter.html
direct download: https://www.taxpool.net/tpb_update2/tpb_install-2023.zip

it first shows always a notice that there is a critical error.
![bottles-program error](https://github.com/bottlesdevs/Bottles/assets/78868813/30a57570-dd9c-417b-89f9-8228e753f076)
Here  in detail:
[backtrace.txt](https://github.com/bottlesdevs/Bottles/files/13068696/backtrace.txt)

### To Reproduce

see comment above.

### Package

Flatpak from Flathub

### Distribution

Manjaro Linux KDE Plasma

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.1.55-1-MANJARO
Disk:
    Total: 12544299008
    Free: 12544126976
RAM:
    MemTotal: 23.4GiB
    MemAvailable: 16.5GiB
Bottles_envs: null
```

**Comment by xioren** [comment]
What leads you to believe this is a Bottles bug?

**Comment by gilunixuser** [comment]
So I should post this problem directly to wine in your opinion?

**Comment by xioren** [comment]
First I would try a different runner, I assume you are using the default Soda runner which is out of date. Try installing and using a wine/proton ge runner. You might also try setting a different version of Windows in the bottle settings. If all else fails then yes you might report the bug to [WINE](https://bugs.winehq.org/).

**Comment by gilunixuser** [comment]
I do not know and see any way to install a different runner. 
How can I install wine/proton ge runner?

At least I could select the runner sys-wine-8.0.2.
And increadable it works now!!!
So may be bottles should set a different runner by default not an out of date one.

There are a lot of settings/changes  which can be set in bottles. Which are the most relevant ones, if something is not working?

Thank you.

**Comment by cybin** [comment]
Click on the sandwich menu (upper right corner) and open Preferences. There is a 'Runners' tab where you can install various runners.

**Comment by orowith2os** [comment]
Closing, as this is not a Bottles issue.
