### ISSUE TITLE
[Request]: Is there any method to theme Bottles?

### ISSUE THREAD

**Issue by AligatorRicardo** [bottlesdevs/Bottles#3141]
### Describe the request

According to bottlesdevs/Bottles#2886, Bottles blocks the most common way to theme GTK4 Flatpaks in the GTK_THEME flag that works for all apps EXCEPT BOTTLES and allowing access to .config/gtk-4.0 also doesn't do anything. I understand theming is not official and may  break, but user should at least have the freedom to have some way to do it. 
Is there any way to theme Bottles flatpak? 

### To Reproduce

1. Define GTK_THEME=Catppuccin-Mocha-Standard-Mauve-Dark
2. Get a themed Bottles as happens for any other GTK 4 Flatpak (Expected)
3. It is still using default light libadwaita.

### Package

Flatpak from Flathub

### Distribution

Flatpak Runtime on NixOS 23.05, should affect all distributions.

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: /nix/store/wcxx4angs8yrgcm18icc1bl3c65ffw8r-desktops/share/wayland-sessions/hyprland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.56
Disk:
    Total: 1779785728
    Free: 1779634176
RAM:
    MemTotal: 3.3GiB
    MemAvailable: 903.0MiB
Bottles_envs: null
```

**Comment by orowith2os** [comment]
> Bottles blocks the most common way to theme GTK4 Flatpaks in the GTK_THEME flag that works for all apps EXCEPT BOTTLES

No. This variable does not, and never will, work properly, and that goes for more than just Bottles; any modern GNOME app *can* and *will* break if you try and set GTK_THEME on it. You should be using proper GTK CSS modifications, preferably with Gradience, if you actually want to theme anything, but expect no support from us, or anybody else. You are on your own.
