### ISSUE TITLE
[Bug]: Enabling NVAPI sets dxvk.conf, overriding individual program's dxvk.conf

### ISSUE THREAD

**Issue by SeongGino** [bottlesdevs/Bottles#3149]
### Describe the bug

If NVAPI is enabled, Bottles creates a dxvk.conf in the wine prefix's root. As a consequence of this, dxvk.conf files that reside in a program's directory is not being respected.

### To Reproduce

1. Enable NVAPI
2. Make a dxvk.conf in a game directory next to the exe, with obvious overrides like:
```
dxgi.syncInterval = 0
d3d9.presentInterval = 0
# these force-disable vsync in a D3D9-11 app
```
3. Start the program in question
4. Observe the application settings not being respected
5. Disable NVAPI
6. Remove the dxvk.conf from the root of the bottle/wineprefix
7. Start the same program as step 3
8. Observe the application settings now being respected

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.8-273-tkg-linux-tkg-pds
Disk:
    Total: 8336732160
    Free: 8336564224
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.4GiB
Bottles_envs: null
```

### Additional context

The game(s) in question don't have vsync adjustment themselves, hence the need to force it off. This applies to any setting though, like anisotropy.

**Comment by xioren** [comment]
If I understand the issue correctly your existing dxvk.conf is in a different location than the one Bottles creates (resulting in two separate dxvk.conf files) and the Bottles dxvk.conf is overriding your existing one?

**Comment by SeongGino** [comment]
> If I understand the issue correctly your existing dxvk.conf is in a different location than the one Bottles creates (resulting in two distinct dxvk.conf files) and the Bottles dxvk.conf is overriding your existing one?

This is exactly the issue, correct.

**Comment by koplo199** [comment]
Latest commit in #3117 should fix it
