### ISSUE TITLE
[Question] In-Game Videos not playing - Bug?

### ISSUE THREAD

**Issue by CaptainCoward** [bottlesdevs/Bottles#3151]
At this point i'm not sure if this is a bug or related to missing components.

Normaly videos would just play fine in the games i installed using the Wine-GE runners. However since i'm on a fresh install Videos just refuse to play even on the same  Runner Version i used before so i guess something must be missing.. I followed all instructions related to Gstreamer and tried the `BOTTLES_USE_SYSTEM_GSTREAMER=1 bottles`  variable in different combinations (something which i didn't need on my previous installation where it  worked right away after installing Bottles). I installed literally everything i could find via `Pacman -Ss `related to gst and gstreamer, and all the video-acceleration packages for  VD-PAU and VAAPI and yet: No In-Game-Video Playback. 
I ran the games via Terminal though there is no Warning related to this. All i get is a White/Blank Screen whenever there should be a Video. The only Runner which seems to have Videos is "kron4ek 8.18 staging" which is giving me horrible performance. Videos work on Steam, Lutris etc (with runners that refuse to have Video on Bottles).. though i'm used to Bottles and really would like to get this working again. 
At this point my only guess is that is related to the current bottles version because i can't think of anything that i haven't tried yet.

**Comment by xioren** [comment]
Not much we can do without logs. Are you trying with the same version GE runner that previously worked or a newer version?

**Comment by CaptainCoward** [comment]
I'm using the Flatpak version of Bottles. I first tried to import my old bottle but since videos wouldn't play i created a new bottle and reinstalled the games. Though the issue remained the same. I can't be 100% certain if the dependencies are 1:1 the same but i installed everything i could think off and used the same runner as before.
What log do you need? I'll upload the output of my Terminal.
The Game will start and run fine though the Intro Videos are skipped. While all other videos in-game are either a whitescreen or get skipped as well. It's like no Wine-GE Version is showing Videos anymore.

What's odd about this is. Soda-Experimental seems to work. Yet Soda prints a lot about missing Gstreamer files.  I honestly have no clue what i'm missing here. I have installed everything related to Gst and Gstreamer that i could find.
`wine:498): GStreamer-WARNING **: 23:37:33.708: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsndfile.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsndfile.so: wrong ELF-Class: ELFCLASS64
`
WineGE doesn't print anything like this - Videos just wont work. 
[bottlesWineGE.txt](https://github.com/bottlesdevs/Bottles/files/13313472/bottlesWineGE.txt)
![example](https://github.com/bottlesdevs/Bottles/assets/15695543/4f8020e8-7afa-4bc4-b2d6-29169b418145)

**Comment by xioren** [comment]
You can ignore those Soda warnings. After running Bottles from terminal look for a Kebab menu (three dots) on the right side of each installed program, from there select "lauch with terminal" on a game your having issues with. I would need to see if there is any relevant output to either terminal when the game tries to play a video.

**Comment by CaptainCoward** [comment]
Okay i did what you told me. Started  Bottles via Terminal, then in bottles i used the "launch with Terminal" Option. In-Game i then clicked on a Video after that didn't play i went back to the Main Menu.
I'll upload both. The "regular" Terminal log and  The Log of the Bottles-Terminal. 
[terminal.txt](https://github.com/bottlesdevs/Bottles/files/13318253/terminal.txt)
[Bottles-Terminal.txt](https://github.com/bottlesdevs/Bottles/files/13318256/Bottles-Terminal.txt)

**Comment by xioren** [comment]
Yeah using environment variables in Bottles is finicky at best. I don't believe there is a blanket way to prefer system libraries but I could be wrong. You might try setting a DLL override in the bottle settings. Try setting ```winegstreamer``` to ```Native, then Builtin```.

**Comment by CaptainCoward** [comment]
Tried that.. sadly didn't work neither. I think i'm giving up on this for now and just use heroic launcher.. till i get another idea. Ty though for your patnience and support :)
