### ISSUE TITLE
[Bug]: Battle.net doesnt install

### ISSUE THREAD

**Issue by abrasmelin** [bottlesdevs/Bottles#3159]
### Describe the bug

I can not install battle.net . It says installation failed! dependencies installation failed.

### To Reproduce

1-Click Install Programs
2-Select Blizzard Battle.net
3-Click Start Installation
4-Get Installation Failed message.

### Package

Flatpak from Flathub

### Distribution

fedora 39

### Debugging Information

```shell
Official Package: false
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib64/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.11-300.fc39.x86_64
Disk:
    Total: 998500204544
    Free: 965035278336
RAM:
    MemTotal: 125.7GiB
    MemAvailable: 120.8GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.38'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

**Comment by xioren** [comment]
Please run flatpak from the terminal and post the output from the installation.

**Comment by orowith2os** [comment]
This is both an invalid issue (not from our Flatpak - the report says so, and the selection you made while filing the issue was a lie), and probably a duplicate of another issue regarding Battle.net. And it would probably be better to go to bottlesdevs/programs, not Bottles.
