### ISSUE TITLE
Program Install and runs fine , but its never added to the shortcust in the bottle

### ISSUE THREAD

**Issue by stccorp** [bottlesdevs/Bottles#3172]
I am installing SQLYog.  I have my bottle, I click on Run Executable, the program install and runs fine.  The problem is that after I close, I dont see the program anywhere.  I am a complete noob with bottles so not sure If I need to do something else so I dont have to re-install the program every time I want to use it.  

Something interesting is that my database connections are still there in the bottle when I re-install the program. Is just the "shortcut" to the program that is never created.

Thank you

**Comment by orowith2os** [comment]
If the app itself doesn't create a shortcut, it won't show up. We can't resolve anything if it isn't a Bottles issue. So is it an app issue, or Bottles issue? Do other apps install just fine?

**Comment by stccorp** [comment]
The apps installs fine.  So I should contact the company and tell them to add somekind of shortcut??

Thank you

**Comment by orowith2os** [comment]
Install other apps and see if they have a shortcut. If they do, bug the company to add one. You should also poke around in the bottle's files to see if it does anything to actually attempt to install a shortcut.

**Comment by stccorp** [comment]
Thank you, that worked. I just had to create  the shortcut myself
