### ISSUE TITLE
[Bug]: Could not get index for components repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4998 ms: Couldn't connect to server")  00:27:57 (ERROR) Could not get index for dependencies repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4996 ms: Couldn't connect to server")  00:27:57 (ERROR) Could not get index for installers repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4997 ms: Couldn't connect to server")  00:27:57 (ERROR) Could not get index for components repository  00:27:57 (ERROR) Could not get index for installers repository  00:27:57 (ERROR) Could not get index for dependencies repository 

### ISSUE THREAD

**Issue by yangle1988** [bottlesdevs/Bottles#3185]
### Describe the bug

0:23:04 (INFO) No installers found! 
00:23:05 (INFO) No dependencies found! 
(deck@steamdeck ~)$ flatpak run com.usebottles.bottles
F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
00:27:45 (INFO) Bottles Started! 
00:27:57 (ERROR) Could not get index for components repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4998 ms: Couldn't connect to server") 
00:27:57 (ERROR) Could not get index for dependencies repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4996 ms: Couldn't connect to server") 
00:27:57 (ERROR) Could not get index for installers repository: (28, "Failed to connect to rjtt.mirror.usebottles.com port 443 after 4997 ms: Couldn't connect to server") 
00:27:57 (ERROR) Could not get index for components repository 
00:27:57 (ERROR) Could not get index for installers repository 
00:27:57 (ERROR) Could not get index for dependencies repository 
00:27:57 (INFO) Performing Bottles checks… 
00:27:57 (INFO) Runners found:
         - sys-wine-8.0.2
 
00:27:58 (INFO) No dependencies found! 
00:27:58 (INFO) No installers found! 

### To Reproduce

flatpak run com.usebottles.bottles

### Package

Flatpak from Flathub

### Distribution

steamos

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.52-valve9-1-neptune-61
Disk:
    Total: 7767027712
    Free: 7766876160
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 9.2GiB
Bottles_envs: null
```

**Comment by yangle1988** [comment]
问题已经得到解决，原来是没有开全局代理。

**Comment by freechelmi** [comment]
Could you edit your title please ?

**Comment by mirkobrombin** [comment]
Not going to take this as a serious report.
