### ISSUE TITLE
[Bug]: Installing Bottles on Ubuntu 22.04.3 LTS 

### ISSUE THREAD

**Issue by Ken53** [bottlesdevs/Bottles#3187]
### Describe the bug

Got errors during install of Bottles on Ubuntu.

### To Reproduce

1. Install Ubuntu 22.04
2. Do all the standard updates
3. sudo su
4. apt update && apt upgrade
5. apt install <list of packages kept back>
6. sudo apt install flatpak
7. sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
8. sudo reboot
9. flatpak install flathub com.usebottles.bottles
10. Scroll up in the terminal and look at the above errors.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.3 LTS 

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: ubuntu-xorg
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors: {}
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.0-37-generic
Disk:
    Total: 3083632640
    Free: 3083476992
RAM:
    MemTotal: 5.7GiB
    MemAvailable: 4.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
Here is a sample of the errors, I get during install:

(wine:1879): GStreamer-WARNING **: 14:14:30.132: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstgdkpixbuf.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstgdkpixbuf.so: wrong ELF class: ELFCLASS64

(wine:1879): GStreamer-WARNING **: 14:14:30.132: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanagerbad.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanagerbad.so: wrong ELF class: ELFCLASS64

(wine:1879): GStreamer-WARNING **: 14:14:30.132: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsteffectv.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsteffectv.so: wrong ELF class: ELFCLASS64
```

### Additional context

I fist got onto the issue, when I was running a program in bottles. That is when I found out that I was getting the same errors during the installation.

**Comment by xioren** [comment]
Those are warnings not errors. Are you unable to perform some task or just noticed those warnings?
