### ISSUE TITLE
[Request] Duplicate prefixes

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#320]
**Is your feature request related to a problem? Please describe.**
I want to use the same prefix with all the settings I did but with a different wine version,if I could copy a prefix then I would just have to change the wine version instead of changing everything the same.

**Describe the solution you'd like**
Being able to copy a prefix.

**Comment by mirkobrombin** [comment]
Do you intend to be able to clone a bottle?

**Comment by Toadfield** [comment]
yes

**Comment by Toadfield** [comment]
Is it already possible to do this somehow?

**Comment by Toadfield** [comment]
If it's already possible,then how can I do it manually?

**Comment by mirkobrombin** [comment]
> If it's already possible,then how can I do it manually?

Simply clone the bottle folder from `~/.local/share/bottles/bottles` and edit the `bottle.json`
