### ISSUE TITLE
[Bug]: Crashing when opening Preferences

### ISSUE THREAD

**Issue by Kagukara** [bottlesdevs/Bottles#3201]
### Describe the bug

I had just installed flatpak and restarted my PC to test for a different bug, but when I press Ctrl+, or click on "Preferences" to bring up the preferences window I can't click on anything and a few seconds later bottles crashes.

This crash almost never happens on the AUR package but when it does its usually when you click on "Preferences" but you can still click around on before it does crash.

### To Reproduce

1. Install flatpak
   - `sudo pacman -S flatpak`
2. Restart PC
3. Install bottles via flathub
   - `flatpak install flathub com.usebottles.bottles`
4. Run bottles
   - `flatpak run com.usebottles.bottles`
5. Click on the kebab menu (︙) then "Preferences" or Press Ctrl+,
6. Bottles Crashes

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information
```shell
Official Package: true
Version: '51.9'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.7-arch1-1
Disk:
    Total: 33666330624
    Free: 33666179072
RAM:
    MemTotal: 62.7GiB
    MemAvailable: 57.4GiB
Bottles_envs: null
```
### Troubleshooting Logs
```shell
$ flatpak run com.usebottles.bottles
12:58:15 (INFO) Bottles Started! 
12:58:16 (INFO) Performing Bottles checks… 
12:58:16 (INFO) Dxvks found:
	- dxvk-2.3
 
12:58:16 (INFO) Vkd3ds found:
	- vkd3d-proton-2.11
 
12:58:16 (INFO) Nvapis found:
	- dxvk-nvapi-v0.6.4
 
12:58:16 (INFO) Latencyflexs found:
	- latencyflex-v0.1.1
 
12:58:16 (INFO) Runners found:
	- soda-8.0-2
	- sys-wine-8.0.2
 
12:58:16 (INFO) Catalog installers loaded 
12:58:16 (INFO) Catalog dependencies loaded 
12:58:16 (INFO) Catalog components loaded 
Gdk-Message: 12:58:27.119: Error reading events from display: Connection reset by peer
```
### Additional context
- WM: sway version 1.8.1

**Comment by mirkobrombin** [comment]
Cannot replicate
