### ISSUE TITLE
[Request]:  a mac os version

### ISSUE THREAD

**Issue by fadi123go** [bottlesdevs/Bottles#3206]
### Tell us the problem or your need

Some mac users may want to to use windows apps. Crossover has a mac version and I think you should as well.

### Describe the solution you'd like

so please would you create a mac version.

**Comment by Kodehawa** [comment]
tried https://github.com/Whisky-App/Whisky?

**Comment by elnappo** [comment]
Sadly the awesome [Whisky app is no longer maintained](https://docs.getwhisky.app/maintenance-notice). So there is again the need for an alternative. But I guess the hardest part is not porting Bottles to macOS but instead create a version of wine with the [GPTK](https://developer.apple.com/games/game-porting-toolkit/) from Apple.
