### ISSUE TITLE
[Bug]: bottles not resizing correctly having broken layout[new update bug]

### ISSUE THREAD

**Issue by chiefdinkan** [bottlesdevs/Bottles#3214]
### Describe the bug

The layout shouldn't be like this 

![image](https://github.com/bottlesdevs/Bottles/assets/87846149/6fba033e-e718-4dad-96b2-f7f31386fc84)
![image](https://github.com/bottlesdevs/Bottles/assets/87846149/aa527a33-c1c4-45fd-bef1-edb9fe6f020a)
only like this from the new update

### To Reproduce

1.open bottles

### Package

Flatpak from Flathub

### Distribution

arch linux

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: hyprland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.6.6-arch1-1-g14
Disk:
    Total: 8249311232
    Free: 8249126912
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 10.8GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
~  flatpak run com.usebottles.bottles                                                                                                                                          
(process:2): Adwaita-WARNING **: 09:46:54.072: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
09:46:54 (INFO) Bottles Started!

(bottles:2): Gtk-WARNING **: 09:46:54.194: AdwViewSwitcher 0x560d5f2bc4d0 (viewswitcher) reported min height -6, but sizes must be >= 0
09:47:00 (INFO) Performing Bottles checks…
09:47:00 (INFO) Dxvks found:
         - dxvk-2.3
         - dxvk-gplasync-v2.3-1
         - dxvk-2.3-2-4d97468

09:47:00 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11
         - vkd3d-proton-2.10-3-5e31159

09:47:00 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4-2-03cc59d
         - dxvk-nvapi-v0.6.4-1-ed4338f

09:47:00 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1

09:47:00 (INFO) Runners found:
         - soda-8.0-2
         - wine-ge-proton8-25
         - kron4ek-wine-8.16-staging-tkg-amd64
         - sys-wine-8.0.2

09:47:00 (INFO) Bottles found:
         - hmmm

09:47:01 (INFO) Catalog components loaded
09:47:02 (INFO) Catalog installers loaded
09:47:03 (INFO) Catalog dependencies loaded
09:47:28 (INFO) Setting Key sync=fsync for bottle hmmm…
09:47:28 (INFO) There is no running wineserver.
```

**Comment by HammyHavoc** [comment]
Yes, seeing this too. Very annoying.

**Comment by abhishekpapanna** [comment]
I am seeing this too. This was after the update. Is it only on Arch?

**Comment by HammyHavoc** [comment]
> I am seeing this too. This was after the 51.10 update. I am seeing this on Arch Plasma. I have one more machine with POP-OS and there I don't see this issue.

I'm seeing it on Kubuntu.

**Comment by nate-moo** [comment]
I too am having this issue on arch linux + KDE plasma wayland

**Comment by nate-moo** [comment]
I fixed it by disabling Wayland access using flat seal, as it seems to be a Wayland specific issue

**Comment by HammyHavoc** [comment]
I enabled the Kubuntu backports repository then updating my system, that fixed the GTK issues. So, I assume the problem is more one of running an LTS distro that's behind on bug fixes for breaking changes than it is perhaps specifically a Bottles one. Someone more clued-up than me can probably confirm or deny that. :- )

Wishing you all excellent health and happiness throughout 2024 and beyond. May your frame rates be high and your system stability be rock-like.

**Comment by AccaliaDeElementia** [comment]
Flatpak release 51.11 appears to have resolved this issue. Updating to that version and granting it wayland access again via flatseal shows proper behavior.

I believe this issues is now resolved

**Comment by chiefdinkan** [comment]
> I believe this issues is now resolved

Still present for me in the latest flatpak release .

**Comment by AAndonio** [comment]
The problem is still present for me too on 51.11
