### ISSUE TITLE
[Bug]: Crash on launching flatpak

### ISSUE THREAD

**Issue by aadilayub** [bottlesdevs/Bottles#3216]
### Describe the bug

The program crashes and refuses to launch, when running the flatpak.

### To Reproduce

1. Install Bottles from Flathub
2. Run the program

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue 39

### Debugging Information

```shell
It is not possible to run this command.
```

### Troubleshooting Logs

```shell
~ took 11s 
❯ flatpak run com.usebottles.bottles
Traceback (most recent call last):
  File "/app/bin/bottles", line 44, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 30, in <module>
    from bottles.backend.managers.manager import Manager
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 39, in <module>
    from bottles.backend.managers.component import ComponentManager
  File "/app/share/bottles/bottles/backend/managers/component.py", line 25, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (8.2.1-DEV) is older than compile-time version (8.4.0-DEV)
```

**Comment by fredinwheel** [comment]
I've had a chance to try and reproduce this error today in relation to #3213  but I haven't come across it. Bottles launched normally both from the CLI and GUI. Apart from the problem in the above mentioned issue, there didn't seem to be any issues with Bottles on my Silverblue setup. Could there be something you configured in your system that causes this error?

**Comment by aadilayub** [comment]
> Could there be something you configured in your system that causes this error?

Unfortunately I don't know enough about Flatpak to tell if that is the case. I've digged up some more info from [Warehouse](https://flathub.org/apps/io.github.flattool.Warehouse). Is there anything out of the ordinary here:

![image](https://github.com/bottlesdevs/Bottles/assets/31581044/3185699c-3818-4d1a-9d64-e7937e559b79)

**Comment by aadilayub** [comment]
From #3213:

> Let's take https://github.com/bottlesdevs/Bottles/issues/3216 for example, it's 100% caused by a shitty frontend for flatpak that updated Bottles without updating the GNOME runtime (org.gnome.Platform). And depending on how disastrous that software is, it may or may not be fixed by a simple flatpak update.

For the record, I only installed Bottles from GNOME Software (with Flathub as the only flatpak remote), and didn't do anything after that. After I ran into the crash, I tried removing/instaling the program a bunch of times.

**Comment by HubKing** [comment]
I get this error too. https://github.com/bottlesdevs/Bottles/issues/3218#issuecomment-1871086308

I usually use Pamac to install/update Flatpak apps, but I had run `flatpak update` in the terminal to update everything, and that did not fix this. I just tried `flatpak install --reinstall com.usebottles.bottles`, and I still get the same error.

**Comment by ChaosEngine60** [comment]
> I get this error too. [#3218 (comment)](https://github.com/bottlesdevs/Bottles/issues/3218#issuecomment-1871086308)
> 
> I usually use [Pamac](https://wiki.manjaro.org/index.php/Pamac) to install/update Flatpak apps, but I had run `flatpak update` in the terminal to update everything, and that did not fix this. I just tried `flatpak install --reinstall com.usebottles.bottles`, and I still get the same error.

I just downgraded to 51.9 using Warehouse and now Bottles is working. If you are already using 51.9 and getting the error, maybe you could try downgrading to 51.8? Worth a shot.

**Comment by ChaosEngine60** [comment]
"There's more than one way to skin a cat" springs to mind. Well done.
