### ISSUE TITLE
[Bug]: Bottles fails to open after updates.

### ISSUE THREAD

**Issue by ChaosEngine60** [bottlesdevs/Bottles#3218]
### Describe the bug

flatpak run com.usebottles.bottlesult:- *** stack smashing detected ***: terminated

### To Reproduce

flatpak run com.usebottles.bottles
Result:- *** stack smashing detected ***: terminated

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.2 Cinnamon

### Debugging Information

```Official Package: true
Version: '51.9'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: null
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-91-generic
Disk:
    Total: 8359309312
    Free: 8359141376
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.3GiB
Bottles_envs: null

```

### Troubleshooting Logs

```shell
~$ flatpak run com.usebottles.bottles
*** stack smashing detected ***: terminated
```

### Additional context

Was working fine about 2 days ago. As far as I can tell, the issue started to occur after some Flatpak updates came in.

**Comment by MINE5168** [comment]
I have the same, especially with a Steam shortcut. Games won't launch anymore.

**Comment by ChaosEngine60** [comment]
Error from Warehouse:

Command '['flatpak-spawn', '--host', 'flatpak', 'run', 'com.usebottles.bottles/x86_64/stable']' returned non-zero exit status 134.

**Comment by HubKing** [comment]
I get the following. Arch, Flatpak.

```
Traceback (most recent call last):
  File "/app/bin/bottles", line 44, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 30, in <module>
    from bottles.backend.managers.manager import Manager
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 39, in <module>
    from bottles.backend.managers.component import ComponentManager
  File "/app/share/bottles/bottles/backend/managers/component.py", line 25, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (8.2.1-DEV) is older than compile-time version (8.4.0-DEV)

```

**Comment by ChaosEngine60** [comment]
Issue seems to be with 51.10. If I downgrade to 51.9 Bottles works fine.

Dec 29 11:29:12 pull           com.usebottles.bottles                       stable       system       flathub
Dec 29 11:29:13 deploy update  com.usebottles.bottles                       stable       system       flathub
Dec 30 12:13:45 uninstall      org.gnome.Platform.Compat.i386               45           system
Dec 30 12:15:39 deploy update  com.usebottles.bottles
~$ flatpak run com.usebottles.bottles
*** stack smashing detected ***: terminated

**Comment by MINE5168** [comment]
> Issue seems to be with 51.10. If I downgrade to 51.9 Bottles works fine.
> 
> Dec 29 11:29:12 pull com.usebottles.bottles stable system flathub Dec 29 11:29:13 deploy update com.usebottles.bottles stable system flathub Dec 30 12:13:45 uninstall org.gnome.Platform.Compat.i386 45 system Dec 30 12:15:39 deploy update com.usebottles.bottles ~$ flatpak run com.usebottles.bottles *** stack smashing detected ***: terminated

This also solved the issues for me. Bottles run correctly both through steam and bottles.

**Comment by ChaosEngine60** [comment]
Issue reproduced in 51.10

Jan  1 17:43:11 deploy update  com.usebottles.bottles - stable       system       flathub

:~$ flatpak run com.usebottles.bottles
*** stack smashing detected ***: terminated

**Comment by mirkobrombin** [comment]
Cannot replicate.

**Comment by diggernet** [comment]
Just ran into this with both Bottles and Hugin.
It's caused by some issue between Platform 23.08 and the old Nvidia 390-157 driver, and impacts many Flatpak apps.
More details: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1676
Rolling back to Bottles 51.9 fixes it, because that version is using Platform 22.08.
Same with an older version of Hugin.
Those of us stuck with 390-157 are kind of in a bind, because Platform 22.08 is End of Life.  :(
