### ISSUE TITLE
[Bug]: Core tab in preferences not functioning

### ISSUE THREAD

**Issue by HalJordan** [bottlesdevs/Bottles#3219]
### Describe the bug

When looking at available options, and making sure I have the latest runners available, there's a Core tab. Clicking it when on any of the other 4 tabs does nothing. Is this intended? Should there be options there, or do I need to edit a file somewhere to enable it?

### To Reproduce

1. Open bottles
2. Click hamburger
3. Click Preferences
4. Click 'Core' tab.

### Package

Flatpak from Flathub

### Distribution

Arch

### Debugging Information

```shell
Official Package: false
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/amd_icd64.json:/usr/share/vulkan/icd.d/amd_icd32.json:/usr/share/vulkan/icd.d/amd_pro_icd32.json:/usr/share/vulkan/icd.d/amd_pro_icd64.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.8-arch1-1
Disk:
    Total: 1999324053504
    Free: 591086743552
RAM:
    MemTotal: 30.8GiB
    MemAvailable: 19.9GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.38'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

**Comment by HalJordan** [comment]
What?

This very github repo has a button for "Download on Flathub" .... if THAT isn't supported you need to remove it from the readme...

**Comment by hammadmajid** [comment]
Same bug here. 

Installed Bottles with `sudo dnf installe bottles` on Fedora Workstaion 41 (Wayland)

https://github.com/user-attachments/assets/8a31cef4-64e2-4ffc-b646-f36e4685a313
