### ISSUE TITLE
[Request] Close Bottles after the Windows program has been started from the file manager

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#322]
**Is your feature request related to a problem? Please describe.**
When I open a program with Bottles in my file manager and select which prefix should start the game,then the problem is that after I started the program Bottles is still open.

**Describe the solution you'd like**
That you can set that bottles gets closed after you selected which prefix should run the program.

**Comment by mirkobrombin** [comment]
I have not integrated this function because in Bottles V3 I cannot know if the program has been started and if therefore I can close Bottles

**Comment by Toadfield** [comment]
Wouldn't it be easy to implement it that you know when bottles opens a program?
I mean you could program it so that whenever you click the button that executes the program in a bottle,that then that button also closes bottoles.

**Comment by mirkobrombin** [comment]
> Wouldn't it be easy to implement it that you know when bottles opens a program?
> I mean you could program it so that whenever you click the button that executes the program in a bottle,that then that button also closes bottoles.

But that way it would become a UX fail because a user who wants to keep Bottles open can't use the file manager integration, right?

**Comment by Toadfield** [comment]
You could add a setting in the preferences menu that is titled something like "close bottles file manager when the program is started",so that only the users that want that can use it.

**Comment by mirkobrombin** [comment]
> You could add a setting in the preferences menu that is titled something like "close bottles file manager when the program is started",so that only the users that want that can use it.

This could be the ideal solution.
