### ISSUE TITLE
[Request]: Auto-adjust Wine DPI to respect the system-wide text scaling factor

### ISSUE THREAD

**Issue by piousdeer** [bottlesdevs/Bottles#3223]
### Tell us the problem or your need

Wine apps do not respect the system-wide font size multiplier and end up looking tiny (or huge).

Users can manually adjust their DPI using the legacy Wine configuration tool (winecfg), but that is not very discoverable and is inconvenient for those who adjust their scaling factor often (I usually swap my screen scaling and text scaling factors of 150% and 100% before gaming to work around a long-standing GNOME issue that makes Xwayland apps blurry when fractional scaling is used).

Screenshots of default vs adjusted DPI with text scaling factor of 1.5:
<img src="https://github.com/bottlesdevs/Bottles/assets/31318219/6e7a8ea6-a33b-4e1a-8a5c-3805e5b7dbaf">
<img src="https://github.com/bottlesdevs/Bottles/assets/31318219/cad166f9-49cf-4298-a56d-9014d31987cf">
<img src="https://github.com/bottlesdevs/Bottles/assets/31318219/c88421cb-e0f4-4bdc-a099-61bf4e24e283">
<img src="https://github.com/bottlesdevs/Bottles/assets/31318219/66afacce-2905-40aa-be18-3f3cdbd80f8f">

### Describe the solution you'd like

Before starting an app, apply [this registry tweak](https://wiki.winehq.org/Winecfg#Screen_Resolution_.28DPI_Setting.29) to set the DPI to 96 * $TEXT_SCALING_FACTOR. On GNOME, the factor can be read with `gsettings get org.gnome.desktop.interface text-scaling-factor`.

**Comment by orowith2os** [comment]
This indeed would be a request better suited for Wine. You can read the GNOME font settings via the Settings portal for something you can fairly reasonably assume to be available on any system.

**Comment by LSeelig** [comment]
From looking glass, I see that wine 9.+ Bottles will use wayland if the registry is set and display env is unset, but I use wayland fractional scaling (the reason I don't use xwayland when possible). Currently, I think Bottles sets an improper resolution/dpi based on the GNOME/mutter fractional scaling upscale instead of my screen's actual resolution.
