### ISSUE TITLE
[Bug]: Directory permissions broken after 51.10 update

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [bottlesdevs/Bottles#3224]
### Describe the bug

After updating Bottles to 51.10 it no longer sees Downloads directory from user's home directory. It is a regression since 51.9. It is huge issue for me since i use a lot of GOG installers and mostly they are not single file installer, which causes installer to not work since it can't see .bin files required to install game.

### To Reproduce

1. Launch bottles
2. click on "launch executable"
3. try to launch executable from /home/user/Downloads (it's the only directory to my knowledge which Bottles could see prior to 51.10 update)

### Package

Flatpak from Flathub

### Distribution

Fedora 39 KDE

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.8-200.fc39.x86_64
Disk:
    Total: 16785358848
    Free: 16785195008
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 27.4GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
You can give Bottles permissions to reach any path using [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).
