### ISSUE TITLE
[Bug]: No CAP_SYS_NICE with flatpak gamescope

### ISSUE THREAD

**Issue by Ali-Hasan-Khan** [bottlesdevs/Bottles#3227]
### Describe the bug

How to remove the following warning while using Gamescope in bottles:
`No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.`

### To Reproduce

1. Open Bottles
2. Switch on Gamescope option in settings
3. Run any game

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.0-39-generic
Disk:
    Total: 3035529216
    Free: 3035381760
RAM:
    MemTotal: 5.7GiB
    MemAvailable: 3.0GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Please have a look: https://github.com/bottlesdevs/Bottles/issues/1562#issuecomment-1221481661
