### ISSUE TITLE
[Bug]: Some games crashed in old bottles enviroments

### ISSUE THREAD

**Issue by Aijokey** [bottlesdevs/Bottles#3229]
### Describe the bug

Sometimes bottle brakes and after that it is impossible to run some games sometimes it is impossible to run any game. Creating new bottle fix problems. And sometimes bottles program could crash without logs if you don't delete broken bottle 

### To Reproduce

1. Launch Bottles from terminal
2. Click on old bottle
3. Run some game
4. Black screen
5. Crash

### Package

Flatpak from Flathub

### Distribution

Fedora 39

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/nvidia/wine
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.6.8-200.fc39.x86_64
Disk:
    Total: 8076066816
    Free: 8075886592
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 11.6GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(bottles:2): Gtk-WARNING **: 16:08:23.709: AdwViewSwitcher 0x56109636f060 (viewswitcher) reported min height -6, but sizes must be >= 0
16:08:24 (INFO) Performing Bottles checks… 
16:08:24 (INFO) Dxvks found:
	 - dxvk-2.3
 
16:08:24 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.11
 
16:08:24 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.4
 
16:08:24 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
16:08:24 (INFO) Runners found:
	 - soda-8.0-2
	 - vaniglia-8.6
	 - sys-wine-8.0.2
 
16:08:24 (INFO) Bottles found:
	 - test
	 - Gaming
 
16:08:24 (INFO) Catalog dependencies loaded 
16:08:24 (INFO) Catalog components loaded 
16:08:24 (INFO) Catalog installers loaded 
16:08:26 (INFO) Launching an executable… 
16:08:26 (ERROR) result should be Result or bool, but it was <class 'NoneType'> 
16:08:26 (INFO) Using EasyAntiCheat runtime 
16:08:26 (INFO) Using BattlEye runtime 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

### Additional context

I found that epic games store and steam do something with registry that could brake bottle. After installing Epic games some games crashes. After installing steam there is a chance of this error https://github.com/bottlesdevs/Bottles/issues/3209 .  Exporting registry from old to new bottle, the same mistake appears in new bottle

**Comment by Aijokey** [comment]
UPD: i find this after crash in fedora problem reporting. wine/wine64-preloader application crash
![Screenshot from 2024-01-03 16-21-48](https://github.com/bottlesdevs/Bottles/assets/48978298/4776b8d2-182b-477c-95df-782721a72bce)

**Comment by Aijokey** [comment]
I export registry files from old bottle to new and there is the same error in new bottle

**Comment by mirkobrombin** [comment]
This looks like a problem with wine itself rather than Bottles. Bottles is just a manager, sorry.
