### ISSUE TITLE
[Request] Support for more older wine versions

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#323]
**Is your feature request related to a problem? Please describe.**
Some games only work for older wine versions. You can only install some of the newer wine versions with bottles.

**Describe the solution you'd like**
That you can install the older wine and proton versions.

**Comment by mirkobrombin** [comment]
Just open a pull request on bottlesdevs/components

**Comment by Toadfield** [comment]
I would have to search for where you can download the old wine versions first.

**Comment by mirkobrombin** [comment]
> I would have to search for where you can download the old wine versions first.

You can grab older versions of lutris from their GitHub repo

**Comment by Toadfield** [comment]
Where can I do this on their repo?
Is there a folder or something that has all their wine versions and you can download them?
And when I found it,do I just have to make a pr that lists all wine versions that are downloadable?

**Comment by mirkobrombin** [comment]
> Where can I do this on their repo?
> Is there a folder or something that has all their wine versions and you can download them?
> And when I found it,do I just have to make a pr that lists all wine versions that are downloadable?

You can find them in the Release section of the repository, here an example of a component: https://github.com/bottlesdevs/components/blob/main/runners/wine/lutris-5.21.json

**Comment by Toadfield** [comment]
If it's so easy to add wine versions,why aren't they all already added in bottles?

**Comment by mirkobrombin** [comment]
> If it's so easy to add wine versions,why aren't they all already added in bottles?

I don't think there is any interest on their part in doing so. The runners you see have been added by the Bottles community.

**Comment by Toadfield** [comment]
If every wine version is available in the lutris repo,would it be possible to add every version at once in a pr?

**Comment by mirkobrombin** [comment]
> If every wine version is available in the lutris repo,would it be possible to add every version at once in a pr?

The community is free to add as many runners as they want, as long as they work.
