### ISSUE TITLE
[Bug]: Guild Wars 2 keeps redownloading 71GB Gw2.dat file

### ISSUE THREAD

**Issue by Ratko** [bottlesdevs/Bottles#3230]
### Describe the bug

After installing Guild Wars 2 through Bottles on Debian 12 64bit, I was surprised how well it plays. Next time I have attempted to play, it re-downloaded 71 GB Gw2.dat file again. Needless to say, every time I try to play it wants to re download huge game data file. I have Gw2.dat file from my Playonlinux and Steam installation, but I do not know where to put it, since I am not good with flatpack . Can someone enlighten me how I could fix this issue?

### To Reproduce

install Guild Wars 2, go to sleep, come back to play

### Package

Flatpak from Flathub

### Distribution

Debian 12

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-17-amd64
Disk:
    Total: 16755326976
    Free: 16755163136
RAM:
    MemTotal: 31.2GiB
    MemAvailable: 28.1GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.
