### ISSUE TITLE
[Bug]: EAapp error EC:201 until runner swap

### ISSUE THREAD

**Issue by mngonzu** [bottlesdevs/Bottles#3231]
### Describe the bug

When using Soda 8.02 Ea app after a clean start I get the error "we couldn't find your account info"  This error doesn't happen using other runners like wine-ge, the weird thing is it get fixed when you swap runner, launch it and then set it to use Soda again

![image](https://github.com/bottlesdevs/Bottles/assets/68573545/06743975-e6b5-41fb-8ab2-ed8acb3d374d)
![image](https://github.com/bottlesdevs/Bottles/assets/68573545/88fa0831-b928-46f1-88c5-6a0a0241b2b5)
![image](https://github.com/bottlesdevs/Bottles/assets/68573545/118d2f94-1343-4d1e-b4cc-4e5dfe474564)

### To Reproduce

Create bottle with gaming template
Install EAapp
Launch (error about account info)
Change runner to wine-ge
Launch (it works)
Change back to soda
It works (?)

### Package

Flatpak from Flathub

### Distribution

openSuse Tumbleweed

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: default
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.7-1-default
Disk:
    Total: 8345890816
    Free: 8345714688
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.1GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.
