### ISSUE TITLE
[Bug]: File paths with spaces not handled correctly

### ISSUE THREAD

**Issue by Sollace** [bottlesdevs/Bottles#3234]
### Describe the bug

Bottles doesn't seem to correctly handle file paths that contain spaces in them. Specifying "/path/to/file/file name.extension" causes it to try to interpret that has "/path/to/file/file" and "name.extension" even if I specify the value in quotes.

### To Reproduce

To get this I created a bottle and installed Inkscape 0.92.* inside it, and then configured the settings in KDE to launch .svg files using the bottled version of Inkscape.

It works correctly when I move the files to somewhere and rename them to have no spaces in their name of their path, but any time I try to use files that do have names it results in Inkscape launching and producing an error saying it can't find the file (once for each part of the path separated by the spaces).

If I navigate to the file's location and open it from within Inkscape, it works correctly.

I thought it was a problem with the run argument, but KDE will not let me add quotes around the %F in the settings dialogue, and even running it manually with quotes around the file path results in the same error message (see below):

`flatpak run --command=bottles-cli com.usebottles.bottles run -p Inkscape -b Common -- "/home/sollace/Desktop/golly look.svg"`

![image](https://github.com/bottlesdevs/Bottles/assets/6429283/0f7d9a08-024b-40fa-90ed-15b20166bf22)

### Package

Flatpak from Flathub

### Distribution

Manjaro KDE

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
            nvngx_path: null
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.1.66-1-MANJARO
Disk:
    Total: 16680046592
    Free: 16679890944
RAM:
    MemTotal: 31.1GiB
    MemAvailable: 24.0GiB
Bottles_envs: null
```

**Comment by Sollace** [comment]
Running as `flatpak run --command=bottles-cli com.usebottles.bottles run -p Inkscape -b Common -- "\"/home/sollace/Desktop/golly look.svg\""` seems to function as a workaround but I still can't find any way to fix this when double-clicking an svg file.

**Comment by ftdt10** [comment]
Add single quotes if space exists in file name, append drive letter, and wrap it with double quotes.

flatpak run --command=bottles-cli com.usebottles.bottles run -b BOTTLE_NAME -e PATH_TO_EXE --args "z:/home/USER/Documents/'test 123 abc.svg'"

and see https://github.com/bottlesdevs/Bottles/issues/2425#issuecomment-1880785975

**Comment by Sollace** [comment]
> Add single quotes if space exists in file name, append drive letter, and wrap it with double quotes.
> 
> `flatpak run --command=bottles-cli com.usebottles.bottles run -b BOTTLE_NAME -e PATH_TO_EXE --args "z:/home/USER/Documents/'test 123 abc.svg'"`
> 
> and see [#2425 (comment)](https://github.com/bottlesdevs/Bottles/issues/2425#issuecomment-1880785975)

Ah, thank you! Single quotes did the trick.

I think I figured out what I need. Using this for my file association:

`run --command=bottles-cli com.usebottles.bottles run -p Inkscape -b Common -- '"%U"'`

`Exec=flatpak run --command=bottles-cli com.usebottles.bottles run -p Inkscape -b Common -- '"%U"'`
