### ISSUE TITLE
[Request]: Add the ability to set Bottles language

### ISSUE THREAD

**Issue by stefanobartoletti** [bottlesdevs/Bottles#3238]
Please add the ability to set Bottles language from inside the app, independently from the system language

**Comment by 13xforever** [comment]
You already can though?

**Comment by 5685C4A059D5** [comment]
Seconding as it's rather jarring to see a mix of translated and untranslated strings.



> You already can though? 

This setting is for the environment within a bottle, not Bottles the app itself.

**Comment by mirkobrombin** [comment]
This is something you should do in your system preferences. Sorry we are not going to add this functionality in Bottles Legacy, we could consider for Bottles Next where we have more flexibility.
