### ISSUE TITLE
[Request] That when you open a windows program via bottles in your file manager,that you can select which prefix that program uses by default.

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#324]
**Is your feature request related to a problem? Please describe.**
Some programs need a different wine version,so I have to start some programs in a different bottle than others,the problem is that I forgot sometimes with which of my bottles it works the best.

**Describe the solution you'd like**
That when you open a windows program with bottles in your file manager that then you can select a bottle as default and when you selected that there is a "default" lable besides the bottle name and you will see that everytime you open that exact same program with bottles,so you know which bottle it should use.

**Comment by mirkobrombin** [comment]
This will be fixed in Bottles V4 with installer support.
