### ISSUE TITLE
[Request]: Request for a snap package for bottles

### ISSUE THREAD

**Issue by soumyaDghosh** [bottlesdevs/Bottles#3242]
### Tell us the problem or your need

There are many reason to not use flatpak, which is the only officially supported package for now

1. The user may not like the package.
2. The user may not be able to install/trust a third party package manager.
3. The user may not be allowed to install a third party package manager as the system is owned by some other entity(enterprise/company/school/college/university).

### Describe the solution you'd like

There is an initial work I found by @kenvandine in his [GitHub](https://github.com/kenvandine/bottles-snap). This can be used as a base and can be worked upon. The community will also help in creating and maintaining it.

### Other solutions?

A proper guide of installation with the deb package, like a script for the latest Ubuntu/Debian.

**Comment by Megalomaniak** [comment]
As per #2947 I presume that noting but Flatpaks will be supported. Which is a shame since I don't personally like either Flats or Snaps(they are both terrible at integrating with rest of the system and probably always will be).

**Comment by orowith2os** [comment]
Deal with it.
