### ISSUE TITLE
[Bug]: Unsupported Graphics Card on Epic Games Store

### ISSUE THREAD

**Issue by Petrelis-Efstratios** [bottlesdevs/Bottles#3243]
### Describe the bug

When I open Epic Game Store (fresh install), a small black screens appears for a while (I suppose its the update window) and then it pops this message:

**Unsupported Graphics Card**,

There is a problem with your graphics card. Please ensure your card meets the minimum system requirements and that you have the latest drivers installed.

I click OK and Epic Games Store closes

### To Reproduce

Create a bottle with gaming option, install epic games store through _Install Programs_ feature. Open the app

### Package

Flatpak from Flathub

### Distribution

Ubuntu 23.10

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-14-generic
Disk:
    Total: 3054043136
    Free: 3053875200
RAM:
    MemTotal: 5.7GiB
    MemAvailable: 2.8GiB
Bottles_envs: null
```

### Additional context

The laptop has an Intel Core i5 2450M without a dedicated gpu.

**Comment by KSMaan45** [comment]
try to change bottles dxvk component to dxvk-1.10.3, that's what works for me on intel i5 4460 (Haswell) with iGPU HD 4600

**Comment by Petrelis-Efstratios** [comment]
> try to change bottles dxvk component to dxvk-1.10.3, that's what works for me on intel i5 4460 (Haswell) with iGPU HD 4600

I disabled it and it worked. Thanks

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.
