### ISSUE TITLE
Steam network problem

### ISSUE THREAD

**Issue by Herman-Sid** [bottlesdevs/Bottles#3251]
Hello,
My system Fedora 39 Gnome Wayland.
I installed Bottles(version 51.10) from sowtware store, i don't use a flatpak.
I use Proton GE 8.27

When I try to start Steam, I get an error saying that steam cannot access the steam network, but the steam client update has been downloaded and installed.
I tried installing steam manually by specifying the path to the exe file, and I also tried using your steam installation option.
In all cases, steam is installed, the first launch shows how the client downloads the update, after which the second launch occurs and a message appears about an error in accessing the steam network.

Enabling the experimental sandbox function and then activating the Share Network option leads to the fact that then all applications in the bottle do not launch.

I spent a lot of time but could not find a description of a similar problem from anyone.

**Comment by orowith2os** [comment]
> I installed Bottles(version 51.10) from sowtware store, i don't use a flatpak.

Verify the package sources by looking inside of the About information. This statement on its own is grounds for closing this issue and ignoring it entirely.

**Comment by Herman-Sid** [comment]
> > I installed Bottles(version 51.10) from sowtware store, i don't use a flatpak.
> 
> Verify the package sources by looking inside of the About information. This statement on its own is grounds for closing this issue and ignoring it entirely.

Now I specifically installed the version from the flatpack, the version number is the same.
Also, when you launch steam, the client is updated and the subsequent launch displays a Steam network error message.
steam installed through your application.
![Screenshot from 2024-01-19 16-11-20](https://github.com/bottlesdevs/Bottles/assets/21198008/7ce0c8fc-dbd8-45c3-8ffd-3ad94a6ef5e7)

**Comment by Herman-Sid** [comment]
The problem turned out to be proton-GE, when I switched to Soda it all worked.

however, your project is very cool, but it will not work if you just install and configure it, there are still many details that I had to learn before getting Bottles to work.
It’s a shame that you don’t write about this anywhere.
