### ISSUE TITLE
[Request]: Unified Linux Wine Game Launcher 

### ISSUE THREAD

**Issue by LexaproDelirium** [bottlesdevs/Bottles#3255]
Hello, would you guys please take a quick look at this new project from GloriousEggroll.

https://github.com/GloriousEggroll/ULWGL

If the project achieves it's goal, I believe the end user will have a much easier time getting their games up and running.

**Comment by LexaproDelirium** [comment]
looks like you guys are already aware of it :D i am gonna close this!

**Comment by beh-10257** [comment]
@LexaproDelirium wait is this already supported ??

**Comment by LexaproDelirium** [comment]
@beh-10257 no not yet.

**Comment by beh-10257** [comment]
@LexaproDelirium I mean at least leave the issue open
since well I want to be an alpha tester and want to use ulwgl in bottles

**Comment by orowith2os** [comment]
You can test that when ulwgl is actually *in* Bottles. Until then, no point in having this open.

**Comment by Lyapsus** [comment]
Anything to actually track this one? You guys love to close everything so much
