### ISSUE TITLE
[Bug]: Issue with Steam Overlay Functionality when Adding Bottles-Flatpak Configured Games as Non-Steam Games

### ISSUE THREAD

**Issue by nazdridoy** [bottlesdevs/Bottles#3257]
### Describe the bug

Normally (bottles from AUR) if you add a non-Steam Game to Steam its overlay feature will function correctly. However if you add a game that has been configured to run with bottles-Flatpak to Steam as a non-Steam Game then the mentioned features will not work.

### To Reproduce

1. Configure a game to run with Bottles-Flatpak.
2. Add the configured game as a non-Steam Game in Steam.
3. Launch the game through Steam.
4. Observe that the Steam Overlay features are not working 

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.7.0-zen3-1-zen
Disk:
    Total: 4085186560
    Free: 4085018624
RAM:
    MemTotal: 7.6GiB
    MemAvailable: 3.6GiB
Bottles_envs: null
```

### Additional context

This issue is not related to the Flatpak version of Steam but specifically to the interaction between the native distro package version of Steam and games running within a Flatpak environment configured with Bottles-Flatpak.

**Comment by orowith2os** [comment]
This is more of a problem with how Steam functions; it wants to inject its own shared libraries into other apps to get its overlay functioning. This is not compatible with Flatpak. If Valve wants to ensure their overlay works with Flatpaks, they should make a runtime extension containing the libraries for their overlay, and use that with Flatpaks.
