### ISSUE TITLE
[Bug]: Genshin impact atl+click function isn't working 

### ISSUE THREAD

**Issue by User65-87-11** [bottlesdevs/Bottles#3259]
### Describe the bug

There is functionality to select menu icons on a screen using 'alt' mode wich allows mouse to click on UI icons . It doesn't work. Game overall reacts to mouse an keyboard.

### To Reproduce

1.login
2.press alt and move mouse to click on screen menu
3.nothing happes.

### Package

Flatpak from Flathub

### Distribution

Linux debian 6.5.0-5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1 (2023-11-29) x86_64 GNU/Linux

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: lightdm-xsession
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-5-amd64
Disk:
    Total: 16797585408
    Free: 16797421568
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 21.8GiB
Bottles_envs: null
```

### Additional context

Also there is a problem in logging in and making genshin window  inactive and going back again. The issue is keyboard input isnt working to input password. Maybe it's related to ingame UI onscreen and alt-key functionality.

**Comment by mirkobrombin** [comment]
Wrong repo, please use the "programs" repo.
