### ISSUE TITLE
[Meta] Inconsistency in app name translations

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [bottlesdevs/Bottles#3263]
In the GNOME ecosystem, it is a very common practice to translate the names of applications, especially literal ones. Most Bottles translations follow this trend, except for a number of languages with the Cyrillic writing system. This makes the application stand out in the application list and look sloppy, and it feels less native to the desktop environment than it should be

Perhaps #1035 could have started this, since the title had been translated in other translations before. The question is why the approach here is different from the standard one

**Comment by mirkobrombin** [comment]
Bottles is a product, its name should never be translated.
