### ISSUE TITLE
[Bug]: Bottles launcher open invisible window with prime-run 

### ISSUE THREAD

**Issue by manulg48** [bottlesdevs/Bottles#3264]
### Describe the bug

I'm trying to open bottles with 'prime-run' because I have a dedicated Nvidia graphics card and an integrated AMD graphics card. I want to launch bottles with the nvidia card. When I launch bottles without the command I opens the window correctly but when I apply prime run it launches the window and the terminal shows a log that bottles started, but the window is transparent and show a croped imagged of what was in that part of the screen when I launched it.

### To Reproduce

1. Run in the terminal 'prime-run flatpak run com.usebottles.bottles'

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/nvidia/wine
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.7.1-arch1-1
Disk:
    Total: 8039600128
    Free: 8039419904
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 9.3GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
You could simply use the "Use Discrete GPU" option in the bottle' settings, no?
