### ISSUE TITLE
[Request]: sandwine

### ISSUE THREAD

**Issue by drws** [bottlesdevs/Bottles#3265]
### Tell us the problem or your need

Searching for better and/or easier sandboxing solutions.

### Describe the solution you'd like

[sandwine](https://github.com/hartwork/sandwine) seems to be an interesting sandboxing solution that also uses [Bubblewrap](https://github.com/containers/bubblewrap). It coult potentially be helpful for a better and more featureful isolation of individual bottles.

**Comment by orowith2os** [comment]
Unless sandwine uses `flatpak-spawn` as well, this is non-actionable. bubblewrap doesn't work in a Flatpak environment, as Flatpak disables any features it needs to make a sandbox there.
