### ISSUE TITLE
[Request]: please add dotnetdesktop7 and dotnetdesktop8 on dependencie

### ISSUE THREAD

**Issue by amidevous** [bottlesdevs/Bottles#3266]
### Tell us the problem or your need

[Request]: please add dotnetdesktop7 and dotnetdesktop8 on dependencie

### Describe the solution you'd like

[Request]: please add dotnetdesktop7 and dotnetdesktop8 on dependencie

**Comment by mirkobrombin** [comment]
Wrong repo, please use the dependencies repo.
