### ISSUE TITLE
[Bug]: Bottles 5.10 via Flatpak missing file access permissions?

### ISSUE THREAD

**Issue by joelostblom** [bottlesdevs/Bottles#3267]
### Describe the bug

I recently updated to bottles 5.10 and it make one of my programs stop working with the error message: `cant find file path/to/.exe`. When downgrading to bottles 5.9 to fix the issue, I noticed that one of the permissions added was "file access" which seems like it could be the reason that the exe-file was not found in 5.10. I also noticed that wine was upgraded from 22.08 to 23.08 so that's a possible confounding factor.

You can see the added permission when downgrading in this screenshot:

![image](https://github.com/bottlesdevs/Bottles/assets/4560057/cc0c9329-f5a0-4119-a55f-83bb7d44200d)

### To Reproduce

Try creating a bottle with a exe-file in 5.10. I used the standalong version of iClicker 5.x from https://www.iclicker.com/downloads/iclicker-cloud/

### Package

Flatpak from Flathub

### Distribution

PopOS 22.04 (Ubuntu)

### Debugging Information

```shell
Note that this is for the working version, 5.9

Official Package: true
Version: '51.9'
DE/WM: pop
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.10-76060610-generic
Disk:
    Total: 20951638016
    Free: 20951478272
RAM:
    MemTotal: 39.0GiB
    MemAvailable: 30.4GiB
Bottles_envs: null
```

**Comment by gdonval** [comment]
Bottle defaults in installing games in its own app-specific folder. If you want to install/use them out of that, you need to alter Flatpak's permission by yourself, either by using the CLI or by installing and using Flatseal.

---

Giving Bottle (and therefore games) unrestricted access to your home folder is generally not a good idea. 

[Games](https://www.steamgifts.com/discussion/XxDfg/games-that-deletemess-up-your-hard-drive-when-you-uninstall-it) in the past have had bugs leading to the deletion of **all** your files. Some games feature very invasive "anti-cheat" software. Steam had a [nasty bug back in 2015](https://www.theregister.com/2015/01/17/scary_code_of_the_week_steam_cleans_linux_pcs/) that deleted all people's files... Plus Wine is able to run you typical Windows ransomware... And, even though it hasn't happened recently, errors in Wine could turn legit code into a data-eating mess.

---

So if you want your files somewhere else, that's not a problem: add that folder in your permission list using the `flatpak` command line tool or Flatseal:

![Example of added folders in Flatseal](https://github.com/bottlesdevs/Bottles/assets/2644113/2029fe0a-7b4b-47cf-8581-56f4e3051ead)

But by default it makes more sense to just allow the minimum.
