### ISSUE TITLE
[Question] Bat File.

### ISSUE THREAD

**Issue by ALipAkrohk** [bottlesdevs/Bottles#327]
Hello
To run bat files in wine from the command: _`wine cmd / c`_ is used, what is the equivalent in Bottle ?!

**Comment by mirkobrombin** [comment]
> Hello
> To run bat files in wine from the command: _`wine cmd / c`_ is used, what is the equivalent in Bottle ?!

You can simply press the Run.exe button (it also supports bat) or open the CMD from the details page and proceed manually.
