### ISSUE TITLE
[Request]: set drive_c attribute +F 

### ISSUE THREAD

**Issue by gegoxaren** [bottlesdevs/Bottles#3276]
### Tell us the problem or your need

Avoid wine doing case folding, instead let the Kernel do it. 

### Describe the solution you'd like

During the creation of a bottle, Bottles should try to set the case folding attribute using `chattar +F /path/to/drive_c` before populating it. 

### Additional context and references

```
$ man chattr
```

**Comment by orowith2os** [comment]
Please provide more reasoning for this.

**Comment by gegoxaren** [comment]
> Please provide more reasoning for this.

This is what Steam does, this is what is recommended to prevent stuttering, and potential of, say, having two libraries with different cases, and the user not knowing which one is used.

Case folding done at the kernel level is more performant for apps run under wine, than having wine do the case folding.

The perfarmance gain is because if case folding is not enabled, Wine has to manually check every combination of cases, meaning that there are lots of I/O operations that have to be done. By setting the  `+F` attribute this would be avoided.

I have in my own experimentation on Bottles seen that loading times for some games are reduced.

**Comment by mirkobrombin** [comment]
Doing so would require root privileges which are not granted on a flatpak. Do you know how Steam achieves so?

**Comment by koplo199** [comment]
@mirkobrombin Are you sure it requires root privilege? Investigating the matter it seems the only requirements are a compatible filesystem (like `ext4`[^1]), and the directory being empty.

It seems `chattr` is not available on the GNOME flatpak runtime, however the following python function should achieve the same as `chattr +F`:
<details open>


```Python
import fcntl
from array import array

FS_IOC_GETFLAGS = 0x80086601
FS_IOC_SETFLAGS = 0x40086602
FS_CASEFOLD_FL = 0x40000000

def chattr_f(directory: str):
    with open(directory, 'r') as f: 
        try:
            arg = array('L', [0])
            fcntl.ioctl(f.fileno(), FS_IOC_GETFLAGS, arg, True)
            arg[0] |= FS_CASEFOLD_FL
            fcntl.ioctl(f.fileno(), FS_IOC_SETFLAGS, arg, True)
        except:
            print(f"Cannot set casefold flag for directory: {directory}")

```
Code adapted from [here](https://www.geeklab.info/2021/04/chattr-and-lsattr-in-python/)
</details>

I cannot really test at the moment, but it seems very interesting as a basically free performance boost.

[^1]: At least on my system it isn't enabled by default though, but a `sudo tune2fs -O casefold /dev/MY_DISK_PARTITION` should fix it

**Comment by mirkobrombin** [comment]
> @mirkobrombin Are you sure it requires root privilege? Investigating the matter it seems the only requirements are a compatible filesystem (like `ext4`[1](#user-content-fn-1-d2b71680f828be88c10fe7ed274ad4dc)), and the directory being empty.
> 
> It seems `chattr` is not available on the GNOME flatpak runtime, however the following python function should achieve the same as `chattr +F`:
> 
> ```python
> import fcntl
> from array import array
> 
> FS_IOC_GETFLAGS = 0x80086601
> FS_IOC_SETFLAGS = 0x40086602
> FS_CASEFOLD_FL = 0x40000000
> 
> def chattr_f(directory: str):
>     with open(directory, 'r') as f: 
>         try:
>             arg = array('L', [0])
>             fcntl.ioctl(f.fileno(), FS_IOC_GETFLAGS, arg, True)
>             arg[0] |= FS_CASEFOLD_FL
>             fcntl.ioctl(f.fileno(), FS_IOC_SETFLAGS, arg, True)
>         except:
>             print(f"Cannot set casefold flag for directory: {directory}")
> ```
> 
> Code adapted from [here](https://www.geeklab.info/2021/04/chattr-and-lsattr-in-python/)
> 
> I cannot really test at the moment, but it seems very interesting as a potentially free performance boost.
> 
> ## Footnotes
> 1. At least on my system it isn't enabled by default though, but a `sudo tune2fs -O casefold /dev/MY_DISK_PARTITION` should fix it [↩](#user-content-fnref-1-d2b71680f828be88c10fe7ed274ad4dc)

I did a partial test using chattr and it was requiring root privileges. I'll experiment with your suggestion asap, thanks!

**Comment by gegoxaren** [comment]
Case-fold support _should_ be set when you create the file-system. `fs2tune` to add it, is not recommended on file-systems that was created using an old kernel/tools (Linux 5.2) (different sizes of the attribute list, IIRC, _can_ cause problems).

You should not use case-fold on `/boot/` partition (or the file system `/boot/` is on), as GRUB will not recognise the file system.

**Comment by mirkobrombin** [comment]
Misread  `chattr: Operation not supported while setting flags on case-fold`.

**Comment by gegoxaren** [comment]
Is the folder empty?

**Comment by mirkobrombin** [comment]
yes

**Comment by gegoxaren** [comment]
And you are absolutely sure the file-system has case-folding support activated?  If you have a thumb-drive please format it to EXT4 with `mkfs.ext4 -O casefold /dev/sd[whatever]`, and try en on that....

I'm on Debian 12, and this works even with unprivileged (not in wheel/sudoers group) users.

**Comment by mirkobrombin** [comment]
> And you are absolutely sure the file-system has case-folding support activated? If you have a thumb-drive please format it to EXT4 with `mkfs.ext4 -O casefold /dev/sd[whatever]`, and try en on that....
> 
> I'm on Debian 12, and this works even with unprivileged (not in wheel/sudoers group) users.

It's a btrfs on a lvm volume. Can't check rn but I think that's not the case.
