### ISSUE TITLE
[Bug]: Pen Pressure Don't Work Properly in WINE-GE Runner Component

### ISSUE THREAD

**Issue by CodeZeke123** [bottlesdevs/Bottles#3281]
### Describe the bug

The Pen Pressure doesn't work under WINE-GE. Only SYS-WINE would only work.
This is what exactly happen on my Wacom Intiuos Drawing Tablet's Pen Pressure under WINE-GE and It's not my Windows Program(I'm using Paint Tool SAI) has a problem.

![337 A](https://github.com/bottlesdevs/Bottles/assets/42813939/fafadb0f-1145-4fac-b69b-61f10a67f664)

How can i fix this issue?

### To Reproduce

1. Use Any Pen Tablet
2. Go to Hamburger Menu and Select "Preference"
3. Under Runners, Click the WINE GE and Select Any Version and Click the Download Icon then Wait to Download and Install
4. Create New Bottles using Custom Environment and Choose WINE GE in Runner Dropdown Menu
5. Go to .var/app/com.usebottles.bottles/data/bottles/bottles/<Bottle name>/drive_c/ and Paste the SAI Folder inside Home Directory
6. Click the <Bottle Name> and Select the Executable File and Find it from Step 5
7. And Run
8. After the Program Run, Please Create a new Canvas and try to test if the Pen Pressure is not working under WINE-GE Runner Wine Compatibility Layer
9. Then Run the Program again; But this time will SYS-WINE and try to test if the Pen Pressure is working under SYS-WINE Runner Wine Compatibility layer. 
10. Pen Pressure is working properly under SYS-WINE Runner and not in WINE-GE.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.3

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.4-1-liquorix-amd64
Disk:
    Total: 8064016384
    Free: 8063852544
RAM:
    MemTotal: 15.0GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
Bottles Started! 

20:12:52 (INFO) Performing Bottles checks… 
20:12:52 (INFO) Dxvks found:
	 - dxvk-2.3
 
20:12:52 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.11
 
20:12:52 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.4
 
20:12:52 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
20:12:52 (INFO) Runners found:
	 - soda-8.0-2
	 - wine-ge-proton8-27-lol
	 - wine-ge-proton8-26
	 - sys-wine-8.0.2
 
20:12:52 (INFO) Bottles found:
	 - Call of Duty 1 
	 - Paint Tool SAI 2
 
20:12:53 (INFO) Catalog installers loaded 
20:12:53 (INFO) Catalog dependencies loaded 
20:12:53 (INFO) Catalog components loaded 
20:12:57 (INFO) Launching an executable… 
20:12:57 (INFO) Using EasyAntiCheat runtime 
20:12:57 (INFO) Using BattlEye runtime 
gamemodeauto: 
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0098:err:hid:udev_bus_init UDEV monitor creation failed <<---- I think this is the culprit
0024:err:shell:SHGetFileInfoW pidl is null!
0024:err:shell:SHGetFileInfoW pidl is null!
0024:err:shell:SHGetFileInfoW pidl is null!
0024:err:shell:SHGetFileInfoW pidl is nul
```

**Comment by mirkobrombin** [comment]
Not an issue with Bottles, please report to the runner holder.

**Comment by Axis4s** [comment]
> ### Describe the bug
> The Pen Pressure doesn't work under WINE-GE. Only SYS-WINE would only work. This is what exactly happen on my Wacom Intiuos Drawing Tablet's Pen Pressure under WINE-GE and It's not my Windows Program(I'm using Paint Tool SAI) has a problem.
> 
> ![337 A](https://github.com/bottlesdevs/Bottles/assets/42813939/fafadb0f-1145-4fac-b69b-61f10a67f664)
> 
> How can i fix this issue?
> 
> ### To Reproduce
> 1. Use Any Pen Tablet
> 2. Go to Hamburger Menu and Select "Preference"
> 3. Under Runners, Click the WINE GE and Select Any Version and Click the Download Icon then Wait to Download and Install
> 4. Create New Bottles using Custom Environment and Choose WINE GE in Runner Dropdown Menu
> 5. Go to .var/app/com.usebottles.bottles/data/bottles/bottles//drive_c/ and Paste the SAI Folder inside Home Directory
> 6. Click the  and Select the Executable File and Find it from Step 5
> 7. And Run
> 8. After the Program Run, Please Create a new Canvas and try to test if the Pen Pressure is not working under WINE-GE Runner Wine Compatibility Layer
> 9. Then Run the Program again; But this time will SYS-WINE and try to test if the Pen Pressure is working under SYS-WINE Runner Wine Compatibility layer.
> 10. Pen Pressure is working properly under SYS-WINE Runner and not in WINE-GE.
> 
> ### Package
> Flatpak from Flathub
> 
> ### Distribution
> Linux Mint 21.3
> 
> ### Debugging Information
> Official Package: true
> Version: '51.10'
> DE/WM: cinnamon
> Display:
>     X.org: true
>     X.org (port): :99.0
>     Wayland: false
> Graphics:
>     vendors:
>         amd:
>             vendor: amd
>             envs:
>                 DRI_PRIME: '1'
>             icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
>     prime:
>         integrated: null
>         discrete: null
> Kernel:
>     Type: Linux
>     Version: 6.7.4-1-liquorix-amd64
> Disk:
>     Total: 8064016384
>     Free: 8063852544
> RAM:
>     MemTotal: 15.0GiB
>     MemAvailable: 10.7GiB
> Bottles_envs: null
> ### Troubleshooting Logs
> Bottles Started! 
> 
> 20:12:52 (INFO) Performing Bottles checks… 
> 20:12:52 (INFO) Dxvks found:
> 	 - dxvk-2.3
>  
> 20:12:52 (INFO) Vkd3ds found:
> 	 - vkd3d-proton-2.11
>  
> 20:12:52 (INFO) Nvapis found:
> 	 - dxvk-nvapi-v0.6.4
>  
> 20:12:52 (INFO) Latencyflexs found:
> 	 - latencyflex-v0.1.1
>  
> 20:12:52 (INFO) Runners found:
> 	 - soda-8.0-2
> 	 - wine-ge-proton8-27-lol
> 	 - wine-ge-proton8-26
> 	 - sys-wine-8.0.2
>  
> 20:12:52 (INFO) Bottles found:
> 	 - Call of Duty 1 
> 	 - Paint Tool SAI 2
>  
> 20:12:53 (INFO) Catalog installers loaded 
> 20:12:53 (INFO) Catalog dependencies loaded 
> 20:12:53 (INFO) Catalog components loaded 
> 20:12:57 (INFO) Launching an executable… 
> 20:12:57 (INFO) Using EasyAntiCheat runtime 
> 20:12:57 (INFO) Using BattlEye runtime 
> gamemodeauto: 
> wineserver: using server-side synchronization.
> wine: Using setpriority to control niceness in the [-10,10] range
> 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
> 0098:err:hid:udev_bus_init UDEV monitor creation failed <<---- I think this is the culprit
> 0024:err:shell:SHGetFileInfoW pidl is null!
> 0024:err:shell:SHGetFileInfoW pidl is null!
> 0024:err:shell:SHGetFileInfoW pidl is null!
> 0024:err:shell:SHGetFileInfoW pidl is nul
> ### Additional context
> _No response_

is this CSP?
