### ISSUE TITLE
[Bug]: Wine could not load kernel32.dll On A fresh Bottles Install

### ISSUE THREAD

**Issue by ShadowOfTheDark669** [bottlesdevs/Bottles#3282]
### Describe the bug

After installing bottles and creating a new bottle , I added my game's executable file and tried to run it .
 Surprissingly it did not run . It crashed at launch . I tried many games of the ones I have but none ran to my avail .

 I tried closing and opening the program several times but it did not work . Lastly I ran bottles from the terminal to diagnose the issue and saw that whenever I ran the exe it gave and error "wine: could not load kernel32.dll"
 
After not finding any suitable fix for this on the internet , as a last attempt I downloaded wineGE proton from bottles settings and ran the game . Voila ! It worked , then I tried switching back to soda wine which was giving me issues earlier and it weirdly still WORKED ?!
 
If this was a beginner it probably would confuse and drain the absolute bottles out of them . I am eager to know what could have caused this . If this is a bottles issue or a  system specific one.

I am currently unable to reproduce the issue.

I do have to mention that I gave it filesystem access and dbus session bus and dbus system bus access before running the exec. 
I also disabled the dbus session and system bus access while bottles was already running at a later point before running the exec . Not sure if this contributed to the issue.

### To Reproduce

1.Installed Bottles From Flatpak
2.Gave Access To System Files Using Flatseal
3.Created A Bottle
4.Added The Game's Exe
5.Ran The Exe

### Package

Flatpak from Flathub

### Distribution

Endeavour OS

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.4-arch1-1
Disk:
    Total: 4044562432
    Free: 4044394496
RAM:
    MemTotal: 7.5GiB
    MemAvailable: 1.6GiB
Bottles_envs: null
```

**Comment by ShadowOfTheDark669** [comment]
It all happened becuase I used the --no-related flag while installing.

**Comment by ShadowOfTheDark669** [comment]
It all happened as I was using the flag --no-related to install bottles from flatpak.

**Comment by p-himik** [comment]
I just tried using Bottles for the first time to install a program that's x64 but has an x86 installer (TouchDesigner). Immediately landed on this issue even though I haven't used `--no-related`.

**Comment by rnollet** [comment]
I got the same problem. Was solved by:

1. `sudo apt remove wine`, `sudo apt autoremove`, `sudo apt clean`
2. `rm -r ~/.wine`
3. removing and recreating the bottle

Not sure which one of these steps was the one that actually solves the problem. I would bet on 2+3.
