### ISSUE TITLE
how to start bottle at boot and run an exe as a service

### ISSUE THREAD

**Issue by test2a** [bottlesdevs/Bottles#3283]
i want to use bottles to run a windows program that should automatically start on boot/reboot and should run as a service so that if there is any failure, the system should restart it or if unable to do so, let the user know via alert/notification about failure.

The notification can be handled by other means but the bottles program itself should inform the user about such stuff.
second one, the program i want to run is a server which doesn't need to be used. would it be possible to install bottles on a vps, install the program using vnc and then strip the machine off x11, will the program still work?

**Comment by test2a** [comment]
```
flatpak run --command=bottles-cli com.usebottles.bottles run -b bottle_name -p program
11:38:28 (INFO) Forcing offline mode 
Windows path detected. Avoiding validation.

```
![Screenshot_20240216_113934](https://github.com/bottlesdevs/Bottles/assets/39449563/8cb7c8db-957e-4dee-9ad5-427a63e0a628)


this is from terminal but if i use GUI of bottles, i am able to run the program normally

**Comment by test2a** [comment]
```
11:42:29 (INFO) Forcing offline mode 
Windows path detected. Avoiding validation.
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''

```

same for if i use 
```
flatpak run --command=bottles-cli com.usebottles.bottles run -b bottle_name -e "C:\Program Files\program\program.exe"
```

**Comment by test2a** [comment]
```
flatpak run --command=bottles-cli com.usebottles.bottles run -b bottle_name -e 'C:\Program Files\program\program.exe'
11:56:12 (INFO) Forcing offline mode 
Windows path detected. Avoiding validation.
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
00a4:err:hid:udev_bus_init UDEV monitor creation failed
```

this did start the program so it looks like i had to use ' instead of "

**Comment by mirkobrombin** [comment]
The only way to do so is using the desktop environment way to autostart commands at boot, e.g. in GNOME and many others just placing a custom Desktop Entry in ~/.config/autostart does the trick. Similar to this but in your path rather than /etc https://help.gnome.org/admin/system-admin-guide/stable/autostart-applications.html.en
