### ISSUE TITLE
[Bug]: Sandwhiched Text in GTK Windows When Running Bottles

### ISSUE THREAD

**Issue by ThisNekoGuy** [bottlesdevs/Bottles#3284]
### Describe the bug

Describing the issue is a bit difficult for me, but launching Bottles causes me to have windows that have text that doesn't display properly and makes it hard to read in its GTK windows.

### To Reproduce

1. flatpak install bottles
2. Launch bottles
3. See "warped" windows:
![Screenshot_20240216_192230](https://github.com/bottlesdevs/Bottles/assets/28468662/dc3f33c8-44d1-4d0f-9351-60f4eaa11600)

### Package

Flatpak from Flathub

### Distribution

Gentoo Linux (LLVM)

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.1-tkg-pds-gentoo-llvm-zen2
Disk:
    Total: 16781697024
    Free: 16781533184
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 20.8GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(process:2): GLib-GIO-WARNING **: 01:28:49.210: Can't find module 'dconf' specified in GSETTINGS_BACKEND
01:28:49 (INFO) Bottles Started! 

(bottles:2): Gtk-WARNING **: 01:28:49.303: AdwViewSwitcher 0x5ee8e533cc70 (viewswitcher) reported min height -6, but sizes must be >= 0
01:28:50 (INFO) Performing Bottles checks… 
01:28:50 (INFO) Dxvks found:
         - dxvk-2.3
 
01:28:50 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11.1
 
01:28:50 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
01:28:50 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
01:28:50 (INFO) Runners found:
         - soda-8.0-2
         - sys-wine-8.0.2
 
01:28:51 (INFO) Catalog installers loaded 
01:28:51 (INFO) Catalog dependencies loaded 
01:28:51 (INFO) Catalog components loaded
```

**Comment by kovec681** [comment]
I have the same problem.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.1.71-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7700X 8-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT

```
Official Package: true
Version: '51.11'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.71-1-MANJARO
Disk:
    Total: 16361979904
    Free: 16361816064
RAM:
    MemTotal: 30.5GiB
    MemAvailable: 26.1GiB
Bottles_envs: null
```

```
16:13:26 (INFO) Bottles Started! 
16:13:27 (INFO) Performing Bottles checks… 
16:13:28 (INFO) Dxvks found:
         - dxvk-2.0-1-12901b5
         - dxvk-2.2
 
16:13:28 (INFO) Vkd3ds found:
         - vkd3d-proton-2.8
         - vkd3d-proton-2.9
 
16:13:28 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6
 
16:13:28 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
16:13:28 (INFO) Runners found:
         - soda-7.0-9
         - soda-7.0-8
         - soda-7.0-4
         - sys-wine-9.0
 
16:13:28 (INFO) Bottles found:
         - Japanese
         - Test
 
16:13:28 (INFO) Catalog installers loaded 
16:13:28 (INFO) Catalog dependencies loaded 
16:13:28 (INFO) Catalog components loaded 
```

![image](https://github.com/bottlesdevs/Bottles/assets/49417329/dd02f332-84b6-4853-9c06-eb1ec7f55a60)
![image](https://github.com/bottlesdevs/Bottles/assets/49417329/f96309ec-a9eb-4d6b-a192-cfc260a610e7)

**Comment by mirkobrombin** [comment]
There is nothing in Bottles that does that on purpose and all the texts in the widgets are properly defined. Idk what is causing so but looks like not an issue with Bottles itself.

**Comment by Baadvo** [comment]
Unfortunately I don't have a solution but I have the same problem.  :(


I'll at least add the system settings.
Distribution: Manjaro linux (stable)
Environment: KDE 5.27.10
KDE framework: 5.115.0
Qt: 5.15.12
Protokol: Wayland

**Comment by ThisNekoGuy** [comment]
The common trend so far seems to be Plasma+Wayland but I'm not certain whether this is actually the cause or not.

**Comment by ThisNekoGuy** [comment]
It appears that might actually be the case, somehow.
If I run bottles under Xwayland (although in this case I used `GDK_DPI_SCALE=2 GDK_SCALE=2` for better HiDPI usability), Bottles' menus are actually legible in a normal fashion in contrast to running it under Wayland normally.

![Screenshot_20240225_011957](https://github.com/bottlesdevs/Bottles/assets/28468662/bc048164-d06a-4119-a688-0a102c5f150d)

**Comment by Baadvo** [comment]
I found a solution for Manjaro!
https://forum.manjaro.org/t/fix-for-gtk-flatpak-apps-fonts-and-formatting-looking-terrible/130655

1) Install ,,xdg-desktop-portal-gtk"
2) Restart your PC (Really do it.)
3) Enjoy!

**Comment by ThisNekoGuy** [comment]
:man_facepalming: Well that works, and even solves a different problem I've been having, but creates a whole new issue for my web browser's text scaling in tabs and address bar. (They're tiny :upside_down_face: )

Good to know though.

**Comment by mirkobrombin** [comment]
So it was a luck of dependency. Cool.
