### ISSUE TITLE
[BUG] Debian/ubuntu packaging does not work

### ISSUE THREAD

**Issue by marchellodev** [bottlesdevs/Bottles#329]
**Describe the bug**
After installing the latest stable .deb version from Releases page, bottles fails to start:
```
bash: /usr/bin/bottles: /opt/hostedtoolcache/Python/3.8.10/x64/bin/python3: bad interpreter: No such file or directory
```

Start of the file `/usr/bin/bottles`: 
```
#!/opt/hostedtoolcache/Python/3.8.10/x64/bin/python3

# bottles.in
...
```

It seems like it expects python 3.8.10 to be installed in the /opt dir.

I believe the issue is with Github Actions, since you are providing exactly this path to the env (https://github.com/bottlesdevs/Bottles/runs/2863701538?check_suite_focus=true) Lines 5 and 6

![image](https://user-images.githubusercontent.com/61112084/123452227-e2406f00-d5e6-11eb-9263-ef0b664d5c30.png)

**Installation**
 - Method: .deb file
 - Version 3.1.15

**To Reproduce**
1. Install .deb file
2. Try to launch bottles

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04

**Comment by mirkobrombin** [comment]
Hi, thanks for your feedback! There was a rule in the workflow that replaced the interpreter with `/usr/bin/python3` but I must have deleted it a few commits ago.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/123464764-c768fd00-d5dc-11eb-94a9-f16ee819531e.png)
I can confirm that the latest unstable works on Pop! _OS 20.10.

Thanks again for your feedback 🙏

**Comment by marchellodev** [comment]
Cool, thanks!

**Comment by Lars** [comment]
Question (sorry to reopen) shouldn't this patch be applied to the stable build as well? 2021-07-28 debian package still exhibits this error (wrong interpreter path).

**Comment by mirkobrombin** [comment]
> Question (sorry to reopen) shouldn't this patch be applied to the stable build as well? 2021-07-28 debian package still exhibits this error (wrong interpreter path).

This is weird, I haven't changed the workflow. I'll take a look at it
