### ISSUE TITLE
(Improvement) Automatically confirm installation guides and hide the window

### ISSUE THREAD

**Issue by hardBSDk** [bottlesdevs/Bottles#3296]
If you open the "Dependencies" section of the bottle and install the XNA Framework 3.1 or 4.0 (for example), it will open an install window for .NET Framework 2.0

Can you automatically confirm the installation guides and hide the window?

**Comment by mirkobrombin** [comment]
This can be done by improving the manifest of the dependency. Please report in the dependencies repo.
