### ISSUE TITLE
[Request]: Roblox cursor fix

### ISSUE THREAD

**Issue by iJustGhost** [bottlesdevs/Bottles#3297]
### Tell us the problem or your need

Roblox has a cursor problem when running in xwayland, pressing right click makes the camera move around but the cursor refuses to stay in place.

### Describe the solution you'd like

The fix I found is using gamescope and adding "--force-grab-cursor" flag. But this is completely done in a command line, it would be better if an option is available in the gui under gamescope option.

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.
