### ISSUE TITLE
[Bug]: Bottles only able to see hidden directories.

### ISSUE THREAD

**Issue by Welved** [bottlesdevs/Bottles#3299]
### Describe the bug

I installed the flatpak variant of bottles, it installed fine and I have opted for the gaming environment. When I go in to install the game, clicking any available button to import the exe to install, the explorer seems to only be able to see hidden directories and none of the other normal directories.

I've even tried to go to the exe itself and right click to 'open with', literally does not wok. It shows me the cursor spin wheel making it look like it's doing something... but it does not.

### To Reproduce

1. Install bottles via flatpak https://flathub.org/apps/com.usebottles.bottles
2. Attempt at installing a windows game.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-21-generic
Disk:
    Total: 33596936192
    Free: 33596768256
RAM:
    MemTotal: 62.6GiB
    MemAvailable: 57.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
flatpak run com.usebottles.bottles
17:43:44 (INFO) Bottles Started! 
17:43:47 (INFO) Performing Bottles checks… 
17:43:47 (INFO) Dxvks found:
	 - dxvk-2.3
 
17:43:47 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.11.1
 
17:43:47 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.4
 
17:43:47 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
17:43:47 (INFO) Runners found:
	 - soda-8.0-2
	 - sys-wine-9.0
 
17:43:47 (INFO) Bottles found:
	 - Games
 
17:43:47 (INFO) Catalog installers loaded 
17:43:47 (INFO) Catalog dependencies loaded 
17:43:47 (INFO) Catalog components loaded 
17:43:52 (INFO) Setting Key sync=fsync for bottle Games… 
17:43:52 (INFO) There is no running wineserver.
```

### Additional context

The bottles application is able to see my root directory, but none of the sub-directories that are visible... only the hidden directories.

**Comment by orowith2os** [comment]
You need to use Flatseal to provide Bottles access to where you store your games. Access to the Downloads folder should already be provided ootb.

**Comment by Welved** [comment]
> You need to use Flatseal to provide Bottles access to where you store your games. Access to the Downloads folder should already be provided ootb.

Thanks. I used bottles plenty of times before, in all those times; this issue hasn't popped up. What happened?

**Comment by Welved** [comment]
> You need to use Flatseal to provide Bottles access to where you store your games. Access to the Downloads folder should already be provided ootb.

Thank you! Looks to have fixed my issue.
