### ISSUE TITLE
If it's necessary to install wine related runtimes for flatpak bottles

### ISSUE THREAD

**Issue by lumingzh** [bottlesdevs/Bottles#3300]
The wine related runtimes like wine-mono, dxvk installed when install bottles flatpak. However, bottles will download and install all these components online when setup wine prefix. 

So I have this question, if bottles don't use flatpak runtimes, why install them as dependences, thank you.

**Comment by mirkobrombin** [comment]
Those are provided by the Wine Flatpak Platform, not us. We cannot do much here.
