### ISSUE TITLE
[Request]: Implement an option to disable GTK overlay scrollbars

### ISSUE THREAD

**Issue by Tiagoquix** [bottlesdevs/Bottles#3306]
### Tell us the problem or your need

Bottles uses GTK, and it has overlay scrollbars enabled by default.
Since GTK 4, overlay scrollbars can only be disabled if it's implemented by the app developer.

I'm on KDE, and I personally don't like the overlay scrollbars feature.

https://wiki.archlinux.org/title/GTK#Disable_overlay_scrollbars
> GTK 4 will no longer support GTK_OVERLAY_SCROLLING. It has already been [dropped](https://github.com/GNOME/gtk/commit/e49615184a9d85bb0bb4e289b3ee8252adee3813#diff-3cf94c6e1eb009e20985034bc2210bfd) from master. As of GTK 4, the overlay nature of the scrollbars is part of the toolkit. The blanket toggle has been removed to prevent developers from breaking applications that have not been tested with both combinations. To allow application developers to decide what their applications should look like, the toolkit instead provides a mechanism to opt-out or add a setting for users. The function [gtk_scrolled_window_set_overlay_scrolling()](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-set-overlay-scrolling) can be used to enable/disable overlay scrolling on a per-application basis. Application developers can optionally use [GSettings](https://blog.gtk.org/2017/05/01/first-steps-with-gsettings/) to have a user setting bound to the property.

### Describe the solution you'd like

Add an option in the settings menu to disable GTK overlay scrollbars.

### Other solutions?

Restore the env. variable for Bottles only and don't add an option to the GUI.

### Additional context and references

Using KDE Plasma.

**Comment by jannuary** [comment]
That seems incredibly misleading? Global non-overlay scrollbars have never been removed, just added as an actual supported option: `gsettings set org.gnome.desktop.interface overlay-scrolling false`

**Comment by moeenio** [comment]
> The command you gave doesn't work for me, as I don't use GNOME.

For the record, this works for me on KDE with flatpak Bottles.
