### ISSUE TITLE
[Bug]: Gamepad stopped working for some games on current bottle

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#3307]
### Describe the bug

the gamepad stops working for some games in the current bottle and to make it work again only by creating a new bottle and running the game that does not recognize the gamepad there

### To Reproduce

This is the hardest, I don't know how to reproduce this, but this is the second time I've fallen into this damn bug, but here are some games that stopped working on the current bottle: DARK SOULS 2 SOTFS, DARK SOULS III and SEKIRO, all the games are from the same company, but Elden Ring continues to work

### Package

Flatpak from Flathub

### Distribution

Fedora Sericea

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: sway
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-550-54-14/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.7-200.fc39.x86_64
Disk:
    Total: 8342220800
    Free: 8342044672
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
none
```

### Additional context

I could prove this bug with video here, but I don't know which program can capture the gamepad buttons being pressed

**Comment by mirkobrombin** [comment]
Not related to bottles, please report this to the wine runner maintainer.
