### ISSUE TITLE
[Request] Bottles on i386 Ubuntu

### ISSUE THREAD

**Issue by marchellodev** [bottlesdevs/Bottles#331]
Hey, it seems like you only provide .deb for x86_64 systems. Is it possible to build it for 32-bit computers as well?

**Comment by mirkobrombin** [comment]
Hi, we do not provide 32bit packages because Bottles uses 64bit Wine runners.

**Comment by marchellodev** [comment]
Ok,got it, thanks!

**Comment by mirkobrombin** [comment]
> Ok,got it, thanks!

Perhaps the new v4 structure could allow 32bit builds.
