### ISSUE TITLE
[Bug]: I can't run/install Windows app from Bottles - Sketchup Pro 2021

### ISSUE THREAD

**Issue by gusarg81** [bottlesdevs/Bottles#3311]
### Describe the bug

Since I can't use anymore Wine (I use KDE Neon distro and since KDE 6, there are incompatibilities when using Wines repos), I am trying to use Bottles.

When I try to run the installer of Sketchup Pro 2021 (having console enabled):

> wineserver: using server-side synchronization.
> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> 0080:err:hid:udev_bus_init UDEV monitor creation failed
> wineserver: file_set_error() can't map error: Function not implemented

With Wine, this app installs and runs just fine.

### To Reproduce

- Create Bottle (no matter which exec, with all of them the same error)
- Run the installer

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04 (KDE Neon distro)

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-25-generic
Disk:
    Total: 8335339520
    Free: 8335175680
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
flatpak run com.usebottles.bottles
10:33:44 (INFO) Bottles Started! 
10:33:47 (INFO) Performing Bottles checks… 
10:33:47 (INFO) Dxvks found:
         - dxvk-2.3
 
10:33:47 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11.1
 
10:33:47 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
10:33:47 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
10:33:47 (INFO) Runners found:
         - soda-8.0-2
         - caffe-9.2
         - wine-ge-proton8-26
         - sys-wine-9.0
 
10:33:47 (INFO) Bottles found:
         - Sketchup Pro 2021
 
10:33:48 (INFO) Catalog installers loaded 
10:33:48 (INFO) Catalog dependencies loaded 
10:33:48 (INFO) Catalog components loaded 
10:33:55 (INFO) Launching an executable… 
10:33:55 (INFO) Using Wine MSI Installer -- install 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
0080:err:hid:udev_bus_init UDEV monitor creation failed
wineserver: file_set_error() can't map error: Function not implemented
```

**Comment by mirkobrombin** [comment]
wrong repo, use the programs rpeo.

**Comment by gusarg81** [comment]
> wrong repo, use the programs rpeo.

Can you be more specific? Thanks.

**Comment by Head-Scratcher** [comment]
> > wrong repo, use the programs rpeo.
> 
> Can you be more specific? Thanks.

Did you get this working? I am trying to install SketchUp 2022, and with next to no experience with WINE I thought I might try Bottles as it was supposed to be more user friendly. But it just looks like more of the same garbage as I have tried over the years. Guess this is why we are forced to run Windows in a virtual environment, with programs that don't work and no real help from the people that are supposed to know.

**Comment by gusarg81** [comment]
> > > wrong repo, use the programs rpeo.
> > 
> > 
> > Can you be more specific? Thanks.
> 
> Did you get this working? I am trying to install SketchUp 2022, and with next to no experience with WINE I thought I might try Bottles as it was supposed to be more user friendly. But it just looks like more of the same garbage as I have tried over the years. Guess this is why we are forced to run Windows in a virtual environment, with programs that don't work and no real help from the people that are supposed to know.

Nope, I didn't try anymore since there is no help, no examples, nothing.
So I've installed Sketchup in my Win partition...

**Comment by Head-Scratcher** [comment]
> > > > wrong repo, use the programs rpeo.
> > > 
> > > 
> > > Can you be more specific? Thanks.
> > 
> > 
> > Did you get this working? I am trying to install SketchUp 2022, and with next to no experience with WINE I thought I might try Bottles as it was supposed to be more user friendly. But it just looks like more of the same garbage as I have tried over the years. Guess this is why we are forced to run Windows in a virtual environment, with programs that don't work and no real help from the people that are supposed to know.
> 
> Nope, I didn't try anymore since there is no help, no examples, nothing. So I've installed Sketchup in my Win partition...

I've been running SketchUp in a Windows 7 VMWare Workstation VM but it is less than ideal. I wish SketchUp would make a Linux version, or someone actually make a program that worked. I'd settle for some decent detailed instructions on how to get it going, but all I can find are videos that get a simple one .exe file to work, not something like SketchUp that have lots of KB dependencies.

**Comment by Head-Scratcher** [comment]
> > > > wrong repo, use the programs rpeo.
> > > 
> > > 
> > > Can you be more specific? Thanks.
> > 
> > 
> > Did you get this working? I am trying to install SketchUp 2022, and with next to no experience with WINE I thought I might try Bottles as it was supposed to be more user friendly. But it just looks like more of the same garbage as I have tried over the years. Guess this is why we are forced to run Windows in a virtual environment, with programs that don't work and no real help from the people that are supposed to know.
> 
> Nope, I didn't try anymore since there is no help, no examples, nothing. So I've installed Sketchup in my Win partition...

I've been running SketchUp in a Windows 7 VMWare Workstation VM but it is less than ideal. I wish SketchUp would make a Linux version, or someone actually make a program that worked properly. I'd settle for some decent detailed instructions on how to get it going, but all I can find are videos that get a simple one .exe file to work, not something like SketchUp that have lots of KB dependencies.

**Comment by rmsraph** [comment]
> > wrong repo, use the programs rpeo.
> 
> Can you be more specific? Thanks.

@mirkobrombin means that: https://github.com/bottlesdevs/programs

**Comment by Head-Scratcher** [comment]
> > > wrong repo, use the programs rpeo.
> > 
> > 
> > Can you be more specific? Thanks.
> 
> @mirkobrombin means that: https://github.com/bottlesdevs/programs
> 
> @gusarg81 did you fixed it? I have the same issue on Linux Mint, but not in Manjaro Gnome.

I have downloaded the zip file from the link and have extracted it, how do you install it? There doesn't appear to be any obvious installation files.

Also you are saying you couldn't get it to work on Linux Mint? That was what I was trying to get SketchUp 2022 to work on with no success.

**Comment by andku85** [comment]
I posted a link from a youtube video of a guy installing 2018. it might help. was doing research before my new build is done.

https://github.com/orgs/bottlesdevs/discussions/3754#discussioncomment-15184818

**Comment by Tomasinjo** [comment]
I kept getting "Invalid handle" popups and then it failed to install - Sketchup 2020.

I resolved it with

`winetricks remove_mono`
