### ISSUE TITLE
err:xrandr:xrandr14_get_adapters Failed to get adapters

### ISSUE THREAD

**Issue by fir3-1ce** [bottlesdevs/Bottles#3325]
I have been trying to run Grim Fandango in a Bottle. The 1998 version from CD, not the Remastered version that's on Steam. This is what I'm getting on a Bottle with ge-proton9-1, set to Windows XP and with cnc-ddraw installed from the dependencies list:

```
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
00f0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00f0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00f0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00f0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e8:err:xrandr:xrandr14_get_adapters Failed to get adapters
```

I am getting this same error with the soda and sys-wine runners. The game opens for a split second then closes. I have tried emulating a virtual desktop, using gamescope, and switching around a bunch of other options, including shutting off the DXVK and VKD3D translation layers.

On my system's default Wine install, I managed to get the game to run, but it's stuck in what appears to be an 800x600 resolution box in the upper left corner of my screen, while the rest of it is black. I only got this to work after upgrading OpenGL with the amdgpu-install script.

I have no idea why I can't get this to work in a Bottle, but it seems like there should be a simple enough solution. Can I please have some guidance? Also why is the forum site down? Thank you

Ubuntu 22.04 LTS / GPU: AMD RX 5500 / iGPU: AMD ATI 0f:00.0 Cezanne / CPU: AMD Ryzen 3 5300G
Bottles from Flatpak

**Comment by mirkobrombin** [comment]
wine related

**Comment by fir3-1ce** [comment]
@mirkobrombin,

OK, but on my system wine install (wine-9.0), it still gets to fullscreen, even though the game doesn't actually scale. This behavior still differs from the runners I've tried on Bottles.
