### ISSUE TITLE
[Bug]: failed to install microsoft arial font

### ISSUE THREAD

**Issue by Thdecoolste** [bottlesdevs/Bottles#3331]
### Describe the bug

When creating a new bottle i get the error message saying failed to install Microsoft Arial Font.

### To Reproduce

1. create new bottles, 2. select application. The name i used was Fusion 360 but with different names i got the same error, 3. create, and then i get this log: Generating bottle configuration…
The Wine config is being updated…
Wine config updated!
Running as Flatpak, sandboxing userdir…
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: application…
Installing DXVK…
Installing VKD3D…
Installing dependency: Microsoft Arial Font …
Failed to install dependency: Microsoft Arial Font

### Package

Flatpak from Flathub

### Distribution

Debian 12, KDE plasma version 5.27.10, KDE framework version 5.107.0, Qt version 5.15.10, kernel version 6.7.9-amd64(64-bit)

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.9-amd64
Disk:
    Total: 4014960640
    Free: 4014788608
RAM:
    MemTotal: 7.5GiB
    MemAvailable: 2.8GiB
Bottles_envs: null
```

**Comment by Thdecoolste** [comment]
Found the issue, turned out i couldn't be downloaded on school wifi. I retried at home and had no issue.

**Comment by nicoKoehler** [comment]
I have encountered the same issue on PopOS 22.04 LTS. 
I was not on any restricted wifi, and the VPN (tried it switched off) was not to blame either. 

A workaround for me was to use the bottle-cli, which successfully created the bottle when the GUI wouldnt. After that, I could use the GUI just fine for launching, but issue creating new bottles remains

**Comment by XenosXN** [comment]
> I have encountered the same issue on PopOS 22.04 LTS. I was not on any restricted wifi, and the VPN (tried it switched off) was not to blame either.
> 
> A workaround for me was to use the bottle-cli, which successfully created the bottle when the GUI wouldnt. After that, I could use the GUI just fine for launching, but issue creating new bottles remains

im also having that issue on popos, how did you get the bottle-cli thing to work? im trying to make a new bottle in the terminal but im new to linux so im having a hard time with it

**Comment by nicoKoehler** [comment]
`flatpak run --command=bottles-cli com.usebottles.bottles new --bottlename SOMETHING --environment ENV`

Where ENV is part of the presets, like application, gaming, etc.

**Comment by Jonibhoni** [comment]
I'm having the same issue...

```
Official Package: true
Version: '51.11'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-28-generic
Disk:
    Total: 8239521792
    Free: 8239353856
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 12.3GiB
Bottles_envs: null
```
Here's the log:
```
2:59:21 (INFO) Setting Key Installed_Dependencies=['d3dx9', 'msls31'] for bottle MeineGamesBottle… 
22:59:21 (INFO) Dependency installed: msls31 in MeineGamesBottle 
22:59:21 (INFO) Installing dependency [arial32] in bottle [MeineGamesBottle]. 
22:59:21 (ERROR) Failed to download [https://cfhcable.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe] 
22:59:21 (ERROR) Failed to install dependency: Microsoft Arial Font 
```

**Comment by furkansimsekli** [comment]
> flatpak run --command=bottles-cli com.usebottles.bottles new --bottlename SOMETHING --environment ENV

It should be `--bottle-name` instead of `--bottlename`.

**Comment by Jonibhoni** [comment]
But from what I see (in ...<virtual c_drive>/windows/Fonts), creating the bottle via command-line doesn't solve the issue with the font not downloaded. It simply creates the bottle without Arial...

**Comment by anghelos** [comment]
I have the same issue on Fedora Kinoite (Aurora).

I believe the issue should be reopened.

**Comment by Jonibhoni** [comment]
If I try that URL manually in Firefox, it also says "connection failed" (translated). On my Laptop and my phone. From both home WiFi and mobile connection.

https://cfhcable.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe

**Comment by anghelos** [comment]
There is apparently a fix already, still waiting to be merged: https://github.com/bottlesdevs/Bottles/issues/3144#issuecomment-1793627302

**Comment by anghelos** [comment]
The sourceforge link for Arial is broken, it needs to be changed to a different mirror. This pull request fixes it: https://github.com/bottlesdevs/dependencies/pull/233

**Comment by hirntot** [comment]
seems like the next font was moved?
`Failed to install dependency: Microsoft Courier New Font`

**Comment by ansarizafar** [comment]
I have the same issue on Ubuntu. Is there any solution?

**Comment by FurqanHun** [comment]
I just installed Bottles and ran into the same problem where the ms arial font dependency kept failing during setup. Restarting Bottles didn’t fix it, so i just manually installed the core fonts directly into wine and that worked:
```bash
flatpak run --command=winetricks com.usebottles.bottles corefonts
```

**Comment by Otamated** [comment]
I still have the Arial font issue  and the suggested solution didn't work flatpak run --command=winetricks com.usebottles.bottles corefonts

**Comment by FurqanHun** [comment]
> I still have the Arial font issue and the suggested solution didn't work flatpak run --command=winetricks com.usebottles.bottles corefonts

It could be failing for multiple reasons. Like maybe the SourceForge mirror is flaky (I’ve had issues grabbing some packages from SourceForge manually too), or maybe some checksum validation is failing. I’m not sure which one it is, but those seem like the most likely causes.

**The actual manual method is to grab the fonts installer `.exe`, extract the `.ttf` files manually, and drop them in the bottle's or wine's prefix.**

Installing corefonts directly through winetricks isn’t technically "manual"...it just bypasses the Bottles gui. When you create a new Bottle, it uses a YAML recipe that checks for and installs dependencies like fonts if they aren’t already cached or present. If they're already present in wineprefix, it just reuses what’s already there instead of downloading again.

I think that’s why bypassing the gui fixed it for me in the past (and for others, judging by the thumbs up). Same thing if you install all the fonts through the dependency manager (i don't really remember what it was called) from the Bottles gui before you even make a bottle... it puts them in a shared dependency cache, so new bottles just copy them over instead of fetching them fresh.

**Comment by nicoKoehler** [comment]
FWIW, I was facing the same issue and it was resolved after switching off the VPN. Guess the microsoft mirrors or wherever Bottles gets the fonts did not like it. (the assumption was based on other users reporting it not working on public wifi). Worked like a charm now.
