### ISSUE TITLE
[Bug]: "Failed to create a placeholder directory file"

### ISSUE THREAD

**Issue by Welved** [bottlesdevs/Bottles#3338]
### Describe the bug

I am on Fedora trying to use bottles, but I get this "Failed to create a placeholder directory file" error. I am using the flatpak variant. It works just fine on Ubuntu 22.04, but on Fedora it doesn't seem to work.

I does create the directory as I named it, but... it just errors out without writing any files into the directory.

### To Reproduce

1. Open Bottles
2. "Create New Bottle..."

### Package

Flatpak from Flathub

### Distribution

Fedora 39 (Workstation Edition)

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.4-200.fc39.x86_64
Disk:
    Total: 33280987136
    Free: 33280823296
RAM:
    MemTotal: 62.0GiB
    MemAvailable: 57.2GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
18:19:13 (INFO) Bottles Started! 
18:19:15 (INFO) Performing Bottles checks… 
18:19:15 (INFO) Dxvks found:
	 - dxvk-2.3
 
18:19:15 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.12
 
18:19:15 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.7.0
 
18:19:15 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
18:19:15 (INFO) Runners found:
	 - soda-8.0-2
	 - sys-wine-9.0
 
18:19:15 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
18:19:15 (INFO) Catalog installers loaded 
18:19:15 (INFO) Catalog dependencies loaded 
18:19:15 (INFO) Catalog components loaded 
18:19:58 (ERROR) Failed to create placeholder directory/file at: /run/user/1000/doc/a041bc45/Windows/Nexon
```

**Comment by mirkobrombin** [comment]
`/run/user/1000/doc/a041bc45/Windows/Nexon` you are using a custom path for your bottles, without properly give permissions to the flatpak. Install [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and give Bottles permissions to reach the new path, then open Bottles, reset the custom bottles path and choose it again.

**Comment by arun-mani-j** [comment]
In my case, the error came as:
```
22:04:41 (ERROR) Failed to create placeholder directory/file at: /home/arun-mani-j/.var/app/com.usebottles.bottles/data/bottles/bottles/game-name
```

Turned out that, that I had created a bottle with custom path already but deleted it from the file manager. This did not delete the bottles data. So the old bottles data did not allow new one to be created. Deleting it fixed the issue.

**Comment by Alshat** [comment]
@arun-mani-j How did you delete the old data?

**Comment by arun-mani-j** [comment]
> [@arun-mani-j](https://github.com/arun-mani-j) How did you delete the old data?

@Alshat 
I simply deleted the folder of the old game from `.var/app/com.usebottles.bottles/data/bottles/bottles/`.

```sh
$ ls .var/app/com.usebottles.bottles/data/bottles/bottles/
Bully/                  Red-Dead-Redemption-2/  Valheim/
Dark-Souls-Remastered/  Stalker/                WWE-2K19/
GTA-IV/                 Stalker-SOC/            WWE-2K23/

$ ls .var/app/com.usebottles.bottles/data/bottles/bottles/Red-Dead-Redemption-2/
cache/  placeholder.yml

$ cat .var/app/com.usebottles.bottles/data/bottles/bottles/Red-Dead-Redemption-2/placeholder.yml 
Path: /mnt/common/Games/Red-Dead-Redemption-2
```

For example, I don't have RDR 2 in my games disk (`/mnt/common/Games`), but there is still Bottles data for it. It's because I deleted the game from file manager directly. Now if I try to add it back will the same name, Bottles will fail as there is already a directory called `Red-Dead-Redemption-2`. So you need to delete this directory to avoid any name conflicts.

**Comment by TieSKey** [comment]
I had the same problem, deleting the "wine profile / main bottles folder" will make it disappear from the UI but folder at ~/.var/app/com.usebottles.bottles/data/bottles/bottles/ is still present and prevents creation of a new bottle with an existing name.  
I guess bottles should keep the bottle in the UI (in a fail state) so users realize a bottle must be deleted from there.
