### ISSUE TITLE
[Bug]: Can't view any file after creating a bottle

### ISSUE THREAD

**Issue by talha4n6** [bottlesdevs/Bottles#3343]
### Describe the bug

The file manager pops up to choose an exe, it shows 0 file
![image](https://github.com/bottlesdevs/Bottles/assets/84320942/d4a3199a-c1c1-4f05-a4ae-6883636605d3)

### To Reproduce

No error message

### Package

Flatpak from Flathub

### Distribution

Ubuntu 23.04 LTS

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: ubuntu-xorg
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-27-generic
Disk:
    Total: 8284135424
    Free: 8283967488
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 12.1GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
![image](https://github.com/bottlesdevs/Bottles/assets/9479903/bb95098b-6e86-4d93-82dd-69aebe2bf05b)

I can't reproduce the issue, ensure Flatpak is correctly configured in your system. Worth asking for support [here](https://github.com/flatpak/flatpak).
