### ISSUE TITLE
[Bug]: Thick black borders around the Library tab

### ISSUE THREAD

**Issue by Rekt3y** [bottlesdevs/Bottles#3346]
### Describe the bug

Opening the Library tab in the main window causes black borders to appear. Going back to the Bottles tab causes the borders to disappear. 

In reality, these borders are transparent, so they appear black in the Desktop, but the color changes depending on what I open the screenshot with. For that reason, I'll also upload a jpeg version to show what the end user sees.

Normal:
![Screenshot_20240416_174714](https://github.com/bottlesdevs/Bottles/assets/86079814/f3cc609a-a478-466f-9844-bc98f8641706)

What the user sees:
![Screenshot_20240416_174538](https://github.com/bottlesdevs/Bottles/assets/86079814/9fdf2413-8174-4fb2-9a66-4dbf07a70e74)

With transparency supported:
![Screenshot_20240416_174538](https://github.com/bottlesdevs/Bottles/assets/86079814/9dfd0f92-ff4b-4c80-b115-1fe801139058)

### To Reproduce

1. Open Bottles
2. On the Bottles tab, everything looks fine
3. Go to the Library tab
4. The Library tab has thick black borders around

### Package

Flatpak from Flathub

### Distribution

Fedora 39 KDE Spin

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.5-201.fc39.x86_64
Disk:
    Total: 16781692928
    Free: 16781529088
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.8GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
$ flatpak run com.usebottles.bottles

(process:2): Gtk-WARNING **: 17:41:30.430: Locale not supported by C library.
        Using the fallback 'C' locale.
17:41:30 (INFO) Bottles Started! 
17:41:31 (INFO) Performing Bottles checks… 
17:41:31 (INFO) Dxvks found:
         - dxvk-2.3
 
17:41:31 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11.1
 
17:41:31 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
17:41:31 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
17:41:31 (INFO) Runners found:
         - soda-8.0-2
         - wine-ge-proton8-26
         - sys-wine-9.0
 
17:41:31 (INFO) Bottles found:
         - Lies of P
         - Art
         - Fallout 4
 
17:41:31 (INFO) Catalog installers loaded 
17:41:31 (INFO) Catalog dependencies loaded 
17:41:31 (INFO) Catalog components loaded 
^C
```

**Comment by mirkobrombin** [comment]
This is somewhat related to your setup, cannot replicate sorry.

**Comment by Rekt3y** [comment]
Uninstalling `org.gtk.Gtk3theme.Breeze-Dark` fixed the issue. 
The replacement for it is `org.gtk.Gtk3theme.Breeze`
