### ISSUE TITLE
[Bug]: Can't create desktop entry

### ISSUE THREAD

**Issue by quintenvandamme** [bottlesdevs/Bottles#3349]
### Describe the bug

When clicking on add create desktop entry on an application i get redirected to https://docs.usebottles.com/bottles/programs#flatpak. After running the command on the page it still doesn't work.
```sh
flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications
```
I have also tried using flatseal but everything is fine.

![image](https://github.com/bottlesdevs/Bottles/assets/58103738/244631bb-071c-461a-8973-dbe3bd9bec7f)

![image](https://github.com/bottlesdevs/Bottles/assets/58103738/34cec9af-b5f2-458c-b06c-3b1dbd25d635)

![image](https://github.com/bottlesdevs/Bottles/assets/58103738/d890e6b4-b001-4ef6-94da-82e497ff0775)

### To Reproduce

1.  Go to a program.
2. Click on the 3 dots of the program.
3. Select  Add Desktop Entry.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.7-arch1-1
Disk:
    Total: 12237590528
    Free: 12237426688
RAM:
    MemTotal: 22.8GiB
    MemAvailable: 19.5GiB
Bottles_envs: null
```

**Comment by quintenvandamme** [comment]
As a note i also did they exact same on my desktop that is also running Arch Linux and i had no problems.

**Comment by mirkobrombin** [comment]
![image](https://github.com/bottlesdevs/Bottles/assets/9479903/460aa7ef-de3e-4f94-b424-17016a5147b2)

It works for me. There is definitely something wrong in your setup.

**Comment by quintenvandamme** [comment]
I found that running bottels from the terminal actually created a desktop entry.
![image](https://github.com/bottlesdevs/Bottles/assets/58103738/5f69c905-2087-48d9-9f30-2e12c771f5d5)
![image](https://github.com/bottlesdevs/Bottles/assets/58103738/35c9a156-e664-492d-b982-5993cf644484)
