### ISSUE TITLE
[Request]: Bring support of MSIX / Appinstaller and UWP.

### ISSUE THREAD

**Issue by shawny43** [bottlesdevs/Bottles#3350]
### Tell us the problem or your need

There no way to install apps trough MSIX / Appinstaller or UWP installations. Should we needs to bring support of it?

### Describe the solution you'd like

Bring all MSIX/appinstaller and UWP source codes to Bottles or reverse enginnering it has it's could. 

### Other solutions?

Bring out an converter or an emulation of Windows 11/10 directly into bottles to get support of MSIX and UWP

### Additional context and references

MSIX: https://learn.microsoft.com/en-us/windows/msix/overview
UWP: https://learn.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide
Appinstaller: https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer

**Comment by orowith2os** [comment]
This seems like an issue more suited to Wine, not Bottles, especially
regarding UWP.

**Comment by shawny43** [comment]
Bottles could add Proton from Valve for better support right?

**Comment by shawny43** [comment]
Soo what's i could do to install apps from MSIX, Appinstaller, etc?

**Comment by BvngeeCord** [comment]
Gonna quickly chime in, I'm also curious what steps I can (if any exist currently) take to install apps packaged via `.appinstaller`/`.msix`/`.appx` files.

**Comment by mirkobrombin** [comment]
That's not related to Bottles.

**Comment by beedell-roke** [comment]
@Bvngee and others, y'all may find [`bbs.archlinux.org/viewtopic.php?pid=2109872#p2109872`](https://bbs.archlinux.org/viewtopic.php?pid=2109872#p2109872) useful. [^1]

[^1]: [`reddit.com/r/winehq/comments/10t3wig/comment/n152ezr`][1]

      [1]: https://www.reddit.com/r/winehq/comments/10t3wig/comment/n152ezr/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
