### ISSUE TITLE
[Request] Being able to set that a bottle for every wine version gets created automatically

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#338]
**Is your feature request related to a problem? Please describe.**
I want to use every Wine version that bottles supports,but I am too lazy to create a bottle for each wine version myself.

**Describe the solution you'd like**
That you can set that a bottle for each wine version gets created automatically.

**Comment by mirkobrombin** [comment]
That's not what the product does. You should only create a bottle when you need it and if you need a bottle per runner, well you should create them manually as some users may not like it as a workflow. Ok I can make it a separate feature but I don't think I can invest the time to create a feature that would be used by a few, especially if it requires a lot of time and several changes to the current Bottles structure.

For now I close the issue, I reopen it if the request for the functionality from other users grows.
