### ISSUE TITLE
[Request]: Offline Installer

### ISSUE THREAD

**Issue by sandboxgamedev123** [bottlesdevs/Bottles#3380]
# Description
The goal is to have an offline installer for Bottles.

### Describe the solution you'd like

Debian (.deb) packages or the AppImage format might be a solution. Is there a way to create offline Flatpak files for every component needed to use Bottles?

Can I become a contributor to help provide assistance toward this goal?

### Other solutions?

Another possible solution might be to have scripts for making an offline installer based on the Flatpak version of Bottles.

**Comment by xioren** [comment]
The .deb version of Bottles is no longer maintained and there are no plans on maintaining an AppImage at the moment.

**Comment by sandboxgamedev123** [comment]
Is it okay if I contribute to a possible offline installer, either with Debian (.deb) packages or the AppImage format? I have experience compiling programs for the AppImage format. I might try to keep many of the components outside of the AppImage, similar to how RetroArch uses the AppImage format.

**Comment by xioren** [comment]
I appreciate your willingness to contribute but I am pretty sure offering anything other than the Flatpak is not in the scope of the project right now. However I cannot speak for the project owner so take that with a grain of salt. If you are dead set on using an AppImage, I have seen Bottles packaged by a third party in an AppImage format. While it is not officially supported it might suit your needs (if you can find that project).

**Comment by sandboxgamedev123** [comment]
I understand. This issue was not created specifically to have have other contributors "make it happen". It is meant more as a point of discussion on the feature and how I can "make it happen". Because Bottles has components that are relatively large in file size (such as Wine), it might not be practical to have the "one file" program version of an AppImage.

For now, I think the easiest solution might be to utilize the Flatpak version for an offline installer.

**Comment by ivan-hc** [comment]
Hi @sandboxgamedev123 , Bottles uses `pcurl` to download some packages if missing, at first start.

Here is the list https://usebottles.com/database/components/

PS: I'm the one that maintains the unofficial AppImage https://github.com/ivan-hc/Bottles-appimage for any question, contact me there

**Comment by sandboxgamedev123** [comment]
Hi ivan-hc, thank you for the information.
