### ISSUE TITLE
org.gnome.Platform version 46

### ISSUE THREAD

**Issue by fxzxmicah** [bottlesdevs/Bottles#3386]
Is there a plan to upgrade to version 46 for flatpak?

**Comment by fxzxmicah** [comment]
These dependencies are installed as flatpak dependencies, but it seems that the program is not using them and will download them again every time a bottle is created.
```
org.winehq.Wine.DLLs.dxvk
org.winehq.Wine.gecko
org.winehq.Wine.mono
```

**Comment by Rrauros** [comment]
Its already merged actually. @mirkobrombin can we get a new release so we can close this?

**Comment by fxzxmicah** [comment]
fixed
