### ISSUE TITLE
Wine mono dependency install taking long

### ISSUE THREAD

**Issue by vikingnope** [bottlesdevs/Bottles#3421]
Hi, 

I just wanted to make sure, is it normal that the Wine Mono dependency install takes long? 

Have been on the screen for around 30 minutes now, and I am not sure if its stuck.

Seems to be getting stuck here:

```
 
18:30:36 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32'] for bottle Windows Apps… 
18:30:36 (INFO) Dependency installed: courie32 in Windows Apps 
18:30:36 (INFO) Installing dependency [mono] in bottle [Windows Apps]. 
18:30:36 (INFO) Using Wine Uninstaller -- get_uuid 
18:30:36 (WARNING) Bottles runtime was requested but not found 
wineserver: using server-side synchronization.
wine-mono-9.1.0-x86.msi (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (80.7MiB/80.7MiB - 48.2MiB)

18:30:39 (INFO) Renaming [wine-mono-9.1.0-x86.msi] to [wine-mono-9.1.0-x86.msi]. 
18:30:39 (INFO) Launching an executable… 
18:30:39 (INFO) Using Wine MSI Installer -- install 
18:30:39 (WARNING) Bottles runtime was requested but not found 
wineserver: using server-side synchronization.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
```

**Comment by vikingnope** [comment]
After installing wine and wine-mono through my package manager it works now

**Comment by karmakarmeghdip** [comment]
> After installing wine and wine-mono through my package manager it works now

not working here, stuck at installing wine mono
![image](https://github.com/user-attachments/assets/951f8e8b-a881-4523-9f86-8856b5d9dcc1)

**Comment by M0n7y5** [comment]
Reopen the issue as its not working

**Comment by fhvirus** [comment]
I just came across this issue, and installing `lib32-freetype2` from my system's package manager as per the warning message seems to works.

**Comment by orowith2os** [comment]
This sounds like a distro packaging problem. If it repos with our Flatpak, file a new issue. I'm locking this.

If it only happens with your distro packages, bother them, not us.
