### ISSUE TITLE
Installing Bottles also installed like 4.5GB of some other stuff that i dont know how to remove

### ISSUE THREAD

**Issue by Deniiguess** [bottlesdevs/Bottles#3425]
When i installed the program, i noticed my storage was rapidly decreasing and also noticed that it kept installing more and more stuff during the installation process. After i uninstalled Bottles (because the few programs i kinda need dont really work with Wine still dont quite work with Bottles), it only removed like 1GB and not those 4.5 other GB. Any ideas on what to do to remove the rest?

(I used the flatpack install if youre wondering.)

**Comment by Perkolator** [comment]
Try `flatpak uninstall --unused` if it helps.

**Comment by Deniiguess** [comment]
I just checked my storage again and... it came back up to the space i should have. Dont know what happened. Will keep that command in mind for the future tho.

**Comment by Perkolator** [comment]
If your issue is resolved, please close the issue. Thank you.

**Comment by Deniiguess** [comment]
Actually nevermind it was just my windows partition and not my linux one. Also it says "Nothing unused to uninstall"

**Comment by Perkolator** [comment]
Then check what Flatpaks are installed with `flatpak list`. Do you recognize everything you have installed and are there something that should not be there?

Tip: when you install some Flatpak, check what all it actually installs, make a note of it (or just leave the terminal open if you're just quickly testing some software), and if you uninstall it, compare what got installed and what gets uninstalled.

**Comment by Deniiguess** [comment]
Just had 3 flatpaks installed (just uninstalled 1, didnt really change anything), 1 of them is one i recognize and 1 is important for the one that i recognize.

**Comment by Perkolator** [comment]
Then it might be some Flatpak cache.. probably gets cleaned out later. Time to purchase new disk if few GB is a problem for you? I don't see this as a Bottles problem if everything regarding Bottles was uninstalled. Flatpak is an ecosystem of its own, it uses some space on your disk.

**Comment by Deniiguess** [comment]
I see. Well i guess ill just wait for now. Thanks for trying to help.
