### ISSUE TITLE
[Bug]: Can't install it on KDE Neon plasma 6

### ISSUE THREAD

**Issue by myaccou** [bottlesdevs/Bottles#3446]
### Describe the bug

It said "Aborted due to failure (While pulling runtime/org.freedesktop.Platform.GL32.default/x86_64/23.08 from remote flathub: opcode open-splice-and-close: opcode close: min-free-space-size 500MB would be exceeded, at least 31.8 kB requested)"

### To Reproduce

e

### Package

Flatpak from Flathub

### Distribution

KDE Neon Plasma 6.0

### Debugging Information

```shell
e
```

### Troubleshooting Logs

```shell
e
```

### Additional context

e

**Comment by ovo-Tim** [comment]
It looks like you don't have enough free disk space

**Comment by GabsEdits** [comment]
You don't have enough free disk space as mentioned above
