### ISSUE TITLE
[Bug]: Bottles can't find .dll files even though they're there

### ISSUE THREAD

**Issue by Mewmew251** [bottlesdevs/Bottles#3457]
### Describe the bug

So, to start us off I am running off of Ubuntu Noble Numbat. I'm trying to get bottles to run ClipStudioPaint by following this tutorial: https://youtu.be/YDfKwF19wOA?si=eNEtATqj5JqJHRzT  and I have come to a problem. The ClipStudiopaint.exe file won't open, and opening up the terminal for it's launch gives me this
wineserver: using server-side synchronization.
0040:err:module:hacks_init HACK: reporting LocalSystem account SID.
0060:err:module:hacks_init HACK: reporting LocalSystem account SID.
0024:err:module:import_dll Library boost_thread.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library QmPdkDll.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library ailia.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library giflib.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library jpeg62.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library libpng16.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library tiff.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library libfbxsdk.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library zlib.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library icuuc65.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library boost_date_time.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:import_dll Library boost_regex.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0024:err:module:loader_init Importing dlls for L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe" failed, status c0000135

I've tried installing microsoft .netframework 4.7.2 with no change in this. However, after changing my runner from soda to sys wine-9.0 I got the hack reporting lines to no longer show up. So at this point it's got something to do with wine not being able to read these dll files even though their names are exactly the same to a t
I've looked up other posts about issues with dll files not being found and they either gave up on fixing it or were still awaiting for someone to respond back to help out. I don't know much on coding, so when it comes to solving things about linux, I just look it up. Any suggestions would be appreciated. I'm clueless and could use some guidance

### To Reproduce

1.download clipstudiopaint 2.0 from clipstudio's website
2.follow this tutorial up until you open the clipstudiopaint.exe file
(for directory information through the bottles folder do c drive, program files, CELSYS, clipstudio 1.5 (dunno why it says 1.5)
clip studio paint, and then you should be able to find the clipstudiopaint.exe file)
3.try to start clipstudiopaint.exe (and fail)
4. change runner from soda to sys wine-9.0
5. (optional) install microsoft .net framework 4.7.2 manually instead of directly from bottles

### Package

Flatpak from Flathub

### Distribution

Ubuntu Noble Numbat

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-183-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.0-39-generic
Disk:
    Total: 8360706048
    Free: 8360525824
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
0274:err:module:import_dll Library boost_thread.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library QmPdkDll.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library ailia.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library giflib.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library jpeg62.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library libpng16.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library tiff.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library libfbxsdk.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library zlib.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library icuuc65.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library boost_date_time.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:import_dll Library boost_regex.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe") not found
0274:err:module:loader_init Importing dlls for L"Z:\\run\\user\\1000\\doc\\7709b187\\CLIPStudioPaint.exe" failed, status c0000135
```

**Comment by EnochxynL** [comment]
Do I need to reinstall "com.usebottles.bottles" app in flatpak? I think you mean I need to place the bottles in /root ("C:" drive is just emulated by bottle.)

Or you mean I need to reinstall the PROGRAM (CLIPStudioPaint) instead of the whole bottle application into the "C:" drive in a bottle environment (wine prefix)?
