### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NoirVulture** [bottlesdevs/Bottles#3484]
### Describe the bug

[('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/syswow64/iccvid.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/syswow64/iccvid.dll', '[Errno 9] Descritor de arquivo inválido'), ('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '[Errno 9] Descritor de arquivo inválido')]  File "/app/share/bottles/bottles/backend/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1496, in create_bottle
    TemplateManager.new(environment, config)

  File "/app/share/bottles/bottles/backend/managers/template.py", line 63, in new
    shutil.copytree(

  File "/usr/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)

### To Reproduce

I was trying to install a windows program called HyperX NGENUITY, after it the program colapsed...

### Package

Flatpak from Flathub

### Distribution

Fedora 40 KDE Plasma

### Debugging Information

```shell
[('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/syswow64/iccvid.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/syswow64/iccvid.dll', '[Errno 9] Descritor de arquivo inválido'), ('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '[Errno 9] Descritor de arquivo inválido')]  File "/app/share/bottles/bottles/backend/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1496, in create_bottle
    TemplateManager.new(environment, config)

  File "/app/share/bottles/bottles/backend/managers/template.py", line 63, in new
    shutil.copytree(

  File "/usr/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)
```

### Troubleshooting Logs

```shell
[('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/syswow64/iccvid.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/syswow64/iccvid.dll', '[Errno 9] Descritor de arquivo inválido'), ('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Hyper-X-NGENUITY/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/b6033fce-0a35-4288-860a-d11a0a803f71/drive_c/windows/mono/mono-2.0/lib/mono/4.6.1-api/Mono.Cairo.dll', '[Errno 9] Descritor de arquivo inválido')]  File "/app/share/bottles/bottles/backend/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1496, in create_bottle
    TemplateManager.new(environment, config)

  File "/app/share/bottles/bottles/backend/managers/template.py", line 63, in new
    shutil.copytree(

  File "/usr/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)
```

### Additional context

This is the first time a had any problem with windows apps in bottles, what a shame...

**Comment by GabsEdits** [comment]
Missing details
