### ISSUE TITLE
[Request]: Allow to use vkd3d that is built in with Proton GE

### ISSUE THREAD

**Issue by dominikzogg** [bottlesdevs/Bottles#3506]
### Tell us the problem or your need

I installed Star Wars Outlaws with Uplay.

It did not work, so i searched for solutions and found that current master of vkd3d-proton got it fixed.
So i built vkd3d-proton master myself and put it to the correct place for bottles to use it.
In a discussion https://github.com/HansKristian-Work/vkd3d-proton/issues/2116#issuecomment-2365357445 i get told that it would work using the vkd3d-proton builtin GE-Proton9-13. I wouldn't had to build it.

### Describe the solution you'd like

Allow me to choose builtin at vkd3d on a bottle.

**Comment by mirkobrombin** [comment]
It's already supported, just keep vkd3d off and pick GE as the runner

**Comment by dominikzogg** [comment]
@mirkobrombin if i disable it it leads to game (tested with another Ubisoft title) the game hangs endless on start. It seems it does not fallback. Tested with GE 9.15.
