### ISSUE TITLE
[Bug]: Bottles crash

### ISSUE THREAD

**Issue by gajohnstonjr** [bottlesdevs/Bottles#3509]
### Describe the bug

('/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Games/drive_c/windows/mono/mono-2.0/etc/mono/4.0/settings.map', '/home/USER/.var/app/com.usebottles.bottles/data/bottles/templates/38e9c9b0-aa88-4807-acc3-24993758163d/drive_c/windows/mono/mono-2.0/etc/mono/4.0/settings.map', '[Errno 9] Bad file descriptor')]  File "/app/share/bottles/bottles/backend/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1496, in create_bottle
    TemplateManager.new(environment, config)

  File "/app/share/bottles/bottles/backend/managers/template.py", line 63, in new
    shutil.copytree(

  File "/usr/lib/python3.11/shutil.py", line 573, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/shutil.py", line 527, in _copytree
    raise Error(errors)

### To Reproduce

go to bottles
run .exe file
python crashes

### Package

Flatpak from Flathub

### Distribution

Fedora 40 workstation

### Debugging Information

```shell
gajohnstonjr@DragonBorne:~$ flatpak run --command=bottles-cli com.usebottles.bottles info health-check
Official Package: true
Version: '51.13'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-555-58-02/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.10.11-200.fc40.x86_64
Disk:
    Total: 33669533696
    Free: 33669365760
RAM:
    MemTotal: 62.7GiB
    MemAvailable: 59.4GiB
Bottles_envs: null
```

### Additional context

I am very new to linux soplease excuse if I dont get it right aaway or it is not in correct format

**Comment by GabsEdits** [comment]
Missing details
