### ISSUE TITLE
[Request]: Ability to search steam managed bottles

### ISSUE THREAD

**Issue by ikcikoR** [bottlesdevs/Bottles#3511]
### Tell us the problem or your need

As it stands, the search on the top right doesn't work with Steam Bottles, which really sucks since you usually have very few custom bottles and a LOT of Steam bottles since there is one per game in Steam's case.
![image](https://github.com/user-attachments/assets/93f7ed9e-094c-4fc5-b525-6880e412d72a)

### Describe the solution you'd like

Allow the "Search your bottles..." feature to also filter Steam Proton prefixes by name

**Comment by mirkobrombin** [comment]
Closed by https://github.com/bottlesdevs/Bottles/commit/601140e104134d6489eb6a06b0125e8d531ae26d
