### ISSUE TITLE
[Request]: Win11 support

### ISSUE THREAD

**Issue by Twig6943** [bottlesdevs/Bottles#3515]
### Tell us the problem or your need

I need to open winecfg each time I want to switch the prefix's version to 11.

### Describe the solution you'd like

title

### Other solutions?

title

### Additional context and references

I want to provide a .yml file for this project but cant due to bottles not supporting win11 mode 
https://github.com/Twig6943/AffinityOnLinux

**Comment by Twig6943** [comment]
@mirkobrombin this is still missing
![image](https://github.com/user-attachments/assets/4a4bdda0-8529-41d3-97d2-3f40e556fcf1)
![image](https://github.com/user-attachments/assets/d0a03303-ff3e-40ce-960d-30ec1bfadc1b)

**Comment by Perkolator** [comment]
I already posted the same issue in the [commit](https://github.com/bottlesdevs/Bottles/commit/424af7ae86c38f7c51b47051ec246c27efdaf74f). I see @mirkobrombin answered to it but I can't answer him there because github is bugging (I can't see the comments or send new comments when I'm logged in).

**Comment by Perkolator** [comment]
The selector actually misses other versions too that are in the `catalogs.py` file:
- win95
- win98
- winxp64
- win2003

**Comment by Twig6943** [comment]
@Perkolator gotchu
![image](https://github.com/user-attachments/assets/8ffcaa17-9840-4246-9638-3170dc57b0f3)

**Comment by mirkobrombin** [comment]
win95 and win98 are not available for 64bit bottles, only 32bit.

Found the mistake for win11, a new update will be released in the next hour.

**Comment by mirkobrombin** [comment]
Nvm will take some more time, not sure why the implementation is not working.
