### ISSUE TITLE
Is it possible to use the FFmpeg variable?

### ISSUE THREAD

**Issue by bestperson-free** [bottlesdevs/Bottles#3517]
!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!
Greetings, I found in the documentation the use of https://docs.usebottles.com/faq/video-gstreamer-problems, but no where did I find the possibility of using FFmpeg for programs in bottles. Is this possible and how to do it? Thanks

**Comment by GabsEdits** [comment]
Closing since it does not follow any of our issues templates
