### ISSUE TITLE
[Request] Being able to set that all steam proton prefixes get added to bottles

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#352]
**Is your feature request related to a problem? Please describe.**
I play many steam games and want that those prefixes are added to bottles automatically cause then I could launch mods via bottles for the steam games.

**Describe the solution you'd like**
That you can set in the settings that proton prefixes automatically get added to bottles.

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/Bottles/issues/195

Steam prefixes are slightly different from regular wine prefixes.
