### ISSUE TITLE
[Request]: "Native" Force Stop all Processes option

### ISSUE THREAD

**Issue by aazanabili** [bottlesdevs/Bottles#3521]
### Tell us the problem or your need

some programs need restart to open how i can bottle(-b name) restart in Bottles

### Describe the solution you'd like

add restart or shurdown for every bottle

### Other solutions?

or alwo to use (shurdown  /r) in cmd in bottle

**Comment by mirkobrombin** [comment]
![image](https://github.com/user-attachments/assets/b9fb4bec-fa97-4e66-939f-e96e6fabdfce)

**Comment by aazanabili** [comment]
it is dont work??!!

**Comment by xlionjuan** [comment]
The "Force Stop all Processes" is useless, I need to kill the process by htop.

**Comment by mirkobrombin** [comment]
They both works for me. What’s the problem you face? Like some details rather than “does not work???”?

**Comment by xlionjuan** [comment]
If the software hangs, this button will not work, it can only be killed by htop or system dialog (xxx is not responding) and click force quit

**Comment by mirkobrombin** [comment]
That means the wineserver itself is stuck. Another option is to implement a "native" Forse Stop all Processes.
