### ISSUE TITLE
[Request] A method to speed up prefix creation

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#353]
**Is your feature request related to a problem? Please describe.**
It takes long to create a prefix in bottles.

**Describe the solution you'd like**
That instead of that bottles creates a new prefix normally that bottles has an example prefix and just copies that prefix and changes the wine and dxvk verison to the version you set in the create a new prefix menu.
And also that it uses symlink dxvk cause that is much lighter.

**Comment by mirkobrombin** [comment]
This would mean creating a prefix for each runner because everyone is different based on the runner. This cannot be done.

**Comment by Toadfield** [comment]
Why can't this be done?
I mean bottles would just need to create an example prefix for every runner that it can copy.

**Comment by mirkobrombin** [comment]
> Why can't this be done?
> I mean bottles would just need to create an example prefix for every runner that it can copy.

Because it is not a good solution to take up space on the user's disk, we have already been accused that we download files at startup, imagine taking up more space. Also, the process would slow down the installation of a new runner.
