### ISSUE TITLE
[Bug]: None of my apps have a icon

### ISSUE THREAD

**Issue by Wolfey-foryou** [bottlesdevs/Bottles#3538]
### Describe the bug

All of the apps i open/use on bottles js have the bottles icon
![image](https://github.com/user-attachments/assets/19805199-ec2c-4cc2-bb06-bd8413c9f805)
![image](https://github.com/user-attachments/assets/68a71829-bb38-49d7-9f5d-ac860cbfe0ff)

### To Reproduce

Just start an app with bottles prob only on gnome tho tried on kde its normal

### Package

Flatpak from Flathub

### Distribution

Fedora 40

### Debugging Information

```shell
Official Package: true
Version: '51.15'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.11.3-200.fc40.x86_64
Disk:
    Total: 8310431744
    Free: 8310259712
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.0GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment]
Nothing we can fix here, that’s how works on gnome
