### ISSUE TITLE
The Bottles forum never loads

### ISSUE THREAD

**Issue by Jack-Balcombe** [bottlesdevs/Bottles#3539]
Hi,
Is it just me, or does the forum link for bottles, [forum.usebottles.com](https://forum.usebottles.com), not work anymore? Whenever I try to go to the forums, the website never loads. I have tried on both wifi and mobile data, on multiple browsers and devices. It's been like this for more than half a year.

If your forum is down or the URL has changed, can you please update / fix this?
Thanks.

![ksnip_20241020-061258](https://github.com/user-attachments/assets/1eaf58b8-3e32-4a1f-816f-e04eb51eed60)
![ksnip_20241020-061256](https://github.com/user-attachments/assets/b0f5acf7-bd81-415c-853c-53f7ee9e6fac)

**Comment by Dskobra** [comment]
Same issue here. Tried both ping and tracerotue where the former had no response.

jordan@DESKTOP-LINUX:~$ traceroute forum.usebottles.com
traceroute to forum.usebottles.com (163.172.176.180), 30 hops max, 60 byte packets
 1  _gateway (192.168.50.1)  0.585 ms  0.591 ms  0.603 ms
 2  machnet-88-129.machlink.com (69.49.88.129)  3.580 ms  4.092 ms  4.102 ms
 3  mach-v4v6-90-110.machlink.com (69.49.90.110)  3.513 ms  3.499 ms  3.510 ms
 4  10.200.200.2 (10.200.200.2)  3.421 ms  3.431 ms  3.412 ms
 5  e0-32.core1.dvn1.he.net (216.66.77.217)  9.228 ms  9.237 ms  9.805 ms
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  scaleway-dc2.par.franceix.net (37.49.237.111)  98.721 ms  98.736 ms scaleway-dc3.par.franceix.net (37.49.237.27)  98.727 ms
11  195.154.1.189 (195.154.1.189)  98.745 ms  98.044 ms  98.078 ms
12  51.158.0.187 (51.158.0.187)  98.041 ms  98.026 ms 51.158.0.149 (51.158.0.149)  98.429 ms
13  10.42.235.67 (10.42.235.67)  98.928 ms 10.42.235.65 (10.42.235.65)  98.889 ms  98.389 ms
14  10.56.108.10 (10.56.108.10)  98.035 ms  98.052 ms  97.568 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by Sturmlocke86** [comment]
Same here, was about to post the same. +1 issue OP

**Comment by mirkobrombin** [comment]
Just moved here https://github.com/orgs/bottlesdevs/discussions
