### ISSUE TITLE
[Bug]: Clicking on a snapshot instantly starts the restore process

### ISSUE THREAD

**Issue by t-nil** [bottlesdevs/Bottles#3544]
### Describe the bug

Hi! I just tried to rename a snapshot, but a left-click on it instantly started the restore, which is definitely not what I wanted.
Since this is (correct me) a destructive operation, I think it would be wise to double-check with the user ("are you sure?"); maybe even in the Gnome style of changing the list entry into having ✓and ✗buttons on the right (I think I've seen it someplaces). Of course, a click selecting the snapshot and offering a menu to do things like delete, rename, would also be a  wonderful solution!

I'm really not versed enough in Gtk to start a PR myself; would you kindly consider that feature? 

![image](https://github.com/user-attachments/assets/9422d83e-2131-45c2-98e3-26a2705f7f02)
Also I'm a bit confused as to why one of the entries has a dedicated "Restore" button, but for both entries, simply clicking on them starts the restore.

### To Reproduce

1. Create a bottle
2. Create multiple snapshots
3. (Accidentally) click on a snapshot

### Package

Flatpak from Flathub

### Distribution

Linux ra1n-desktop-manjaro 6.11.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 01:37:46 +0000 x86_64 GNU/Linux

### Debugging Information

```shell
Official Package: true
Version: '51.13'
DE/WM: xfce
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.11.5-1-MANJARO
Disk:
    Total: 14657966080
    Free: 14657814528
RAM:
    MemTotal: 27.3GiB
    MemAvailable: 13.1GiB
Bottles_envs: null
```

### Additional context

I think this is a bug, since a user can accidentally start a destructive non-reversible operation. But if you disagree, feel free to change to "Feature Request"

**Comment by mirkobrombin** [comment]
It’s actually both

**Comment by mirkobrombin** [comment]
Aborting is not possible due to the nature of FVS

**Comment by t-nil** [comment]
Hey, I would argue against closing this issue. The main thing is that Bottles starts this destructive action without asking for additional information. (That should be possible regardless of the process being abortable.)
