### ISSUE TITLE
Be less alcohol related

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#356]
Bottles is a prefix manager for Wine, so it was easy to fall into the game of adapting to wine-based nomenclature. I would like to remedy this situation by trying to rename (where possible) the terminologies, to something less explicit.

### The problem
The problem is the risk of _unconsciously introducing people to alcoholism_, treating it like a game. Bottles was (obviously) not born with this intent but I don't want it to be seen as such.

Renaming the whole project can be a problem, there have already been too many major changes and it is necessary to calm things down. What it is possible to do in the near future is to rename our Chardonnay runner to something less explicit and change the internal terminology of the program, avoiding to refer to Wine as little as possible. This procedure has already started with v2 (for others purposes) by renaming wine to runner.

## When
Definitely as soon as possible but first you have to wait for the flatpak to be updated to the new stable on July 14th, as the components repository has to be modified to support the new terminology and I would like to do it in the new standard Yaml format.

Thanks to @sophie-h to [bring the "problem" to my attention](https://gitlab.gnome.org/Teams/Circle/-/issues/61#note_1097417).

**Comment by thegarlynch** [comment]
We should limit how many bottles people could run, not banning alcohol altogether

**Comment by mirkobrombin** [comment]
> We should limit how many bottles people could run, not banning alcohol altogether

You are right but unfortunately there are those who know no limits.

**Comment by ZekeSmith** [comment]
I don't think a new name is necessary bottles is a fine name but perhaps changing the logo design language into more friendly drinks such as a bottle of milk, water and orange juice.

**Comment by mirkobrombin** [comment]
> I don't think a new name is necessary bottles is a fine name but perhaps changing the logo design language into more friendly drinks such as a bottle of milk, water and orange juice.

For now, it is not in the plans to change the name of the project.

**Comment by ZekeSmith** [comment]
yeah I misread it a little bit I still think the main logo needs a change though I think it looks really cool already just making it resemble safer drinks would be a good start and probably the most impactful change. After that most of it I personally don't notice on daily usage but it is better to remove as much as you can. Images and icons will have the biggest impact so I personally would start with the main logo and then move to the internal icons and symbols.

**Comment by mirkobrombin** [comment]
> yeah I misread it a little bit I still think the main logo needs a change though I think it looks really cool already just making it resemble safer drinks would be a good start and probably the most impactful change. After that most of it I personally don't notice on daily usage but it is better to remove as much as you can. Images and icons will have the biggest impact so I personally would start with the main logo and then move to the internal icons and symbols.

I agree with you, I should hear @jannuary who designed the logo, maybe even @alvarlagerlof might have some ideas.

**Comment by ZekeSmith** [comment]
I had some spare time I just designed a new logo design mock up its basic but I want a concept similar to the new one:
![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124922162-56e6c500-e04d-11eb-8614-7c20cfd11c5f.png)
I cant figure out a good design for the water bottle but I think something similar with the orange and milk bottles could work

**Comment by mirkobrombin** [comment]
> I had some spare time I just designed a new logo design mock up its basic but I want a concept similar to the new one:
> ![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124922162-56e6c500-e04d-11eb-8614-7c20cfd11c5f.png)
> I cant figure out a good design for the water bottle but I think something similar with the orange and milk bottles could work

I really like the idea (and the work itself)

**Comment by ZekeSmith** [comment]
Thanks I'm still thinking of a way to do the water bottle better though.

**Comment by ZekeSmith** [comment]
![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124932405-299f1480-e057-11eb-89c7-438a9a6bec35.png)
alright I did some polishing up and I got something to look good

**Comment by mirkobrombin** [comment]
> ![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124932405-299f1480-e057-11eb-89c7-438a9a6bec35.png)
> alright I did some polishing up and I got something to look good
Much cleaner. Is the white of the bottle on the right transparent or an error?

**Comment by ZekeSmith** [comment]
transparent but on second thoughts white might look better

**Comment by ZekeSmith** [comment]
![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124933536-13de1f00-e058-11eb-956c-aa703dabd51b.png)
try this

**Comment by mirkobrombin** [comment]
> ![com usebottles bottles](https://user-images.githubusercontent.com/81902668/124933536-13de1f00-e058-11eb-956c-aa703dabd51b.png)
> try this

![image](https://user-images.githubusercontent.com/9479903/124933632-537b1b80-e004-11eb-9ef6-a5e21b67af64.png)

better

**Comment by ZekeSmith** [comment]
its supposed to be a handle but idk if black or white would look better for it

**Comment by mirkobrombin** [comment]
> its supposed to be a handle but idk if black or white would look better for it

ah ok it looked like a label haha

**Comment by ZekeSmith** [comment]
yeah thats why I had it transparent idk the best way to make it look like a handle

**Comment by ZekeSmith** [comment]
maybe I remove it and people can use their imagination that the handle is behind the bottle

**Comment by mirkobrombin** [comment]
> maybe I remove it and people can use their imagination that the handle is behind the bottle

it seems great to me, let's hide the problem behind the bottle hahaha

**Comment by ZekeSmith** [comment]
![image](https://user-images.githubusercontent.com/81902668/124934258-aa124500-e058-11eb-8990-6522942aade5.png)

**Comment by mirkobrombin** [comment]
Maybe the cap from the first concept was better for the third bottle

**Comment by ZekeSmith** [comment]
yeah let me try that

**Comment by ZekeSmith** [comment]
![image](https://user-images.githubusercontent.com/81902668/124934960-518f7780-e059-11eb-8978-378ad91ff18b.png)

**Comment by jannuary** [comment]
My vision:
![image](https://user-images.githubusercontent.com/27908024/124935212-a8805700-e02f-11eb-91b7-f04f88230488.png)

**Comment by mirkobrombin** [comment]
It might be a good idea to combine the two concepts. I really like the central bottle of the first and the last of the second

**Comment by ZekeSmith** [comment]
yeah I like the idea I feel the color pallet doesnt stand out well though and I have no idea what beverages those are supposed to be first one still looks like an alcoholic beverage

**Comment by jannuary** [comment]
@ZekeSmith can you send your svg over?

**Comment by ZekeSmith** [comment]
yep sure

**Comment by ZekeSmith** [comment]
I cant upload it here whats the best way to get it to you?

**Comment by mirkobrombin** [comment]
> I cant upload it here whats the best way to get it to you?

archive?

**Comment by jannuary** [comment]
Could you rename it to .txt and send it that way?

**Comment by ZekeSmith** [comment]
that makes sense, its early in the morning for me.
[com.usebottles.bottles.zip](https://github.com/bottlesdevs/Bottles/files/6785092/com.usebottles.bottles.zip)

**Comment by jannuary** [comment]
Aight, thanks!

**Comment by ZekeSmith** [comment]
> It might be a good idea to combine the two concepts. I really like the central bottle of the first and the last of the second

I agree I didn't even think of hot beverage bottles or what I presume that is.

**Comment by ZekeSmith** [comment]
also for the small svg bottle icon I feel like a scaled down version of the milk bottle would work pretty well.

**Comment by ZekeSmith** [comment]
yeah I think it is.

**Comment by jannuary** [comment]
Not sure how to make the label on the middle one look good:
![image](https://user-images.githubusercontent.com/27908024/124938199-4c6b0200-e032-11eb-9164-621ba2bcc2b4.png)

**Comment by ZekeSmith** [comment]
I think the milk drop looks better and maybe make the left look less like alcohol I think it still does.

**Comment by ZekeSmith** [comment]
perhaps a orange or green cap to it instead of the black one and make the orange more saturated.

**Comment by mirkobrombin** [comment]
> Not sure how to make the label on the middle one look good:
> ![image](https://user-images.githubusercontent.com/27908024/124938199-4c6b0200-e032-11eb-9164-621ba2bcc2b4.png)

I really like the black cap in the thermos but it could be a problem on dark backgrounds

**Comment by ZekeSmith** [comment]
no no sorry bad explaining on my half I meant the orange juices lid color.

**Comment by jannuary** [comment]
Iteration:
![image](https://user-images.githubusercontent.com/27908024/124941442-fd729c00-e034-11eb-955d-d738745f0333.png)

**Comment by ZekeSmith** [comment]
I like the bottle to the left more now but the milk now seems far to bland to be in the center and doesnt feel authentic it almost looks like another alcoholic item.

**Comment by ZekeSmith** [comment]
![image](https://user-images.githubusercontent.com/81902668/124941935-4b03fe80-e05f-11eb-9756-175eb007c73f.png)

**Comment by ZekeSmith** [comment]
this is what I have so far I have changed the water bottle on the right to resemble more of a metallic water bottle I also fixed the smoothing of the bottles and made the milk bottle jagged.

**Comment by ZekeSmith** [comment]
can I have your svg file possibly?

**Comment by jannuary** [comment]
Right, here you go: 
[com.usebottles.Bottles.Source.txt](https://github.com/bottlesdevs/Bottles/files/6785435/com.usebottles.Bottles.Source.txt)

**Comment by ZekeSmith** [comment]
![image](https://user-images.githubusercontent.com/81902668/124944059-21e46d80-e061-11eb-821c-4090aa96c4c8.png)

**Comment by jannuary** [comment]
Are you on Telegram or Matrix by any chance?
We can continue there if that's more convenient to you.

**Comment by ZekeSmith** [comment]
yeah @t4bzl0ck:matrix.org

**Comment by mirkobrombin** [comment]
a demo from behind the scenes
![image](https://user-images.githubusercontent.com/9479903/124959355-69480b00-e01b-11eb-8bd0-1e6589f7674a.png)

**Comment by ZekeSmith** [comment]
Current progress to more fit a mate scheme and contrast well with other gnome applications.
![image](https://user-images.githubusercontent.com/81902668/125014198-9a264f80-e0b0-11eb-9347-9250993f1c5d.png)

**Comment by ZekeSmith** [comment]
Current final logo:
![image](https://user-images.githubusercontent.com/81902668/125184262-a7357100-e25f-11eb-9c02-5bff1af09988.png)

**Comment by pervoj** [comment]
@ZekeSmith In which app is the icon made?

**Comment by ZekeSmith** [comment]
Inkscape.

**Comment by mirkobrombin** [comment]
this issue will be completed in 2021.8.14
