### ISSUE TITLE
[Request]: MFC140 missing in the dependencies section

### ISSUE THREAD

**Issue by Twig6943** [bottlesdevs/Bottles#3569]
### Tell us the problem or your need

![image](https://github.com/user-attachments/assets/270c1be0-5a65-4554-8a79-6672c09b6078)

### Describe the solution you'd like

title.

### Other solutions?

title.

### Additional context and references

title.

**Comment by mirkobrombin** [comment]
Duplicate of https://github.com/bottlesdevs/dependencies/issues/157
