### ISSUE TITLE
[Bug]: Deleting a bottle created on a different drive doesnt delete cache directories

### ISSUE THREAD

**Issue by guaanch** [bottlesdevs/Bottles#3573]
### Describe the bug

When deleting a bottle that was created on a different directory than default (in my case in a different drive mounted on /mnt), the cache folder located on `~/.var/app/com.usebottles.bottles/data/bottles/bottles/` with the bottles name isn't removed. This causes an error when trying to create a bottle with the same name. Deleting the cache directory manually fixes the issue.

### To Reproduce

1.- Create a custom bottle on a different directory than default.
2.- Delete said bottle.
3.- Create a bottle with the same name.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.15'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.12.1-2-cachyos
Disk:
    Total: 16786145280
    Free: 16785973248
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
#Bottle deletes without errors
15:19:09 (INFO) Deleted the bottle in: /mnt/hdd/Bottles/Test

#Creating a bottle with the same name shows this error
15:19:54 (ERROR) Failed to create placeholder directory/file at: /home/juan/.var/app/com.usebottles.bottles/data/bottles/bottles/Test
```

### Additional context
File permissions have been setup using flatseal to grant access to mounted drives on /mnt

**Comment by LukeElrod** [comment]
This issue is still present in the latest flatpak
