### ISSUE TITLE
[Request]: "bottles-cli run" should provide the output of the invoked windows application/program to STDOUT

### ISSUE THREAD

**Issue by OrbitingOcelot** [bottlesdevs/Bottles#3574]
### Tell us the problem or your need

I am using bottles to run some legacy win applications that perform various services, and have created programs for those applications. I need to parse the output of the applications in my scripts, however, if these programs are invoked via bottles-cli run, their output is not shown.

Example:
```
user@sys:$ flatpak run  --command=bottles-cli com.usebottles.bottles run -p 'MyProgram' -b SomeBottle
19:50:07 (INFO) Forcing offline mode 
wineserver: using server-side synchronization.
user@sys:$
```

I believe most users would expect to see the actual program out here, but it is not provided.

### Describe the solution you'd like

```
user@sys:$ flatpak run  --command=bottles-cli com.usebottles.bottles run -p 'MyProgram' -b SomeBottle
19:50:07 (INFO) Forcing offline mode 
wineserver: using server-side synchronization.
!!!Output from the windows application/program goes here
!!!Output from the windows application/program goes here
!!!Output from the windows application/program goes here
user@sys:$
```

### Other solutions?

It is possible to achieve this with "bottles-cli shell", however this is not very convenient to setup.
This could also be a command-line argument for "bottles-cli run" like for example "-o   provide program output".

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/commit/f31c0a7af7c66f7e69bf1504a07bdbb160075636
