### ISSUE TITLE
can you add Microsoft store

### ISSUE THREAD

**Issue by ikkqqstudio** [bottlesdevs/Bottles#3580]
it is possible to add Microsoft store on Bottles?

**Comment by BrycensRanch** [comment]
+1 it’s very surprising this hasn’t been added yet

**Comment by CardboardDog** [comment]
As far as I know, it's not currently possible because the MS store is UWP.

**Comment by mirkobrombin** [comment]
Hi, this is not possible at the moment https://github.com/bottlesdevs/Bottles/issues/1248
