### ISSUE TITLE
[Request] Being able to select bottles as a runner for steam windows games

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#359]
**Is your feature request related to a problem? Please describe.**
I want to start my steam windows games with bottles so I can start them in different prefixes and that I can choose wine versions that steam doesn't support.

**Describe the solution you'd like**
That you can choose bottles as the runner for steam windows games.

**Additional context**
There are other programs that support it to set them as a runner for steam proton games (for example proton tkg),so it should be possible for bottles to achieve that somehow.

**Comment by mirkobrombin** [comment]
The only way to launch Windows games from Steam is to install Steam for Windows in a bottle. As already mentioned, Proton prefixes are not normal prefixes, Valve implements several patches to integrate with the functionality of the Steam client and third parties (origin etc). You can't just use a Bottles runner in Steam.
