### ISSUE TITLE
[Bug]: Bottles generated desktop files or flatpak run --command=bottles-cli com.usebottles.bottles run -p 'Hollow Knight' -b 'Hollow Knight' -- %u (or any other game) dont work anymore)

### ISSUE THREAD

**Issue by Sinaaaa** [bottlesdevs/Bottles#3595]
### Describe the bug

Generated desktop files stopped working.
`run` doesn't find the correct files or config???

### To Reproduce

run `flatpak run --command=bottles-cli com.usebottles.bottles run -p 'Hollow Knight' -b 'Hollow Knight' -- %u
` or force exec generated desktop file.

### Package

Flatpak from Flathub

### Distribution

Arch BTW

### Debugging Information

```shell
Official Package: true
Version: '51.16'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd: &amp;id002
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.12.4-arch1-1
Disk:
    Total: 8219500544
    Free: 8219324416
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 13.2GiB
Bottles_envs: null
```
```


### Troubleshooting Logs

```shell
+> flatpak run --command=bottles-cli com.usebottles.bottles run -p 'Hollow Knight' -b 'Hollow Knight' -- %u
07:25:39 (INFO) Forcing offline mode 
ERROR:root:Config file not exists
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 184, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
INFO:root:Bottles found:
	 - Dead Cells
	 - Hollow Knight
```
```


### Additional context

_No response_

**Comment by Sinaaaa** [comment]
Of course if I click the game within the Bottles client all is well.

**Comment by chriswegit** [comment]
Also generated links via "add to steam" are not working anymore - maybe the same type of issue?

**Comment by Kheperu** [comment]
Same issue here.

`flatpak run --command=bottles-cli com.usebottles.bottles run -p Roon -b Roon -- %u
09:39:17 (INFO) Forcing offline mode 
ERROR:root:Config file not exists
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 184, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
INFO:root:Bottles found:
         - Roon
         - MP3Tag
         - CUETool
         - Vortex
         - EA Launcher
         - Old Windows games
         - ComicRack
`
App starts fine if run from Bottles app, but not from terminal or Desktop Entry.

**Comment by Kheperu** [comment]
Can confirm rolling back to previous version of Bottles (51.15) fixes the issue

**Comment by Leniptic** [comment]
Same problem, none of my desktop shortcuts work anymore, but every application can still be launched directly through Bottles. A bit annoying, lol

**Comment by NK01** [comment]
Same problem, none of my desktop shortcuts work anymore, but every application can still be launched directly through Bottles.

> Can confirm rolling back to previous version of Bottles (51.15) fixes the issue

Can confirm this works

**Comment by prozessor666** [comment]
Can confirm as well. Do not even get an error message. Program just refuses to start.

**Comment by TacoCake** [comment]
Possibly related to:
- https://github.com/bottlesdevs/Bottles/issues/3598
- https://github.com/bottlesdevs/Bottles/issues/3598
