### ISSUE TITLE
[Bug]: Desktop Shortcut for bat file doesnt run

### ISSUE THREAD

**Issue by renhiyama** [bottlesdevs/Bottles#3598]
### Describe the bug

I am modding a game, hence I have a `start.bat` file in my game directory. I have added the shortcut to that bat file, and it actually works out of the box in Bottles GUI.
However, when I add it as a desktop shortcut (linux side) and run it, it doesnt start. By grabbing the  `.desktop` file's Exec command, its just:
```
flatpak run --command=bottles-cli com.usebottles.bottles run -p 'Game Modded' -b 'Games'
21:30:13 (INFO) Forcing offline mode 

```
Whereas if I ran the shortcut from Bottles GUI, it will open a command prompt and runs the commands as expected and logs its messages in console and even games open properly.

### To Reproduce

I would suggest just write a bat file with an echo command & `start <game>.exe` and add it as a shortcut in bottles gui, and then export a desktop shortcut, and run via that. GUI works, but desktop shortcut wont.

### Package

Flatpak from Flathub

### Distribution

Fedora 41

### Debugging Information

```shell
Official Package: true
Version: '51.16'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.11.10-300.fc41.x86_64
Disk:
    Total: 16439738368
    Free: 16439566336
RAM:
    MemTotal: 30.6GiB
    MemAvailable: 22.3GiB
Bottles_envs: null
```

**Comment by mufabil45** [comment]
Have a same issue on my end as well, got it fixed by downgrading the version with this command.

```sudo flatpak update --commit=ba8aaeebfa31af3b3bcd01376f583d630c015d5cb09678b691a545d794972927 com.usebottles.bottles```

**Comment by mirkobrombin** [comment]
Maybe the new way we run the executable in bottles-cli is not compatible with .bat files.
