### ISSUE TITLE
[Bug]: Launching .exe files from the file manager no longer works.

### ISSUE THREAD

**Issue by ndiruhniu** [bottlesdevs/Bottles#3601]
### Describe the bug

I launch applications and games through the file manager, because it is convenient. But starting with version 51.16 it stopped working. I also checked on version 51.17, it does not work.

### To Reproduce

1. Double click on .exe/.msi/.bat file.
2. Select bottle.
3. Nothing happens.

### Package

Flatpak from Flathub

### Distribution

Mint 22 (Ubuntu 24.04)

### Debugging Information

```shell
Official Package: true
Version: '51.17'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.11.11-x64v1-xanmod1
Disk:
    Total: 12490940416
    Free: 12490768384
RAM:
    MemTotal: 23.3GiB
    MemAvailable: 20.4GiB
Bottles_envs: null
```

**Comment by DFaby26** [comment]
lo voy a poner en español el error que parece pasar  esta relacionado con _executable  porque ejecutar 
flatpak run --command='bottles-cli' com.usebottles.bottles   run -b "$BOTTLE" -e "$EXECUTABLE_GAME"  da un error  que es el siguiente "UnboundLocalError: cannot access local variable 'program' where it is not associated with a value
" pero si ejecutas usando -p funciona  , agrego una imagen del error.
![error](https://github.com/user-attachments/assets/8b948455-ee4f-4f3c-836e-5db0f5719659)

**Comment by ndiruhniu** [comment]
I don't quite understand what this has to do with it. Everything worked in version 51.15, so I had to roll back to it.

**Comment by jntesteves** [comment]
Fixed in #3605, will be in the next version. Thanks for reporting the issue.

**Comment by ndiruhniu** [comment]
Thanks for fixing this

**Comment by EmRodDev** [comment]
@jntesteves Still being an issue on Fedora Worksation 42. The "Select bottle" menu appears in case you have more than one configured bottle, but nothing happens after choosing one.

**Comment by ndiruhniu** [comment]
@EmRodDev You need to grant access to the home directory for the application Bottles through Flatseal.
