### ISSUE TITLE
Program launcher doesn't appear after installation

### ISSUE THREAD

**Issue by Naadiyaar** [bottlesdevs/Bottles#3622]
So I tried this with multiple programs and all of them launch successfully after installation (via install wizard) but I can't find a launcher to run the program afterward.

considering the documentation, bottles understands information about executables from a generated `.lnk` file. so I tracked them to this path:
```
find ~ 2>/dev/null -name "*.lnk" -type f
/home/nadiyar/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/PowerShell/PowerShell 7 (x64).lnk
/home/nadiyar/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/Public/Desktop/Stars.lnk
/home/nadiyar/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Games/Stars/Stars.lnk
/home/nadiyar/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Games/Stars/Uninstall Stars.lnk
```
![Screenshot from 2024-12-21 03-44-21](https://github.com/user-attachments/assets/058cb20e-a2d1-45b1-bc09-e29807f76476)

Also I should add to successfully install programs I had to copy them into `.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/steamuser/Desktop/` and run the .exe file from there.

version `51.17`
flatpak 
on Fedora 40 gnome 46

**Comment by Naadiyaar** [comment]
tried manually copying Star.lnk to `.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/steamuser/AppData/Roaming/Stars/` doesn't help

**Comment by jntesteves** [comment]
If you copy the link to `~/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/` does it work? It seems Bottles read PowerShell correctly from that path (the user's Start Menu), but failed to read the link to your app from the system's Start Menu at `~/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/`.

**Comment by Naadiyaar** [comment]
> If you copy the link to `~/.var/app/com.usebottles.bottles/data/bottles/bottles/lust/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/` does it work? 

this is not working either.

But apparently the problem is from apps I tried to install.
I created a new bottle and installed Notepad++ and Stardew Valley. and even though their `.lnk` files exist in the same path, notepad++ launcher is available but for Stardew Valley it isn't.

```
~/.var/app/com.usebottles.bottles/data/bottles/bottles/stardew
=> find . -name "*.lnk"
./drive_c/users/Public/Desktop/Stardew Valley.lnk
./drive_c/users/Public/Desktop/Notepad++.lnk
./drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Games/Stardew/Stardew Valley.lnk
./drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Games/Stardew/Uninstall Stardew Valley.lnk
./drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Notepad++.lnk
```
![image](https://github.com/user-attachments/assets/26baef55-59b3-424b-bfd8-9809cb42a807)

Also tried different paths and file names (no spaces, capital letters) but the issue persists.

If you think nothing else can be done, feel free to close the issue.
thanks for the reply.

**Comment by Naadiyaar** [comment]
One more question, isn't there any other way to run the program?

**Comment by jntesteves** [comment]
> One more question, isn't there any other way to run the program?

There's the big "+ Add Shortcuts..." button right under the programs list. It lets you manually create an entry on the list for a program that doesn't install a link.

But this seems like a genuine bug, I think those links should've been added to the list.

**Comment by Naadiyaar** [comment]
Adding entry manually causes error when running the program
![Screenshot from 2024-12-21 19-14-20](https://github.com/user-attachments/assets/502a1517-ac92-4816-a1fd-5c157b1d38bf)

```
flatpak run com.usebottles.bottles

(bottles:2): Gtk-WARNING **: 19:15:05.492: Theme parser warning: style.css:184:3-185:1: Expected ';' at end of block

(bottles:2): Gtk-WARNING **: 19:15:05.492: Theme parser warning: style-dark.css:23:3-24:1: Expected ';' at end of block
19:15:05 (INFO) Launching with URI: None
19:15:05 (INFO) [Activate] request received.
19:15:05 (INFO) Bottles Started!
19:15:10 (INFO) Performing Bottles checks…
19:15:10 (INFO) Dxvks found:
         - dxvk-2.5.1

19:15:10 (INFO) Vkd3ds found:
         - vkd3d-proton-2.13

19:15:10 (INFO) Nvapis found:
         - dxvk-nvapi-v0.7.1

19:15:10 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1

19:15:10 (INFO) Runners found:
         - soda-9.0-1
         - sys-wine-9.0

19:15:10 (INFO) Bottles found:
         - stardew

19:15:11 (INFO) Catalog installers loaded
19:15:11 (INFO) Catalog dependencies loaded
19:15:11 (INFO) Catalog components loaded
19:15:13 (INFO) Setting Key sync=fsync for bottle stardew…
19:15:13 (INFO) There is no running wineserver.
19:15:19 (INFO) Launching an executable…
19:15:19 (INFO) Using Wine Starter -- run
19:15:19 (INFO) Using EasyAntiCheat runtime
19:15:19 (INFO) Using BattlEye runtime
fsync: up and running.
19:15:32 (WARNING) ShellExecuteEx exception seems occurred.
```

**Comment by Naadiyaar** [comment]
> There's the big "+ Add Shortcuts..." button

Other than installation wizard there's no other executable available to add as a shortcut.
should I add the `.lnk` file?

**Comment by jntesteves** [comment]
> Other than installation wizard there's no other executable available to add as a shortcut. should I add the `.lnk` file?

No, you must add the .exe, which should be somewhere in the drive_c/ directory if the program was installed successfully. If there's no program where the links point to, maybe that's why they're not showing on the List in Bottles.

There could be other drives mounted in the Bottle. If the setup wizard didn't install to `C:`, the program's folder could be somewhere else. If that somewhere else was not given permission in Flatseal, it went to a mount "in memory"-only and the data was lost when you closed Bottles. Happened to me once. Make sure you install to `C:` or a drive that you know you've given permission for Bottles to access.

**Comment by Naadiyaar** [comment]
Oh yes! Wizard was installing to `z:` which is a symlink to my system's root and the rest is as @jntesteves mentioned.
changed the installation path to `c:` and now launcher is there and game runs fine.
Yay 🥰 🎉

solution: https://github.com/bottlesdevs/Bottles/issues/3622#issuecomment-2558163087
