### ISSUE TITLE
[Bug]: Bottles won't start after latest python update

### ISSUE THREAD

**Issue by efwis** [bottlesdevs/Bottles#3630]
### Describe the bug

just updated my system using EndeavourOS upon trying to start a program in bottles I get complete stop. tried to run bottles via terminal to receive any errors. Python 3 was just updated today.

This does not affect the flatpak, however I will not use flatpak for bottles  as I don't feel like tinkering around to make my files accessible to bottles and my program, let alone having to reinstall them.

### To Reproduce

click on bottles itself or a program installed via bottles from the shortcut menu
system starts running for about 30 seconds and never loads closing out the process.

### Package

Flatpak from Flathub

### Distribution

EndeavourOS

### Debugging Information

```shell
Official Package: true
Version: '51.17'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.12.6-arch1-1
Disk:
    Total: 7244840960
    Free: 7244668928
RAM:
    MemTotal: 13.5GiB
    MemAvailable: 11.6GiB
Bottles_envs: null
```

### Additional context

i refuse to use flatpak crap on my computer. Below you will find what errors are being printed from terminal.

Traceback (most recent call last):
  File "/usr/bin/bottles", line 49, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 30, in <module>
    from bottles.backend.managers.manager import Manager
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 31, in <module>
    import pathvalidate
ModuleNotFoundError: No module named 'pathvalidate'

**Comment by mydongistiny** [comment]
This isn't a bottles error. Your deps need to be rebuilt for the new python. You need to rebuild python-pathvalidate icoextract patool python-fvs vkbasalt-cli .
