### ISSUE TITLE
[Bug]: Fedora namespace Xdp not available

### ISSUE THREAD

**Issue by Kenny-Dave** [bottlesdevs/Bottles#3647]
### Describe the bug

Bottles won't open after Fedora update. Please forgive my ignorance, I am quite green. Full error is 

```
name@fedora:~$ bottles
Traceback (most recent call last):
  File "/usr/bin/bottles", line 49, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 29, in <module>
    gi.require_version("Xdp", "1.0")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xdp not available
```

libxdp installed version: 

```
name@fedora:~$ dnf list --installed | grep xdp
libxdp.x86_64                                        1.4.3-1.fc41                        <unknown>
```

Bottles installed version: 
```
name@fedora:~$ dnf list --installed | grep bottles
bottles.noarch                                       1:51.17-2.fc41                      <unknown>
```

The commands for debugging listed below give me an error: 
```
error: app/com.usebottles.bottles/x86_64/master not installed
```

I have tried uninstalling and reinstalling bottles, and rebooting, without success. 

### To Reproduce

Install bottles in Fedora 41.

### Package

Flatpak from Flathub

### Distribution

Fedora 41 kernel 6.12.6.200 64 bit, KDE 6.2.4, Frameworks 6.9.0

### Debugging Information

```shell
name@fedora:~$ flatpak run --command=bottles-cli com.usebottles.bottles info health-check
error: app/com.usebottles.bottles/x86_64/master not installed
```
```


### Troubleshooting Logs

_No response_

### Additional context

_No response_

**Comment by orowith2os** [comment]
Not a supported package of ours, please file an issue with the Fedora maintainers, not us.

**Comment by Kenny-Dave** [comment]
Thanks, the flatpak version works fine on Fedora. Just adding a note for anyone else with the same issue.
