### ISSUE TITLE
[Request] Being able to set that all bottles use the same prefix

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#368]
**Is your feature request related to a problem? Please describe.**
I want that every bottle uses the same prefix so that I don't have to look in every bottle to find my programs.

**Describe the solution you'd like**
That in the settings of a bottle that you can then select which bottles prefix it should use.

**Comment by mirkobrombin** [comment]
Why don't you just use one bottle?
If these bottles are configured differently then the answer is no: it cannot be done in Bottles.
