### ISSUE TITLE
[Request] Being able to temporarily launch a program in a non bottles prefix via a bottles wine version.

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#369]
**Is your feature request related to a problem? Please describe.**
I want to install a mod for a steam game,therefore I want that the installer gets launched with the steam prefix.

**Describe the solution you'd like**
That in the Settings of a bottle you can launch a program in a non bottles prefix.

**Comment by mirkobrombin** [comment]
Why don't you just use a bottle?
If these bottles are configured differently then the answer is no: it cannot be done in Bottles.

**Comment by mirkobrombin** [comment]
You can use runners installed in Bottles on an external prefix, from the command line:
```bash
cd ~/.local/share/bottles/runners/
WINEPREFIX="path/to/prefix" ./vaniglia-6.11/bin/wine64 path/to/file.exe
```
