### ISSUE TITLE
[BUG] Appimage compatibility with Ubuntu 18.04

### ISSUE THREAD

**Issue by rubberneck** [bottlesdevs/Bottles#375]
**Describe the bug**
Bottles errors when creating new a bottle.

**Installation**
 - Method: Appimage
 - Version: 2021.7.14
 
**To Reproduce**
1. install appimage
2. run `bottles` 
3. click `Create a new Bottle`
4. fill form name: evernote | choose software as enviroment
5. click `create`
6. see error

**Expected behavior**
For it to create a new bottle

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**
```
$ bottles 
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
2021-07-14 14:27:15 INFO: Dxvk found: [dxvk-1.9]
2021-07-14 14:27:15 INFO: Vkd3d found: [vkd3d-v2.4]
2021-07-14 14:27:15 INFO: Runners found: [vaniglia-6.11]
2021-07-14 14:27:16 INFO: Bottles Started!
2021-07-14 14:27:32 INFO: Creating the wineprefix …
wine: could not load ntdll.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/user/.local/share/bottles/runners/vaniglia-6.11/bin/../lib/wine/x86_64-unix/ntdll.so)
2021-07-14 14:27:33 INFO: Generating Bottle configuration file …
2021-07-14 14:27:33 INFO: Applying environment: [Software] …
2021-07-14 14:27:34 ERROR: Error while running async job: <bound method BottlesRunner.async_create_bottle of <bottles.runner.BottlesRunner object at 0x7fef9b7676a0>>
Exception: [Errno 2] No such file or directory: '/home/user/.local/share/bottles/bottles/evernote/bottle.yml'
  File "/tmp/.mount_bottleoYfQER///usr/local/share/bottles/bottles/utils.py", line 184, in target
    result = self.task_func(*args, **kwargs)
  File "/tmp/.mount_bottleoYfQER///usr/local/share/bottles/bottles/runner.py", line 1057, in async_create_bottle
    with open(f"{bottle_complete_path}/bottle.yml", "w") as configuration_file:
```

**Comment by mirkobrombin** [comment]
The AppImage has not been tested on Ubuntu 18.04. It seems a library is missing, I will try to reply in the next few days. In the meantime, you can use another package.

**Comment by mirkobrombin** [comment]
So this is the problem:
```bash
wine: could not load ntdll.so
```

Wine is missing the `ntdll.so` library and fails to create the wineprefix.
![image](https://user-images.githubusercontent.com/9479903/125733435-f782c0a7-18e3-4442-85fe-57ec08efe539.png)

The library is provided by the runner itself but for some reason cannot be founded, it will take me more time to fix. In the meantime I ask you to use the snap or the flatpak.

**Comment by rubberneck** [comment]
If this is something specific to 18.04 and it is going to be time consuming feel free to just close this as I need to upgrade that machine anyways.

**Comment by mirkobrombin** [comment]
I'm not closing for now because 18.04 is still supported by Canonical. For now I don't give it too much priority though, thanks for the information

**Comment by danihodovic** [comment]
I'm having a similar issue with 20.04.

```
(13:30:02) INFO Running an executable on the bottle…
wine: could not load ntdll.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/dani/.local/share/bottles/runners/caffe-6.23/bin/../lib/wine/x86_64-unix/ntdll.so)

```

**Comment by mirkobrombin** [comment]
> I'm having a similar issue with 20.04.
> 
> ```
> (13:30:02) INFO Running an executable on the bottle…
> wine: could not load ntdll.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/dani/.local/share/bottles/runners/caffe-6.23/bin/../lib/wine/x86_64-unix/ntdll.so)
> ```

This problem is related to Caffe, our new runner. It need GLIBC 2.32 and should be added as a dependency of the appimage. Btw the appimage is broken, we are investigating many problems. Please use the Flatpak if possible, the appimage fix can require a lot of time

**Comment by danihodovic** [comment]
Flatpak worked better. It might be a good idea to remove the AppImage altogether until it works properly.

**Comment by mirkobrombin** [comment]
> Flatpak worked better. It might be a good idea to remove the AppImage altogether until it works properly.

I thought I had it already removed, I think we will avoid publishing it until we understand what is causing the problem. I am also evaluating if I have the effort to invest in that too, I know that there is a guy who has expressed that he wants to try to investigate the problem, let's see if he can

**Comment by K-os** [comment]
> I thought I had it already removed, [...]

The AppImage is still available on the Github release page (https://github.com/bottlesdevs/Bottles/releases/tag/2021.12.28-treviso), where I downloaded it just to discover that it doesn't work on Ubuntu 20.04.

**Comment by mirkobrombin** [comment]
Closing until we find a new appimage maintainer. https://twitter.com/usebottles/status/1482656337918152708?s=21
