### ISSUE TITLE
[Request] hu locale

### ISSUE THREAD

**Issue by ovari** [bottlesdevs/Bottles#380]
Can you please merge the hu (Hungarian - magyar) locale and release an update with this locale for testing?

Thank you

**Comment by mirkobrombin** [comment]
Merged, you will find the unstable build for the AppImage shortly.

**Comment by ovari** [comment]
Note to self
https://github.com/bottlesdevs/Bottles/releases/tag/unstable
https://github.com/bottlesdevs/Bottles/releases/download/unstable/Bottles-devel-x86_64.AppImage

**Comment by ovari** [comment]
> If you are not up to date, Bottles has changed its release cycle, going from one release simply when it is ready, to two fixed appointments on the **14th** and **28th** of each month.

https://usebottles.com/blog/release-2021.7.14/

Does this mean that the Hungarian locale will be released for everyone on July 28th and automatically available for people who installed the [flatpak version from Flathub](https://flathub.org/apps/details/com.usebottles.bottles)?

Thank you

**Comment by mirkobrombin** [comment]
Yep

**Comment by ovari** [comment]
Can the `Easily manage wineprefix` please also be translatable in the Linux Mint 20.2 Cinnamon menu? Please see image below. Thank you

![kép](https://user-images.githubusercontent.com/17465872/126083659-e3f9273d-5f5e-4820-a8b8-a019dec7db35.png)

**Comment by mirkobrombin** [comment]
It should be translated, I'll check if any translations are missing

**Comment by ovari** [comment]
Sorry, it must be the flatpak version from Flathub, not the AppImage version.

**Comment by ovari** [comment]
The following strings didn't seem to work:
1. Gaming
2. An environment improved for Windows games.
3. Software
4. Custom

![kép](https://user-images.githubusercontent.com/17465872/126093021-90867b56-ce7f-4d02-ad38-f51ae91ca9cd.png)

There translations are showing in Weblate.

Thank you

**Comment by ovari** [comment]
1. `vaniglia` seems to be Italian for `vanilla`. Can this please be translatable?
2. Does 6.11 refer to the Wine 6.11 release at [WineHQ](https://www.winehq.org/)?
3. Currently Wine 6.12 is the latest version of Wine. Is there a way to select the newer version?

Thank you

![kép](https://user-images.githubusercontent.com/17465872/126093567-04e5d465-2843-4aa7-a32a-09f6bfa07f99.png)

**Comment by ovari** [comment]
1. Can the heading of the window please be updated from `Bottles névjegye` to `A Tárolók névjegye`?
2. Can `Bottles` please be translatable?
3. Clicking on the `Licenc` button alternates making the button green and not green. Doesn't seem to do anything else.
4. Clicking on the `Bezárás` (Close) button does not close the window.

Thank you

![kép](https://user-images.githubusercontent.com/17465872/126094090-247f8cae-ee29-4c28-b383-01a6ee690388.png)

**Comment by ovari** [comment]
Can the following please be translatable:
1. PID
2. Memory
3. CPU
4. Start
5. Time
6. Command

Thank you

![kép](https://user-images.githubusercontent.com/17465872/126094744-ad24b6ce-1b5e-4756-9055-464b49f5b748.png)

**Comment by ovari** [comment]
1. Can `No dxvk found, installing latest version ...` and the other messages that followed please be translatable?
![kép](https://user-images.githubusercontent.com/17465872/126095303-f72300bc-4c36-4d35-874c-dac26a113c63.png)
2. Can `A bottle named ... was created successfully` please be translatable?
![kép](https://user-images.githubusercontent.com/17465872/126095442-085165fe-9090-410a-984a-9f88bfa41714.png)

Thank you

**Comment by ovari** [comment]
1. Please allow `Gaming` to be translatable.
2. Is there a reason why there is a horizontal section at the bottom of the Bottles window?

Thank you

![kép](https://user-images.githubusercontent.com/17465872/126097140-a1884926-168e-41b5-bf14-5145fab51074.png)

**Comment by ovari** [comment]
Please allow the following to be translated:
1. Details & Utilities
2. Preferences
3. Dependencies
4. Programs
5. Essentials

Thank you

![kép](https://user-images.githubusercontent.com/17465872/126098654-a8f8adc8-aebe-4a5c-9ee3-807d73b50d82.png)

**Comment by mirkobrombin** [comment]
> 1. `vaniglia` seems to be Italian for `vanilla`. Can this please be translatable?
> 2. Does 6.11 refer to the Wine 6.11 release at [WineHQ](https://www.winehq.org/)?
> 3. Currently Wine 6.12 is the latest version of Wine. Is there a way to select the newer version? Seem to have found it as it is classified as `unstable`.

1. No. Vaniglia is the runner built and offered by Bottles by default and cannot be translated. The Italian name is a choice.
2. No. Refer to https://github.com/bottlesdevs/wine/releases
3. Vaniglia 6.12 will be built, tested and deployed in the next few days

> 1. Can the heading of the window please be updated from `Bottles névjegye` to `A Tárolók névjegye`?
> 2. Can `Bottles` please be translatable?
> 3. Clicking on the `Licenc` button alternates making the button green and not green. Doesn't seem to do anything else.
> 4. Clicking on the `Bezárás` (Close) button does not close the window.

1. No. Bottles is the product name and should not be translated. Only "bottles" intended as the user wine prefixes can be translated.
2. Same of point 1
3. In the original Bottles there is no such button, maybe it is provided by Mint o something else:
![image](https://user-images.githubusercontent.com/9479903/126109666-5c823092-9ba1-4833-b628-e1ca2aaf4136.png)
4. Same of point 3. You should use the close button provided by the window.

> Can the following please be translatable:
> 1. PID
> 2. Memory
> 3. CPU
> 4. Start
> 5. Time
> 6. Command

Yes, with the exception of PID and CPU. I will add the strings to Weblate

> 1. Can `No dxvk found, installing latest version ...` and the other messages that followed please be translatable?
> 2. Can `A bottle named ... was created successfully` please be translatable?

1. Should already be translated, strings are available on Weblate. I'll check it out as soon as possible.
2. Same of point 1

> 1. Please allow `Gaming` to be translatable.
> 2. Is there a reason why there is a horizontal section at the bottom of the Bottles window?

1. The environments have already been translated, if it doesn't load the translations then there is a problem:

![image](https://user-images.githubusercontent.com/9479903/126110138-ebcd01ab-4150-407d-8725-91940cf0a3f7.png)
(The `_(..)` function declare a new translation).

2. Sound like a Mint thing:
![image](https://user-images.githubusercontent.com/9479903/126110350-608418b8-4dbd-43d3-a20d-39f20d5faad1.png)

3. Should already be translated
![image](https://user-images.githubusercontent.com/9479903/126110579-39626df4-2838-4318-a3c9-3c9462a7ce04.png)

**Comment by ovari** [comment]
`PID` = `Folyamatazonosító` to distinguish it from, say, `Csőrendszer- és műszerezettségi diagram`
https://www.microsoft.com/en-us/language/Search?&searchTerm=PID&langID=382&Source=true&productid=0

`CPU` = `Processzor`; however, if it refers to a `CPU core`, then it is `Processzormag`
https://www.microsoft.com/en-us/language/Search?&searchTerm=CPU&langID=382&Source=true&productid=undefined

**Comment by ovari** [comment]
Is it possible then to please add `A ` before the heading `Bottles névjegye` for it to become `A Bottles névjegye`? Thank you

**Comment by ovari** [comment]
It doesn't happen with `Shortwave` on Linux Mint 20.2 Cinnamon
![image](https://user-images.githubusercontent.com/17465872/126126561-c0b1f8d0-fbd5-41f8-a8a8-0518c2dd8c69.png)

Can the `Bottles` on Linux Mint please be fixed?

Perhaps there are some code pointers from Shortwave that can be applied to `Bottles`?

Thank you

**Comment by mirkobrombin** [comment]
> `PID` = `Folyamatazonosító` to distinguish it from, say, `Csőrendszer- és műszerezettségi diagram`
> https://www.microsoft.com/en-us/language/Search?&searchTerm=PID&langID=382&Source=true&productid=0
> 
> `CPU` = `Processzor`; however, if it refers to a `CPU core`, then it is `Processzormag`
> https://www.microsoft.com/en-us/language/Search?&searchTerm=CPU&langID=382&Source=true&productid=undefined

PID and CPU are "international" technical terms that I prefer not to translate.

> It doesn't happen with [Shortwave](https://gitlab.gnome.org/World/Shortwave) on Linux Mint 20.2 Cinnamon
> 
> Can the `Bottles` on Linux Mint please be fixed?
> 
> Perhaps there are some code pointers from Shortwave that can be applied to `Bottles`?

I have 5 active virtual machines (Arch, Fedora Silverblue, Ubuntu 18.04, elementary os 6, elementary os 5). To solve the problem I would have to create another vm for linux mint and understand what changes compared to the other distributions. This may take some time, until I finish a long todolist of fixes already in progress.

**Comment by ovari** [comment]
Shoul `lnk path` be `link path`?
https://www.microsoft.com/en-us/language/Search?&searchTerm=link%20path&langID=382&Source=true&productid=undefined

Should `localy` be `locally`?

Thank you

**Comment by ovari** [comment]
Can the [Bottles Glossary](https://hosted.weblate.org/projects/bottles/glossary/hu/) be translated? Thank you
