### ISSUE TITLE
[Request] Feature to remove shortcut on desktop and start menu when i uninstall software or delete the bottle

### ISSUE THREAD

**Issue by vandpurnama** [bottlesdevs/Bottles#385]
The problem here actually if i uninstall a software bottle doesn't remove the apps shortcut on desktop or start menu... 
please add feature to remove shortcut if i uninstall the software or delete the bottle so shortcut automatically will be deleted

i also tried wine uninstaller but it doesn't delete the shortcut either i must delete the shortcut manually 

![gambar](https://user-images.githubusercontent.com/33601181/126133218-44969bd0-edb8-4428-b492-917e78e111f2.png)

**Comment by mirkobrombin** [comment]
This behavior is handled by Wine and we can't do anything about it in the current branch (Treviso). We will be able to check this in the next main release under development (Trento).

Related: 
- https://github.com/bottlesdevs/Bottles/issues/133
- https://github.com/bottlesdevs/Bottles/issues/115
- https://github.com/bottlesdevs/Bottles/issues/299#issuecomment-852774690

**Comment by mirkobrombin** [comment]
This is partially fixed with 2021.7.28 locking the winemenubuilder.exe on runner installation. So when wine tries to use the tool, it won't find it and no shortcut will be created. It may not be the ultimate solution but it is something.
