### ISSUE TITLE
[BUG] MESA-INTEL: warning: Haswell Vulkan support is incomplet

### ISSUE THREAD

**Issue by LinuxConfused** [bottlesdevs/Bottles#393]
**Describe the bug**
I'm struggling after migration from flatpac. I had installed app image recently when you notified the impending doom of flatpac. However, my program wouldn't run from the app image, so I continued flatpac version. Today the flatpac no longer worked. Regrettably, I uninstalled my program, thinking I would reinstall on the new bottles and it should work. Now my program, which had been successfully running on the flatpac version will not install in bottles. When I click on "Run Executable", nothing happens. I thought I migrated my files successfully, but maybe not? I don't know how to verify, or where exactly they should go.

I reinstalled the app image of the latest release and am trying to use it. Here's what it does when I open from the app image:
```bash
APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2
Gtk-Message: 20:47:49.970: Failed to load module "appmenu-gtk-module"
2021-07-23 20:47:51 INFO: Dxvk found: [dxvk-1.8.1]
2021-07-23 20:47:51 INFO: Vkd3d found: [vkd3d-v2.4]
2021-07-23 20:47:51 INFO: Runners found: [chardonnay-6.10]
2021-07-23 20:47:51 INFO: Bottles found: Amblyoplay
2021-07-23 20:47:51 INFO: Bottles Started!
2021-07-23 20:48:07 INFO: Setting Key: [sync] to [wine] for bottle: [Amblyoplay] …

(bottles:53585): Handy-CRITICAL **: 20:48:07.618: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed

When I attempt to run the windows executable for the Amblyoplay program, here is the result:
MESA-INTEL: warning: Haswell Vulkan support is incomplete
/lib/ld-linux.so.2: could not open
/lib/ld-linux.so.2: could not open
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

0090:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
```

I'm a linux noob (I guess that's obvious!) but hopefully this is the info you need to help me! Thanks so so much!

**Installation**
 - Method: Flatpak
 - Version: not provided

**Desktop (please complete the following information):**
 - OS: Pop! OS 
 - Version 21.04

**Comment by mirkobrombin** [comment]
Hi, I moved your comment to this issue as it was not related to the [topic].

Let me tell you two things before I get into your problem. When you need to report a problem, check if it has already been reported using the search bar, if it is not already present then open a new issue.  When you open a new issue, you can choose between [Bug Report](https://github.com/bottlesdevs/Bottles/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and [Feature request](https://github.com/bottlesdevs/Bottles/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), once chosen you will have to explain the problem following the instructions on the screen.

Remember that a detailed issue helps developers (of any project) to give you better support, avoiding them asking for more details or having to deal with the text of your issue to make it clear to other users looking for an answer to the same problem.

Let's ignore the AppImage and focus on the Flatpak (which is officially [supported again](https://github.com/flathub/com.usebottles.bottles/issues/90#issuecomment-872482952)). Now speaking of your problems with Bottles, I need some information:
- What version of Bottles do you have installed? (Bottles > Menu > About)
- What program are you trying to run?
- Please provide me the following output:
  - `echo "Native Bottles directory\n" && ls -l ~/.local/share/bottles/bottles`
  - `echo "Flatpak Bottles directory\n" && ls -l ~/.var/app/com.usebottles.bottles/data/bottles/bottles`

**Comment by LinuxConfused** [comment]
Thank you for your patience and moving this to the correct place.

I'm running Bottles 2021.7.14-treviso
Yesterday when Amblyoplay no longer opened, I uninstalled the previous flatpak of Bottles, then reinstalled the latest version. The program I'm trying to run is called Amblyoplay. I was running it as a Windows executable, but they have it available for iOS and Andriod as well. It's a software with basic gaming, for vision therapy. I ran it successfully on previous version of Bottles.

output from echo:
echo "Native Bottles directory\n" && ls -l ~/.local/share/bottles/bottles
Native Bottles directory\n
total 4
drwxrwxr-x 4 amber amber 4096 Jul 23 20:51 Amblyoplay

next output from echo:
echo "Flatpak Bottles directory\n" && ls -l ~/.var/app/com.usebottles.bottles/data/bottles/bottles
Flatpak Bottles directory\n
total 4
drwxrwxr-x 4 amber amber 4096 Jul 24 16:57 Amblyoplay

**Comment by mirkobrombin** [comment]
I think it's a runner's problem. Try in this way:
1. Install Chardonnay 6.10 from Bottles Preferences
2. Choose it in your bottle settings (your bottle > preferences > runner)
3. Then try starting the program

**Comment by LinuxConfused** [comment]
Chardonnay 6.10 was already installed, and selected for my bottle. I'm still not able to run my program.

**Comment by mirkobrombin** [comment]
I will try to run it in a bottle in the next few days. It is free software?

**Comment by LinuxConfused** [comment]
Thank you. It was for sure a glitch in my system.  When I looked into the runners further, I got error messages saying no space left in my root files. (After failed attempts to repair) I did a fresh install of my system, and then fresh install of flatpak Bottles. 
Now everything works perfectly, out of the box with no changes. My program is up and running again.
Thank you so much for your help!
