### ISSUE TITLE
[BUG] self.runner.get_running_processes() when splitting processes with | gets "index out of range"

### ISSUE THREAD

**Issue by MacsyMetropolia** [bottlesdevs/Bottles#396]
**Describe the bug**
The python task splitting bash command of running user processes to array crashes.

Length check only checks for >= 6 columns in `get_running_processes`, but the loop tries to get 7th index on the array. They are offset by 1.

**Installation**
 - Method: [AUR, so installing from source]
 - Version ["today?"]

**To Reproduce**
1. Install some runners
2. Close Bottles
3. Relaunch

**Expected behavior**
Initialization proceeds beyond get_running_processes.

**Fix**
Offsetting array indexes by -1 at bottles/runner.py:1224

**Screenshots**
![konsole screenshot](https://lh3.googleusercontent.com/60F8wcVaI-vQG7oLp-wzb5JkfjKx64N1etuSS93vdSXipguAiQon7462BVgOOGVFQIFUiDLb8IPWgf16nQ4QqSvwR7RV62hkZG1Dez86LnqZ9ciwJZmkYOpF-KFjivvHg57soSHbh8_pCt78ApNOKzcT0iigkjhNP6lenqdEPYF00S__gzsLNSjcOtOVBE6nstNmRoXyTcrNVpC0EGhYWmyQdy4sQRWG5V3wyAiKwc6337yYga5pvumlMr5OEsLLi3iQ9D7Uuc2VBth41ntE8JaoUq9OPa0o1kH4fPwJKbmyR1z12LyJ_BRdMJnWGue80iJdeW4kZacdnOrPyhA27UmGBCWGgA0cmEEVU8H68Dl4YFr-ub1Tm_EsYO2NYV6q8H_gf1N7D70ylNNYw_qXihQuOrbA-b6b-GaU7tjm4Hqt1GwlC4go-aQA2lQmlD_t5xACp9smYMkFEDaiCSpDNEDukzH0R7FUzX2u_I7MaO5YysvRg1lr000Mab_uMA278lB46w9ifNBlKiVskPug60f4r9QcyIg4jEnYGW98wKHjnrwfsWw4KzzeClBie1Rk-vBl4dIfBoXBIEMziKMp7VSU0gkK4ReNB6DDPUagDBRRpHx7UxHk9Zy_fYfLCHmE8K0DcZRJr2NQRCzDlxIOTsRLYCUL2cPj3KVg_ZnZ8550-kydqnv2N52OrjztJEPPIIGk9AZNR-z8JSjrfYv6Wxw=w985-h1083-no)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Version [Rolling]

**Comment by MacsyMetropolia** [comment]
I believe process_data array should be formed like this:

![fix](https://lh3.googleusercontent.com/pw/AM-JKLVlZbhnRNlVDRByyVeFwxeDXqwLVtdcOYL65RY39M8Zpfs4cQKlj7vgDv4PRh8vaiiaScUmoohABvKN26BMsEe0EKH9CRusxE2AgpE10AQt_ebPmK6d103j6C0AkB4cGp9F8ptSPuCv9kXjIGsqzTtj=w973-h545-no)

**Comment by mirkobrombin** [comment]
Hi, arrays in python also starts from 0 but in this case, the first result in list is an empty string:
![image](https://user-images.githubusercontent.com/9479903/126872888-6d248d50-4e8f-4d02-a318-89208453ce62.png)

**Comment by MacsyMetropolia** [comment]
> Hi, arrays in python also starts from 0 but in this case, the first result in list is an empty string:
> 
> ```python
> >>> command = "ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'"
> >>> pids = subprocess.check_output(['bash', '-c', command]).decode("utf-8")
> >>> for pid in pids.split("\n"):
> ...     process_data = pid.split("|")
> ...     print(process_data)
> ... 
> ['', '33086', '0.0', '0.2', '17:18', '00:00:00', 'C:\\windows\\system32\\winedevice.exe']
> ['', '33093', '0.1', '3.2', '17:18', '00:00:00', 'C:\\windows\\system32\\winedevice.exe']
> ['', '33179', '0.1', '1.7', '17:18', '00:00:00', 'C:\\windows\\system32\\winecfg.exe']
> ```

In that case the array length check should be >= 7, not 6, right?

**Comment by mirkobrombin** [comment]
> > Hi, arrays in python also starts from 0 but in this case, the first result in list is an empty string:
> > ```python
> > >>> command = "ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'"
> > >>> pids = subprocess.check_output(['bash', '-c', command]).decode("utf-8")
> > >>> for pid in pids.split("\n"):
> > ...     process_data = pid.split("|")
> > ...     print(process_data)
> > ... 
> > ['', '33086', '0.0', '0.2', '17:18', '00:00:00', 'C:\\windows\\system32\\winedevice.exe']
> > ['', '33093', '0.1', '3.2', '17:18', '00:00:00', 'C:\\windows\\system32\\winedevice.exe']
> > ['', '33179', '0.1', '1.7', '17:18', '00:00:00', 'C:\\windows\\system32\\winecfg.exe']
> > ```
> 
> In that case the array length check should be >= 7, not 6, right?

I honestly don't remember why I put 6 and not 7, I wrote that method many months ago :D
Regarding the `out of range` exception, maybe the output is different from mine. Can you open any wine program and try this in your terminal?

```bash
ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'
```

**Comment by MacsyMetropolia** [comment]
It produces 6 columns as you mentioned, but like you said, the parsing function in python produces 7:

```bash
 ✘ joona@linuxmain  ~  ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'
1313801|0.0|89.5|17:46|00:35:35|/usr/bin/wineserver
1313816|0.0|0.0|17:46|00:00:01|C:\windows\system32\winedevice.exe
1313824|0.0|0.3|17:46|00:00:07|C:\windows\system32\winedevice.exe
1318804|0.0|0.0|18:25|00:00:00|grep|--color=auto|--exclude-dir=.bzr|--exclude-dir=CVS|--exclude-dir=.git|--exclude-dir=.hg|--exclude-dir=.svn|--exclude-dir=.idea|--exclude-dir=.tox|wine
```

**Comment by mirkobrombin** [comment]
> It produces 6 columns as you mentioned, but like you said, the parsing function in python produces 7:
> 
> ```shell
>  ✘ joona@linuxmain  ~  ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'
> 1313801|0.0|89.5|17:46|00:35:35|/usr/bin/wineserver
> 1313816|0.0|0.0|17:46|00:00:01|C:\windows\system32\winedevice.exe
> 1313824|0.0|0.3|17:46|00:00:07|C:\windows\system32\winedevice.exe
> 1318804|0.0|0.0|18:25|00:00:00|grep|--color=auto|--exclude-dir=.bzr|--exclude-dir=CVS|--exclude-dir=.git|--exclude-dir=.hg|--exclude-dir=.svn|--exclude-dir=.idea|--exclude-dir=.tox|wine
> ```

from Ubuntu:
```bash
|33962|0.0|10.0|17:28|00:00:00|/home/mirko/.local/share/bottles/runners/Proton-6.12-GE-1/files/bin/wineserver
|33969|0.0|0.5|17:28|00:00:00|C:\windows\system32\winedevice.exe
|33976|0.1|6.0|17:28|00:00:00|C:\windows\system32\winedevice.exe
|34064|0.1|7.0|17:28|00:00:00|C:\windows\system32\winecfg.exe
```

so we have different output because I get 7 columns (notice the first `|`) and you 6. Despite the 6 or 7 columns, I should change this method because of inconsistent method across different distributions

**Comment by mirkobrombin** [comment]
Can you try this?
```bash
pgrep wine | xargs ps -f -p | tr -s ' ' '|'
```

should give you something like this:
```bash
❯ pgrep wine | xargs ps -f -p | tr -s ' ' '|'
UID|PID|PPID|C|STIME|TTY|STAT|TIME|CMD
mirko|34470|1568|1|17:32|?|Ss|0:00|/home/mirko/.local/share/bottles/runners/Proton-6.12-GE-1/files/bin/wineserver
mirko|34477|1568|0|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
mirko|34484|1568|1|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
mirko|34571|1568|0|17:32|pts/5|S+|0:00|C:\windows\system32\winecfg.exe
```

**Comment by MacsyMetropolia** [comment]
> > It produces 6 columns as you mentioned, but like you said, the parsing function in python produces 7:
> > ```shell
> >  ✘ joona@linuxmain  ~  ps -eo pid,pmem,pcpu,stime,time,cmd | grep wine | tr -s ' ' '|'
> > 1313801|0.0|89.5|17:46|00:35:35|/usr/bin/wineserver
> > 1313816|0.0|0.0|17:46|00:00:01|C:\windows\system32\winedevice.exe
> > 1313824|0.0|0.3|17:46|00:00:07|C:\windows\system32\winedevice.exe
> > 1318804|0.0|0.0|18:25|00:00:00|grep|--color=auto|--exclude-dir=.bzr|--exclude-dir=CVS|--exclude-dir=.git|--exclude-dir=.hg|--exclude-dir=.svn|--exclude-dir=.idea|--exclude-dir=.tox|wine
> > ```
> 
> from Ubuntu:
> 
> ```shell
> |33962|0.0|10.0|17:28|00:00:00|/home/mirko/.local/share/bottles/runners/Proton-6.12-GE-1/files/bin/wineserver
> |33969|0.0|0.5|17:28|00:00:00|C:\windows\system32\winedevice.exe
> |33976|0.1|6.0|17:28|00:00:00|C:\windows\system32\winedevice.exe
> |34064|0.1|7.0|17:28|00:00:00|C:\windows\system32\winecfg.exe
> ```
> 
> so we have different output because I get 7 columns (notice the first `|`) and you 6. Despite the 6 or 7 columns, I should change this method because of inconsistent method across different distributions

That... makes more sense. Maybe string-replace first "|” if it's the first symbol or something :smile:

**Comment by mirkobrombin** [comment]
> That... makes more sense. Maybe string-replace first "|” if it's the first symbol or something

This can be the way but I think it's better combining `pgrep` with `xargs` and `tr` if this give the same output across different distros

**Comment by mirkobrombin** [comment]
> Can you try this?
> 
> ```shell
> pgrep wine | xargs ps -f -p | tr -s ' ' '|'
> ```
> 
> should give you something like this:
> 
> ```shell
> ❯ pgrep wine | xargs ps -f -p | tr -s ' ' '|'
> UID|PID|PPID|C|STIME|TTY|STAT|TIME|CMD
> mirko|34470|1568|1|17:32|?|Ss|0:00|/home/mirko/.local/share/bottles/runners/Proton-6.12-GE-1/files/bin/wineserver
> mirko|34477|1568|0|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
> mirko|34484|1568|1|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
> mirko|34571|1568|0|17:32|pts/5|S+|0:00|C:\windows\system32\winecfg.exe
> ```

Let me know if this is working in the right way on your manjaro

**Comment by MacsyMetropolia** [comment]
> > Can you try this?
> > ```shell
> > pgrep wine | xargs ps -f -p | tr -s ' ' '|'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should give you something like this:
> > ```shell
> > ❯ pgrep wine | xargs ps -f -p | tr -s ' ' '|'
> > UID|PID|PPID|C|STIME|TTY|STAT|TIME|CMD
> > mirko|34470|1568|1|17:32|?|Ss|0:00|/home/mirko/.local/share/bottles/runners/Proton-6.12-GE-1/files/bin/wineserver
> > mirko|34477|1568|0|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
> > mirko|34484|1568|1|17:32|?|Sl|0:00|C:\windows\system32\winedevice.exe
> > mirko|34571|1568|0|17:32|pts/5|S+|0:00|C:\windows\system32\winecfg.exe
> > ```
> 
> Let me know if this is working in the right way on your manjaro

It does give something like that. I couldn't get proton runner working so I don't have that process. But that's unrelated. 

With sys-wine:

```bash
joona@linuxmain ~  pgrep wine | xargs ps -f -p | tr -s ' ' '|'
UID|PID|PPID|C|STIME|TTY|STAT|TIME|CMD
joona|1313801|1|91|17:46|?|Rs|51:04|/usr/bin/wineserver
joona|1313816|1|0|17:46|?|Sl|0:02|C:\windows\system32\winedevice.exe
joona|1313824|1|0|17:46|?|Sl|0:11|C:\windows\system32\winedevice.exe
```

**Comment by mirkobrombin** [comment]
Thanks, unfortunately pgrep does not provide enough details. I am preparing a temporary fix, as Bottles v4 will use `winedbg` to list the running processes. https://github.com/bottlesdevs/LibraryWine/blob/main/Bottles.LibraryWine/WineProcess.cs

Regarding Proton, open an issue if you can't get it to work and I'll try to help you there. Thanks for the report

**Comment by MacsyMetropolia** [comment]
> Thanks, unfortunately pgrep does not provide enough details. I am preparing a temporary fix, as Bottles v4 will use `winedbg` to list the running processes. https://github.com/bottlesdevs/LibraryWine/blob/main/Bottles.LibraryWine/WineProcess.cs
> 
> Regarding Proton, open an issue if you can't get it to work and I'll try to help you there. Thanks for the report

Pretty new to issuing, I guess you can close this with attached commit? Or should I close it?

**Comment by mirkobrombin** [comment]
> > Thanks, unfortunately pgrep does not provide enough details. I am preparing a temporary fix, as Bottles v4 will use `winedbg` to list the running processes. https://github.com/bottlesdevs/LibraryWine/blob/main/Bottles.LibraryWine/WineProcess.cs
> > Regarding Proton, open an issue if you can't get it to work and I'll try to help you there. Thanks for the report
> 
> Pretty new to issuing, I guess you can close this with attached commit? Or should I close it?

I will close by the commit, thanks
