### ISSUE TITLE
[BUG] Can't close window on initial download

### ISSUE THREAD

**Issue by n1trux** [bottlesdevs/Bottles#398]
In 2021.7.14-treviso, when you get the initial dialog to download the default runner, you can't hit X to close the window and there's no "cancel" button, so if something doesn't work there, you have to kill the app via the task manager.

**Comment by mirkobrombin** [comment]
Thanks for bringing this to my attention

**Comment by mirkobrombin** [comment]
Now bottles manage this exception.
