### ISSUE TITLE
[Request] Choose directory to put bottles in

### ISSUE THREAD

**Issue by n1trux** [bottlesdevs/Bottles#399]
I'd really like to be able to choose the folder(s) my bottles are created in. I like to install my games on another partition than my applications or home folder, because I like to use an unencrypted partition to have them start faster.

You can just symlink `~/.local/share/bottles/bottles/` or a subfolder to another location, but it'd be nice if you could do this in the UI.

**Comment by mirkobrombin** [comment]
This was supposed to be supported in Treviso but has been scheduled to Trento (the fourth version) due to several problems in the management of customized routes.

Ref https://github.com/bottlesdevs/libbottles/issues/1 and close.

**Comment by RealTehreal** [comment]
> I'd really like to be able to choose the folder(s) my bottles are created in. I like to install my games on another partition than my applications or home folder, because I like to use an unencrypted partition to have them start faster.
> 
> You can just symlink `~/.local/share/bottles/bottles/` or a subfolder to another location, but it'd be nice if you could do this in the UI.

Could you please add some more information on how you achieved to symlink the bottles folder out of the original directory? For me, the bottles are located at ~/.var/app/com.usebottles.bottles/data/bottles/bottles
When I tried to replace it with a symlink to a folder on another partition, bottles won't run anymore.
Thanks in advance!

**Comment by mirkobrombin** [comment]
> > I'd really like to be able to choose the folder(s) my bottles are created in. I like to install my games on another partition than my applications or home folder, because I like to use an unencrypted partition to have them start faster.
> > You can just symlink `~/.local/share/bottles/bottles/` or a subfolder to another location, but it'd be nice if you could do this in the UI.
> 
> Could you please add some more information on how you achieved to symlink the bottles folder out of the original directory? For me, the bottles are located at ~/.var/app/com.usebottles.bottles/data/bottles/bottles When I tried to replace it with a symlink to a folder on another partition, bottles won't run anymore. Thanks in advance!

If you are using the Flatpak, you also need to add the relative permission to that folder (e.g. using Flatseal).

**Comment by RealTehreal** [comment]
It worked. Thank you!
