### ISSUE TITLE
[Request] 32 bit wine prefix support

### ISSUE THREAD

**Issue by senolfeldmann** [bottlesdevs/Bottles#400]
Many 32 applications (especially older ones) do not run properly in 64 bit wine prefixes. Even the [official Wine FAQ](https://wiki.winehq.org/FAQ#How_do_I_create_a_32_bit_wineprefix_on_a_64_bit_system.3F) states this:
> At present there are some significant bugs that prevent many 32 bit applications from working in a 64 bit wineprefix.

In my case, applications which are dependent on .Net 2 do not work properly most of the time, as .Net 2 is only installable on 32-bit systems/wine prefixes. Bottles is an amazing tool, it would be even more amazing if people who are dependent on 32-bit prefixes could use Bottles, too.

It would be great if one could choose if a bottle is a 32 or 64 bit one upon creation. E.g. Crossover has this feature.

**Comment by mirkobrombin** [comment]
This is something that we supported in v1 and that has been lost in v2. I've always had doubts about it. I know that many have (had) this problem, in my experience I have never had the need to create 32bit prefixes to start 32bit programs that do not work in 64bit prefixes.

I'm not against re-integrating this functionality but I want to make sure it's still the case. I will try for example to install dotnet2 and test its operation.

**Comment by senolfeldmann** [comment]
Ok, that sound great, thank you for being open for this feature. Bear in mind that x64 dotnet2 works on x64 prefixes, but I especially meant the x86 version. I can find more programs which need a 32-bit prefix if you want.

**Comment by mirkobrombin** [comment]
Yes thank you I would very much appreciate a list of software that requires a 32bit prefix to test on

**Comment by Torbuntu** [comment]
Was just trying to install GOG Galaxy Client 2.0 and the failures led me to find the [winehq page here](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38672&iTestingId=108575) which mentions using a win32 prefix.

EA Origin also needs a win32 prefix for many games to work.

Hope this information helps.

**Comment by mirkobrombin** [comment]
> Was just trying to install GOG Galaxy Client 2.0 and the failures led me to find the [winehq page here](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38672&iTestingId=108575) which mentions using a win32 prefix.
> 
> EA Origin also needs a win32 prefix for many games to work.
> 
> Hope this information helps.

This helps

**Comment by mirkobrombin** [comment]
The latest unstable (currently being built by GitHub) offers this feature. For the moment only with Custom environment, let me know if there are any problems.

**Comment by Torbuntu** [comment]
Is it possible to push the unstable release to flathub-beta?

**Comment by Torbuntu** [comment]
Thank you much :)

**Comment by ata-star** [comment]
how do i use the 32 bit prefix

**Comment by mirkobrombin** [comment]
> how do i use the 32 bit prefix

Wait for the next stable. If you are in beta channel, just create a new custom bottle and select 32bit

**Comment by SilverGreen93** [comment]
> > how do i use the 32 bit prefix
> 
> Wait for the next stable. If you are in beta channel, just create a new custom bottle and select 32bit

So how is this done? I cannot find any option to enable win32 prefix.

**Comment by Astolfo2001** [comment]
choose custom environment and change the architecture to 32-bit
