### ISSUE TITLE
[BUG] Game can be opened from explorer but failed when open via Bottles

### ISSUE THREAD

**Issue by goingtosleep** [bottlesdevs/Bottles#407]
**Describe the bug**
After I installed "Volley Balley" game and tick `Open after installation`, the game runs fine. But when I open the game from Bottles programs menu or from the context menu (Open with Bottles), the game fails to open, announce `Cannot open file bmst.bin`. The file `bmst.bin` is a file in the game's folder.

However, when I open the exe file from explorer (Bottles > Command Line > type in explorer), the game opens just fine. In previous version (2021.7.14-treviso), I didn't have this problem.

**Installation**
 - Method: Flatpak (I really want to use AppImage but confliction prevent me to install necessary i386 packages).
 - Version: 2021.7.28-treviso

**To Reproduce**
1. Install the game with Bottles (choose whatever the environment). The game can be downloaded [here](https://drive.google.com/file/d/1qKQBo1w_Y0GgnUrbH1Pcqg_i_pn-s3fY) (mini 3MB game).

2. Go to Programs tab, open `Volley Balley` program (or open the exe with Bottles).

3. Cannot open, a dialog appears and show `Cannot open file bmst.bin`.

**Expected behavior**
The game open normally in Bottles.

**Screenshots**
![](https://i.imgur.com/Oi4eLlm.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon (based on Ubuntu 20.04)
 - Version: 5.22.4

**Comment by mirkobrombin** [comment]
There is no official way to detect installed programs in Wine. Bottles try to list them looking for link files in the Start menu. So we have no control on this behavior.

When you can do is add the .exe to the program list, using the add button in the programs section (from the sidebar).

**Comment by goingtosleep** [comment]
I think Bottles detected the correct .exe file, but somehow cannot open it correctly.
I tried your suggestion, add `vball.exe` to Bottles but the result is still the same:
![](https://i.imgur.com/TQmZF42.png)

**Comment by mirkobrombin** [comment]
I think I have identified the problem. I need to do some testing but it will be fixed for the 2021.8.14 release.

**Comment by mirkobrombin** [comment]
I'm preparing an off-calendar release that will be rolling out on Flatpak and Snapcraft within the next few hours.

**Comment by goingtosleep** [comment]
Confirm that the bug no longer exists on `2021.7.28-treviso-2` (AppImage). Thanks a lot!
