### ISSUE TITLE
Use $XDG_DATA_HOME for bottles

### ISSUE THREAD

**Issue by erazemk** [bottlesdevs/Bottles#41]
Currently Bottles puts its wineprefixes in `~/.Bottles`, which works fine, but "pollutes" the user's home directory. A possibly more appropriate place for the directory would be `$XDG_DATA_HOME` (following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)), which is usually `~/.local/share`.

Using that format the Bottles directory would be moved to `~/.local/share/Bottles`.

**Comment by mirkobrombin** [comment]
This is a fix that I have already considered but that I will apply in the v2, currently under development in the "develop" branch of this repository. I prefer to only apply bugfixes to this version for now.

Thanks anyway, I'll use this issue as a memo for v2.
