### ISSUE TITLE
[BUG] Bottles runs in Xwayland mode instead of running in wayland mode in the Flathub version

### ISSUE THREAD

**Issue by GreatGodvin** [bottlesdevs/Bottles#419]
**Describe the bug**
Bottles when installed from Flathub runs in Xwayland mode instead of running in wayland mode.

**Installation**
 - Method: Flathub
 - Version: 2021.7.28-treviso

**To Reproduce**
1. Boot your system in wayland mode
1. Run ```flatpak run com.usebottles.bottles``` to start Bottles
2. Run ```xprop``` in another terminal
3. Notice that the cursor changes to a plus sign when hovering over Bottles window indicating that Bottles is running in Xwayland mode.

**Expected behavior**
Bottles runs in native wayland mode and the wine applications run in Xwayland mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: n/a

**Additional context**
Bottles can be run in wayland mode by running ```flatpak run --socket=wayland com.usebottles.bottles``` But then wine applications will fail to start with the following error:
```
00c0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00c0:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

This can be fixed by passing the environment variable DISPLAY=:0 to wine applications. In this way Bottles will run in wayland mode and the wine applications will run in Xwayland mode. I suggest adding ```--socket=wayland``` to finish-args in ```com.usebottles.bottles.json``` file and adding the environment variable ```DISPLAY=:0``` to wine applications if Bottles was run in wayland mode.

**Comment by mirkobrombin** [comment]
This requires some work on the code. I try to schedule it for the next release, thanks for reporting

**Comment by BobyMCbobs** [comment]
I'm running Wayland and have the latest Flatpak version installed.
For me, when the sockets x11, wayland, and fallback-x11 are all set this issue occurs.
When I only have socket=x11 set, it works fine.

**Comment by mirkobrombin** [comment]
> I'm running Wayland and have the latest Flatpak version installed.
> For me, when the sockets x11, wayland, and fallback-x11 are all set this issue occurs.
> When I only have socket=x11 set, it works fine.

Because with only that flag it run the entire Bottles under xorg. So is this bug also confirmed in 2021.8.28?

**Comment by jjardon** [comment]
This seems same issue as https://github.com/flathub/com.usebottles.bottles/issues/141

**Comment by mirkobrombin** [comment]
I set up a VM where I can use wayland and work on a fix
