### ISSUE TITLE
[BUG] Opening a .exe does nothing

### ISSUE THREAD

**Issue by sonnyp** [bottlesdevs/Bottles#432]
Bottles is fantastic thank you!

Possibly related #132 

**Describe the bug**

Opening an .exe with Bottles does nothing.

**Installation**
 - Method: flathub
 - Version 2021.7.28-treviso
 
**To Reproduce**
1. Download https://www.escapemotions.com/products/rebelle/download/Rebelle_4_Demo_64bit_v4.1.2_Windows.exe
2. Open with Bottles (suggested default action since that's my only .exe app handler)

**Expected behavior**

Someting happens, create a new bottle for the exe?

**Actual behavior**

(This is probably missing from the issue template)

Bottles opens, the progress cursor shows for a few seconds and nothing happens.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Comment by mirkobrombin** [comment]
Hi, thanks for being so explanatory. I think it's a regression in the CLI, can you try to start it from the terminal?

```bash
flatpak run com.usebottles.bottles -e path.exe
```

**Comment by sonnyp** [comment]
Same.

```
sonny@porygon ~> flatpak run com.usebottles.bottles -e Downloads/Rebelle_4_Demo_64bit_v4.1.2_Windows.exe
Gtk-Message: 12:21:36.672: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:21:36.672: Failed to load module "pk-gtk-module"
2021-08-05 12:21:36 INFO: Dxvk found: [dxvk-1.9.1]
2021-08-05 12:21:36 INFO: Vkd3d found: [vkd3d-v2.4]
2021-08-05 12:21:36 INFO: Runners found: [vaniglia-6.13]
2021-08-05 12:21:37 INFO: Bottles Started!
TypeError: Must be number, not NoneType
```

But this time I can see what I imagine the UI to create a Bottle appear and then replaced immediately with the welcome screen.

I noticed a couple of related issues around flatpak permissions and the .desktop file, I'll send a PR once opening from the CLI works.

**Comment by sonnyp** [comment]
Actually the TypeError and the UI switch happens without an argument as well

```
sonny@porygon ~> flatpak run com.usebottles.bottles
Gtk-Message: 12:28:46.668: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:28:46.668: Failed to load module "pk-gtk-module"
2021-08-05 12:28:46 INFO: Dxvk found: [dxvk-1.9.1]
2021-08-05 12:28:46 INFO: Vkd3d found: [vkd3d-v2.4]
2021-08-05 12:28:46 INFO: Runners found: [vaniglia-6.13]
2021-08-05 12:28:47 INFO: Bottles Started!
TypeError: Must be number, not NoneType
```

I'll do some investigation around the file opening issue.

**Comment by mirkobrombin** [comment]
> Actually the TypeError and the UI switch happens without an argument as well
> 
> ```
> sonny@porygon ~> flatpak run com.usebottles.bottles
> Gtk-Message: 12:28:46.668: Failed to load module "canberra-gtk-module"
> Gtk-Message: 12:28:46.668: Failed to load module "pk-gtk-module"
> 2021-08-05 12:28:46 INFO: Dxvk found: [dxvk-1.9.1]
> 2021-08-05 12:28:46 INFO: Vkd3d found: [vkd3d-v2.4]
> 2021-08-05 12:28:46 INFO: Runners found: [vaniglia-6.13]
> 2021-08-05 12:28:47 INFO: Bottles Started!
> TypeError: Must be number, not NoneType
> ```
> 
> I'll do some investigation around the file opening issue.

The `TypeError` is under investigation and pop up also on normal Bottles start up https://github.com/orgs/bottlesdevs/projects/3#card-66282918



> Same.
> 
> ```
> sonny@porygon ~> flatpak run com.usebottles.bottles -e Downloads/Rebelle_4_Demo_64bit_v4.1.2_Windows.exe
> Gtk-Message: 12:21:36.672: Failed to load module "canberra-gtk-module"
> Gtk-Message: 12:21:36.672: Failed to load module "pk-gtk-module"
> 2021-08-05 12:21:36 INFO: Dxvk found: [dxvk-1.9.1]
> 2021-08-05 12:21:36 INFO: Vkd3d found: [vkd3d-v2.4]
> 2021-08-05 12:21:36 INFO: Runners found: [vaniglia-6.13]
> 2021-08-05 12:21:37 INFO: Bottles Started!
> TypeError: Must be number, not NoneType
> ```
> 
> But this time I can see what I imagine the UI to create a Bottle appear and then replaced immediately with the welcome screen.

I will also do local tests to identify the problem.

> I noticed a couple of related issues around flatpak permissions and the .desktop file, I'll send a PR once opening from the CLI works.

Thanks 🙏

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/128337963-cb96b256-98a2-41c1-bd70-e57a69f18b4a.png)
It appears not to be present in the other packages

**Comment by mirkobrombin** [comment]
I have read your issue better and we need to clarify a fact before: Bottles allows you to start an executable in an existing bottle, at the moment it is not possible to pick an executable, create a new bottle then run the first selected executable. It will definitely be a feature of Trento (v4), currently under development.

The problem that needs to be fixed is the fact that starting the executable in the selected bottle is not working (at least in my tests).

**Comment by sonnyp** [comment]
> at the moment it is not possible to pick an executable, create a new bottle then run the first selected executable inside the new bottle

Ha ok that explains.

> It will definitely be a feature of Trento (v4), currently under development.

Great, since they are no way for Bottles to dynamically change its desktop behavior regarding advertising its ability to open files I think the current situation is pretty confusing. 

> The problem that needs to be fixed is the fact that starting the executable in the selected bottle is not working (at least in my tests).

I can help testing. Should I reproduce like so:

1. Create a bottle
2. Close Bottles
3. Open an exe with Bottles
4. Pick the previously created bottle

?

---

The good news is that we can proceed with https://github.com/bottlesdevs/Bottles/pull/436 (give me a moment to test though). 
The bad news is that this ticket is getting quite meta/complicated.

Feel free to close it in favor of more descriptive tickets. I'm also happy to create one for something like "Create a bottle if none exists when opening a file".

**Comment by mirkobrombin** [comment]
> > at the moment it is not possible to pick an executable, create a new bottle then run the first selected executable inside the new bottle
> 
> Ha ok that explains.
> 
> > It will definitely be a feature of Trento (v4), currently under development.
> 
> Great; I think the current situation is pretty confusing for first-time/new users.
> 
> > The problem that needs to be fixed is the fact that starting the executable in the selected bottle is not working (at least in my tests).
> 
> I can help testing. Should I reproduce like so:
> 
> 1. Create a bottle
> 2. Close Bottles
> 3. Open an exe with Bottles
> 4. Pick the previously created bottle
> 
> ?
> 
> EDIT: works for me - maybe #436 is what you are facing
> 
> The good news is that we can proceed with #436 (give me a moment to test though).
> The bad news is that this ticket is getting quite meta/complicated.
> 
> Feel free to close it in favor of more descriptive tickets. I'm also happy to create one for something like "Create a bottle if none exists when opening a file".

Thanks a lot, now I look at the PR.

Yes this issue is mixing problems, I close it for now and feel free to open another one. Also let me know in the PR as soon as I can merge it. Thanks again, all your contributions is appreciated :D
