### ISSUE TITLE
[Request] Offer to create a bottle when opening a file

### ISSUE THREAD

**Issue by sonnyp** [bottlesdevs/Bottles#437]
Follow up https://github.com/bottlesdevs/Bottles/issues/432

When opening a file, Bottles should offer the option to create a new bottle for it.

That way, even if they are no bottles, the user isn't left with the welcome screen and no way to proceed.

My use case was installing Bottles, download a `.exe`, choosing 'Open with Bottles', going through first time setup and I was left with an empty screen. Not a great first time user experience.

Same problem on a second try but without the first time setup.

https://github.com/bottlesdevs/Bottles/issues/432

**Comment by mirkobrombin** [comment]
Planned for Trento but should be done in 2021.8.28
