### ISSUE TITLE
[Crash report] Random crash when opening up.

### ISSUE THREAD

**Issue by LifeWatcher123** [bottlesdevs/Bottles#438]
I really don't have anything to go off of. it just randomly crashed.

This crash report was generated by Bottles.

**Details**
* **package**: Flatpak

**Log**
```python3
HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /lutris/vkd3d/releases/download/v2.4/vkd3d-v2.4.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f85228aedf0>: Failed to establish a new connection: [Errno 110] Connection timed out'))  File "/app/share/bottles/bottles/utils.py", line 235, in target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/runner.py", line 239, in async_install_component
    download = self.download_component(component_type,

  File "/app/share/bottles/bottles/runner.py", line 190, in download_component
    download_url = requests.get(download_url, allow_redirects=True).url

  File "/app/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)

  File "/app/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)

```

**Comment by mirkobrombin** [comment]
It seems to be hitting some limits in reaching the component repository. Do you have a VPN configured or some particular network configuration?

**Comment by LifeWatcher123** [comment]
I don't have anything I myself have configured, but my internet connection does have this weird behavior where it won't connect to a website the first time, in which I need to reload the connection for it to connect. Maybe that's what caused it.

**Comment by mirkobrombin** [comment]
> I don't have anything I myself have configured, but my internet connection does have this weird behavior where it won't connect to a website the first time, in which I need to reload the connection for it to connect. Maybe that's what caused it.

It could be. I handled the exception but unfortunately there is nothing else I can do. In Bottles V4 this should be fixed by the new download manager. Let me know if you need anything else.
