### ISSUE TITLE
Dependency manager 

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#44]
In v2 we have chosen to adopt our dependency system instead of the usual Winetricks.

## What are dependencies?
Dependencies on Bottles are like package dependencies on almost all Linux distributions. Software may require dependencies in order to run and these can be downloaded and installed manually or via our dependency manager who will take care of everything (because each dependency can depend on other dependencies).

## Why not Winetricks?
We want to offer a centralized dependency management system. We want to be able to trace those installed in the bottle configuration file to be able to remove them or simply share the bottle with all dependencies listed.

Also, with an internal system it will be easier to install dependencies when an Environment is chosen.For example the Software environment requires vcrun, corefonts and several others. With our system we can install the dependencies at the bottle creation, without exiting the software or using external ones.

**Extensibility**. Using external repositories for dependencies and providing these with a manifest containing instructions and dependencies, it will be easier to add new dependencies to Bottles and extend support for new software.

Finally, Winetricks is external software and clashes with our UI 😏.

## A community driven repository
Our [repository](https://github.com/bottlesdevs/dependencies) will be community driven. This mean that other users can open Pull Requests to provide new dependency support to Bottles!

Online database: https://usebottles.com/database/dependencies

**Comment by mirkobrombin** [comment]
![Screenshot from 2020-12-05 22-48-30](https://user-images.githubusercontent.com/9479903/101266074-1851fa80-374c-11eb-8bc1-d2eda7e37564.png)

**Comment by mirkobrombin** [comment]
The dependency database can also be browsed from the official website: https://usebottles.com/database/dependencies

**Comment by mirkobrombin** [comment]
![Screenshot from 2021-01-02 14-01-12](https://user-images.githubusercontent.com/9479903/103457857-02ac0280-4d03-11eb-8ccd-1b816321e3a5.png)

**Comment by Byrkoet** [comment]
None of the dependencies seem to be downloadable, after clicking the download icon, the button greys out. (Ubuntu x64 + Gnome)

**Comment by mirkobrombin** [comment]
> None of the dependencies seem to be downloadable, after clicking the download icon, the button greys out. (Bottles 2.1.0.3 Ubuntu x64 + Gnome). The manifest shows up correctly, but after clicking the download icon, opening the manifest shows an empty popup. The url in the manifest isn't broken, as I tried it in a browser.
> ![Screenshot from 2021-01-20 14-05-22](https://user-images.githubusercontent.com/1343700/105178624-91ed4e80-5b28-11eb-89eb-e11434d5e34e.png)

Should be fixed in 2.1.0.4

**Comment by Byrkoet** [comment]
Downloading dependencies works fine now, although while installing core fonts, an error shows for low disk space, while there is 6GiB left for the bottle. (btw, after installing fonts "windows/fonts" dir is empty?)
![Screenshot from 2021-01-21 00-30-25](https://user-images.githubusercontent.com/1343700/105253482-df48da80-5b7f-11eb-9633-84d04d92c272.png)

**Comment by mirkobrombin** [comment]
> Downloading dependencies works fine now, although while installing core fonts, an error shows for low disk space, while there is 6GiB left for the bottle. (btw, after installing fonts "windows/fonts" dir is empty?)
> ![Screenshot from 2021-01-21 00-30-25](https://user-images.githubusercontent.com/1343700/105253482-df48da80-5b7f-11eb-9633-84d04d92c272.png)
> (Bottles 2.1.0.3 "Gaming environment" Ubuntu x64 + Gnome)

Please open a bug report for this, following the Bug template.

**Comment by ryahpalma** [comment]
Not working here too. I'm not able to install dependencies, .NET Framework can't install.

**Comment by mirkobrombin** [comment]
> Not working here too. I'm not able to install dependencies, .NET Framework can't install.

Please open a bug report for this, following the Bug template.

**Comment by mirkobrombin** [comment]
I'm going to close.this issue as dependency manager is already implemented. Please Open New Issues for bug reporting.
