### ISSUE TITLE
[BUG] The use of color is confusing

### ISSUE THREAD

**Issue by sonnyp** [bottlesdevs/Bottles#443]
First of all, I really like the UI refresh, kudos to the designers.

I have an issue with the use of colors for Gaming/Software/Custom

This blue is Adwaita/GNOME color for primary actions
This red is Adwaita/GNOME color for destruction actions
This grey is Adwaita/GNOME colour for insensitive (disabled) actions

IMHO it's very confusing

![Screenshot from 2021-08-07 16-06-49](https://user-images.githubusercontent.com/19673/128602965-0dc59e82-26a2-4c34-82cf-098082ca120f.png)

Regardless of the colors being used, it's also unusual for GNOME applications to make use of such strong color accents.

I think the symbolic icons for each category is enough and I don't really see the need for the colors. They don't appear to be re-used (for this purpose) anywhere else.

If you agree I'm happy to send a PR to give a try or to any other proposal.

**Comment by sonnyp** [comment]
It's specially confusing because the colors are used for different purposes there

![Screenshot from 2021-08-07 16-14-53](https://user-images.githubusercontent.com/19673/128603178-ecf17b12-218f-43d9-9ab3-abf3ec1aec22.png)

**Comment by mirkobrombin** [comment]
I've never noticed it. It actually makes sense.

**Comment by alvarlagerlof** [comment]
Yeah you've got a point for sure. We should change that. I'd be for neural colors for environment types.
