### ISSUE TITLE
Bring the team together

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#445]
I would like to create an area where we can discuss without the limitations of the Issue or the risk to go off topic.

@jannuary @alvarlagerlof @sonnyp  @ZekeSmith @pietrodicaprio which platform do you prefer? Matrix, Discord, Telegram, Gitter.. we already have a Matrix chat for design related discussions but we can use whatever you want.

This doesn't have to be closed to us, I like the idea that others can join and use this as a starting point to contribute. Also, I'm not asking for attendance or anything similar, simply create a common meeting place.

**Comment by alvarlagerlof** [comment]
I prefer Matrix or Discord

**Comment by mirkobrombin** [comment]
> I prefer Matrix or Discord

I'm also already using Discord for other projects

**Comment by sonnyp** [comment]
Personally, I don't have Discord, I'm on matrix kindof, the GNOME community uses Matrix as well.

**Comment by jannuary** [comment]
i don't have a particular preference, either matrix, discord or telegram is fine

**Comment by mirkobrombin** [comment]
#EnterTheMatrix

**Comment by ZekeSmith** [comment]
I agree on matrix.

**Comment by mirkobrombin** [comment]
I created the space on the matrix and invited everyone.

**Comment by ZekeSmith** [comment]
Spaces is a beta feature and not all matrix clients support it. I would reccomend creating a room instead and once spaces is supported on most clients you can add the existing room.

**Comment by mirkobrombin** [comment]
> Spaces is a beta feature and not all matrix clients support it. I would reccomend creating a room instead and once spaces is supported on most clients you can add the existing room.

Rooms in space should also be reachable outside of space. Am I wrong?

**Comment by ZekeSmith** [comment]
Yes that is correct but it might cause issues inviting people to it as a space.

**Comment by mirkobrombin** [comment]
https://matrix.to/#/#usebottles-development:matrix.org
