### ISSUE TITLE
[BUG] Blank window when offline.

### ISSUE THREAD

**Issue by ZekeSmith** [bottlesdevs/Bottles#449]
Bottles launches as a invisible window if the internet is not connected or reachable. This completely removes the ability to use bottles offline.

![IMG_20210809_100911](https://user-images.githubusercontent.com/81902668/128649838-ccf0819b-5b07-41e5-ae13-2b983ca8e994.jpg)

Tested system:
Fedora 34 Wayland

**Comment by ZekeSmith** [comment]
After leaving it for about 20mins it launched but the window doesnt have any of my bottles and if I click the plus button it wont create one.

**Comment by mirkobrombin** [comment]
I've tested the latest Appimage, Flatpak and meson build in offline mode and just works. I'm doing tests on xorg because wayland is disabled by default using nvidia proprietary drivers. So I cannot full test this

**Comment by mirkobrombin** [comment]
Although now Bottles handle this exception, issues like this can take benefits from #439
