### ISSUE TITLE
[Request] Launch options prefix / suffix / syntax

### ISSUE THREAD

**Issue by n1trux** [bottlesdevs/Bottles#451]
In Steam, you can use `%command%` to specify a prefix/suffix for launching applications.

So if you like to run `hl2.exe -dx9` you can either input `-dx9` or `%command% -dx9`. This allows you to prepend launch options, too, so you can launch the game with a wrapper. There's no official documentation on this (Volvo pls fix) but a bit of discussion [on Steam's Linux github](https://github.com/ValveSoftware/steam-for-linux/issues/4544).

If you'd like to use [libstrangle](https://gitlab.com/torkel104/libstrangle) to limit a game's FPS in Steam, you could use it by entering `strangle 60 %command% -dx9`.

I would like this to be possible (and visible in the UI) for Bottles, too. To avoid confusion with familiarity, I propose that we'd use the same method Steam uses and replace `%command%` with the game's executable (or rather: with bottles' wrapper and the executable).

Alternatively you could use the command line to use a program to then run bottles which then runs an application, but that's not convenient and may confuse users who are less technical.

**Comment by mirkobrombin** [comment]
This may be easy to implement. I'm currently testing on libwine integration in Bottles and there is an task that should help to achieve what you need: https://github.com/bottlesdevs/libwine/issues/3 (extracted from https://github.com/bottlesdevs/libwine/issues/2)

**Comment by mirkobrombin** [comment]
This is now available with the latest unstable build, just using the `%command%` placeholder in the arguments dialog.

![image](https://user-images.githubusercontent.com/9479903/129940591-b8d1d4cf-7774-4310-9b25-f0ade07ec40d.png)
