### ISSUE TITLE
add the ability to install gdiplus (like with winetricks)]

### ISSUE THREAD

**Issue by pyrotek45** [bottlesdevs/Bottles#452]
**Is your feature request related to a problem? Please describe.**
some vst plugins require gdiplus to work properly.

**Describe the solution you'd like**
to have the ability to install gdiplus (like in winetricks) for the flatpak bottles

**Describe alternatives you've considered**
use wine with winetricks (but for distros like silverblue, this is a bad solution, i would like the flatpak version to have gdiplus in it)

**Comment by mirkobrombin** [comment]
Moved to the right repository.
