### ISSUE TITLE
Use AdwComboRow

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#454]
Currently, we are using GtkComboBox-es inside of lists, which, and I quote, is "old and terrible". Libhandy has a specific widget for list rows with combo boxes - [HdyComboRow](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1.2/HdyComboRow.html).

**Comment by mirkobrombin** [comment]
It was not available in glade on Ubuntu 20.04 last time and it is weird because was introduced on first releases of libhandy.

OT: we should take care of other packages than flatpak, because libhandy may be out of date in some distros.

**Comment by mirkobrombin** [comment]
I think this issue can be closed in favor of https://github.com/bottlesdevs/Bottles/issues/610 so replacing libhandy with libadwaita.

**Comment by jannuary** [comment]
This still applies.

**Comment by TheEvilSkeleton** [comment]
Reopening as requested by @jannuary.
