### ISSUE TITLE
[BUG] Bottles doesn't show previously created bottles on Arch

### ISSUE THREAD

**Issue by windowsagent** [bottlesdevs/Bottles#455]
After creating a bottle, and relaunching bottles, bottles doesn't show the previously added bottle. It sometimes shows all the previously created bottles after creating a new bottle, and after a restart everything's empty again.

 - Meson build (through AUR)
 - 2021.7.28-1

1. Launch bottles, create a new bottle.
2. Close bottles, then reopen it.
3. Recently created bottle doesn't appear.

Bottles should display previously created bottles.

 - OS: Arch
 - Version: (kernel) 5.13.9-arch1-1 (all packages are up to date)

**Additional context**
Sometimes creating a new bottle temporarily fixes the problem (bottles displays previously created bottles), but the issue appears again after relaunching bottles.

**Comment by mirkobrombin** [comment]
Try starting bottles from the command line to catch logs. Also check for your bottles in ~/.local/share/bottles/bottles

**Comment by windowsagent** [comment]
![Screenshot_2021-08-10_19-09-29](https://user-images.githubusercontent.com/52929255/128950475-fbf5b964-1453-4c92-b842-9231802f11d0.png)
I can confirm the bottles are present, as those are the two that were missing.
Log shows this error:

Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 125, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/main.py", line 166, in do_activate
    win = BottlesWindow(application=self,
  File "/usr/share/bottles/bottles/window.py", line 102, in __init__
    self.runner = BottlesRunner(self)
  File "/usr/share/bottles/bottles/runner.py", line 82, in __init__
    self.clear_temp()
  File "/usr/share/bottles/bottles/runner.py", line 103, in clear_temp
    os.remove(os.path.join(BottlesPaths.temp, f))
IsADirectoryError: [Errno 21] Is a directory: '/home/windowsagent/.local/share/bottles/temp/arial32'

**Comment by mirkobrombin** [comment]
Try removing all from ~/.local/share/bottles/temp

**Comment by windowsagent** [comment]
Still some errors, and it doesn't show up the bottles.

Gtk-Message: 13:20:05.558: Failed to load module "colorreload-gtk-module"
Gtk-Message: 13:20:05.558: Failed to load module "window-decorations-gtk-module"
2021-08-11 13:20:05 INFO: Dxvk found: [dxvk-1.9.1]
2021-08-11 13:20:05 INFO: Vkd3d found: [vkd3d-v2.4]
2021-08-11 13:20:05 INFO: Runners found: [sys-wine-6.14
|vaniglia-6.13|vaniglia-6.13-unstable]
2021-08-11 13:20:06 INFO: Bottles found: FL-Studio|LameXP
2021-08-11 13:20:06 INFO: Temp path cleaned successfully!
2021-08-11 13:20:06 INFO: Bottles Started!
TypeError: Must be number, not NoneType
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/pages/list.py", line 227, in idle_update_bottles
    self.list_bottles.add(BottlesListEntry(self.window,
  File "/usr/share/bottles/bottles/pages/list.py", line 57, in __init__
    update_date = datetime.strptime(self.configuration.get("Update_Date"), "%Y-%m-%d %H:%M:%S.%f")
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S.%f'

Based on the log it is detecting the bottles. Maybe it has problems displaying them due to the missing gtk modules?

**Comment by mirkobrombin** [comment]
Please upload the bottle.yml file

**Comment by windowsagent** [comment]
The FL Studio doesn't have one, but it makes sense as I forgot to mention I deleted that one earlier (through bottles itself).

Here's the LameXP one:
Creation_Date: '2021-08-08 19:40:21.237949'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.1
Environment: Software
External_Programs:
    LameXP: /home/windowsagent/.local/share/bottles/bottles/LameXP/drive_c/Program
        Files (x86)/MuldeR/LameXP/LameXP.exe
Installed_Dependencies: []
Name: LameXP
Parameters:
    aco_compiler: false
    discrete_gpu: false
    dxvk: false
    dxvk_hud: false
    environment_variables: ''
    fixme_logs: false
    gamemode: false
    pulseaudio_latency: false
    sync: wine
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: true
Path: LameXP
Programs: {}
Runner: vaniglia-6.13
State: 0
Uninstallers: {}
Update_Date: '2021-08-08 19:42:43.090939'
VKD3D: vkd3d-v2.4
Versioning: false

**Comment by mirkobrombin** [comment]
`ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S.%f'` this is the problem, I need to do some testing
