### ISSUE TITLE
elementary OS 6 porting

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#457]
Manifest: https://github.com/bottlesdevs/Bottles/blob/master/com.usebottles.bottles.elementary.json

First working build here: https://github.com/bottlesdevs/Bottles/issues/457#issuecomment-899363947

Currently this cannot be achieve because some extensions are missing from the elementary flatpak repository.

Platform:
- org.gnome.Platform.Compat.i386
- org.freedesktop.Platform.GL32
- org.freedesktop.Platform.VAAPI.Intel

SDK:
- org.gnome.Sdk.Compat.i386
- org.freedesktop.Sdk.Extension.toolchain-i386

Also there is no elementary variants, like io.elementary.Sdk.Compat.i386. These are available from flathub but it is not pre-configured in elementary, so currently Bottles Treviso cannot be ported in elementary os 6.

**Comment by sonnyp** [comment]
Since Elementary is fully embracing flatpak, is it worth supporting Elementary explicitely?

I understand Elementary doesn't ship with flathub enabled by default but I imagine most users will enable it or be willing to do so.

Or maybe wait for someone willing to maintain Bottles Elementary?

**Comment by mirkobrombin** [comment]
Bottles started as an elementary app and as an elementary user I find the experience of having to use it with the Adwaita (broken) theme horrible. I'm mainly thinking about the user experience.
![image](https://user-images.githubusercontent.com/9479903/129217474-515062fc-e521-4d1f-ba8e-f7d43a8d513b.png)

**Comment by ZekeSmith** [comment]
Hmm mabye contact the elementry team I am sure they would want to embrace new software into their flatpak repo. Porting it might be a bit difficult though I could imagine. Having the elementry pay what you want could be useful though.

**Comment by mirkobrombin** [comment]
Perhaps this can be achieved by using the appimage as source in the flatpak, since it already has all the necessary dependencies. Ok it's highly tweaked but it's something ..

**Comment by mirkobrombin** [comment]
> Hmm mabye contact the elementry team I am sure they would want to embrace new software into their flatpak repo. Porting it might be a bit difficult though I could imagine. Having the elementry pay what you want could be useful though.

https://github.com/elementary/flatpak-platform/discussions/61

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/129541937-8b401e7e-8da3-4b00-94f4-227ccd6fa084.png)

Using the new eos flatpak manifest.

**Comment by mirkobrombin** [comment]
closed by https://github.com/bottlesdevs/bottles-elementary
