### ISSUE TITLE
[BUG] Latest unstable AppImage crashes 

### ISSUE THREAD

**Issue by SoftExpert** [bottlesdevs/Bottles#465]
**Describe the bug**
Latest unstable AppImage crashes 

**Installation**
 - Appimage: [e.g. Appimage, Meson build, other]
 - Unstable build [https://github.com/bottlesdevs/Bottles/commit/62e915110b3435613df061e3b1d069f56127dbbd](https://github.com/bottlesdevs/Bottles/commit/62e915110b3435613df061e3b1d069f56127dbbd)

**To Reproduce**
1. From console launch ./Bottles-devel-x86_64.AppImage
2. Bottles crashes immediately
3. See error

**Expected behavior**
Main windows should open

**Screenshots**
![image](https://user-images.githubusercontent.com/1254018/129273316-240b9532-d338-4d5d-bb96-870654eb7935.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.0.4

**Additional context**
Bottles 2021.7.28-treviso-2 starts correctly

**Comment by mirkobrombin** [comment]
should be fixed with latest
