### ISSUE TITLE
[Request] Add media foundation to dependency list

### ISSUE THREAD

**Issue by Crono23** [bottlesdevs/Bottles#468]
I tried playing Blasphemous using Bottles. The game runs fine, however, the cutscenes doesn't show up. Because AFAIK Blasphemous is using media foundation to play those cutscenes.
I would very much like it if it is added to dependency list so I can install it.

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. Can you open a new issue [here](https://github.com/bottlesdevs/dependencies/issues/new?assignees=mirkobrombin&labels=request+dependency&template=dependency-implementation-request.md&title=%5BRequest+dependency%5D), following the template?

**Comment by Crono23** [comment]
I opened the issue as requested. But I can only find download link for the media foundation on the Microsoft Update Catalog website, is that okay?

**Comment by mirkobrombin** [comment]
> I opened the issue as requested. But I can only find download link for the media foundation on the Microsoft Update Catalog website, is that okay?

Yep, thanks. I'm going to track this in the new issue.

Ref: https://github.com/bottlesdevs/dependencies/issues/5
