### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ovari** [bottlesdevs/Bottles#473]
- [x] 1
- [x] 2
- [x] 3 issue created at https://github.com/bottlesdevs/dependencies/issues/6

Can the following strings please be translated:
1. `Gaming`
![kép](https://user-images.githubusercontent.com/17465872/129460552-d628bcc8-5999-421e-8e6f-eab3ac3b9b63.png)
![kép](https://user-images.githubusercontent.com/17465872/129460576-eb75e3a4-53da-4ab4-b3a2-fd1a4100c061.png)
2. `64-bit`
![kép](https://user-images.githubusercontent.com/17465872/129460600-6b5db4da-9f49-4544-9c41-7a8899eacdc4.png)
3. `Essentials`, `Fonts`, descriptions like `Microsoft Arial Font` (in English, should the the tags be singular, i.e. `Essential`, `Font`)
![kép](https://user-images.githubusercontent.com/17465872/129460655-2daeffaf-42c8-4581-9c87-03bc55e6e222.png)

Thank you

Linux Mint 20.2 Cinnamon
Bottles 2021.8.14-treviso

**Comment by mirkobrombin** [comment]
Dependency categories cannot be translated as they come from the repository. Isn't architecture an international format? For everything else I will add the translations soon.

**Comment by ovari** [comment]
English → Hungarian (hyphen `-` replaced by non-breaking space &nbsp; and `es` appended)
32-bit → 32 bites (https://hu.wikipedia.org/wiki/32_bites_architekt%C3%BAra)
64-bit → 64 bites (https://hu.wikipedia.org/wiki/64_bites_architekt%C3%BAra)

Thank you

**Comment by mirkobrombin** [comment]
Also environments cannot be translated as they are stored in the bottle configuration file

**Comment by mirkobrombin** [comment]
Translations provided for architectures

**Comment by ovari** [comment]
> Dependency categories cannot be translated as they come from the repository

Does that mean that descriptions like `Microsoft Arial Font` **can** be translated?

**Comment by mirkobrombin** [comment]
> > Dependency categories cannot be translated as they come from the repository
> 
> Does that mean that descriptions like `Microsoft Arial Font` **can** be translated?

No

**Comment by ovari** [comment]
> > > Dependency categories cannot be translated as they come from the repository
> > 
> > 
> > Does that mean that descriptions like `Microsoft Arial Font` **can** be translated?
> 
> No

Where is the repository which they come from? Perhaps they can be translated there?

**Comment by ovari** [comment]
> Also environments cannot be translated as they are stored in the bottle configuration file

Can environments always stored say in English in the bottle configuration file; however, when displayed in the GUI be translated before being shown? If there is no translation for a locale, it could show in English.

What do you think?

Thank you

**Comment by ovari** [comment]
Couldn't see the string `Generating Bottle configuration file …` to translate. Did we overlook it? Thank you
