### ISSUE TITLE
[BUG] Wrong working directory for external programs

### ISSUE THREAD

**Issue by Lucki** [bottlesdevs/Bottles#498]
**Describe the bug**
The wrong (or none at all) working directory is set for external programs.

**Installation**
 - Method: aur
 - Version 2021.8.14-1

**To Reproduce**
1. Add an external program which relies on the current working directory
2. Try to start the program and see it crashing or misbehaving
3. Try to open the program folder from the programs context menu and see nothing happen:
    ~~~
    gio: file:///home/lucki/Game.exe: Fehler beim Holen der Informationen für Datei »/home/lucki/Game.exe«: Datei oder Verzeichnis nicht gefunden
    gio: file:///home/lucki/Game.exe: Error getting information for file »/home/lucki/Game.exe«: file or folder not found
    ~~~

**Expected behavior**
The correct working directory has been set either automatically to the executable path or through an option.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch

**Additional context**
This looks like the causing line:
https://github.com/bottlesdevs/Bottles/blob/97d409a4b954ac6ae5a6bb86f4d9ba18d5b6c31a/src/runner.py#L793
`program_folder` is set to the executable and not the path.

Quick fix:

~~~ diff
- program_folder = ext_programs[program].split("/")[-1] 
+ program_folder = os.path.dirname(ext_programs[program])

**Comment by BrainBlasted** [comment]
I'm running the latest version and still seeing this happen.
