### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by Maagot** [bottlesdevs/Bottles#506]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.8.28-treviso-2

**Log**
```python3
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Software'  File "/app/share/bottles/bottles/utils.py", line 277, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 716, in async_delete_bottle
    shutil.rmtree(path)

  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())

  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)

```

**Comment by mirkobrombin** [comment]
What runner did you use to create the bottle?

**Comment by thetaprimeprime** [comment]
I found the same issue a week ago, it seems that Bottles doesn't successfully mkdir.

So I mkdir for a bottle manually before I actually create the bottle in Bottles, and it works for me.

I use flatpak version too.

**Comment by mirkobrombin** [comment]
> I found the same issue a week ago, it seems that Bottles doesn't successfully mkdir.
> 
> So I mkdir for a bottle manually before I actually create the bottle in Bottles, and it works for me.
> 
> I use flatpak version too.

There are 2 possible causes:
- the bottle was created using a runner not compatible with flatpak (e.g. lutris-lol, lutris-ge-LoL) so the wineprefix is not initialized and the path is never created
- the flatpak has no write permissions (this is not possible at all, starting from 2021.7.28 it uses its own self-container path, maybe you have this problem before that version)
