### ISSUE TITLE
[BUG] Possible Bug in bottles renaming

### ISSUE THREAD

**Issue by PsykeDady** [bottlesdevs/Bottles#509]
FIRST OF ALL: sorry for my bad english :-\ 

**Describe the bug**
Renaming a bottles work only for "GUI" view, i suspect that not work into some config file. If i rename a bottle, opening software from terminal list the old name but GUI list new name. This prevents me from create a new bottle with old name of another ( software create a bottle but at next start of software, it disappear) 

**Installation**
 - Method: AUR
 - Version: 2021.8.28-treviso-2

**To Reproduce**
1. Create a bottles named "myBottle"
2. Rename into "myOldBottle"
3. Create a bottle named "myBottle"
4. quit bottles
5. open bottles

**Expected behavior**
bottles has now two bottles: 
- myBottle
- myOldBottle

**Actual behavior** 
Bottles has instead one only bottle: 
- myOldBottle

**Screenshots**
![photo_2021-08-31_12-43-51](https://user-images.githubusercontent.com/27916449/131490530-205fded6-73fc-4477-b265-646e81b60fec.jpg)
( please note name on bottle is different from name on terminal) 

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: no-version

**Additional context**
hi mirko <3

**Comment by mirkobrombin** [comment]
Bug confirmed
