### ISSUE TITLE
[Bug report] Bottles fails to launch windows/wine command line

### ISSUE THREAD

**Issue by Cervoxx** [bottlesdevs/Bottles#513]
This crash report was generated by Bottles.

**Details**
* **package**: Other (Arch AUR)
* **version**: 2021.8.28-treviso-2

This error occurs when I try to launch the wine command line from bottles. The last version that did work is 2021.8.14-treviso. This does NOT crash the entire program, just spits out an error.

**Log**
```python3
not all arguments converted during string formatting  File "/usr/share/bottles/bottles/utils.py", line 277, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/runner.py", line 277, in run_command
    return UtilsTerminal().execute(command)

  File "/usr/share/bottles/bottles/utils.py", line 103, in execute
    ' '.join(self.terminal) % f"bash -c '{command}'",

```

**Comment by mirkobrombin** [comment]
The new release should be available from AUR.

**Comment by Cervoxx** [comment]
Confirmed fixed, thank you!

**Comment by mirkobrombin** [comment]
> Confirmed fixed, thank you!

Thanks for reporting!
