### ISSUE TITLE
[BUG] Bottles Icon not Showing in windows

### ISSUE THREAD

**Issue by RushingAlien** [bottlesdevs/Bottles#516]
**Describe the bug**
Window created by bottles is not associated with `com.usebottles.Bottles.desktop` shortcut
**Installation**
 - Method: AUR Arch Linux
 - Version 2021.8.28-treviso-3

**To Reproduce**
1. Install bottles from the AUR
2. Open Bottles
3. See in the overview and dash that the bottles window is not associated with the desktop shortcut (no icon)
4. The bottles shortcut doesn't indicate that the app is on (does not show tiny dot underneath)

**Expected behavior**
For Bottles desktop shorcut to be associated Bottles' windows
**Screenshots**
![Cuplikan layar dari 2021-09-05 08-22-22](https://user-images.githubusercontent.com/80886145/132111977-ffef88e1-89a9-45f6-9cc4-1c6418aac7d2.png)
![Screenshot-2021-09-05-08:22:37](https://user-images.githubusercontent.com/80886145/132111980-65aab0ff-0b51-4a76-9a3d-ad368a7dc7cc.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version : Rolling
 - Desktop : Gnome
 - Display server : Wayland
 
 **Additional Information**
I currently worked around this by adding `StartupWMClass=bottles` in my `.desktop` file.
Not sure about the flatpak and appimage version.

**Comment by RushingAlien** [comment]
Possibly related https://aur.archlinux.org/packages/bottles/#comment-818872

**Comment by mirkobrombin** [comment]
AppImage, snap and flatpak use another desktop file so I guess it just touches Arch and builds in general. The solution is simple, I put it in the task list.
