### ISSUE TITLE
[BUG] Can't create file path when installing dependencies

### ISSUE THREAD

**Issue by MagicalDrizzle** [bottlesdevs/Bottles#517]
**Describe the bug**
Installing dependencies seems to silently fail with the "can't create file path" error, while the GUI download indicators keep running till I manually terminate the application. Installing runners works fine so I don't think this is a permission issue.
```
/home/~~/.local/share/bottles/temp/georgi32.exe/fontinst.exe: can't create file path 
2021-09-05 08:51:36 WARNING: File [impact32.exe] already exists in temp, skipping.
/home/~~/.local/share/bottles/temp/impact32.exe/fontinst.exe: can't create file path
```
**Installation**
 - Method: AUR/AppImage (both have this problem)
 - Version: 2021.8.28

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Version: rolling

**Comment by mirkobrombin** [comment]
I have tried the dependencies and they work, I believe there is an error in the font manifest. What's weird is that despite the error actually installing the font for me, it's not really failing.Also, the interface says it is progressing and it's true, it hasn't crashed, the process just takes some time.I'll take a look at the manifest to see if there's a mistake.

**Comment by MagicalDrizzle** [comment]
I personally have waited like an hour and it's still progressing (and the fonts folder is empty) so I think it just silently failed and only shows up on the terminal.

**Comment by mirkobrombin** [comment]
> I personally have waited like an hour and it's still progressing (and the fonts folder is empty) so I think it just silently failed and only shows up on the terminal.

I can confirm the problem using the public repository, I was using a test one

**Comment by mirkobrombin** [comment]
The problem has been fixed and will be distributed as a hotfix today.
