### ISSUE TITLE
[Request] Proxy settings

### ISSUE THREAD

**Issue by thjderjktyrjkt** [bottlesdevs/Bottles#518]
**Is your feature request related to a problem? Please describe.**
My PC is behind a firewall with network access only from a proxy, but `Bottles` doesn't follow the system proxy settings, nor is there any settings for manual proxy configuration.

**Describe the solution you'd like**
Make it so it follows system proxy settings (KDE and Gnome) 

**Describe alternatives you've considered**
Add an option for proxy server.

**Additional context**
I'm using Flatpak version. I can use `Flatseal` to manually change environment variables for `Bottles`

**Comment by eailfly** [comment]
This is actually a key feature for China users

**Comment by mirkobrombin** [comment]
Just use local repositories. Clone all repos and launch Bottles using the right env vars:

```bash
LOCAL_INSTALLERS=/path/to/programs/ \
LOCAL_DEPENDENCIES=/path/to/dependencies/ \
LOCAL_COMPONENTS=/path/to/components flatpak run com.usebottles.bottles
```

Remember to give permissions using Flatseal.

**Comment by glyh** [comment]
@mirkobrombin Could you give  a more detailed explanation?Which repo should I clone?

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/programs
https://github.com/bottlesdevs/dependencies
https://github.com/bottlesdevs/components

**Comment by zicklag** [comment]
I can clone those repositories, but bottles is still unable to get to the internet to download applications such as dxvk, and it fails with an error in the console:

```
11:18:33 (WARNING) Connection status: offline … 
11:18:33 (INFO) Bottles Started! 
11:18:33 (WARNING) Connection status: offline … 
11:18:33 (INFO) Using local components repository at /home/zicklag/bottles/components 
11:18:33 (INFO) Using local dependencies repository at /home/zicklag/bottles/dependencies 
11:18:33 (INFO) Using local installers repository at /home/zicklag/bottles/programs 
11:18:33 (INFO) Performing Bottles checks… 
11:18:33 (INFO) Runners found:
	 - sys-wine-7.0
 
11:18:33 (WARNING) Connection status: offline … 
11:18:33 (INFO) No components found. 
11:18:34 (WARNING) Connection status: offline … 
11:18:34 (INFO) No dependencies found! 
11:18:34 (WARNING) Connection status: offline … 
11:18:34 (INFO) No installers found! 
11:18:34 (INFO) Library saved 
11:18:37 (INFO) Performing Bottles checks… 
11:18:37 (WARNING) No dxvk found. 
11:18:38 (WARNING) Connection status: offline … 
11:18:38 (WARNING) No vkd3d found. 
11:18:39 (WARNING) Connection status: offline … 
11:18:39 (WARNING) No nvapi found. 
11:18:39 (WARNING) Connection status: offline … 
11:18:39 (WARNING) No latencyflex found. 
11:18:40 (WARNING) Connection status: offline … 
11:18:40 (WARNING) Connection status: offline … 
11:18:40 (INFO) Runners found:
	 - sys-wine-7.0
 
11:18:40 (WARNING) No runners found. 
11:18:41 (WARNING) Connection status: offline … 
11:18:41 (INFO) No components found. 
11:18:41 (INFO) No dependencies found! 
11:18:41 (INFO) No installers found! 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/new.py", line 196, in create_bottle
    dxvk=self.manager.dxvk_available[0],
IndexError: list index out of range
```

**Comment by Liquorice10113** [comment]
I am suprised that proxychains actually works.
Install and configure proxychains then `proxychains flatpak run com.usebottles.bottles`, the proxy works just fine.

**Comment by fooryo** [comment]
> I am suprised that proxychains actually works. Install and configure proxychains then `proxychains flatpak run com.usebottles.bottles`, the proxy works just fine.

Does it still for work for you? They same command gives me error:
```
ERROR: ld.so: object '/usr/lib/libproxychains4.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by synalice** [comment]
> Just use local repositories. Clone all repos and launch Bottles using the right env vars:
> 
> LOCAL_INSTALLERS=/path/to/programs/ \
> LOCAL_DEPENDENCIES=/path/to/dependencies/ \
> LOCAL_COMPONENTS=/path/to/components flatpak run com.usebottles.bottles
> Remember to give permissions using Flatseal.

I've cloned the dependencies repo and changed `url` in one of the YAML files. Running Bottles like this `LOCAL_DEPENDENCIES=/path/to/dependencies flatpak run com.usebottles.bottles`. Unfortunately, I still get an error.
```
(WARNING) Failed to download [https://original-url.com/file.exe] with code: 403 != 200
```

Am I doing something wrong?

**Comment by luoyanghero** [comment]
> https://github.com/bottlesdevs/programs https://github.com/bottlesdevs/dependencies https://github.com/bottlesdevs/components

USE LOCAL REPO NOT OK. 
But local repo record dependency package url, can download manually and put it to bottles/temp.
For example: one dependency is "soda-9.0-1-x86_64.tar.xz", but download failed on offical website.
You can find "soda-9.0-1" at repo "components,dependency,programs". Get download url "https://github.com/bottlesdevs/wine/releases/download/soda-9.0-1/soda-9.0-1-x86_64.tar.xz" at "soda.9.0-1.yml".
After downloaded, copy it to "/root/.var/app/com.usebottles.bottles/data/bottles/temp"
Rerun bottles.

**Comment by leojay-wang** [comment]
Recently I meet the same problem. But After I tried, HTTP_PROXY and HTTPS_PROXY enviroment viriables are able to effect. If you need enable proxy settings, You can execute below commands:
```
export HTTP_PROXY=http://proxy_ip:port
export HTTPS_PROXY=http://proxy_ip:port
flatpak run com.usebottles.bottles
```
