### ISSUE TITLE
[BUG] Bottles install lutris-fshack in the wrong path

### ISSUE THREAD

**Issue by MagicalDrizzle** [bottlesdevs/Bottles#527]
The CLI shows lutris 6.14 is installed, the files for it is there, but the GUI says it's not.

**Installation**
 - Method: AppImage
 - Version: 2021.8.28-treviso-4

![Screenshot from 2021-09-08 07-03-37](https://user-images.githubusercontent.com/49761211/132425225-2deed8e3-3b8b-4843-8a29-9bad6c9c41b6.png)

I don't actually know how to reproduce it, I just kind of exit and start and repeat a bunch of times

**Comment by mirkobrombin** [comment]
I missed this issue. I don't understand the problem, can you provide more details?

**Comment by mirkobrombin** [comment]
I missed this issue. This is the problem:

```bash
Failed to open '/home/USER/.var/app/com.usebottles.bottles/data/bottles/runners/lutris-6.14-2-fshack': No such file or directory
```

It is extracting the component archive in the wrong directory.
