### ISSUE TITLE
Toggling DXVK and VKD3D cause the entire applictation to freeze

### ISSUE THREAD

**Issue by MagicalDrizzle** [bottlesdevs/Bottles#529]
Not sure if this is specific to bottles or not, cause I think this happens with lutris also.
Toggling DXVK, VKD3D and use virtual desktop cause the application to freeze for a solid 30 seconds before responding. Maybe toggling these settings trigger a lot of changes, but would it better to show a loading screen than to freeze the whole thing?

**Comment by mirkobrombin** [comment]
These are Bottles' only non-async operations. I'm already working on it.
