### ISSUE TITLE
[Request] MangoHUD support?

### ISSUE THREAD

**Issue by MagicalDrizzle** [bottlesdevs/Bottles#530]
The included DXVK HUD only works with GPUs that support Vulkan, and games that don't turn into a glitchy mess with DXVK. enabled Would it be possible to add MangoHud also?

**Comment by mirkobrombin** [comment]
Can you provide some more details? For example the link to the project and the example of use?

**Comment by MagicalDrizzle** [comment]
https://github.com/flightlessmango/MangoHud
like the dxvk overlay but compatible with a wider variety of games

**Comment by mirkobrombin** [comment]
Thanks, I'll have a look at it

**Comment by mirkobrombin** [comment]
I have to put it in the Bottles repository and register it as a component in order to use it. I think he will work on it for the 28th release.

**Comment by mirkobrombin** [comment]
Analyzing the component, I noticed that it is necessary to compile a custom version as the execution script hard-declares the libraries it needs. This will take a little longer, at the moment it is still possible to install it locally and add it to the program arguments.

**Comment by nilsoffermann** [comment]
It is also available as _org.freedesktop.Platform.VulkanLayer.MangoHud_ on Flathub. That's how the Steam Flatpak and Lutris access it in the Flatpak version afaik

**Comment by mirkobrombin** [comment]
I have no experience with flatpak extensions but I think this the way to go

**Comment by JurijOrlow** [comment]
> I have no experience with flatpak extensions but I think this the way to go

You can simply add command prefix, since mangohud can be enabled by prefixing wine command with "mangohud" (eg. 'mangohud wine /path/to/exe')

**Comment by Ayush1325** [comment]
Any updates on how to use mangohud with bottles? I tried changing launch options to `mangohud %command%` and `mangohud wine %command%`. However, neither seem to work with the flatpak version. I have mangohud installed on my system as well as `org.freedesktop.Platform.VulkanLayer.MangoHud` installed. 
The error I get is `env: ‘mangohud’: No such file or directory`.

**Comment by mirkobrombin** [comment]
Closed by c6d23fb818014e6ebe8f2660d4b2281bdfb549b2 and 66adbd4bf2e33bf96b5488ed0808463e48e7d441
