### ISSUE TITLE
[Crash report]  Downloading vkd3d fails, abort gives error

### ISSUE THREAD

**Issue by Eonfge** [bottlesdevs/Bottles#533]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.8.28-treviso

**Log**
```python3
'Manager' object has no attribute 'async_component_manager'  File "/usr/share/bottles/bottles/utils.py", line 277, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/manager.py", line 534, in async_create_bottle
    self.check_vkd3d(no_async=True)

  File "/usr/share/bottles/bottles/backend/manager.py", line 330, in check_vkd3d
    self.async_component_manager.install(

```

**Comment by mirkobrombin** [comment]
I should already fixed it. Cam you please upgrade to the latest release and test again?

**Comment by Eonfge** [comment]
I'm running Bottles directly from the Fedora Main Repository. I've given it another shot with the Flatpak image but that's giving me other issues: https://github.com/flathub/com.usebottles.bottles/issues/148

**Comment by mirkobrombin** [comment]
So the Fedora package is not updated. There have been several updates in the last few days, so I can understand that the maintainer didn't distribute them right away. I close this issue but I keep the other from flathub monitored.
