### ISSUE TITLE
[BUG] Unable to find libjpeg.so.8

### ISSUE THREAD

**Issue by thetaprimeprime** [bottlesdevs/Bottles#539]
**Describe the bug**
Some programs won't show jpeg pictures and the following output printed:
`wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8`

**Installation**
 - Method: Flatpak
 - Version 2021.9.14-treviso

**To Reproduce**
1. Open a program that shows a jpeg image.
2. The image not showed.
3. Terminal says wine cannot find libjpeg.so.8

**Expected behavior**
Since Flatpak runtime has `libjpeg.so.62.3.0`, so I guess it should be linked with `libjpeg.so.62.3.0`.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Comment by mirkobrombin** [comment]
Which runner have you tried?

**Comment by thetaprimeprime** [comment]
I tried lutris-6.14-2 and vaniglia-6.15

**Comment by mirkobrombin** [comment]
I need to figure out how to provide this in the Flatpak, I would mention @sonnyp

**Comment by sonnyp** [comment]
@thetaprimeprime could you provide a name of a windows app I can reproduce this with?

**Comment by thetaprimeprime** [comment]
> @thetaprimeprime could you provide a name of a windows app I can reproduce this with?

I found a program which can produce this problem, MycView.
http://myc01.free.fr/mycview/
MycView is an image viewer. When it opens a jpeg file, no image but a black screen shows.

**Comment by sonnyp** [comment]
Thanks. I can reproduce but couldn't find an obvious solution yet.

Could you try and reproduce in Steam flatpak somehow?

Writing down some notes for when I or someone else comes back to this

Flatpak bottles seem to include the "standard" i386 compatibilities. 

Comparing [Bottles flatpak manifest](https://github.com/flathub/com.usebottles.bottles/blob/master/com.usebottles.bottles.yml) with [Steam flatpak manifest ](https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.yml) may help.

Perhaps Freedesktop sdk 21 fixes the issue.

**Comment by mirkobrombin** [comment]
I can confirm this also outside of the flatpak (fedora and aur version), but should be easy to fix, just adding libjpeg as a dependency

```
0114:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8
0118:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8
0118:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8
```

Also testing with the freedesktop sdk 21, the problem persist.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/141691332-56d09954-79d3-4910-b401-0bff82a32b3f.png)

Seems to be working with latest release. Feel free to add more details :)

**Comment by thetaprimeprime** [comment]
Great to hear that! Thanks!
