### ISSUE TITLE
Installation manager

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#55]
One of the next features is a repository based program installer.

Unlike other wine prefix managers, this feature installs programs in an existing bottle (if possible). Each program consists of a manifest file containing installation instructions and necessary dependencies The installer checks whether the new program is compatible with other already installed and then proceeds with the installation.

The development can be split into 3 parts:
- repository/manifest structure
- conflicts finder
- effective installer

Repository concept: https://github.com/bottlesdevs/programs

**Comment by mirkobrombin** [comment]
Work for the installers will begin after v4.

**Comment by LinuxConfused** [comment]
I'm on Pop! OS 21.04
I'm struggling after migration from flatpac. I had installed app image recently when you notified the impending doom of flatpac. However, my program wouldn't run from the app image, so I continued flatpac version. Today the flatpac no longer worked. Regrettably, I uninstalled my program, thinking I would reinstall on the new bottles and it should work. Now my program, which had been successfully running on the flatpac version will not install in bottles. When I click on "Run Executable", nothing happens. I thought I migrated my files successfully, but maybe not? I don't know how to verify, or where exactly they should go.

I reinstalled the app image of the latest release and am trying to use it. Here's what it does when I open from the app image:
APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2
Gtk-Message: 20:47:49.970: Failed to load module "appmenu-gtk-module"
2021-07-23 20:47:51 INFO: Dxvk found: [dxvk-1.8.1]
2021-07-23 20:47:51 INFO: Vkd3d found: [vkd3d-v2.4]
2021-07-23 20:47:51 INFO: Runners found: [chardonnay-6.10]
2021-07-23 20:47:51 INFO: Bottles found: Amblyoplay
2021-07-23 20:47:51 INFO: Bottles Started!
2021-07-23 20:48:07 INFO: Setting Key: [sync] to [wine] for bottle: [Amblyoplay] …

(bottles:53585): Handy-CRITICAL **: 20:48:07.618: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed

When I attempt to run the windows executable for the Amblyoplay program, here is the result:
MESA-INTEL: warning: Haswell Vulkan support is incomplete
/lib/ld-linux.so.2: could not open
/lib/ld-linux.so.2: could not open
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

0090:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003


I'm a linux noob (I guess that's obvious!) but hopefully this is the info you need to help me! Thanks so so much!

**Comment by mirkobrombin** [comment]
Closing as the first version has already been integrated.
