### ISSUE TITLE
[Request] Deploy bottle as appimage.

### ISSUE THREAD

**Issue by enzeinzen** [bottlesdevs/Bottles#553]
Not really a problem but it would be awesome and it would make porting over windows applications so easy.

I would love it if there were a script within bottles that would allow the user to deploy a specific bottled application as an appimage that contains wine, the bottle itself and all dependencies. I know that it's more an appimage thing but creating appimages for windows apps is very tedious at the moment and this could potentially simplify the process greatly. The scripts are already made, they just have to be integrated into a seamless solution and I think Bottles would be perfect for that.

[Here](https://github.com/RazZziel/PortableLinuxGames) are some great scripts for making wine appimages.

Thank you and I completely understand if you think that's beyond the scope of the project.

**Comment by mirkobrombin** [comment]
We are already doing this but in a different way. Bottles can already export a bottle with all its dependencies and will soon be able to export and import the bottle configuration file, to replicate it. The idea of ​​using AppImage to distribute Windows software isn't bad but it might actually be out of the idea of ​​the project itself.

**Comment by mirkobrombin** [comment]
Closing but still a good idea.
