### ISSUE TITLE
[Crash report] No such file or directory for Font Times New Roman 32

### ISSUE THREAD

**Issue by joandreiy** [bottlesdevs/Bottles#554]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.9.14-treviso

**Log**
```python3
[Errno 2] Arquivo ou diretório inexistente: '/home/USER/.local/share/bottles/temp/times32/Times.TTF'  File "/usr/share/bottles/bottles/utils.py", line 295, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/dependency.py", line 196, in async_install
    self.__step_install_fonts(

  File "/usr/share/bottles/bottles/backend/dependency.py", line 540, in __step_install_fonts
    shutil.copyfile(

  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

```

**Comment by mirkobrombin** [comment]
What dependency are you trying to install

**Comment by joandreiy** [comment]
Font Times New Roman 32

**Comment by mirkobrombin** [comment]
I'll take a look, thanks for reporting

**Comment by mirkobrombin** [comment]
What package are you using?
I've tested with Flatpak, AppImage and build from source but cannot replicate this.

**Comment by joandreiy** [comment]
com.usebottles.bottles.deb package

**Comment by mirkobrombin** [comment]
Please try another package

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/134799281-2e738619-0ef4-497b-9059-821cb91280f6.png)
I have tried to replicate the bug with every package but it doesn't appear at all to me. I close the issue waiting for similar reports.
