### ISSUE TITLE
Build from source. But got an error after.

### ISSUE THREAD

**Issue by shrisha108** [bottlesdevs/Bottles#563]
Hi just installed Bottles from source without any errors but when I ran it got this:
```
[shrisha@fedora build]$ bottles
Traceback (most recent call last):
  File "/usr/local/share/bottles/bottles/main.py", line 155, in do_command_line
    self.do_activate()
  File "/usr/local/share/bottles/bottles/main.py", line 203, in do_activate
    if css_res:
UnboundLocalError: local variable 'css_res' referenced before assignment
```
Any directions to dig?

Fedora 34, 64-bit.

**Comment by mirkobrombin** [comment]
Should be fixed by latest commit ccc3956

**Comment by shrisha108** [comment]
Thank you. When approximately?

**Comment by mirkobrombin** [comment]
> Thank you. When approximately?

The next release is scheduled for 2021.9.28, you can still download the latest unstable from [here](https://github.com/bottlesdevs/Bottles/actions/runs/1269491191) or clone the repository source using git or downloading the latest [archive](https://github.com/bottlesdevs/Bottles/archive/refs/heads/master.zip) from master.

**Comment by shrisha108** [comment]
I just edited main.py and added    ```  css_res = False ``` And it's up and running.

**Comment by mirkobrombin** [comment]
> I just edited main.py and added ` css_res = False` And it's up and running.

That too is an option yeah haha
