### ISSUE TITLE
[BUG] `Run with arguments` doesn't work

### ISSUE THREAD

**Issue by thetaprimeprime** [bottlesdevs/Bottles#564]
**Describe the bug**
`Run with arguments` doesn't work. 

![image](https://user-images.githubusercontent.com/2255715/134762936-bd3bb77a-a475-42d8-84cd-2068945e8f3c.png)
Clicking `Run` throws an error:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/dialogs/runargs.py", line 47, in __run_executable
    self.parent.run_executable(False, args)
AttributeError: 'DetailsView' object has no attribute 'run_executable'
```

**Installation**
 - Method: Flatpak
 - Version 2021.9.14-treviso

**To Reproduce**
1. Enter a bottle
2. Open `Run with arguments` in the inverted triangle menu.
3. Type any args, such as `-a`
4. Click `Run`

**Expected behavior**
Run without error

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Comment by mirkobrombin** [comment]
Thanks for reporting
