### ISSUE TITLE
[BUG] Chinese translation doesn't work

### ISSUE THREAD

**Issue by lumingzh** [bottlesdevs/Bottles#574]
**Describe the bug**

I'm using fedora silverblue in Chinese, bottles installed from flathub.
After start bottles I found it displayed in English instead of Chinese.

I don't know about software development, but I think it maybe relates to the language code name like zh_Hans and zh_CN.

**Installation**
 - Method: flatpak from flathub
 - Version: 2021.9.28-treviso

**To Reproduce**

1. Installed from flathub
2. start bottles
3. the app displayed in English instead of Chinese

**Expected behavior**

Display in Chinese

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/89230850/135376148-bce356f6-6e21-4be9-82a4-a2f306e03a1d.png)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version: 35beta

**Comment by mirkobrombin** [comment]
Bottles is fully translated in Chinese (simplified).  https://hosted.weblate.org/engage/bottles/

**Comment by lumingzh** [comment]
> Bottles is fully translated in Chinese (simplified). https://hosted.weblate.org/engage/bottles/

I know, I translated it. But it doesn't work.

**Comment by mirkobrombin** [comment]
I tried to set the Chinese language and it works, sure you are using the correct locale?

**Comment by lumingzh** [comment]
I find only one locale file in installed app/runtime directory. 

The file path is: `/var/lib/flatpak/runtime/com.usebottles.bottles.Locale/x86_64/stable/fe73c934458ba01075d6ea039a5a4870339452a54b244ff7c64e67a633c9d0f4-zh/files/zh/share/zh_Hans/LC_MESSAGES/bottles.mo`, but has no effect. I don't know why.

**Comment by mirkobrombin** [comment]
Is it working launching with env var `LANG`?

**Comment by lumingzh** [comment]
No, but one gtk-warning show up that: Locale not supported by C library. Using the fallback 'C' locale

I tried --env=LANG=zh_CN/zh_Hans/zh, all three didn't work and zh_CN has no warning about locale.

**Comment by mirkobrombin** [comment]
This is weird

**Comment by mirkobrombin** [comment]
the `Locale not supported` is raised by `zh_Hans`?

**Comment by lumingzh** [comment]
> the `Locale not supported` is raised by `zh_Hans`?

Yes, this gtk-warning is raised by zh_Hans and zh.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/135821446-7f55b54a-1b93-4798-ade6-51a271dcf52f.png)
It raise the warning but actually work

**Comment by lumingzh** [comment]
> > the `Locale not supported` is raised by `zh_Hans`?
> 
> Yes, this gtk-warning is raised by zh_Hans and zh.

Well, I tried to create a bottle, and run with LANG=zh_Hans, and it's funny:
![2021-10-04 16-45-24 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821752-158cda24-0d07-4b25-8904-e0f4a4d85211.png)
![2021-10-04 16-46-41 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821756-086f81e8-9e55-467c-b395-5722750d4c57.png)
![2021-10-04 16-47-06 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821759-f532c1ff-a97d-4da1-bcbb-ba0287d50620.png)
![2021-10-04 16-47-11 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821762-69c36abb-7886-4cb0-887a-a93d15ce748d.png)
![2021-10-04 16-47-23 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821764-01942f1b-4214-480f-bc9d-09c37f0db722.png)
![2021-10-04 16-47-36 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821766-ae871a1c-682c-487d-b153-4ae8a1b83bcc.png)
![2021-10-04 16-47-49 的屏幕截图](https://user-images.githubusercontent.com/89230850/135821768-fca40833-617b-49e2-8d09-3ed424b539a8.png)

**Comment by mirkobrombin** [comment]
I think Bottles is a little bit confused

**Comment by mirkobrombin** [comment]
Oh, I got it. It only take translations for python strings but it is not working on Gtk Templates.

**Comment by lumingzh** [comment]
> Oh, I got it. It is only taking translations for python strings but it is not working with Gtk Templates.

And why must specify language environment, I think it's decided by system language.

**Comment by mirkobrombin** [comment]
> > Oh, I got it. It is only taking translations for python strings but it is not working with Gtk Templates.
> 
> And why must specify language environment, I think it's decided by system language.

But the strange thing is that it is working wit all other languages. I can see bottles fully translated in italian and other languages but in chinese is only partial :|

**Comment by lumingzh** [comment]
This is the default language setting for Chinese (Simplified) or Chinese (China) whatever in Fedora Silverblue/Gnome Shell.
![2021-10-04 17-01-49 的屏幕截图](https://user-images.githubusercontent.com/89230850/135823930-5982aa33-b958-4ee2-a129-1716b0650f9c.png)

**Comment by mirkobrombin** [comment]
Ah

**Comment by lumingzh** [comment]
The same problem happened with [Junction](https://github.com/sonnyp/Junction/issues/61), translation from weblate, po file named zh_Hans as well. But there is one more error in terminal running with --env=LANG=zh_Hans:
![2022-01-21 15-41-25 的屏幕截图](https://user-images.githubusercontent.com/89230850/150487309-b4cb19ca-bb36-4586-bfb3-c0b57deb646b.png)
I don't know if it's related.

**Comment by mirkobrombin** [comment]
This issue also touched on the Portuguese translation a few days ago which was fixed by a translations rebuild

**Comment by lumingzh** [comment]
@mirkobrombin @sonnyp New progress! [Collision](https://github.com/GeopJr/Collision/issues/58) changed language code from zh_Hans to zh_CN and the translation works normal now. I wish you can test with Bottles, thank you.

**Comment by mirkobrombin** [comment]
Thanks for updating us

**Comment by zhang-wenchao** [comment]
I also have this problem.
