### ISSUE TITLE
[Crash report] embedded null byte 

### ISSUE THREAD

**Issue by LeandroStanger** [bottlesdevs/Bottles#584]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak beta
* **version**: 2021.9.28-treviso

**Log**
```python3
embedded null byte  File "/app/share/bottles/bottles/utils.py", line 295, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/runner.py", line 307, in run_command
    res = subprocess.Popen(command, shell=True)

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(

```

**Comment by mirkobrombin** [comment]
Is this the beta release?

**Comment by LeandroStanger** [comment]
```
Is this the beta release?
```
Yes

**Comment by mirkobrombin** [comment]
This is weird, I've already fixed in the current branch. Let me check

**Comment by mirkobrombin** [comment]
@LeandroStanger can you give me the steps to reproduce?

**Comment by LeandroStanger** [comment]
```
@LeandroStanger can you give me the steps to reproduce?
```
Just install Epic Games Launcher

**Comment by mirkobrombin** [comment]
From the installers?

**Comment by LeandroStanger** [comment]
```
Using our installer?
```
Yes. Not Run

**Comment by mirkobrombin** [comment]
Ok I found the problem:
```/home/USER/.local/share/bottles/runners/vaniglia-6.18/bin/wine 'C:\`1EShProgram Files (x86)>EShEShProgram Files (x86)":1EShRAPTOR$EShEShRAPTORF2raptor.exe,raptor.exeW-VCC:\Program Files (x86)\RAPTOR\raptor.exe' test```

it is appending special characters to the path

**Comment by mirkobrombin** [comment]
Fixed using new `__getLnkData` method to scan for installed programs. Ref: https://gist.github.com/Winand/997ed38269e899eb561991a0c663fa49

**Comment by mirkobrombin** [comment]
you need to wait for release day or install latest from unstable
https://github.com/bottlesdevs/Bottles/actions/runs/1326182225
