### ISSUE TITLE
[Crash report] Python error on attempting to launch wine program

### ISSUE THREAD

**Issue by Cervoxx** [bottlesdevs/Bottles#597]
This crash report was generated by Bottles.

**Details**
Error occurs when trying to launch [raptor](https://raptor.martincarlisle.com/) from the bottles UI after manually installing [wine mono ](https://dl.winehq.org/wine/wine-mono/)6.4.0 on vangalia 6.18. 

No error occurs when trying to run the same software on vangalia 6.15 with mono 6.3.0 installed into that prefix.

* **package**: Other- AUR
* **version**: 2021.9.28-treviso

**Log**
```python3
embedded null byte  File "/usr/share/bottles/bottles/utils.py", line 295, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/runner.py", line 308, in run_command
    return subprocess.Popen(command, shell=True).communicate()

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(

```

**Comment by mirkobrombin** [comment]
already tracking here #584
