### ISSUE TITLE
[Request] Recent executable / History of last opened executables

### ISSUE THREAD

**Issue by BabaJi-0** [bottlesdevs/Bottles#611]
**Is your feature request related to a problem? Please describe.**
Maybe I am doing something wrong. But having to select same executable from the picker every time is a problem.

**Describe the solution you'd like**
Saving history.

I am using Flatpak version.
I have bad communication skills. Sorry.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/139597307-4db7d6e4-5e15-44a5-9fcb-304efab3e4ce.png)
