### ISSUE TITLE
[BUG] Bottles Becomes Unresponsive In First Launch Wizard clicking hyperlink

### ISSUE THREAD

**Issue by ThisNekoGuy** [bottlesdevs/Bottles#617]
**Describe the bug**
Bottles becomes unresponsive when clicking the hyperlink in the "we are almost there" window in the first time setup wizard.

**Installation**
 - Method: AUR
 - Version: 2021.9.28-1

**To Reproduce**
1. Launch Bottles for the first time
2. Click next (Welcome window)
3. Click next (Runner info window)
4. At the "We're almost there" window, click the hyperlink that says "Read more about what we're going to download"
5. Bottles becomes unresponsive

**Expected behavior**
Bottles should have opened the hyperlink in my default web browser

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling release

**Additional context**
N/A

**Comment by mirkobrombin** [comment]
After some investigation I have come to the conclusion that it is system related and we cannot fix it in ours. Make sure the xdg portals are installed and refer to your distribution's documentation / support.

I close the issue but feel free to add comments.
