### ISSUE TITLE
[BUG] Can't draw window 

### ISSUE THREAD

**Issue by modzilla99** [bottlesdevs/Bottles#623]
**Describe the bug**
Wine windows can't be drawn. Worked till yesterday, now it stopped working for some reason. About Dialogue opens like normal. Only wine windows seem to be affected.

**Installation**
 - Method: Flatpak
 - Version: 2021.10.14-treviso
 - Distro: Fedora 34 GNOME + Wayland

**To Reproduce**
1. Try to open anything in a bottle (like winecfg or cmd)

**Expected behavior**
Winecfg should open or at least give me an error message.

**Screenshots**
Not applicable, nothing happens. Nothing to screenshot

**Logs**

Starting the flatpak from bash with verbose flag results in the following logs:
<details>
  <summary>Logs</summary>

    F: No installations directory in /etc/flatpak/installations.d. Skipping
    F: Opening system flatpak installation at path /var/lib/flatpak
    F: Opening user flatpak installation at path /home/justin/.local/share/flatpak
    F: Opening user flatpak installation at path /home/justin/.local/share/flatpak
    F: Opening system flatpak installation at path /var/lib/flatpak
    F: Opening user flatpak installation at path /home/justin/.local/share/flatpak
    F: Opening system flatpak installation at path /var/lib/flatpak
    F: Cleaning up unused container id 1717638490
    F: Cleaning up unused container id 3957019593
    F: Allocated instance id 1637727715
    F: Add defaults in dir /com/usebottles/bottles/
    F: Add locks in dir /com/usebottles/bottles/
    F: Allowing wayland access
    F: Allowing pulseaudio access
    F: Pulseaudio user configuration file '/home/justin/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/justin/.config/pulse/client.conf«: Datei oder Verzeichnis nicht gefunden
    F: Running 'bwrap --args 40 xdg-dbus-proxy --args=43'
    F: Running 'bwrap --args 40 bottles'
    2021-10-14 14:16:09 INFO: Dxvk found: [dxvk-1.9.2]
    2021-10-14 14:16:09 INFO: Vkd3d found: [vkd3d-v2.4]
    2021-10-14 14:16:09 INFO: Runners found: [vaniglia-6.18]
    2021-10-14 14:16:10 INFO: Bottles found: Cisco-Jabber
    2021-10-14 14:16:10 INFO: Flaschen gestartet!
    TypeError: Must be number, not NoneType
    2021-10-14 14:16:15 INFO: Setting Key: [sync] to [wine] for bottle: [Cisco Jabber] …
    (bottles:2): Handy-CRITICAL **: 14:16:15.809: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
    2021-10-14 14:16:32 INFO: Running winecfg on the wineprefix …
    2021-10-14 14:16:32 INFO: Using Xwayland..
    002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
    00ac:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    00ac:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    00ac:err:systray:initialize_systray Could not create tray window
    00f4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    00f4:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    2021-10-14 14:16:51 INFO: Running a Control Panel on the wineprefix …
    2021-10-14 14:16:51 INFO: Using Xwayland..
    002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
    00ac:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    00ac:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    00ac:err:systray:initialize_systray Could not create tray window
    00ec:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    00ec:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    2021-10-14 14:17:08 INFO: Opening the file manager in the path …
    2021-10-14 14:17:13 INFO: Running a CMD on the wineprefix …
    2021-10-14 14:17:13 INFO: Using Xwayland..
    0110:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0110:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    
    (bottles:2): Handy-CRITICAL **: 14:17:42.585: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
    2021-10-14 14:17:44 INFO: Running an executable on the bottle …
    2021-10-14 14:17:44 INFO: Using Xwayland..
    0130:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
    0130:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
    0130:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
    0154:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0154:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    [1014/141744.982:ERROR:network_change_notifier_win.cc(146)] WSALookupServiceBegin failed with: 0
    wine: Unhandled exception 0x80000003 in thread 154 at address 034CCA18 (thread 0154), starting debugger...
    018c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    018c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    018c:err:systray:initialize_systray Could not create tray window
    0184:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0184:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    2021-10-14 14:17:51 INFO: Sending Status: [reboot] to the wineprefix …
    2021-10-14 14:17:51 INFO: Using Xwayland..
    2021-10-14 14:18:12 INFO: Running a debug console on the wineprefix …
    2021-10-14 14:18:12 INFO: Using Xwayland..
    01d8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    01d8:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    2021-10-14 14:18:24 INFO: Running an executable on the bottle …
    2021-10-14 14:18:24 INFO: Using Xwayland..
    0200:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
    0200:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
    0200:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
    0224:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0224:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    [1014/141825.068:ERROR:network_change_notifier_win.cc(146)] WSALookupServiceBegin failed with: 0
    wine: Unhandled exception 0x80000003 in thread 224 at address 034CCA18 (thread 0224), starting debugger...
    025c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    025c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    025c:err:systray:initialize_systray Could not create tray window
    0254:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0254:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

</detail>

**Comment by mirkobrombin** [comment]
It looks like you are using wayland but cannot find the display for xwayland. Strange because we haven't changed anything about it.

Can you try xorg to see if that is actually the problem?
