### ISSUE TITLE
[BUG] Ubisoft Connect API Error

### ISSUE THREAD

**Issue by ACertainTopfi** [bottlesdevs/Bottles#624]
**Describe the bug**
Same issue as mentioned here: https://github.com/bottlesdevs/Bottles/issues/562#issuecomment-926363763
After installing Ubisoft Connect, both via UbisoftConnectInstaller.exe or the experimental Installer feature, the application cannot be started, showcasing an API error (Error at hooking API "LdrFindResource_U"). This error does not happen when using Proton via the "Add a non Steam Game" function inside Steam, nor has it happened on 2021.9.28-treviso.

**Installation**
 - Method: Flatpak
 - Version 2021.10.14-treviso-1

**To Reproduce**
1. Create new bottle based on a runner of your choice
2. Go to Installers (or install UbisoftConnetInstaller.exe diretly)
3. Click on the "Install Uplay" button
4. Try starting Uplay after installation has finished
5. Error

**Expected behavior**
Ubisoft Connect should be able to launch as expected and as seen when installing it via Steams "Add a non Steam Game" function or previous versions of Bottles such as 2021.9.28-treviso.

**Screenshots**
![Bildschirmfoto von 2021-10-14 19-16-11](https://user-images.githubusercontent.com/79299376/137374275-d9bb8b5e-b80d-4dd2-99cf-9423eb9a566f.png)

![Bildschirmfoto von 2021-10-14 20-29-04](https://user-images.githubusercontent.com/79299376/137375346-200577d7-0cf9-44f2-afb3-37c71a2dc752.png)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 35

**Additional context**
Of note is that the issue was found by another user on 2021.9.14-treviso, yet was not present on 2021.9.28-treviso. I was able to install and launch Ubisoft Connect via the experimental Installer feature on release 2021.9.28-treviso, where all core features of Ubisoft Connect worked as expected.

Despite the manifest not being changed between versions, I tried manually adding both different versions of dotnet and vcredists via the dependency tab, though that did not make a difference. The same goes for trying a few launch options.

Furthermore, the error is reproducible on other runners such as lutris-6.14-4 and Proton-6.19-GE-2 when using Bottles.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/137382891-b9f68a1e-f35c-4def-96a8-7952bce08b95.png)

Ok I managed to reproduce :D

**Comment by mirkobrombin** [comment]
Not able to reproduce in 2022.3.14-3
