### ISSUE TITLE
[BUG] cannot run executable from 2021.10.14

### ISSUE THREAD

**Issue by saaditory** [bottlesdevs/Bottles#625]
**Describe the bug**
All the bottles that were working previously have stopped working now. Clicking on play button next to an app or launching an .exe/.msi file does not do anything.

**Installation**
 - Method: Flatpak
 - Version 2021.10.14

**To Reproduce**
Nothing launches..

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 34

**Comment by mirkobrombin** [comment]
> Yes, I am using Wayland.
> 
> And Thanks, It works now. I appreciate the work behind this wonderful client.

Thanks :D
