### ISSUE TITLE
[Crash report]  'str' object has no attribut

### ISSUE THREAD

**Issue by BBBright** [bottlesdevs/Bottles#632]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.10.14-treviso

**Log**
```python3
'str' object has no attribute 'items'  File "/usr/share/bottles/bottles/utils.py", line 296, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/runner.py", line 226, in run_command
    for env_var in parameters["environment_variables"].items():

```

**Comment by mirkobrombin** [comment]
Can you try with a new bottle to see if it is broken on start?

**Comment by BBBright** [comment]
Yes, new 32-bit bottles work fine. Thanks. Any idea what is forcing WINEARCH to win64 when I try to run programs in my old 32-bit bottle?

**Comment by mirkobrombin** [comment]
> Never mind, I figured it out. bottle.yml in the old 32-bit bottle (which was imported from a Play On Linux installation) had "Arch: win64". The problem didn't show up before because I had "WINEARCH=win32" set in Preferences > Environment variables, which was evidently overriding the win64 specification in the .yml.

This make sense ahahah
