### ISSUE TITLE
[BUG] xfce4-terminal: Unknown option "-c"

### ISSUE THREAD

**Issue by Roze061** [bottlesdevs/Bottles#669]
**Describe the bug**
if Run Command line inside Bottles, Command line doesn't open.
```python3
2021-10-28 06:19:00 INFO: Running a CMD on the wineprefix …
xfce4-terminal: Unknown option "-c"
```
```
xfce4-terminal 0.8.10 (Xfce 4.16)

Copyright (c) 2003-2020
	The Xfce development team. All rights reserved.

Written by Benedikt Meurer <benny@xfce.org>,
Nick Schermer <nick@xfce.org>
and Igor Zakharov <f2404@yandex.ru>.

Please report bugs to <https://gitlab.xfce.org/apps/xfce4-terminal/>.
```

**Installation**
 - Method: other
 - Version 2021.10.28-treviso

**To Reproduce**
1. Go to 'Bottle details'
2. Click on 'Command Line'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Version [e.g. 33]
 - Kernel: 5.14.11-arch1-1
 - Display server: Xorg

**Additional context**

#645

https://github.com/bottlesdevs/Bottles/blob/ff058cb57377c417f377bb6b1a84847f838940d0/src/utils.py#L115

**[Request] set prefered Terminal**

**Comment by mirkobrombin** [comment]
> ```shell
> $ xterm -e bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'
> ```
> 
> I not See error
> 
> ```shell
> $ lxterminal -e bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'
> ```
> 
> Same, I not see error
> 
> ```shell
> $ xfce4-terminal -e bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'
> xfce4-terminal: Unknown option "-c"
> 
> $ xfce4-terminal --command bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'  
> xfce4-terminal: Unknown option "-c"
> 
> $ python3 -c "import subprocess; t = [\"xfce4-terminal\", \"-e %s\"]; var = ' '.join(t) % f\"bash -c \'echo t; sleep 9\'\"; print(var); subprocess.Popen(var, shell=True, stdout=subprocess.PIPE).communicate()[0].decode(\"utf-8\")"       
> xfce4-terminal -e bash -c 'echo t; sleep 9'
> xfce4-terminal: Unknown option "-c"
> ```
> 
> xfce4-terminal: Unknown option "-c"
> 
> ```shell
> $ xfce4-terminal -e "bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'"                                                                      
> Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
> 
> $ xfce4-terminal --command "bash -c 'for n in {1..30}; do echo -n .; sleep 0.1; done'"
> Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
> 
> $ python3 -c "import subprocess; t = [\"xfce4-terminal\", \"-e %s\"]; var = ' '.join(t) % f\"\\\"bash -c \'echo t; sleep 9\'\\\"\"; print(var); subprocess.Popen(var, shell=True, stdout=subprocess.PIPE).communicate()[0].decode(\"utf-8\")"
> xfce4-terminal -e "bash -c 'echo t; sleep 9'"
> Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
> ```
> 
> If I run from LXDE LXTerminal, work same like XTerm and LXTerminal but have "SESSION_MANAGER"
> 
> EDIT: mirkobrombin do You have XTerm?

Nope. Regarding the problem with `SESSION_MANAGER`, it could be caused by the new way we manage the environment, that is by creating a copy where the variables necessary for the bottle in use are injected. So if `SESSION_MANAGER` is not in the current user environment, therefore it will not be present in the copy either.
