### ISSUE TITLE
Add UWP/WinRT support.

### ISSUE THREAD

**Issue by chiddekel** [bottlesdevs/Bottles#672]
Add UWP/WinRT support 
![UWP/WinRT](https://i.stack.imgur.com/s3FZi.pngl)

**Comment by Martinligabue** [comment]
they plan to add Linux support(???) (I do not know what I am reading, but it seems cool) https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#prioritization

they made it work, but I'm not sure it's easy to add an app https://ian.bebbs.co.uk/posts/UnoLinux

**Comment by mirkobrombin** [comment]
> they plan to add Linux support(???) (I do not know what I am reading, but it seems cool) https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#prioritization
> 
> they made it work, but I'm not sure it's easy to add an app https://ian.bebbs.co.uk/posts/UnoLinux

Microsoft is migrating a large number of applications to .NET Standards which is Linux compatible.

**Comment by mirkobrombin** [comment]
Moving this task to the 2021.11.28 project

**Comment by AlphaCraft9658** [comment]
What happened with this?

**Comment by nightfullstar** [comment]
This is not directly relevant to Bottles as it is more of a GUI solution, it seems. Relevant discussion going on in winetricks; https://github.com/Winetricks/winetricks/issues/2225
