### ISSUE TITLE
[Crash report]  'Music'  

### ISSUE THREAD

**Issue by she11sh0cked** [bottlesdevs/Bottles#676]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.10.28-treviso

**Log**
```python3
'Music'  File "/usr/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

Note: 'Music' was a bottle that i deleted

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by she11sh0cked** [comment]
Wow that was fast!

**Comment by mirkobrombin** [comment]
> Wow that was fast!

I hope it works 👀. We'll find out on the next release hahaha.
