### ISSUE TITLE
[BUG] C++ runtime error (wine)

### ISSUE THREAD

**Issue by she11sh0cked** [bottlesdevs/Bottles#677]
**Describe the bug**
Application runs into a C++ runtime error, but only if started via the bottles programs section. Runs fine if started via command line.

**Installation**
 - Method: AUR (bottles-git)
 - Version 2021.10.28-treviso

**To Reproduce**
Steps to reproduce the bad:
1. Install "[Ableton Live 11 Suite](https://cdn-downloads.ableton.com/channels/11.0.11/ableton_live_trial_11.0.11_64.zip)"
2. Go to "Programs"
3. Run "Ableton Live 11 Suite"

Steps to reproduce the good:
1. Go to Utilities
2. Run "Command Line"
3. `cd "C:/ProgramData/Ableton/Live 11 Suite/Program"`
4. `start "" "Ableton Live 11 Suite.exe"`

**Screenshots**
![image](https://user-images.githubusercontent.com/22623152/139537623-b6196874-52db-4da3-9155-9a88a2d0cbe3.png)

**Desktop:**
 - OS: Manjaro Linux
 - Version: 21.1.6
 - Display server: Xorg

**Additional context**
[backtrace.txt](https://github.com/bottlesdevs/Bottles/files/7446928/backtrace.txt)

**Comment by mirkobrombin** [comment]
I think there is a compatibility problem with Wine. Ik Ableton works generally out of the box under Wine but what is crashing here is not Bottles but Wine runtime itself. I need to reproduce and investigate, thanks for reporting.

**Comment by mirkobrombin** [comment]
I'm not able to replicate. I'm moving this task to 2021.11.28 project, feel free to add more details.

**Comment by mirkobrombin** [comment]
Closing as I'm not able to replicate. Feel free to add more details.
