### ISSUE TITLE
[Crash report]  'test'  

### ISSUE THREAD

**Issue by JUNUX1** [bottlesdevs/Bottles#683]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.10.28-treviso

**Log**
```python3
'test'  File "/usr/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

**Comment by mirkobrombin** [comment]
Duplicate of https://github.com/bottlesdevs/Bottles/issues/676

**Comment by JUNUX1** [comment]
Well nothing important happening actually and everything is working perfectly.
I just wanted to help by reporting the issue.
Good job

**Comment by mirkobrombin** [comment]
> Well nothing important happening actually and everything is working perfectly. I just wanted to help by reporting the issue. Good job

Thanks for reporting 🖖😅
