### ISSUE TITLE
[Request] Passing arguments into bottled applications

### ISSUE THREAD

**Issue by Rerumu** [bottlesdevs/Bottles#686]
I find it impossible to launch command line programs or programs that expect some input (ex. from an URI handler) in a bottle.

An argument like `--arguments STRING` or similar to allow for passing arguments directly into the program invoked through the Bottles command line would solve the issue.

Ex.
```
bottles --bottle MyBottle --lnk LnkPath --arguments "-a b -c d"
```

**Comment by mirkobrombin** [comment]
fixed by #687
