### ISSUE TITLE
[BUG] Header of Settings squashed

### ISSUE THREAD

**Issue by Justinzobel** [bottlesdevs/Bottles#693]
![image](https://user-images.githubusercontent.com/1370117/140595321-349e5979-911c-4a9a-a7d4-0a92151f5a35.png)

**Describe the bug**
Image show issue clearly

**Installation**
 - Method: Meson build
 - Version 2021.10.28-treviso

**To Reproduce**
1. Compile from source
2. Run
3. Open Settings

**Expected behavior**
Header bar not squashed

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Is that the breeze theme? I don't try Bottles with all themes but will create a VM to test as soon as I can. In the meantime, can you try to edit Bottles' breeze.css file to try and fix it yourself?

**Comment by Justinzobel** [comment]
Looks like these changes fix it, I figured I'd just disable the breeze check and it displays OK:

```
diff --git a/src/main.py b/src/main.py
index e8cd4da..db9b100 100644
--- a/src/main.py
+++ b/src/main.py
@@ -197,11 +197,11 @@ class Bottles(Gtk.Application):
                 path="/com/usebottles/bottles/yaru.css",
                 lookup_flags=0
             )
-        elif "Breeze" in user_theme:
-            css_res = Gio.resources_lookup_data(
-                path="/com/usebottles/bottles/breeze.css",
-                lookup_flags=0
-            )
+#        elif "Breeze" in user_theme:
+#            css_res = Gio.resources_lookup_data(
+#                path="/com/usebottles/bottles/breeze.css",
+#                lookup_flags=0
+#            )
         elif "io.elementary.stylesheet" in user_theme:
             css_res = Gio.resources_lookup_data(
```

**Comment by mirkobrombin** [comment]
Oh fine, maybe breeze is now compatible with libhandy components
