### ISSUE TITLE
[BUG] Missing 'patoolib' in latest AUR release

### ISSUE THREAD

**Issue by she11sh0cked** [bottlesdevs/Bottles#695]
**Describe the bug**
Seems to be missing a python module? Works after I `pip install patool`.

**Installation**
 - Method: AUR (bottles-git)
 - Version 1:r2004.23f18ef-1

**To Reproduce**
1. Run `bottles` in bash

**Expected behavior**
Should install the dependency.

**Desktop:**
    OS: Manjaro Linux
    Version: 21.1.6
    Display server: Xorg

**Comment by mirkobrombin** [comment]
@francescomasala

**Comment by mirkobrombin** [comment]
Oh I only notice now that you are talking about bottles-git and not bottles. That package is not maintained by us, please report it directly to the AUR.

**Comment by tomek-szczesny** [comment]
This has just happened again, and affects "bottles" AUR package.
