### ISSUE TITLE
[Request] Language Settings

### ISSUE THREAD

**Issue by Yaksinikos** [bottlesdevs/Bottles#708]
**Is your feature request related to a problem? Please describe.**
The deal is to let the user decide what language of those 5 speaking to use for an program.

**Describe the solution you'd like**
Settings entry to choose the program's language.

**Describe alternatives you've considered**
As a fallback language could be used the systems default one.

**Comment by jannuary** [comment]
What's the use case for having the app's language ≠ system language?

**Comment by Translator5** [comment]
E.g. my personal case, where the main pc is german, but for the parents I would like to let them some tools in russian.

Also there is the case, when the primary translation to your system language is not properly done/finished, so you would like to use a other language you can manually choose from.

Moreover, this is a general linux distros & apps issue, where you may use primary english, but some cases (e.g. the grandparents come along and you would like to let them read some texts from within a app - e.g. astrology generated text's) you cant simply change a app's language to e.g. chinese.

**Comment by mirkobrombin** [comment]
Thank you for the explanation. We will try to implement it asap.

**Comment by MrQuerter** [comment]
Sorry for bumping but I can't find that option so I guess it wasn't added.

Bottles is having my polish language set but I would like to change it to original English since it's better to find solutions and make bug reports (no need to translate it correctly yourself or search the internet for screens) if it's in that language since most people have that.

**Comment by mirkobrombin** [comment]
In the meantime you can start Bottles by setting the locale using env var

**Comment by Fi0lek** [comment]
Like @MrQuerter, I also use Polish, but in most applications I prefer to use the English version.
For example, like @MrQuerter to search for solutions on the Internet.

Pozdro.

**Comment by Doomsdayrs** [comment]
This is important for asian games and programs, where it is useful to specify locale

**Comment by mirkobrombin** [comment]
We already implemented this feature (Language section under System). 

Report missing language codes.

**Comment by Yaksinikos** [comment]
Actually I spoke about the Bottles-UI not only the wine-instances (bottles itself) ... 😆

**Comment by mirkobrombin** [comment]
So forcing a different system-lang in Bottles?

**Comment by silriozs** [comment]
> We already implemented this feature (Language section under System).
> 
> Report missing language codes.

Need following languages:
`ja_JP`  Japanese
`zh_TW`  Chinese (Traditional)
`ko_KR`  Korean

It would be better if user can edit the language list from UI or some config files instead of hardcoding the language options.

**Comment by xrishox** [comment]
Which variable are you modifying when it comes to locale in bottles? I know that for a lot of visual novels LANG isn't enough and it actually requires LC_ALL

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/Bottles/blob/475dec5d3eb3d4212412312c2d6188459b7f07fb/bottles/backend/wine/winecommand.py#L170

**Comment by jianlins** [comment]
Is it implemented? How can I configure it in GUI?
