### ISSUE TITLE
[Request]  Support for `wine-wayland`

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#710]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to run our games natively on Wayland

**Describe the solution you'd like**
It would be nice if Bottles can provide https://github.com/varmd/wine-wayland/ as a runner

**Comment by mirkobrombin** [comment]
I was already trying to bring it to Bottles but I found some complications and I ran out of time. I'll try again for the November 28th release

**Comment by VarLad** [comment]
@mirkobrombin Thanks a lot! :smile: 
Nice to know its being considered by the devs

**Comment by VarLad** [comment]
The next release is next week
Just wanted to ask, does getting `wine-wayland` in that release look feasible as of yet?

**Comment by mirkobrombin** [comment]
I am still testing, I don't know if I will be able to provide it on the 28th

**Comment by mirkobrombin** [comment]
Patoolib (the library we use to unpack) doesn't seem to support zstd, the format used by wine-wayland for the archive. Unfortunately, this is a blockage at the moment and we need to consider an alternative implementation.

**Comment by VarLad** [comment]
@mirkobrombin Just read this

I think Wine will support wayland in one of its near future releases. I also hear that the wine wayland in the repo I linked is a hack. 
I'll be closing this issue for now, and will wait for Wine to release the Wayland support soon. Reference: https://www.phoronix.com/scan.php?page=news_item&px=Wayland-Wine-End-Of-2021

**Comment by mirkobrombin** [comment]
> @mirkobrombin Just read this
> 
> I think Wine will support wayland in one of its near future releases. I also hear that the wine wayland in the repo I linked is a hack. I'll be closing this issue for now, and will wait for Wine to release the Wayland support soon. Reference: https://www.phoronix.com/scan.php?page=news_item&px=Wayland-Wine-End-Of-2021

This would make things easier for me a lot
