### ISSUE TITLE
[BUG] Enable DLSS (DXVK-NVAPI) causes crashing. Missing file?

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#720]
When the "Enable DLSS (DXVK-NVAPI)" preference is enabled, after each close of Bottles and re-open a window is shown that says a crash has occurred.

Flatpak 2021.11.14-treviso-1 on Arch Linux using X11.

Steps to reproduce:
1) Create a bottle
2) Enable the preference "Enable DLSS (DXVK-NVAPI)"
3) Close Bottles
4) Reopen Bottles

A window pops up saying Bottles crashed the last time with the following info:

[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/nvapi//x32/nvapi.dll' File "/app/share/bottles/bottles/utils.py", line 317, in __target
result = self.task_func(*args, **kwargs)

File "/app/share/bottles/bottles/backend/manager.py", line 1396, in install_nvapi
shutil.copy(f"{nvapi_path}/{dll}/{dll_file}", inst_path)

File "/usr/lib/python3.9/shutil.py", line 426, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)

File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

**Comment by mirkobrombin** [comment]
Check from Bottles preferences if NVAPI is installed

![image](https://user-images.githubusercontent.com/9479903/141793043-e8e6fa03-eb1c-45af-94ae-a08b4b587b5d.png)

**Comment by Githob2021** [comment]
> Something is blocking your connection to the server repository. I'm using the Flatpak too. Can you try to start Bottles trough the terminal to see the output when in preferences?

Thanks, my firewall was blocking those downloads. It looks good now. So the crashing does not happen with that component installed.

I guess the bug for this could be reworded to instead either
1) not be able to enable that setting if the component is missing so the crash is avoided
2) If the component is enabled, do a graceful fail and the message should say "you need to download the component from preferences"

**Comment by mirkobrombin** [comment]
Should be handled some commits ago now
