### ISSUE TITLE
Cannot locate Ableton Live 11 cab files

### ISSUE THREAD

**Issue by skandals** [bottlesdevs/Bottles#723]
**Describe the bug**
When I try to install Ableton Live 11 Suite.exe, when it starts to install it pops up a window to locate a .cab file but when I try to look for it, it does not appear even the folder where the .cab files should be does not appear.It's just blank.

**Installation**
 - Method: 2021.11.14-treviso-2
 - Version  2021.11.14

**To Reproduce**
1. Go to 'Home/Documents/Software/Ableton'
2. Click on 'Ableton Live Suite.exe'
3. Bottles pops up and Select Bottle to install Ableton.
4. Ableton installation window pops up and click Install
5.Try to locate .cab files but try to select the Ableton Live Suite.exe
6. See error

**Expected behavior**
I expected to see the .cab files and locate them so that Ableton can continue installing. Those .cab files are the installer data for Ableton.

**Screenshots**

![Screenshot from 2021-11-16 12-41-33](https://user-images.githubusercontent.com/93284428/141971989-a0c5cb53-b88a-4f6e-8784-b021ecd240ed.p
![Screenshot from 2021-11-16 12-41-49](https://user-images.githubusercontent.com/93284428/141971996-9907c9c5-647a-48c5-ad57-ed6c78b56fee.png)
ng)
![Screenshot from 2021-11-16 12-40-15](https://user-images.githubusercontent.com/93284428/141971952-ff5d41ce-232e-437d-b482-c3357394ff96.png)

**Desktop (please complete the following information):**
 - OS: Zorin OS Pro
 - Version : 16
 - Display server: Xorg

**Comment by skandals** [comment]
![Screenshot from 2021-11-16 12-41-33](https://user-images.githubusercontent.com/93284428/141975075-5678e7ad-c8c9-4df4-af17-2aadc511233c.png)

I tried looking for them but I cant find the .cab files

**Comment by mirkobrombin** [comment]
Where should be located? (No experience with Ableton)

**Comment by skandals** [comment]
The Ableton exe and the cab files file should be located at the *Home* folder but they do not appear.

**Comment by mirkobrombin** [comment]
Are you on Flatpak? If so, it is fully-sandboxed and has no access to your homedir. You should place files inside the bottle or extend Bottles permissions https://docs.usebottles.com/flatpak/expose-directories

Also, latest release is 2021.11.14-treviso-3, can you please upgrade?

**Comment by skandals** [comment]
I think so, I saw a folder named Flatpak, I don't know much i'm new to using Linux. Let me try I will let you know if it works.

Okay I will upgrade.

**Comment by skandals** [comment]
Thank you 😃 it works now!

**Comment by mirkobrombin** [comment]
> Thank you smiley it works now!

I'm happy :D
