### ISSUE TITLE
[BUG] APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2

### ISSUE THREAD

**Issue by pushqrdx** [bottlesdevs/Bottles#724]
**Describe the bug**
`APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2` on startup

**Installation**
 - Method: Appimage
 - Version latest

**To Reproduce**
1. Run

**Desktop (please complete the following information):**
 - OS: debian
 - Version sid
 - Display server: Xorg
 
**Additional context**
The first time i tried to run the AppImage it threw that warning but also errored out and refused to start, second time i ran it, Bottle started but still threw that warning, It also takes very long time before showing gui, i wonder if that's related

**Comment by mirkobrombin** [comment]
Related: #726 (actually what I say about libs).
