### ISSUE TITLE
[BUG] wine: not found

### ISSUE THREAD

**Issue by pushqrdx** [bottlesdevs/Bottles#726]
**Describe the bug**
Bottles doesn't seem to be able to create a wine prefix, it throws `/bin/sh: 1: /home/pushqrdx/.local/share/bottles/runners/vaniglia-6.21/bin/wine: not found` and doesn't stop or check for that, it just keeps going throwing errors because no prefix was made in the first place

**Installation**
 - Method: Appimage
 - Version: 2021.11.14-treviso-3

**To Reproduce**
1. Just try to make a bottle

**Desktop (please complete the following information):**
 - OS: debian
 - Version: sid
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Hi, the AppImage can cause that error when one or more lib is not available or configured properly. Can you try installing wine in your system or use the Flatpak?

**Comment by pushqrdx** [comment]
@mirkobrombin i can manually run vaniglia so idk why isn't bottles able to, there's no missing libraries because vaniglia runs just fine on its own

**Comment by mirkobrombin** [comment]
> @mirkobrombin i can manually run vaniglia so idk why isn't bottles able to, there're no missing libraries because vaniglia runs just fine on its own

Because the AppImage is not just a folder with some files. It still needs some libraries and sometimes there is no guarantee that these will be found even if they are actually provided by the system.


> @mirkobrombin i can manually run vaniglia so idk why isn't bottles able to, there're no missing libraries because vaniglia runs just fine on its own. Also note that there's no `/lib/ld-linux.so.2` on debian, the dynamic linker is under `/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2`

Maybe this cause the problem. Can you try to launch the AppImage with the `LD_LIBRARY_PATH` env set properly?

**Comment by pushqrdx** [comment]
@mirkobrombin pretty sure that the problems are caused by looking for `/lib/ld-linux.so.2` which doesn't exist on debian, i don't think this is something that can be fixed by LD_LIBRARY_PATH as the linker isn't named `ld-linux.so.2` but `ld-linux-x86-64.so.2`, i tried creating a symlink, while that made the warning go away, still bottles couldn't run vaniglia, it appears that vaniglia itself has `/lib/ld-linux.so.2` hardcoded in it

**Comment by mirkobrombin** [comment]
> @mirkobrombin pretty sure that the problems are caused by looking for `/lib/ld-linux.so.2` which doesn't exist on debian, i don't think this is something that can be fixed by LD_LIBRARY_PATH as the linker isn't named `ld-linux.so.2` but `ld-linux-x86-64.so.2`, i tried creating a symlink, while that made the warning go away, still bottles couldn't run vaniglia,

The only way for me is to try to install Debian and reproduce because on Silverblue (pc) and Ubuntu, eos, arch (VM) the AppImage works.

**Comment by pushqrdx** [comment]
In order to get `/lib/ld-linux.so.2` i needed to add i386 arch to debian (sudo the following)
```
dpkg --add-architecture i386
apt update
apt install libc6-i386 libx11-6:i386 libxext6:i386 libfreetype6:i386
```
this stopped the dynamic linker problems because now i have a 32bit linker for wine

**Comment by mirkobrombin** [comment]
Oh good to know. Maybe I will add this to the documentation.

**Comment by pushqrdx** [comment]
@mirkobrombin yeah that would help a lot of people, i got Bottles to work correctly  on debian after adding `i386` arch and those libraries, people might also need these for graphic acceleration & proton GE. Although i think that Bottles should at least run `wine -v` and stop if it didn't get proper answer back, because now it just keeps trying to apply changes to a prefix that doesn't even exist
```
libfaudio0:i386 libpcap0.8:i386 libstb0:i386 libvkd3d1:i386 libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386
```

**Comment by mirkobrombin** [comment]
> @mirkobrombin yeah that would help a lot of people, i got Bottles to work correctly on debian after adding `i386` arch and those libraries, people might also need these for graphic acceleration & proton GE.
> 
> ```
> libfaudio0:i386 libpcap0.8:i386 libstb0:i386 libvkd3d1:i386 libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386
> ```
> 

Thanks!

> Although i think that Bottles should at least run `wine -v` and stop if it didn't get proper answer back, because now it just keeps trying to apply changes to a prefix that doesn't even exist

working on.

**Comment by mirkobrombin** [comment]
Tracking on 2021.12.14 project.
