### ISSUE TITLE
Program links missing

### ISSUE THREAD

**Issue by homerhomer** [bottlesdevs/Bottles#728]
With newer versions of Bottles it's not populating in the "Programs" section.  One of the programs I've noticed this with is StarCraft.  With Bottles 2021.9.28-treviso everything works as expected.  There are two items in Programs, "StarCraft" and "StarCrarft Campign Editor" 
With newer releases I'm missing "StarCraft" and only see "StarCrarft Campign Editor". 

The last working version that I had was "2021.9.28-treviso".  My install is a flatpak from flathub running on Majaro.  I'm able to revert to the older release and everything works again. 

Thanks for the great program

**Comment by mirkobrombin** [comment]
Good to know, I'm planning a fix for 2021.11.28

**Comment by mirkobrombin** [comment]
I think this was fixed. Some commits ago I've extended the search process to the user (wine) Desktop as the runner should place here all .lnk. Let me know after release
