### ISSUE TITLE
New Icon? 

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#73]
The current icon doesn't fit well with GNOME HIG, would you like help with redesigning it?

**Comment by mirkobrombin** [comment]
Hi, I know. Help can be useful.

**Comment by jannuary** [comment]
How's this?
![image](https://user-images.githubusercontent.com/27908024/103543947-e9a57c00-4ed1-11eb-937e-d2b11bf41b39.png)

**Comment by mirkobrombin** [comment]
Dude, you are an artist! Fantastic, I love it.

**Comment by mirkobrombin** [comment]
If I have to be critical, there is something that does not convince me about the top of the bottle from the left.

**Comment by jannuary** [comment]
Iterating on that:
![image](https://user-images.githubusercontent.com/27908024/103546096-0db68c80-4ed5-11eb-8e22-e8bb444959c4.png)

**Comment by mirkobrombin** [comment]
It looks perfect to me!

**Comment by jannuary** [comment]
Alright, gonna file an MR later.

**Comment by jimmac** [comment]
Nice one. One minor suggestion -- keep the labels having the shading of the bottle. Having them flat feels off.
