### ISSUE TITLE
[Crash report]  Cab file /home/alain/.var/app/com.us

### ISSUE THREAD

**Issue by alx76x** [bottlesdevs/Bottles#735]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.11.14-treviso-3

**Log**
```python3
Cab file /home/alain/.var/app/com.usebottles.bottles/data/bottles/temp/msxml6.msi not found
```

**Comment by mirkobrombin** [comment]
Can you provide steps to reproduce?

**Comment by alx76x** [comment]
Solved thanks

Il giorno ven 19 nov 2021 alle ore 17:18 Mirko Brombin <
***@***.***> ha scritto:
