### ISSUE TITLE
[Request] Make an Ubuntu PPA

### ISSUE THREAD

**Issue by wrestlerdude** [bottlesdevs/Bottles#740]
As the title says. I'm requesting for a PPA to be created for this project, integrated with the continuous integration to publish the newly versioned and built deb packages so my package manager apt can manage updates. This would allow me to get new updates without having to manually get them. I could of course use the flatpak from flathub but I avoid flatpaks unless absolutely necessary due to my storage size constraints. Thank you for giving up your time to read this.

**Comment by mirkobrombin** [comment]
Hi, I understand your request but there are a few points that blocks me from make it true:

1. Sadly I don't have the time to devote to it (could you do it?)
2. A repository means a new package targeted for a distribution or group of distributions, which ones should be supported? Each distribution (e.g. Debian, Ubuntu) has different package versions that may or may not work with Bottles, so it is important to understand which distribution(s) should be targeted.
3. Offering us a repository means that this is a new official method of distributing Bottles and this means that we have to put another package in the test queue for each release and therefore more time needed for each release, time than to meet the planned CalVer, we would have to remove from development.
4. I don't have a debian-based distribution installed and can't test packages.

I believe the best solution is to find who can keep the package for the specific distribution (eg Ubuntu). This person should then test the releases and adapt the package accordingly before updating the repository, taking responsibility for it.

Let me know if you can take on this responsibility or feel free to share the issue with anyone who may be interested 😀

**Comment by mirkobrombin** [comment]
Closing in lack of response. Feel free to reply.

**Comment by trymeouteh** [comment]
Would prefer a maintained Pacstall package over a PPA personally.

https://github.com/bottlesdevs/Bottles/issues/1058
