### ISSUE TITLE
[BUG] Duplicating a bottle creates a bottle much larger than the original

### ISSUE THREAD

**Issue by markochk** [bottlesdevs/Bottles#743]
**Describe the bug**
In `~/.var/app/com.usebottles.bottles/data/bottles/bottles/my-bottle/drive_c/users/me/AppData/Roaming/Microsoft/Windows/` exists a file called `Templates` that points to home directory. This file causes duplicating a bottle to create one much larger than the original.

**Installation**
 - Method: Flatpak
 - Version: 2021.11.14-treviso-4

**To Reproduce**
1. Create a new Software bottle
2. Click on 'Duplicate bottle'
3. Despite the original bottle being ~450MB, new bottle is tens of GB in size (I stopped it at 30GB, but it would've kept going).

**Expected behavior**
Duplicate bottle should be identical in size to the original bottle.

**Desktop:**
 - OS: Fedora
 - Version 35
 - Display server: Wayland

**Additional context**
Deleting the `Templates` file before duplication causes it to work properly.

**Comment by mirkobrombin** [comment]
Thanks for reporting
