### ISSUE TITLE
[BUG] window is not scrollable

### ISSUE THREAD

**Issue by MartinTwean** [bottlesdevs/Bottles#744]
**Desktop (please complete the following information):**
1. OS: Arch Linux x86_64
2. Kernel: 5.15.4-arch1-1
3. Resolution: 1920x1080
4. DE: GNOME 41.1
5. Display server: Xorg

**To Reproduce**
- Bottles 2021.11.14-treviso-3
The Bottles window is not scrollable. You can't maximize the window either. At a resolution of 1920x1080 only 17 lines are visible, the rest is cut off and cannot be used.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/94994890/143311357-6ffea77c-6970-4a74-8353-b2781c4bba2d.jpg)

**Comment by mirkobrombin** [comment]
Thanks for report, should be easy to fix
