### ISSUE TITLE
[BUG] MagicaVoxel

### ISSUE THREAD

**Issue by t1u1** [bottlesdevs/Bottles#746]
**Describe the bug**
MagicaVoxel used to work earlier in bottles, but doesn't anymore.

**Installation**
 - Method: flatpak
 - Version: 2021.11.14-treviso-4
 
 **To Reproduce**
* Create gaming bottle
* Download MagicaVoxel from https://github.com/ephtracy/ephtracy.github.io/releases/tag/0.99.6
* Run MagicaVoxel.exe
 
**Expected behavior**
The app should be visible. However all I see is a blank screen. It used to work fine earlier, about 10 months back.

When it started failing, I thought the problem will correct itself over time. I have tried everything, including deleting the bottle, uninstalling the bottles app and recreating a fresh bottle.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 -  Version 20.04 LTS
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Hi, what is the latest Bottles release that was working with MagicaVoxel?

**Comment by mirkobrombin** [comment]
Easy fix: https://docs.usebottles.com/flatpak/black-screen-or-silent-crash

**Comment by t1u1** [comment]
That worked! Thank you so much :100:
