### ISSUE TITLE
[Request] Stop using proton ge and favor wine ge instead.

### ISSUE THREAD

**Issue by Cervoxx** [bottlesdevs/Bottles#749]
Various problems are found when using proton builds outside of steam, as described here, https://github.com/lutris/lutris/pull/3330 and quoted here: 

> proton runs in a container, which uses a runtime environment and libraries specifically built for use within that container. Not running it as intended results in the container and therefore its runtime not being used, and severely breaks library compatibility. It causes wine to search for libraries on your system instead of those it was built with/intended for within proton. It may work, if enough libraries match, but it is not correct and not supportable due to library differences across distros.

It could be feasible to use https://github.com/GloriousEggroll/wine-ge-custom instead to try and get the same results.

**Comment by mirkobrombin** [comment]
Thank you for your information. I've never encountered similar problems (in Bottles) but I don't exclude it. In many cases I managed to start programs through Proton GE that did not run with other runners. The difference with Lutris is Bottles is strictly a prefix manager, so it's easy to recreate a bottle (or go back if the versioning is active) if the runner or a library breaks something.

At Bottles we offer both Proton GE and Wine GE builds but personally I've never had the opportunity to read up on both projects and I don't know what the differences are.

In addition, the runner is installed at the discretion of the user and is not provided out the box (like our Vaniglia runner), so I don't know if it's really a problem.

**Comment by mirkobrombin** [comment]
I want to stop providing Proton-GE with 2022.1.28 in favor of the already-provided Wine-GE.

**Comment by mirkobrombin** [comment]
We will keep the Proton runner as we still offer both wine-ge and proton-ge. Also, we are working looking for a way to implement and tweak steam proton prefixes directly from Bottles.
