### ISSUE TITLE
[BUG] AppImage doesn't start on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by fang64** [bottlesdevs/Bottles#756]
**Describe the bug**
The AppImage version of Bottles fails to start, dropping a stack trace on start.

**Installation**
 - Method: AppImage
 - Version: 2021.11.28

**To Reproduce**
1. Open Terminal
2. cd /tmp
3. wget https://github.com/bottlesdevs/Bottles/releases/download/2021.11.28-treviso/Bottles-2021.11.28-treviso-x86_64.AppImage
4. chmod +x ./Bottles-2021.11.28-treviso-x86_64.AppImage
5. ./Bottles-2021.11.28-treviso-x86_64.AppImage
6. See error:
``` Traceback (most recent call last):
  File "/tmp/.mount_BottlekKEmd5//usr/bin/bottles", line 50, in <module>
    import gi
  File "/tmp/.mount_BottlekKEmd5/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
```

**Expected behavior**
I expected the application to actually run.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04.3 LTS
 - Display server: Wayland
**Additional context**
N/a

**Comment by fang64** [comment]
I created PR with a possible fix, I do realize that including files might not be in-line with your rules for contribution, so I wasn't really sure if this approach was correct. 

I suspect this falls into this, but honestly AppImage Builder not pulling these, is an issue for me.
"Do not package external files and do not make changes to the code, no hard script. Obviously with the exception of files essential for packaging. Once the package is published, you can open a Pull Request to add it to the packages table above! Thanks heart!"

**Comment by mirkobrombin** [comment]
> I created PR with a possible fix, I do realize that including files might not be in-line with your rules for contribution, so I wasn't really sure if this approach was correct.
> 
> I suspect this falls into this, but honestly AppImage Builder not pulling these, is an issue for me. "Do not package external files and do not make changes to the code, no hard script. Obviously with the exception of files essential for packaging. Once the package is published, you can open a Pull Request to add it to the packages table above! Thanks heart!"

That notice refer to other contexts. I'll test your fix and then merge, thanks
