### ISSUE TITLE
[BUG] Rename the new "Task manager" to "Task Manager" for consistency

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#758]
Flatpak 2021.11.28-treviso

The new "Task manager" when in a Bottle on the side under "Programs" has a lower case m for Manager. However when you go to Details & Utilities the Windows style Task Manager label is capitalized M in Manager.

To fix: Change the label from Task manager to Task Manager. You can see a screenshot on the Bottles Twitter here: https://twitter.com/usebottles/status/1462421410492604420

**Comment by Githob2021** [comment]
I'm somewhat conflicted on this one because throughout Bottles there are cases where menu header starting letters are capitalized but not everywhere.

For example in Preferences -> General
Dark Mode <- Capitalized Mode, should it be Dark mode to match the rest?
Show update date -> Show Update Date?
Temp files -> Temp Files?
Close Bottles after starting a program -> Close Bottles After Starting a Program?
--------
In the "hamburger" menu:
Import and export -> Import and Export? (or Import & Export)?
-------
When creating a new bottle
The title says New bottle -> New Bottle?
Bottle information -> Bottle information?
The example text beside Name: "My beautiful bottle" -> My beautiful Bottle?
--------
Inside a bottle:

Under Graphics:
Use Gamemode -> Use gamemode?
Enable ACO shader compiler -> Enable ACO Shader Compiler?
Use a virtual desktop -> Use a Virtual Desktop?

Under System:
DXVK Version -> DXVK version?
..
..
..
Working directory -> Working Directory?

Under Audio:
Reduce PulseAudio latency -> Reduce PulseAudio Latency?

Under Developers & Debug:
Environment variables -> Environment Variables?
Enable wine fixme logs -> Enable WINE fixme Logs?

I guess what I am saying is I am wondering what your thoughts are for a standard (if any)
1) Should starting letters always be capitalized when correct as per the English language
2) Does it not matter?

Currently it seems like a mix of both.
-----
Lol, I must be getting annoying with all of my tickets. I really love Bottles though and even now have 3-4 more  tickets I would put in of things I like to see improve/change/potential bugs.

**Comment by mirkobrombin** [comment]
Hi, I hope I have it all figured out, I am quite worn out from work and my concentration may have been compromised.

"Bottles" refer to the program.
"bottle/bottles" refer to the wineprefix (we call them bottles because are a bit different from standard wineprefixes)

The "inconsistent use of terms" is not wanted, it is more a question of "we just didn't notice". I've added it to the project for the next release. There is no standard, we have not chosen the camel case or something. Just the WINE tools are named like their developers named them (like Task Manager, Registry Editor).

**Comment by Githob2021** [comment]
Very cool! I would actually chip in and help if I knew how to program lol. My background is a software QA tester.

I found another one too. When you hover over the "hamburger" menu on the main screen, the tool tip says "Open menu" -> Open Menu?
