### ISSUE TITLE
[BUG] I can' t remove a bottle that has already been created

### ISSUE THREAD

**Issue by vleeth** [bottlesdevs/Bottles#762]
Please don't fill issue for a Windows executable that doesn't work in Bottles. Our software is a Wine prefix manager. If a Windows application doesn't work, it could be a Wine problem (**Wine is NOT a software developed by Bottles**) or a misconfiguration of the wineprefix (take a look at WineHQ: https://www.winehq.org) or ProtonDB: https://www.protondb.com for more information on the software you are trying to run). 

We will support the installation of Windows software, only through our official installers: https://github.com/bottlesdevs/Bottles/issues/55 (when these are ready).
Please DO NOT open issues for this reason. Issues should be used to report Bugs and request New Features for Bottles.

**Describe the bug**

**Installation**
Flatpak bottles

**Desktop (please complete the following information):**
kubuntu 20.04

**Comment by mirkobrombin** [comment]
Please fill the issue body.
