### ISSUE TITLE
[Request] Additions to the Bottle display area. Pinning/Favorites, Hiding Bottles and Icons.

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#763]
I thought of additional ideas on top of different sorting methods in my other ticket; https://github.com/bottlesdevs/Bottles/issues/753. I'm not sure if this could be added to that one, or keep this one separate since it may be out of scope. Or if this one takes longer to implement/different release. Your call.

For users where they are using say 10+ bottles, it would be beneficial to have a couple visual appeasing changes:

1) Being able to pin/favorite bottles that would always be at the top. Either in a separate section or a thick bar that separates favorite and regular  bottles. If you wanted to be quirky you could call this section the "Display Case". Like how people have a shelf to display their expensive/favorite wine bottles. A use case would be a users currently played game so it's  easy to find, favorite game or common used application.

2) Being able to hide bottles that go into an expandable "Hidden Bottles" section. If you want to be quirky you could even call it "Hidden Stash" like a hidden stash of wine. Some options for this section could be only displaying when enabled in settings or by default minimized on launch unless the user expands the menu to see this section. A use case would be for games you may not want a visiting relative or friend to see while they are in your room but you want to let them play with your Bottle games. Also for those who have a lot of bottles, it would be a way to clean up the section.

3) Letting the user add a small icon inside the bottle that would be a .png or .ico and is displayed besides the bottles name. Either on the left of the name or right side. I think left would work better because the right side expands with bottle name length. This could be for example a games launch icon or application. Maybe functionality could be added where Bottles can scan inside a bottle for all available icons (like ones that are on .exe for games) like the Linux package Cuttlefish icon viewer.

4) Being able to create groups/clusters based on tags users set/create. For example they could set 3-4 games with "RPG" another "Racing", "FPS" and those would be grouped together before being sorted by A-Z, install size, etc (from ticket 753). That way games or applications are together by Genre. Non-gamers could tag all MS office stuff as "Office" and they would be grouped for example. Adobe stuff for "Creativity", etc.

I am not a graphical designer nor do a I claim to be, but I can try my best making some mock ups if you need help visualizing some of my ideas above.

Following: https://github.com/bottlesdevs/Bottles/issues/763

**Comment by mirkobrombin** [comment]
I think this will confuse the user. We are already planning to add a search bar if there are more than 5 bottles. Should it be enough?

@alvarlagerlof @jannuary

**Comment by jannuary** [comment]
Type-to-search in the bottle view makes sense to me. The features listed in the issue seem pretty niche, and I'm not sure what problems would they solve.

**Comment by alvarlagerlof** [comment]
I agree. Let's just start with search and type to search.

**Comment by mirkobrombin** [comment]
Merging with https://github.com/bottlesdevs/Bottles/issues/493
