### ISSUE TITLE
[BUG] Black border around Bottles when Alt+Tab minimized

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#764]
Bottles flatpak: 2021.11.28-trviso

I don't see this happening to all games, but this one in particular gives a thick black border around Bottles when alt+tab minimized.

**Comment by mirkobrombin** [comment]
It is more a compositor/wm/desktop/distro problem then Bottles 😅

**Comment by Githob2021** [comment]
Interesting, shouldn’t it be happening to all the different games I play? For other ones Bottles looks normal and doesn’t have the black border. I think it’s a combination of settings in this particular bottle that may be causing this, even if the issue is on the compositor/wm/desktop/distro side. Otherwise I would expect it to happen to every single game.

**Comment by mirkobrombin** [comment]
> Interesting, shouldn’t it be happening to all the different games I play? For other ones Bottles looks normal and doesn’t have the black border. I think it’s a combination of settings in this particular bottle that may be causing this, even if the issue is on the compositor/wm/desktop/distro side. Otherwise I would expect it to happen to every single game.

Each game (each software) works different. I missed the part where you say that other games doesn’t show the problem. So I think it is related to the game itself.

**Comment by Githob2021** [comment]
Thanks. I will close this ticket.
