### ISSUE TITLE
[Request] Multiple directories where bottles can be stored & read from

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#766]
Currently if a user wants to have bottles in multiple locations, they need to export and then import the bottle when needed. My proposition is Bottles being able to read bottles from multiple directories. This may be an issue for flatpak users like myself, but it should be solvable by simply adding a direct path in "Filesystems>Other Files" in flatseal. A simple guide would solve that.

Basically, the functionality would mimic Steam where you can have libraries on multiple drives.

Currently for Bottles, the default is
/home/XXXXXXXX/.var/app/com.usebottles.bottles/data/bottles/bottles/

with this new functionality we could for example add
/run/media/XXXXXXX/XXXXX/bottles/
/home/XXXXXX/Documents/bottles/
etc

Let me know if you require a better description/examples.

If this does get implemented, there will need to be safety checks put into place to avoid a different bug I am encountering in [767.](https://github.com/bottlesdevs/Bottles/issues/767)

**Comment by mirkobrombin** [comment]
I think this request is similar to https://github.com/bottlesdevs/Bottles/issues/578

**Comment by mirkobrombin** [comment]
Closing in favor of #578
