### ISSUE TITLE
[BUG] Renaming a bottle does not change the directory name which then creates conflicts and doesn't delete the correct bottle

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#767]
I had made a forum question for this, but after testing for a while I am encountering bugs. https://forums.usebottles.com/d/24-is-this-working-as-designed-renaming-bottles

When a user makes a bottle named for example ABC then renames it to ABCDEF, The name is only changed on the Bottles frontend and the directory is still "ABC". If the user then makes another ABC bottle, since ABC is now being used by ABCDEF it makes ABC_### (3 random numbers so there is no conflict). However when you then go to delete the ABC bottle, Bottles gets confused and deleted the wrong bottle!

1) Create a bottle named ABC
2) Rename it to ABCDEF
-> the directory for ABCDEF is still the original ABC
3) Create a new bottle named ABC
4) It creates a bottle directory named ABC_### (3 random numbers because the now ABCDEF is still using ABC)
5) Close bottles and reopen it
6) Attempt to delete the ABC bottle and it will delete the ABCDEF bottle because it is using that ones name in the frontend/backend but it should have deleted ABC_###
-> It creates a new bottle with undefined features because of a conflict.

Ideally when renaming a bottle in Bottles, it would change the directory in the backend as well to avoid all of this conflict.

**Comment by mirkobrombin** [comment]
This was already fixed, I think it is a regression: https://github.com/bottlesdevs/Bottles/issues/509

**Comment by Githob2021** [comment]
> This was already fixed, I think it is a regression: #509

Will this also make it so when you change a bottle name in Bottles it also changes the directory name? Or does it only solve the conflicting names when 2 bottles mistakenly use the same directory name due to a rename?

**Comment by mirkobrombin** [comment]
> > This was already fixed, I think it is a regression: #509
> 
> Will this also make it so when you change a bottle name in Bottles it also changes the directory name? Or does it only solve the conflicting names when 2 bottles mistakenly use the same directory name due to a rename?

Only solve. The directory should never be renamed, it can breaks directories, symlinks etc
