### ISSUE TITLE
[BUG] Installers doesn't fail if dependencies are not being installed

### ISSUE THREAD

**Issue by Mindus-Amitiel-Debsin** [bottlesdevs/Bottles#769]
**Describe the bug**
I installed the Epic Games Store (EGS) according to your experimental installer, and when I tried to log in to EGS using my login [EGS credentials], I had no keyboard input. I first tried using a macro on my Patriot Viper mouse to auto-fill in my eMail addy, and then tried typing manually on my laptop keyboard and then my USB keyboard. No keys were entered on any input method. The pointer did work, though.

**Installation**
 - Method: Flatpack from Pop!_OS Pop! Store.
 - Version 2021.11.28-treviso

**To Reproduce**
1. Go to Bottles
2. Click on "Epic Games Store"
3. Scroll down to "Installers" on Left
4. Click on / Install Epic Games Store. [I did this in both Software Mode and also Games Mode]
5. Click on the [Play] symbol on the newly installed Epic Games Store launcher.
6. Click on "Sign in With Epic Games"
7. Try to enter credentials with different mouse/keyboards and seeing no text in the app, only mouse movement.

**Expected behavior**
I would be able to enter my credentials to EGS as expected and continue in the application.

**Screenshots**
![Screenshot from 2021-12-08 23-50-28](https://user-images.githubusercontent.com/8101416/145355634-0469db68-e24d-45cb-9347-5cb9781b95c8.png)
![Screenshot from 2021-12-08 23-50-36](https://user-images.githubusercontent.com/8101416/145355641-0d721c1c-ed2b-4590-ba73-daa5ab4636f3.png)
![Screenshot from 2021-12-08 23-51-21](https://user-images.githubusercontent.com/8101416/145355711-78bc761d-eba5-49a7-b1b1-7b5452535421.png)

Screencast here: 

https://user-images.githubusercontent.com/8101416/145354991-eaf88cce-effc-4098-8f49-48006377f05d.mp4

Sorry for the poor quality. M$Hub wouldn't accept my .webm and I have poor experience in transcoding.

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version 21.04 nVidia version
 - Display server: XOrg... or is it Gnome 38?
**Additional context**
I run with my keyboard setup as Colemak (I highly recommend), and perhaps that is the problem. I tried using the buttons on the bottle such as "Reboot Windows" and "Shutdown Windows" but they had no interaction and I'm not sure if they did anything. I also restarted Bottles several times, but did not restart my PC. I will try that after posting and update you.

P.S., Thanks so much for your hard work! This project look awesome. Of course, my true wish is for you and [@Lutris](https://github.com/lutris) to combine to make the perfect *Nix gaming applications!!! Good luck.

**Comment by mirkobrombin** [comment]
Hi, thanks for your words 😊

Can you try installing an old version of the vaniglia runner from the preferences and set it for you bottle then try again starting unreal?

**Comment by Mindus-Amitiel-Debsin** [comment]
![Screenshot from 2021-12-09 03-27-04](https://user-images.githubusercontent.com/8101416/145388314-23b2469d-c8c2-46c8-8277-4f8985715c16.png)
I tried all of the runners that are downloaded in the above image, and I noticed that at 6.15 and below, EGS wouldn't even launch. When EGS did launch, I got into the EGS store by clicking on "Sign in later" and I was also not able to enter text in the store, either.
I'd be happy to provide any further info that you request.

**Comment by mirkobrombin** [comment]
I'll do some tests today, it is an under early development feature, maybe something is missing. For what I remember, I was able to login using Vaniglia 6.18 and fixing the input problem installing the riched20 dependency, that should already be provided by the installer

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/145391587-7361db77-8ca1-4ec6-b043-73ae7d1d6048.png)
Neverming, I'm able to type on it also using Vaniglia 6.20+, just install the `allfonts` dependency from the dependencies manager. I'm going to update the epic manifest adding the missing dependency to fix the problem.

**Comment by Mindus-Amitiel-Debsin** [comment]
![Screenshot from 2021-12-09 03-59-45](https://user-images.githubusercontent.com/8101416/145392673-65746883-1fa6-4334-9d08-9b7f36270b28.png)
I can confirm that after installing allfonts, the EGS worked! Thanks for your assistance. Do you need any logs or other info from my PC to discover why the installer didn't install allfonts by itself?

**Comment by mirkobrombin** [comment]
Update: I figured out what is causing `allfonts` to not be installed. There was a broken dependency that was failing the dependencies installation. I've fixed now and should works. I'm renaming this issue to "Installers doesn't fail if dependencies are not installed"

**Comment by mirkobrombin** [comment]
> ![Screenshot from 2021-12-09 03-59-45](https://user-images.githubusercontent.com/8101416/145392673-65746883-1fa6-4334-9d08-9b7f36270b28.png) I can confirm that after installing allfonts, the EGS worked! Thanks for your assistance. Do you need any logs or other info from my PC to discover why the installer didn't install allfonts by itself?

PS. regarding the Notifications glitch, disable them on epic settings, I'll automate it in the future

**Comment by mirkobrombin** [comment]
Re-opening as the main problem is not fixed, Installers keep saying that the installation was fine except a dependency fails the installation
