### ISSUE TITLE
UI Refresh

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#77]
Would you be interested in implementing a UI redesign that cleans up the layout and integrates modern GNOME design patterns?
You can see my mockup with comments [here.]( https://www.figma.com/file/2o1rKcFToABvzJFcxyy2v3/Bottles-Refresh?node-id=0%3A1)
![Frame 4](https://user-images.githubusercontent.com/27908024/103764895-e4ba0700-504e-11eb-8c2a-36f0be6659e8.png)

**Comment by mirkobrombin** [comment]
Beautiful mockup! First of all, thanks, you are bringing a breath of fresh air to this project.
Bottles 2 is a very young project at the moment and we have a lot of features in development but I want to make your mockup a reality.

**Comment by mirkobrombin** [comment]
Beautiful mockup! First of all, thanks, you are bringing a breath of fresh air to this project.
Bottles 2 is a very young project at the moment and we have a lot of features in development but I want to make your mockup a reality.

Some details of your concept bring to light some of the features that we want to integrate in the near future:
- download progress (which is part of the new download manager under development)
- bottle rename
- program icons (and a better integration with these)

If you want to contribute even more we can keep this issue open and collaborate in the redesign of Bottles (v3?) Until the achievement of a perfect UI and a bundle of features fully developed to make it a reality.

## A few small notes
- How could the missing buttons for "arguments and find help" be redesigned in the program list?
- Is removing quick operations from the bottle list a deliberate thing? Do you think it can be quick enough to reach on the bottle details page?

**Comment by mirkobrombin** [comment]
Also the widgets you show in the concept are present in `libhandy`. This should become a Bottles dependency once the new UI becomes a reality.

**Comment by alvarlagerlof** [comment]
@mirkobrombin @jannuary I'm happy to help discussing this to make sure it works as good as it can

**Comment by mirkobrombin** [comment]
At the time of this comment there is no `libhandy-catalog` for Glade on Fedora 33 (my daily). I can migrate to Arch Linux which offers it but at the moment it could become a hang on the Bottles release (outside of Flatpak) if older distributions don't support `libhandy`.

Two parallel projects could be maintained at the moment:
- one for the improvement of the current design
- one for the new libhandy based design by @jannuary

**Comment by jannuary** [comment]
@mirkobrombin I think you need to have `libhandy-1-devel` and an RPM version of Glade installed.

**Comment by mirkobrombin** [comment]
> @mirkobrombin I think you need to have `libhandy-1-devel` and an RPM version of Glade installed.

I will try.

**Comment by rf-peixoto** [comment]
How about a one click option? Especially for simple applications that do not require installation. Next to it is a button "Try common / recommended settings?" that would test the application with the most used configurations. If it doesn't work, then start "Configure manually?".

I just left Windows, I feel that this facility is what is missing in most Linux applications.

**Comment by mirkobrombin** [comment]
> How about a one click option? Especially for simple applications that do not require installation. Next to it is a button "Try common / recommended settings?" that would test the application with the most used configurations. If it doesn't work, then start "Configure manually?".
> 
> I just left Windows, I feel that this facility is what is missing in most Linux applications.

Hi, thanks for reporting.

This is how Bottles works, there are 3 environments optimized by context (gaming, software). Just run your .exe/.msi/.bat inside your bottle.

Bottles was not born with the idea of ​​"one bottle for one program" but "one bottle for a thousand programs". We are also working on an installation manager that check for software dependencies before install it, so we can know in advance if that program is compatible with the others in the bottle.

Regarding the "One click", just create a software or gaming bottle and execute the executable inside it, using the configuration that comes with the environment.

**Comment by mirkobrombin** [comment]
To test the new UI under development, use the `refresh` branch.

```bash
git clone https://github.com/bottlesdevs/Bottles.git
git checkout refresh
mkdir build
meson build
cd build
ninja
ninja instal
```

**Comment by jannuary** [comment]
> To test the new UI under development, use the `refresh` branch.
> 
> ```bash
> git clone https://github.com/bottlesdevs/Bottles.git
> git checkout refresh
> mkdir build
> meson build
> cd build
> ninja
> ninja install
> ```

You can also use GNOME Builder to build it automatically.

**Comment by mirkobrombin** [comment]
I will soon be providing a new beta release tag to test the new UI under development

**Comment by LeandroStanger** [comment]
GTK4?

**Comment by mirkobrombin** [comment]
> GTK4?

No but I think we can upgrade in the future without too many complications.

**Comment by lionirdeadman** [comment]
The flatpak manifest in the refresh branch when modified to use the refresh branch instead tag 2.0.9.9 crashes with the following :
```
Traceback (most recent call last):
  File "/app/bin/bottles", line 49, in <module>
    from bottles import main
  File "/app/share/bottles/bottles/main.py", line 43, in <module>
    from .window import BottlesWindow
  File "/app/share/bottles/bottles/window.py", line 20, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
```

**Comment by mirkobrombin** [comment]
> The flatpak manifest in the refresh branch when modified to use the refresh branch instead tag 2.0.9.9 crashes with the following :
> 
> I think it's missing libhandy.
> 
> ```
> Traceback (most recent call last):
>   File "/app/bin/bottles", line 49, in <module>
>     from bottles import main
>   File "/app/share/bottles/bottles/main.py", line 43, in <module>
>     from .window import BottlesWindow
>   File "/app/share/bottles/bottles/window.py", line 20, in <module>
>     gi.require_version('Handy', '1')
>   File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Handy not available
> ```

Some dependencies need to be packaged, unfortunately I don't have time for them at the moment.I recommend using the unstable AppImage to test or if you know how to solve it you can open a PR.

**Comment by mirkobrombin** [comment]
The first beta is available for download for testing and reporting bugs before the final release.
https://github.com/bottlesdevs/Bottles/releases/tag/nightly

### Know issues
- [ ] missing translations

**Comment by jannuary** [comment]
> The flatpak manifest in the refresh branch when modified to use the refresh branch instead tag 2.0.9.9 crashes with the following :
> 
> I think it's missing libhandy.
> 
> ```
> Traceback (most recent call last):
>   File "/app/bin/bottles", line 49, in <module>
>     from bottles import main
>   File "/app/share/bottles/bottles/main.py", line 43, in <module>
>     from .window import BottlesWindow
>   File "/app/share/bottles/bottles/window.py", line 20, in <module>
>     gi.require_version('Handy', '1')
>   File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Handy not available
> ```

Better late than never, but this should be fixed on [Flathub](https://flathub.org/beta-repo/appstream/com.usebottles.bottles.flatpakref).

**Comment by mirkobrombin** [comment]
Bottles v3 released. Have fun bug hunters!
