### ISSUE TITLE
[Request] Wine logs

### ISSUE THREAD

**Issue by alvarlagerlof** [bottlesdevs/Bottles#774]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to see logs of wine in the app somehow. It was a useful debugging tool to run Bottles in the terminal and see what it outputed as it was working, but really only the logs from wine are interesting.

**Describe the solution you'd like**
A logs item in the sidebar maybe? Or linked to Task manager maybe?

**Describe alternatives you've considered**
Running through the terminal, but that output it currently quite limited.

**Comment by mirkobrombin** [comment]
I’m considering different solutions:
- logging all output and showing latest X rows in a dialog on user call
- an optional “Attach Debugger” in the Run Executable context menu that launch it trough the CMD

I think the second one is the best and less expensive solution but I really want to implement the EasyTerm before this (bottlesdevs/EasyTerm).

**Comment by alvarlagerlof** [comment]
I just realized that the "Command line" outputs what I expected to see. Feels like it is misnamed.
