### ISSUE TITLE
[BUG] dotnet472 installation fails

### ISSUE THREAD

**Issue by lavadrop** [bottlesdevs/Bottles#779]
Dependency installation fails, crash report is not generated and running in a Terminal downloads Firefox and unzips, then Bottles crashes again quietly. Also, no logs.

Flatpak version 2021.11.28-treviso

**To Reproduce**
Download Bottles from Flathub or Gnome Software
Run the setup and create your first bottle (Software environment in my case)
Install dotnet472

**Expected behavior**
A crash report

**Desktop (please complete the following information):**
 - OS: OpenSUSE 
 - Version Tumbleweed
 - Display server: Wayland

**Additional context**
Terminal output when trying to install dotnet472:
Used Flatseal to expose home directory to Bottles

2021-12-12 12:44:47 INFO: Installing dependency [d3dcompiler_47] in bottle [Subtitling].
Downloading Firefox Setup 62.0.3.exe: 100% [==================================================>

2021-12-12 12:44:50 INFO: Renaming [Firefox Setup 62.0.3.exe] to [firefox_setup_6203_32bit.7z].
patool: Extracting /home/user/.var/app/com.usebottles.bottles/data/bottles/temp/firefox_setup_6203_32bit.7z ...
patool: running /app/bin/7z x -o/home/user/.var/app/com.usebottles.bottles/data/bottles/temp/firefox_setup_6203_32bit -- /home/user/.var/app/com.usebottles.bottles/data/bottles/temp/firefox_setup_6203_32bit.7z
patool: ... /home/user/.var/app/com.usebottles.bottles/data/bottles/temp/firefox_setup_6203_32bit.7z extracted to `/home/user/.var/app/com.usebottles.bottles/data/bottles/temp/firefox_setup_6203_32bit'.

**Comment by mirkobrombin** [comment]
Download link was dead, fixed
