### ISSUE TITLE
Bottles doesn't start when it founds a "corrupted" bottle

### ISSUE THREAD

**Issue by adamantinum** [bottlesdevs/Bottles#78]
**Describe the bug**
Bottles doesn't start, or starts but doesn't respond, when it founds a "corrupted" bottle (it's still present, although I've deleted it from the menu).

**Installation**
From Arch User Repository

**To Reproduce**
Create a bottle, delete it, close the software and try to reopen it.

**Expected behavior**
Bottle should start and be usable

**Screenshots**
![photo_2021-01-06_17-25-07](https://user-images.githubusercontent.com/50221095/103795120-e0d5b700-5045-11eb-9f9f-b2d92e61ee24.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by mirkobrombin** [comment]
Also confirmed in the official package.

**Comment by mirkobrombin** [comment]
Should be fixed with latest commit, `bottles-git` should receive the update soon. Otherwise you can use the latest built Appimage.
