### ISSUE TITLE
[BUG] Import not showing Lutris 

### ISSUE THREAD

**Issue by dginovker** [bottlesdevs/Bottles#781]
**Describe the bug**
According to the [import documentation](https://docs.usebottles.com/bottles/import-from-other-managers), selecting "Import and export", then clicking on the circle arrow will list available imports from Bottles/Lutris/POL. However, I am not seeing my Lutris games.

**Installation**
 - Method: Flatpak
 - Version: 2021.11.28-treviso

**To Reproduce**
1. Install Lutris Battle for Middle Earth through the first option in the README here: https://github.com/Linux-BFME/Installers
2. Open Bottles, select "Import and export"
3. Click the refresh arrow
4. See no Lutris games

![image](https://user-images.githubusercontent.com/32943174/145740183-b9950615-66ca-46d6-9293-fec9cc021772.png)

**Expected behavior**
I would be able to import Lutris game into Bottles

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Display server: Xorg

**Additional context**
The Lutris game is a custom one not displayed on the Lutris.net website. May be related?

**Comment by mirkobrombin** [comment]
Hi read this https://docs.usebottles.com/flatpak/expose-directories you need to give flatpak permissions to ~/Games

**Comment by MiraiSubject** [comment]
Doing /home/deck/Games instead of ~/Games yields nothing either. I tried again just now to sanity check, but I forgot to document that in my previous comment. 

![Screenshot_20220421_181756](https://user-images.githubusercontent.com/803255/164505636-d56ae958-166b-419d-ace4-5476f8eeeb7b.png)

**Comment by MiraiSubject** [comment]
I don't know if I can give you more information to get this problem solved (please let me know if I can!), but I have submitted a feature request/proposal as an alternative to all the fiddling with a hardcoded path.

**Comment by Ugzuzg** [comment]
I have the same issue. And looking at the code I find it weird that it works for @mirkobrombin.
Here `xdg_data_home` is expected to resolve to Flatpak's overridden home:
https://github.com/bottlesdevs/Bottles/blob/260c0d76c76278197a4e95cdf8fd52e4c3ba7b8f/src/backend/globals.py#L48

But here the same variable is used to look for external prefixes (but the files are in `HOST_XDG_DATA_HOME`, not `XDG_DATA_HOME`, so it doesn't work):
https://github.com/bottlesdevs/Bottles/blob/260c0d76c76278197a4e95cdf8fd52e4c3ba7b8f/src/backend/globals.py#L78-L81

> <p>
>            Flatpak also overrides the XDG environment variables to point sandboxed applications
>            at their writable filesystem locations below <code class="filename">~/.var/app/$APPID/</code>:
>        </p>
>
> XDG_DATA_HOME
> XDG_CONFIG_HOME
> XDG_CACHE_HOME
> XDG_STATE_HOME (since Flatpak 1.13)
> <p>
>            The host values of these variables are made available inside the sandbox via these
>            HOST_-prefixed variables:
>        </p>
>
>HOST_XDG_DATA_HOME
>HOST_XDG_CONFIG_HOME
>HOST_XDG_CACHE_HOME
>HOST_XDG_STATE_HOME (since Flatpak 1.13)
> -- https://docs.flatpak.org/en/latest/flatpak-command-reference.html

**Comment by mirkobrombin** [comment]
I had already noticed this problem, caused by a migration to xdg vars. I was sure I fixed it, I must have lost the changes for some reason.
