### ISSUE TITLE
[BUG] The first startup freeze on download process

### ISSUE THREAD

**Issue by realiis** [bottlesdevs/Bottles#784]
**Describe the bug**
The first startup freeze on download process and show up error on terminal.
```
ERROR Error while running async job: <bound method Manager.checks of <bottles.backend.manager.Manager object at 0x7fdd61c608b0>>
Exception: checks() got an unexpected keyword argument 'after' 
  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
```

**Installation**
 - Method: Flatpak
 - Version 2021.12.14-treviso

**To Reproduce**
1. Install Bottles
2. Open Bottles
3. Click `Install` in the welcome window

or

1. Remove Bottles directory `rm -rf ~/.var/app/com.usebottles.bottles`
2. Open Bottles
3. Click `Install` in the welcome window

**Expected behavior**
Download the runners and allow create bottles

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 35
 - Display server: Wayland

**Comment by jibsaramnim** [comment]
I can confirm to get the exact same exception on my system, also running Fedora 35. 

I wonder if this issue might not be Fedora specific. I was curious and took a peek at the source. I'm not very familiar with this project and am not sure how to run/test it locally so I'm not confident enough to submit a pull request, but I _think_ the issue originates from [this merge here](https://github.com/bottlesdevs/Bottles/commit/2e6ab90a5f6c2b42fd495cd2aa3d209527d739b6#diff-5ddda185522f9e1db4e8dd11c436d5077822ba7c23dc1f43a392454527595ffbL103). My guess would be that bringing back the `after` property (and passing that off to `self.check_runners`, like before) should help things along.

**Comment by mirkobrombin** [comment]
My fault, I forgot to update the onboard after refactoring the manager checks method :D 

![](https://media0.giphy.com/media/u2FZvYGx9B51gbAqMY/giphy.gif?cid=ecf05e47gty1ommwug9exzu6t32xg3r5sm2ukth8fyjm67pk&rid=giphy.gif&ct=g)
