### ISSUE TITLE
[BUG] Version 2021.12.14-treviso reset dark mode to off. Only option that reset?

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#785]
Version 2021.12.14-treviso Flatpak

After updating to the latest Bottles and launching it, my dark mode setting was turned off. I’m not sure if this was caused by a persistent state regression on that only setting or others but it makes me wonder if other settings also reset or only this one.

To look into/fix: keep the users settings between version updates. I don't think this happened with the last few updates I did the past couple months which is why I think it’s a regression in only this version.

**Comment by mirkobrombin** [comment]
Hi this is why: https://github.com/bottlesdevs/Bottles/blob/bf76d861d36e9427f1050c89996dbdc1c589b8fe/debian/changelog#L13 so just enable the new night setting.
