### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by cunidev** [bottlesdevs/Bottles#786]
The initial download was taking ages (on a fast connection), so I just normally closed the app, and re-opened it. The following appeared

This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by cunidev** [comment]
Wait, this happens just after the download fails

```
(13:42:31) ERROR Error while running async job: <bound method Manager.checks of <bottles.backend.manager.Manager object at 0x7fca034357f0>>
Exception: checks() got an unexpected keyword argument 'after' 
  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
```


in the CLI log, but is unrelated with closing/reopening the app.

Interestingly, this exception does **not** stop the "Downloading" dialog, that continues being shown indefinitely.

By the way, thanks for the awesome app.

**Comment by mirkobrombin** [comment]
Hi, this was already reported https://github.com/bottlesdevs/Bottles/issues/784 and fixed. The next release (2021.12.14-treviso-1) is going to be distributed :smile:
