### ISSUE TITLE
[Request] Recipes for installing a certain programm

### ISSUE THREAD

**Issue by abthediablo** [bottlesdevs/Bottles#789]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
It would be desirable if one - e.g. self created scripts - can store, which components / dependencies such as fonts or frameworks, one needs with the installation of a certain program and installs these immediately automatically.

Similar principle as for example "PlayOnLinux" or "Crossover", where you can choose from ready-made packages.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mirkobrombin** [comment]
We are already working on it, the experimental feature is already available for testing: https://docs.usebottles.com/bottles/installers

For maintainers: https://github.com/bottlesdevs/programs
Currently supported (alpha) installers: https://usebottles.com/appstore/
