### ISSUE TITLE
[Crash report]  checks() got an unexpected keyword argument 'after'

### ISSUE THREAD

**Issue by alanmimms** [bottlesdevs/Bottles#790]
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottlejStV9z///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

This was on Ubuntu 20.04 x86_64 with a pretty vanilla Python3 global install but not a virtualenv.

**Comment by mirkobrombin** [comment]
Already fixed in 2021.12.14-treviso-2
