### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by realiis** [bottlesdevs/Bottles#796]
**Describe the bug**
Error in terminal while creating a new bottle
```21:16:52) ERROR Failed to get Xwayland display 
(21:16:52) INFO Using Xwayland.. 
(21:16:52) ERROR Failed to get Xwayland display 
(21:16:52) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7f022e0bfbb0>>
Exception: argument of type 'NoneType' is not iterable 
  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/manager.py", line 1045, in create_bottle
    Runner.set_windows(config, config["Windows"])
  File "/app/share/bottles/bottles/backend/runner.py", line 580, in set_windows
    Runner.reg_add(
  File "/app/share/bottles/bottles/backend/runner.py", line 670, in reg_add
    logging.info(res)
  File "/app/share/bottles/bottles/utils.py", line 181, in info
    self.root.info(self.__color("info", message))
  File "/app/share/bottles/bottles/utils.py", line 160, in __color
    if "\n" in message:
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/new.py", line 238, in finish
    self.new_bottle_config = result.data.get("config")
AttributeError: 'NoneType' object has no attribute 'data'
```

**Installation**
 - Method: Flatpak
 - Version: 2021.12.14-treviso-3

**To Reproduce**
1. Install Bottles
2. Open Bottles and install runners
3. Create bottle

or

1. Remove Bottles directory `rm -rf ~/.var/app/com.usebottles.bottles`
2. Open Bottles and install runners
3. Create bottle

**Expected behavior**
Successfully creating a bottle

**Screenshots**
It stopped at Setting Windows version
![image](https://user-images.githubusercontent.com/39202026/146259343-1994169d-5e2d-4475-ad11-9acbd116f135.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 35
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Fixed by this commit: https://github.com/flathub/com.usebottles.bottles/commit/2cbf72b4e9ef9c5e0d25e13345dfa8d1ba622a05 should available soon.

**Comment by mirkobrombin** [comment]
Re-opening as even though it should now work, the exception still needs to be handled
