### ISSUE TITLE
[Request] Back button form config page

### ISSUE THREAD

**Issue by alvarlagerlof** [bottlesdevs/Bottles#80]
**Is your feature request related to a problem? Please describe.**
The navigation is confusing. It does not follow the patterns that other gnome apps do. It is confusing

**Describe the solution you'd like**
Clicking the config button opens another page with a back button.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/14835120/103899928-6d8c7d80-50f7-11eb-845c-5af9d8cfc940.png)

![image](https://user-images.githubusercontent.com/14835120/103899986-86952e80-50f7-11eb-80c4-b1ea0f1aec53.png)

**Comment by alvarlagerlof** [comment]
Overall, the UI is very confusing and not logical. I'm happy to help improve it because I cannot figure out how to use this right now

**Comment by mirkobrombin** [comment]
We are already working on the redesign of the application, I ask you to provide all requests in Issue #77.

**Comment by jannuary** [comment]
Could this be reopened? This is more of an incremental issue, rather than something in the scope of the potential UI refresh.

**Comment by mirkobrombin** [comment]
> Could this be reopened? This is more of an incremental issue, rather than something in the scope of the potential UI refresh.

It was closed by mistake, it's a todo.
