### ISSUE TITLE
Question: Sandboxing without Flatpak

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#803]
Is there a way to setup the sandbox feature when installing Bottles using the AUR or DEB package?

**Comment by mirkobrombin** [comment]
There is only a partial sandbox (that should not be called like this) out of Flatpak, using the Custom environment during bottle creation, select the option to unlink your homedir from the bottle userdir. Btw this as said is not a true sandbox but just a rule to remove all symlinks between the WINE prefix and your homedir.

We are planning to port this feature also on other packages but idk how and when :D

**Comment by trymeouteh** [comment]
The sandboxing is just preventing the Wine prefix from accessing your Linux home directory so Windows apps cannot scan your files and folders in your Linux home directory?

**Comment by mirkobrombin** [comment]
> The sandboxing is just preventing the Wine prefix from accessing your Linux home directory so Windows apps cannot scan your files and folders in your Linux home directory?

WINE can still access your personal data using it's virtual device (`F:\ or Z:\` in most cases), when not under Flatpak. This option just prevent it for spawn data in your homedir by default when it try to save files in its userdir (`C:\users\user`).

**Comment by trymeouteh** [comment]
Since Flatpak restrict directory access in general, it will sandbox the Z drive and other drives.

**Comment by mirkobrombin** [comment]
> Since Flatpak restrict directory access in general, it will sandbox the Z drive and other drives.

Ya but you asked for the AUR and Deb packages

**Comment by trymeouteh** [comment]
Yes so by sandboxing it will sandbox directory and files and nothing else like internet, bluetooth, wifi, etc?

**Comment by mirkobrombin** [comment]
We are talking about flatpak sandbox?
