### ISSUE TITLE
[Request] Window resizing

### ISSUE THREAD

**Issue by alvarlagerlof** [bottlesdevs/Bottles#81]
**Is your feature request related to a problem? Please describe.**
The window is not re-sizable

**Describe the solution you'd like**
Ability to resize the window

**Describe alternatives you've considered**
None, this is standard.

**Additional context**
None

**Comment by mirkobrombin** [comment]
This is a personal choice as allowing fullscreen resize makes the UI distracting. I keep the issue open in case someone else has the same need. In that case we will make the change.

**Comment by alvarlagerlof** [comment]
I posted this because I often use apps in split-screen, with super + arrow keys. It is not currently possible.
