### ISSUE TITLE
[BUG] Creating bottle very slow on Flatpak

### ISSUE THREAD

**Issue by None124** [bottlesdevs/Bottles#811]
**Describe the bug**
Creating bottle/run executor takes very long time approx 35 minutes flatpak version while rpm doesnt take more than 4 minutes.

**Installation**
 - Method: flatpak
 - Version: latest 2021.12.14-treviso-3

**To Reproduce**
1. Open bottles
2. Create new bottle

**Expected behavior**
faster bottle creation/running executor like RPM version.

**Desktop:**
 - OS: Fedora
 - Version: 35
 - Display server: Wayland happens also in Xorg

**Comment by mirkobrombin** [comment]
Hi, this is because it's stalled. We have already fixed this in Wayland, you should have received the update. Can you double check if there are updates or try to reinstall Bottles?

**Comment by None124** [comment]
Yes i'm sure it is the latest version i have reinstalled flatpak bottles multiple times with no luck.

**Comment by mirkobrombin** [comment]
I'm forcing an update, it require ~4h

**Comment by mirkobrombin** [comment]
Ref 83b77f124286930600f5a6a1e5db2cc110c553df

**Comment by mirkobrombin** [comment]
Coming update is: 2021.12.14-treviso-4 let me know if the problem persist.

**Comment by None124** [comment]
Hello, the problem still persist with 2021.12.14-treviso-4

**Comment by mirkobrombin** [comment]
Start bottles from terminal and post here the output

**Comment by None124** [comment]
Yes at first bottle creation i install Wine mono

here is my bottle creation logs https://gist.github.com/None124/cb65fbd50c7eea6929a33ba1933e0c8e

**Comment by mirkobrombin** [comment]
I got it, the new Wayland checker is slow (on your PC), because it start before every command, so you have to wait for it before the next command can start. I'll find a solution to prevent it for being spawned multiple times

**Comment by None124** [comment]
But it also happen in Xorg?

**Comment by mirkobrombin** [comment]
> But it also happen in Xorg. for Flatpak version only.

Then it's just weird. The problem had to be fixed anyway because performing that check every time was useless, but unfortunately I don't know how to help with your problem. I don't know what slows everything down, if you see the logs are "just" slow all commands for some reason (which is not Bottles dependent).

**Comment by None124** [comment]
> > But it also happen in Xorg. for Flatpak version only.
> 
> Then it's just weird. The problem had to be fixed anyway because performing that check every time was useless, but unfortunately I don't know how to help with your problem. I don't know what slows everything down, if you see the logs are "just" slow all commands for some reason and it is also using the temp, so it is not downloading anything (which is not Bottles dependent).

Thanks alot i will try the new version as soon as it is pushed to flathub.

**Comment by mirkobrombin** [comment]
> > > But it also happen in Xorg. for Flatpak version only.
> > 
> > 
> > Then it's just weird. The problem had to be fixed anyway because performing that check every time was useless, but unfortunately I don't know how to help with your problem. I don't know what slows everything down, if you see the logs are "just" slow all commands for some reason and it is also using the temp, so it is not downloading anything (which is not Bottles dependent).
> 
> Thanks alot i will try the new version as soon as it is pushed to flathub.

Let us know :)

**Comment by bprfh** [comment]
Just to add feedback that it works for other users.
I am also running fedora 35(wayland, gnome) and I don't notice any obvious slowness, but I didn't try out the rpm version for comparison.
I installed bottle today and version is: 2021.12.14-treviso-4

**Comment by None124** [comment]
> > > > But it also happen in Xorg. for Flatpak version only.
> > > 
> > > 
> > > Then it's just weird. The problem had to be fixed anyway because performing that check every time was useless, but unfortunately I don't know how to help with your problem. I don't know what slows everything down, if you see the logs are "just" slow all commands for some reason and it is also using the temp, so it is not downloading anything (which is not Bottles dependent).
> > 
> > 
> > Thanks alot i will try the new version as soon as it is pushed to flathub.
> 
> Let us know :)

Thanks for looking at my issue, it is working pretty good right now. 😄

**Comment by mirkobrombin** [comment]
> > > > > But it also happen in Xorg. for Flatpak version only.
> > > > 
> > > > 
> > > > Then it's just weird. The problem had to be fixed anyway because performing that check every time was useless, but unfortunately I don't know how to help with your problem. I don't know what slows everything down, if you see the logs are "just" slow all commands for some reason and it is also using the temp, so it is not downloading anything (which is not Bottles dependent).
> > > 
> > > 
> > > Thanks alot i will try the new version as soon as it is pushed to flathub.
> > 
> > 
> > Let us know :)
> 
> Thanks for looking at my issue, it is working pretty good right now. smile

Nice :D
