### ISSUE TITLE
[BUG] Bottles crashes when saving launch options then clicking any button or sometimes right away on Save

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#812]
Flatpak 2021.12.14-treviso-3

When I launch bottles, go into a bottle and click the "3 dot" menu > Change launch options then add a launch option and click "Save"  then either Bottles crashes with no error log in the terminal or it lets you click one more  button before crashing.

Did not crash when clicked save:
(15:50:09) INFO Setting Key: [PhysX.cpl] to [__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only] for bottle: [Games]… 

Tried again to edit, crashed when clicked save:
(15:50:19) INFO Setting Key: [PhysX.cpl] to [__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only] for bottle: [Games]… 

I tried opening the Change launch options setting and leaving it blank and clicking save and it still crashed after clicking on more button (any, like back arrow to see other bottles)

This is all the terminal says:

Did not crash when clicked save:
(15:48:42) INFO Setting Key: [PhysX.cpl] to [] for bottle: [Games]… 

Crashed when click save:
(15:48:42) INFO Setting Key: [PhysX.cpl] to [] for bottle: [Games]… 

Even when Bottles crashes the first time upon click save, it does successfully save the launch option and I can see it there.

**Comment by mirkobrombin** [comment]
Also you are using the launch options in the wrong way, read here: https://docs.usebottles.com/bottles/programs#prefix-and-suffix-in-launch-options


Btw I'll fix the crash in the next release

**Comment by Githob2021** [comment]
> Also you are using the launch options in the wrong way and will block the execution if you don't use the `%command%` placeholder, read here: https://docs.usebottles.com/bottles/programs#prefix-and-suffix-in-launch-options

I will talk to you more about this in the forum.

> Btw I'll fix the crash in the next release

Thanks for looking into it/fixing it!
