### ISSUE TITLE
[BUG] [Flatpak] The Run Executable button silently fails starting any application

### ISSUE THREAD

**Issue by 1player** [bottlesdevs/Bottles#814]
**Describe the bug**

Starting any executable using the Run Executable main button silently fails with error "ShellExecuteEx failed: File not found."

**Installation**
 - Method: Flatpak
 - Version: 2021.12.14-treviso-4

**To Reproduce**
1. Install Bottles from Flathub
2. Create a new bottle (I'm using the Gaming preset)
3. Run any .exe with the terminal activated for debugging

**Expected behavior**

The application starts.

**Actual behavior**

Nothing happens. The terminal says, in all cases:

```
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
Application could not be started, or no application associated with the specifi
ed file.
ShellExecuteEx failed: File not found.
```

*If I run the application from the command line feature in Bottles, it starts fine.*

**Desktop:**
 - OS: Fedora 35
 - Desktop environment: GNOME
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
Hi, try this: https://docs.usebottles.com/flatpak/black-screen-or-silent-crash

Also the `winemenubuilder` error is not a blocking thing, it is just blacklisted in Bottles as it generate broken desktop entries that escape the bottle configuration.

**Comment by 1player** [comment]
Yes, that works.

But there still is something going on: if I give the Bottles flatpak access to all my home directory with Flatseal, I can start the game from the Bottles command line, but not through the "Run executable" button. Why is that? The link you've posted says it's because of the Flatpak sandbox, but this is not the case.

**Comment by mirkobrombin** [comment]
That's weird 😅

Give me some information:
1. what command do you run that actually works?
2. please provide your bottle.yml file (can be exported using backup menu in the bottle view)

**Comment by 1player** [comment]
Well, looks like I can't reproduce this anymore. Either a glitch in the matrix, or I did mess up when giving Bottles access to my home directory yesterday.

Now, if I give Bottles access to my $HOME, everything starts fine. Still, it would be really nice to have an error message pop up when the application can't be started because of sandboxing issues. Even just sending users to that docs URL would be fine.

Sorry for wasting your time, thanks for the app!

**Comment by mirkobrombin** [comment]
> 

Not a waste of time at all, good to know about it. Thanks for reporting 😊
