### ISSUE TITLE
[BUG] Website is not GDPR compliant

### ISSUE THREAD

**Issue by iamwonderfull93748** [bottlesdevs/Bottles#815]
Hi bottledevs, thx for a great product

The website at https://usebottles.com/ is putting tracking cookies in the browser both before and after declining the cookie popup.

That makes it illegal in the EU.

**Comment by mirkobrombin** [comment]
Hi, I think there is a bug in the cookie alert 😅 moving to the right repository https://github.com/bottlesdevs/website/issues/11
