### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by OrionRandD** [bottlesdevs/Bottles#816]
Hi.
I just would like to give you a suggestion about changing the name of this application...
Reasoning: When Micro$oft created WSL - Windows Subsystem for Linux, I thought that was a way of diminishing the GNU/Linux project and telling people, through their wording play, that Window$ is a much superior System and that Linux was/is only a small application that can run inside the mighty Window$. So that they called Linux a sub-System - really an underdog, inferior, subaltern System, slave system - inside a Master one.
So, when I saw this project I thought: "Why did they not call it Window$-subsystem?".
For sure, in my opinion, it would atract more attention and funds to the project.
But, certainly, github-Micro$oft would not like the name at all.
So, perhaps, if you change its name, before that, make the repository redundant in chissel/fossil and/or gitlab.
But, really, consider changing the project name from Bottles to "Windows-subsystem" - WSS

**Comment by AlexzanDev** [comment]
lol?

**Comment by francescomasala** [comment]
Lolz

**Comment by jannuary** [comment]
No 💖

**Comment by dst212** [comment]
Plot twist: Bottles is not a subsystem

**Comment by alvarlagerlof** [comment]
Windows is a trademark, and using it will likely put us in trouble. Bottles is not a large organization capable of depending ourselves in court.

**Comment by mirkobrombin** [comment]
> Windows is a trademark, and using it will likely put us in trouble. Bottles is not a large organization capable of depending ourselves in court.

This, plus: I don't think this is the purpose of Microsoft with WSL but if so, we are better after all, we don't?

**Comment by OrionRandD** [comment]
> Windows is a trademark, and using it will likely put us in trouble. Bottles is not a large organization capable of defending ourselves in court.

Windows can be a trademark, but not the word windows in a dictionary. Because they do not own this word... Do you mean that if we use the word windows in our houses we are violating Micro$oft patents? LOL

**Comment by OrionRandD** [comment]
> This, plus: I don't think this was the purpose of Microsoft with W

You can be sure that this was the purpose whe they created that. The reasoning is very clear: "You do not need to leave Windows and install Linux to have all their goodies... Stay in Window$ and we will offer the same system inside Window$. Then you wlll be in great shape compared to those who only have Linux in their system..."
