### ISSUE TITLE
[Request] Reword "Software" to "Applications"

### ISSUE THREAD

**Issue by janopae** [bottlesdevs/Bottles#822]
Currently, Bottles differentiates between the environments "Software" and "Games". This is a very unclear separation, as all games are software. Not only games are software, but also drivers, plugins and all other kinds of stuff. Imagine in the future, an environment for audio plugins (like effects or virtual instruments in VST format) was added. The category "Software" made even less sense then.

I propose rewording the "Software" environment to "Applications". You could argue that games technically were also applications, but at least the hypothetical use case of plugins would be covered. Also, I suspect that most people don't see games as applications, terms like "apps and games" are common in marketing, people are going to see a difference in running apps on their PlayStation to running games on their PlayStation (while they'll refer to both as software).

Another possible wording would be "Apps". But I guess that most people refer to Win32 applications with the traditional longhand "Applications". They might confuse it with the newer UWA platform.

**Comment by mirkobrombin** [comment]
I had never thought about this, I think it is an excellent consideration. Thanks for sharing.

**Comment by wastee** [comment]
I think it depends. 

If i need an environment to install virtual instruments in VST format in WINE. I'll think am i need dxvk or something with "game tuner". Because some virtual instruments or sound effect's GUI need some "game tuner" to improve the GUI even it's not a game.

**Comment by mirkobrombin** [comment]
But actually the software env came with dxvk too but without some dependencies. Is that enough for your case?

**Comment by mirkobrombin** [comment]
Planning for 2022.1.14
