### ISSUE TITLE
[BUG] Enabling Gamemode prevent using the "Command Line" option

### ISSUE THREAD

**Issue by nicobatty** [bottlesdevs/Bottles#825]
**Describe the bug**
When the Gamemode option is enabled, it is not possible to use the "Command Line" option (nothing happens in the GUI side).

**Installation**
 - Method: Flatpak
 - Version: 2021.12.14-treviso-4

**To Reproduce**
1. Create a Gaming bottle.
2. Enable gamemode.
3. Click on on the "Command Line" option.
4. Nothing happens on the GUI side.

**Expected behavior**
1. Create a Gaming bottle.
2. Enable gamemode.
3. Click on on the "Command Line" option.
4. The command line shows up.

**Screenshots**
Since nothing is happening I don't really have any screenshots but here are the logs that helped me find what was the source of it not running:
```
/app/bin/easyterm.py:101: DeprecationWarning: Vte.Terminal.spawn_sync is deprecated
  self.terminal.spawn_sync(

(easyterm.py:255): VTE-WARNING **: 22:04:43.077: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
Traceback (most recent call last):
  File "/app/bin/easyterm.py", line 244, in do_command_line
    EasyTermLib(cwd, command, env, actions, dark_theme, palette)
  File "/app/bin/easyterm.py", line 135, in __init__
    self.window = MainWindow(cwd, command, env, actions, dark_theme, palette)
  File "/app/bin/easyterm.py", line 101, in __init__
    self.terminal.spawn_sync(
gi.repository.GLib.Error: g-io-error-quark: Failed to execute child process “gamemoderun”: Failed to execve: No such file or directory (1)
```

**Desktop (please complete the following information):**
 - OS: EndeavourOS (similar to Arch Linux)
 - Version: Rolling release
 - Display server: Xorg
 - Desktop Environment: KDE Plasma

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by nicobatty** [comment]
No problem! I just noticed that I have the same problem if I try to access Wine-DBG from the "Debug" option.

**Comment by mirkobrombin** [comment]
The problem is related to EasyTerm (the terminal we provide with the flatpak), seems like it is not able to locate gamemoderun. So since both tools run via EasyTerm, they have the same problem. I will find a fix and apply it for the next release of Bottles and EasyTerm.
