### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by andyl** [bottlesdevs/Bottles#830]
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottleU4pZ83///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by andyl** [comment]
AppImage not installing on Ubuntu 20.04 - It hangs indefinitely at the "Downloading..." prompt.

**Comment by mirkobrombin** [comment]
Duplicate of #784
