### ISSUE TITLE
[BUG] Can't launch program through CLI

### ISSUE THREAD

**Issue by adabadam** [bottlesdevs/Bottles#835]
**Describe the bug**
Can't launch executable file from CLI. Launches fine from the GUI.

**Installation**
 - Method: AUR
 - Version: 2021.12.14-treviso-2

**To Reproduce**
I enter this in the terminal:
`bottles -b 'Ableton' -e '/home/adam/.local/share/bottles/bottles/Ableton/drive_c/ProgramData/Ableton/Live 11 Suite/Program/Ableton Live 11 Suite.exe'`

I get this response:
```
(18:28:53) INFO Performing Bottles checks...
(18:28:53) INFO DXVKs found:
         - dxvk-1.9.2

(18:28:53) INFO VKD3Ds found:
         - vkd3d-v2.4

(18:28:53) INFO NVAPIs found:
         - dxvk-nvapi-v0.4

(18:28:53) INFO Runners found:
         - sys-wine-7.0-rc1

         - vaniglia-6.23

(18:28:54) INFO Bottles found:
         - Ableton

(18:28:55) INFO Running an executable on the bottle…
0250:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
```

**Expected behavior**
Expected the program to launch.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.15.10-arch1-1
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
I think it's because of the sandbox, does it works with "Right click" in your file manager?

**Comment by adabadam** [comment]
Right click -> Open With Bottles opens the GUI. Is that what you meant?

**Comment by adabadam** [comment]
A process does seem to launch but it is not visible on any of my workspaces
![2021-12-20-1640025465_1920x1080](https://user-images.githubusercontent.com/81109003/146816465-904c0e8d-7a35-47e9-96bb-8ad031fb7ca1.png)

**Comment by mirkobrombin** [comment]
I think it's blocked by the sandbox, I'll find a fix

**Comment by Mansalol** [comment]
Jn

**Comment by mirkobrombin** [comment]
I'm not able to reproduce, are you sure the program works from inside Bottles? 
Do a simple test:
- go to the executable path
- right click and Launch with Bottles
- it should pop up the Bottles GUI with your bottles, click "Run here" 

Does it launch?

If not, does it works from inside the Bottle's programs list?

**Comment by mirkobrombin** [comment]
Closing for no response.
