### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by RickAndTired** [bottlesdevs/Bottles#837]
Bottles gets stuck on the first "Install" in the welcome window. It will stay on the "Downloading..." screen until I force close it (I've tried letting it go for an hour)

This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottleUxpxHi///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by mirkobrombin** [comment]
Duplicate
