### ISSUE TITLE
[Question] Any downsides with Flatpak version?

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#838]
Bottles looks absolutely brilliant! Having a shared prefix for games makes a lot of sense nowadays.

I am looking at the Flatpak version and really like the fact that it protects the Linux host folders and home folders so that Windows malware can't break out!

And I love that you can manually add Other Folders via Flatseal, so that Wine's exploration of Z: will be able to see just those folders. Perfect.

But is everything really perfect with Flatpak? I have been reading the docs and tickets and can't see any downsides at all.

I'd like to check:

Are there any downsides to the flatpak version?

1. Such as worse game/application compatibility? Or worse performance?
2. Will PROTON-GE and DXVK and Vkd3d-proton work properly inside sandbox?
3. What about driver features like enabling NVAPI for DLSS or enabling DXR raytracing in vkd3d? Will those new, modern driver APIs work in sandbox? I mean `PROTON_ENABLE_NVAPI` in the Proton readme: https://github.com/ValveSoftware/Proton/ 
4. Does Game Mode (meaning "high priority game process") work? https://github.com/FeralInteractive/gamemode 
5. Does MangoHud work? https://github.com/flightlessmango/MangoHud
6. Does Gamescope Wayland micro compositor work? https://github.com/Plagman/gamescope

I am excited about the Flatpak even if some of this is broken, because the benefits of being sandboxed against Windows malware is huge! :)

**Comment by mirkobrombin** [comment]
> Bottles looks absolutely brilliant! Having a shared prefix for games makes a lot of sense nowadays.

Thanks a lot for the kind words :D

> Such as worse game/application compatibility?

At the moment there is only one reported case but it is more related to a configuration problem than performance. I've done a lot of performance tests (really a lot of tests) with a series of games:
- Need for Speed Heat
- Need for Speed Payback
- Need for Speed Hot Pursuit Remastered
- Battlefield 5
- Warframe
- Titanfall 2
- Tom Clancy's The Division
- Grand Theft Auto V
and other.

In all cases I had no performance issues compared to "native" Steam, Lutris and Bottles. There are cases such as:
- Need for Speed Heat
- Warframe
- Grand Theft Auto V

in which I had more performances with Bottles via Flatpak. Hope this information can help you.

> Will PROTON-GE and DXVK and Vkd3d-proton work properly inside sandbox?

All components are working properly. In the case of vkd3d there is a small regression in the current version that prevents it from being installed in certain cases, it has been fixed and the fix will be distributed in the next release.

> What about driver features like enabling NVAPI for DLSS or enabling DXR raytracing in vkd3d? Will those new, modern driver APIs work in sandbox? I mean PROTON_ENABLE_NVAPI in the Proton readme: https://github.com/ValveSoftware/Proton/

I hope. I mean, we provide DLSS support with DXVK-Nvapi, just enable in your bottle preferences. Since I don't have an RTX, I had others test the function and the result was positive. So I can't speak from personal experience unfortunately but it should work.

> Does Game Mode (meaning "high priority game process") work? https://github.com/FeralInteractive/gamemode

Yes. It came with the Flatpak. Just enable in your bottle preferences.

> Does MangoHud work? https://github.com/flightlessmango/MangoHud

Not supported yet: https://github.com/bottlesdevs/Bottles/issues/530

> Does Gamescope Wayland micro compositor work? https://github.com/Plagman/gamescope

Never heard of it, I'll check it out.

**Comment by Bananaman** [comment]
Wow, thanks a lot! This is fantastic. I am going to use the Flatpak.

It's a big peace of mind to know that Windows software can no longer infect the Linux host, can no longer spy on its filesystem, can no longer spam garbage files in my Linux home folders, etc!

You have done an amazing job with Bottles, and I love the GUI too. This is the future for running Windows on Linux! :D

1. Regarding GameScope: This is the compositor that Valve uses in STEAMOS and in their Steam Deck console. It boosts game FPS on Wayland through bypassing the normal wayland compositor somehow.
2. Regarding your use of DXVK-NVAPI project: I had no idea what this is, but after reading through the details, they say that it's the exact same library that Proton contains built-in. It's a dll file which implements NVAPI functions and passes them through to Vulkan calls in NVIDIA driver. Perfect. I guess you decided to use the standalone library instead of Protons own, to make NVAPI work with regular Wine too.
3. I saw that [there are some steps](https://github.com/jp7677/dxvk-nvapi#proton) to enabling DXVK-NVAPI: `PROTON_ENABLE_NVAPI=1`, `PROTON_HIDE_NVIDIA_GPU=0`, `dxvk.conf: dxgi.nvapiHack = False`, and installing the DLLs into `dist/lib/wine[64]/nvapi` of Proton. And [similar steps](https://github.com/jp7677/dxvk-nvapi#wine) if a prefix uses plain Wine. Does the user have to do any parts of that, or does Bottles do everything? The hardest part to automate is dxvk.conf but there is a variable `DXVK_CONFIG_FILE=/xxx/dxvk.conf` so perhaps Bottles uses that and makes a global dxvk config with the necessary settings. :) 
4. With Vkd3d-proton [there is a new flag](https://github.com/HansKristian-Work/vkd3d-proton#environment-variables) `VKD3D_CONFIG=dxr11` which enables raytracing. Is this flag supported in Bottles?  I check again because I can't find any references to it in any other discussions here. :)

**Comment by mirkobrombin** [comment]
> Regarding GameScope: This is the compositor that Valve uses in STEAMOS and in their Steam Deck console. It boosts game FPS on Wayland through bypassing the normal wayland compositor somehow.

good to know

>  saw that there are some steps to enabling DXVK-NVAPI: PROTON_ENABLE_NVAPI=1, PROTON_HIDE_NVIDIA_GPU=0, dxvk.conf: dxgi.nvapiHack = False, and installing the DLLs into dist/lib/wine[64]/nvapi of Proton. And similar steps if a prefix uses plain Wine. Does the user have to do any parts of that, or does Bottles do everything? The hardest part to automate is dxvk.conf but there is a variable DXVK_CONFIG_FILE=/xxx/dxvk.conf so perhaps Bottles uses that and makes a global dxvk config with the necessary settings. :)

Bottles take care of everything, except for Proton flags (you need to set on your own from Environment variables section in your bottle's preferences). Despite we offer Proton in Bottles, you should use Wine-GE which is meant to be used outside of Steam (also available on Bottles).

> With Vkd3d-proton there is a new flag VKD3D_CONFIG=dxr11 which enables DirectX 12 raytracing (DXR). Is this flag supported in Bottles? I check again because I can't find any references to it in any other discussions here. :) edit: and nothing in the code, it seems.

Currently all these "custom options" are not managed by default by Bottles but can easily be set from Environment variables section like the other one above. One of the next releases will improve env vars management, as this is just a text field. In the future this will look like the DLL Overrides section, so you can add a row for each env var, assign a value to it and easily toggle on/off status without deleting.

> If I understand correctly, the proper usage of Bottles is to install the Windows versions of Steam, Origin, Epic etc, and then launch the games from that. But my question is: Should I launch steam in the bottle and then the game from steam. Or should I launch the game "directly" via its bottle start menu shortcut? I am just concerned about ensuring that the game runs with Game Mode (perhaps if I start steam/launcher first, game mode only affects the launcher exe but not the actual game process?).

Yes but not :D First if a game works with Steam/Proton, you should use Steam with Proton enabled (Flatpak is the best in my experience, like Bottles it provides all necessary stuff and works just out of the box). For all other games you can create a new Gaming env bottle (which came with some dependencies/tweaks to be most compatible as possible with modern games) and try to run the executable inside it (like the EGS), if it doesn't work you still need to find a valid configuration online (ProtonDB/WineDB..) and try to tweak the bottle on your own. 

We are working on our installers, which are a bunch of instructions that Bottles interpret to make your bottle compatible and being able to support the executable. Currently this is an experimental feature and can be enabled from Bottles' preferences. We offer installers for: EGS, Blizzard, Origin, GOG, Steam but still an under early development feature.

**Comment by Bananaman** [comment]
> Bottles take care of everything, except for Proton flags (you need to set on your own from Environment variables section in your bottle's preferences).

Thanks, I will try! Do I need to create dxvk.conf with `dxgi.nvapiHack = False`?

> Despite we offer Proton in Bottles, you should use Wine-GE which is meant to be used outside of Steam (also available on Bottles).

Hmm, that's a good point. I hear that Proton has a lot of Steam hooks for things like Origin and Uplay launchers, so that games that use multiple launchers work under Steam's Proton. I guess all of that is messed up if everything runs on a Windows Steam version inside Bottles.

I am going to switch to Wine-GE. Thanks.

> Currently all these "custom options" are not managed by default by Bottles but can easily be set from Environment variables section like the other one above. One of the next releases will improve env vars management.

Ah okay, that's totally fine. And I look forward to that GUI redesign! :D

> if a game works with Steam/Proton, you should use Steam with Proton enabled

Alright thanks, understood! :D I will use native (Fedora) Steam package, or the Flatpak, for all Steam games. And will use Bottles for all other launchers. :)

Thanks a lot for the help and answers! I'm more confident now and will install Bottles now and Wine-GE and do the environment tweaks. :)

**Comment by Bananaman** [comment]
I have just installed Bottles and am still figuring out the settings, but damn I LOVE this application. Thank you @mirkobrombin :D

**Comment by mirkobrombin** [comment]
> Thanks a lot for the help and answers! I'm more confident now and will install Bottles now and Wine-GE and do the environment tweaks. :)

You are welcome :)

> I have just installed Bottles and am still figuring out the settings, but damn I LOVE this application. Thank you @mirkobrombin :D

Thanks <3
