### ISSUE TITLE
[Request] Option to disable mouse scroll wheel for selecting bottles preferences that use a dropdown

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#843]
Flatpak 2021.12.14-treviso-4

Please implement an option to disable the mouse scroll wheel for selecting preferences in a bottle. I've had this happen at least 100 times the past couple months I've used bottles.

What happens is when you are in a bottle and trying to scroll up or down using the scroll wheel, if you are even slightly over one of the preferences, it will instead scroll the settings inside of that preference. This then causes Bottles to become unresponsive for a couple of seconds while it does the flag switching or whatever happens in the background.

For example, you open bottle "EGS" then you click on Preferences tab. As you are scrolling your mouse wheel down to look through the preferences, if you slightly move over to the darker area where the preferences are under System it will change everything like Runner, DXVK version, Windows version. When this happens if you have the application/game open in a virtual desktop it will open a virtual desktop for each setting which can take a long time. Then you need to remember what the setting was and set it back.

This can be solved by using versioning, but ideally I wouldn't be able to accidentally change a setting by using my scroll wheel.

What would be nice: a "General" preference in the main menu hamburger menu under "General" that says something along the lines of "use mouse scroll wheel to select preferences" with a toggle for off/on.

Let me know if this does not make sense and I will try to make a mock up. I am not gifted graphically so it might look bad.

Thank you.

**Comment by mirkobrombin** [comment]
Hi, I've already fixed this and will available on next release :D 

![image](https://user-images.githubusercontent.com/9479903/146989703-7a071e6c-7f99-4462-a574-c237740a97c8.png)
