### ISSUE TITLE
[BUG] Do not force Discrete GPU on non-optimus laptop/PC

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#849]
This is a continuation of a very long bug report:

https://github.com/bottlesdevs/programs/issues/21

Summary:

- NVIDIA Driver, Fedora 35, Bottles Flatpak.
- OpenGL programs run on Wayland in Bottles.
- OpenGL programs don't work in X11 in Bottles (both Flatpak and native Bottles).
- OpenGL programs work in X11 in Lutris.

The cause hasn't been found yet. The previous ticket contains lots of information but no definitive answers yet.

## Update: The cause has been found below: https://github.com/bottlesdevs/Bottles/issues/849#issuecomment-999884104

**Comment by Bananaman** [comment]
Alright, after testing EGS and discovering that it wasn't starting with `-opengl` flag on X11 in Bottles, we began suspecting that OpenGL isn't working in Bottles.

This is now confirmed.

- Grab this v1.2 windows version of an OpenGL testing tool: https://sourceforge.net/projects/openglchecker/files/Release/1.2/OpenGLChecker_1.2_win32.zip/download
- Manually unzipped it into my `drive_c` of my "Games" Bottle.
- Went to Programs: Add Programs, clicked Plus, and navigated to that `drive_c` path and added the program.

Results:

- X11 in Bottles: Doesn't start. The window just flickers and instantly vanishes.
- Wayland in Bottles: Starts. The window appears and shows the OpenGL testing features and is able to run the benchmarks etc.

This concludes the testing to find the cause:

- OpenGL is not working in Native or Flatpak versions of Bottles on my Fedora 35 system.
- OpenGL is working in Lutris (but I uninstalled it and will keep trying to make Bottles work).

My next ideas for testing: Running native Linux OpenGL tests.

**Comment by Bananaman** [comment]
I installed a random OpenGL game from Flathub:

https://www.flathub.org/apps/details/io.github.mki1967.mki3dgame

Now I can confirm that OpenGL is working perfectly inside Flatpaks.

The issue has therefore been narrowed down to:

- It's something inside Bottles, possibly the environment variables it gives to Wine, which is disabling OpenGL on X11 on my system.

**Comment by Bananaman** [comment]
Here's the output of native OpenGL libraries:

```
$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 495.44
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 495.44
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 495.44
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by Bananaman** [comment]
Alright I had an idea.

I went into Bottles Environment Variables, and set this:

- `WINEDEBUG=+all` (https://wiki.winehq.org/Debug_Channels)
- This turns on maximum logging of exactly *everything* that goes on in Wine.

Then I ran this in a Terminal:

- `flatpak run com.usebottles.bottles 2>&1 | tee winelog.txt`
- In Bottles, I attempted to run the "OpenGLChecker" utility, in X11. It failed, as expected.
- This captured over half a million lines of text.

Next, to analyze the text...

- `cat winelog.txt | grep -i "wgl" -C5`
- This does a case insensitive search for "wgl", which is the term Wine uses for Windows OpenGL. With 5 lines before/after for context for each call.
- You would expect to see a lot of things related to creating wgl contexts etc, as in the final logs of the 1st post on this thread: https://forum.winehq.org/viewtopic.php?t=34889
- On my system, I can see that it gives up when it attempts to retrieve the OpenGL Driver (`__wine_get_wgl_driver`).

```
15237.444:0100:0104:trace:virtual:dump_view       0x7a840000 - 0x7a840fff c-r--
15237.444:0100:0104:trace:virtual:dump_view       0x7a841000 - 0x7a93cfff c-r-x
15237.444:0100:0104:trace:virtual:dump_view       0x7a93d000 - 0x7a93efff c-rw-
15237.444:0100:0104:trace:virtual:dump_view       0x7a93f000 - 0x7a93ffff c-rW-
15237.444:0100:0104:trace:virtual:dump_view       0x7a940000 - 0x7a945fff c-rw-
15237.444:0100:0104:trace:imports:import_dll --- __wine_get_wgl_driver win32u.dll.0 = 7E38169C
15237.444:0100:0104:trace:virtual:NtProtectVirtualMemory 0xffffffff 0x7a93f000 00001000 00000008
15237.444:0100:0104:trace:virtual:get_vprot_range_size base 0x7a93f000, size 0x7000, mask 0x20.
15237.444:0100:0104:trace:virtual:dump_view View: 0x7a840000 - 0x7a945fff (builtin image)
15237.444:0100:0104:trace:virtual:dump_view       0x7a840000 - 0x7a840fff c-r--
15237.444:0100:0104:trace:virtual:dump_view       0x7a841000 - 0x7a93cfff c-r-x
--
15237.444:0100:0104:trace:imports:import_dll --- glVertex2fv OPENGL32.dll.320 = 7A84790C
15237.444:0100:0104:trace:imports:import_dll --- glTexCoord2fv OPENGL32.dll.275 = 7A84736C
15237.444:0100:0104:trace:imports:import_dll --- glGenTextures OPENGL32.dll.105 = 7A845E2C
15237.444:0100:0104:trace:imports:import_dll --- glLoadIdentity OPENGL32.dll.164 = 7A84658C
15237.444:0100:0104:trace:imports:import_dll --- glGetIntegerv OPENGL32.dll.111 = 7A845EEC
15237.444:0100:0104:trace:imports:import_dll --- wglCreateContext OPENGL32.dll.345 = 7A847C2C
15237.444:0100:0104:trace:imports:import_dll --- glClearColor OPENGL32.dll.18 = 7A84534C
15237.444:0100:0104:trace:imports:import_dll --- glGetError OPENGL32.dll.109 = 7A845EAC
15237.444:0100:0104:trace:imports:import_dll --- glGetString OPENGL32.dll.124 = 7A84608C
15237.444:0100:0104:trace:imports:import_dll --- wglMakeCurrent OPENGL32.dll.356 = 7A847D8C
15237.444:0100:0104:trace:imports:import_dll --- glGetFloatv OPENGL32.dll.110 = 7A845ECC
15237.444:0100:0104:trace:imports:import_dll --- glBlendFunc OPENGL32.dll.13 = 7A8452AC
15237.444:0100:0104:trace:imports:import_dll --- glEnable OPENGL32.dll.79 = 7A845AEC
15237.444:0100:0104:trace:imports:import_dll --- wglGetProcAddress OPENGL32.dll.355 = 7A847D6C
15237.444:0100:0104:trace:imports:import_dll --- wglDeleteContext OPENGL32.dll.347 = 7A847C6C
15237.444:0100:0104:trace:imports:import_dll --- glNormal3fv OPENGL32.dll.190 = 7A8468CC
15237.444:0100:0104:trace:virtual:NtProtectVirtualMemory 0xffffffff 0x1000a000 00001000 00000002
15237.444:0100:0104:trace:virtual:get_vprot_range_size base 0x1000a000, size 0x7000, mask 0x20.
15237.444:0100:0104:trace:virtual:dump_view View: 0x10000000 - 0x10010fff (image)
15237.444:0100:0104:trace:virtual:dump_view       0x10000000 - 0x10000fff c-r--
--
15237.960:0100:0104:trace:module:load_dll Found L"C:\\windows\\system32\\OPENGL32.dll" for L"opengl32.dll" at 7A840000, count=-1
15237.960:0100:0104:Ret  ntdll.LdrLoadDll() retval=00000000 ret=7b04d27b
15237.960:0100:0104:Call ntdll.RtlReleasePath(006c1408) ret=7b04d28c
15237.960:0100:0104:trace:heap:RtlFreeHeap (00640000,70000062,006C1408): returning TRUE
15237.960:0100:0104:Ret  ntdll.RtlReleasePath() retval=00000000 ret=7b04d28c
15237.960:0100:0104:Call opengl32.wglChoosePixelFormat(12010050,0061fb80) ret=7e3e8578
15237.960:0100:0104:trace:wgl:wglChoosePixelFormat 0x12010050 0x61fb80: size 40 version 1 flags 37 type 0 color 32 0,0,0,0 accum 0 depth 16 stencil 0 aux 0
15237.960:0100:0104:Call win32u.__wine_get_wgl_driver(12010050,00000015) ret=7a8bb23a
15237.960:0100:0104:Call ntdll.RtlRunOnceExecuteOnce(7d7a44e4,7d75d7e0,00000000,00000000) ret=7b08e619
0104: *killed* exit_code=0
15238.012:0020:0024:trace:esync:__esync_wait_objects Woken up by handle 0x8c [0].
15238.012:00bc:00c0:trace:esync:__esync_wait_objects Woken up by handle 0xc4 [0].
15238.012:0020:0024:Ret  ntdll.NtWaitForMultipleObjects() retval=00000000 ret=7b08f851
```

I decided to do a grep for GLX and I see that Blottles seems to have the following environment variable: `__GLX_VENDOR_LIBRARY_NAME=nvidia`.

I tried manually setting the Bottles Environment to `__GLX_VENDOR_LIBRARY_NAME=mesa` but this didn't make it run either.

All I can conclude is that Wine in Bottles isn't finding OpenGL. Every other OpenGL flatpak and native application works, including in Wine via Lutris. I can't figure out what Bottles is doing that is disabling OpenGL...

**Comment by Bananaman** [comment]
Here's the full list of environment variables passed to Wine, captured in the log.

Literally ANY of these variables could be the cause of the problem. So it's a heavy work to debug this...

`new_process( token=0000, debug=0000, parent_process=0000, flags=00000000, socket_fd=18, access=001fffff, machine=0000, info_size=336, handles_size=0, jobs_size=0, objattr={rootdir=0000,attributes=00000000,sd={},name=L""}, handles={}, jobs={}, info={debug_flags=0,console_flags=0,console=0038,hstdin=0034,hstdout=0008,hstderr=000c,x=0,y=0,xsize=0,ysize=0,xchars=0,ychars=0,attribute=00,flags=1,show=1,curdir=L"C:\\OpenGLChecker\\",dllpath=L"",imagepath=L"C:\\OpenGLChecker\\OpenGLChecker.exe",cmdline=L"\"C:\\OpenGLChecker\\OpenGLChecker.exe\" ",title=L"C:\\OpenGLChecker\\OpenGLChecker.exe",desktop=L"",shellinfo=L"",runtime=L""}, env=L"SHELL=/bin/sh\0SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/55088,unix/unix:/tmp/.ICE-unix/55088\0COLORTERM=truecolor\0XDG_CONFIG_DIRS=/app/etc/xdg:/etc/xdg\0GREP_COLOR=37;45\0HISTCONTROL=ignoredups\0XDG_MENU_PREFIX=gnome-\0HOSTNAME=aurora\0HISTSIZE=1000\0YSU_MODE=ALL\0LESS_TERMCAP_se=\e[27m\0LESS_TERMCAP_so=\e[7m\0SSH_AUTH_SOCK=/run/user/1000/keyring/ssh\0XDG_DATA_HOME=/home/johnny/.var/app/com.usebottles.bottles/data\0__GL_SHADER_DISK_CACHE_PATH=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Games\0XDG_CONFIG_HOME=/home/johnny/.var/app/com.usebottles.bottles/config\0XMODIFIERS=@im=ibus\0DESKTOP_SESSION=gnome\0LC_MONETARY=en_GB.UTF-8\0SSH_AGENT_PID=4208\0GREP_COLORS=mt=37;45\0FLATPAK_ID=com.usebottles.bottles\0EDITOR=/usr/bin/nano\0ALSA_CONFIG_PATH=/usr/share/alsa/alsa-flatpak.conf\0XDG_SESSION_DESKTOP=gnome\0LOGNAME=johnny\0XDG_SESSION_TYPE=x11\0SYSTEMD_EXEC_PID=55340\0_=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/runners/vaniglia-6.23/bin/wine64\0WINEESYNC=1\0XAUTHORITY=/run/flatpak/Xauthority\0SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0\0container=flatpak\0WINDOWPATH=2\0GDM_LANG=en_US.UTF-8\0GI_TYPELIB_PATH=/app/lib/girepository-1.0\0WINEARCH=win64\0LC_PAPER=en_GB.UTF-8\0LANG=en_US.UTF-8\0WINEPREFIX=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Games\0LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:\0XDG_CURRENT_DESKTOP=GNOME\0VTE_VERSION=6602\0AT_SPI_BUS_ADDRESS=unix:path=/run/flatpak/at-spi-bus\0PULSE_CLIENTCONFIG=/run/flatpak/pulse/config\0INVOCATION_ID=5e5c234fa8394e77ad35d21383e651ea\0MANAGERPID=4084\0PULSE_LATENCY_MSEC=60\0YSU_VERSION=1.7.3\0STEAM_FRAME_FORCE_CLOSE=1\0XDG_CACHE_HOME=/home/johnny/.var/app/com.usebottles.bottles/cache\0MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed\0XDG_SESSION_CLASS=user\0TERM=xterm-256color\0__GL_SHADER_DISK_CACHE=1\0LESS_TERMCAP_mb=\e[1;31m\0LESS_TERMCAP_me=\e[0m\0LESS_TERMCAP_md=\e[1;31m\0LESSOPEN=||/usr/bin/lesspipe.sh %s\0USER=johnny\0WINE_LARGE_ADDRESS_AWARE=1\0DXVK_HUD=compiler\0DISPLAY=:99.0\0SHLVL=1\0LESS_TERMCAP_ue=\e[0m\0LESS_TERMCAP_us=\e[1;32m\0PAGER=less\0FLATPAK_SANDBOX_DIR=/home/johnny/.var/app/com.usebottles.bottles/sandbox\0LC_MEASUREMENT=en_GB.UTF-8\0WINEDEBUG=+all\0STAGING_SHARED_MEMORY=1\0TILIX_ID=4a9ef15f-a5d8-4498-9cea-335d52ff62fd\0LD_LIBRARY_PATH=/app/lib:/app/lib32\0XDG_RUNTIME_DIR=/run/user/1000\0export=\0DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/ \0DXVK_STATE_CACHE_PATH=/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Games\0DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket\0LC_TIME=en_GB.UTF-8\0GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0\0which_declare=typeset -f\0JOURNAL_STREAM=8:428112\0XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share\0__GLX_VENDOR_LIBRARY_NAME=nvidia\0GDMSESSION=gnome\0__GL_DXVK_OPTIMIZATIONS=1\0DBUS_SESSION_BUS_ADDRESS=unix:path=/run/flatpak/bus\0ALSA_CONFIG_DIR=/usr/share/alsa\0__VK_LAYER_NV_optimus=NVIDIA_only\0MAIL=/var/spool/mail/johnny\0__NV_PRIME_RENDER_OFFLOAD=1\0PULSE_SERVER=unix:/run/flatpak/pulse/native\0GIO_LAUNCHED_DESKTOP_FILE_PID=60815\0LC_NUMERIC=en_GB.UTF-8\0OLDPWD=/home/johnny\0WINEDATADIR=\\??\\Z:\\home\\johnny\\.var\\app\\com.usebottles.bottles\\data\\bottles\\runners\\vaniglia-6.23\\share\\wine\0WINEHOMEDIR=\\??\\Z:\\home\\johnny\0WINECONFIGDIR=\\??\\Z:\\home\\johnny\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\Games\0WINEDLLDIR0=\\??\\Z:\\home\\johnny\\.var\\app\\com.usebottles.bottles\\data\\bottles\\runners\\vaniglia-6.23\\lib\\wine\0WINEUSERNAME=johnny\0WINEDLLOVERRIDES=\0WINELOCALE=en-US\0SystemDrive=C:\0SystemRoot=C:\\windows\0ComSpec=C:\\windows\\system32\\cmd.exe\0NUMBER_OF_PROCESSORS=24\0OS=Windows_NT\0PATH=C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0\0PATHEXT=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh\0PROCESSOR_ARCHITECTURE=AMD64\0PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD\0PROCESSOR_LEVEL=23\0PROCESSOR_REVISION=7100\0windir=C:\\windows\0winsysdir=C:\\windows\\system32\0TEMP=C:\\users\\johnny\\Temp\0TMP=C:\\users\\johnny\\Temp\0APPDATA=C:\\users\\johnny\\AppData\\Roaming\0CLIENTNAME=Console\0HOMEDRIVE=C:\0HOMEPATH=\\users\\johnny\0LOCALAPPDATA=C:\\users\\johnny\\AppData\\Local\0LOGONSERVER=\\\\AURORA\0SESSIONNAME=Console\0USERDOMAIN=AURORA\0USERNAME=johnny\0USERPROFILE=C:\\users\\johnny\0ALLUSERSPROFILE=C:\\ProgramData\0ProgramData=C:\\ProgramData\0PUBLIC=C:\\users\\Public\0ProgramFiles(x86)=C:\\Program Files (x86)\0ProgramW6432=C:\\Program Files\0CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files\0CommonProgramW6432=C:\\Program Files\\Common Files\0COMPUTERNAME=AURORA\0ProgramFiles=C:\\Program Files\0CommonProgramFiles=C:\\Program Files\\Common Files\0" )`

**Comment by Bananaman** [comment]
@mirkobrombin Success.

I can confirm now this bug is 100% Bottles fault. (I don't say that to gloat, lol, just to confirm it. I love Bottles and want to help fix it!)

- I looked at the last log message above and noticed the Wine runner path used by Bottles.
- So I decided "Hmm, what if I just call the runner directly without Bottles starting it?"
- So ...

```
$ cd "/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Games/drive_c/OpenGLChecker"
$ /home/johnny/.var/app/com.usebottles.bottles/data/bottles/runners/vaniglia-6.23/bin/wine64 OpenGLChecker.exe
```

Here I saw a brief "Creating /home/johnny/.wine configuration" GUI popup from Wine... and then the Terminal output continued...

```
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.23 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0070:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0080:fixme:imm:ImeSetActiveContext (0x263560, 0): stub
0080:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000263560): stub
002c:fixme:imm:ImeSetActiveContext (0x262790, 1): stub
002c:fixme:imm:ImmReleaseContext (0000000000030064, 0000000000262790): stub
0124:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\notepad.exe" (error=80)
012c:fixme:file:NtLockFile I/O completion on lock not implemented yet
012c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0134:fixme:file:NtLockFile I/O completion on lock not implemented yet
0134:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
013c:fixme:file:NtLockFile I/O completion on lock not implemented yet
013c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0134:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0134:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
012c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
012c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
wine: configuration in L"/home/johnny/.wine" has been updated.
017c:fixme:imm:ImeSetActiveContext (0x64eb10, 1): stub
017c:fixme:imm:ImmReleaseContext (00030054, 0064EB10): stub
017c:fixme:msvcrt:__clean_type_info_names_internal (1000E404) stub
```

And on my X11 screen was... The OpenGL demo running!

So now the issue is:

- Bottles *IS* setting *SOME* variable incorrectly in the environment for Wine on X11, which is breaking OpenGL on my system and probably others too.
- All other flatpaks OpenGL, native OpenGL, even the Bottles runner itself, all work perfectly. It's only Bottles that is broken. That makes me suspect the launch arguments/environment.

**Comment by Bananaman** [comment]
Alright time for the next level of debugging: Checking "What if I run the pure wine runner myself, but INSIDE the Flatpak environment?"

- First, I had to start a shell inside the Flatpak environment:
- `flatpak run --command=sh com.usebottles.bottles` ([Source](https://docs.flatpak.org/en/latest/debugging.html))
- Then, running the same Wine runner and the same executable, but in a "pure" environment without Bottles managing the launching:
- `/home/johnny/.var/app/com.usebottles.bottles/data/bottles/runners/vaniglia-6.23/bin/wine64 /home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/Games/drive_c/OpenGLChecker/OpenGLChecker.exe`
- This popped up a "Wine Mono is missing. Install?" GUI. I clicked install, and it installed that successfully.
- And then...
- The OpenGL demo was running.

So now I've confirmed:

- That the Bottles flatpak/sandbox is not the issue.
- This also coincides with the fact that the native Bottles also has the same problem.
- That the runner used by Bottles is not the issue.
- **That the environment/arguments used by Bottles is the issue.**

The only remaining question is: What's argument/env is Bottles telling Wine that is breaking things?

**Comment by Bananaman** [comment]
@mirkobrombin LOL! This is funny.

## Success, Part 3

I've found it.

- Bottles: Bottle: Preferences: "Discrete GPU".
- Disable this option.
- Now Bottles works.

**Comment by mirkobrombin** [comment]
The `Discrete GPU` option force some env var to ensure that the right GPU is selected. This usually in Optimus laptops is required in hybrid mode. If this broke xorg in non-optimus laptops (PC), I need to figure out how to detect optimus laptop and automatically-enable this only on these. Easy, I'll fix on next release, thanks for debug :)

**Comment by Bananaman** [comment]
@mirkobrombin I guess it's time for a ....

## Success, Part 4

The real fix has been found. It wasn't "Discrete GPU". Turns out that I just toggled that setting as the same time as I had already fixed the issue... The fix... was the Part 2 steps:

- Open a shell in the flatpak.
- Run the wine runner once to let it create a `~/.wine` config inside the Flatpak and install Wine-Mono (it asks the user this via GUI).
- After this, the Flatpak works perfectly, no tweaks needed (I have enabled "Discrete GPU" again).
- I have confirmed this fix with Epic Games Store and with the OpenGLChecker demo/benchmark. :)

Alright, well this is educational. Something about how Bottles initializes wine environment is missed. When Wine runs "plain" once, and makes its own `~/.wine`, this is enough to completely fix Bottles :)

And you're welcome about the debugging. I also greatly thank you for being so responsive with necessary information! I absolutely love Bottles and want it to succeed. It's such a smart project. :)

**Comment by Bananaman** [comment]
@mirkobrombin I have very good news. You may have seen the message I just posted where I thought Discrete GPU wasn't the fix. Well, after about half an hour of extra debugging, I can luckily confirm that it was the reason.

It's just that Bottles GUI is a bit buggy when you use the Installer recipes. The Epic Store installer has `discrete_gpu: True` in the manifest. This re-enables the discrete GPU option, but the GUI doesn't correctly show that it's enabled. I had to enable/disable the setting again to get it to properly disable itself.

I did a totally fresh install of Bottles with no config and can now 100% confirm that the Discrete GPU setting is THE reason. :) WOO!

And you're welcome about the debugging. I also greatly thank you for being so responsive with necessary information! I absolutely love Bottles and want it to succeed. It's such a smart project. :)

**Comment by mirkobrombin** [comment]
:) I hope latest commit fixed this. Now despite the flag status, Bottles will inject that variables only on optimus laptops. The fix will be released with next version (2021.12.28).

Thanks to you for helping me debugging this problem, really appreciated! Merry Xmas too!

**Comment by Bananaman** [comment]
@mirkobrombin Thank you, that looks like a really smart solution! It seems like it scans for display adapters and enables the discrete GPU environment only if it finds 2 or more GPUs?

This is what I get on my system by the way:

```
$ lspci | grep 'VGA.*NVIDIA'
2d:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090] (rev a1)
```

Anyway that looks awesome. I am so happy that Bottles is working now. It's a beautiful application and really solves Linux gaming and Windows apps in a way that I've never seen before. The way I always wished! With everything installed in 1 "wine prefix" with universal settings for all games in there. It's so clean and so much easier to manage this kind of system. :)

**Comment by mirkobrombin** [comment]
If the system (vm or not) has dual gpu (amd+nvidia/intel+nvidia/intel+amd) and you want to use Bottles, I assume that you properly configured your drivers. Now Bottles do a simple check:
- test amd nvidia intel
- if found 2 gpu and one is nvidia it will force this last (if discrete is enabled)
- if found 2 gpu but no one is nvidia it will force dri_prime (still if discrete enabled)
- if only 1 gpu is detected it will return false and no variables are set 

Should be enough (?)

**Comment by Bananaman** [comment]
Yeah, I see what the code is doing. It solves the issue completely for all normal people (most people on desktop have 1 GPU, or 2+ of the same brand), so it's a great fix for most people! :)

The `<0.5%` of users with multiple dedicated desktop GPUs from different brands will hit the "bug" again. I dunno what to do about those people. We could have a ticket where we ask community for a strong way to detect Optimus/PRIME laptops. Or we could just put it in the Wiki to let people know that Discrete GPU can cause issues on non-laptops. Maybe even add a note to the setting in the GUI, which says "May cause issues on non-laptops."? Just as a hint for the `<0.5%` of people who will hit the bug.

**Comment by mirkobrombin** [comment]
Make sense
