### ISSUE TITLE
[BUG] GUI toggles aren't correctly updated when using Installer recipes

### ISSUE THREAD

**Issue by Arcitec** [bottlesdevs/Bottles#850]
Bottles isn't refreshing the settings GUI after/while installing recipes that modify settings.

- Disable Discrete GPU setting.
- Run the Epic Games installer. It will re-enable Discrete GPU.
- Look in the Preferences tab. It will still say that Discrete GPU is disabled, even though the recipe has re-enabled it.
- Leaving the Bottle GUI back to the main Bottle List GUI, and then going back into the Bottle, refreshes the GUI and shows that the setting has changed.

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/commit/4658c64654189da92a69e51e0b90c1311175614c

Installer will keep to update that flag but Bottles will use it only on optimus laptops.

**Comment by Bananaman** [comment]
@mirkobrombin Yeah. :D This isn't about the Discrete GPU bug. This is about Installer manifests changing settings but the Bottles GUI doesn't update the flag. The GUI needs to refresh after an installer changes settings.

Example: So if you disable Discrete GPU, then install EGS, then go to Preferences, "Discrete GPU" will look disabled but it's actually enabled. Leaving the bottle and going back into the bottle will update the Preferences and show the real value.

**Comment by mirkobrombin** [comment]
Postponed to 2022.2.14
