### ISSUE TITLE
[Request] Notes section for individual bottles

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#851]
It would be beneficial to have a "Notes" section for individual bottles. Perhaps either a separate tab like "Versioning/Programs/Task manager" except called Notes or just a sub in the Details & Utilities.

This would be helpful for us to leave notes for the bottle as to any tweaks we had to make so everything runs fine. Sure you could use an external application to keep notes like Joplin but why not have a section within the bottle that actual relates to it?

As to what it should look like, if it's a separate tab like "Versioning/Programs/Task manager"  then it should be a big text entry box where we could enter bullet points

If it's a sub inside Details & Utilities or somewhere, it could be a simple 1 or 2 high text entry box where we could write stuff like "vaniglia-6.21 runner causes stutters, use the vaniglia-6.18 runner for now." or "I had to make a registry edit to be able to run the game" or "used the -novid launch command to skip the loading videos for games".

**Comment by mirkobrombin** [comment]
I don't know if it's actually more convenient to have it in bottles or an external program. I have to think about it.

**Comment by mirkobrombin** [comment]
Actually out-of-scope. If you need to takes notes, just use a text editor o note app. I hate closing issues but this feature is actually wrong to implement and just require effort which I want to dedicate to other things like layers, dependencies and our installers.
