### ISSUE TITLE
[Request] Ideas for DXVK.conf Management

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/Bottles#852]
I just ran my first game in Bottles flatpak, with EGS store, vaniglia 7, vkd3d-proton 2.5, nvapi 0.5.1, and dxvk 1.9.2.

HITMAN 3. It runs beautifully. :)

However, I discovered that the game's own DXVK log says:

```
DXGI: NvAPI workaround enabled, reporting AMD GPU
```

This confirms my suspicion that Bottles doesn't manage any dxvk.conf file.

So I created `dxgi.conf` next to the game's `.exe`, and put `dxgi.nvapiHack = False`.

That's necessary for enabling NVAPI/DLSS. Otherwise it pretends to be an AMD GPU and NVAPI won't be used by the game.

It just made me wonder, is there anything Bottles can do about this?

For example:

- When `Enable DLSS (NVAPI-DXVK)` is enabled in Bottles config, we could give a simple environment variable:
- `DXVK_CONFIG_FILE=/path/to/dxvk-no-nvapihack.conf`
- This could be a simple, global config file stored inside the Bottle somewhere, with just the `dxgi.nvapiHack = False` instruction.
- This change would mean that all games can see the NVIDIA GPU and will be using NVAPI.
- I think the user can still place a dxvk.conf in the game folder and override more settings, but I am not sure. Either way, this is the only setting 99% of users use in DXVK. :D

I dunno. What are your thoughts about this? The "Enable DLSS (NVAPI)" switch in Bottles currently does "nothing" (game thinks you have an AMD GPU and won't use NVAPI) until the user manually creates a dxvk.conf, so perhaps there are some ideas to make the integration better?

If we have this default environment variable, users will be happier since NVAPI/DLSS won't require a manual dxvk.conf file.

**Comment by mirkobrombin** [comment]
I think it is possible to automate this flow https://github.com/jp7677/dxvk-nvapi#how-to-use sad enough they don’t say to users how to enable in Bottles 🥲

 Btw I’ll implement this in next release.

**Comment by mirkobrombin** [comment]
I saw [this article](https://www.gamingonlinux.com/2021/10/proton-experimental-expands-nvidia-dlss-support-on-linux-to-directx-11-titles/) about DLSS support with Proton on Steam using the env `PROTON_HIDE_NVIDIA_GPU` (or the dxvk conf file) so I looked in the Proton source code and appear that env var just [set another `WINE_HIDE_NVIDIA_GPU` var](https://github.com/ValveSoftware/Proton/blob/50b4c8785f389f0840bfc6a9ee3f233c9de2da48/proton#L1051) that should do the trick. Maybe can you try with it?

**Comment by Bananaman** [comment]
@mirkobrombin I will investigate what steps are needed! :)


What I know so far:

- **Need:** We must load the DXVK DLL, but Bottles already does this. :) That's described here: https://github.com/jp7677/dxvk-nvapi#wine

- `dxgi.customVendorId = 10de` in dxvk.conf: **Don't do this.** This is for making games think that Intel/AMD GPUs are NVIDIA GPUs. All real NVIDIA GPUs already have vendorID 10de. This is just some weird setting that attempts to use NVAPI.dll on non-NVIDIA hardware, which is weird.

- **Need:** `dxgi.nvapiHack = False` in dxvk.conf: **This is needed.** Otherwise DXVK-NVAPI pretends that you have an AMD GPU. And it's easy to do this one with a global dxvk config variable. :) All Bottles has to do is somehow ensure that the global dxvk conf file always exists and gets re-created if deleted in the bottle.

- **Avoid:** `PROTON_ENABLE_NVAPI=1` env: **Don't do this.** It tells the Proton-based runners to load the dxvk-nvapi DLL that is bundled inside Proton. We shouldn't be using the Proton runner anyway since it has very deep integration with Steam nowadays and doesn't run properly outside Steam due to lacking environment variables and steam-gameid etc, which means that the Proton "game compatibility improvements" are *not even active at all* if Proton runs outside of Steam. Plus, Proton nowadays runs games with something they call "pressure-vessel" which is another sandbox which breaks when you don't run Proton via Steam (this comment is by GloriousEggroll "GE" :D): https://github.com/lutris/lutris/pull/3330#issue-752329327

- **Need:** `PROTON_HIDE_NVIDIA_GPU ---> WINE_HIDE_NVIDIA_GPU`: Great discovery. **We need this.** I think I understand what this is for, since the explanation is pretty good at the DXVK-NVAPI page. Basically, most games ask DirectX what GPU the user has, and DXVK already correctly replies "nvidia", so most games already work without this. But some games use another technique to look at GPU, and that's what this flag is for. It fixes NVIDIA detection for a tiny number of games that use other ways to query the GPU vendor.

This is the complete list. If we support Proton runner we need the proton-specific variables instead, but we shouldn't be using Proton.

I am gonna install some DLSS games and experiment with these variables to make sure it works! :smile:

**Comment by mirkobrombin** [comment]
> Avoid: PROTON_ENABLE_NVAPI=1 env: Don't do this. It tells the Proton-based runners to load the dxvk-nvapi DLL that is bundled inside Proton. We shouldn't be using the Proton runner anyway since it has very deep integration with Steam nowadays and doesn't run properly outside Steam due to lacking environment variables and steam-gameid etc, which means that the Proton "game compatibility improvements" are not even active at all if Proton runs outside of Steam. Plus, Proton nowadays runs games with something they call "pressure-vessel" which is another sandbox which breaks when you don't run Proton via Steam (this comment is by GloriousEggroll "GE" :D): lutris: remove proton support from lutris lutris/lutris#3330 (comment)

Discussing here: https://github.com/bottlesdevs/Bottles/issues/749

> This is the complete list. If we support Proton runner we need the proton-specific variables instead, but we shouldn't be using Proton.

As Wine-GE is actually Proton-GE but meant to be used out of Steam, we should not put effort on it.

> Need: PROTON_HIDE_NVIDIA_GPU ---> WINE_HIDE_NVIDIA_GPU: Great discovery. We need this (the WINE variable). I think I understand what this is for, since the explanation is pretty good at the DXVK-NVAPI page. Basically, most games ask DirectX what GPU the user has, and DXVK already correctly replies "nvidia" (when DXVK.conf contains dxgi.nvapiHack = False, to enable true GPU vendor reporting), so most games already work without this. But some games use another technique to look at GPU, and that's what this flag is for. It fixes NVIDIA detection for a tiny number of games that use other ways to query the GPU vendor.

> - Install nvapi.dll from DXVK-NVAPI and tell Wine to use "native DLL" for it to make sure it's loaded.
> - Help the game detect NVIDIA so that the game tries to load nvapi.dll: See below.
> - Stop DXVK hiding NVIDIA GPU (most games detect NVIDIA this way): `dxvk.conf: dxgi.nvapiHack = False`
> - Stop WINE hiding NVIDIA GPU (some games detect NVIDIA this way): `WINE_HIDE_NVIDIA_GPU=0`
> - I don't know if anything special is needed in VKD3D but I don't think so! DXVK-NVAPI project doesn't mention it and I've never heard of specific tweaks for VKD3D NVAPI.

So still need both env var and taht rule set in dxvk.conf file. I think the better way to display these in the GUI is just:
- if DLSS is enabled: ensure that dxvk.conf exist and contain that rule, otherwise just create and/or add it automatically
- add another option in Advanced section "Tell WINE to hide my GPU", so on toggle it just inject `WINE_HIDE_NVIDIA_GPU=0` on next commands
