### ISSUE TITLE
Improve first-time experience

### ISSUE THREAD

**Issue by hadess** [bottlesdevs/Bottles#86]
When running bottles for the first, the only thing I get is this unparented dialogue.

![Screenshot from 2021-01-08 11-19-57](https://user-images.githubusercontent.com/769861/104004211-c31e6400-51a3-11eb-98f0-ec1f66b2fab5.png)

It doesn't mention the software name (it's barely visible at the top of the screen in the activities), and doesn't mention the latest version of what is downloaded, or from where, or explain what a "Runner" is. It would be useful to instead follow an "empty state" design pattern, that would allow for more control before downloading anything.

https://wiki.gnome.org/Design/OS/EmptyStates

**Comment by hadess** [comment]
It should also be "There are no runners on the system".

**Comment by mirkobrombin** [comment]
Please follow the Bug template next time if you intend to report a bug.

**Comment by hadess** [comment]
I used the Flathub version installed today. Is anything else missing from the report? There are a lot of problems with the UI, I just want to know if you're interested in them.

**Comment by mirkobrombin** [comment]
We are very interested. We are already working on a complete restyle of the application to improve usability. Thanks for the reports, what we can improve immediately we do it, the rest ends up in the redesign project.

**Comment by hadess** [comment]
> We are very interested. We are already working on a complete restyle of the application to improve usability. Thanks for the reports, what we can improve immediately we do it, the rest ends up in the redesign project.

OK, I might wait until that's done then. The other problems I've seen were problems with the UI (the Downloads popup wasn't popping down when you clicked on it, the Download Manager inside the app not using application-wide notifications, for example), so it might not be worth filing more bugs until you've made those changes.

**Comment by mirkobrombin** [comment]
> > We are very interested. We are already working on a complete restyle of the application to improve usability. Thanks for the reports, what we can improve immediately we do it, the rest ends up in the redesign project.
> 
> OK, I might wait until that's done then. The other problems I've seen were problems with the UI (the Downloads popup wasn't popping down when you clicked on it, the Download Manager inside the app not using application-wide notifications, for example), so it might not be worth filing more bugs until you've made those changes.

The downloads popup should appear. If this does not happen, it should be a bug reported separately (following the template) by specifying the package.

**Comment by hadess** [comment]
> The downloads popup should appear

Popping down is the opposite of popping up. It wasn't closing when you clicked on the "Downloads manager" item in it. As I mentioned, I'll wait until the redesign is done to spend more time on this.

**Comment by mirkobrombin** [comment]
I close the issue as the problems have already been addressed and will come with the new design. I will no longer be making major design changes in the master branch. Works on implementing the new UI are in the refresh branch now for anyone who wants to test and collaborate.

**Comment by hadess** [comment]
> I close the issue as the problems have already been listed and fixes will come with the new design.

FWIW, I won't be testing the new version. I would expect issues to be closed when things are fixed (or reasonably thought to be fixed). I don't have the time to monitor a branch until that problem is eventually fixed to 
> test and collaborate.

**Comment by mirkobrombin** [comment]
> > I close the issue as the problems have already been listed and fixes will come with the new design.
> 
> FWIW, I won't be testing the new version. I would expect issues to be closed when things are fixed (or reasonably thought to be fixed). I don't have the time to monitor a branch until that problem is eventually fixed to
> 
> > test and collaborate.

Nobody asked you to do that 👀
For our better organization we monitor the case in the "refresh" project, available on figma as a concept or in the branch branch as a release.

**Comment by hadess** [comment]
How do I know when I can test the fix then?

**Comment by mirkobrombin** [comment]
> How do I know when I can test the fix then?

We cannot merge the new UI now into the master branch (it would be a disaster). The current release is will not receive any other UI improvements. When the new UI is ready we will release AppImage for testing so you and others can express all your disappointments (or compliments) before the final release.

Alternatively (as you've been  [told](https://github.com/bottlesdevs/Bottles/issues/88#issuecomment-756695605)) you can follow Bottles redesign [here](https://www.figma.com/file/2o1rKcFToABvzJFcxyy2v3/Bottles-Refresh?node-id=0:1), without having to install anything. And leave any comments [here](https: //github.com/bottlesdevs/Bottles/issues/77).

**Comment by hadess** [comment]
That's not how issue management is usually done, but it's your project.

**Comment by mirkobrombin** [comment]
> That's not how issue management is usually done, but it's your project.
I see absolutely no reason to keep 2 or 3 issues open for the exact same problem.

This is not "my project and therefore I do what I want". The problem was simply reported earlier by other users who immediately started working together to improve the design of the application and fix these problems. This is the kind of support we need.

**Comment by hadess** [comment]
I'm glad you found people who had the time to contribute to your application. I was just asking for issues not to be closed until the problems they report are fixed, nothing else.

> This is the kind of support we need.

Sorry I don't have time to contribute more directly to your project and instead spend my time working on the OS and desktops your project rely on :(

**Comment by mirkobrombin** [comment]
> I'm glad you found people who had the time to contribute to your application. I was just asking for issues not to be closed until the problems they report are fixed, nothing else.
> 
> > This is the kind of support we need.
> 
> Sorry I don't have time to contribute more directly to your project and instead spend my time working on the OS and desktops your project rely on :(

I think I explained myself badly, probably my English is not the best. This like other issues are linked to #77, it is only for my best organization not to have more issues for the same issue. We just monitor everything in that issue.
