### ISSUE TITLE
[BUG] Enter/space on a button doesn't do anything, only clicks work

### ISSUE THREAD

**Issue by braiam** [bottlesdevs/Bottles#861]
Buttons like "new bottle", "Cancel"/"Save" in dialog boxes ignore keyboard enter/space, but it works with on/off toggles, submenus (like notifications, preferences), dropdowns (like FSR option, virtual desktop size).

Buttons should be aware of keyboard input and be consistent with the rest.

**Comment by Githob2021** [comment]
Adding a +1 to this.

It's not intuitive to have to click the pencil again after renaming a bottle. Both Enter or clicking the pencil icon should save the change.

**Comment by mirkobrombin** [comment]
Planning for 2022.1.14

**Comment by mirkobrombin** [comment]
> Adding a +1 to this.
> 
> It's not intuitive to have to click the pencil again after renaming a bottle. Both Enter or clicking the pencil icon should save the change.

Merging here: https://github.com/bottlesdevs/Bottles/issues/862
