### ISSUE TITLE
[Request] Enter in a text input should submit/continue the view

### ISSUE THREAD

**Issue by braiam** [bottlesdevs/Bottles#862]
When naming a new bottle, enter doesn't do anything in the box. One would expect that it should submit the form in the state it's is. This happens on the following text input:

- Versioning naming
- Renaming bottle
- Changing launch options of a program
- Program environment variable
- Creating a bottle

Those are the only ones I've found. I've also found that enter and space are ignored in buttons, but [that's another bug report.](https://github.com/bottlesdevs/Bottles/issues/861)

**Comment by mirkobrombin** [comment]
Planning for 2022.1.14

**Comment by mirkobrombin** [comment]
Merging this: https://github.com/bottlesdevs/Bottles/issues/861#issuecomment-1001072124 here.
