### ISSUE TITLE
[BUG] Unable to install dotnet35 in the Flatpak version

### ISSUE THREAD

**Issue by guihkx** [bottlesdevs/Bottles#864]
**Describe the bug**
I'm unable to install the `dotnet35` component due to (probably) missing dependencies in the Flatpak version.

**Installation**
 - Method: Flatpak
 - Version: 2021.12.14-treviso-4

**To Reproduce**
1. Launch Bottles in the terminal:  `flatpak run com.usebottles.bottles`
2. Try to install the `dotnet35` component on any existing bottle (tested on a 64-bit one)
3. The `dotnet35` installer will fail:

    ```
    (09:43:17) INFO Installing dependency [dotnet35] in bottle [net35test]. 
    (09:43:20) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\AppDefaults\dotnet35.exe] with Value: [Version] and Data: [winxp] in register bottle: net35test 
    (09:43:20) INFO reg: The operation completed successfully
	
    (09:43:20) WARNING File [dotnet35.exe] already exists in temp, skipping. 
    (09:43:21) INFO Running an executable on the bottle… 
    0158:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
    0158:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
    0158:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
    (09:43:33) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscoree] and Data: [native,builtin] in register bottle: net35test 
    (09:43:34) INFO reg: The operation completed successfully
    ```

**Expected behavior**
Although Bottles claims the installation was successfully, it wasn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/626206/147408622-8324065d-03bb-4f68-87df-1efde139cc7e.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: rolling release
 - Display server: X11

**Comment by mirkobrombin** [comment]
Can reproduce on AppImage and AUR package

**Comment by guihkx** [comment]
> Update: Also using wine outside Bottles

Weird. I can't reproduce it with vanilla wine-7.0rc1.

Since you're also on Arch, can you try first installing the `samba` package and then switching the runner to `sys-wine-7.0-rc1` on Bottles? It should work after that in either AppImage or AUR Bottles, but not on Flatpak still.

**Comment by mirkobrombin** [comment]
> > Update: Also using wine outside Bottles
> 
> Weird. I can't reproduce it with vanilla wine-7.0rc1.
> 
> Since you're also on Arch, can you try first installing the `samba` package and then switching the runner to `sys-wine-7.0-rc1` on Bottles? It should work after that in either AppImage or AUR Bottles, but not on Flatpak still.

I'm on Silverblue, I use a VM for Arch. I was using Vaniglia not the system one. I can confirm that sys-wine is working.

**Comment by mirkobrombin** [comment]
| Runner                | Flatpak | Appimage/AUR |
| ---------------------- | ---------- | --------------------- |
| Vaniglia 7.0 RC2 | N          | N                        |
| Vaniglia 6.21       | N          | N                        |
| Lutris 6.21           | Y          | Y                        |
| sys-wine             | n/a        | Y                        |


I can confirm that the problem is Vaniglia related

**Comment by guihkx** [comment]
Cool, the .NET installer now launches in the Flatpak version if I use the `lutris-6.21-6` runner. But it will only launch after I change Wine's version to Windows XP beforehand, and even then, the installer fails at some point. 🤷

**Comment by mirkobrombin** [comment]
> Cool, the .NET installer now launches in the Flatpak version if I use the `lutris-6.21-6` runner. But it will only launch after I change Wine's version to Windows XP beforehand, and even then, the installer fails at some point. shrug

I've updated the dependency manifest, now should the installation should change the windows version to xp and restore after installation. This do not require a software update, just restart Bottles

**Comment by guihkx** [comment]
Hmm, unfortunately I don't think that did anything. :(

After the installer extracts some files, this error pops up:

![image](https://user-images.githubusercontent.com/626206/147420192-4cde5963-db00-462c-b069-3da81badc6d0.png)

Here's what I did, step-by-step:

https://user-images.githubusercontent.com/626206/147420370-108524d0-761a-4b60-9946-1b7b815004df.mp4

**Comment by mirkobrombin** [comment]
Because it is not setting windows xp for some reason, the workaround is to manually set the win version to winxp, btw I think you need a fix I've made today, as in 64bit bottles the winxp version should be winxp64

**Comment by guihkx** [comment]
Yup, that workaround works. Now regarding these two errors:

```
0158:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0158:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0158:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```

Do you think we'd get rid of this error if you partially shipped Samba in the Flatpak version of Bottles?

**Comment by mirkobrombin** [comment]
Yup but I'm still looking on this, idk where to fetch that package

**Comment by guihkx** [comment]
I've been experimenting locally... While I was able to build the 64-bit libraries of krb5, I'm getting some weird error while building the 32-bit version. I haven't tried building samba yet, but I guess it's going to be even harder.

**Comment by mirkobrombin** [comment]
The new caffe-6.23 runner (coming as new default in Bottles 2021.12.28) is able to run it!

![image](https://user-images.githubusercontent.com/9479903/147489173-c40c7150-8064-4b54-b3d0-1d1219f32be6.png)

**Comment by guihkx** [comment]
Are you able to complete the installation, though?

**Comment by mirkobrombin** [comment]
> Are you able to complete the installation, though?

![image](https://user-images.githubusercontent.com/9479903/147489655-a106f493-aef6-4c5a-be45-6f1d8bb3a14a.png)

Fails after this view, still need samba I think

**Comment by mirkobrombin** [comment]
It was failing but.. has installed the needed files :|

**Comment by guihkx** [comment]
Yeah, mine's there also. I managed to package samba and kerberos (both 32 and 64 bit libraries), but I'm still getting the `err:kerberos:kerberos_LsaApInitializePackage` error. The `ntlm_auth` one is gone, though. I don't get those with AUR bottles...

So I think I either mispackaged krb5, or that error has nothing to do with the installation failing and the culprit is something else

**Comment by mirkobrombin** [comment]
I think too

**Comment by guihkx** [comment]
Got this answer from a Wine dev:

![image](https://user-images.githubusercontent.com/626206/147500824-107fbf0a-6f97-49e1-8c58-46844d573d26.png)

So it may indicate my packaging of the kerberos lib is incorrect. Will investigate.

**Comment by mirkobrombin** [comment]
let me know

**Comment by guihkx** [comment]
Closing in favor of: https://github.com/bottlesdevs/documentation/issues/12

**Comment by SuNNjek** [comment]
Is the ntlm_auth error supposed to be fixed with `--allow=devel`? I'm still getting the `ntlm_auth was not found or is outdated` when running the flatpak on Arch with Samba installed. Just trying to understand if I'm doing something wrong here.
