### ISSUE TITLE
[BUG] Cannot manipulate the LDT on Flatpak

### ISSUE THREAD

**Issue by xerz-one** [bottlesdevs/Bottles#868]
When trying to run [some random old program](https://clic.xtec.cat/legacy/en/clic3/download.htm) with Bottles under Flatpak, the following error pops up:

```
modify_ldt: Operation not permitted
wine: Unhandled page fault on read access to 000002F8 at address 7E267241 (thread 010c), starting debugger...
Can't attact process 0104: error 5
```

The culprit might be Flatpak not allowing manipulation of LDT entries, and seems to align with a ticket over at Lutris: https://github.com/flathub/net.lutris.Lutris/issues/85

**Comment by mirkobrombin** [comment]
I’m aware of this, waiting for news on flatpak front

**Comment by Githob2021** [comment]
I've also run into this problem before. Have you considered implementing the temporary workaround that the Lutris team had:

"Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?

Removing these lines should do:
https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2899-L2901"

Considering this issue has been open since December 2019 (2 years ago) you may be waiting a while for news from the Flatpak front.

**Comment by mirkobrombin** [comment]
Are you sure Lutris is patching Flatpak? It sounds weird :D

**Comment by Githob2021** [comment]
> Are you sure Lutris is patching Flatpak? It sounds weird :D

That's a good point. Looks like it used to lead to this link https://flathub.org/apps/details/net.lutris.Lutris but is no longer available.

Either way, it would be appreciated if you could test or implement that temporary patch/workaround until Flatpak does whatever they need to do.

**Comment by mirkobrombin** [comment]
Ya but such patch is for flatpak (the “whole flatpak project”) not just our Bottles flatpak. This mean ther users should replace their flatpak support with our one 😅

**Comment by xerz-one** [comment]
Oh, did this get fixed already? Why did the ticket get closed?

**Comment by mirkobrombin** [comment]
> Oh, did this get fixed already? Why did the ticket get closed?

Just missclicked 😅

**Comment by zihaaad** [comment]
according to [this](https://www.reddit.com/r/leagueoflinux/comments/u6p78v/comment/i5djmtg/?utm_source=share&utm_medium=web2x&context=3) it looks like this command need to run seperately ` sudo sysctl -w abi.vsyscall32=0` I haven't personally tested this.

**Comment by RobOT05442309** [comment]
Hello [mirkobrombin](https://github.com/mirkobrombin), first, thank you for all the work to make wine so easy to use by providing Bottles. I just wondering if you have been able to get some news from Flatpak side on this issue ?  Availability to allow withelisting temporary LDT when necessary or other workaround ? Or this issue/request on Flatpak seems to be doomed and will stay that way ?

Thanks for your feedback!

**Comment by mirkobrombin** [comment]
Unfortunately at the moment there are no news or workarounds, sorry

**Comment by TheEvilSkeleton** [comment]
Good news! https://github.com/flatpak/flatpak/pull/5082 fixes the issue and allows `modify_ldt`. This should be released in the next release. I'm closing this issue since it's outside of our control anyway.
