### ISSUE TITLE
Unlabeled entry when creating new "bottle"

### ISSUE THREAD

**Issue by hadess** [bottlesdevs/Bottles#87]
![Screenshot from 2021-01-08 11-26-31](https://user-images.githubusercontent.com/769861/104004855-9028a000-51a4-11eb-8661-5975a6e153ae.png)

I don't know what I'm supposed to put in that field.

**Comment by mirkobrombin** [comment]
Follow the Bug template if you want to report a bug please.

**Comment by hadess** [comment]
> Follow the Bug template if you want to report a bug please.

[Same answer applies](https://github.com/bottlesdevs/Bottles/issues/86#issuecomment-756682853).

**Comment by mirkobrombin** [comment]
I know what are you talking about, just reference to one issue for all the UI related problems.

I also bring to your attention the redesign project: https://github.com/bottlesdevs/Bottles/issues/77

**Comment by mirkobrombin** [comment]
Also, this is not an empty entry. The cursor focus has removed the placeholder text.

**Comment by hadess** [comment]
It's the first focusable widget on the page, so it's focused by default, so it's empty by default :)
A label for the entry would fix that problem. The common design pattern for this in GNOME is to use GtkListBoxes and one row per item, so the path configuration below could also use its own list box row and expand when a custom path is used.

**Comment by mirkobrombin** [comment]
> It's the first focusable widget on the page, so it's focused by default, so it's empty by default :)
> A label for the entry would fix that problem. The common design pattern for this in GNOME is to use GtkListBoxes and one row per item, so the path configuration below could also use its own list box row and expand when a custom path is used.

    Closed for the same reason as #86.
