### ISSUE TITLE
[BUG] Xfce-terminal unknown option -c

### ISSUE THREAD

**Issue by Caticer** [bottlesdevs/Bottles#870]
**Describe the bug**
I can't launch wine terminal. It gives:
`xfce4-terminal: Unknown option "-c"
`
**Installation**
 - Method: Meson build
 - Version: 2021.12.14-treviso-4

**To Reproduce**
1. Go to 'bootle you created previusly'
2. Click on 'Commandline'

**Expected behavior**
wine command line with xfce4-terminal

**Screenshots**
![Ekran görüntüsü_2021-12-29_03-18-51](https://user-images.githubusercontent.com/25691875/147607819-a4e3d011-85dc-47fa-922f-5f982f9dcd5d.png)
"Bilinmeyen se?enek" is means Unknown option btw. sorry for language

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Version: latest
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Thanks for reporting
