### ISSUE TITLE
[BUG] New Rename feature isn't working as intended

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#876]
Flatpak 2021.12.28-treviso

I tried the new feature of renaming an .exe and instead of renaming the one in the programs list, it added a new one with the new name (it works) but also kept the old one.

I then tried to remove the old one with the old name from the "Programs" tab and instead it removed both of them until I hit refresh and then only the old one is there.

I would have thought by renaming it would actually rename the current one and not just clone/make a new one. In which case there should be a command that automatically runs to remove the old one instead of making the user do it manually. Currently it is more like "clone+rename" instead of "rename"

But if you still need the old one to make the new named one to work, then it should clone+hide it automatically.

Screenshots

Renamed from the Details & Utilities tab:
![20211229-162718](https://user-images.githubusercontent.com/93590337/147705151-a504d5d2-3bfe-47a2-b885-75d22143a519.png)

Went to Programs tab to remove the old one
![20211229-162911](https://user-images.githubusercontent.com/93590337/147705163-19599c8e-c15d-44e1-a2f0-653c4c9e0426.png)

Both are removed
![20211229-163327](https://user-images.githubusercontent.com/93590337/147705172-81f21c7a-4e53-45cd-88d2-7236ed9c3a1a.png)

Hit refresh and only the old one remains. New one is gone
![20211229-163331](https://user-images.githubusercontent.com/93590337/147705180-2482b263-cda7-4383-8018-1934b67d2fa1.png)

**Comment by mirkobrombin** [comment]
Uuopps 👀
