### ISSUE TITLE
[BUG] Bottles gaming profile create a wineprefix which programs can't find D3DCOMPILER_43.dll

### ISSUE THREAD

**Issue by braiam** [bottlesdevs/Bottles#878]
**Describe the bug**
The gaming profile installs by default the d3dcompiler_43 setting up native,builtin dll override. This produces errors where the program can find the dll in the prefix. Creating a clean prefix using wine directly, doesn't produce this issue.

**Installation**
 - Method: debian package
 - Version 2021.12.14-treviso-3

**To Reproduce**
1. Create a gaming bottle
2. Add vcredist2019
3. Run hotwheels.exe (this is from epicgames)
4. Program doesn't start
5. Running from the command line shows the following error:

    ```
    01b4:err:module:import_dll Loading library D3DCOMPILER_43.dll (which is needed by L"Z:\\mnt\\games\\legendary\\HOTWHEELSUNLEASHED\\hotwheels\\Binaries\\Win64\\EpicGamesStore\\hotwheels-Win64-Shipping.exe") failed (error c000007b).
    01b4:err:module:LdrInitializeThunk Importing dlls for **L"Z:\\mnt\\games\\legendary\\HOTWHEELSUNLEASHED\\hotwheels\\Binaries\\Win64\\EpicGamesStore\\hotwheels-Win64-Shipping.exe"** failed, status c0000135
    01ac:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 0000000000B9FD70
    ```

**Expected behavior**
It should be able to find the library and go its merry way.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version Testing
 - Display server: xorg

**Additional context**
While I understand the rationale to installing dx libraries by default, it seems that I would need to use custom to make sure that this doesn't happen. Also, I'm unable to remove it, which seems counter-intuitive.

**Comment by mirkobrombin** [comment]
Hi, what runner is using?

**Comment by braiam** [comment]
@mirkobrombin both Vaniglia and systemwine produce the same behavior.

**Comment by mirkobrombin** [comment]
Is the flatpak working?

**Comment by Githob2021** [comment]
This is a really similar/same issue I brought up last week for a game I can't run either but others can using winetricks apparently.

https://forums.usebottles.com/d/31-age-of-empires-ii-hd-winetricks-equivalent-workaround-not-working-in-bottles/5

**Comment by Noobao** [comment]
Same issue when trying to use it in Sherlock Holmes - Crimes & Punishments and  Observer system redux (The gog version)

**Comment by braiam** [comment]
@mirkobrombin I don't expect the flatpak to be any different, since avoiding using bottles while using wine directly (wineprefix=bottle) yields the same result. A custom profile, however, that doesn't have installed any dependency is capable of working as intended.

**Comment by mirkobrombin** [comment]
> 

If it works on a “standard” prefix why don’t you use the custom ento to create a vanilla prefix?

The gaming env provide a lot of tweaks and dependencies, maybe that game does work with these.

**Comment by mirkobrombin** [comment]
> @mirkobrombin I don't expect the flatpak to be any different, since avoiding using bottles while using wine directly (wineprefix=bottle) yields the same result. A custom profile, however, that doesn't have installed any dependency is capable of working as intended.

I expect it. Each software thinks in its own way, it depends on how it was written by the developer, it depends on his choices and a configuration does not necessarily work everywhere. Gaming and Software environments are meant to provide the most commonly used set of tweaks and dependencies to make an executable work but I don't expect that to be THE solution all the time.

**Comment by braiam** [comment]
@mirkobrombin So, flatpaks don't even reach that point, with being unable to load winusb.sys:

```
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
006c:err:module:open_builtin_so_file failed to load .so lib "/home/braiam/.var/app/com.usebottles.bottles/data/bottles/runners/caffe-6.23-x86_64/lib/wine/x86_64-unix/wineusb.sys.so"
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
```

This happens with any runner: caffe 6.23 64bit and undetermined, vagnilla 6.23 and 6.21, Proton-6.21-GE-2. So that's a non-starter. (Proton also threw a bunch of errors about wrong ELF, but the script seems to correctly identify as a 64bit prefix, so I don't know what's going on there) There's nothing on the documentation that says that I should configure the flatpak differently.

But I reiterate, the d3dcompiler_43 task is very unlikely to not be the culprit of this. I expect that any prefix that follows that recipe to have the problem described, flatpak or no flatpak, since it's [the only dependency](https://github.com/bottlesdevs/dependencies/search?q=d3dcompiler_43) that munges with that dll.

**Comment by Bananaman** [comment]
@mirkobrombin Hello. I got this d3dcompiler error too. think it's a regression in Bottles.

- Bug appeared: `2021.12.28`
- No bug: `2021.12.14-treviso-4`

I downgraded Bottles like this:

```
sudo flatpak update --commit=7e871de14ec935e654140814602996e31d2ca8ee72301bb8befc40872f7335ad com.usebottles.bottles
```

Then I can run programs again.

**Comment by Bananaman** [comment]
@mirkobrombin Today I updated to `2022.1.14-trento-2` and can confirm the issue is fixed. :) <3

**Comment by 1player** [comment]
Fixed for me as well with the latest version, but I had to create a new prefix. I'm not getting the error anymore with caffe-7.0
