### ISSUE TITLE
vaniglia 7.0 rc2 unstable- epic games store flickers

### ISSUE THREAD

**Issue by bv94** [bottlesdevs/Bottles#879]
**Describe the bug**
**(vaniglia bug)**
epic games launcher flickers
ui elements get drawn, stay for like 500ms
then windows goes blank, then windows redraws ui and so on and so forth

**Installation**
 - Method: flatpak
 - Version: 2021.12.28-treviso

**To Reproduce**
1. use vaniglia-7.0-rc2-unstable(with proton epic games runs fine, but some apps dont run with proton, vaniglia works with everything but epic games)
2.dxvk 1.9.2, vkd3d-v2.4 , dxvk-nvapi = off, amd fsr = balanced, aco shader compiler = on(i tried turning it off, didnt help), gamemode = on

note. it works just fine with proton 7.0 rc2 ge1
(edit: note i tried using vaniglia 6.23, caffee 6.23, pretty much the same)
i really wanted to only use vaniglia cuz everything works with it except for epic games store, : (

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: pop os gnome 21.10
 - Version 21.10
 - Display server: gnome, Wayland(i guess)

**Comment by mirkobrombin** [comment]
How did you install epic? If using our installer, this is because it store the executable arguments in the wrong way. As a workaround: just go to the programs section, look for Epic and set Launch Options ‘ -opengl -SkipBuildPatchPrereq’ (also if already exists), then save and it works.

**Comment by bv94** [comment]
caffee has the same issues

**Comment by mirkobrombin** [comment]
> caffee has the same issues

I didn't say that coffee solves but that it gives greater performance. To get epic through our installer (which is experimental I remember, so there are bugs and not a few) you need to follow the instructions I told you or wait for the fix in the next release.
