### ISSUE TITLE
[BUG] Bottles "Programs" tab doesn't detect Scrivener 3 being installed

### ISSUE THREAD

**Issue by danutsu** [bottlesdevs/Bottles#882]
**Describe the bug**
After installing Scrivener 3 (https://www.literatureandlatte.com/download_action.php?url=https://scrivener.s3.amazonaws.com/Scrivener-installer.exe) it doesn't show up in the Programs list of the Bottle.

**Installation**
 - Method: Flatpak from Flathub via GNOME Software
 - Version: 2021.12.28-treviso

**To Reproduce**
1. Create a new "Software" bottle.
2. Download and run Scrivener from https://www.literatureandlatte.com/scrivener/download
(64-bit version, but bug also reproduces with 32-bit version)
3. After installation completes, go to Programs tab and click Refresh

**Expected behavior**
Scrivener appears in list of installed programs.

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 35
 - Display server: Wayland

**Comment by mirkobrombin** [comment]
I think we are not monitoring that path, let me check

**Comment by tinkicker** [comment]
I have the same issue on Xubuntu 20.04.

**Comment by mirkobrombin** [comment]
Where is located the .lnk file? So I can add its path

**Comment by danutsu** [comment]
I think it's in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Scrivener 3 (at least on my Windows machine, that's where it is)

**Comment by danutsu** [comment]
Hey, are you sure about that commit? Doesn't line 605 overwrite the results of line 602? Also, line 609, right below, seems to already be scanning this folder, so perhaps there's a different issue with the Scrivener 3 link? 

Of course, I'm not familiar with your codebase!

**Comment by mirkobrombin** [comment]
Nvm you are right 🙃 was right there lol

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/159329748-c732deb3-3df3-4d29-be54-daaf8ddc1061.png)

Seems fixed now (2022.3.28 development release).

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/159329899-cfdb5141-fb16-40c4-bd18-40236fa3968a.png)

Seems fixed now (2022.3.28 development release).
