### ISSUE TITLE
[BUG] Xwayland not accessible from inside the sandbox

### ISSUE THREAD

**Issue by joserebelo** [bottlesdevs/Bottles#884]
**Describe the bug**
Bottles fails to get the Xwayland display. It looks like XAUTHORITY is not being correctly propagated to inside the flatpak sandbox, see below.

~Potentially related: #623 and #794~ Actually no, had thought this before discovering the XAUTHORITY issue.

**Installation**
 - Method: Flatpak
 - Version: 2021.12.28-treviso

**To Reproduce**
1. Be on Wayland
2. Create a bottle
3. Attempt to open anything (winecfg, command line, ...)

**Expected behavior**
- XAUTHORITY should be available inside the sandbox
- A window should open
- On error, it would be nice to have a popup

**Desktop:**
 - OS: Arch Linux
 - Display server: Wayland, Plasma 5.23.4

**Additional context**

Logs from the error:

```
(11:06:08) INFO Setting Key: [sync] to [esync] for bottle: [MyBottle]… 
(11:06:08) INFO Setting Key: [discrete_gpu] to [True] for bottle: [MyBottle]… 
(11:06:08) INFO Setting Key: [pulseaudio_latency] to [True] for bottle: [MyBottle]… 
(11:06:08) ERROR Cannot find states.yml file for bottle: [MyBottle] 

(bottles:2): Handy-CRITICAL **: 11:06:08.812: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
(11:06:09) INFO Running winecfg on the wineprefix… 
(11:06:09) INFO Using Xwayland.. 
(11:06:09) ERROR Failed to get Xwayland display 
```

Running some checks inside the flatpak sandbox:

```bash
flatpak run --command=sh --devel com.usebottles.bottles
%1~$ echo $DISPLAY

%1~$ xdpyinfo -display :0
Authorization required, but no authorization protocol specified
xdpyinfo:  unable to open display ":0".
%1~$ xdpyinfo -display :1
xdpyinfo:  unable to open display ":1".
%1~$ 
```

This fixes the problem:

```bash
$ echo "$XAUTHORITY"
/run/user/1900/xauth_bruVGd
$ cp "$XAUTHORITY" ~/.var/app/com.usebottles.bottles/data/xauth
$ XAUTHORITY=~/.var/app/com.usebottles.bottles/data/xauth flatpak run com.usebottles.bottles 
```

I don't have enough context on flatpak to understand who should be responsible for making XAUTHORITY correctly available inside the sandbox.

**Comment by mirkobrombin** [comment]
Thanks for your debug, I thing this should be handled by Flatpak itself. Maybe I can force that env in the flatpak but also idk if this will break other things

**Comment by joserebelo** [comment]
@mirkobrombin looking at https://github.com/flatpak/flatpak/blob/973a909c8448ca8f36f75ec7d792c60ef511cb6f/common/flatpak-run.c, I believe that you are right. Flatpak seems to have some logic in place to propagate the xauth, but it doesn't seem to be working. I'll try and check this out and open a bug upstream.

**Comment by mirkobrombin** [comment]
> @mirkobrombin looking at https://github.com/flatpak/flatpak/blob/973a909c8448ca8f36f75ec7d792c60ef511cb6f/common/flatpak-run.c, I believe that you are right. Flatpak seems to have some logic in place to propagate the xauth, but it doesn't seem to be working. I'll try and check this out and open a bug upstream.
> 
> EDIT: This actually seems to work in other apps (eg. Spotify), so there may be something wrong with Bottles.

Spotify seems to be using xwayland by default for the whole app https://github.com/flathub/com.spotify.Client/blob/1bd91412e202cb240cf09433c7f1a63a30389674/com.spotify.Client.json#L13

Bottles use wayland for the app and xwayland for WINE as this doesn't support wayland

**Comment by joserebelo** [comment]
Yup, looks like `flatpak run --nosocket=fallback-x11 --socket=x11 com.usebottles.bottles` also does the trick.

From the [flatpak docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html), with `fallback-x11` it will `show windows using X11, if Wayland is not available, overrides x11 socket permission`. Do you see any drawbacks of changing `fallback-x11` to `x11`, given that we do expect Xwayland to be available for wine regardless?

**Comment by mirkobrombin** [comment]
We used to force x11 avoiding the fallback but some users ask for Wayland explicitly :D

**Comment by mirkobrombin** [comment]
I don't want to force x11 on wayland, I want to go more deeply on this. The current release test a bunch of ports to find the display server (as the flatpak do not reach the DISPLAY env var), so it should just works (and it works in mine). I need to set a VM and test this on other distro.

**Comment by ThomChroma** [comment]
Still the same for me unfortunately, with `2022.1.14-trento` on openSUSE Tumbleweed and Sway.

**Comment by joserebelo** [comment]
@mirkobrombin it's not a missing DISPLAY server, the problem really is the missing XAUTHORITY.

> and it works in mine

What desktop environment / display manager are you running?

**Comment by joserebelo** [comment]
@mirkobrombin according to https://github.com/flatpak/flatpak/issues/3396#issuecomment-580574659, xwayland access does need `socket=x11`, so I'm really wondering how this is working for anyone at all :thinking:

**Comment by mirkobrombin** [comment]
> @mirkobrombin according to [flatpak/flatpak#3396 (comment)](https://github.com/flatpak/flatpak/issues/3396#issuecomment-580574659), xwayland access does need `socket=x11`, so I'm really wondering how this is working for anyone at all, given that wine requires x11/xwayland thinking

![image](https://user-images.githubusercontent.com/9479903/149613396-c891e1ad-c13b-470a-ba4f-3b1ac73dcb3a.png)

From the official [documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions):
```
--socket=fallback-x11 - show windows using X11, if Wayland is not available, overrides x11 socket permission. Note that you must still use --socket=wayland for wayland permission
```

So if the system is running Wayland, Bottles will run under Wayland but as WINE does not works on Wayland (right now), we are using XWayland for all WINE processes: 
https://github.com/bottlesdevs/Bottles/blob/8f7dd6e05a7f960f5e9446fc73318ebd93e9d153/src/backend/runner.py#L477

FWIK (and based on my tests) `fallback-x11` does not need `x11` at all

**Comment by mirkobrombin** [comment]
> @mirkobrombin according to [flatpak/flatpak#3396 (comment)](https://github.com/flatpak/flatpak/issues/3396#issuecomment-580574659), xwayland access does need `socket=x11`, so I'm really wondering how this is working for anyone at all, given that wine requires x11/xwayland thinking


I had a discussion on Flatpak matrix channel and seems like the right way to proper use it, is to set the `x11` permission instead of the `fallback-x11`. It was working due to my trick but not for all and it is not the right way.
