### ISSUE TITLE
[BUG] Can't install .deb on Ubuntu 20.04 due to missing libhandy-1-0

### ISSUE THREAD

**Issue by JoeJoeTV** [bottlesdevs/Bottles#885]
**Describe the bug**
I can't install the latest .deb package of Bottles on Ubuntu 20.04/Mint 20.2(based on Ubuntu 20.04 LTS) due to missing `libhandy-1-0` dependency. I have not found any placa that says, that Focal Fossa is not supported, so I assumed the latest LTS release would be.

**Installation**
 - Method: DEB
 - Version 2021.12.28-treviso

**To Reproduce**
1. Go to [the Releases Page](https://github.com/bottlesdevs/Bottles/releases/tag/2021.12.28-treviso)
2. Download .deb file
3. Try to install the package, which will fail because of missing `libhandy-1-0`

**Expected behavior**
The package should install.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon x64 (based on Ubuntu 20.04 LTS)
 - Version 20.2 (20.04)
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Seems like that Ubuntu starts providing it with Ubuntu 21.04 https://packages.ubuntu.com/search?keywords=libhandy&searchon=names&suite=hirsute&section=all

Sorry but we need it, you should try the Flatpak or the AppImage 😅

**Comment by JoeJoeTV** [comment]
Ok, thanks. Can you maybe put a Notice in the Readme that the .deb only supports 21.04 and up?

**Comment by mirkobrombin** [comment]
> Ok, thanks. Can you maybe put a Notice in the Readme that the .deb only supports 21.04 and up?

Yup
