### ISSUE TITLE
[Request] Investigate if it's possible to hide the "Compiling shaders..." message.

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#889]
Flatpak 2021.12.28-treviso

Please investigate if it's possible to hide the "Compiling shaders..." message in the bottom left of the screen when playing games. I would expect it to only show up if you have the "DXVK HUD" Preferences set to on, but it shows up all the time. In MMO games with a huge amount of areas, this message displays pretty much all the time. It would be nice if we could not have it shown unless we explicitly want it shown with the DXVK HUD preference.

**Comment by braiam** [comment]
AFAIK, if in this line if the dxvk hud isn't enabled, just leave unset the environment variable instead of setting it to compiler

https://github.com/bottlesdevs/Bottles/blob/0f1be01435ddd543931ad2a19cbcd1003bd918d9/src/backend/runner.py#L456

**Comment by mirkobrombin** [comment]
> AFAIK, if in this line if the dxvk hud isn't enabled, just leave unset the environment variable instead of setting it to compiler
> 
> https://github.com/bottlesdevs/Bottles/blob/0f1be01435ddd543931ad2a19cbcd1003bd918d9/src/backend/runner.py#L456

You're right, I think it's still there due to some old tests
