### ISSUE TITLE
[BUG] AppImage doesn't start on Xubuntu 20.04

### ISSUE THREAD

**Issue by HugLifeTiZ** [bottlesdevs/Bottles#89]
**Describe the bug**
The AppImage version of Bottles fails to start, dropping a stack trace on start.

**Installation**
 - Method: AppImage
 - Version: devel, I guess?

**To Reproduce**
1. Download AppImage
2. Make it executable
3. Put it somewhere in your PATH, optionally
4. Run it, get stack trace.

**Expected behavior**
I expect the program to start and show its main window.

**Screenshots**
Got a console log:
```
Aura ~ $ bottles
Traceback (most recent call last):
  File "/tmp/.mount_bottle9BP8D9//usr/local/share/bottles/bottles/main.py", line 76, in do_activate
    win = BottlesWindow(application=self,
  File "/tmp/.mount_bottle9BP8D9//usr/local/share/bottles/bottles/window.py", line 91, in __init__
    self.init_template()
TypeError: <lambda>() missing 1 required positional argument: 's'
```

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version: 20.04

**Additional context**
The Flatpak version starts, but it has other problems. I'll file issue reports for those too.

**Comment by mirkobrombin** [comment]
Please provide the version from the about dialog.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/104085743-0e8f4b80-5252-11eb-919c-96a64b208aa1.png)

I think it's more of a distribution specific problem. Please give me the output for `python3 -V` or `python -V`

**Comment by HugLifeTiZ** [comment]
I can't provide the version in the about dialog if I can't get the app to start at all. Here's the output you've requested:

```
Aura ~ $ python3 -V
Python 3.8.5
Aura ~ $ python -V

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

```

**Comment by mirkobrombin** [comment]
> I can't provide the version in the about dialog if I can't get the app to start at all. Here's the output you've requested:
> 
> ```
> Aura ~ $ python3 -V
> Python 3.8.5
> Aura ~ $ python -V
> 
> Command 'python' not found, did you mean:
> 
>   command 'python3' from deb python3
>   command 'python' from deb python-is-python3
> ```

I think it's some outdated dependency, like python-gi for example because it works from 20.10. You could try building from meson to be 100% sure.

**Comment by HugLifeTiZ** [comment]
Are you building the AppImage on 20.10 or a newer distro? You lose a lot of the benefit of AppImages if you do that. You don't have to go flibit-mode and use CentOS 7, but Ubuntu 18.04 might be reasonably far enough back.

**Comment by mirkobrombin** [comment]
> Are you building the AppImage on 20.10 or a newer distro? You lose a lot of the benefit of AppImages if you do that. You don't have to go flibit-mode and use CentOS 7, but Ubuntu 18.04 might be reasonably far enough back.

I think the problem is that we don't include all the necessary dependencies in the AppImage assuming that the system ones are fine.

**Comment by francescomasala** [comment]
We are using Ubuntu 18.04 "Bionic Beaver" for building the appimage

**Comment by suoko** [comment]
same on Debian 10
./Bottles-devel-x86_64.AppImage 
/usr/lib/python3/dist-packages/gi/overrides/Gdk.py:461: Warning: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
  initialized, argv = Gdk.init_check(sys.argv)

(bottles:8848): Gtk-WARNING **: 17:15:12.584: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
Traceback (most recent call last):
  File "/tmp/.mount_Bottle3C5YzW//usr/local/share/bottles/bottles/main.py", line 77, in do_activate
    arg_executable=self.arg_executable)
  File "/tmp/.mount_Bottle3C5YzW//usr/local/share/bottles/bottles/window.py", line 91, in __init__
    self.init_template()
TypeError: <lambda>() missing 1 required positional argument: 's'

**Comment by mirkobrombin** [comment]
What version of `python-gi` is installed?

**Comment by suoko** [comment]
python3-gi:amd64 3.30.4-1 uptodate

**Comment by mirkobrombin** [comment]
I'll find time to mount a vm and investigate.

**Comment by mirkobrombin** [comment]
Latest release 2.1.0.3 fix this issue.
