### ISSUE TITLE
[Request] Allow configuration of where bottles are stored

### ISSUE THREAD

**Issue by IsaacClank** [bottlesdevs/Bottles#890]
**Is your feature request related to a problem? Please describe.**
To my knowledge, there isn't an option to configure where to store created bottles.

**Describe the solution you'd like**
I would like to be able to configure where my bottles are stored.

**Describe alternatives you've considered**
If this isn't possible, being able to import existing wineprefix would satisfy my request, but I don't think that's the easier implementation.

**Additional context**
...

**Comment by mirkobrombin** [comment]
Duplicate of https://github.com/bottlesdevs/Bottles/issues/578
