### ISSUE TITLE
[BUG] .NET 48 is not installed while creating a Bottle.

### ISSUE THREAD

**Issue by italoghost** [bottlesdevs/Bottles#891]
**Describe the bug**
.NET 48 is not installed while creating a Bottle.

**Installation**
 - Method: Flatpak
 - Version 2021.12.28-treviso

**To Reproduce**
1. Go to the initial page.
2. Click on 'Create a new bottle'.
3. Wait until the .NET 48 installation starts.

**Expected behavior**
.NET 48 should be installed.

**Screenshots**
![bottles_error](https://user-images.githubusercontent.com/48540550/147928971-0395055d-bf8d-4ccf-a150-bbb34dc0dbe3.png)

It is in Portuguese. Translating, it would be something like "The .NET 48 Framework or a further update has already been installed on this computer"

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version 21.10
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by 413Michele** [comment]
It happens to me too, I'll add that executing an MSI installer which requires Microsoft .NET Framework (4.6.2 and higher) fails saying that it's missing

**Comment by mirkobrombin** [comment]
Fix will be distributed with next release. It is also possible to workaround the problem: from Dependencies section install `dotnet40` then install `dotnet48`. These will be installed silently so no popup, look for the Operations menu in the headerbar.

**Comment by italoghost** [comment]
@mirkobrombin I tried this workaround when I was debugging but it didn't work either. After successfully installing .NET 40, the same error appeared after trying to install .NET 48 or even the previous versions.

**Comment by mirkobrombin** [comment]
I've updated dependencies manifests, can you try now? It should fails checking hashes, so try again to make a new download. This works on my but if still fails I'll deeply investigate the problem, let me know

**Comment by 413Michele** [comment]
> @mirkobrombin I tried this workaround when I was debugging but it didn't work either. After successfully installing .NET 40, the same error appeared after trying to install .NET 48 or even the previous versions.

It was like this for me too, but after your last message the workaround works



> It happens to me too, I'll add that executing an MSI installer which requires Microsoft .NET Framework (4.6.2 and higher) fails saying that it's missing

The program still doesn't recognize that .NET is installed though, should I open a new issue?

**Comment by mirkobrombin** [comment]
Yea please

**Comment by italoghost** [comment]
I had the same error as @413Michele. The program did not recognize that .NET was installed.
