### ISSUE TITLE
[Crash report]  list index out of range  

### ISSUE THREAD

**Issue by liulei9385** [bottlesdevs/Bottles#893]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.12.28-treviso

**Log**
```python3
list index out of range  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 968, in create_bottle
    runner = self.runners_available[0]

```

**Comment by mirkobrombin** [comment]
Seems like Bottles was not able to install a runner. Do you see any in preferences?

**Comment by liulei9385** [comment]
I use flatpak with proxy ,but Installing component: [dxvk-1.9.2] too slow.

**Comment by mirkobrombin** [comment]
It depend on your connection, the resources are on GitHub

**Comment by liulei9385** [comment]
with curl set proxy download fast,but use bottles download slow.
