### ISSUE TITLE
[BUG] Bottles does not remember Bottles application size

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#895]
Flatpak 2021.12.28-treviso

When a user resizes the Bottles application itself (not a WINE application) and then closes Bottles it resets to a default size. Bottles should remember/respect the size of the application that the user wants.

For example, if I make Bottles the entire screen and close Bottles, when I open it again it will be the same size even though I made it full screen when I closed it.

**Comment by mirkobrombin** [comment]
I've faced huge problems trying to implement this. Also I don't want to push the GUI as we are planning to upgrade to GTK4+libadwaita, so we will return on this after this.
