### ISSUE TITLE
[BUG] .msi installer can't find .NET Framework even though the dependencies are installed

### ISSUE THREAD

**Issue by 413Michele** [bottlesdevs/Bottles#899]
Coming from #891

**Description**
An MSI installer that requires Microsoft .NET Framework fails to even start the installation because it can't find it. However, the dependency is met in Bottles. The installer can be downloaded [here](https://safeincloud.ladesk.com/178979-Download), or from the [direct link](https://www.safe-in-cloud.com/download/SafeInCloud_Setup.msi)

**Installation**
 - Method: Flatpak
 - Version 2021.12.28-treviso

**To Reproduce**
1. Create a Bottle using Caffe as runner (Vaniglia can't open the .msi)
2. Install dotnet40 and dotnet48 in the dependencies
3. Run the installer
4. The installer fails and prompts the user to install .NET Framework 4.6.2 or higher

**Expected behavior**
The installer finds dotnet and installs the application

**Screenshots**
![Schermata del 2022-01-05 16 29 16](https://user-images.githubusercontent.com/29912185/148244187-7db400a0-b71b-4377-98d4-b2b1a6487f46.png)

**Desktop (please complete the following information):**
 - OS: elementaryOS 64bit
 - Version 6.1
 - Display server: Xorg

**Additional context**
A [portable version](https://www.safe-in-cloud.com/download/SafeInCloud_Portable.zip) of the program completely fails to open, with this terminal output:

![image](https://user-images.githubusercontent.com/29912185/148245332-05e763af-320d-4764-8b2b-e56b1ed53ba0.png)

I understand that this might be a Wine problem, if that is the case I'll report it on its bug tracker

**Comment by mirkobrombin** [comment]
I need to try with other software that requires dotnet to figure out if it's a general breakup. I think there are tools to check this

**Comment by gbtb** [comment]
I've also faced this problem when tried to install https://git-fork.com/ . But, few months ago I was able to install in and run with default wine + winetricks combo on my NixOS. Looking into this prefix now, I see that it works with wine-wow-7.0-rc2-staging/bin and following lines are in winetricks.log:
```
w_workaround_wine_bug-34803
remove_mono
remove_mono
winxp
dotnet40
dotnet48
d3dcompiler_47
```
What seems interesting, is than I've specified only dotnet48 and d3dcompiler_47 to winetricks. Which means that other "tricks" were added automatically

**Comment by mirkobrombin** [comment]
Also our dotnet48 package depend by dotnet40 but Bottles will supports dependencies chained only from 2022.1.14

**Comment by 413Michele** [comment]
I'm answering now with the new release out and because I have new info. The installation works now, but only after I installed mono as a dependency and not before that, so that might have been the problem.

Additionally, to let the installer work I need to add this argument:

`WIXUI_DONTVALIDATEPATH="1"`

otherwise the installer fails because "installation directory must be in a local hard drive". It might be useful to add it as a standard argument when dealing with .MSI installers

As far as executing the installed program, it doesn't work, either with dotnet48 or not. When trying to start it it gives this (new) error:

wineserver: using server-side synchronization.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
007c:err:module:open_builtin_so_file failed to load .so lib "/home/michele/.var/app/com.usebottles.bottles/data/bottles/runners/caffe-6.23/lib/wine/x86_64-unix/wineusb.sys.so"
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Non è stato possibile eseguire l'applicazione, o nessuna applicazione è associata con il file specificato.
ShellExecuteEx fallito: Percorso non trovato.

**Comment by mirkobrombin** [comment]
> I'm answering now with the new release out and because I have new info. The installation works now, but only after I installed **mono** as a dependency and not before that, so that might have been the problem.
> 
> Additionally, to let the installer work I need to add this argument:
> 
> `WIXUI_DONTVALIDATEPATH="1"`
> 
> otherwise the installer fails because "installation directory must be in a local hard drive". It might be useful to add it as a standard argument when dealing with .MSI installers
> 
> As far as executing the installed program, it doesn't work, either with dotnet48 or not. When trying to start it it gives this (new) error:
> 
> wineserver: using server-side synchronization. 002c:err:wineboot:process_run_key Error running cmd L"C:\windows\system32\winemenubuilder.exe -r" (2). 007c:err:module:open_builtin_so_file failed to load .so lib "/home/michele/.var/app/com.usebottles.bottles/data/bottles/runners/caffe-6.23/lib/wine/x86_64-unix/wineusb.sys.so" 007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\Registry\Machine\System\CurrentControlSet\Services\wineusb": c0000142 MESA-INTEL: warning: Haswell Vulkan support is incomplete Non è stato possibile eseguire l'applicazione, o nessuna applicazione è associata con il file specificato. ShellExecuteEx fallito: Percorso non trovato.

Mono is needed if net is not provided. Are we sure such flag does not break other installers?

**Comment by 413Michele** [comment]
> Mono is needed if net is not provided. Are we sure such flag does not break other installers?

 The thing is, having dotnet40 and dotnet48 isn't enough, the installer only works if mono is installed. Regarding the flag, I don't know honestly. It seems innocuous enough, but I'm not a programmer so I can't really give an opinion

**Comment by gbtb** [comment]
@413Michele You were probably affected by this issue the same as I - https://github.com/bottlesdevs/Bottles/issues/949
It prevented installation of dotnet48, without any warnings because of quiet flag, passed to dotnet48 installer.
Now it is fixed in a master branch and will be shipped in a next release :)
