### ISSUE TITLE
[BUG] /lib/ld-linux.so.2 not found

### ISSUE THREAD

**Issue by HugLifeTiZ** [bottlesdevs/Bottles#90]
**Describe the bug**
There is no graphical indication of this, but stderr in a terminal shows that for some reason, setup_dxvk.sh can't run the wine binary from the installed runner.

**Installation**
 - Method: Flatpak
 - Version: 2.0.9

**To Reproduce**
1. Run bottles in a terminal: `flatpak run com.usebottles.bottles`
2. Create a new bottle
3. Select gaming type
4. Set a name, don't customize the path
5. Watch terminal as it installs, notice error message about trying to run wine

**Expected behavior**
The setup_dxvk.sh script should not give the output it does.

**Screenshots**
Got my terminal log:
```
2021-01-08 23:01:50 INFO: Runners found: [lutris-6.0-rc1-x86_64]
2021-01-08 23:01:50 INFO: Dxvk found: [dxvk-1.7.3]
2021-01-08 23:01:50 INFO: Connection status: online …
2021-01-08 23:01:51 INFO: Selected env is: [Software]
2021-01-08 23:01:51 INFO: Bottles Started!
2021-01-08 23:01:57 INFO: Selected env is: [Gaming]
2021-01-08 23:02:03 INFO: Creating the wineprefix …
wine: created the configuration directory '/home/tiz/.local/share/bottles/bottles/Gaming'
wineserver: using server-side synchronization.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Could not find Wine Gecko. HTML rendering will be disabled.
/lib/ld-linux.so.2: could not open
wine: configuration in L"/home/tiz/.local/share/bottles/bottles/Gaming" has been updated.
2021-01-08 23:02:15 INFO: Generating Bottle configuration file …
2021-01-08 23:02:15 INFO: Applying environment: [Gaming] …
2021-01-08 23:02:21 INFO: Installing dxvk …
2021-01-08 23:02:21 INFO: Installing dxvk for bottle: [Gaming].
/home/tiz/.local/share/bottles/dxvk/dxvk-1.7.3/setup_dxvk.sh: line 72: /home/tiz/.local/share/bottles/runners/lutris-6.0-rc1-x86_64/bin/wine: No such file or directory
wine: Not a wine executable. Check your $wine.
2021-01-08 23:02:22 INFO: Bottle: [Gaming] successfully created!
2021-01-08 23:02:22 INFO: Bottles found: Gaming
```

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version: 20.04

**Additional context**
This could be symptomatic of a bigger problem. Notice the line: `/lib/ld-linux.so.2: could not open`
I tried to install some games into a bottle, and any executable I tried to run inside the bottle just resulted in that line appearing and nothing happening. I was going to file that as a separate issue.

**Comment by mirkobrombin** [comment]
This is a problem that was also reported to me yesterday. At the moment I'm investigating, I keep the issue open for updates.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/104085505-4eedca00-5250-11eb-859c-0236f44014f0.png)
I'm rolling out an update that seems works (to me).

**Comment by francescomasala** [comment]
![Screenshot from 2021-01-09 09-49-13](https://user-images.githubusercontent.com/25754886/104088888-d7c13180-5261-11eb-8f15-e633deba13f6.png)
It works on my machine

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/104091674-08fc2a80-527f-11eb-8e42-e47f16a3b037.png)
Working on Flatpak 2.0.9.8 from Flathub.

**Comment by HugLifeTiZ** [comment]
It's still not working for me, but I'm noticing in your screenshots that you're using Wine-tkg 5.21. The application does not offer me the ability to install that runner, only the latest Lutris RC. But it looks like the runners have the same layout as the builds from https://github.com/Kron4ek/Wine-Builds, so I copied 5.21-tkg into the runners directory and remade the bottle with it.

But still no difference.

```
2021-01-09 13:21:06 INFO: Runners found: [5.21-tkg]
2021-01-09 13:21:06 INFO: Dxvk found: [dxvk-1.7.3]
2021-01-09 13:21:06 INFO: Connection status: online …
2021-01-09 13:21:06 INFO: Bottles found: Gaming
2021-01-09 13:21:06 INFO: Selected env is: [Software]
2021-01-09 13:21:06 INFO: Bottles Started!
2021-01-09 13:21:09 INFO: Deleting a bottle …
2021-01-09 13:21:09 INFO: Successfully deleted bottle in path: [/home/tiz/.local/share/bottles/bottles/Gaming]
2021-01-09 13:21:12 INFO: Selected env is: [Gaming]
2021-01-09 13:21:16 INFO: Creating the wineprefix …
wine: created the configuration directory '/home/tiz/.local/share/bottles/bottles/Gaming'
wineserver: using server-side synchronization.
/lib/ld-linux.so.2: could not open
/lib/ld-linux.so.2: could not open
wine: configuration in L"/home/tiz/.local/share/bottles/bottles/Gaming" has been updated.
2021-01-09 13:21:26 INFO: Generating Bottle configuration file …
2021-01-09 13:21:26 INFO: Applying environment: [Gaming] …
2021-01-09 13:21:32 INFO: Installing dxvk …
2021-01-09 13:21:32 INFO: Installing dxvk for bottle: [Gaming].
/home/tiz/.local/share/bottles/dxvk/dxvk-1.7.3/setup_dxvk.sh: line 72: /home/tiz/.local/share/bottles/runners/5.21-tkg/bin/wine: No such file or directory
wine: Not a wine executable. Check your $wine.
2021-01-09 13:21:33 INFO: Bottle: [Gaming] successfully created!
2021-01-09 13:21:33 INFO: Bottles found: Gaming
```

**Comment by HugLifeTiZ** [comment]
It kind of seems like the problem is that it can't run 32-bit binaries for some reason. Maybe there's a missing dependency? I do have org.gnome.Platform.Compat.i386 installed, but maybe something else is necessary.

```
Aura ~ $ flatpak run --command=bash com.usebottles.bottles
[📦 com.usebottles.bottles ~]$ cd xdg/share/bottles/runners/5.21-tkg/
[📦 com.usebottles.bottles 5.21-tkg]$ bin/wine64 --version
wine-5.21 (Staging)
[📦 com.usebottles.bottles 5.21-tkg]$ bin/wine --version
bash: bin/wine: No such file or directory
```

**Comment by mirkobrombin** [comment]
> It's still not working for me, but I'm noticing in your screenshots that you're using Wine-tkg 5.21. The application does not offer me the ability to install that runner, only the latest Lutris RC. But it looks like the runners have the same layout as the builds from https://github.com/Kron4ek/Wine-Builds, so I copied 5.21-tkg into the runners directory and remade the bottle with it.
> 
> But still no difference.
> 
> ```
> 2021-01-09 13:21:06 INFO: Runners found: [5.21-tkg]
> 2021-01-09 13:21:06 INFO: Dxvk found: [dxvk-1.7.3]
> 2021-01-09 13:21:06 INFO: Connection status: online …
> 2021-01-09 13:21:06 INFO: Bottles found: Gaming
> 2021-01-09 13:21:06 INFO: Selected env is: [Software]
> 2021-01-09 13:21:06 INFO: Bottles Started!
> 2021-01-09 13:21:09 INFO: Deleting a bottle …
> 2021-01-09 13:21:09 INFO: Successfully deleted bottle in path: [/home/tiz/.local/share/bottles/bottles/Gaming]
> 2021-01-09 13:21:12 INFO: Selected env is: [Gaming]
> 2021-01-09 13:21:16 INFO: Creating the wineprefix …
> wine: created the configuration directory '/home/tiz/.local/share/bottles/bottles/Gaming'
> wineserver: using server-side synchronization.
> /lib/ld-linux.so.2: could not open
> /lib/ld-linux.so.2: could not open
> wine: configuration in L"/home/tiz/.local/share/bottles/bottles/Gaming" has been updated.
> 2021-01-09 13:21:26 INFO: Generating Bottle configuration file …
> 2021-01-09 13:21:26 INFO: Applying environment: [Gaming] …
> 2021-01-09 13:21:32 INFO: Installing dxvk …
> 2021-01-09 13:21:32 INFO: Installing dxvk for bottle: [Gaming].
> /home/tiz/.local/share/bottles/dxvk/dxvk-1.7.3/setup_dxvk.sh: line 72: /home/tiz/.local/share/bottles/runners/5.21-tkg/bin/wine: No such file or directory
> wine: Not a wine executable. Check your $wine.
> 2021-01-09 13:21:33 INFO: Bottle: [Gaming] successfully created!
> 2021-01-09 13:21:33 INFO: Bottles found: Gaming
> ```

This is the lutris-5.21 runner.



> It kind of seems like the problem is that it can't run 32-bit binaries for some reason. Maybe there's a missing dependency? I do have org.gnome.Platform.Compat.i386 installed, but maybe something else is necessary.
> 
> ```
> Aura ~ $ flatpak run --command=bash com.usebottles.bottles
> [📦 com.usebottles.bottles ~]$ cd xdg/share/bottles/runners/5.21-tkg/
> [📦 com.usebottles.bottles 5.21-tkg]$ bin/wine64 --version
> wine-5.21 (Staging)
> [📦 com.usebottles.bottles 5.21-tkg]$ bin/wine --version
> bash: bin/wine: No such file or directory
> ```

Check if these are installed:
- org.gnome.Sdk.Compat.i386 `2.38`
- org.freedesktop.Sdk.Extension.toolchain-i386 `20`

**Comment by HugLifeTiZ** [comment]
I thought I had the first installed already, but what I had was `org.gnome.Platform.Compat.i386`. After installing both, I can run 32-bit executables! Thanks very kindly. :)

**Comment by mirkobrombin** [comment]
> I thought I had the first installed already, but what I had was `org.gnome.Platform.Compat.i386`. After installing both, I can run 32-bit executables! Thanks very kindly. :)

So we have to insert the addiction. Thanks a lot for reporting.

**Comment by bughunter2** [comment]
I tried all suggestions from this thread #90 and also #1405 and #1333.

However, ultimately, it seemed my Bottles installation (or home dir) was somehow misconfigured.
The following seems to have worked though:

Step 1:
$ sudo dnf install glibc.i686
Step 2:
$ flatpak remove com.usebottles.bottles
Step 3:
Clean up leftovers in your home directory, e.g.,: $HOME/.var/app/com.usebottles.bottles/
But be CAREFUL, you may still have things in there like files from your bottles, which may include your games, saved games, and so on.
Step 4:
$ flatpak install com.usebottles.bottles

If I only installed glibc.i686 without doing the other steps, then the 32-bit 'wine' binary from the soda runner would work OUTSIDE of bottles, but not while running INSIDE bottles (flatpak).

I'm not sure how this all came to be. I have a fresh Fedora 37 installation (Xfce spin) of just a few days old. I fully updated it before installing flathub and bottles.

I noticed something curious:
$ flatpak run --command=bash com.usebottles.bottles
Then, when looking in /lib/i386-linux-gnu , that directory was almost empty, instead of being populated with lots of 32-bit libs.

After running the above steps, the directory is nicely populated with those libraries.
