### ISSUE TITLE
[Request] - Support for LatencyFlex

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#900]
Is it possible to have an option for [LatencyFleX](https://github.com/ishitatsuyuki/LatencyFleX) in Bottles?

**Comment by mirkobrombin** [comment]
It seems to work via proton nvapi, I think it's possible but I have to investigate. Thanks for reporting

**Comment by VarLad** [comment]
@mirkobrombin Any update on this? 

Also, if I may ask, Gamescope doesn't work with Flatpak on GNOME, saying that the device is not supported. Is that intentional or a bug?

**Comment by Githob2021** [comment]
> @mirkobrombin Any update on this?
> 
> Also, if I may ask, Gamescope doesn't work with Flatpak on GNOME, saying that the device is not supported. Is that intentional or a bug?

Do you have an AMD graphics card?

**Comment by VarLad** [comment]
AMD iGPU + NVIDIA GPU

**Comment by mirkobrombin** [comment]
> @mirkobrombin Any update on this?
> 
> Also, if I may ask, Gamescope doesn't work with Flatpak on GNOME, saying that the device is not supported. Is that intentional or a bug?

That’s weird 🤔

**Comment by VarLad** [comment]
@mirkobrombin Are there any hardware requirements on when can I use Gamescope?

**Comment by mirkobrombin** [comment]
> @mirkobrombin Are there any hardware requirements on when can I use Gamescope?

I don't think. This is the project repo: https://github.com/Plagman/gamescope

**Comment by VarLad** [comment]
@mirkobrombin Any idea if ProtonGE's latest version will be provided in the future, by the installer? 
Also, sorry for using this thread for asking random questions :sweat_smile:

**Comment by VarLad** [comment]
As in, Bottles has the option to download and install different runners from Preferences. 
Any idea when would Proton-7.2-GE-2 would be added to that list?

**Comment by mirkobrombin** [comment]
> ~As in, Bottles has the option to download and install different runners from Preferences.~ ~Any idea when would Proton-7.2-GE-2 would be added to that list?~
> 
> Just checked right now and its there! smile Thanks! I guess thats a _really_ recent addition

Oh ok, It was published some hours ago :D

**Comment by VarLad** [comment]
@mirkobrombin Just to inform, the first release came out https://github.com/ishitatsuyuki/LatencyFleX/releases/tag/v0.1.0 :smiley: 
Its inspired by SteamDeck supporting ApexLegends I believe.

**Comment by mirkobrombin** [comment]
Nice

**Comment by VarLad** [comment]
@mirkobrombin By the way, can I ask the version of Gamescope in Bottles?
I've an AMD iGPU + NVIDIA setup, and Gamescope appears to be disabled (even if I disable "Discrete GPU" since Gamescope doesn't support NVIDIA)

**Comment by mirkobrombin** [comment]
Make sure it is installed, if you use flatpak you need to install gamescope via flatpak too

**Comment by VarLad** [comment]
Installing via flathub did the trick. 
Now I get the error when I launch with the terminal `
```
/app/utils/bin/gamescope invalid option -- 'd'
See --help for a list of options
```
This is my gamescope config

![image](https://user-images.githubusercontent.com/51269425/158011250-e9046ff5-fad0-4b09-bffc-d203f5ae84f8.png)

**Comment by mirkobrombin** [comment]
Maybe they changed some flags, can you open a new issue?
