### ISSUE TITLE
[BUG] dotnet35 fails to install 

### ISSUE THREAD

**Issue by Diridibindy** [bottlesdevs/Bottles#901]
Dotnet 3.5 refuses to install. 

**Installation**
 - Method: AUR
 - Version 2021.12.28-treviso

**To Reproduce**
1. Create a bottle
2. Install dotnet 3.5 through the dependencies tab

**Expected behavior**
Dotnet 3.5 installation finishes without a hitch

**Screenshots**
![2022-01-06_00-40](https://user-images.githubusercontent.com/65438862/148293868-b86f4b76-2694-4fc9-afd7-ea8bdee83f43.png)
![2022-01-06_00-40_1](https://user-images.githubusercontent.com/65438862/148293873-a20dc5b6-cbcb-4353-aad8-02941bcdafe7.png)
![2022-01-06_00-40_2](https://user-images.githubusercontent.com/65438862/148293874-d08fd15b-e547-4b76-8e39-19b272aaeb9d.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
We set winxp here https://github.com/bottlesdevs/dependencies/blob/02b77b0dd00918e1539c3298a6840d25ac330e97/Essentials/dotnet35.yml#L11 and win10 after the installation process

**Comment by Diridibindy** [comment]
Yeah, that was my bad. Misread the manifest. Edited the bug report

**Comment by mirkobrombin** [comment]
What runner are you using?

**Comment by Diridibindy** [comment]
caffe-6.23

**Comment by mirkobrombin** [comment]
That’s weird, it was working 😅 I’ll test again tomorrow and make a fix if needed, thanks for reporting

**Comment by Diridibindy** [comment]
No problem, I'll test with a few different runners in the meantime

**Comment by mirkobrombin** [comment]
As a workaround you can set winxp and then start the dependency installation again, should do the trick

**Comment by Diridibindy** [comment]
Will try, but iirc I have already tried to do that and it failed.

**Comment by mirkobrombin** [comment]
Oh wait I’ve already fixed this, the problem was caused by wrong keys on register when changing windows version. The fix will be distributed with 2022.1.14, in the meantime you can just do the workaround using winecfg, should works.

**Comment by Diridibindy** [comment]
Oh, so just changing the wine version with winecfg should do the trick?

**Comment by mirkobrombin** [comment]
I hope. If not you should set it in winecfg and run the installer manually, so not from dependencies view. This until I distribute the new release.

**Comment by Diridibindy** [comment]
Is the fix already in the tree?

**Comment by Diridibindy** [comment]
Changing win version to winxp using winecfg worked

**Comment by mirkobrombin** [comment]
> Is the fix already in the tree?

Yup but there are also a lot of untested changes

**Comment by Diridibindy** [comment]
Okay, thanks for helping!

**Comment by mirkobrombin** [comment]
I’ll close as a fix is already done, feel free to add more comments

**Comment by imperfectlink** [comment]
This is still broken as of 2022.7.14

**Comment by JamesTDG** [comment]
Experiencing the same exact issue with .NET 3.5 here. Running Bazzite with NVidia graphics card, and the .NET issues make it so I can't install some old Windows games...
