### ISSUE TITLE
[Question] does Wine need to be installed serperately? 

### ISSUE THREAD

**Issue by xioren** [bottlesdevs/Bottles#903]
Sorry for the dumb question but after having issues getting something to work with Wine I just found out about Bottles. Is Bottles like proton in the sense that it is all self contained? I already have Wine + Winetricks installed and I just installed the Bottles .deb. Can I uninstall Wine and/or Winetricks?

**Comment by mirkobrombin** [comment]
No, despite bottles does not need wine, it require some other dependencies that came with it. You can install the flatpak that does not need it at all. Let me know if you need other info.
