### ISSUE TITLE
[Request] Please add a select option in dependencies.

### ISSUE THREAD

**Issue by Zenklops** [bottlesdevs/Bottles#906]
Issue:

Whenever I'm trying to install the several vcredists versions for a bottle or other dependencies, I'm always turned off by the painstaking one by one approach to download and install them.

Solution:

I'd like an option which lets you select all the components you want to download and install and then they'd do it automatically for you.

https://i.imgur.com/X0lRxsW.png

**Comment by mirkobrombin** [comment]
This was already discussed here: https://github.com/bottlesdevs/Bottles/issues/595

But I would like to reconsider the implementation of this feature and will keep it monitored in this new one.
