### ISSUE TITLE
[BUG] Latest version of gir1.2-handy available for Ubuntu 21.10 below Bottles' requirement

### ISSUE THREAD

**Issue by Rick1029** [bottlesdevs/Bottles#908]
**Describe the bug**
Bottles requires gir1.2-handy of version 1.5 or greater, but only 1.2.3-1 is available in [Ubuntu Impish](https://packages.ubuntu.com/en/impish/gir1.2-handy-1)

**Installation**
Deb Package install fails with missing dependency.

**Expected behavior**
Way to install deb without using Debian unstable repos

**Desktop (please complete the following information):**
 Pop OS 21.10

**Comment by mirkobrombin** [comment]
Bottles is also on Flathub and pop os has Flatpak support by default. Do you explicitly need the deb or just missed it?

Because we explicitly need such version.

**Comment by Rick1029** [comment]
I prefer debs over flatpaks because flatpaks don't tend to respect my system theme or they generally bug around with gnome (window renders where it isn't, cant full screen or change size, etc...)

There is a line under the releases that says >Deb packages work on Ubuntu 21.04+ only, but if Ubuntu lacks this dependency in their repos then it might be beneficial to state Debian repos are necessary for deb package installation.

I'll try the flatpak regardless - thank you.

**Comment by mirkobrombin** [comment]
I’ll test the release on Ubuntu using old libhandy. Btw pop os should automatically force/inject/set it’s own theme with Bottles (despite we do not support this) so give a try.

**Comment by MichelN86** [comment]
I have pop os 21.10 as well, i manually installed these 2 deb packages so i could install bottles

1. Download and update/install [libhandy-1-0_1.5.0-1](http://ftp.de.debian.org/debian/pool/main/libh/libhandy-1/libhandy-1-0_1.5.0-1_amd64.deb)

2. Download and update/install [gir1.2-handy-1_1.5.0-1](http://ftp.de.debian.org/debian/pool/main/libh/libhandy-1/gir1.2-handy-1_1.5.0-1_amd64.deb)

**Comment by mirkobrombin** [comment]
Good
