### ISSUE TITLE
[BUG] Fails to run executables inside the bottle

### ISSUE THREAD

**Issue by HugLifeTiZ** [bottlesdevs/Bottles#91]
**Describe the bug**
When you try to run an .exe file via the dashboard button, nothing happens.

**Installation**
 - Method: Flatpak
 - Version: 2.0.9

**To Reproduce**
1. Run bottles in a terminal: `flatpak run com.usebottles.bottles`
2. Create a bottle
3. Go to the bottle's dashboard
4. *Turn off esync.* Otherwise it will make A LOT OF NOISE in the console and you won't be able to discern anything useful.
5. Run an .exe file in the dashboard
6. Select any .exe file at all
7. Nothing happens, observe a particular error in the terminal

**Expected behavior**
The installer for my game or whatever it is I'm trying to set up starts.

**Screenshots**
Console log:
```
2021-01-08 23:13:42 INFO: Setting Key: [esync] to [False] for bottle: [Gaming] …
2021-01-08 23:13:48 INFO: Running an executable on the wineprefix …
wineserver: using server-side synchronization.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

/lib/ld-linux.so.2: could not open
```
This is all that appears whenever I attempt to run a program.

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version: 20.04

**Additional context**
Could be the actual problem behind #90.

It is worth noting that by default, the Flatpak version requests two filesystem permissions that I used Flatseal to deny: `~/Games` and `~/wineprefixes`. I have neither directory and I want neither directory. Don't make presumptions on which non-hidden directories are okay to create or access. In addition, it's likely a good idea to use `$XDG_DATA_HOME` instead of hardcoding `~/.local/share`.

**Comment by mirkobrombin** [comment]
It is actually the same problem as the other issue, I close to keep a single issue in which to monitor the case.
