### ISSUE TITLE
[Request] Optimize storage of bottle versions

### ISSUE THREAD

**Issue by gbtb** [bottlesdevs/Bottles#912]
**Is your feature request related to a problem? Please describe.**
Current implementation of versioning mechanism is sub-optimal in terms of storage space. Each version folder is basically a full copy of prefix drive_c folder at some point in time. 

**Describe the solution you'd like**
I'd like to discuss possible solutions we can implement.

**Describe alternatives you've considered**
1. Storing version folders inside an archive Pros: Simple to implement. Cons: not as effective for multiple versions, since files still have multiple compressed copies. 
1. Use [hard-links](https://en.wikipedia.org/wiki/Hard_link) for a files in new version, which has not changed since previous version. Pros: also seems simple. Cons: requires manual file operations and we will still have at least two copies of files - one in a version folder, and one in a bottle folder. So if you install a game with prefix size X and then make a version out of it, you will have 2X space taken, and only for subsequent versions hard links will get you profit.
1. Use an [OverlayFS](https://en.wikipedia.org/wiki/OverlayFS) under the hood. Tutorial in [Arch wiki](https://wiki.archlinux.org/title/Overlay_filesystem) is very simple - all you need is basically one mount command and it works. Pros: It is baked into Linux kernel, similar methods is used by Docker and it is proven to work well for Docker images, it will save the most space on disk. Cons: mount command requires sudo, it is more complex in terms implementation, and also it is also possibly will add a performance penalty to wine

**Additional context**

**Comment by mirkobrombin** [comment]
I considered using symlinks but this led me to create another feature (still under development), namely Layers, where each dependency and program is on its own layer and these are mounted on demand.

I am aware that versioning can be optimized, perhaps using something like OSTree or trivial symlinks but at the moment I can't get into this. I'd like some other developers to join this conversation.

**Comment by TiBeN** [comment]
Why not use git as a backend for this feature ?

**Comment by mirkobrombin** [comment]
closed by 5cfe7a81351559b0b257b39a3ff6812d7dd87210
