### ISSUE TITLE
[BUG] No module named 'gi'

### ISSUE THREAD

**Issue by Microwave-WYB** [bottlesdevs/Bottles#914]
**Describe the bug**
Got `No module named 'gi'` bug after installing from aur.  

**Installation**
 - Method: aur
 - Version: 2021.12.28

**To Reproduce**
1. Install from aur using `yay -S bottles`
2. run bottles in command line

**Expected behavior**
Expected bottles to run.

**Screenshots**
```
$ bottles
Traceback (most recent call last):
  File "/usr/bin/bottles", line 50, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Desktop (please complete the following information):**
 - OS: Manjaro Gnome
 - Display server: Wayland
**Additional context**
Installed `python-gobject` with `sudo pacman -S python-gobject `, couldn't solve the problem.
Tried flatpak, it worked, but I hate flatpak.

**Comment by francescomasala** [comment]
Hi!
Try to install [libhandy](https://archlinux.org/packages/extra/x86_64/libhandy/) in theory this should fix the problem

**Comment by mirkobrombin** [comment]
I think the right package should by names something like PyGObject, also libhandy should already be a dependency
