### ISSUE TITLE
[Crash report]  'NoneType' object has no att

### ISSUE THREAD

**Issue by CleoMenezes** [bottlesdevs/Bottles#917]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.12.28-treviso

**Log**
```python3
'NoneType' object has no attribute 'startswith'  File "/app/share/bottles/bottles/utils.py", line 339, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 1207, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])

  File "/app/share/bottles/bottles/backend/dependency.py", line 164, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/dependency.py", line 252, in __perform_steps
    if not self.__step_cab_extract(step=step):

  File "/app/share/bottles/bottles/backend/dependency.py", line 429, in __step_cab_extract
    if dest.startswith("temp/"):

```

**Comment by mirkobrombin** [comment]
This is not 2021.12.28 but 2022.1.14 (Beta is missing the version change, sending update now). 

That version has new dependencies manager that is not compatible with current repository. You need to force use the new one.

Clone this somewhere https://github.com/mirkobrombin/dependencies then give access permission to the flatpak, so start it with LOCAL_DEPENDENCIES=‘/path/to/repo’ env var.
