### ISSUE TITLE
[BUG] About Page "License" and "Close" Buttons do not Work

### ISSUE THREAD

**Issue by RippedCornet391** [bottlesdevs/Bottles#924]
**Describe the bug**

The "Close" and "License" buttons on the About page do not function properly. When clicked, nothing happens, and nothing is printed to the console.

**Installation**
 - Method: AUR
 - Version 2022.1.14-trento

**To Reproduce**

1. Open Bottles.
2. Open the About page.
3. Click the "Close" or "License" buttons.

**Expected behavior**

The "Close" button would close the About page. The "License" button would show something related to the program's license.

**Desktop (please complete the following information):**

 - OS: Manjaro Linux
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. After many days of investigation (we found this "bug" months ago) have concluded that it is the system or desktop environment's fault in some way. I am not able to solve the problem and it is definitely related to this one.
