### ISSUE TITLE
Extend/Improve Bottles' CLI

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#927]
Currently our CLI can only be used to start programs in already existing bottles. This should be extended with more features so users can interact with their bottles without using the GUI.

### Features
- [x] info
  - [x] bottles-path (return path of user bottles path according to the configuration)
  - [x] health-check
 
- [x] list
  -  [x] bottles
     - [x] `--filter environment:gaming|application|custom`
  -  [x] components
     - [x] `--filter category:dxvk|runner|vkd3d|nvapi|latencyflex`

-  [x] programs
   - [x] `--bottle:"Hello Bottles" [required]`

- [x] new
  -  [x] bottle
     - [x] `--name "Hello Bottles" [required]`
     - [x] `--environment gaming|software|custom`
     - [x] `--custom-environment /path/to/env.yml`

- [x] edit
  -  [x] bottle
     - [x] `--params dxvk:true,sync:futex2,..`
     - [x] `--add-env-var HELLO=world`
     - [x] `--add-dll-override d3dx9.dll:n,b`
     - [x] `--win win10`
     - [x] `--runner caffe-7.2`
     - [x] `--dxvk dxvk-1.9.4`
     - [x] `--nvapi dxvk-nvapi-v0.5.2`
     - [x] `--latencyflex latencyflex-v0.1.0`

- [x] reg
  -  [x] add|edit|del
     - [x] `--bottle "Hello Bottles" [required]`
     - [x] `--key "HKEY_LOCAL_MACHINE.." [required]`
     - [x] `--value "myAwesomeKey" [required]`
     - [x] `--data "myAwesomeValue" [required by add|edit]`
     - [x] `--key-type ('REG_DWORD', 'REG_SZ', 'REG_BINARY', 'REG_MULTI_SZ') [required by add|edit]`

- [x] run
  - [x] `--executable path/to/.exe|.msi|.bat`
  - [x] `--bottle "Hello Bottles" [required]`
  - [x] `--program "Notepad++.exe"`

- [x] tools
  -  [x] cmd
  -  [x] winecfg
  -  [x] uninst
  -  [x] regedit
  -  [x] taskmgr
  -  [x] control
  -  [x] explorer
   - [x] `--bottle "Hello Bottles" [required]`

and maybe others.

### Usage
```bash
 bottles-cli list bottles
```

#### Flatpak

```bash
 flatpak run --command="bottles-cli" com.usebottles.bottles list bottles
```

![image](https://user-images.githubusercontent.com/9479903/159807694-67161dd5-c00f-4946-8d18-0100ca105931.png)

**Comment by juligreen** [comment]
Especially executing installers would be nice.

**Comment by imLinguin** [comment]
Things that could be useful too:
- Launch winecfg/winetricks
- Execute command e.g `reg /?`, `echo %APPDATA%`

**Comment by mirkobrombin** [comment]
Bottles doesn't uses/provides winetricks. Is heroic "just" pops it up or actually uses it? Because we can just show Bottles up

**Comment by imLinguin** [comment]
Then we can skip winetricks step, we should avoid spawning a window especially for Steam Deck, gamescope can go crazy when there are multiple windows open.

**Comment by mirkobrombin** [comment]
Updated main comment with the features that will came with the next release
