### ISSUE TITLE
[Request] Running .bat files

### ISSUE THREAD

**Issue by tim77** [bottlesdevs/Bottles#93]
**Is your feature request related to a problem? Please describe.**
Currently Bottles can run `.exe` and `.msi` files. This is not enough. :) 

**Describe the solution you'd like**
I'd like to to run `.bat` files as well in Bottle.

**Describe alternatives you've considered**
Adding option into file chooser dialog to run `.bat` files or all supported types where `.bat` will be included.

**Comment by mirkobrombin** [comment]
As a non Windows user I have completely ignored this thing. Thanks for reporting.

**Comment by tim77** [comment]
Just for example and testing where could be useful this feature: https://benchmark.unigine.com/valley
It works out of box only if run .bat launcher.

**Comment by mirkobrombin** [comment]
> Just for example and testing where could be useful this feature: https://benchmark.unigine.com/valley
> It works out of box only if run .bat launcher.

Now the .bat files can be run. They run through wineconsole cmd.
