### ISSUE TITLE
[BUG] Bottles synchronously opens network connections right after launch

### ISSUE THREAD

**Issue by soystemd** [bottlesdevs/Bottles#932]
### Problem:

Network connections can be slow and unreliable, and trying to 
synchronously open connections to fetch components list, dependencies list, installers index etc. makes opening Bottles very slow, and in some cases outright impossible. IMO expecting the user's internet connection to be reliable is very bad practice and should NEVER be done anywhere.

### Solution:

Fetching components list, dependencies list, installers index etc. 
should either be done asynchronously after launch, or better yet, they should be fetched right when they're needed.

##### Info

Version:  2022.1.14-trento-1

**Comment by mirkobrombin** [comment]
This is something Bottles has been doing from older versions and I would actually like to improve.

**Comment by mirkobrombin** [comment]
I have to postpone this task because I am redesigning the manager using an internal cache and limiting requests only when they are strictly necessary (for example a cache update)
