### ISSUE TITLE
[BUG] Exe is launched every single time you go into a bottle, then it closes itself

### ISSUE THREAD

**Issue by Githob2021** [bottlesdevs/Bottles#933]
2022.1.14-trento flatpak
In the latest version everytime you go into a bottle, it will launch an .exe and close it right away. For some instances this is unjarring because it makes the screen black for a couple seconds before closing.

I think it is a bug in the new feature to "stop" an exe from the main screen because you can see the "Play" button change to "Stop" button for a second and back to "Play" again all without any interaction from the user. Every single time you go into a bottle.

When you have the console/logs window open, you can clearly see it is launching the exe, but it should not be because Bottles was not asked too yet.

**Comment by mirkobrombin** [comment]
What executable is trying to run?

**Comment by Githob2021** [comment]
> What executable is trying to run?

Any program listed in "programs" on the Details & Utilities tab. I checked all of my bottles and they all launch and try close the .exe right away as soon as you go into the Bottle.

**Comment by mirkobrombin** [comment]
maybe your programs are started on wine boot (on windows boot)? Bottles only start the wineserver asking for the running processes. 

Can you list the installed programs?

**Comment by Githob2021** [comment]
@mirkobrombin Unfortunately it looks like this is still an issue in flatpak 2022.1.28-trento. Every time I go into a bottle, the play button changes to stop and back to play without the user doing anything. Essentially it is launching the game every single time without user interaction.

**Comment by mirkobrombin** [comment]
This is actually a "fake status" but it is not running WINE

**Comment by Githob2021** [comment]
The problem is that it causes the user to not be able to start the bottle for a couple seconds. A lot of times I forget about this "bug" and I click the play button which has already turned into a stop button automatically.
