### ISSUE TITLE
Another idea about can't use bottles in China

### ISSUE THREAD

**Issue by lumingzh** [bottlesdevs/Bottles#935]
I saw you closed discussion，but I have a better idea.

After some research I found that bottles download index files directly from github repository, then download packaged files or installers of components/dependencies/programs through urls in index files. Correct me if I am wrong.

Here is the point, the source files in github repository are using amazon cloud which is blocked from China, but the packaged files in github RELEASE are not and the download speed is fast.

So how about release index files as packaged files in RELEASE, then make bottles download the packaged files instead of source files?

This should solve this problem and don't need much work. Thank you.

**Comment by mirkobrombin** [comment]
The repository is not just an index but an e tore archive of manifests which Bottles use to understand how to install packages. https://github.com/bottlesdevs/dependencies


Actually I’ve already fixed this by providing local repositories. Just clone all:
- https://github.com/bottlesdevs/dependencies
- https://github.com/bottlesdevs/components
- https://github.com/bottlesdevs/programs

And start bottles with these env vars:
- LOCAL_DEPENDENCIES=/path
- LOCAL_COMPONENTS=/path
- LOCAL_INSTALLERS=/path (programs repository)


So you need to keep them updated.

**Comment by lumingzh** [comment]
> The repository is not just an index but an entire archive of manifests which Bottles use to understand how to install packages. https://github.com/bottlesdevs/dependencies
> 
> Actually I’ve already fixed this by providing local repositories. Just clone all:
> 
>     * https://github.com/bottlesdevs/dependencies
> 
>     * https://github.com/bottlesdevs/components
> 
>     * https://github.com/bottlesdevs/programs
> 
> 
> And start bottles with these env vars:
> 
>     * LOCAL_DEPENDENCIES=/path
> 
>     * LOCAL_COMPONENTS=/path
> 
>     * LOCAL_INSTALLERS=/path (programs repository)
> 
> 
> So you need to keep them updated.

Well I will try that, but how about my idea? I think it's better than manually operation by users.

**Comment by mirkobrombin** [comment]
> > The repository is not just an index but an entire archive of manifests which Bottles use to understand how to install packages. https://github.com/bottlesdevs/dependencies
> > Actually I’ve already fixed this by providing local repositories. Just clone all:
> > ```
> > * https://github.com/bottlesdevs/dependencies
> > 
> > * https://github.com/bottlesdevs/components
> > 
> > * https://github.com/bottlesdevs/programs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And start bottles with these env vars:
> > ```
> > * LOCAL_DEPENDENCIES=/path
> > 
> > * LOCAL_COMPONENTS=/path
> > 
> > * LOCAL_INSTALLERS=/path (programs repository)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So you need to keep them updated.
> 
> Well I will try that, but how about my idea? I think it's better than manually operation by users.

I have to find out how to automate the process, as users will expect that Bottles handle repositories updates. I'm already working on somethings similar for repository caching, creating repositories releases and communicating with GitHub through API, so when a new release came out, Bottles will download the release and extract to keep it updated. It is very important to keep it updated, otherwise users will have huge problems if a dependency mirror change.

**Comment by lumingzh** [comment]
> > > The repository is not just an index but an entire archive of manifests which Bottles use to understand how to install packages. https://github.com/bottlesdevs/dependencies
> > > Actually I’ve already fixed this by providing local repositories. Just clone all:
> > > ```
> > > * https://github.com/bottlesdevs/dependencies
> > > 
> > > * https://github.com/bottlesdevs/components
> > > 
> > > * https://github.com/bottlesdevs/programs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And start bottles with these env vars:
> > > ```
> > > * LOCAL_DEPENDENCIES=/path
> > > 
> > > * LOCAL_COMPONENTS=/path
> > > 
> > > * LOCAL_INSTALLERS=/path (programs repository)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So you need to keep them updated.
> > 
> > 
> > Well I will try that, but how about my idea? I think it's better than manually operation by users.
> 
> I have to find out how to automate the process, as users will expect that Bottles will handle repositories updates. I'm already working on somethings similar for repository caching, creating repositories releases and communicating with GitHub through API, so when a new release came out, Bottles will download the release and extract to keep it updated. It is very important to keep it updated, otherwise users will have huge problems if a dependency mirror change.

Great! I will be waiting to try that.

**Comment by mirkobrombin** [comment]
> > > > The repository is not just an index but an entire archive of manifests which Bottles use to understand how to install packages. https://github.com/bottlesdevs/dependencies
> > > > Actually I’ve already fixed this by providing local repositories. Just clone all:
> > > > ```
> > > > * https://github.com/bottlesdevs/dependencies
> > > > 
> > > > * https://github.com/bottlesdevs/components
> > > > 
> > > > * https://github.com/bottlesdevs/programs
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > And start bottles with these env vars:
> > > > ```
> > > > * LOCAL_DEPENDENCIES=/path
> > > > 
> > > > * LOCAL_COMPONENTS=/path
> > > > 
> > > > * LOCAL_INSTALLERS=/path (programs repository)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > So you need to keep them updated.
> > > 
> > > 
> > > Well I will try that, but how about my idea? I think it's better than manually operation by users.
> > 
> > 
> > I have to find out how to automate the process, as users will expect that Bottles will handle repositories updates. I'm already working on somethings similar for repository caching, creating repositories releases and communicating with GitHub through API, so when a new release came out, Bottles will download the release and extract to keep it updated. It is very important to keep it updated, otherwise users will have huge problems if a dependency mirror change.
> 
> Great! I will be waiting to try that.

Let me know if local repositories works as idk when I will start working on repositories caching

**Comment by lumingzh** [comment]
@mirkobrombin Yes, I tested the local repository and works well. But I don't know why the download speed is slow, I download the same file like caffe-6.23-x86_64.tar.xz by firefox browser and the download speed is fast.

**Comment by mirkobrombin** [comment]
> @mirkobrombin Yes, I tested the local repository and works well. But I don't know why the download speed is slow, I download the same file like caffe-6.23-x86_64.tar.xz by firefox browser and the download speed is fast.

Dependencies came from different sources, caffe is downloaded directly from github.

Closing, I'll plan the caching feature.
