### ISSUE TITLE
[BUG] GameMode settings

### ISSUE THREAD

**Issue by thetaprimeprime** [bottlesdevs/Bottles#943]
**Describe the bug**
Gnome won't lock screen automatically when GameMode is on and any windows program is running

**Installation**
 - Method: Flatpak
 - Version 2022.1.14-trento-2

**To Reproduce**
1. Turn on 'Blank screen delay' and 'Automatic Screen Lock' in gnome setting
2. Run Bottles and turn on GameMode
3. Run some programs in Bottles
4. Screen will never get locked automatically.

**Expected behavior**
GameMode doesn't affect  'Automatic Screen Lock' functionality.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg

**Additional context**
GNOME 41

**Comment by mirkobrombin** [comment]
Gamemode prevent the screensaver, this is just its Norma behavior. We are not the gamemode developers

**Comment by Knebergish** [comment]
Hello, @thetaprimeprime 
You can configure Gamemode for yourself with your settings: [Gamemode configuration](https://github.com/FeralInteractive/gamemode#configuration). In the example settings file you can find [setting](https://github.com/FeralInteractive/gamemode/blob/master/example/gamemode.ini#L34) responsible for screensaver inhibition.

**Comment by mirkobrombin** [comment]
> Hello, @thetaprimeprime
> You can configure Gamemode for yourself with your settings: [Gamemode configuration](https://github.com/FeralInteractive/gamemode#configuration). In the example settings file you can find [setting](https://github.com/FeralInteractive/gamemode/blob/master/example/gamemode.ini#L34) responsible for screensaver inhibition.

Ya I know this but this seems like a global configuration not per bottle, should this be implemented in Bottles main configurations?

**Comment by Knebergish** [comment]
Specifically for me, there is no need for such a setting. As a last resort, I can turn Gamemode on and off in each bottle individually.

**Comment by mirkobrombin** [comment]
> Specifically for me, there is no need for such a setting. As a last resort, I can turn Gamemode on and off in each bottle individually.

I will reopen the issue to see if other users ask for this feature. Thank you for your feedback 😁

**Comment by mirkobrombin** [comment]
> > Hello, @thetaprimeprime
> > You can configure Gamemode for yourself with your settings: [Gamemode configuration](https://github.com/FeralInteractive/gamemode#configuration). In the example settings file you can find [setting](https://github.com/FeralInteractive/gamemode/blob/master/example/gamemode.ini#L34) responsible for screensaver inhibition.
> 
> Ya I know this but this seems like a global configuration not per bottle, should this be implemented in Bottles main configurations?

After some investigation I ended up that this cannot be implemented because of the quoted post. So users will still need to edit the configuration on their own.
