### ISSUE TITLE
[BUG] Renaming a program makes the whole Programs list disappear until application restart

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/Bottles#945]
**Describe the bug**
When a new program is added to the Programs list, trying to rename it results in the whole list of programs disappearing. Upon Bottles restart the list is back and the new program appears correctly renamed. Meanwhile, trying to add a new program after the list has disappeared and before Bottles is restarted results in the following error:

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 84, in add
    self.manager.update_config(
  File "/usr/share/bottles/bottles/backend/manager.py", line 832, in update_config
    f"bottle: [{config['Name']}]…"
KeyError: 'Name'
```

**Installation**
 - Method: AUR
 - Version 2022.1.14-trento-2

**To Reproduce**
1. Go to a bottle's Programs sidebar entry and add a new program to the list
2. Rename it -> the list of programs disappears
3. Try to add another program -> the above mentioned error is produced
4. Restart Bottles -> the list of programs is back and the new program is correctly renamed

**Comment by Nocifer** [comment]
Very possibly related: when a new game is added in "Programs", it _doesn't_ show up in the list of programs found in "Details and Utilities" until a Bottles restart. But if it is renamed via its "Programs" entry (and the list of programs there consequently disappears as per the original bug report) then it _does_ show up in the "Details and Utilities" list of programs and can be both launched and further manipulated (e.g. renamed again).

**Comment by Githob2021** [comment]
I've encountered this a lot of times. While I do believe this is a bug, you can click the refresh button on the Programs page. It's the looping backwards arrow at the top near the X button. This will refresh the page "Start Menu" and then the programs will appear on this page and Details & Utilities.
