### ISSUE TITLE
[BUG] An apostrophe (aka single quote) in a program's path or name breaks stuff

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/Bottles#947]
**Describe the bug**
If a program's path contains an apostrophe/single quote in its path, then launching it breaks with:

```
(11:56:45) INFO Running an executable on the bottle… 
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
```

Removing the apostrophe restores functionality.

**To Reproduce**
1. Add a game which contains an apostrophe in its path or .exe name, like e.g. Baldur's Gate.
2. Try to launch it.
3. Fail and see error.

**Comment by mirkobrombin** [comment]
Nice found

**Comment by Bananaman** [comment]
@mirkobrombin Not sure if useful, but the `printf` built-in command in shells have a `%q` mode which makes any variable safely escaped. It escapes things without "" or '' around it, by instead using backslashes around spaces and bad characters. If you can find an identical thing for python then it could be used to make a totally safe parameter that doesn't need any quoting around it.

**Comment by mirkobrombin** [comment]
> @mirkobrombin Not sure if useful here, but the `printf` built-in command in shells have a `%q` mode which makes any variable safely escaped. It escapes things without "" or '' around it, by instead using backslashes around spaces and bad characters. If you can find an identical thing for python then it could be used to make a totally safe parameter that doesn't need any quoting around it. That type of escaping would be useful since you seem to be using `sh -c "commands here"`.

Should do the trick but I can also easily escape it in python

**Comment by jroyvde** [comment]
I'm still able to reproduce this in 2022.12.14.1

**Comment by m911t** [comment]
For me on nixOS it happens with or without run in terminal being checked.
as seen in https://github.com/NixOS/nixpkgs/issues/207994

**Comment by jannuary** [comment]
@beh-10257 what version are you using?

**Comment by beh-10257** [comment]
@jannuary the latest stable flatpak version
If there is a nightly version I will try it
I don't know how though so yeah

**Comment by Perkolator** [comment]
Happening here too, but only when `Launch with Terminal` is used. Normally running the game shortcut, the game starts.

`Rock 'n' Roll Will Never Die.exe` launched with terminal:

```
wine: failed to open "/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Rock-n-Roll-Will-Never-Die/drive_c/GAMES/rock/Rock n Roll Will Never Die.exe": c0000135
```
= Apostrophes missing. Launching the game just from the shortcut it opens fine.

If I remove the apostrophes from the actual exe filename (and create new shortcut for it in Bottles), the game starts fine both ways.

Whether "dedicated sandbox" is on or off doesn't matter in this case.
