### ISSUE TITLE
[BUG] Can't Access Permission to allow access to usb drive

### ISSUE THREAD

**Issue by davelev74** [bottlesdevs/Bottles#95]
On other Distro's I was able to see usb drives with Wine programs. Where is this option in Bottles?

**Comment by mirkobrombin** [comment]
Hi thanks for your report.

Please next time follow the Bug report template providing all required informations.

Which version of Bottles are you using?

Is it the Flatpak, AppImage, AUR or what?

How can I reproduce your problem?

**Comment by davelev74** [comment]
Will do. Several other issues cropped up with Pop so I blew it away and
went back to Mint. It was freezing periodically but so did Pop tho not as
much. Mint generally worked better for me tho. thanks. I may try bottles on
Mint if it is available or try Pop again in the future. Thx
David Levinson
davelev74@gmail.com
Cell: 215.817.5198

**Comment by mirkobrombin** [comment]
Ok thanks, let me know.  @davelev74 
Please what your e-mail sign, I've removed your comment to avoid personal data leaks. <3

**Comment by davelev74** [comment]
Thanks,
I kinda like the idea of the Bottles so I tried it on Mint with the same
issue.
David Levinson
davelev74@gmail.com
Cell: 215.817.5198

**Comment by mirkobrombin** [comment]
Are you using the Flatpak or AppImage?
