### ISSUE TITLE
[BUG] Desktop entry not working at all

### ISSUE THREAD

**Issue by MichelN86** [bottlesdevs/Bottles#950]
**Describe the bug**
When adding a desktop entry and try to boot the game from shortcut nothing happens

**Expected behavior**
When clicking on the shortcut i want to run my game from it.

**Screenshots**
![Schermafdruk van 2022-01-19 15-14-36](https://user-images.githubusercontent.com/97549636/150148102-63ba0f5d-220e-4cab-b9af-a2c9dc8a04a2.png)

**Desktop (please complete the following information):**
 - OS: Pop! OS 
 - Version 21.10
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
Post the desktop entry content please

**Comment by MichelN86** [comment]
[Desktop Entry]
Name=SFC3
Exec=bottles -e 'SFC3.exe' -b 'Old Games'
Type=Application
Terminal=false
Categories=Application;
Icon=com.usebottles.bottles-program
Comment=Launch SFC3 using Bottles.
Actions=Configure;
[Desktop Action Configure]
Name=Configure in Bottles
Exec=bottles -b 'Old Games'

**Comment by mirkobrombin** [comment]
Oh there was another related issue but I’m not able to find it out. Btw easy to fix, Bottles is no setting the right path to the executable. I’ll fix this with next release, in the meantime can you try to edit the -e flag, pointing to the full executable path?

**Comment by MichelN86** [comment]
> [Desktop Entry]
> Name=SFC3
> Exec=bottles -e '/media/michel/f2e342d3-487b-4e3d-bc16-3b68b2e9ba9d/Games/Star Trek SFC3/SFC3.exe' -b 'Old Games'
> Type=Application
> Terminal=false
> Categories=Application;
> Icon=com.usebottles.bottles-program
> Comment=Launch SFC3 using Bottles.
> Actions=Configure;
> [Desktop Action Configure]
> Name=Configure in Bottles
> Exec=bottles -b 'Old Games'

Still not launching

**Comment by Bananaman** [comment]
This is not a bottles path: `/media/michel/f2e342d3-487b-4e3d-bc16-3b68b2e9ba9d/Games/Star Trek SFC3/SFC3.exe`

The bottles paths are `/path/to/your/bottles/drive_c/installation/path/game.exe`.

**Comment by MichelN86** [comment]
> This is not a bottles path: `/media/michel/f2e342d3-487b-4e3d-bc16-3b68b2e9ba9d/Games/Star Trek SFC3/SFC3.exe`
> 
> The bottles paths are `/path/to/your/bottle/drive_c/installation/path/game.exe`.
> 
> It's best if you wait for the fixed Bottles that will create proper paths though.

Yes it is my game path, i don't install my games on that path.

**Comment by mirkobrombin** [comment]
Last commit fixed the executable path. I've also tried with an external executable and it works.
