### ISSUE TITLE
[Crash report]  cabextract utility not found, 

### ISSUE THREAD

**Issue by arteymix** [bottlesdevs/Bottles#952]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.12.28-treviso

**Log**
```python3
cabextract utility not found, please install to use dependencies which need this feature
```

I suspect the dependency is missing from the RPM package on Fedora. I had it fixed by installing it manually.

**Comment by mirkobrombin** [comment]
Duplicate of #921
