### ISSUE TITLE
[BUG] Can't Find d3d12.dll when Creating New 'Application' Bottle - Throws "File or Directory Doesn't Exist" Exception

### ISSUE THREAD

**Issue by cachandlerdev** [bottlesdevs/Bottles#953]
**Describe the bug**
When I try to create a new bottle, the app throws an exception while installing VKD3D. When running from the console, the app throws a "No such file or directory" exception after failing to find `/home/cachandler/.local/share/bottles/vkd3d/vkd3d-v2.4/x86/d3d12.dll`.

**Installation**
 - Method: AUR
 - Version 2022.1.14-trento-4

**To Reproduce**
1. Open Bottles
2. Click on "New Bottle"
3. Add a name and choose the "Application" preset.
4. Try to create the bottle.

**Expected behavior**
The bottle would be created successfully, and would not look for a nonexistent dll file.

**Screenshots**
![image](https://user-images.githubusercontent.com/70250943/150266634-78178954-c5f4-423e-95ca-cbe549576389.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Display server: Xorg

**Logs**
```
(19:15:33) INFO Installing VKD3D… 
(19:15:33) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7facbdbf4e20>>
Exception: [Errno 2] No such file or directory: '/home/cachandler/.local/share/bottles/vkd3d/vkd3d-v2.4/x86/d3d12.dll' 
  File "/usr/share/bottles/bottles/utils.py", line 339, in __target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/backend/manager.py", line 1206, in create_bottle
    self.install_dll_component(config, "vkd3d", version=vkd3d_name)
  File "/usr/share/bottles/bottles/backend/manager.py", line 1394, in install_dll_component
    manager.install(config, exclude)
  File "/usr/share/bottles/bottles/backend/dll.py", line 35, in install
    self.__install_dll(config, path, dll)
  File "/usr/share/bottles/bottles/backend/dll.py", line 66, in __install_dll
    shutil.copyfile(source, target)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
```

**Additional context**
When I checked `/home/cachandler/.local/share/bottles/vkd3d/vkd3d-v2.4/x86/d3d12.dll` to see if the file existed, I found that it did not. However, `/home/cachandler/.local/share/bottles/vkd3d/vkd3d-v2.4/x32/d3d12.dll` did exist. While I may be mistaken, this seems to indicate that Bottles is mistakenly checking a nonexistent "x86" folder for the dll file, when it should be looking for a "x32" folder.

**Comment by mirkobrombin** [comment]
Hi just replace vkd3d 2.4 with 2.5
https://twitter.com/usebottles/status/1482110864572534784?s=21
