### ISSUE TITLE
[BUG] Unimplemented function POWRPROF.dll.PowerUnregisterSuspendResumeNotification

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#956]
2022.1.14-trento-4 flatpak

After I am done playing a game (Final Fantasy VII Remastered) a WINE has crashed error pops up with the following
```
wine: Call from 000000017002D620 to unimplemented function POWRPROF.dll.PowerUnregisterSuspendResumeNotification, aborting

wine: Unimplemented function POWRPROF.dll.PowerUnregisterSuspendResumeNotification called at address 000000017002D620 (thread 0160), starting debugger...
```
Followed by a thousand numbers in the debugger expanded window.

I was talking to other people who play this game and I believe this is specific to Bottles because those using Lutris do not encounter this issue.

This is not a big issue because I am able to play the game fine, it is more of an annoyance that a crash pop-up appears after I close my game every single time. Maybe it will impact some other games or programs running in the future.

This is low priority, just creating a ticket for future reference.

**Comment by mirkobrombin** [comment]
Closing as this is more WINE-related stuff then Bottles. If you want we can collaborate to make an installer, so open an issue in the programs repository.
