### ISSUE TITLE
[BUG] No access to internet

### ISSUE THREAD

**Issue by Lvaskz** [bottlesdevs/Bottles#96]
**Describe the bug**
Bottles not let me create bottles, not access to internet( ubuntu 20.04.1,)

**Installation**
 - Appimage bottle
 - Version continuos build

**To Reproduce**
1. Go to appmenu
2. Click on bottles icon
3. Bottle Windows appears with no one option to create bottle.
4. Click on the internet buttom.
5. See error pop-up window, not internet access, but I have access to internet. Flatpak version no problem in this part.

**Expected behavior**
Access to all options to create bottles

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 20.04

**Comment by mirkobrombin** [comment]
I think this problem is related to #89

**Comment by vognev** [comment]
in my case it seems due to trying to connect to 1.1.1.1:53 (TCP i guess), however the port is not available:

```
nmap -p 53 1.1.1.1                              

PORT   STATE    SERVICE
53/tcp filtered domain
```

**Comment by mirkobrombin** [comment]
> in my case it seems due to trying to connect to 1.1.1.1:53 (TCP i guess), however the port is not available:
> 
> ```
> nmap -p 53 1.1.1.1                              
> 
> PORT   STATE    SERVICE
> 53/tcp filtered domain
> ```

Can you try to change the ip to another one (like the Google one)?

You need to build from source with meson.

**Comment by vognev** [comment]
just did quick patching of `bottles-git` from AUR, changing port to 80 seems works

![image](https://user-images.githubusercontent.com/679032/104752105-ed04f700-575e-11eb-87c2-2280308eab4c.png)

**Comment by mirkobrombin** [comment]
> just did quick patching of `bottles-git` from AUR, changing port to 80 seems works
> 
> ![image](https://user-images.githubusercontent.com/679032/104752105-ed04f700-575e-11eb-87c2-2280308eab4c.png)

Thanks, I'm rolling out this update shortly.

**Comment by Lvaskz** [comment]
hi, the issue remains with the version 2.1.0.2, see

[image: botellas.png]

**Comment by Lvaskz** [comment]
![botellas](https://user-images.githubusercontent.com/29207169/104870311-c76a2000-590d-11eb-90a6-a585b87221b9.png)

**Comment by Lvaskz** [comment]
cadmiel@cadmiel-Inspiron-3442:~$ python3 -V
Python 3.8.5
cadmiel@cadmiel-Inspiron-3442:~$ apt-show-versions python3-gi
python3-gi:amd64/focal 3.36.0-1 uptodate
python3-gi:i386 not installed

**Comment by mirkobrombin** [comment]
Make sure the log is the same.
