### ISSUE TITLE
[Request] Override a bottle option per program

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/Bottles#960]
**Is your feature request related to a problem? Please describe.**
Not sure if it is a "ask for support" or a "feature request" issue.

It is possible to override a bottle option per program ? 

An example, I have three games installed inside my bottle. One of theses three games requires "gamescope" to be enabled, but not the others. If this option is only settable at the bottle level, this requires me to create an entire environment (new bottle) only for this game right ? 

**Describe the solution you'd like**
If it is not possible, so a way to adjust options (graphical ones at least) at the program level to reduce disk size taken by an entire bottle for just one option delta.

Maybe i missed a concept here.

**Comment by mirkobrombin** [comment]
Currently this feature is not here but it will be available with the arrival of the Layers (under development).
- https://github.com/bottlesdevs/Bottles/issues/510

**Comment by mirkobrombin** [comment]
Just for organization, I'm closing this issue in favor of #510 which is the best way to provide such feature.
