### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by RaafatTurki** [bottlesdevs/Bottles#964]
**Describe the bug**
bottles crashes when I launch it on my system

**Installation**
 - Method: AUR
 - Version: `bottles 2022.1.14-4` & `bottles-git 1:r2004.23f18ef-1`

**Desktop (please complete the following information):**
 - OS: Arch
 - Display server: Xorg
- Exit code: 133 

**Crash log**
```
/usr/share/bottles/bottles/dialogs/generic.py:18: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '4') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GtkSource, Gdk, Handy, Pango, WebKit2
(10:55:01) INFO Performing Bottles checks...
(10:55:01) INFO Runners found:
         - sys-wine-7.0-rc5


(10:55:01) INFO Temp path cleaned successfully!

(bottles:465129): GLib-GIO-ERROR **: 10:55:02.473: Settings schema 'com.usebottles.bottles' does not contain a key named 'night-theme'
sudo: fish: Job %s, '%s' terminated by signal %s (%s)\n: command not found
```

**Comment by mirkobrombin** [comment]
The installation failed and settings schema are broken. This is not a Bottles bug. Can you try to remove it (clean/prune the package) and install again?

**Comment by RaafatTurki** [comment]
the issue persists even after reinstalling,  a full system update and a reboot.

here are the installed versions of all 15 dependencies:
```
hicolor-icon-theme 0.17-2
dconf 0.40.0-1
python 3.10.2-1
libhandy 1.4.0-1
gtk3 1:3.24.31-1
patool 1.12-5
p7zip 1:17.04-3
python-gobject 3.42.0-3
python-requests 2.26.0-5
python-yaml 5.4.1.1-4
python-markdown 3.3.6-3
wine 7.0rc5-1
cabextract 1.9.1-2
webkit2gtk 2.34.4-1
xorg-xdpyinfo 1.3.2-3
```
and here are [all the files](https://zerobin.net/?1fedfd8fa5df0164#TebB5SbgcyDnF4Aym0Vl51VUU56bytixAyj7C8LoN0M=) that came with bottles

I should mention that I'm relatively new to bottles, it seems pretty promising and I'd love to give it a solid shot, I'll test installing it on my other arch machine later today to see if there's any difference there.

**Comment by mirkobrombin** [comment]
Unfortunately I can’t try the aur package. @francescomasala check this please.

**Comment by RaafatTurki** [comment]
I've installed the aur package on my other machine and it worked just fine, I've built it from source on my main machine and it has also worked fine.

could this be a packaging issue?

**Comment by mirkobrombin** [comment]
Do both your installations have the same desktop environment?

**Comment by RaafatTurki** [comment]
yes both are running `bspwm`

**Comment by mirkobrombin** [comment]
I'll try, in the meantime can you use the Flatpak?

**Comment by RaafatTurki** [comment]
after an another update it works just fine now, perhaps there was a dependency version misalignment due to the rolling nature of arch.

**Comment by mirkobrombin** [comment]
Nice
