### ISSUE TITLE
[BUG] Can't open portal file chooser

### ISSUE THREAD

**Issue by somerandomcloud** [bottlesdevs/Bottles#966]
**Describe the bug**
File manager doesnt open when clicking "Run Executable" in a bottle (or any other button that needs the file manager)

**Installation**
 - Method: FlatPak
 - Version: 2022.1.14-trento-4

**To Reproduce**
1. Go to a bottle
2. Click on Run Executable
3. Nothing happens, but console spews an error

**Expected behavior**
File manager to open so I could access an .exe to run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Kernel: 5.15.16_1
 - Display server: Xorg (openbox)
**Additional context**
Error:
```(bottles:2): Gtk-WARNING **: 21:50:30.765: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop```

**Comment by mirkobrombin** [comment]
Your system luck something, maybe `xdg-desktop-portal-gtk`. Btw this is not related to Bottles I think

**Comment by somerandomcloud** [comment]
Ill have a look for xdg-desktop-portal-gtk. It is sorta related to Bottles, bc flatpak is supposed to install all dependencies, no?

**Comment by somerandomcloud** [comment]
Just installed xdg-desktop-portal-gtk from the void packages repo, doesnt seem to have fixed it. I have tried everything I could think of, aka updating every package on my system, both the .AppImage and the flatpak, messing around with freedesktop. I dont think its an issue that is unrelated to Bottles

**Comment by mirkobrombin** [comment]
> Ill have a look for xdg-desktop-portal-gtk. It is sorta related to Bottles, bc flatpak is supposed to install all dependencies, no?

Not at all, we use the GtkFileChooserNative to reach the system file chooser, this assume that your system is configured correctly to "expose" this setting. Maybe other flatpaks works because they don't use the native file chooser but the Gtk one. I can confirm this is not a Bottles bug, trust me.

I see this: https://github.com/paolostivanin/OTPClient/issues/151#issuecomment-550211431 I know you are not using Solus but the issue is related.

**Comment by Githob2021** [comment]
@somerandomcloud are you also using your file picker in a flatpak? When I had Dolphin in a flatpak, that option did not work for me. It is working again when I moved back to integrated file picker. I did try and figure it out for a bit in flatseal and never got it working but I'm sure it would be a simple change either in flatseal or Bottles.

I use Arch btw.

**Comment by somerandomcloud** [comment]
I have Nemo installed via xbps, as Void Linux doesnt come with an integrated file picker... Fixed by using flatseal. 

I have no clue why it didnt have any permissions, but now it does and the file picker works. So if anyone else is having similar issues, check out flatseal

**Comment by mirkobrombin** [comment]
Nice found

**Comment by KookiesGH** [comment]
@somerandomcloud Apologies for necro, but what setting did you tick in Flatseal to get the file browser to work? I'm having the same problem, but I can't figure out what controls what I need

**Comment by somerandomcloud** [comment]
> @somerandomcloud Apologies for necro, but what setting did you tick in Flatseal to get the file browser to work? I'm having the same problem, but I can't figure out what controls what I need

Cant help you mate, I have long abandoned what I was trying to do
