### ISSUE TITLE
[Request] Enable Font Anti-Aliasing For Wine Apps

### ISSUE THREAD

**Issue by DownThePark** [bottlesdevs/Bottles#969]
**Is your feature request related to a problem? Please describe.**
I've noticed that wine applications (such as Office 2007) do have have font anti-aliasing by default.

**Describe the solution you'd like**
I would like a way for font anti-aliasing to work with my wine applications (such as Office 2007)

**Describe alternatives you've considered**
i tried using a regedit from [here](https://askubuntu.com/questions/29552/how-do-i-enable-font-anti-aliasing-in-wine) and importing it via regedit from Bottles but that didn't do anything. The fonts are still jagged-looking.

**Additional context**
Bottles Version: 2022.1.14-trento-4 (Flatpak version)
Flatpak version: 1.8.5

**Comment by mirkobrombin** [comment]
I’ll check this

**Comment by DownThePark** [comment]
After a bit of searching, it seems that it may not be possible to use anti aliasing with Office 2007 specifically, given that another person also had this issue ([source](https://askubuntu.com/questions/134542/fonts-look-bad-in-microsoft-office-using-wine)). However, other wine apps I've tested such as Notepad++ also don't appear to use anti-aliasing even after applying the above-mentioned regedit tweak either, so that regedit method doesn't work either way.

**Comment by DownThePark** [comment]
Alright! So anti-aliasing with the flatpak version of Bottles is an interesting thing. I did a clean install of Ubuntu 20.04 and also a RHEL-based distro (which was AlmaLinux 8 specifically) and installed the latest Flatpak version of Bottles in both of them and here's what I found:

- With Ubuntu 20.04, anti-aliasing worked right off the bat without doing any tweaking.
- With AlmaLinux 8/RHEL8, anti-aliasing did not work right off the bat.

Here's a screenshot showing the difference between the two, with Ubuntu being on the left and Alma being on the right:

![Wine Anti-Aliasing Comparison](https://i.imgur.com/N1RFaOd.png)

So it seems that working anti-aliasing depends on the distro being used for some odd reason.

**Comment by mirkobrombin** [comment]
Or maybe if the hardware acceleration is enabled? (just my guess)

**Comment by meisme-dev** [comment]
Is there a fix for this on RHEL based distros? I have hardware acceleration enabled so that isn't the problem.

**Comment by jul1u5** [comment]
Same issue on NixOS. Font anti-aliasing doesn't work when running through Flatpak (version 2022.8.28-brescia-2). However, it does work in the native [package](https://github.com/NixOS/nixpkgs/blob/d86a4619b7e80bddb6c01bc01a954f368c56d1df/pkgs/applications/misc/bottles/default.nix) (version 2022.5.14-trento-1).
