### ISSUE TITLE
[Crash report]  Cab file /home/rubertt/.local/share/

### ISSUE THREAD

**Issue by Rubertt12** [bottlesdevs/Bottles#971]
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2022.1.14-trento

**Log**
```python3
Cab file /home/rubertt/.local/share/bottles/temp/vcredist6/vcredist.exe not found
```

**Comment by mirkobrombin** [comment]
Already fixed in current branch
