### ISSUE TITLE
[Request] Thumbnailing support

### ISSUE THREAD

**Issue by RaafatTurki** [bottlesdevs/Bottles#972]
**Describe the solution you'd like**
It would be a real UX point to have exe thumbnailing specially for custom executables in the programs section.

The developer of `exe-thumbnailer` has deprecated it in favor of their newly created utility [icoextract](https://github.com/jlu5/icoextract) (more info on this [here](https://github.com/exe-thumbnailer/exe-thumbnailer/issues/17))

I think implementing this is going to be a breeze since it's in python and available on `pip` and the `aur`

**Comment by mirkobrombin** [comment]
I've been looking for that tool for months °-°

**Comment by mirkobrombin** [comment]
Implemented https://github.com/bottlesdevs/Bottles/commit/0e620fef0257a1eca4c708eafd559954e8ca976b
