### ISSUE TITLE
[BUG] Occasionally Bottles starts up slow/delayed which causes a distorted "blank" Bottles application window to appear until it loads

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#974]
Flatpak 2022.1.14-trento-4
Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.16-hardened1-1-hardened (64-bit)
Graphics Platform: X11

I don't like to put in tickets like this because it is not easy to reproduce and I don't even have steps to reproduce but I figured I would make one and see if anyone else has any ideas or experiences.

What happens in occasionally when I launch Bottles it takes 5-7 seconds to load. During this time a blank "Bottles" appears with just that outline that appears on my screen. This causes a visual glitch until Bottles fully loads.

I am not sure what is causing this as my computer is very powerful and the SSD is fast. My internet connection is great as well. **If I had to guess, Bottles is encountering some kind of error it is trying to self-correct before it loads. Or trying to check for dependency/news updates via Internet and is waiting for a response from the servers.**

The only error I see when launching via terminal is:
```
Failed to load module "canberra-gtk-module"
```
I know it is not this causing the delay because even when that one shows up, Bottles loads instantly.

I'm hoping other users can provide experiences or thoughts because although this is a very minor issue, it is jarring when it happens because it loads at the front of other applications and creates a blank void unless you click in the Plasma task manager to minimize it.

I use Bottles pretty much all day off and on opening and closing and I would say it happens at least 1 or 2 times a day.

**Comment by mirkobrombin** [comment]
Bottles performs a lot of checks on start up, I think this is causing the slowdown and maybe the glitch.

**Comment by Knebergish** [comment]
My Bottles startup time is usually 1-2 seconds, but yes, I also have a blank area instead of a window for the startup time. Yes, it doesn't look very nice, but it's a minor issue that doesn't disrupt the correct working of the program, although new users might be a little confused.

**Comment by mirkobrombin** [comment]
Maybe related, sometimes I see a white bottles list and need to resize the windows to show them. This seems like a gtk issue 🤔

**Comment by Knebergish** [comment]
I record my startup glitch: [BottlesStartup.gif](https://user-images.githubusercontent.com/10116459/151329038-2b0d020a-2f64-4c3b-851d-d7e3d0c5eb57.gif)

I minimize all windows, start Bottles. After starting Bottles all other windows are restored (standard Plasma behavior), but instead of the Bottles window an area with my wallpaper appears, and only after some time Bottles interface is drawn.
Apparently, when I start Bottles, an area is created to display it, but as long as the Bottles interface is not fully initialized, it displays what was on the screen when I started it.

**Comment by mirkobrombin** [comment]
And so the only blocking thing is the manager check. I’m rewriting it to make all the initial checks async and avoid problems like these.

**Comment by mirkobrombin** [comment]
Closing for #932
