### ISSUE TITLE
[BUG] bottles crashes through cli command to start executable. desktop entry hangs or crashes.

### ISSUE THREAD

**Issue by Erfboom** [bottlesdevs/Bottles#975]
**Describe the bug**
If I open up bottles and run the executable inside, the program runs. If I run bottles in the terminal (eg. bottles -e 'executable.exe' -b 'path to bottle') bottles does checks and gets stuck on "launching an executable" before crashing. I've seen it get to the wine stage but wine hangs. The desktop entry, when told to use the terminal, shows the same behavior. When I run the wine command manually to skip bottles using the prefix bottles created, the program launches no problem. When I add this command into the desktop entry and launch it, the program launches no problem.

**Installation**
I installed bottles through yay bottles in Arch. I had to build patool and load a lot of python modules before hand for this to even work. version = 2022.1.14-trento-4

**To Reproduce**
go into bottles and go to a program and create a desktop entry. go into where your desktop entries are saved DE dependent (kde here) and try to execute it. Then copy the command and paste it into a terminal and try to run it. previously, before the desktop entry bug was fixed, bottles created a desktop entry with 'NONE' in the executable path. manually putting the full path to the exe allowed it to run via cli and via the desktop entry. 

**Expected behavior**
i expected the cli command to launch the executable in the specified bottle both from the desktop entry and terminal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch
 - Version 5.16.2-arch1-1 (64bit)
 - Display server: wayland
 
**Additional context**
building bottles was a struggle and I'm not sure I did it right. i had dependency issues one after the other involving python pip and the various modules that were missing. eventually the dependencies were satisfied and it built. however, the first time I built it (by git cloning and running the install.sh script and it worked. bottles opened, created the bottle, installed the program and its dependencies, launched it, created the desktop entry and launched that. i uninstalled it through the uninstall.sh script and installed it through yay, it built, it opened and the program opens, but these issues occurred.

**Comment by Erfboom** [comment]
wanted to add some more information. I did yay -Rns bottles and deleted ~/.local/share/bottles/bottles/[name of bottle]. I then went back into yay bottles, chose the non git repo, and did a fresh build of patool and bottles. i then opened bottles and now i see this:

![image](https://user-images.githubusercontent.com/56370823/151291653-f2d93539-3184-4e19-82d6-3869e746979e.png)

and this:

![image](https://user-images.githubusercontent.com/56370823/151291709-c870b151-3fc5-4c20-bc93-e1d6c1b09f0b.png)

the icons were there upon first installing bottles yesterday, now they're not there.

However, i was able to get the command to work in terminal by not using quotes or apostrophes and escaping spaces. eg. bottles -e /home/[user]/.local/share/bottles/bottles/drive_c/Program\ Files/Scrivener3/Scrivener.exe -b Scrivener

wine was called successfully and the program opened. i then created a new desktop shortcut. this time i edited applications in kde and made a custom entry for scrivener. in the command box i pasted my terminal command. i tried with quotes, and the .desktop file wouldn't execute. i tried without quotes just like i had it in the terminal, and it opened and reopens upon closing. 

have no idea what's going on :).

**Comment by Erfboom** [comment]
well, i tried to use the .appimage and it failed with an error that's documented on here already regarding pixbuf and gtk and not being able to find icons because it's looking in /org/gtk which doesn't exist in arch. setting this variable made the .appimage happy as per another issue:

XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" ./[appimage]

however, the bottles installation i have through yay, does not care about that so the icons are still missing.

**Comment by mirkobrombin** [comment]
Can you try the flatpak? The appimage is discontinued. 

Talking about your problem with the aur package.. it’s weird 😅 it actually build Bottles from scratch like the install.sh script. If you still have the same problem with flatpak I’ll try to reproduce in a vm.

**Comment by Erfboom** [comment]
I will also try this in my vm template and I'll let you know how the flat
pack works out. The appimage is working as intended now and I'll probably
use that for now. I'll update this later tonight.

**Comment by Erfboom** [comment]
got a little bit more information here.

1. installing yay bottles in my vm that has a barebones arch install worked out of the box. note that python is 3.10 in there.
2. i cleared out anything i installed via pip previously and tried to install it via yay again, but got a build error saying meson wasn't found. i did a which meson and a where meson and a pacman command and sure enough, meson was installed.
3. i did a pip install meson command and this let the installation go through for whatever reason. however, i can't open it. it says module gi not found despite libhandy being installed and python-gobject being installed. i suspect if i do a pip install this will fix that error.

i also installed the flatpack and it opened and works just fine minus performance issues when dragging the window and font issues not displaying correctly. 

the python version on my machine is python 3.9. i would love to reset everything python related to scratch and remove all pip modules cleanly to try and see if i can build this just like the vm can. if not, i'm going to flash the vm template onto this machine so it's 1:1 and then try again, but if you have any suggestions i can try them in the meantime.

**Comment by Erfboom** [comment]
and fixed it.

it was absolutely a python issue. i had python 3.9 installed because kodi is having issues with python 3.10. so i downgraded both python and kodi. 

i removed python from /usr/lib/ and upgraded the python package. then i clean built bottles and... it found all the modules it was looking for, built right away, and installed with icons to boot.

**Comment by mirkobrombin** [comment]
So can I close? :D

**Comment by Erfboom** [comment]
probably. i think a lot of these weird problems in arch with this program are due to version mismatches with python like i had. because my python didn't match what bottles was built against, i had every arch issue i've seen in the issue list. python3.10 caused issues for a lot of people and it's not enough to just have python3.X. issues happen between 3.9 and 3.10.

other than that, program runs great! i absolutely love it and it's exactly what linux has needed in regards to wine management. there's a place for this and lutris, but i love the simplicity and the swiss army knife nature of it to accommodate games and apps. :)

**Comment by mirkobrombin** [comment]
Nice 😎
