### ISSUE TITLE
[Request] Let the user customize the color of the bottles type label (Gaming/Application/Custom)

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#977]
Flatpak 2022.1.28-trento

In the latest version, the label color for "Gaming" changed from orange/red to white. I have a lot of bottles (around 100) and using dark mode. It is harsh on the eyes to have the big white label.

I propose letting the user change the colors of labels for Gaming/Application/Custom in preferences, with a setting using hex code for colors. Maybe  this could go under "General"?

That way users who want white can use white (default?), those who want red/orange can make it red. If I want blue I can make it blue, etc.

With this, the text color inside the label would also need to change otherwise it may be ineligible.

Changing the color of the bottle names from white would also be great.

**Comment by mirkobrombin** [comment]
This automatically hit https://github.com/bottlesdevs/Bottles/issues/443

@jannuary @alvarlagerlof what about using non-status-related colors?

Like:
- Applications: https://www.color-hex.com/color/b3f2dd
- Gaming: https://www.color-hex.com/color/ffa274

Also this (https://github.com/bottlesdevs/Bottles/issues/493) should help finding user bottles.

**Comment by Githob2021** [comment]
Now that I think about it some more, it would actually be nice if we could completely hide the labels. There really is no benefit to having the label on the name of the bottle itself. It could be shown in the details tab when inside the bottle.

**Comment by jannuary** [comment]
I feel like we might just revisit displaying labels quite prominently in the first place. It isn't very useful to the end user, not to mention we don't exactly do a good job explaining what is quantifiably different between "Gaming" and "Application" (weird wording as well, much prefered "Software" myself)

**Comment by mirkobrombin** [comment]
Search in bottles list implemented. We will consider other improvements in the future.
