### ISSUE TITLE
[BUG] Bottles doesn't show up when open. 

### ISSUE THREAD

**Issue by thanhminhmr** [bottlesdevs/Bottles#981]
**Describe the bug**
The flatpak version of bottles doesn't show GUI when running.
```htop``` do list bottle processes, but all of them were idling.
![image](https://user-images.githubusercontent.com/31412085/151531679-65c4f81d-536d-4f73-a30d-70e4a98e6999.png)
Tried starting bottles by running command from terminal ```flatpak run com.usebottles.bottles```, or by clicking on the icon from ArcMenu result are the same.

**Installation**
 - Method: flatpak
 - Version: 2022.1.28-trento (obtained from ```flatpak list```)

**To Reproduce**
1. Run Bottles
2. See nothing

**Expected behavior**
Bottles GUI show up.

**Screenshots**
The console output.
![image](https://user-images.githubusercontent.com/31412085/151532047-61a3d1dc-5d9e-4147-80bd-9c8c20222cf0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.3 LTS
 - Display server: Xorg

**Additional context**
Currently none.

**Comment by mirkobrombin** [comment]
Does the older version still has this problem?

**Comment by thanhminhmr** [comment]
UPDATE:
I completely nuke Bottles ```flatpak remove com.usebottles.bottles --delete-data``` and then reinstall.
Now the taskbar icon show up but still no GUI when switch to it, only this.
![image](https://user-images.githubusercontent.com/31412085/151533704-e5d5d556-c198-4a44-8f3f-9b0fc36c06da.png)

Running Bottles using terminal show up this warning (from Ubuntu I guess).
![image](https://user-images.githubusercontent.com/31412085/151534060-3e296b1f-1198-4499-a301-413e8491f914.png)
![image](https://user-images.githubusercontent.com/31412085/151534136-0f2ce005-f574-4406-af81-5ca804a5082d.png)

**Comment by thanhminhmr** [comment]
> Does the older version has this problem?

I don't know when the last update happens so I'm not sure. But a week (?) ago when I first install it, it works fine and I even manage to run some Windows apps already.

**Comment by thanhminhmr** [comment]
Maybe #974 is related? I'll let it run for a while to see if it gonna shows up or not.

**Comment by mirkobrombin** [comment]
Ya I think it's related. I'll investigate, thanks for reporting

**Comment by mirkobrombin** [comment]
Can you do a speedtest?

**Comment by thanhminhmr** [comment]
You mean this speedtest?
![image](https://user-images.githubusercontent.com/31412085/151555108-6fce001a-fa45-4d5f-a09d-3ccb2f2e380c.png)

**Comment by thanhminhmr** [comment]
You mean this speedtest?
![image](https://user-images.githubusercontent.com/31412085/151555466-ff7fd26a-c10a-4b2a-947b-8d9bbc924c89.png)
Note that this is not international internet speed. If I download something from a server outside my country, the speed drop to about 1MB/s.

**Comment by mirkobrombin** [comment]
Bottles only downloads the repositories index which are a few kb, I can exclude a connection problem. I’ll investigate

**Comment by francescomasala** [comment]
> The app took 1 hour to start, this screenshot maybe helpful. ![image](https://user-images.githubusercontent.com/31412085/151543503-fd38ce84-1afa-458b-8138-1186669e4fb7.png)

Maybe https://github.com/bottlesdevs/Bottles/pull/1012 fixes it, i had the same problem on arch linux and now it's fixed

**Comment by mirkobrombin** [comment]
Shoud I distribute an hotfix? :S

**Comment by thanhminhmr** [comment]
> Should I distribute an hotfix? :S

I think yes, because this bug completely break the app for some people. If someone have something important in their Bottle, they'd be unable to access it since last update, and that is definitely not good.

**Comment by mirkobrombin** [comment]
4th hotfix coming :D
