### ISSUE TITLE
[BUG] Changing the DXVK version results in the backup .bck files getting removed, which then makes it impossible to deactivate DXVK without breaking the prefix.

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/Bottles#991]
**Description & Steps To Reproduce**
* Create a new Wine prefix via Bottles.
* Enable DXVK, either manually or automatically (via choosing the "Gaming" type for the prefix).
* Observe how there is a d3d*.dll.bck file for every d3d*.dll file replaced by DXVK in system32 and syswow64.
* Go to the prefix's preferences and change the DXVK version.
* Observe how the .bck files get deleted.
* Go to the prefix's preferences and disable DXVK completely.
* Observe how there are now no d3d*.dll files at all to be found in system32/syswow64, because the .dll files got removed but there were not .bck backups to be restored in their place.
* The prefix is now broken.

**Expected behavior**
The .bck files should remain untouched and always available to be restored whenever DXVK is disabled.

**Installation**
Method: AUR
Version: 2022.1.28-trento

**Additional context**
The terminal output does not give me any useful hints as to what could be responsible behind the scenes.

**Comment by mirkobrombin** [comment]
Uoops :eyes:
