### ISSUE TITLE
[BUG] After installing bottles on Manjaro KDE i have updates in pamac that are stuck and wont complete or clear

### ISSUE THREAD

**Issue by rider1611** [bottlesdevs/Bottles#996]
**Describe the bug**
flatpak packages related to bottles are stuck in pamac updates and will not update, clear or uninstall.

**Installation**
 - Method: flatpak
 - Version 2022.1.28-trento

**To Reproduce**
1. On Manjaro KDE Plasma, using pamac install the flatpak of Bottles
2. After the next update, related flatpak packages will be stuck in updates and never go away

**Expected behavior**
I should not have flatpak updates stuck in my pamac updates tab that wont go away

**Screenshots**
![image](https://user-images.githubusercontent.com/98710596/151714571-18e3b920-52bd-43a6-ae2d-9dade136bfe4.png)
![image](https://user-images.githubusercontent.com/98710596/151714711-6af3d4be-087c-4050-9adf-041744387fbb.png)

**Desktop:**
 - OS: Manjaro KDE Plasma
 - Unstable branch
 - Display server: Xorg

**Comment by mirkobrombin** [comment]
You should ask this to the panache developers 😅

**Comment by Knebergish** [comment]
Hello, @rider1611. Your problem can be related to the this issue: [New Flatpak runtime updates available out of nowhere](https://forum.manjaro.org/t/new-flatpak-runtime-updates-available-out-of-nowhere/100333)
Try execute in the terminal:
`flatpak uninstall --unused`
After that try update Bottles via Pamac again.

**Comment by rider1611** [comment]
![image](https://user-images.githubusercontent.com/98710596/151805049-5706d856-0a21-4494-98b4-2f762cea9392.png)

**Comment by Knebergish** [comment]
Sorry, in my case it helped.
Try to read this topic in full, several other solutions were mentioned there: for some users, the update was completed successfully after 2-3 attempts, some used the Bauh utility.
Unfortunately, I have no other ideas. If all these methods do not help you, write about it in the aforementioned Manjaro topic, perhaps someone will suggest some other options.

**Comment by rider1611** [comment]
I fixed the issue for the record, in case anyone searches and finds this.. I had to install Bauh which is an AUR package that updates packages, after updating what Bauh recommended it fixed the problem. After this my updates are all cleared and everything seems normal.
