### ISSUE TITLE
[Request] Use XDG_DATA_HOME spec fully

### ISSUE THREAD

**Issue by nanonyme** [bottlesdevs/Bottles#997]
**Is your feature request related to a problem? Please describe.**
Currently this project is hardcoding flatpak directories. This is not necessary when XDG spec is followed and destinations are read from environment variables

**Describe the solution you'd like**
Have uniform path handling solution that works everywhere same way

**Comment by mirkobrombin** [comment]
There was another issue about this but never scheduled a fix
