### ISSUE TITLE
[BUG]  Crash when making main window

### ISSUE THREAD

**Issue by M4r5ha11** [bottlesdevs/Bottles#999]
**Describe the bug**
Crash when making main window

**Installation**
 - Flatpak
 - Version: ? (dropdown menus are not work)

**To Reproduce**
1. Run Bottles
2. Check the console
3. End

**Screenshots**
![_2022-01-31_09-16-55](https://user-images.githubusercontent.com/68496774/151754164-3f8985ba-ebac-4ab5-91d3-1d05b3abe5ae.png)

![_2022-01-31_09-37-39](https://user-images.githubusercontent.com/68496774/151755240-e51aed80-6d83-4197-a410-7be89de6cb6f.png)

**Desktop:**
 - OS: Debian
 - Version: 11
 - Display server: Wayland (LXQt)

**Comment by mirkobrombin** [comment]
Apparently you have a broken bottle that is causing the issue. 

Can you check in ~/.var/app/com.usebottles.bottles/data/bottles/bottles if there are bottles without the bottle.yml or without the Paraneters key in the bottle.yml?

**Comment by M4r5ha11** [comment]
bottle.yml exist. I'm running with `flatpak run com.usebottles.bottles`

**Comment by M4r5ha11** [comment]
![_2022-01-3](https://user-images.githubusercontent.com/68496774/151758970-4a8c192a-1057-4bf9-ae51-722162737114.png)
hm

**Comment by mirkobrombin** [comment]
Can you share the bottle.yml?
